### ISSUE TITLE
Accessibility issue for Modal and fix FocusLock (Micro Request?)

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1013]
This is borrowed from the Flexion refactoring backlog. We could possibly call on 18F phone-a-friend to assist. The issue was surrounding hitting escape while a modal is open. 

> Title: Fix FocusLock component this.restoreFocus()
> Restoring focus back to the main page when modals close was causing problems when exiting Add Practitioner modals and scrolling to the success notification at the top.

@kkoskelin could be a resource as he logged the original ticket in the backlog.

**Comment by adunkman** [comment]
Asked around a bit, and the consensus is that focus should be returned to the item which spawned the modal (for example, the button clicked which caused the modal to appear). 

I also got a plug for the new [USWDS modal component](https://designsystem.digital.gov/components/modal/) which implements that focus flow.

**Comment by JessicaMarine** [comment]
Moved to Flexion: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8108
