### ISSUE TITLE
Upgrade Elasticsearch Cluster for Kibana

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1167]
So that we can automate the rotation and rollup of logs indexed into Kibana.

Targeting 7.9 or 7.10.

This would be the terraform that for indexing logs to elasticsearch.

**Comment by mark-meyer** [comment]
A question I had regarding this was: does Terraform correctly update Elasticsearch clusters in-place? AWS has included this feature via the console for a [while now](https://aws.amazon.com/about-aws/whats-new/2018/08/amazon_elasticsearch_service_now_supports_zero_downtime_in-place_version_upgrades/), but I wasn't certain if simply bumping the `elasticsearch_version` number in Terraform would follow an upgrade path or just create a new cluster.

It looks like the answer is that it will upgrade in-place if it can as of [version 1.55.0 of the AWS provider](https://github.com/hashicorp/terraform-provider-aws/issues/5554), which was over [two years ago](https://github.com/hashicorp/terraform-provider-aws/blob/release/2.x/CHANGELOG.md#1550-january-10-2019). This should make it fairly trivial to upgrade the cluster to the latest version.

**Comment by mmarcotte** [comment]
I believe Flexion is doing this in another ticket. Will follow up and close...

**Comment by mmarcotte** [comment]
Looks like [Batch 7](https://github.com/ustaxcourt/ef-cms/pull/1568/files) achieves this!
