### ISSUE TITLE
Petitioner: Login/Authentication to Prod environment (Test Run)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#139]
As a Petitioner, in order to access the online filing system, I need to log in to the Court's production environment.

After registering for an account, Petitioner is able to log into the system with their username and password.

## Acceptance Criteria
* Petitioner registers acct in new production environment [Note: Want to test this with as many domains as practicable; but especially hotmail]
* Petitioner can log in

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by vickimcfadden** [comment]
Blocked by [#6600](https://github.com/flexion/ef-cms/issues/6600) in Flexion backlog.

**Comment by mmarcotte** [comment]
Cannot create a new account in our Staging environment
> An error was encountered with the requested page.

Trying to figure out what happened.

**Comment by mmarcotte** [comment]
Was able to get it working in Staging.

However, as this ticket pertains to the Production environment, I'm marking it as Blocked until we can perform a production deploy while Pen Testing is occurring. Will coordinate with the Pen Testing team to identify a window.
