### ISSUE TITLE
Capture error messages handled on AWS for Court's environments and route them 

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#141]
Capture error messages handled on AWS and route them to where they need to go
This is for court's environments

**Comment by waldoj** [comment]
At present, _anything_ in the EF-CMS that is sent to the terminal (as an error — `STDERR` — or as a general status message — `STDOUT`) is recorded in CloudWatch. Those logs are retained for a period of just one week.

**Comment by adunkman** [comment]
Replaced by https://github.com/ustaxcourt/ef-cms/issues/317.
