### ISSUE TITLE
Training for new users

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#144]
* Training plan created: https://docs.google.com/spreadsheets/d/1GRLxRUVTQble0I4Lm5LEaPWdYKeZWUCK8_426KJTJ6s/edit?usp=sharing
* Trainers identified (see above)
* Training materials created: https://docs.google.com/spreadsheets/d/1fg1Gt4Jzz0y_FvZLW0lVvT6Y-7OcfLPldTyejsm958Y/edit?usp=sharing
* Training dates scheduled: https://docs.google.com/spreadsheets/d/1KjKSpIM2plYzuT6jRgw9isTp4DJvi9FZiedq7wizQFY/edit?usp=sharing
* ~~Training location determined and scheduled~~
* Trainees identified and scheduled (To be determined by trainers)
* Identify all of the areas where there are work arounds and ensure that users have the information necessary. See MVP review doc for some of the work around ideas
    * Create content (written or videos) that public users can reference for submitting a case and creating a petition
    * Ensure that the Court's OIS staff is trained on system
    * Ensure the court is trained on helpdesk process and triaging common system issues

**Comment by vickimcfadden** [comment]
Following [training schedule](https://docs.google.com/spreadsheets/d/1KjKSpIM2plYzuT6jRgw9isTp4DJvi9FZiedq7wizQFY/edit#gid=0) the training will be completed Oct 15 and the lunch and learns (first round of these) will go until Nov 24.

**Comment by vickimcfadden** [comment]
Training completed, lunch and learns will continue through 11/24.
