### ISSUE TITLE
Public domain is set up

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#145]
* Court wants to use https://dawson.ustaxcourt.gov for production
* Public domain is set up
* Court's site points to the new domain

**Comment by waldoj** [comment]
This will also require figuring out what that domain should be — fundamentally a UX question. The anti-pattern is using either a project name (meaningless to the public) or the technical acronym like "ef-cms" (likewise meaningless to the public). The question is what term _is_ meaningful to the public. Perhaps something as simple as `cases.ustaxcourt.gov`? I'm not sure.

**Comment by adunkman** [comment]
The Court’s production domain now points to the production AWS account’s hosted zone. The application is not yet deployed in that location. Given that we have additional issues tracking DNS setup (#245) and overall environment setup (#256), I’m going to mark this one completed.

**Comment by adunkman** [comment]
Additionally, #235 tracks updating references to this URL, which will happen during hard launch.
