### ISSUE TITLE
Onboard Tenille Lenard

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1485]
Welcome to the team! 🎉 😎

#### Access to tools

- [x] GitHub — speak with your team lead to determine the appropriate repositories and levels of access in the [ustaxcourt](https://github.com/ustaxcourt) and [flexion](https://github.com/flexion) organizations.
- [x] [Slack](https://ustaxcourt.slack.com) — look for important channels to join in [How We Work](./how-we-work.md).
- [x] Zoom — speak with your team lead to get access to Zoom if you will be hosting meetings.
- [x] Zendesk — get access only if you will be providing customer support.
- [x] Trello — used for some backlogs (see the [README](../README.md)). Work with your team lead to gain access.
- [x] Get Tenille access to Statuspage

#### Access to application data

- [x] Get access to AWS accounts through AWS Organizations.
- [x] Configure access to relevant DAWSON environments through Cognito.
- [x] Configure Kibana logging access through Cognito.

#### Install relevant tools

- [x] Zoom and Slack desktop clients (recommended).
- [x] ZenHub [browser extension](https://www.zenhub.com/extension) (used to view backlogs).
- [x] If you will be running or developing on the application locally, follow the setup steps in the [README](../README.md).
- [ ] Download [TextExpander](https://textexpander.com/download) and get an account

#### Optional tasks

- [x] Join any of the [Digital.gov Communities of Practice](https://digital.gov/communities/) email lists which may be beneficial to your role. These are communities used to collaborate and share resources with others across government.

**Comment by ttlenard** [comment]
*Note: The README links above don't seem to be working.

**Comment by ttlenard** [comment]
Update as of 7/30/21

- I have a Zoom account

Open requests to Mike MicVicker include:
- Slack Desktop Client 
- TextExpander
- Visual Studio Code
- Google Suite (then I can get the ZenHub browser extension)

**Comment by mmarcotte** [comment]
* List given to McVicker. He's picking them off; hopefully TextExpander
* Truong is actively helping Tenille get AWS access.

**Comment by mmarcotte** [comment]
Truong gave AWS access to Tenille, but it's very limited and without required permissions. Mike to get with Truong to resolve.
