### ISSUE TITLE
Draft up a response to users making feature requests

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1563]
Can we please draft up a snippet to respond and mark as solved any feature requests? And then in the handoff forward the request to Product Owner.

**Comment by mmarcotte** [comment]
Gave @ttlenard access to update the snippet groups (and thus the snippets therein)

FYI Jen Siegel should have access to update all of these, too.

**Comment by ttlenard** [comment]
We do have this one in Text Expander: 

Thanks for getting in touch with DAWSON Support.  We’re always looking to hear how we can better meet your needs, and although we don’t publicly comment on our roadmap of features, we regularly use feedback like this to help ensure we’re on track and make adjustments.

Did we want to edit this existing snippet?

**Comment by mmarcotte** [comment]
We are going to use the `;soon` snippet for this, thanks Tenille!
