### ISSUE TITLE
Soften language for Textexpander snippet for `;resetFailed`

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1564]
Can we please soften the language in the snippet for people who are trying to reset their password, but are using the wrong case of their email (`Should.Be.All.Lower.Case@example.com` versus `should.be.all.lower.case@example.com`)

Here's the current language:

> Hello,
> 
> You are receiving this error because you are not using the correct case for your Email Address while attempting to reset your password. The system is case-sensitive. Please enter your Email Address exactly as you see it below:
> 
> {{email field}}

Really we are mostly confident that this is the reason why they are encountering the error below. We're just not 100% positive that's the only thing that would cause this error.

![error-changing-password.png](https://images.zenhubusercontent.com/5f172596f365e24f3ab7b0c3/eb3cfa61-f1f0-48c9-b86a-23b724c60337)

**Comment by mmarcotte** [comment]
Gave @ttlenard access to update the snippet groups (and thus the snippets therein)

**Comment by ttlenard** [comment]
Updated language to this: 

Thank you for contacting DAWSON Support. Please note that the email address is case sensitive, so please be sure to enter your Email Address exactly as you see it below:

%filltext:name=Email Address:width=40%

If you do not recall your password, you should be able to reset it by following these instructions: 

1. Go to https://dawson.ustaxcourt.gov
2. Click on "Log-in" in the upper right corner
3. Click the "Forgot your password?" link
4. Type in your email into the box (this is case sensitive!), and click the "Reset my password" button.
5. You will receive an email with a code to confirm your identity.
6. Enter that code into the box provided on the page where you just clicked "Reset my password", and you specify your new password. 

If you continue to experience problems accessing DAWSON, please email again with additional information, including a screenshot if possible.

**Comment by mmarcotte** [comment]
worked great, thanks Tenille!
