### ISSUE TITLE
Onboard DevOps Engineer Jerome Emilo

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1610]
Welcome to the team! 🎉 😎

#### Access to tools

- [ ] GitHub — speak with @mmarcotte to determine the appropriate repositories and levels of access in the [ustaxcourt](https://github.com/ustaxcourt) and @mariahkannenberg for [flexion](https://github.com/flexion) organizations.
- [ ] [Slack](https://ustaxcourt.slack.com) — look for important channels to join in [How We Work](https://github.com/ustaxcourt/ef-cms/blob/staging/docs/how-we-work.md).
- [ ] Zoom — speak with your team lead to get access to Zoom if you will be hosting meetings.
- [ ] Zendesk — get access only if you will be providing customer support.
- [ ] Trello — used for some backlogs (see the [README](https://github.com/ustaxcourt/ef-cms/blob/staging/README.md)). Work with your team lead to gain access.

#### Access to application data

- [ ] Get access to AWS accounts through AWS Organizations.
- [ ] Configure access to relevant DAWSON environments through Cognito.
- [ ] Configure Kibana logging access through Cognito.

#### Install relevant tools

- [ ] Zoom and Slack desktop clients (recommended).
- [ ] ZenHub [browser extension](https://www.zenhub.com/extension) (used to view backlogs).
- [ ] If you will be running or developing on the application locally, follow the setup steps in the [README](https://github.com/ustaxcourt/ef-cms/blob/staging/README.md).
- [ ] [tfswitch](https://tfswitch.warrensbox.com/) to switch terraform versions (you may already have another piece of software for that)

#### Bookmark relevant pages

- [ ] Retrium
- [ ] PlanningPoker
- [ ] Flexion Zoom Rooms
- [ ] TOTP Generator
- [ ] Kibana login pages
    - [ ] Prod
    - [ ] Staging

#### Organizational Things

- [ ] Get added to relevant meetings (who manages it)
    - [ ] Twice-a-Week 18F Sync (18f)
    - [ ] Weekly Engineering 18F Sync (18f)
    - [ ] Morning Standup (flexion)
    - [ ] Bi-weekly backlog grooming (flexion)
    - [ ] Scrum ceremonies (flexion)
    - [ ] Bi-weekly Grooming/Planning 18F/USTC (18F)
    - [ ] Bi-weekly Grooming/Planning Flexion (Flexion)
    - [ ] Twice-a-Week USTC Stakeholder Check-In (Jessica)

#### Optional tasks

- [ ] Join any of the [Digital.gov Communities of Practice](https://digital.gov/communities/) email lists which may be beneficial to your role. These are communities used to collaborate and share resources with others across government.
- [ ] possible Terraform tour from @adunkman or @codyseibert

**Comment by mmarcotte** [comment]
Not going to happen...

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
