### ISSUE TITLE
Pen Testing: Found API key

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#1647]
The Court engaged a third-party (NSSPlus) to perform penetration testing and  a vulnerability assessment of DAWSON.  NSSPlus reported an informational item relating to Found API Key.  NSSPlus' findings and recommendations are included in Notes below.

## Acceptance Criteria:
* Remediate issue found by NSSPlus re: Found API Key

## Notes:
* See section 7.2 of this report for NSSPlus' findings and recommendations re: Found API Key: 
[https://app.zenhub.com/files/152320868/622ca15d-173e-49d3-80eb-c50f7d9024d1/download](https://app.zenhub.com/files/152320868/622ca15d-173e-49d3-80eb-c50f7d9024d1/download)

**Comment by mmarcotte** [comment]
API key found within the git history is no longer valid, nor are we utilizing that service. This is not a security risk.
