### ISSUE TITLE
BUG: Printable Docket Record Button is showing for New Cases when logged in

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1675]
**Describe the Bug**

The printable docket record button is still showing for New Cases when the user is logged in. Because it is relying on `status`, being not new and we are not passing along `status` to the Public Case, it gets it wrong for cases that the user is not associated.

Related to:
https://github.com/flexion/ef-cms/issues/8280 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

Any

**Who were you logged in as?**

IRS Practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Fixing https://github.com/flexion/ef-cms/issues/8952

**To Reproduce**

1. Login as an IRS Practitioner
2. Navigate to a Case that hasn't had the petition served (New)
3. See the Printable Docket Record button

**Expected Behavior**

The Printable Docket Record button should not be visible for New cases.

**Actual Behavior**

The printable Docket Record button is visible for New cases

**Screenshots**

<img width="1807" alt="Screen Shot 2021-09-28 at 3 27 46 PM" src="https://user-images.githubusercontent.com/5023502/135153026-f3468709-e640-49fb-a707-a5e45aa06d00.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
I tested this by logging in as an IRS practitioner and going to the following cases: 23150-21, 23145-21. I do not see the printable docket record link.  

I did go to one of my active cases as an IRS practitioner1 (23154-21), and I do not see the printable docket record link on that one either. @mmarcotte - Should I see the link on one of my active cases???

**Comment by ttlenard** [comment]
Tenille to test with other users besides IRS practitioner.

**Comment by ttlenard** [comment]
@mmarcotte I tested with the following roles and it looks great for all the user types! Thank you!  I'd say this is ready to be merged!

IRS practitioner
Private Practitioner
Petitioner
Docket Clerk
Petitions Clerk
Admissions Clerk

I think this is good. It seems it is the most important for the first 3 users in the list above?
