### ISSUE TITLE
BUG: Parties cannot file documents on cases closed for more than 6 months

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1706]
**Describe the Bug**

It appears that https://github.com/flexion/ef-cms/issues/8952 has introduced another bug. Parties to a case can no longer file and serve documents on a case if the case has been closed for more than 6 months. 

**Business Impact/Reason for Severity**

It's vital for parties to a case to be able to file documents on a case even if the case has been closed longer than 6 months

**In which environment did you see this bug?**

`test`

**Who were you logged in as?**

Users:

* 4ebb8e80-4fea-46ea-9401-904b03660849 (IRS Practitioner)
* 5c0573d4-1af0-4afa-b6a0-287988c80a27 (Private Practitioner)

on case 16715-19

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Check to see if this was an issue

**To Reproduce**

1. Become user `4ebb8e80-4fea-46ea-9401-904b03660849`
2. Navigate to 16715-19
3. See notice that you cannot file a document until the petition has been served

**Expected Behavior**

You should be able to file a document.

**Actual Behavior**

You receive a notice 

> You will be able to file documents after the Petition is processed.

And you cannot file documents

**Screenshots**

<img width="1807" alt="Screen Shot 2021-10-01 at 5 08 13 PM" src="https://user-images.githubusercontent.com/5023502/135686355-0d9f68ec-1d76-4e10-829a-608b395c4e8e.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
This only applies to the automated notices. If the case has been closed for more than six months, regardless of WHO changes the information, not automatic notices should be generated. 

They should still be able to file documents and change this information.

Everything else should continue to work as expected.

**Comment by mmarcotte** [comment]
Tenille adding coverage to test matrix for these scenarios ☝️

**Comment by ttlenard** [comment]
This looks good.  I went through a variety of test scenarios.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5aa2fb35-1303-4b51-8765-c984d31cbb45)
