### ISSUE TITLE
BUG: The "How to merge PDF documents" does not appear to be 508 compliant

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#1806]
**Describe the Bug**
As a petitioner, when I open the "Learn more about how to merge files into one PDF" link https://app.test.ef-cms.ustaxcourt.gov/aecece6938ab09496720.pdf, a help document opens and it appears that this document is not 508 compliant. I used the default narrator app that is installed on my court issued laptop, as well as Edges "read aloud" functionality on the PDF that opens, and some of the content is not getting recognized with these tools.

It appears that the help document has steps 1 and 2 as screen grabs, but these steps are not numbered, there is no alt text available on these two screen grabs, and there is no written instructions to accompany the screen grabs. Screen readers do not recognize the screen grabs and they skip over these.

The first numbered step in the document is #3. Number 1 and number 2 steps are not identified in the document.

There are additional screen grabs in the document that do not have alt text or associated text to help explain what the screen grab is showing.
**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Log in as a petitioner or Private Practitioner
Click on start a case
Under the Accordion Menu that has the instructions for creating a case, click on Prepare the petition
Click on link for the "Learn more about how to merge files into one PDF"
Open a screen reader tool and notice that it doesn't recognize the screen grabs that are in this document.

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

The screen reader tools skip some screen grabs

Screenshots
image.png
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/a03110be-3f7f-4304-97dc-657ad0ad4fb0)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
1 - Tenille will update the document.
2 - Mike or Jim can replace the updated 508 compliant document that is in S3?  Is this correct?

**Comment by ttlenard** [comment]
This is the updated PDF that now passes accessibility checks. "How to Merge PDF Documents"
[https://app.zenhub.com/files/148831192/f65081a4-74dd-4bd5-baff-1ff5fd32cacf/download](https://app.zenhub.com/files/148831192/f65081a4-74dd-4bd5-baff-1ff5fd32cacf/download)

**Comment by mmarcotte** [comment]
Nice, once you have the updated PDF we can help bring it into the codebase.

**Comment by ttlenard** [comment]
There was also this document that I found that seems to be in the same boat as the other?  ![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cfad5bea-6d26-4284-bd29-da2a4a1c94cf)

Here is the link from MIG: https://app.mig.ef-cms.ustaxcourt.gov/e33b1fc56596bd91a37b.pdf

Here is the updated PDF that passes accessibility checks: [https://app.zenhub.com/files/148831192/7b80c9c3-5ebe-4d0d-93c3-e26b47239851/download](https://app.zenhub.com/files/148831192/7b80c9c3-5ebe-4d0d-93c3-e26b47239851/download)

**Comment by ttlenard** [comment]
@mmarcotte See above 2 comments.  I fixed two documents today that were linked in DAWSON.  These both now pass Accessibility checks.  Let me know if you have questions.

**Comment by ttlenard** [comment]
@mmarcotte and @jimlerza - Jen just provided some additional edits that she would like to the "How to create a case" PDF.  Just checking in on the status of this ticket, as I am hoping we can use the document that Jen updated instead of the one that I have linked above.  It is here: [https://app.zenhub.com/files/148831192/1cab006d-3bcc-4b72-b6e8-254d2ed95cf0/download](https://app.zenhub.com/files/148831192/1cab006d-3bcc-4b72-b6e8-254d2ed95cf0/download)

**Comment by mmarcotte** [comment]
Cool, @ttlenard -- seems like we are good to go with this with that PDF that you linked. 

I think it would be better to store this PDF on our web site and then simply update the hyperlink in our codebase. This will give us more control for the next time it needs to change. I'm going to get with Scott Goodrick, as I think he helps manage those files.
