### ISSUE TITLE
Determine a strategy for user management in Cognito pools.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#226]
## Petitioners

- **Data import:** As the Court, in order to make sure that the legacy data with respect to more than two petitioners is not lost, we need a way to allow information for more than two petitioners to be migrated (where applicable). https://github.com/flexion/ef-cms/issues/5430
- **Flag users that will need to log in:** As a project team, in order to know which petitioners need access to the new system, Flexion needs the ability to identify which petitioners have eAccess to the Court's current system. https://github.com/flexion/ef-cms/issues/5508
- **Allow users to login:** As a petitioner who has open cases in the current CMS and e-Access, I need the ability to log in to the new CMS and see my open cases. https://github.com/flexion/ef-cms/issues/5159

Already completed tasks: 

- New petitioners can self-register for an account.

Shelved questions: 

- How do petitioners who paper-file or (petitioners with open cases without e-Access) who later want e-Access get granted access to their case?
    - May be the same solution as https://github.com/flexion/ef-cms/issues/5159; will be re-addressed when picking up that story. 

Notes: 

- Nothing needs to be done for legacy petitioners who don’t have e-Access in the old CMS or only have closed cases. Their data should be visible in EF-CMS, but they will not be able to log in. 

## Practitioners

- **Add bar numbers to practitioners**: As the Court, in order to make sure our legacy practitioners get associated with the right cases, we need the data migration team to be able to transmit the bar nos. of the practitioners on each case as part of that case. https://github.com/flexion/ef-cms/issues/5594
- **Link practitioners to cases via their bar numbers**: As a practitioner (petitioner’s attorney or IRS attorney) who has cases in the current CMS, I need the ability to log in to the new CMS and see all cases that I’m associated with, including both open and closed cases. https://github.com/flexion/ef-cms/issues/5595
- **Remove practitioners:** As an Admissions Clerk, so that I may remove an inactive attorney from a case and limit their access to the system, I need the ability to change the attorney's status. https://github.com/flexion/ef-cms/issues/4652

Already completed tasks:

- Practitioners can be imported and granted user accounts via CSV import.
- Practitioners can be added.

## Court employees

- As the Court, in order to keep up with employee turnover, we need the ability to manage users in the system. https://github.com/flexion/ef-cms/issues/4386
- As the Court’s Tech Lead, I need the ability to bulk load existing court users into the system, so I can ensure that they have access. [Script (already built) versus user interface?]
- As the Court’s Tech Lead, I need the ability to add and remove court users into the system, so I can ensure that the proper employees have access. [Script versus user interface?]
- As the Court’s Tech Lead, I need the ability to change a court user’s role in the system, so I can ensure that they have access to the right functionalities. [Script versus user interface?]

## Developers

- As a developer updating EF-CMS in production, I need to be confident that the new version is working. https://github.com/ustaxcourt/ef-cms/issues/250
- As the Court, in order to maintain a secure system which does not disclose private information, I need to be sure that hardcoded user accounts with well-known passwords are not present.
    - How can users continue to be well-known for development environments to enable developers to fully test all user roles?

**Comment by JessicaMarine** [comment]
> How will the court create and delete users for their staff, such that the appropriate access is granted and removed when employees join and leave the court?

We currently have an issue in Flexion's backlog for this: https://github.com/flexion/ef-cms/issues/4386

**Comment by JessicaMarine** [comment]
> Given the delay to deployment and cutovers, is there time to setup integration with Court AD for court personnel?

I don't think this was ever a timing issue; it was a resource issue.  Does the Court have someone who can do this?

> At least Court personnel would have access for testing and training without having to hardcode user accounts.

This has already been done, so the additional lift, if any, would be going with another approach.

**Comment by adunkman** [comment]
Related item: https://github.com/flexion/ef-cms/issues/5159 (managing migrated users — if they have logins or another approach).

**Comment by adunkman** [comment]
This is also related to two items on Flexion’s DevEx backlog related:

- [Addressing the Setup User Scripts](https://trello.com/c/ZIstzI8L/576-setup-user-scripts-high)
- [Addressing MFA for Court Users](https://trello.com/c/s2xuGJyq/577-no-mfa-for-all-users-high)

**Comment by adunkman** [comment]
Providing a comment here about the way I’m examining user account scripts and when they should be run — will likely pull this into documentation at some point. 

There are three lifecycle stages for scripts: 

| Stage | Description | Caveats |
|-------|---------------|------|
| **Account provisioning** | Provisioning of account-level resources, like the permissions granted to automated tasks in CircleCI. Happens when permissions change or accounts change. | Requires admin-level permissions within an account, and can disrupt all resources within an account. |
| **Application provisioning** | Provisioning and deployment of the infrastructure and code, happens every time code changes. | Uses the permissions defined in the Account provisioning step. Must be environment-aware (`stg`, `mig`, `irs`, `test`) as well as deploy-aware (`blue`, `green`). |
| **One-off tasks** | Tasks are run at irregular times or frequencies. | Depending on the task, may be per account, per environment, or per deploy. |

An example of one-off tasks are: 

| Task | Frequency | Caveats |
|-----|----------|-----------|
| Creating logins for development and testing purposes. | Once per dev and test environment | Should never be run in production |
| Initial import of court logins | Once | Should only be run in production, should not rely on hardcoded or emailed passwords. |
| Deleting an environment. | Once per environment, if desired | Should never be run in production. |
| Deleting an account’s deployer. | Once per account, if desired | Should never be run in production. |

**Comment by adunkman** [comment]
Documentation of scripts being tracked at https://github.com/flexion/ef-cms/issues/5665.

**Comment by adunkman** [comment]
This issue is no longer tracking useful items — remaining work is tracked at https://github.com/ustaxcourt/ef-cms/issues/279.
