### ISSUE TITLE
Do not rely on Serverless Framework for deployments.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#230]
Yesterday when releasing #210, we encountered an issue where [Serverless could not modify the Court’s environment](https://app.circleci.com/pipelines/github/ustaxcourt/ef-cms/275/workflows/c879f1cf-3969-41ed-94b0-23a4de57f924/jobs/2654). 

When reached for assistance, Flexion said that they had to destroy and re-create the CloudFormation stack in order to get it released. 

We can’t have these kind of deployment issues when we are in production. I discussed with the Flexion team yesterday, and they have indicated that they don’t think we can use Serverless Framework, as this is a routine and regular issue that they have experienced. 

The move away from CloudFormation would also significantly simplify our deployment scripts, as we’re currently working around a 200-resource limit for CloudFormation which may no longer be a relevant constraint. We may be able to continue to user Serverless Framework for local development and use `sls package` to generate a package which can be deployed using other tools.

Additionally, if we were to rely on Terraform exclusively for management, we’d be able to have higher confidence in execution plans using `terraform plan`.

**Comment by JessicaMarine** [comment]
We also know that we need to tear down and rebuild all of the Court's environments to eliminate some orphan AWS artifacts from early in the project that tend to cause deploy issues.  Discussing with @julialeague and Flexion when best to perform this environment re-set.

**Comment by adunkman** [comment]
Should be incoming with Sprint 43.

**Comment by adunkman** [comment]
Closed by #280.
