### ISSUE TITLE
Lock all build dependencies to specific versions.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#232]
As the Court product owner, I need build dependencies locked to a specific version, so that we don't have unknown schedules/fails. 

Acceptance criteria:
- Instead of getting the latest version of API/library, we want to be specific about a version number, so we don't get changes when we deploy to a new environment.

Next steps:
- Identify if there are dependencies in the code base that are not locked down
- If there are dependencies that are not locked, specify where in the code base they exist (i.e. apiVersion = latest)
- Specify which versions should be locked down to AWS CLI
- Document environment variables in the README

There are at least some dependencies in the build process which are not version-locked, [as recently discovered](https://github.com/ustaxcourt/ef-cms/pull/219). This results in builds failing on unknown schedules, as other parties update these open source dependencies.

We’ll need to lock these dependencies to specific versions to prevent these automatic updates, as well as determining a strategy for keeping them updated. 

This would be a good opportunity to examine the way tools are being used as well, to see if there’s an opportunity to simplify and reduce dependencies. We may want to use a tool like Artifactory to assist.

**Comment by adunkman** [comment]
Also being tracked in Flexion’s OpEx/DevEx backlog as [Verify all dependencies are locked down](https://trello.com/c/R563IXnY/585-verify-all-dependencies-are-locked-down).

**Comment by vickimcfadden** [comment]
@JessicaMarine this is ready to be pulled into the Flexion backlog.

**Comment by JessicaMarine** [comment]
Added to Flexion's backlog: https://github.com/flexion/ef-cms/issues/6368
