### ISSUE TITLE
Determine a process for communicating about updates to EF-CMS.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#234]
As users of EF-CMS at the Court, so that I can understand how to use new features and understand how changes impact my work, I need to know when changes are made to EF-CMS.

- [x] Mike syncs with Jessica

**Comment by adunkman** [comment]
Include the API and changes to the API that might affect the IRS in this change process.

**Comment by vickimcfadden** [comment]
@mmarcotte to add a few sentences to the support plan and then we can mark as done :tada:

**Comment by mmarcotte** [comment]
Have emailed Scott, Mike, and Jessica about using the USTC web site to communicate about system updates. It seems like a logical place to house support materials as well as information about system updates for DAWSON.

**Comment by vickimcfadden** [comment]
Markdown file in repository will include whatever the updates are and that will be linked to from Dawson. Change log. Next step: add to deployment process and PR checklist.

**Comment by adunkman** [comment]
Andrew to do this in PR and followup to close.
