### ISSUE TITLE
Create and document the support and escalation system.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#238]
As a member of the public, so that I can access the Court’s systems and overcome setbacks, I need to know how to report issues and who to contact if I am stuck.

Acceptance criteria:

- The way that system issues are troubleshooted is known, including who is the first-line of support, and how/when contacting the vendor is appropriate.

**Comment by adunkman** [comment]
Short term plan: development team support through Jessica, prioritizing as items for Flexion, longer-term plan to be discussed after Tech Lead Mike is on the ground running.

**Comment by vickimcfadden** [comment]
Blocked until Court can decide whether Tier 1 support will be handled by Admissions, and if so, whom. 

Determine what OIS is currently doing with Blackstone, and figure out how to transition this to Admissions.

**Comment by mmarcotte** [comment]
Completed with: https://github.com/ustaxcourt/ato/pull/32

Tier 1 first line will be Admissions Section. They will monitor email and phone. OIS will assist for tickets submitted to LanSweeper, but will direct more involved issues to a new E-Help position.
