### ISSUE TITLE
External communications plan.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#240]
Create external messaging and a plan to announce the launch of the new system, including benefits to the public, that it's a new feature, how it will save them time, how it is saving the government money, success of the project itself - timeframe, value, etc

- [x] Draft FAQ
- [x] Post FAQ to website
- [x] Email FAQs petitioners/practitioners [Jessica & Mike]
- [x] Alert Tax Press

**Comment by vickimcfadden** [comment]
@JessicaMarine & I met with Jen Siegel this morning and she's developing a plain-language external explainer of what to expect and will be emailing it to practitioners, petitioners (with active cases), and posting to the web. Goal to send out by 11/13.
