### ISSUE TITLE
Define blackout window, release, and launch plan; and document it.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#241]
As the Court, so that we can effectively launch EF-CMS and operate the Court without losing any data, we need to minimize the time the Court’s systems are locked or inaccessible and effectively plan for launch. 

Acceptance criteria: 

- The process for locking one system and running any final migrations in order to start operations in EF-CMS is documented.
- The timeline needed for each step is known and documented.
- Data is exported as csv and archived for record retention rules. 

Notes:

- [Migrating and validating legacy data](https://github.com/ustaxcourt/ef-cms/wiki/Migrating-and-validating-legacy-data) may be a good place to document this.

**Comment by ericsorenson** [comment]
I've spoken to a few coworkers about approaches for reducing downtime, though applying some of these techniques will take engineering time and add AWS costs. We'll need to discuss options with the court to find a balance.

**Comment by adunkman** [comment]
Met Monday, Mike wasn’t able to meet — synced up on Wednesday with Mike, the current plan is dependent on other work, follow-up meeting scheduled for mid July to determine further next steps.

**Comment by adunkman** [comment]
Scheduled for next Thursday, Jul 16th.

**Comment by julialeague** [comment]
Mike McVicker had an update about the backup database that Blackstone data would be pushed to - the vendor has agreed that they can provide that service, and Mike and his team are now working on clearing up space in the court's system to allow for the backup database to be stored.

We'll have another follow-up meeting on August 19 to check the status on this, along with any other potential blockers to eliminating the blackout window.

**Comment by julialeague** [comment]
@michael-mcvicker and his team are still working on getting the legacy backup database hosted 100% on-premises at the court - they've run into difficulties, specifically with the pdfs, due to some outdated hardware. Troubleshooting is underway currently, and Mike/team will keep us appraised of the status. 

@JessicaMarine has completed the work to identify data schema that isn't currently accounted for in Flexion, and any work that comes from that is or will soon be added to the Flexion backlog. 

We'll discuss the status of the backup database as well as the work being done to enable pushing updates to the flattened data on 08/27 with Mike McVicker and other court stakeholders.

**Comment by julialeague** [comment]
@michael-mcvicker and his team have set up the legacy backup database that's hosted on-premises! The next step is automating batch updates to the flattened tables on a regular interval.

Per @JessicaMarine, I'm going to start working on a document that goes through migration steps with @mark-meyer, to be added to the migration repo.

**Comment by mmarcotte** [comment]
Adding this here to make sure it gets incorporated into the timeline. 

- [ ] before migration: 
  - [ ] Enable username password based authentication (ALLOW_USER_PASSWORD_AUTH) in the App client settings.
  - [ ] bump up the ID token expiration setting. ~240 minutes
- [ ] after migration:
  - [ ] Disable username password based authentication (ALLOW_USER_PASSWORD_AUTH) in the App client settings.
  - [ ] bump down the ID token expiration setting. ~60 minutes

**Comment by vickimcfadden** [comment]
Goal is to have the plan drafted by 10/16 so the Court can follow this plan when doing the next round of QC on 10/19. @mark-meyer to follow guide to see what gaps exist/what needs to be improved.

**Comment by vickimcfadden** [comment]
@julialeague add mobile/usability testing to the punch list/checklist for every deploy.

**Comment by vickimcfadden** [comment]
Done. Document is distributed for those who need it.
