### ISSUE TITLE
Draft a site operating plan.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#244]
As the Court, so that I can be prepared to maintain a production application, I need to develop plans for operating EF-CMS. 

Acceptance criteria: 

- Covers:
  - Ongoing maintenance necessary, how it's performed
  - What actions to be taken in outage
  - Process by which new administrative access is given to the system
  - How to monitor a open source project, site up time
  - The flow of users and data through and in the system
  - Mechanism for ensuring change doesn't break the system

Notes:

Overall, the care and feeding of site in ongoing way.

**Comment by adunkman** [comment]
A question came up around the current use of tools such as HoneyBadger — the current plan is to use the tools that exist as they are. Just preemptively stating that here as it may come up in planning here.

**Comment by adunkman** [comment]
Hoping to have Tech Lead Mike chime in here — a few ongoing to-be-determined items are things like: 

- Management of secrets like passwords
- How to share information about service disruptions + how they are recovered from
- How should the public communicate about lack of access
- What happens if court is in session and the system is unavailable

Currently tagging these items to discuss later — recommendations welcome.

Items that will need sign-off or approvals will need additional notice.

**Comment by adunkman** [comment]
Kelsey and Mike meeting tomorrow to continue/finish flushing this out into sprint-able chunks!

**Comment by adunkman** [comment]
Remaining: 

- Identify any decisions the court needs to make for the site operating plan.

**Comment by vickimcfadden** [comment]
Tracked in [Draft Support Plan](https://github.com/ustaxcourt/ato/blob/master/Support-Plan.md). Related to #416.
