### ISSUE TITLE
Test the application’s failover, monitoring, alerting, outage, and recovery processes.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#247]
As the Court TL, I need to intentionally break the Court's environment, so I have assurances that the system (including people) can withstand outages, route correctly, and fix breaks in a timely manner. 

Pre-conditions: 
- [x] Develop training materials for Admissions section/OIS team on how to accept and route customer issues
- [x] Training to Admissions section/OIS team on how to accept and route customer issues

Acceptance criteria:

- [x] **The test:** When parts of the application fail, the Court knows how the application as a whole will respond. 
- [x] **The test:** When parts of the application fail, the Court knows what kinds of alerts they will receive.
- [x] **The test:** The Court knows how the application will respond as these services come back online after an outage.
- [x] **After:** Any needed changes to monitoring and logging infrastructure are documented as backlogged work.
- [x] **After:** Any needed changes to alerting are documented as backlogged work.
- [x] **After:** Any needed changes to the application are documented as backlogged work.
- [x] The Court’s tech lead is confident that the system is resilient in the face of common issues and experiences outages in a predictable way under extraordinary issues.

Related to #412.

**Comment by vickimcfadden** [comment]
intention is to do chaos, fuzz, and load testing together in a sprint.

**Comment by vickimcfadden** [comment]
@adunkman to follow up with Kelsey & groom issue.

**Comment by vickimcfadden** [comment]
Can get the work ready in development environment and may be able run in migration environment.

**Comment by adunkman** [comment]
Going to drop myself as an assignee to reflect reality since Julia is running with this; always happy to assist if needed!

**Comment by julialeague** [comment]
Logged https://github.com/ustaxcourt/ef-cms/issues/586 to address the lack of automatic lambda failover configuration.

**Comment by julialeague** [comment]
Here are the notes I've taken throughout working on this issue:
https://docs.google.com/document/d/15zCf3F2RRoFbOO-0t8j5AXJCR1ad-Nz2uSw7j892OdM/edit?usp=sharing (only visible to GSA users and folks I've explicitly shared to)

**Comment by julialeague** [comment]
To do: Log the rest of the bold line items from my testing doc that aren't needing risk acceptance discussion with @mmarcotte. Log a follow-up issue to discuss risk acceptance-related questions and document the conclusions.

**Comment by julialeague** [comment]
Per the discussion with Mike Marcotte on Wednesday, I'll log an issue to revisit resiliency testing in the future, since we don't have any automated processes doing this sort of testing for us.

**Comment by julialeague** [comment]
Logged #747 to revisit this testing at a later date.

**Comment by julialeague** [comment]
The epic for failover-related issues: https://github.com/ustaxcourt/ef-cms/issues/631
