### ISSUE TITLE
Prepare contract for 3rd party security scan (pen testing).

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#249]
This will be to ensure the security of the Court's environments, including a security scan by a 3rd party company.

The running of tests is captured by https://github.com/ustaxcourt/ef-cms/issues/147.

**Comment by vickimcfadden** [comment]
currently targeting late Sept/early October. Drafted a solicitation, did market research to identify qualified companies, and shared that with the Court.

**Comment by adunkman** [comment]
The information is now with the court, and is awaiting #311.
