### ISSUE TITLE
Complete final mobile testing.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#251]
Perform final mobile testing on public portion of the site on multiple devices.

Done when:

- Product owner is confident that the system will function well on mobile devices for the public.

**Comment by JessicaMarine** [comment]
Flexion is willing to assist with this task. https://github.com/flexion/ef-cms/issues/4010

**Comment by vickimcfadden** [comment]
Put in an 18F micro-staffing request on 11/17 and asked that work be completed by 12/11.

**Comment by vickimcfadden** [comment]
We have an 18F engineer identified that can start this work on ~11/30.

**Comment by vickimcfadden** [comment]
external user workflows: https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?ts=5fb688d1#gid=215623579

**Comment by echappen** [comment]
@adunkman for my remaining hours on the project I've been assigned to this. My plan is to work through the External Parties Workflows tab of [this Test Matrix](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?ts=5fc51ca8#gid=215623579) on mobile. Is there anything else you'd like me to focus on?

**Comment by echappen** [comment]
I was able to test:
- public search functionality
- petitioner and practitioner dashboards
- creating a case (petitioner and practitioner)

Tested on:
- iPhone 6S (device)
- Galaxy S9 + Android 7.0 (Firefox emulator)

I found no errors and only a few minor refinements, which I'll list in another issue.

**Comment by vickimcfadden** [comment]
thanks so much for your help @echappen ! :ta-da:
