### ISSUE TITLE
Teardown/rebuild and document steps for migration environment

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#255]
This issue is to track the teardown/rebuild of the migration environment. We'll document steps taken and post a wiki.

- [x] Confirm w/ Eric that we're not missing anything.
- [x] Confirm with Mike/data migration team that we're ready to rebuild.
- [x] Run environment destruction script. `npm run destroy:mig`
- [x] Confirm that everything's torn down properly.
- [x] Kick off a CircleCI build for the migration environment.
- [x] Confirm that everything is set up properly upon successful CircleCI build.
- [x] Notify Mike/data migration team that the environment is back up
- [x] Confirm that the data migration team has the access needed to migrate cases.
- [x] Revise documents with findings from this activity: https://github.com/ustaxcourt/ef-cms/blob/staging/docs/SETUP.md / https://github.com/ustaxcourt/ef-cms/blob/staging/docs/ENVIRONMENT_DESTRUCTION.md

**Comment by adunkman** [comment]
Revision of documentation handled in #281.
