### ISSUE TITLE
Determine the shape of a reusable test database.

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#264]
We’re looking to create a test database seeded with test data that can be used across different test environments and forks.

- It could be a script that generates a reusable DB, Flexion has a script already that creates something. 
- Unknowns that we’d like to figure out: 
  - How many cases are open vs. closed? 
  - What is the distribution of the number of practitioners? 
  - How many documents are there?

**Comment by adunkman** [comment]
This should be representative of the migrated data set.

**Comment by julialeague** [comment]
Here is a spreadsheet to track the information we'd like to know regarding current Blackstone data: https://docs.google.com/spreadsheets/d/1Pe32nMh3KdAkVmab-meOU4F_HWdSvGHbEBOo1ZgWeC0/edit?usp=sharing

**Comment by julialeague** [comment]
We're waiting on petitioner data to be transferred to the flattened tables to get the outstanding counts from the spreadsheet. Moving this to blocked for now.

**Comment by adunkman** [comment]
We chatted about this today and it feels done — but @julialeague let us know if this is tracking something that we haven’t thought about and we can re-open!
