### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#279]
## ALL USERS ##
* Newly created users receive their own password reset instructions, TL can not specify password. 
* Remove @example.com users in deployment process. 

## PETITIONERS ##

- Legacy Petitioners who have electronic access and open cases in old system
   * Load legacy petitioners into new system
      * Data migration team to migrate all contact info. for all legacy petitioners -- https://github.com/flexion/ef-cms/issues/5430 (DONE)
      * Flexion to provide instructions to migration team about how to ID those legacy Ps needing accounts -- https://github.com/flexion/ef-cms/issues/5508 (DONE)
   * Provide legacy Ps with new accounts -- https://github.com/flexion/ef-cms/issues/5159
   * Link legacy Ps with existing case(s) --  https://github.com/flexion/ef-cms/issues/5159
- New Petitioners who self-register for account (Cognito) -- DONE
- Paper-filing Petitioners in new CMS (or legacy petitioners with open cases and no current e-Access) who later want electronic access -- Same as https://github.com/flexion/ef-cms/issues/5159?

## PRACTITIONERS ##
* Legacy Practitioners
   * Load into new system via CSV -- Flexion already developed script for this; need to do during black-out period before going live
   * Get new accounts -- Flexion already built as part of the loading process
   * Link with existing cases
      * Data migration team to migrate related Bar Nos. with cases (one or more -- array) as optional field on case entity -- https://github.com/flexion/ef-cms/issues/5594 
      * Flexion to link practitioners with cases via Bar No. matching -- https://github.com/flexion/ef-cms/issues/5595
* Add new Practitioners -- DONE
* Remove Practitioners -- https://github.com/flexion/ef-cms/issues/4652

## COURT EMPLOYEES  (Determine approach w/ Tech Lead; will need stories)
* As the Court’s Tech Lead, I need the ability to bulk load existing court users into the system, so I can ensure that they have access. [Script (already built) versus user interface?]
* As the Court’s Tech Lead, I need the ability to add and remove court users into the system, so I can ensure that the proper employees have access. [Script versus user interface?]
* As the Court’s Tech Lead, I need the ability to change a court user’s role in the system, so I can ensure that they have access to the right functionalities. [Script versus user interface?]

- Changing the technical implementation piece of managing users is also tracked at Flexion’s Production Prep item [Setup User Scripts](https://trello.com/c/ZIstzI8L/576-setup-user-scripts-high)
- Documentation of scripts is tracked at https://github.com/flexion/ef-cms/issues/5665.

**Comment by adunkman** [comment]
The only remaining work in this epic is https://github.com/flexion/ef-cms/issues/4652 (flagged as MVP if time) and https://github.com/ustaxcourt/ef-cms/issues/277. 

I don’t believe this issue is tracking anything beyond https://github.com/ustaxcourt/ef-cms/issues/277 and as such is effectively duplicated tracking in our backlog. Closing!
