### ISSUE TITLE
Execute fuzz testing of endpoints.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#284]
As the Court, so that we can ensure the application will function reliably with a variety of users from the public, we need to be able to understand how the system behaves with unexpected input.

Acceptance criteria

- [ ]  [Fuzz testing](https://en.wikipedia.org/wiki/Fuzzing) is performed against the migration, staging, or production environments.
-  [ ] Any exposed issues are documented.

Notes

- [`artillery-plugin-fuzzer`](https://github.com/artilleryio/artillery-plugin-fuzzer) is one potential framework to execute this kind of testing. 

Also tracked on Flexion’s Production Prep backlog as [Fuzzy testing of api endpoints](https://trello.com/c/x6UIfURI/8-fuzzy-testing-of-api-endpoints).

**Comment by vickimcfadden** [comment]
We may receive some feedback on this from the pen testers.

**Comment by vickimcfadden** [comment]
Ask NSSPlus if they are executing this as part of their pen testing? If so, no need to duplicate work and mark as closed.

**Comment by adunkman** [comment]
Confirmed during kickoff that NSSPlus will be fuzz testing as awarded in #402.
