### ISSUE TITLE
Provide IRS production endpoints by September 1, 2020

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#285]
As the Tech Lead, in order to make sure the IRS has adequate time to get everything set up, we need to provide production endpoints no later than September 1, 2020.

Per 7/1/2020 email from IRS, they are requesting production endpoints by September 1, 2020.

## Acceptance Criteria: ##
* Provide IRS the following production endpoints by 9.1.2020
   * Get case  
   * Get PDF 
   * Authentication

**Comment by adunkman** [comment]
Working on final team confirmation [via Slack](https://ustaxcourt.slack.com/archives/CD58Y6799/p1598634687056000).

**Comment by adunkman** [comment]
Delivered via email: 

>Hi Kevin, 
>
>As mentioned on today’s call, here are the final endpoints for the production environment: 
> - https://cognito-idp.us-east-1.amazonaws.com
> - https://api.dawson.ustaxcourt.gov
>
>Apologies for the previous mistake on the second endpoint — the development team caught my mistake this morning. There will be no further changes to these endpoints before our production launch.
>
>Thanks,
>Andrew
