### ISSUE TITLE
Implement solution for reusable, realistic, but fake test data.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#295]
We’re looking to create a test database seeded with test data that can be used across different test environments and forks. 

Acceptance criteria: 

- A data set is exported to JSON [stored where? — can be anywhere public, GitHub somewhere?]
- The data set represents the same volume and distribution of data as determined in #264.

Notes: 

- After a test-run of all cases, we’ll know additional edge cases which would be useful to add to this data set. 
- We’ll revisit this data set as needed if/when we encounter edge cases that we wish we could have on-record as a known edge case. 
- Rather than focusing on a script to generate these cases, we’ll build a snapshot of the data set.

**Comment by adunkman** [comment]
Decided in standup just now that we’ll avoid creating fake PDF documents for now. @adunkman to followup with creating a new issue to track that.

**Comment by adunkman** [comment]
Created #348.

**Comment by vickimcfadden** [comment]
Done. Golden data set is complete.
