### ISSUE TITLE
Determine a strategy for system status communications.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#305]
As the Court, so that end-users know about planned and unplanned system outages, we need to have a documented communication plan on how, where, and how often we communicate. 

Notes: 

- Broken out from #244, results from this issue should be documented in the Site Operating Plan.

**Comment by mmarcotte** [comment]
For consideration:

* Email all users in the system at least one week out from a scheduled deployment that involves downtime
* Add a notification box in DAWSON that stays until closed with information about an upcoming downtime
* Have the notification be sticky within an hour of the window and red background that counts down to the start of the maintenance window
* After a window is complete email users with the updates and improvements; perhaps add an option to the user's information so they can opt-out (or opt-in) of these updates.

**Comment by adunkman** [comment]
This could also be used for #234, potentially (communicating about routine updates).

My thoughts here are around what happens _during_ downtime events — especially those when unplanned. It might be valuable to use a third-party service here like statuspage.io.

**Comment by vickimcfadden** [comment]
for current court outages process, check with scott & loretta.

**Comment by adunkman** [comment]
Keeping notes in [this document](https://docs.google.com/document/d/1Ip9NLpsKDR2BrRiRUyFOxSaRrH4bUC4PNj8U7uck4w0/edit#) while we’re figuring out the details.

**Comment by mmarcotte** [comment]
Notes (also posted to Google Doc above):
* IRS is not contacted. 
* A notice is prepared by someone, and it looks something like:
  > The Court's eAccess system will be unavailable on Saturday, August 29 from 12:00 AM - 6:00 AM EDT while system maintenance is performed. No documents may be eFiled during this maintenance window, and all case-related systems, including opinions and orders searches, will be affected.
* The notice is sent to Jen Siegal for the Chief Judge to approve
* The notice is sent to Scott who would post it on the Tax Court web site.

Looks like statuspage.io would be free for us? At least for starters?

**Comment by mmarcotte** [comment]
https://status.ustaxcourt.gov lives

**Comment by adunkman** [comment]
Heads up — it looks like that link is serving the default certificate (*.statuspage.io) instead of one for that domain.

![Screenshot of a security warning page, showing the certificate mismatch as described](https://user-images.githubusercontent.com/14930/95874438-e4a3b700-0d3e-11eb-8835-d6d4b7e7a44d.png)

Looks like enabling SSL [requires checking a checkbox](https://support.atlassian.com/statuspage/docs/set-a-custom-domain-and-ssl/) now that domain configuration is completed: 

> To enable SSL:
>
> 1. Go to Your page > Customize page and emails.
> 2. Select the Customize status page tab.
> 3. Click Enable SSL.

**Comment by mmarcotte** [comment]
Done.
