### ISSUE TITLE
Finalize Dawson business goals and metrics and present them to Clerk of the Court and IT Committee

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#320]
As the Court product owner, I need to determine the goals and outcomes I hope to positively impact with Dawson, so that I can monitor its effectiveness at meeting these goals and outcomes.

Acceptance criteria:

- [x] Court decides goals, metrics, and proposed method of tracking, [document](https://docs.google.com/document/d/1xCh1hbXjJItOWlQ2MH-GDDc0KWho88KKcHfUJcpHkSs/edit)

- [x] Court presents these to Clerk of the Court and IT committee for their feedback

Related to #229 and working draft, here: https://docs.google.com/document/d/1yDTyeyxt1F4GX-5Y-NXjg7uDzlIgZxmD6Uc7krZmD0g/edit

**Comment by adunkman** [comment]
Done! :tada:
