### ISSUE TITLE
Pull in prior work documenting security threats, review, brainstorm.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#322]
To facilitate #267, we need to pull in the existing documentation around security threats and review/brainstorm/get alignment on them. 

Acceptance criteria: 

- Existing ATO repo is reviewed with @mmarcotte.
- Notes on the discussion to generate the security plan are privately stored for future reference.
- The security plan has document accepted security risks

**Comment by adunkman** [comment]
Path forward: 

- Continue to go through components that are 3rd party dependencies, what threats are associated with them, the accepted risks and controls in place. 
  - Likely not to list out each npm package, but rather treat them as a whole and see what controls are in place (like `npm audit`).

**Comment by mmarcotte** [comment]
Picking up the thread. I'm going to continue @julialeague 's work of identifying threats, risks, and controls within the 3rd party dependencies. @lauraGgit is going to come at it from the NIST control families side, and ensure our bases are covered there.

**Comment by vickimcfadden** [comment]
Prior work was pulled into current security plan, closing.
