### ISSUE TITLE
Consider having a pre-mortem prior to launch

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#325]
As the Court product owner, so that the team gets concerns on the table prior to launch, I need to think about having a pre-mortem with the team prior to launch.

**Comment by vickimcfadden** [comment]
pre-mortem scheduled for 10/2. 

[pre-mortem notes](https://docs.google.com/document/d/1afEHP9l0NZnMtSBuluYV6W4uzAzZW0RFXicnzd6OwQc/edit?ts=5e0fbf3a) from January 2020.

**Comment by vickimcfadden** [comment]
Decided to hold off on the pre-mortem for a few weeks. Putting this card back into the backlog.

**Comment by adunkman** [comment]
We feel that this isn’t necessary at this point, closing.
