### ISSUE TITLE
Elasticsearch index outdated in migration environment.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#334]
This issue tracks work related to an issue discovered when running our first large-scale data migration against EF-CMS.

### Summary

After running the migration scripts of all open cases (approximately 20,000), retrieving documents by docket number in EF-CMS is working well, however searching by properties such as type results in significantly fewer (on the order of 10,000) results than expected.

When running those migration scripts, most requests returned 200 OK responses. There were approximately 40 requests that failed, due to validation errors.

### Timeline

| UTC Timestamp | Eastern | Event |
|------------|---------------|------|
| 2020-07-30T21:00:00Z | July 30, 5:00pm | Elasticsearch cluster begins a significant event<br>(+50 – 100% CPU usage, free space dropping from 7 to 2 GB) |
| 2020-07-30T23:52:00Z | July 30, 7:52pm | Approximate start of migration scripts |
| 2020-07-31T01:00:00Z | July 30, 9:00pm | Approximate end of migration scripts | 
| 2020-08-01T10:00:00Z | August 1, 6:00am | Elasticsearch cluster returns to normal operation |

### Metrics

| Search rate (operations/min) | Search latency (milliseconds) | Indexing latency (milliseconds)
|--------|------|-----|
| ![image](https://user-images.githubusercontent.com/14930/89575562-fd05cb80-d7fb-11ea-953b-33884efd5d47.png) | ![image](https://user-images.githubusercontent.com/14930/89575873-6b4a8e00-d7fc-11ea-99a5-87ddfa24187f.png) | ![image](https://user-images.githubusercontent.com/14930/89576136-d85e2380-d7fc-11ea-8edc-88bc224ecff9.png)
| [View graph in CloudWatch](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(view~'timeSeries~stacked~false~metrics~(~(~'AWS*2fES~'SearchRate~'DomainName~'efcms-search-mig~'ClientId~'350455059537~(stat~'Maximum)))~region~'us-east-1~title~'Search*20rate*20*28operations*2fmin*29~stat~'Average~period~60~yAxis~(left~(showUnits~false))~start~'2020-07-29T00*3a00*3a00.000Z~end~'2020-08-01T23*3a59*3a59.000Z)) | [View graph in CloudWatch](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(view~'timeSeries~stacked~false~metrics~(~(~'AWS*2fES~'SearchLatency~'DomainName~'efcms-search-mig~'ClientId~'350455059537~(stat~'Maximum)))~region~'us-east-1~title~'Search*20latency*20*28Milliseconds*29~stat~'Average~period~60~yAxis~(left~(showUnits~false))~start~'2020-07-29T00*3a00*3a00.000Z~end~'2020-08-01T23*3a59*3a59.000Z)) | [View graph in CloudWatch](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(view~'timeSeries~stacked~false~metrics~(~(~'AWS*2fES~'IndexingLatency~'DomainName~'efcms-search-mig~'ClientId~'350455059537))~region~'us-east-1~title~'Indexing*20latency*20*28Milliseconds*29~stat~'Average~period~60~yAxis~(left~(showUnits~false))~start~'2020-07-29T00*3a00*3a00.000Z~end~'2020-08-01T23*3a59*3a59.000Z))

| CPU utilization (percent) | Free storage space (GB) |
|-----------------|---------|
| ![image](https://user-images.githubusercontent.com/14930/89576290-16f3de00-d7fd-11ea-9a76-4f240db55808.png) | ![image](https://user-images.githubusercontent.com/14930/89576395-3854ca00-d7fd-11ea-87ef-86779e7cc990.png)
| [View graph in CloudWatch](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(view~'timeSeries~stacked~false~metrics~(~(~'AWS*2fES~'CPUUtilization~'DomainName~'efcms-search-mig~'ClientId~'350455059537))~region~'us-east-1~title~'Maximum*20CPU*20utilization*20*28Percent*29~stat~'Maximum~period~60~yAxis~(left~(showUnits~false))~start~'2020-07-29T00*3a00*3a00.000Z~end~'2020-08-01T23*3a59*3a59.000Z)) | [View graph in CloudWatch](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(view~'timeSeries~stacked~false~metrics~(~(~(expression~'FLOOR*28m1*2f1024*29~label~'FreeStorageSpace~id~'e1~region~'us-east-1))~(~'AWS*2fES~'FreeStorageSpace~'DomainName~'efcms-search-mig~'ClientId~'350455059537~(id~'m1~visible~false)))~region~'us-east-1~title~'Minimum*20free*20storage*20space*20*28GiB*29~stat~'Minimum~period~60~yAxis~(left~(showUnits~false))~start~'2020-07-29T00*3a00*3a00.000Z~end~'2020-08-01T23*3a59*3a59.000Z))

#### For now

- Application logging is not enabled in Elasticsearch, so we don’t have any diagnostic information from Elasticsearch beyond its metrics. It appears something kicked off at approximately 2020-07-30T21:00:00Z, but without the logs, it’s hard to say what it was. 

#### For later

- Elasticsearch cluster health should be included in ustaxcourt/ef-cms-flexion#236 and ustaxcourt/ef-cms-flexion#233.
- Elasticsearch [should have an odd number of nodes, likely 3 in production](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-dedicatedmasternodes.html) rather than the [2 currently provisioned](https://github.com/ustaxcourt/ef-cms/blob/54bf591f5af036ba263da8b8e941cce893d507f0/get-es-instance-count.sh#L29-L32).

### Outstanding questions

- This incident
  - Should the application return errors when inserting data and indexing fails?
  - What caused the index to become outdated?
- Reindexing
  - How do we kick off reindexing of the data, if this issue presents itself again? 
  - What happens when migrations are applied during a deploy? Are we missing a case where we may need to reindex?

### Next steps

1. Enable better logging.

    - [x] Enable Elasticsearch logging. ustaxcourt/ef-cms#6582

2. Clear the migration environment and re-run the scripts.

    - [x] Fix outstanding issues in the clear environment script. ustaxcourt/ef-cms#6580
    - [x] Run the script against the migration environment.
    - [x] Re-run the migration scripts against the fresh migration environment.

3. We hypothesize the same issue will present, and can debug further.

  - [X] Determine a way to capture errors - done, kibana dashboard  
  - [X] Determine a way to evaluate accuracy - @mark-meyer - done, check case type migrated against migration number expectations
    - [ ] Verify the issue with search is presenting similarly, as described in the **Summary** section above.
    - [ ] Examine the metrics and logs with Flexion developers.

### Before closing this issue

- [ ] Create issues in the appropriate backlogs to address everything from **Lessons** above, as well as what’s uncovered in the debugging sessions.

**Comment by adunkman** [comment]
We aren’t able to reproduce the issue now that logging is enabled. We’ll keep an eye on this, but considering it closed for now. 

Remaining tasks are for Elasticsearch tuning. 
  - Flexion noticed that 1 of 50 shards are used in their environments. Likely has to do with sharding key (docket number). 
  - Elasticsearch should have an odd number of nodes, likely 3 in production rather than the 2 currently provisioned (see above).

We can consider this issue closed when these tasks are tracked elsewhere.

**Comment by vickimcfadden** [comment]
merge 48.5 sprint, accept to test environment, compare to metrics/reports

**Comment by adunkman** [comment]
Mark has identified a few errors in the lambda which sends data from dynamodb to elasticsearch, and has met with Eric and Mike for next steps. Eric to improve the logging here to aid in further diagnosis.

**Comment by adunkman** [comment]
Addressed by https://github.com/flexion/ef-cms/issues/6654; will open new issue if other symptoms persist.
