### ISSUE TITLE
Add health and config endpoints to UI and API endpoints.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#339]
As the Court’s Tech Lead, so that I can be sure EF-CMS is in a functional state, I need to be able to check each component is configured together correctly and operational, both during regular operations and after deployments.

Related to ustaxcourt/ef-cms-flexion#236.

Acceptance criteria: (flush out)

- A JSON endpoint is added to each application component.
  - UI, public UI, API, public API.
- The endpoint returns the URLs it is using to access the other components it needs to use.
  - May include other API endpoints, login pages, Elasticsearch endpoints, etc.
- For APIs which access a data store, the endpoint contacts that data store and ensures a connection can be made. 
- A smoke test which hits these endpoints post-deploy.

Specifically out of scope: 

- Monitoring or alerting on this endpoint.

**Comment by mmarcotte** [comment]
Perhaps this is scope creep and worthy of future tickets, but...
* What about having this health check run every (hour? 15min?) in addition to this being a manual process? 
* Logging the report somewhere handy
* How to handle reporting a health failure

**Comment by JessicaMarine** [comment]
Moved to Flexion's backlog: https://github.com/flexion/ef-cms/issues/6281
