### ISSUE TITLE
Unable to delete certificate upon migration to new URLs.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#350]
Certificate e488544e-3ffe-425f-b267-d82529703470 is unable to be removed. 

- It’s not referenced anywhere, so support case 7270882991 opened with AWS.
- We will remove it from Terraform’s state to unblock the environment.

**Comment by adunkman** [comment]
AWS support needs to open an internal support ticket — there is no clear reason why this certificate is unable to be removed. @mmarcotte will be notified by email. 

In the meantime, we’ve removed this resource from terraform state to unblock us from moving forward: 

```bash
➜ terraform state rm module.ef-cms_apis.aws_acm_certificate.us-east-1 
Removed module.ef-cms_apis.aws_acm_certificate.us-east-1
Successfully removed 1 resource instance(s).
```

**Comment by mmarcotte** [comment]
Also removed this resource, and we will await response from AWS support to ensure its removal
```
$ terraform state rm module.ef-cms_apis.aws_acm_certificate.us-east-1
Removed module.ef-cms_apis.aws_acm_certificate.us-east-1
Successfully removed 1 resource instance(s).
```

**Comment by mmarcotte** [comment]
Removed another resource, and learned that we cannot cancel CircleCI jobs during a Terraform operation.
```
$ terraform state rm module.ef-cms_apis.aws_acm_certificate.us-east-1
Removed module.ef-cms_apis.aws_acm_certificate.us-east-1
Successfully removed 1 resource instance(s).
Releasing state lock. This may take a few moments...
```

**Comment by mmarcotte** [comment]
removing more pieces of state from terraform:

and creating these dangling certificate artifacts:
* us-east-1: `5285e8be-d71e-41f5-9e50-01ae4648f220`
* us-west-1: `c68c496e-c0b0-426a-8d7a-bea72824b84a`
* us-west-1: `3e18a96b-e305-4095-b157-6c54d3f2e6eb`

Creating ticket with AWS to remove these

**Comment by adunkman** [comment]
I’ve got one more for you, if you haven’t yet opened a ticket — `42314b52-5987-41b9-af96-3b0753221d09` is dangling after removing the old `prod` environment.

**Comment by mmarcotte** [comment]
Ticket submitted to help remove these Certificates:

* us-east-1: 5285e8be-d71e-41f5-9e50-01ae4648f220
* us-east-1: 0c854287-1413-4987-858d-d08e16d96bab
* us-west-1: c68c496e-c0b0-426a-8d7a-bea72824b84a
* us-west-1: 3e18a96b-e305-4095-b157-6c54d3f2e6eb
* us-east-1: 42314b52-5987-41b9-af96-3b0753221d09
* us-east-1: 85948f68-fba3-4971-8925-abbb9813a73f
* us-west-1: 8a801f84-3a3a-41a5-a34b-fda59564649d

**Comment by mmarcotte** [comment]
... just waiting on AWS to resolve my open ticket. Then this can be closed.

**Comment by mmarcotte** [comment]
Removed these:

* efcms-test.ef-cms.ustaxcourt.gov | 0c854287-1413-4987-858d-d08e16d96bab (us-east-1)
* efcms-prod.ef-cms.ustaxcourt.gov | 42314b52-5987-41b9-af96-3b0753221d09 (us-east-1)
* efcms-prod.ef-cms.ustaxcourt.gov | 8a801f84-3a3a-41a5-a34b-fda59564649d (us-west-1)

Still waiting on Amazon to disassociate:

* efcms-mig.ef-cms.ustaxcourt.gov | 85948f68-fba3-4971-8925-abbb9813a73f (us-east-1)
* efcms-irs.ef-cms.ustaxcourt.gov | 285e8be-d71e-41f5-9e50-01ae4648f220 (us-east-1)

**Comment by mmarcotte** [comment]
certs disassociated and deleted. Done!
