### ISSUE TITLE
offboard Tim, Lia,

### ISSUE THREAD

**Issue by jhansen-flexion** [ustaxcourt/ef-cms#3692]
I am not sure if we ever did this, but please be sure that **Tim Shumway** and **Lia McCabe**'s access is off-

 [ ] All access is revoked to tools listed in [the onboarding template](https://github.com/ustaxcourt/ef-cms/blob/staging/.github/ISSUE_TEMPLATE/onboarding.md) (copy the relevant accounts to checklist items below).

Verify the offboarding person:

- [x] Does not have active AWS IAM accounts in staging and production AWS accounts.
- [x] Does not have active AWS Organization accounts in staging and production AWS accounts.
- [x] Does not have Cognito access to Kibana logs in staging and production AWS accounts.
- [x] Does not have privileged Cognito access to DAWSON environments.
- [x] Does not have access to private GitHub repositories.
- [x] Does not have push access to public GitHub repositories.
- [x] Does not have access to Zendesk.
- [x] Does not have access to Slack.
- [x] Does not have access to Trello boards.
- [x] All sensitive secrets the person had access to are rotated.

**Comment by mmarcotte** [comment]
These users have been offboarded!
