### ISSUE TITLE
User Security: Specify the Temporary Password Validity

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#370]
I noticed while scouring the CircleCI deploy logs that something continues to get rewritten every time. It appears that we're not explicitly specifying the `temporary_password_validity_days` in the Terraform config for our AWS Cognito User Pools. And so each time Terraform is thinking we're meaning to specify Null, but AWS takes that null and converts it to its default of 7. So each subsequent deploy attempts to change that 7 to null. 

So, we should explicitly state one and help unify our User Security approach.

```
~ resource "aws_cognito_user_pool" "irs_pool" {
    ...   
      ~ password_policy {
            minimum_length                   = 8
            require_lowercase                = true
            require_numbers                  = true
            require_symbols                  = true
            require_uppercase                = true
          - temporary_password_validity_days = 7 -> null
        }
    ...
}
```

Acceptance Criteria:
* We no longer try to update the AWS Cognito User Pool every deploy
* We have a clear approach for managing temporary passwords as well as permanent passwords.

**Comment by adunkman** [comment]
#400 handles the approach to managing permanent passwords.
