### ISSUE TITLE
Stress Test - Documents

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#372]
As a system administrator, so that I can ensure that the system can be used with any document from our legacy data, I need to do stress test document functionality with documents that represent legacy data.

Acceptance Criteria:
- [ ] Ensure that features for bulk download and attaching a cover sheet work for legacy PDFs.
- [ ] Stress test the items below and create tickets as necessary if they can wait for post-MVP
  * Users can perform bulk download of case documents (in excess of 3GB total) onto their hard drive
  * Users can view documents in the document view and easily toggle from one to another while having a good user experience
  * Ensure that attaching cover pages to large documents work properly
- [ ] System administrator understands how long it takes to download documents, so they can make bandwidth decisions.

notes:
- from below comments, regarding case size, consider using 017431-17 (open, not sealed): 160 docket-records. Several of the PDFs are 1000+ pages, however not all are currently migrating. Total size 20GB. Might need to calendar it, and then Download Cases link
  > login as a judge - go to one of the judge's trial sessions. It should take you to their Working Copy screen and there is a "Download Cases" link there

- intended to capture the actions of a download to a zip file of large trial session with many documents. 
- can run in migration environment.
- @mark-meyer to identify some big real PDFs.

**Comment by mark-meyer** [comment]
The largest cases in terms of combined docket record PDF size are:

1. 31183-15 (sealed): Over 700 docket-record entries many between 500 - 900 pages. Total size 49GB.
2. 12131-18 (sealed): 300+ docket-records with many 500+ page PDFs. Total size 21.7GB
3. 017431-17 (open, not sealed): 160 docket-records. Several of the PDFs are 1000+ pages, however not all are currently migrating. Total size 20GB.
4. 26965-09: 295 docket-record entries. Similar to above. 91.8 GB

Not quite as large as those above, but open and not sealed:
5354-18:  71 docket records, with many documents that are several thousand pages. Total size 5GB.
13705-16: 81 docket records, Totals size 5GB - JURISDICTION RETAINED

Large single documents. The truly gigantic PDFs have not migrated and Mike McVicker is still working on getting these to AWS. 
Case 28210-15 provides one of the largest migrated PDFs in a non-sealed case. Docket index No. 29 is 800MB and 2749 pages long. 

In terms of length, the winners for the longest docket records go to:

1. 005576-12: 827 docket entries (open/sealed)
2. 029643-86: 808 docket entries
3. 009382-83: 774 docket entries
4. 040159-84: 769 docket entries
5. 015907-84: 750 docket entries

30586-09 is the longest open, non-sealed case. 405 docket entries.

**Comment by vickimcfadden** [comment]
@mark-meyer take a :eyes: at the largest open cases.

**Comment by mmarcotte** [comment]
first one is Blocked and Sealed
Next 4 are Closed.

**Comment by adunkman** [comment]
Bulk download of trial sessions is happening now, and is achieving the majority of this issue. Could get wrapped up soon!

**Comment by mmarcotte** [comment]
One issue is that the you cannot unzip the file on a Windows machine. It appears that filenames were too large to function properly on Windows OS. Might be an easy win to truncate the docket entry titles. 

Also it appears that 4GB is the max file size for zip files in Windows

**Comment by adunkman** [comment]
Resolved by #661.
