### ISSUE TITLE
Support and operations plan delivered to the product owner.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#375]
By the end of this sprint, we’ll wrap up the support and operations planning and @mmarcotte will deliver to @JessicaMarine for commenting, review, and teamwork! :tada:

**Comment by vickimcfadden** [comment]
Draft [Support Plan](https://github.com/ustaxcourt/ato/blob/master/Support-Plan.md) was shared for feedback.

**Comment by vickimcfadden** [comment]
Related to #416.
