### ISSUE TITLE
After a deployment IRS super user account unable to authenticate with API

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#384]
After we last updated the IRS environment, we ran into an issue with the super user being unable to authenticate with the API. The error that was being caught in the Cloudwatch logs was:

```
{
    "errorType": "TypeError",
    "errorMessage": "Expected \"jwk\" to be an Object",
    "stack": [
        "TypeError: Expected \"jwk\" to be an Object",
        "    at t (/var/task/cognito-authorizer.js:172:109)",
        "    at i (/var/task/cognito-authorizer.js:524:485)",
        "    at Runtime.exports.handler (/var/task/cognito-authorizer.js:524:942)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

The workaround that we found was to simply edit and redeploy the `cognito_authorizer_lambda_irs` Lambda function. This seemed to get set properly with the correct environment variables and solved the problem. 

Perhaps there's a race condition where this gets setup via Terraform before Cognito, and there's some strange mismatch of environment variables, but we'd expect that to fail differently than what we are seeing. Something to have on the radar.

the `jwkToPem(k)` call is what was triggering that error:

```
const verify = (methodArn, token, keys, kid, cb) => {
  const k = keys.keys.find(k => k.kid === kid);
  const pem = jwkToPem(k);
```

**Comment by adunkman** [comment]
Fixed in #395.
