### ISSUE TITLE
Award solicitation for pen testing.

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#402]
As the Court, to be able to ensure the security of the Court's environments, we need to perform a security scan by a 3rd party company.

Goal is to award using FY20 money and work to start in the new fiscal year, early October. 

Following #211, #249, and #147.

**Comment by vickimcfadden** [comment]
bids due Thursday, 9/24

**Comment by JessicaMarine** [comment]
Network Security Systems Plus, Inc. submitted the lowest, technically-acceptable bid at $13,500. Award was made on 9/30/2020.  Kick-off meeting scheduled for 4:30pm ET on Tuesday, 10/6/2020
