### ISSUE TITLE
Tier 2 support plan

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#403]
As the Court Tech Lead, I need to understand resources available and plan to support users on system operations, so that we are adequately staffed and have a plan in place. 

- [x] Talk to CIO Mike.
- [x] Plan is documented. 
- [ ] Users and participants in the process are trained. 
- [x] It has been appropriately communicated.

**Comment by vickimcfadden** [comment]
should be finalized by 9/25, to brief chief judge

**Comment by mmarcotte** [comment]
https://github.com/ustaxcourt/ato/pull/32 has the final draft to be communicated to Chief Judge tomorrow.
