### ISSUE TITLE
Review open cases with Court employees

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#405]
As the Court product owner, I need to understand that all the open cases have migrated over correctly, so that we don't inadvertently miss information. 

Next steps:
- [x] 18F/Court to develop an email with how to identify a bug, instructions for communicating when an issue is identified, and next steps on who to communicate bugs to 
- [x] Court identify if/where data is wrong within a specific case with URL, docket number, and screenshots
- [x] 18F to reproduce issues
- [x] 18F to log issues in migration board
- [x] If necessary, add issues to Flexion's bug board

**Comment by vickimcfadden** [comment]
Court expects QC review to be done by Friday, 9/25.

**Comment by JessicaMarine** [comment]
QC completed on Friday, 9/25.  Issues reported here: https://docs.google.com/spreadsheets/d/1MpROyz9KbHWzr2pXD7jJA-8Aedfw-jc8Xdno6gj3ZUU/edit?usp=sharing
