### ISSUE TITLE
Tier 1 support training

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#412]
As the Tax Court Tech Lead, I need to ensure that the folks fielding calls from users have training on the most common likely issues, so that they can handle these tier 1 calls expeditiously, deliver good customer support, and not need to raise the issues to Tier 2 support. 

To do:
- [x] Get Dawson support email address set-up
- [X] Brainstorm most likely issues that Tier 1 would be responsible for managing
- [X] Develop training docs for the most common likely issues, i.e. resetting passwords
- [X] Articulate where / when bugs are logged on GitHub (publicly) or elsewhere (privately)
- [X] Develop form/github template(s) - documentation requests, security incidents, bug notification, feature request, etc.
- [X] Jessica review training docs
- [x] Get Tier 1 folks GitHub accounts
- [x] Train Tier 1 folks on [GitHub](https://www.youtube.com/watch?v=uNa9GOtM6NE&feature=youtu.be)
- [x] Jessica to give Deborah a heads-up on what to expect
- [x] Get Tier 1 setup with Zendesk
- [x] Provide IT specialist & Admissions recorded demo (Jessica creating)

Related to #403.

**Comment by vickimcfadden** [comment]
Next steps for @vickimcfadden & Torey: do a first draft of training materials for OIS/Admissions, including GitHub prompts. 

Next steps for @mmarcotte : schedule the OIS/Admissions training session a few weeks out, get the support email set-up, take a look at the vulnerability disclosure policy to see if it should be included [here](https://github.com/ustaxcourt/ef-cms/security/policy), and set-up the script to look up case information by practitioner ID to see how difficult this is to run.

**Comment by adunkman** [comment]
#421 has been created to track: 

> take a look at the vulnerability disclosure policy to see if it should be included [here](https://github.com/ustaxcourt/ef-cms/security/policy)

**Comment by vickimcfadden** [comment]
First draft of training guide here: https://docs.google.com/document/d/13NabT_hzyfo98_pwVAnWuhVSMh_hR62yskhUCgJqqsI/edit

**Comment by vickimcfadden** [comment]
@JessicaMarine to take a look :point-up:

**Comment by vickimcfadden** [comment]
@JessicaMarine completed her review and I incorporated most of her edits. There are still some open comments for you to consider @mmarcotte !

**Comment by adunkman** [comment]
Latest update: feels like we’re about 95% of the way.

**Comment by mmarcotte** [comment]
I've dropped in some responses and addressed some inaccuracies. Happy to try and get the document over the finish line.

Meanwhile, I'm going to sync with OIS today to ensure we have the Teams account (dawson.support@ustaxcourt.gov) setup and readied.

**Comment by vickimcfadden** [comment]
Established weekly meetings on Thursday mornings! :ta-da:

**Comment by mmarcotte** [comment]
Meeting next with them on Thursday, December 3rd
