### ISSUE TITLE
Devise and implement backup and restore strategy for DynamoDB

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#415]
In the case of a catastrophic event at AWS or security incident, we need to have a mechanism to backup a snapshot of the DynamoDB to a secure location outside of the AWS Account. Will confer with @michael-mcvicker about the best place for this location, perhaps in an on-prem resource.

**Comment by adunkman** [comment]
May involve piggybacking on some recurring cron jobs, or using dynamo’s point-in-time backups. @mark-meyer and @mmarcotte to sync!

**Comment by mark-meyer** [comment]
The DynamoDB tables used for Dawson have [point-in-time recovery](https://aws.amazon.com/dynamodb/pitr/) enabled, which maintains backups for 35 days. It also maintains a 35 day backup for any table that has been deleted. Restoring from the backup is easily done with either the aws cli or the console. 

However, it is not clear what steps will need to be taken. You cannot restore a backup to an existing table; instead you need to restore to a new table and then somehow direct the application to use this table. 

**A possible recovery plan could look like:**

1. Place the app in a maintenance or read-only mode to prevent new data from being written to a possibly corrupt table.
2. Restore from PITR backup to a new DynamoDB table.
3. Re-index elasticsearch so it is in sync with the recovered DynamoDB table.
4. Redirect app to use new dynamoDB table.
5. Delete corrupt table.
6. Exit maintenance mode.

I don't know if there is currently a way to perform items 1 or 4 from this list.

**Comment by vickimcfadden** [comment]
Test blue/green deploy to see if it works and document workflow. @mark-meyer 
@mmarcotte to share documentation on how to run script.

**Comment by mmarcotte** [comment]
Made a PR with improved documentation for how the blue green deployments currently work as well as some notes about how this could inform this ticket. Also logged https://github.com/ustaxcourt/ef-cms/pull/554 to add a switch to put the application into maintenance mode.

**Comment by mark-meyer** [comment]
**Findings for experimenting in exp1**

Both point-in-time and recovery from a deleted dynamoDB table work with the current configuration of ef-cms. With a fully-populated dynamoDB table the recovery into a new table from a backup takes about 70 minutes.

The recovery will create a new table that is not connected to the running app in any way. The current script for performing a manual data migration (described in `docs/BLUE_GREEN_MIGRATION.md`) works to move recovered data from the temporary table created during the point-in-time recovery into either the alpha or beta table. This has been tested on a small set of data in the exp1 environment, but not on a full set of data. The expected time for this to complete should be similar to the current time for running a migration during a deploy. 

**Notes:**

1. The manual migration script requires the receiving table and elasticsearch cluster to be empty. Scripts exist to empty a dynamoDB table, but these perform batch writes on every record and will be time consuming. It may be better to delete the target table and have Terraform recreate it.

2. The recovery process preserves global indices on the tables, but does not preserve stream settings or triggers. This should not be an issue so long as a migration is performed from the this table into a properly configure table.

**Comment by vickimcfadden** [comment]
Mark to add learnings to shared repo doc
