### ISSUE TITLE
Identify and scope out and implement v1 API.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#430]
As an API consumer like the IRS, so that I can maintain uptime on services which use Dawson API, I need to be able to use a stable API with limited changes.

### Notes

- We should retain our ability to change our data structures internally while providing a stable API for consumers.

**Comment by adunkman** [comment]
Current usage of fields from the IRS:

| IRS field name | EF-CMS field |
|---------------|--------------|
tc_case_name                | case.caseCaption
tc_docket_number_suffix     | case.docketNumberSuffix
tc_case_status              | case.status
tc_case_type                | case.caseType
tc_served_date              | document.servedAt
tc_filed_by                 | document.filedBy
tc_filed_date               | document.filingDate
tc_trial_location           | case.trialLocation
tc_preferred_trial_city     | case.preferredTrialCity
tc_practitioner_name        | practitioners.name
tc_practitioner_address     | practitioners.contact
tc_served_parties           | document.servedParties
tc_contact_primary          | case.contactPrimary
tc_street_address           | case.contactPrimary
tc_city                     | case.contactPrimary
tc_state                    | case.contactPrimary
tc_zipcode                  | case.contactPrimary
tc_initial_case_title       | case.initialTitle
tc_sort_docket_number       | case.sortableDocketNumber
tc_lead_case_docket_number  | case.leadCaseId
tc_party_type               | case.partyType
tc_filing_type              | case.filingType
tc_contact_secondary        | case.contactSecondary
tc_entity_name              | case.entityName
tc_practitioner_bar_number  | practitioners.barNumber
tc_practitioner_phone       | practitioners.contact
tc_practitioner_email       | practitioners.email
tc_practitioner_svc_ind     | practitioners.serviceIndicator
tc_trial_date               | case.noticeOfTrialDate
tc_respondent_name          | respondents.name
tc_respondent_address       | respondents.contact
tc_respondent_bar_number    | respondents.barNumber
tc_respondent_phone         | respondents.contact
tc_respondent_email         | respondents.email
tc_respondent_svc_indicator | respondents.serviceIndicator
tc_order_for_amend_petition | case.orderForAmendedPetition
tc_order_for_ap_filing_fee  | case.orderForAmendedPetitionAndFilingFee
tc_order_for_filing_fee     | case.orderForFilingFee
tc_order_for_ods            | case.orderForOds
tc_order_for_ratification   | case.orderForOds
tc_order_to_show_cause      | case.orderToShowCause

**Comment by JessicaMarine** [comment]
@adunkman I don't think that the IRS needs the following;
![image](https://user-images.githubusercontent.com/40871081/94612005-7bb53d00-0270-11eb-969d-8991ef626da6.png)

**Comment by vickimcfadden** [comment]
@adunkman where are we on this?

**Comment by adunkman** [comment]
Need to verify this works for all of us at the Court + Flexion, and then confirm with IRS. Latest in #447.

**Comment by adunkman** [comment]
Completed by #463
