### ISSUE TITLE
Hire E-Help Specialist

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#451]
As the Tech Lead, I need support with internal, external customer issues and handling more complex issues that the Admissions Section can not solve, so that user issues are resolved in a timely manner and more significant issues/bugs are escalated to the EF-CMS backlog.

**Comment by vickimcfadden** [comment]
First round, nobody was qualified, going back up out for candidates, hope to have it close on 11/23.

**Comment by vickimcfadden** [comment]
was posted on usajobs on 11/12.

**Comment by vickimcfadden** [comment]
Internal Court meeting on 11/30 to review applications.

**Comment by mmarcotte** [comment]
🎉
