### ISSUE TITLE
Vulnerability Disclosure Policy

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#453]
Todo:

- [ ] Register email address for reports (such as security@ustaxcourt.gov) 
- [ ] Add this to the Security Contact Email field in WHOIS data

**Comment by mark-meyer** [comment]
[DHS provides guidance](https://cyber.dhs.gov/bod/20-01/#fn:22) to executive agencies which includes clear steps for creating a disclosure policy:  

- Which systems are in scope
- The types of testing that are allowed 
- A description of how to submit vulnerability reports
- A statement that sets expectations for when the reporter (where known) can anticipate acknowledgement of their report and pledges the agency to be as transparent as possible about what steps it is taking during the remediation process.
- An issuance date

DHS also provides [a VDP template](https://cyber.dhs.gov/bod/20-01/vdp-template/) which may be useful.

The TTS handbook also has [information about VDPs](https://handbook.tts.gsa.gov/responding-to-public-disclosure-vulnerabilities/#communicate-with-vulnerability-reporter)

**Examples:**
- [18F](https://github.com/18F/vulnerability-disclosure-policy/blob/master/vulnerability-disclosure-policy.md)
- [Department of Health and Human Services](https://www.hhs.gov/vulnerability-disclosure-policy/index.html)
- [Consumer Product Safety Commission](https://www.cpsc.gov/vulnerability-disclosure-policy)
- [Securities and Exchange Commission](https://www.sec.gov/vulnerability-disclosure-policy)

**Comment by adunkman** [comment]
Status update here — there are TODOs above, and some ongoing discussion on what the right path forward is internal to the Court. @mmarcotte to follow-up.

**Comment by mmarcotte** [comment]
Have emailed OIS to get this one moving.

**Comment by mmarcotte** [comment]
Blocked by OIS for completion. Perhaps in an accountability hole. Whose job is it truly to get this done? Meet with Truong?

**Comment by mmarcotte** [comment]
This has been completed by OIS.
