### ISSUE TITLE
SI-8 Enable API-gateway throttling for spam protection

### ISSUE THREAD

**Issue by lauraGgit** [ustaxcourt/ef-cms#459]
**Is your feature request related to a problem? Please describe.**
NIST Security Control [SI-8](https://nvd.nist.gov/800-53/Rev4/control/si-8) requires spam protection so the the system doesn't get overwhelmed by fraudulent spammy requests

**Describe the solution you'd like**
enable throttling on the API gateway to limit the number of requests within a certain point.

**Describe alternatives you've considered**

**Additional context**

**Comment by adunkman** [comment]
I thought that this may already have been enabled, but there is no throttling configuration in Terraform — I was incorrect. This is not implemented.
