### ISSUE TITLE
Create onboarding checklist

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#473]
When someone joins the team to contribute to EF-CMS, we will want to have an onboarding checklist of things for them in order to get up to speed for procedures and processes as documented in our Operating Plan. Include information about reading specific pieces of documentation, knowing how to get at contact information, as well as people they need to know.

Onboarding plan/checklist for 
- product owner
- product specialist
- devops engineer

**Comment by adunkman** [comment]
@julialeague (thanks!) gave us a great place to start with her [previous onboarding documentation](https://docs.google.com/document/d/1ktys8x_XcFGCto1wxL5uUeAZlk87lOr31FRrZOuL_8g/edit).

**Comment by mmarcotte** [comment]
@vickimcfadden can you help with the product roles? 🙏

**Comment by adunkman** [comment]
Spinning up a WIP pull request with some updates to documentation.

**Comment by mmarcotte** [comment]
@vickimcfadden , @adunkman , and @mark-meyer meeting Thursday to hammer some of these details out for onboarding docs. (ty) 👍
