### ISSUE TITLE
Consider using a security scanner to catch insecure infrastructure configuration.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#477]
Broken out of #250, consider introducing a scanner for ensuring terraform configuration is secure. GitHub’s [super-linter](https://github.com/github/super-linter) seems to be a good option, which uses [tflint](https://github.com/terraform-linters/tflint) for identifying formatting/known linter problems and [terrascan](https://github.com/accurics/terrascan) for identifying security risks.

This can be addressed post-MVP, and labeled as such.

**Comment by adunkman** [comment]
For a personal project, I recently attempted to use `terrascan` and found that ignoring scan results was not supported. This is important because some potential security risks are by design — for example, public S3 buckets is a flagged security risk, but if you are hosting a website from the bucket, it’s an accepted risk. 

I found that [tfsec](https://www.tfsec.dev/) was much more mature (implemented in https://github.com/adunkman/unfurl/pull/3). Here’s [an example of ignoring a ruleset](https://github.com/adunkman/unfurl/blob/27be97bc57f58739451c1c5cd85d35ed2c3bf9f8/terraform/ui.tf#L1-L16) from that project:

```hcl
# tfsec:ignore:AWS002 tfsec:ignore:AWS017
resource "aws_s3_bucket" "ui" {
}
```

**Comment by mmarcotte** [comment]
Look for dupe card in Trello backlog from Cody

**Comment by mmarcotte** [comment]
Covered in Trello backlog, and it's a good idea.
