### ISSUE TITLE
TASK: Get IRS Environment working correctly

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#478]
- [x] Deploy 50.5 to IRS environment for their testing
- [ ] Address bug uncovered from testing https://github.com/flexion/ef-cms/issues/6890

**Comment by mmarcotte** [comment]
ustaxcourt/ef-cms-flexion#503 and ustaxcourt/ef-cms-flexion#504  appears to have addressed outstanding issues with the IRS environment. NOTE: I did have to manually switch the API URL until https://github.com/flexion/ef-cms/issues/6864 is merged in.
