### ISSUE TITLE
TASK: Dry-Run into Test Environment

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#479]
- [x] Take down test environment
- [x] Deploy latest
- [x] Sync documents
- [x] Load Court Users 
- [x] Load Petitioners
- [x] Load Practitioners
 - [x] ...

**Comment by mmarcotte** [comment]
Logged some bugs/issues in the Migration Repo to handle errors.

One lesson learned is to ensure we are hitting the right color API during the migration. 

All told Elasticsearch behaved really well this time. We used 3 x m5.large @ 100GiB

Kibana Elasticsearch had to be beefed up to handle the influx.
