### ISSUE TITLE
Update Review Checklist and add a PR template for Flexion pull requests

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#484]
As the court, we need to update our QASP checklist for PRs to the courts, so that we can ensure they're relevant for smaller change sets.

Also need a PR template to ensure the PR is set up adequately for a successful review.

**Comment by adunkman** [comment]
Introduced in #485.

Remaining tasks: 
- @julialeague in discussion with @mariahkannenberg to get alignment & tweak if needed.

**Comment by adunkman** [comment]
Latest update: Court alignment needed, reprioritizing given other tasks.

**Comment by adunkman** [comment]
Closed in #485!
