### ISSUE TITLE
Dry-Run into Migration Environment

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#512]
- [x] What happens with Petitioners who are also Practitioners?
- [x] Mark to rerun closed cases from 80s and 90s to see if we solved a bug for organization names.
- [x] Create ticket to address not being able to login as an admin?

**Comment by mmarcotte** [comment]
Can't log in to an admin

Found bug with names of organizations. Mark is going to re-run some closed cases from the 80s and 90s.

**Comment by mmarcotte** [comment]
Q: What happens with Petitioners who are also Practitioners?
A: They become petitioners as part of the migration process. Even though we load them as practitioners first, the entity gets overwritten when the case is migrated with petitioner information.

**Comment by mark-meyer** [comment]
Remigrated closed cases from 80s and 90s with no issues.
