### ISSUE TITLE
Adjust logging to encompass data needed for auditing of the application.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#519]
Acceptance criteria: 

- [x] AWS credentials are never logged.
- [x] Logging patterns are documented and shared with the development team.
- [x] All log statements needed for auditing events are added.

Tasks:

- [x] Look for and remedy any logging of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
- [x] Write documentation of on how logging should be done in the application, including usage of log levels.
- [x] Complete below list of specific cases where logging is required for auditing purposes.

Ensure logged or add logs for:

- [x] Successful and unsuccessful account logon events
- [x] Account management events
- [x] Object access — examples: reading database records or files on disk
- [x] Policy changes
- [x] Privilege functions
- [x] Process tracking
- [x] System events
- [x] Web applications:
  - [x] All administrator activity
  - [x] Authentication checks
  - [x] Authorization checks
  - [x] Data deletions
  - [x] Data access
  - [x] Data changes
  - [x] Permission changes

References: 

- NIST Special Publication 800-53 (Rev. 4), Security and Privacy Controls for Federal Information Systems and Organizations
  - [Content of audit records](https://nvd.nist.gov/800-53/Rev4/control/au-3)
  - [Audit events](https://nvd.nist.gov/800-53/Rev4/control/au-2)
- [Logging guide](https://before-you-ship.18f.gov/infrastructure/logging/) 18F’s Before You Ship guide has a nice summary.

**Comment by vickimcfadden** [comment]
@adunkman can help with application logs; @mmarcotte can help with AWS logs.

**Comment by adunkman** [comment]
I’m going to take a first pass at these!

**Comment by adunkman** [comment]
Unfortunately we don’t have visibility into failed logins with Cognito to satisfy "AWS: Cognito user login (and login failure)" —

> [Hosted UI … calls are currently not included in CloudTrail logging events.](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-cognito-user-pools-now-supports-logging-for-all-api-calls-with-aws-cloudtrail/)

We can however see when the API exchanges temporary codes for access tokens, so we can at least see when users are successfully authenticated.
