### ISSUE TITLE
Adjust logging to encompass auditing cases, removing of secrets.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#524]
- [ ] Look for and remedy logging of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
- [ ] Define guidance on how logging should be done in the application. 
- [ ] remove instances where console.log(...) to use one of `applicationContext.logger`:
  - [ ] `.error('errorMessageHere', err)`: an error has occurred, log this and include an object for context
  - [ ] `.warn('highVolume', data)`: useful for logging warnings about activity. Include any relevant info in data
  - [ ] `.notice('userLogin', user)`: useful for metrics and auditing the application's activity
  - [ ] `.info('message here', data)`: not logged to production, but light debugging in lower environments
  - [ ] `.debug('verboseLog', data)`:  messages you want to see for the developer, will not be logged on deployed instance
- [ ] Flesh out and define where audit logging needs to be added.
- [ ] Add audit logging.

**Comment by vickimcfadden** [comment]
@adunkman to merge/groom with other logging issue (#519).

**Comment by adunkman** [comment]
Groomed into #519, all tasks tracked there.
