### ISSUE TITLE
Move Kibana Index Template to codebase (req Terraform 0.13)

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#528]
Right now we must manually specify the Index Template for the Kibana instance that helps scours the Cloudwatch logs via Elasticsearch. #526 introduced this change.

When we switch to Terraform 0.13, we can implement [a promising Terraform Elasticsearch provider](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs) to help manage the template with code. It would involve isolating the template into its own file, and then referencing it in Terraform via a URL.

**Comment by adunkman** [comment]
Replaced by [Use Terraform for managing Elasticsearch index configuration](https://trello.com/c/7tYWB1Zh/937-use-terraform-for-managing-elasticsearch-index-templates) in the refactoring backlog!
