### ISSUE TITLE
Create a toggle for maintenance mode

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#553]
Without requiring a deployment, we need to devise and implement a switch that would turn the application into read-only maintenance mode. The application would not be able to receive writes to DynamoDB or Elasticsearch.

**Comment by vickimcfadden** [comment]
@adunkman to add ticket to Flexion's backlog.

**Comment by adunkman** [comment]
Reported as https://github.com/flexion/ef-cms/issues/7095 — I believe that handles this ticket and will close this issue, but feel free to reopen @mmarcotte if you wanted to track it here as well or if this represents any outstanding work.
