### ISSUE TITLE
Create failover configuration for the application's lambdas

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#586]
Although we have us-east-1 and us-west-1 API gateways set up for the application's lambdas, we don't currently support automatic failover between regions. If a region becomes unavailable, it would be desirable to have traffic re-routed to another available region so that users of Dawson won't experience a service disruption.

## Pre-Conditions
* Research into the best failover configuration approach for the application's lambdas
## Acceptance Criteria
* Configuration as code provided for us-east-1 --> us-west-1 failover
## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Configuring Route53 to failover lambdas based on health checks seems like a useful strategy: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover.html 

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by adunkman** [comment]
Don’t we have multiple API Gateways configured, in us-east-1 and us-west-1? I vaguely recall those existing…

**Comment by julialeague** [comment]
I wasn't able to reproduce the failover issue I previously experienced while testing against the latest code in exp1. Looking into it, I see that a latency-based routing policy was created in route 53 for all of the endpoints in late October! I suspect that my original test was performed against code that didn't already have the latency routing policy, and the introduction of that has resolved the issue. Great to see!
