### ISSUE TITLE
BUG: Timeout for inactivity isn't working right

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#589]
**Describe the Bug**
Court users are not getting kicked or presented with proper messaging when their session times out due to inactivity. Instead they appear to remain logged in, and their attempts to search for docket numbers returns a message that the docket number doesn't exist. It's not until they click around do they get kicked back to the login screen. 

**Business Impact/Reason for Severity**
It's confusing to the user.

**In which environment did you see this bug?**
USTC-Prod

**Who were you logged in as?**
Any user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Not doing anything for a period of activity. Then searching for docket numbers that should exist.

**To Reproduce**

1. Log on to the site
2. Click around
3. Don't do anything for a while
4. Try to search for a docket number that should exist
5. DAWSON reports that the docket number doesn't exist

**Expected Behavior**

DAWSON should inform you gracefully and let you know that you have been logged out for inactivity.

**Actual Behavior**

DAWSON reports that the docket number doesn't exist

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by vickimcfadden** [comment]
Mike to try and recreate. Jessica is experiencing how it _should_ work.

**Comment by adunkman** [comment]
Related to https://github.com/flexion/ef-cms/issues/7501 in Flexion’s backlog to address a specific case. This issue is to assess the global pattern for inconsistencies — Mike has seen issues when a computer is asleep overnight and the UI doesn’t report a logout event, leading to the UI showing zero cases/items in lists.
