### ISSUE TITLE
Make Upload Progress Alerts more friendly to Screen Readers

### ISSUE THREAD

**Issue by echappen** [ustaxcourt/ef-cms#599]
Currently when uploading documents, screen reader will repeat upload message multiple times instead of announcing actual progress. 

This could be refined using `progressbar` Aria roles to make screen reading for uploads more insightful, and less verbose and redundant. [Learn more](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role#:~:text=The%20progressbar%20role%20should%20be,toward%20completing%20the%20requested%20action.).

#### Recommendation
Recommended screen reading would be announcing a custom alert message once ("Less Than 1 Minute Left"), then announcing actual percent progress as number changes. 

#### Steps to Reproduce
- turn on VoiceOver for Mac
- complete creating a case
- upload a case, listen to progress alerts from modal

**Comment by JessicaMarine** [comment]
Moved to Flexion: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8101
