### ISSUE TITLE
Mobile Layout Refinements

### ISSUE THREAD

**Issue by echappen** [ustaxcourt/ef-cms#612]
#### Issues
- [ ] [Create a case](https://app.stg.ef-cms.ustaxcourt.gov/before-filing-a-petition) instruction accordions could be full-width on mobile
Currently they're only ~60% width and it makes reading the accordion content awkward.
- [ ] "Deployed At" timestamp often overlays on top of buttons, making the buttons un-tappable. 
Continued scrolling solves it, but this could be confusing to general users. 
- [ ] When pop-ups are blocked in mobile Safari, tapping links to files does nothing, giving the impression that links are broken. Since file viewing is critical to user flows, a pre-emptive alert to allow pop-ups may help. 

Issues found though [mobile testing on 12/3/2020](https://github.com/ustaxcourt/ef-cms/issues/251)

**Comment by JessicaMarine** [comment]
@echappen Good news! ustaxcourt/ef-cms#6492 will be removed on prod. and ustaxcourt/ef-cms#6493 already has a fix coming for it!!

**Comment by echappen** [comment]
@JessicaMarine 🙌 🙌

**Comment by JessicaMarine** [comment]
Moved to Flexion: https://github.com/flexion/ef-cms/issues/4010
