### ISSUE TITLE
Practitioner email addresses need updating

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#613]
Practitioners have email addresses that need to be updated to create user accounts. Jessica has CSV of users. 
[Practitioners.Bad.or.Invalid.Emails(Admissions).xlsx](https://github.com/ustaxcourt/ef-cms/files/5803644/Practitioners.Bad.or.Invalid.Emails.Admissions.xlsx)
[Practitioners_no_email (Admissions).xlsx](https://github.com/ustaxcourt/ef-cms/files/5803645/Practitioners_no_email.Admissions.xlsx)

Mike Marcotte to create cognito accounts and associate with user records.

**Comment by JessicaMarine** [comment]
[Practitioners.Bad.or.Invalid.Emails(Admissions).xlsx](https://github.com/ustaxcourt/ef-cms/files/5697974/Practitioners.Bad.or.Invalid.Emails.Admissions.xlsx)
[Practitioners_no_email (Admissions).xlsx](https://github.com/ustaxcourt/ef-cms/files/5697975/Practitioners_no_email.Admissions.xlsx)

Also --
1. Bobbie Collins (Bar No. CB0333) needs her email updated: bcollins@lrrc.com to bobbie@nussbuamspeir.com 
2. Confirm email for Michael Moirano (Bar No. MM0876) is mmoirano@mgklaw.com.  If not, update.

**Comment by mark-meyer** [comment]
Neither Bobbie Collins nor Michael Moirano have email/cognito accounts in the system. Michael Moirano's email was not in the legacy DB and Bobbie Collins' was flagged as a bounced/bad email. They both will need to be added when we add the others.

**Comment by mark-meyer** [comment]
An issue has been created for Flexion to create an API that will allow us to address this issue: https://github.com/flexion/ef-cms/issues/7377
