### ISSUE TITLE
Investigate Cognito failover strategy to determine if we need to do a customized Cognito rollover

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#636]
Team to investigate how often there is an AWS outage (like we experienced before Thanksgiving) to see how often we anticipate this happening and whether we need to do work to resolve.

**Comment by adunkman** [comment]
Risk level is low, fallout is high. Would not be able to pick up implementing a failover now due to other pressing issues. Would like to have the data before implementation.

**Comment by adunkman** [comment]
Wanted to clarify on the scope of this issue — for Jessica and Mike to make an informed decision about how to plan for an outage, they would like to know statistics on how often Cognito experiences service outages.

**Comment by julialeague** [comment]
From AWS's documentation, it looks like there is about 1 major outage per year, give or take:

https://aws.amazon.com/premiumsupport/technology/pes/

<img width="976" alt="Screen Shot 2021-01-12 at 2 07 41 PM" src="https://user-images.githubusercontent.com/51330839/104381276-0ef14600-54e1-11eb-93ed-943d7ac8774f.png">

From those documented service outages, the one we experienced in November is the *only* outage that mentions Cognito as an affected service. Does this mean that Cognito has only experienced an outage event once in its lifetime? I'll try to find any other documentation about this, but from what Amazon has published, that seems to be the case.

**Comment by julialeague** [comment]
I haven't been able to find any other significant documentation surrounding AWS service outages, so I'm taking the previously-posted link as canon. 

I think it's safe to assume that Cognito will experience ocassional service "blips" that may cause some brief connectivity issues, but it doesn't typically go down for prolonged periods of time, given what we know.

@mmarcotte @JessicaMarine, do you have any questions about this? Do you think asking an AWS rep to share their knowledge of Cognito outages would be helpful? I doubt they'll say much more than what's already documented publicly, but maybe they'll have some insight into how often you might see service "blips".

**Comment by adunkman** [comment]
Decision made in a meeting just now by @JessicaMarine that once a year, once documented is an acceptable risk for now, and we can revisit if concerns arise in the future about availability.
