### ISSUE TITLE
Determine AWS failover architecture strategy

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#637]
There are two standard types of failover strategies used within AWS - [active-active and active-passive](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-types.html). 

From the AWS documentation:

> **[Active-active]** Use this failover configuration when you want all of your resources to be available the majority of the time. When a resource becomes unavailable, Route 53 can detect that it's unhealthy and stop including it when responding to queries.

> **[Active-passive]** Use an active-passive failover configuration when you want a primary resource or group of resources to be available the majority of the time and you want a secondary resource or group of resources to be on standby in case all the primary resources become unavailable. When responding to queries, Route 53 includes only the healthy primary resources. If all the primary resources are unhealthy, Route 53 begins to include only the healthy secondary resources in response to DNS queries.

Failover Strategy AWS Documentation: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-types.html

We should take some time to determine which of these strategies we want to follow so that we have a holistic plan for failover configuration for all of the components in the EF-CMS application.

**Acceptance Criteria**
* Determine which failover strategy we want to use for Dawson
* Log any necessary issues or update any existing issues to ensure we follow the strategy for each component in Dawson

**Comment by adunkman** [comment]
I’m not sure what this means — would you be able to provide more detail? 🤔

**Comment by julialeague** [comment]
> I’m not sure what this means — would you be able to provide more detail? 🤔

I updated the description to provide actual detail, sorry about that!

**Comment by adunkman** [comment]
Our current strategy is active-active for API calls and active-passive for static files.

- All API Gateway resources are [latency-routed](https://github.com/ustaxcourt/ef-cms/blob/5e09e549f17b8aa2877097c8c4c4f28d1a1fbd47/web-api/terraform/api/api.tf#L325-L327) between us-east-1 and us-west-1 in Route53. This includes: 
  - `api.dawson.ustaxcourt.gov`
  - `api-blue.dawson.ustaxcourt.gov`
  - `api-green.dawson.ustaxcourt.gov`
  - `dynamsoft-lib.dawson.ustaxcourt.gov`
  - `public-api.dawson.ustaxcourt.gov`
  - `public-api-blue.dawson.ustaxcourt.gov`
  - `public-api-green.dawson.ustaxcourt.gov`
  - `ws-blue.dawson.ustaxcourt.gov`
  - `ws-green.dawson.ustaxcourt.gov`


- All Cloudfront resources are failover-routed ([frontend](https://github.com/ustaxcourt/ef-cms/blob/5e09e549f17b8aa2877097c8c4c4f28d1a1fbd47/web-client/terraform/ui/frontend.tf#L77-L79), [frontend-public](https://github.com/ustaxcourt/ef-cms/blob/5e09e549f17b8aa2877097c8c4c4f28d1a1fbd47/web-client/terraform/ui/frontend-public.tf#L81-L83)) through Cloudfront Origin Groups, preferring `us-east-1` and failing over to `us-west-1`. This includes: 
  - `dawson.ustaxcourt.gov`
  - `www.dawson.ustaxcourt.gov`
  - `blue.dawson.ustaxcourt.gov`
  - `green.dawson.ustaxcourt.gov`
  - `app.dawson.ustaxcourt.gov`
  - `app-blue.dawson.ustaxcourt.gov`
  - `app-green.dawson.ustaxcourt.gov`

**Comment by mmarcotte** [comment]
Outstanding ot have this documented. Thank you @adunkman !
