### ISSUE TITLE
Scripts for top 10 most likely help desk questions

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#654]
As the Admissions Clerks and eHelp Specialist, I need scripts for the most likely questions, so that I can accurately and efficiently provide support to users.

- [ ] @vickimcfadden to draft top 10 questions
- [ ] Court to review for accuracy of answers and completeness 
- [x] @adunkman to add some helpful phrases for de-escalation snippets
- [ ] Court to post answers somewhere accessible

**Comment by vickimcfadden** [comment]
Draft script: https://docs.google.com/document/d/1VceFYUzfTQYNXnywtuA4zL_3rbNcSyLzWVOdM9oiKdg/edit

**Comment by adunkman** [comment]
Dropped in some of the most useful snippets I could think of — happy to help further if needed, just pull me back in! 🎉
