### ISSUE TITLE
Check to see how larger PDFs perform

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#661]
We have some real large PDFs. Let's get a basis for how they perform with DAWSON.

- Large PDFs are ones that are between 1-2GB in size.

Understand how a file of this size performs when: 

- Serving the file (a coversheet is attached)
- Downloading a trial session (it is included in a ZIP archive)

If it does not perform, explore adjusting resources available to the lambda functions used.

**Comment by adunkman** [comment]
I’m hitting #702 when attempting to look up these cases — one example is `mig`’s largest PDF:

```json
[
    {
        "Key": "ef12e082-3515-4a9c-8807-0d679036f8a1",
        "LastModified": "2020-11-24T21:16:17+00:00",
        "ETag": "\"ac24dec9264bad5a0cd4c49a009e7639-256\"",
        "Size": 2145386497,
        "StorageClass": "STANDARD"
    }
] 
```

Looking at Elasticsearch, this is case 15011-14. Attempting to workaround the issue to specifically trigger the intended actions.

**Comment by adunkman** [comment]
I was able to workaround the above and calendar a trial with large PDFs. When attempting to download a trial session’s cases (causes all documents to be zipped), the download request starts as expected, and the UI stalls in progress. 

![image](https://user-images.githubusercontent.com/14930/103022840-c1556f00-451a-11eb-9847-0b8eed3ae54f.png)

The websocket continues to report status at regular intervals:

```json
{"action":"batch_download_progress","entries":{"total":100,"processed":100},"fs":{"totalBytes":0,"processedBytes":0},"numberOfDocketRecordsToGenerate":2,"numberOfFilesToBatch":101}
{"action":"batch_download_entry","name":"15011-14, [REDACTED].pdf","type":"file","date":"2020-12-23T17:25:52.429Z","mode":420,"prefix":null,"sourcePath":null,"stats":false,"sourceType":"buffer","linkname":null,"store":false,"comment":"","numberOfDocketRecordsToGenerate":2,"numberOfFilesToBatch":101}
```

Looking at the async lambda logs, we see the process has crashed:

```json
{
    "errorType": "RangeError",
    "errorMessage": "Array buffer allocation failed",
    "stack": [
        "RangeError: Array buffer allocation failed",
        "    at new ArrayBuffer (<anonymous>)",
        "    at new Uint8Array (<anonymous>)",
        "    at new FastBuffer (internal/buffer.js:949:1)",
        "    at createUnsafeBuffer (buffer.js:148:12)",
        "    at allocate (buffer.js:418:10)",
        "    at Function.allocUnsafe (buffer.js:383:10)",
        "    at Function.concat (buffer.js:563:25)",
        "    at bufferConcat (/var/task/api.js:958556:17)",
        "    at ConcatStream.getBody (/var/task/api.js:958503:42)",
        "    at ConcatStream.<anonymous> (/var/task/api.js:958476:51)"
    ]
}
```

The report indicates the memory usage: 

```
REPORT RequestId: aac616f9-99d7-44e1-9baf-a5573903b4b5	Duration: 46178.43 ms	Billed Duration: 46179 ms	Memory Size: 3008 MB	Max Memory Used: 2397 MB
```

**Comment by adunkman** [comment]
Confirmed this is a memory management problem; adding additional memory causes the task to succeed as designed. 

```
REPORT RequestId: 826c64d0-afad-46e4-80b5-072d23b28a25	Duration: 146777.46 ms	Billed Duration: 146778 ms	Memory Size: 5000 MB	Max Memory Used: 4700 MB	Init Duration: 2330.43 ms
```

**Comment by adunkman** [comment]
The largest PDF which we may need to add a coversheet is either the largest unserved migrated PDF, or the largest possible attachment. The largest unserved migrated PDF is 1.7mb, well below the maximum upload of 250mb.
