### ISSUE TITLE
Automate Petitioner Getting eAccess to Case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6617]
## Story 1 -- Petitioner Requests Access
As a Petitioner, in order to get electronic access to a case, I need the ability to request access.  

**Pre-Conditions:**
* Petitioner already has case in the system and is getting paper service

**Acceptance Criteria:**
* Petitioner has the ability to create an account (DONE)
* Petitioner is aware that they can associate themselves to a case, using a separate process each time. 
* Petitioner has the ability to find the case they want to be added to
* Petitioner is allowed to request access to a sealed case by docket number. Only public view of case should display
* Petitioner has the ability to request electronic access to the case
* Petitioner needs to provide their name and address for validation that they are who they are.
* Petitioner is aware what cases they've requested access to
* If petitioner tries to request access to the case again while the request is pending, they're not able to make the request

## Story 2 – Admissions Clerk: Process Petitioner's Request for Electronic Access to Case
As an Admissions Clerk, in order to provide a petitioner electronic access to his/her case, I need the ability to process that request.

** Pre-Conditions **
* Petitioner has made request for electronic access to case 

** Acceptance Criteria: **
* Admissions clerk can select which petitioner on the case the request is for
* Admissions clerk has the ability to print and mail a letter to the petitioner that includes a unique access code to access the case that is generated by the system
* Letter informs the petitioner that electronic access has been requested for the case and instructs them what to do next
* A copy of the letter is saved in the Correspondence file of the case.

## Story 3 – Petitioner: Gain Electronic Access to Case ##
As a Petitioner, so that I can interact with the Court electronically, I need to gain access to my case(s) electronically.

** Pre-Conditions: **
* Petitioner has made request for electronic access to case 
* Admissions Clerk has processed petitioner’s request

** Acceptance Criteria: **
* Petitioner receives unique code to access case (done in paper)
* Petitioner can return to case in DAWSON and enter code
* Upon entering code, petitioner is given access to case:
   * It shows on their dashboard
   * They have the associated view
   * They can e-file documents
   * Service information is updated to "electronic"
   * They begin receiving electronic service at the email that was added

## Notes
* Note: even though admissions clerks can't see a sealed address, it's okay that the address displays on the printed copy. 
* In future, consider adding controls to disallow users from requesting access based on certain criteria.
* Once the petitioner has made request for access, how do we know how to link them to the right person that's on the case?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by mmarcotte** [comment]
This is going to satisfy a growing number of support tickets! Thanks for prioritizing it.

This needs figuring out:

- How to we verify the identity of an individual? 
- Do they need to file something via paper in order to make the switch?

It would be great to figure out a way to allow them to do this via the App:

- we may have their phone number, and we could possibly use it for messaging / verification
  - they navigate to their case
  - there's a button available "i'm the petitioner; please associate this with my account"
  - if they clicked on it, they could be asked to enter the phone number
  - we could send an SMS to that phone number with a 6 digit code
  - and they could use that to be able to verify their identity and be able to specify an email address (or their current account if they already created one)
- if we don't have their phone number, we could have an item go into some qc inbox to verify their identity
- add to the language about how to switch to electronic service for a case (around where we describe how to file a petition... "Want to switch to Electronic Service for an existing case? ...")

**Comment by cholly75** [comment]
Already done.
