### ISSUE TITLE
Court User: Make Procedural Notes Permission Based

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6731]
Allow multiple procedural notes.
Only person in same section can modify/delete procedural note.

## Pre-Conditions
* Case exists in the system.

## Acceptance Criteria
* Internal User can provide a case-level procedural note that anyone in the Court can view. 
* Only person in same section can modify/delete note. (Permission)

## Research/Analysis Notes
* Previous design discussion suggested that these notes might be another tab on the case detail page.

## Definition of Done
- [ ] acceptance criteria have been met
- [ ] Field level and page level validation errors (front-end and server side) integrated and functioning
- [ ] all code changes have been reviewed, approved, and merged and deployed to develop 
- [ ] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [ ] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [ ] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [ ] 0 errors reported in manual a11y testing
- [ ] all new functionality verified to work with keyboard and osx voiceover
- [ ] all code quality checks are passing - sonar, eslint, html validation, etc.
- [ ] code refactored for clarity and to remove any known technical debt 
- [ ] application can be deployed to multiple regions
- [ ]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [ ] performance tests successfully completed and no new significant performance issues found
- [ ] alerting and monitoring for new functionality in place and successfully exercised
- [ ] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [ ] npm audit for CVE’s in production library/module dependencies identified and resolved
- [ ] library/module dependencies are up-to-date and are at the latest resolvable version

**Comment by klohman** [comment]
@mariahkannenberg @JessicaMarine Could we combine this story with[#338 Case Notes]( https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/338)
