### ISSUE TITLE
Perform load tests in the Migration environment

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#679]
With a focus on public search, let's try to measure how ES is performing.

**Comment by adunkman** [comment]
Completed Friday; results archived in [Google Drive](https://drive.google.com/drive/folders/1ZpLt36vgYycCF77qAZoxl4e411Sp1GAI) and delivered directly to @mmarcotte via Slack. Additionally, improved documentation and developer experience of the load testing tooling in https://github.com/ustaxcourt/ef-cms-load-tests/pull/3. 

I believe this is complete; let me know if there is remaining work to be done and we can re-open!
