### ISSUE TITLE
Export database into different account — AWS Glue

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#682]
Goal: Enable Flexion to test in a production-like data environment, including the contents of documents. 

TODO: 

- [x] Consider whether we want to create a stream so other environment's data is always up-to-date. 
- [x] Determine approach: should we migrate from DynamoDB to DynamoDB, or use the migration scripts and endpoints? 
- [x] Identify data that should not be migrated or redacted (@JessicaMarine is working on this)
- [x] Perform the migration
- [x] Document how to do it again in the future
- [x] Sync PDFs
- [ ] Create a script to assume the identity of another user in the system

**Comment by adunkman** [comment]
May make sense to migrate _all_ PDFs with contents. Prioritized after launch.

**Comment by adunkman** [comment]
#793 is related.

**Comment by mark-meyer** [comment]
Mike and I talked about the first todo:  (`Consider whether we want to create a stream so other environment's data is always up-to-date`) and realized we probably don't want to do this. Day-to-day use of the migration environment may include writing/deleting/updating rows which could cause validation issues if that data no longer aligns with data coming from the production DB. This will mean periodically syncing the migration environment as needed.
