### ISSUE TITLE
Additional logic - iterations for eFiled docs

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6825]
Put measures in place to limit confusion around duplicate uploads and iterations of documents. 

When picking a First, Second, or Third iteration of a document, you should be prompted to pick the right thing (i.e., if you haven't filed a First of something, it shouldn't allow you to file a Second or Third; if you've already filed a First & Second of something, it should only allow you to file a Third)

**Comment by cholly75** [comment]
Closing - addressed in ustaxcourt/ef-cms#8020
