### ISSUE TITLE
IRS Attorney Interviews

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6878]
Report: https://docs.google.com/presentation/d/1Wcj4TJ7Bq7sHUoMdH_O3huennZ7wBy8BsDgz8WjD9fw/edit?usp=sharing

### MVP Candidates

* Show deadlines associated with specific cases or documents in the context of a case (e.g. on the case detail page). (This would be a HUGE win for them and also benefit the court in terms of IRS ability to manage and meet deadlines - could be useful for pro se and practitioners as well if we introduce deadlines outside of court users.) (Possibly related to ustaxcourt/ef-cms#6705)
* Links to helpful resources (e.g. USTC Rules and updated eFiling Guide; list of documents, such as the one provided in the eFiling Guide or the new browse document list view; helpful reports, such as for deadlines and case activity; case lists, e.g. by field office, user, etc.). (These could be helpful links in a dashboard sidebar.) (Possibly related to ustaxcourt/ef-cms#6705)
* Show deadline metadata  / order dates for deadline tracking (e.g. Next 5-10 Deadlines list on the dashboard, all deadlines report, case activity report) (Related to ustaxcourt/ef-cms#6669)

**Comment by cholly75** [comment]
Case deadlines to be addressed for external use in revamp of party dashboards.
