### ISSUE TITLE
Court: Dynamsoft License (Re-visit Yearly)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6884]
As the Court, in order to make sure we are storing our licenses in the proper place, we need to reconsider periodically where licenses are housed.

Flexion recommended, and the Court agreed, for the CMS to use a COTS product -- Dynamsoft -- for the direct scan function for internal users.  The Court would have preferred to house the licensed software in S3 or on GitHub, but Dynamsoft required the software to be stored on an Ec2 instance.

## Acceptance Criteria:
* Revisit whether Dynamsoft's licence still prevents it from being stored in S3 or on GitHub

## Note:
* Consider whether to add additional story to backlog to check on this again at some point in the future.

**Comment by cholly75** [comment]
Duplicate.
