### ISSUE TITLE
Orders: Clean up of text editor formatting

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6891]
## Acceptance Criteria
Pain Point from Jessica during demo 
- [ ] View of the generate box - increase size of text shown so it's easier to read
- [ ] Ensure that the text editor is using the same font as generated PDF (Nimbus Roman, 14pt)

Notes from ustaxcourt/ef-cms#6649 review:

- [ ] Pasted text with different font sizes is show showing in text editor 
- [ ] Unordered list is not retained when pasted from Word doc (pasted only as plain text)
- [ ] Ordered list is not retained when pasted from Word doc (pasted only as plain text)
- [ ] when pasting additional text in text editor, screen jumps back to top each time
- [ ] Add error message on create order when no text is entered into editor 

User feedback post-launch
- [ ] When I create an order in Dawson and add the language for some reason it does not hold my spacing once I save and generate the order. Basically, when I add two spaces behind a period and save. It’s not there when I generate the order, it goes back to one space behind a period. (Lisa Allen -- CA)
- [ ] The font when orders are drafted or generated is too small. And if you increase the font while drafting, any time you start a new paragraph, it reverts to the smaller font size. (Judge Buch and several other judges)
- [ ] When drafting orders, the system frequently (more often than not) but not always removes the leading tab from the first paragraph of an order. Often it does this when you save the order, so right after saving you have to go back in and re-add the tab. If you later edit the order, it might delete that leading tab again. (Judge Buch and several other judges)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by cholly75** [comment]
No longer needed.
