### ISSUE TITLE
Judge: Ability to see pending motions, OSC, etc. in my cases (POST-MVP)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6917]
As a Judge, in order to properly manage all of my cases, I need to see all pending motions, OSC, etc. all in one place.

## Notes:
* Consider adding "Pending items" to dashboard
* Include pending motions on Judge’s Dashboard

**Comment by cholly75** [comment]
Pending motions available on Pending Items report; Judge dashboard reflects pending motions outstanding for > 120 days.
