### ISSUE TITLE
Judge: Ability to run calendar call/trials without internet (POST-MVP)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6923]
As a Judge, in order to avoid a disruption in my work, I need the ability to run calendar call and trials without internet service.

* ability to access working copy of trial session without internet access
* ability to sort/filter, set trial status, take notes, etc. on working copy without internet access
* ability to import notes back into CMS when internet access restored

**Comment by cholly75** [comment]
Duplicate of ustaxcourt/ef-cms#6589
