### ISSUE TITLE
Session Copy Update: New Trial Status Values

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6950]
As a trial clerk, judge, or CA, I need the Session Copy page updated to more accurately reflect the status of a particular case in the session.

Based on user feedback, the Court would like to perform updates to the Session Copy page.  This includes updating the list of Trial Status values and filters on both the screen and printable views of the Session Copy.  

IMPORTANT: See Notes section for details on change management for this feature.

## Acceptance Criteria:
* The current list of dropdown list selections and their corresponding filter is modified as follows:
  - Remove "Set for Trial"
  - Remove "Dismissed"
  - Remove "Settled"
  - Change "A Basis Reached" to "Basis Reached"
  - Change "Taken Under Advisement" to "Submitted/CAV"
  - Change "Status Unassigned" to "Unassigned"
  - Add "Probable Settlement"
  - Add "Probable Trial"
  - Add "Definite Trial"
  - Add "Motion"
* Where a value is changed ("A Basis Reached", Taken Under Advisement", "Status Unassigned"), if any cases are currently assigned to the old value, update the trial status on those cases to the new value
* Where a value is changed ("A Basis Reached", Taken Under Advisement", "Status Unassigned"), update the selectable option on the Trial Status dropdown list from the old value to the new value
* Where a value is changed ("A Basis Reached", Taken Under Advisement", "Status Unassigned"), update the corresponding Show Cases By Trial Status filter with the new value
* Where a value is removed ("Set for Trial", "Dismissed", "Settled"), remove that value as a selectable option on the Trial Status dropdown list
* Where a value is removed ("Set for Trial", "Dismissed"), if any cases are currently assigned to the old value, do NOT remove this value from those cases (see Notes below on change management plan)
* Where a value is removed ("Set for Trial", "Dismissed", "Settled"), remove that filter from the Show Cases By Trial Statis list of filters
* Where a value is added ("Probable Settlement", "Probable Trial", "Definite Trial", "Motion"), add that value as a selectable option on the Trial Status dropdown list
* Where a value is added ("Probable Settlement", "Probable Trial", "Definite Trial", "Motion"), add that filter to the Show Cases By Trial Status list of filters
* Where a value is being neither removed, changed, or added ("Rule 122", Recall", "Continued"), do NOT make any changes to the filter, dropdown menu, or Trial Status value for cases with that value assigned
* Printable version of Session Copy screen should reflect the above changes
* These changes are implemented for all Session Copy views, regardless of user role
* Implement behind feature flag if possible
* NEW AC (see comment): Where the value "Settled" exists on a case in a trial session copy, change that assigned value to the new value of "Basis Reached".
## Notes
Screenshot of desired ordering on Show Cases By Trial Status and dropdown list:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/3831ce41-bf82-43dc-9c51-5f2a0c4fcd1c)

Change Management Notes:
* Due to Court seasonal schedules for trial sessions, we have a limited window of time in which we can implement these changes without adversely causing confusion or lost data. We will need to go live with these updates some time between 12/24 and the New Year. Ideally we would like to have these changes in place in the live environment prior to that, and activate them via feature flag when given approval to do so.
* Users will be instructed post-activation to immediately review any Trial Sessions to which they are assigned and update any Trial Status deprecated values assigned to cases to an appropriate value from the new set. We will instruct them to make sure the "Show All" filter is selected when doing so in order to capture all cases in this review.
* If we cannot implement behind feature flag, we will need to time dev/testing/release to accommodate this specific launch window

**UX Notes**
Discussed with @TomElliottFlexion :
- the default dropdown selection will be "Unassigned" and replaces "-Trial Status-"
- keep "Unassigned" in the last position in the checkbox list
- values that are removed will display in the dropdown and list until user changes it
- possibly adding a notification banner at the top of the page that informs user of trial status changes that only displays the first time they navigate to the page after implementation
- how was the order of the list determined?

Complete list in order:
Unassigned
Probable Settlement
Probable Trial
Definite Trial
Rule 122
Basis Reached
Recall
Motion
Submitted/CAV
Continued

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by jhansen-flexion** [comment]
@swongCO  the team requests a wireframe for this story.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge is on Session Copy Page; Clicks on the Trial Status dropdown; Values are updated.

- Log in as a Judge
- Click on the link for an upcoming trial session from your dashboard page
- Session Copy page opens
- Click on the Trial Status dropdown for some of the cases

Expected Results:
- [x] Set for Trial is no longer an option
- [x] Dismissed is no longer an option
- [x] Settled is no longer an option
- [x] A Basis Reached has been updated to Basis Reached
- [x] Taken Under Advisement has been updated to Submitted/CAV
- [x] Status Unassigned has been updated to Unassigned
- [x] New value for Probable Settlement
- [x] New value for Probable Trial
- [x] New value for Motion to Dismiss 
- [x] Rule 122, Recall, Continued remain as selections
- [ ] The ordering of values should match what is listed in the mockup above. 
- [x] No additional values should be available in the dropdown

*Repeat this test with a CA and Trial Clerk.


#### 2) Judge is on the Session Copy Page; Filter checkboxes are updated.

- Continuing from the previous test
- Review the Checkbox options for filtering

Expected Results:
- [x] Set for Trial is no longer an option
- [x] Dismissed is no longer an option
- [x] Settled is no longer an option
- [x] A Basis Reached has been updated to Basis Reached
- [x] Taken Under Advisement has been updated to Submitted/CAV
- [x] Status Unassigned has been updated to Unassigned
- [x] New value for Probable Settlement
- [x] New value for Probable Trial
- [x] New value for Motion to Dismiss 
- [x] Rule 122, Recall, Continued remain as selections
- [ ] The ordering of values should match what is displayed in the mockup above. 
- [x] No additional values should be available to check a box

*Repeat this test with a CA and Trial Clerk 



#### 3) Judge Prints the Session Copy Page; Updated Filter values appear on Printable Session Copy page

- Continuing from the previous test
- Ensure that the "Show All" is selected
- Click on the print link to print the session copy page
- Review the printable Session Copy page
- On the Trial Status Filters Selected section:

Expected Results:
- [x] Set for Trial is no longer displayed
- [x] Dismissed is no longer displayed
- [x] Settled is no longer displayed
- [x] A Basis Reached has been updated to Basis Reached
- [x] Taken Under Advisement has been updated to Submitted/CAV
- [x] Status Unassigned has been updated to Unassigned
- [x] New value for Probable Settlement
- [x] New value for Probable Trial
- [x] New value for Motion to Dismiss 
- [x] Rule 122, Recall, Continued remain
- [x] The ordering of values should match what is displayed in the mockup above. 
- [x] No additional values should be displayed


#### 4) Judge is on the Session Copy page that already had cases with some of the legacy Trial Status' set; Trial status values that were changed are updated to the new wording.

**Preconditions: You will need to ensure that you are accessing a Session copy page that had already had Trial Status values added before deployment of this code.**

- Log in as a Judge
- Click on the link for an upcoming trial session from your dashboard page
- Session Copy page opens

Expected Results:
- [x] Trial Status values that were previously "A Basis Reached" have been updated to "Basis Reached"
- [x] Trial Status values that were previously "Taken Under Advisement" have been updated to "Submitted/CAV"
- [x] Trial Status values that were previously "Status Unassigned" have been updated to "Unassigned"

*Repeat this test with a CA and Trial Clerk 



#### 5) Judge prints the session copy page; Trial status values that have been updated are reflected appropriately on the the printable session copy page.

- Continuing from the previous test
- Click the Print link to print the session copy page
- Review the Printable Session copy page

Expected Results:
- [x] Trial Status values that were previously "A Basis Reached" have been updated to "Basis Reached"
- [x] Trial Status values that were previously "Taken Under Advisement" have been updated to "Submitted/CAV"
- [x] Trial Status values that were previously "Status Unassigned" have been updated to "Unassigned"

*Repeat this test with a CA and Trial Clerk



#### 6) Judge is on the Session Copy page that already had cases with some of the legacy Trial Status' set; Trial status values that have been removed from the filter and dropdown still remain as the trial status, but cannot be re-selected from the dropdown.

**Preconditions: You will need to ensure that you are accessing a Session copy page that had already had Trial Status values added before deployment of this code.**

- Log in as a Judge
- Click on the link for an upcoming trial session from your dashboard page
- Session Copy page opens
- Find a case that has a Trial Status already set to one of the values that has been removed (Set for Trial, Dismissed, Settled)
- Click on the dropdown menu for Trial status (do not select any other value though!)

Expected Results:
- [x] The dropdown picklist does not have this existing legacy value available for selecting
- [x] As long as you don't pick a different value, the legacy value remains as the trial status

*Repeat this test with a CA and Trial Clerk 



#### 7) Judge prints the session copy page that already had cases with some of the legacy Trial Status' set; Trial Status values that have been removed from the filter and dropdown still remain as the trial status, and appear on the printable session copy page.

- Continuing from the previous test
- Click the Print link to print the session copy page
- Review the Printable Session copy page

Expected Results:
- [x] The old legacy values that have been removed from the picklist (Set for Trial, Dismissed, Settled), but that were assigned to cases prior to the code being deployed still remain on the printable session copy page.

*Repeat this test with a CA and Trial Clerk 



#### 8) Judge unchecks the "Show All" checkbox to remove all cases from the display; Judge rechecks the "Show All" checkbox; Cases with the legacy trial status values that have been removed (Set for Trial, Dismissed, Settled) still appear in the list of cases.

- Continuing from the previous test
- Uncheck the "Show All" checkbox, which will remove all cases in the list from view
- Recheck the "Show All" Checkbox.
- Review the list of cases

Expected Results:
- [x] Cases that have the old legacy values that have been removed (Set for Trial, Dismissed, Settled) still appear in the list of cases

*Repeat this test with a CA and Trial Clerk 



#### 9) Judge updates a trial status value that has been removed (Set for Trial, Dismissed, Settled) to new value from the trial status picklist; Old value is no longer available to select from the dropdown and no longer appears on the Session copy page for that case.

**Preconditions: You will need to ensure that you are accessing a Session copy page that had already had Trial Status values added before deployment of this code.**

- Log in as a Judge
- Click on the link for an upcoming trial session from your dashboard page
- Session Copy page opens
- Find a case that has a Trial Status already set to one of the values that has been removed (Set for Trial, Dismissed, Settled)
- Click on the dropdown menu for Trial status
- Select a value from the picklist

Expected Results:
- [x] Old legacy value no longer appears as the Trial Status
- [x] Old legacy value that used to be there can not be selected from the picklist 

*Repeat this test with a CA and Trial Clerk 



#### 10) Judge prints the session copy page after updating one of the old values to a new value; Trial Status value that was updated appears on the printable Session copy page, an so do the older legacy trial status values that have not yet been updated.

- Continuing from the previous test
- Click the Print link to print the session copy page
- Review the Printable Session copy page

Expected Results:
- [x] The updated value that you assigned to the case in the previous test displays as the trial status 
- [x] The old legacy values that have been removed from the picklist (Set for Trial, Dismissed, Settled), but that were assigned to cases prior to the code being deployed still remain on the printable session copy page.

*Repeat this test with a CA and Trial Clerk 


#### 11) Judge updates the trial status for various cases on the session copy page; Selects a variety of values, including the new values that have been added to the picklist; Values display appropriately in the Case List

**Preconditions: You will need to ensure that you are accessing a Session copy page that had already had Trial Status values added before deployment of this code.**

- Log in as a Judge
- Click on the link for an upcoming trial session from your dashboard page
- Session Copy page opens
- Update the trial status for various cases in the list, be sure to select new values, changed values, update old legacy values to new ones, and also be sure to select some values that have no change.

Expected Results:
- [x] All values selected are updated in the trial status for each case
- [x] When checking/unchecking the trial status boxes, the case list below the checkboxes is updated and displays appropriately

*Repeat this test with a CA and Trial Clerk 



#### 12) Judge prints the session copy page; all trial status values selected from the previous test print appropriately.

- Continuing from the previous test
- You should have multiple trial status values that have been updated for cases in the session
- Click on the print link to print the session copy page

Expected Results:
- [x] All of the trial status values that you have assigned to the cases are reflected appropriately on the Printable Session Copy page.

*Repeat this test with a CA and Trial Clerk 



#### 13) Regression test with the Feature Flag off.

**Comment by cholly75** [comment]
@TomElliottFlexion - desired order of filter boxes, top row:
Basis Reached - Probable Settlement - Probable Trial - Definite Trial - Motion to Dismiss
Bottom row:
Recall - Continued - Rule 122 - Submitted/CAV - Unassigned

No preference as to order in dropdown menu to select individual case status.

No reminder banner is needed.

**Comment by ttlenard** [comment]
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/8193e483-de88-46dd-ba01-94a49fab791f)

**Comment by cholly75** [comment]
@TomElliottFlexion @ttlenard - as per court conference feedback, AC has been added - on existing trial session copies, cases where the value "Settled" has been assigned should have that value changed to "Basis Reached".

**Comment by cholly75** [comment]
@TomElliottFlexion - printable version of trial session w/ changed values in TEST (Buch/Miami 12/19) results in 400 error. Session copies w/o new or changed values (literally any other one) continues to work as expected. 

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/cfa87863-9a06-4c97-8847-658cb366b8fe)

**Comment by cholly75** [comment]
@TomElliottFlexion - re: Test Case ustaxcourt/ef-cms#6495 - selecting the menu for a case w/ a deprecated value still has the deprecated value in the list:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/aea3d202-0211-4f7b-a69d-fc5a87d2e8a3)

**Comment by cholly75** [comment]
@TomElliottFlexion @ttlenard - FYI, the AC has been updated to replace "Motion to Dismiss" with "Motion". As "Motion to Dismiss" was a new value introduced with this story, we will simply test for "Motion" in its place.
