### ISSUE TITLE
Court User: Case Type Filter on Blocked Cases Report

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6955]
As a Court User, in order to make sure that I am only reviewing relevant cases on the Blocked Cases report, I need the ability to filter the report for small cases only, regular cases only, or all cases.

Prior to each trial session, a Court User (usually a Calendar Clerk) is going to look at the "blocked cases" report for the trial city to make sure that none of those cases should be un-blocked and scheduled for trial.  In order to streamline the review, the user only needs to see the cases relevant to the upcoming trial session.  For example, if the Court has a Small session in Baltimore, MD, the user only needs to review small cases with the trial location of Baltimore that are blocked.  The user does not need to review regular cases.  As a result, the user needs the ability to filter the blocked report per trial location for small cases only, regular cases only, or all cases.  The user will know which filter to use.

## Acceptance Criteria ##
* After selecting a Trial Location criteria on the Blocked Cases report, the user can select an additional filter for Case Type.
* Selectable values on the Case Type filter:
  - Small
  - Regular
  - All
* Default selection on the Case Type filter is "All"
* Selecting a filter from the Case Type filter updates the displayed report to include **only** those cases of the selected Trial Location and Case Type
* Selecting a different Trial Location _after_ selecting a Case Type will reset the Case Type filter value to "All"

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) New Filter is available for the Court User on the Blocked Cases Report
-  Log in as any court user
- Click on Reports
- Select Blocked Cases Report

Expected Results
- [ ] **NEW FUNCTIONALITY** - There is now a new filter for Case Type below the Trial Location Filter.
- [ ] **NEW FUNCTIONALITY** - Options in the Case Type dropdown are Small, Regular, All
- [ ] **NEW FUNCTIONALIT** - All is the default selection


#### 2) Court user selects a trial location from the blocked cases report, adds filter for Small, results only show small cases in results for selected trial location.
- Select a Trial location
- For the Case Type Filter, select Small

Expected Results
- [ ] **NEW FUNCTIONALITY** - The blocked case list only shows cases for the selected trial session that have a case type of Small.
- [ ] Be sure that you spot check the cases by clicking on the docket number link to verify that the case is a Small case type.


#### 3) Court user selects a trial location from the blocked cases report, adds a filter for Regular, results only show regular cases in results for selected trial location.
- Select a Trial Location
- For the Case Type filter, select Regular

Expected Results
- [ ] **NEW FUNCTIONALITY** - The blocked case list only shows cases for the selected trial session that have a case type of Regular.
- [ ] Be sure that you spot check the cases by clicking on the docket number link to verify that the cases are regular cases.


#### 4) Court user selects a trial location from the blocked cases report, leaves the default selected for All, results show all cases (regular and small) in the results for the selected trial location.
- Select a Trial Location
- For the Case Type filter, keep the default selection of All

Expected Results
- [ ] **NEW FUNCTIONALITY** - The blocked case list only shows cases for both Regular and Small case types
- [ ] Be sure that you spot check the cases by clicking on the docket number link to verify that the cases are both regular and small


#### 5) Court user selects a trial location from the blocked cases report, adds a filter for Small, results appear; Court user then selects a new trial location from the dropdown; The case type filter reverts back to All upon selection of the new trial location.
- Select a Trial Location
- For the Case Type filter, Select Small
- The case list will show small case types for that selected trial location
- Next, select a new trial location

Expected Results
- [ ] **NEW FUNCTIONALITY** - The Case type filter will default back to All
- [ ] The blocked case list only shows cases for both Regular and Small case types
- [ ] Be sure that you spot check the cases by clicking on the docket number link to verify that the cases are both regular and small

**Comment by cholly75** [comment]
Looked at issue w/ table shift when filter is applied and the result set goes from having some CG icons to none or vice versa - not a blocker, can talk to this.
