### ISSUE TITLE
Docket: Action/Status column

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6956]
As a Docket Clerk, in order to indicate that a filing has been acted on, I need the ability to enter a disposition in the Action/Status column of the Docket Record.

When a party files a motion, it will not be granted or denied immediately.  More than likely, the Court will issue an Order granting or denying it several weeks/months later.  In order to cross-reference the Order (which will likely be many entries later on the Docket Record) as the document that disposed of the motion, that Order will be referenced in the "Action/Status column" on the motion's Docket Entry line.  This gives the person viewing the Docket Record a quick-glance at the action, if any, that was taken on the motion.

## Acceptance Criteria: ##
* Docket Clerk must have the ability to enter information in the "Action/Status column"
* Once a "pending" items is acted on, it is removed from "Pending" status.

**Comment by klohman** [comment]
Notes from UX Docket Deep Dives 

Recording Actions (aka Action/Status column)

Need the list of action/ status codes - and what they mean (JESSICA??? Rhonda said she will provide list)
Need the ability to record these actions:
Granted
Denied
Stricken - draws line through entry
Vacated - most of the when it’s vacated, the status changes - happens all the time
Withdrawn - they add the ORD and date in action column, and add Withdrawn on the filing and proceedings
Need a way to record actions but also keep the item as pending until all actions related to a document are resolved
Some actions will update case status - need a way to do this automatically

**Comment by cholly75** [comment]
Functionality already present.
