### ISSUE TITLE
Automatically remove case from Trial Session list

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6958]
New story from ustaxcourt/ef-cms#6805

Case is automatically removed from a trial session when it is closed.
Once a case is removed from a trial session, it shows up under "closed cases" for that trial session
The reason the case was removed displays under disposition with the date.
Court user needs the ability to see all cases that were originally on trial calendar, see all active cases and see all cases that were removed

**Comment by cholly75** [comment]
This is complete.
