### ISSUE TITLE
Order Generation: Side-By-Side view

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6961]
As a Court User, in order to easily and accurately draft Orders in the system, I need the ability to draft an Order while looking at another document/filing on the docket record.

A Court User is typically drafting an Order in response to a party's filing.  As a result, it is most helpful for the user to be able to look at that filing *while* drafting the Order.

## Notes: ##
* Consider some side-by-side viewing option

**Comment by cholly75** [comment]
Duplicate of ustaxcourt/ef-cms#7082
