### ISSUE TITLE
Make pracitioner search elastic

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6965]
Use elastic search for practitioner search

**Comment by cholly75** [comment]
@mariahkannenberg - is this another candidate for DevEx/OpEx? Not sure what the user benefit is here (or how we're doing the practitioner search now) .

**Comment by ttlenard** [comment]
@cholly75 Some additional information that will be helpful for this story.

- When searching for a specific attorney in the Advanced Practitioner Search, partial matches return results.
     -  example: 
     - Search for Peter Karl
     - Results return for Peter Adam Karl III (KP0135)
- When searching for a specific attorney to add them as counsel on the Parties tab within a case, partial matches do NOT return any results
     - example:
     - Go to any case
     - click on case information tab
     - click on parties tab
     - In the add counsel area, enter "Peter Karl"
     - no results will appear
     - The only way to get this attorney to appear is if you type out his entire name "Peter Adam Karl III"
     - This text box will ONLY search for exact matches
     - This came up because when docket was reviewing the EA, the attorney didn't input his name exactly as it is in his DAWSON account, so it was difficult to find this attorney to add his as counsel on the record. 
- We need the search box for adding counsel within a case to be able to search on partial matches just like it does within the Practitioner Database.

**Comment by cholly75** [comment]
Closing NFA
