### ISSUE TITLE
Calendaring - Signifying Consolidated Cases on the Eligible Cases list

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6971]
As a court user calendaring trial sessions, so that all cases in a consolidated group (CG) are scheduled for the same trial session, I need the system to group consolidated cases together when they appear on the eligible cases list.

Currently the Eligible Cases list presented on the New view of the Trial Sessions page displays all cases eligible for trial given the criteria of the trial session itself. Currently there are no signifiers when either the Lead Case or a member case of a consolidated group appears in the Eligible Cases list. This means that the calendaring user must manually check to ensure that all cases in the consolidated group are scheduled for the same trial session.

We would like to add signifiers and grouping to the Eligible Cases list on the screen to make this process less burdensome to the user and ensure completeness in the calendaring process. The approach should follow the same approach used in other stories w/r/t iconography and grouping. 

N.B.: We are NOT changing any of the criteria that determines which cases actually show on the Eligible Cases list.

## Acceptance Criteria
* On the Eligible Cases list on the Session Information page, cases belonging to a consolidated group are indicated by an icon indicating whether or not the case is the Lead case or a Member case.
* On the Eligible Cases list on the Session Information page, cases belonging to the same consolidated group are grouped together in the case listing, with the Lead case listed first followed by the member cases slightly indented underneath in ascending docket number order (i.e., oldest -> newest)
  - Example: Cases 123-20, 234-20, and 345-21 are in a consolidated group together, with 123-20 being the Lead case. The 
     case listing for these cases when calendared would be ordered as such:
     123-15
     123-16
     123-20
       -234-20
       -345-21
     150-20
     123-22
* Eligible Cases list should retain default sorting order (Lien/Levy cases at the top, followed by all other cases in ascending docket number order)
* Consolidated Group overall placement on the list is determined by the Lead Case in the group
* If member cases of the group are on the Eligible Case list but the Lead Case is NOT eligible, do not group or indent the member cases in the list.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

**Questions from UX**
1. Is this dependent on other steps before or after? No - Sincerely, UX

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by swongCO** [comment]
Refer to https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9535 for implementation

**Comment by ttlenard** [comment]
## Test Cases


#### 1) On the Eligible Case list, a Consolidated Group of cases has iconography indicating if a case is the lead or a member case; Consolidated group is sorted appropriately. 

Preconditions: You will need to ensure that there is a consolidated group of cases that are in the General Docket - At Issue, Ready for Trial status, and take note of the requested place of trial for this group. 

This test has some set up
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click Add Trial Session
- Fill out the information for the trial session, and be sure that you select the location of the trial as the city/state of the requested place of trial for the Consolidated group of cases that you took note of in the preconditions above.
- Click Add Session
- Click on the New tab, and open the trial session that you just created by clicking on the City/State link.

Now the test is ready: 
- Scroll down to the Eligible case list on the Session information page

Expected Results:
- [x] The lead case in the consolidated group has the Lead case indicator icon
- [x] The member cases in the condolidated group have the member case indicator icon
- [x] The member cases are indented slightly
- [x] The Cases in the consolidated group are grouped in ascending order (oldest to newest)
- [x] The default sorting order of the Eligible case list is not changed (Lien/Levy cases at still at the top!)
- [ ] The overall placement of the consolidated group on the Eligible case list is determined by the Lead Case in the Group.



#### 2) Manual Block is added to a member case in the consolidated group; Member case no longer appears on the Eligible Case list

- Continuing from test case 1
- Click on the docket number of a member case from the group
- Click on the Case infomration tab
- Click on Add Manual Block
- Add a reason and click Block Case
- Click on the Trial Session tab
- Click on the New tab, and open the trial session that you created in the previous test.
- Scroll down ot the Eligible case list on the Session information page.

Expected results:
- [x] The member case that you just blocked is no longer appearing in the Eligibile case list, and is not indented as part of the Consolidated group.



#### 3) Manual block is added to the lead case in a consolidated group; Lead case no longer appears on the Eligible Case list; member cases are no longer indented.

- Continuing from test case 2
- Click on the docket number of the Lead case from the group
- Click on the Case infomration tab
- Click on Add Manual Block
- Add a reason and click Block Case
- Click on the Trial Session tab
- Click on the New tab, and open the trial session that you created in the previous test.
- Scroll down ot the Eligible case list on the Session information page.

Expected results:
- [x] The Lead case that you just blocked is no longer appearing in the Eligibile case list
- [x] The member cases that are part of the Consolidated Group are no longer indented 
- [x] The member cases that are part of the Consolidated Group have reverted back to the default sorting order
- [x] The member cases in the condolidated group have the member case indicator icon



#### 4) Docket Clerk adds a new case from the eligible case list to the consolidated group as a member case; the new member case displays consolidated status appropriately on the Eligible Case List

- If you are testing with the same consolidated group, be sure to remove the manual blocks that you may have added in the previous test cases before performing this test.
- Before doing this test, be sure to take note of a case from the eligible case list that has a newer docket number than the lead case in the Consolidated group.
- Log in as a docket clerk
- Navigate to the case that you took note of
- Click on the Case information tab
- Click on the Add Cases Link, and add the case to the consolidated group

- Click on Trial Sessions
- Click on the New tab, and open the trial session that you have been working with
- Scroll down to the Eligible Case List

Expected Results:
- [x] The newly added case displays with the consolidated group, in acending order
- [x] The indicator icon should be a member case icon
- [x] The member case is indented slightly




#### 5) Docket Clerk adds a new case from the eligible case list to the consolidated group as the new lead case; the new lead case displays consolidated status appropriately on the Eligible Case List

- Before doing this test, be sure to take note of a case from the eligible case list that has an older docket number than the current lead case in the Consolidated group.
- Log in as a docket clerk
- Navigate to the case that you took note of
- Click on the Case information tab
- Click on the Add Cases Link, and add the case to the consolidated group

- Click on Trial Sessions
- Click on the New tab, and open the trial session that you have been working with
- Scroll down to the Eligible Case List

Expected Results:
- [x] The newly added case displays with the consolidated group, in acending order
- [x] The indicator icon should be the Lead case icon
- [x] The previous Lead case is now a member case, has the member case icon, and is indented slightly



#### 6) Docket Clerk removes a member case from the consolidated group; the removed member case no longer has the consolidated iconography and is no longer grouped with the consolidated cases on the Eligible Case List

- Log in as a docket clerk
- Navigate to a case in the consolidated group that you have been using for the prevoius test cases
- Click on Case Information
- In the consolidated Cases area, click on the link for Remove cases
- Select a member case to remove, and then click "Unconsolidate Cases" button.
- Click on the Trial Sessions Link
- Click on the New Tab
- Scroll down to the Eligible Case List

Expected Results:
- [x] The newly removed case no longer displays with the consolidated group
- [x] The case no longer has the member case indicator icon
- [x] The case still appears in the Eligible case list, but it is not with the consolidated group.


#### 7) Docket Clerk removes the lead case from the consolidated group; The removed lead case no longer has the consolidated iconography; is no longer grouped with the consolidated cases, and a new Lead case icon is displayed on the appropriate case.

- Log in as a docket clerk
- Navigate to a case in the consolidated group that you have been using for the prevoius test cases
- Click on Case Information
- In the consolidated Cases area, click on the link for Remove cases
- Select the lead case to remove, and then click "Unconsolidate Cases" button.
- Take note of the new Lead case docket number
- Click on the Trial Sessions Link
- Click on the New Tab
- Scroll down to the Eligible Case List

Expected Results:
- [x] The newly removed case no longer displays with the consolidated group
- [x] The case that you removed no longer has the Lead case indicator icon
- [x] The case that you removed is still appears in the Eligible case list, but it is not with the consolidated group.
- [x] The case that you took note of in the previous step is now showing the Lead Case indicator icon.

**Comment by liadmccabe** [comment]
@codyseibert 

UX Feedback: 
- We are unclear on what test case 1 means by "Consolidated group is sorted appropriately". E.g. docket number 33089-21L is part of a consolidated group, but is currently being pulled out of the group to the top of the table in its default sorting. You would need to scroll down to the other case types in order to find the other two cases in the group, which are grouped together and indented under the lead case.

- With default sorting, Lien Levy's are at the top, but how are they sorted? There does not seem to be a clear pattern (e.g. the docket numbers are not in an ascending/descending order, and do not appear to be alphabetical either)

- When we filter by Regular case type, we notice that two member cases (30534-15 and 30535-15) are still indented even though the lead case is not being displayed in the filtered view.  This is inconsistent with the default view which currently does not indent consolidated cases that are not listed underneath a lead case when they are separated due to filtering.

![Screen Shot 2022-09-27 at 10.58.20 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e3116d62-4e62-4b50-b25a-65c494d7bb2b)
![Screen Shot 2022-09-27 at 10.58.07 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/b2f483c9-d59b-4173-ab0b-da1edc23db0e)

**Comment by swongCO** [comment]
Story passes UX review but we have a question for Chris re high priority cases which are not signified as such in the table (as in QC page where they have the [circle !] icon).

**Comment by cholly75** [comment]
@codyseibert - feedback is that the Court would like to apply the consolidation grouping/indent when the lead case and any/all of its member cases fall into the same grouping on this screen (CDP, Passport, HP, etc).
