### ISSUE TITLE
Service on Parties

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6987]
As a the Court, in order to ensure parties in a case are served, we need the ability to serve only to parties who need service, as well as have flexibility for managing service on a party level.

Acceptance Criteria:
* Party who submits a document should not be served the same document
* Docket Clerk can select one party or multiples to serve
* IRS doesn't receive a service email when anything fails with documents being added
* Court Users are informed when service doesn't initiate properly
* Court Users are prevented from initiating service if a party has been served previously
* Parties don't receive service for the same document twice

**Comment by cholly75** [comment]
Done.
