### ISSUE TITLE
Automatic Service: Party who submits a document should not be served the same document

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6994]
As a party, to avoid getting excessive service emails from the Court, I don't need to be served a document I filed.

## Acceptance Criteria: ##
* When a party eFiles a document, only the **other** party/parties should be auto-served, if they receive electronic service:
   * If R eFiles a document, P should be eServed
   * If P eFiles a document, R should be eServed
   * If the document is filed by both P and R, nobody should be eServed
* If the non-filing party receives electronic service and is auto-served, the service information should reflect the party and date of service:
   * P = petitioner
   * R = respondent
* If there is no electronic service of a document, no service information should be reflected under  "served parties" and "served date"
* Ensure that these changes don't change the logic for court-issued documents
* For any party-filed document, if service information is entered in the Served Party/Served Date columns of the docket record (based on new logic), a stamp of the served date should also be placed on the bottom of the cover sheet of the document
* If there is no service information in the Served Party/Served Date columns, NO stamp with a service date should be placed on the bottom of the cover sheet of the document

## Notes
- When attorneys are entering into a case through an Entry of Appearance, etc., which parties should be served? I ask because the service preference petitioner who the attorney is representing will automatically change to None once they are added to the case - do we serve them before or after this happens? It may be an order of operations question. **We do not need to serve the petitioner whose attorney is making an entry of appearance**
* [Note: Judge Gale also raised the issue of whether the served stamp should be applied to the cover sheet when nobody is auto-served. In 1542-17L, IRS counsel filed an Entry of Appearance and petitioner gets paper service. The served stamp on the front of the document was confusing because that document was NOT properly served by the IRS in paper and the system didn't auto-serve it.] Need to figure out what desired behavior is of served stamp on the party-filed documents

- last AC - is it accurate that we are only displaying things as served on the docket record for electronic service? what if they include a Certificate of Service  for any paper served parties? **CS information should be at the end of the docket entry in parens. There's be nothing in the served column, but there would be "c/s + date" as part of docket entry**

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
@cholly75 

I think it's worth considering breaking this AC out into it's own story: 
* If there is no electronic service of a document, no service information should be reflected under "served parties" and "served date"
* Ensure that these changes don't change the logic for court-issued documents
* For any party-filed document, if service information is entered in the Served Party/Served Date columns of the docket record (based on new logic), a stamp of the served date should also be placed on the bottom of the cover sheet of the document
* If there is no service information in the Served Party/Served Date columns, NO stamp with a service date should be placed on the bottom of the cover sheet of the document

^^ This AC (i'm assuming) is also relevant for paper-filed documents but is not listed in ustaxcourt/ef-cms#7500. We could make a new story to handle this AC and make it applicable to both e-filed and paper-filed documents with no service info.

**Comment by klohman** [comment]
## Test Cases 3843 

#### 1) Petitioner e-files document in open case and only the other parties receive electronic service 
* Login as petitioner 
* Go to case 
    * Case has parties with electronic service
        * Respondent Counsel - electronic service 
* E-File a document 
    * Select filing party - Petitioner 
Expected results 
- [ ] Respondent counsel receives service email 
- [ ] Petitioner does not receive service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = R 

#### 2) Intervenor e-files document in open case and only the other parties receive electronic service
* Login as intervenor 
* Go to case 
    * Case has parties with electronic service
        * Petitioner - electronic service 
        * Respondent Counsel - electronic service 
* E-File a document 
    * Select filing party - Intervenor 
Expected results 
- [ ] Respondent counsel receives service email 
- [ ] Petitioner receives service email 
- [ ] Intervenor does not receive service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = B 

#### 3) Participant e-files document in open case and only the other parties receive electronic service
* Login as participant 
* Go to case 
    * Case has parties with electronic service
        * Petitioner - electronic service 
        * Respondent Counsel - electronic service 
* E-File a document 
    * Select filing party - Participant & Respondent  
Expected results 
- [ ] Respondent counsel does not receive service email 
- [ ] Petitioner receives service email 
- [ ] Participant does not receive service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = P 

#### 4) Party counsel e-files document in open case and only the other parties receive electronic service
* Login as private practitioner 
* Go to case 
    * Case has parties with electronic service
        * Represented Petitioner - no service 
        * Unrepresented petitioner - electronic service 
        * Respondent Counsel - electronic service 
* E-File a document 
    * Select filing party - Represented petitioner   
Expected results 
- [ ] Respondent counsel receives service email 
- [ ] Represented petitioner does not receives service email 
- [ ] Unrepresented petitioner receives service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = B

#### 5) Respondent e-files document in open case and only the other parties receive electronic service
* Login as respondent counsel
* Go to case 
    * Case has parties with electronic service
        * Represented Petitioner - no service 
        * Petitioner counsel - electronic service 
        * Unrepresented petitioner - electronic service 
        * Respondent Counsel 2- electronic service 
* E-File a document 
    * Select filing party - respondent 
Expected results 
- [ ] Respondent counsel 2 does not receive service email 
- [ ] Represented petitioner does not receives service email 
- [ ] Unrepresented petitioner receives service email 
- [ ] Petitioner counsel receives service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = P

#### 6) All parties and respondent e-files document in open case and no one receives electronic service 
* Login as respondent counsel
* Go to case 
    * Case has parties with electronic service
        * Petitioner - electronic service 
* E-File a document 
    * Select filing party - respondent & petitioner
Expected results 
- [ ] Respondent counsel  does not receive service email 
- [ ] Petitioner does not receives service email 
- [ ] Docket entry displays served column [blank]
- [ ] Docket entry displays Parties column = [blank]

#### 7) Party e-files document in case with all paper service parties and no service information is displayed on docket record 
* Login as respondent counsel
* Go to case 
    * Case has parties with electronic service
        * Petitioner - paper service 
* E-File a document 
    * Select filing party - respondent 
Expected results 
- [ ] Respondent counsel  does not receive service email 
- [ ] Petitioner does not receives service email 
- [ ] Docket entry displays served column [blank]
- [ ] Docket entry displays Parties column = [blank]

#### 8) Party counsel e-files an entry of appearance on a case and only the other parties receive electronic service  
* Login as petitioner counsel 
* Go to case not associated with logged in counsel 
    * Case has parties 
        * Petitioner 1 - Electronic service
        * Petitioner 2 - Electronic service 
        * Respondent counsel - electronic service 
* File an entry of appearance 
    * Representing Petitioner 1 
Expected results 
- [ ] Respondent counsel receives service email 
- [ ] Petitioner 1 does not receives service email 
- [ ] Petitioner 2 receives service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = [B]

#### 9) Respondent counsel e-files first IRS document in case and only the other parties receive electronic service
* Login as respondent counsel 
* Go to case not associated with logged in counsel 
    * Case has parties 
        * Petitioner 1 - Electronic service
        * Petitioner 2 - Electronic service 
        * Respondent counsel - electronic service 
* File an entry of appearance 
    * Representing Petitioner 1 
Expected results 
- [ ] Respondent counsel receives service email 
- [ ] Petitioner 1 does not receives service email 
- [ ] Petitioner 2 receives service email 
- [ ] Docket entry displays served column [current date]
- [ ] Docket entry displays Parties column = [B]
