### ISSUE TITLE
Petitioner: E-filing a document in a consolidated case group

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7000]
As a petitioner in a case, to streamline the filing process in a consolidated case group, I need to be able to file a single document across the consolidated case group as a single operation.

With the recent enhancements to DAWSON to better handle consolidated groups of cases, we would like to now make available to petitioners the ability to e-file a document across multiple cases in their consolidated group.

## Pre-Conditions
ustaxcourt/ef-cms-flexion#9599

## Acceptance Criteria
* When e-filing an eligible document (see Notes section below re: eligible document types) in a case to which they are a party, if that case is a part of a consolidated group (Lead or Member) a petitioner is presented with the option to file in all cases across the consolidated group to which that case belongs
* The default option for the selection UI is to file in all cases in the consolidated group
* When filing in multiple cases:
  - Document entries on case docket records are created for each case selected by Petitioner
  - Cover sheets are applied to the document on each docket entry in the following manner for consolidated cases:
    - If the filing is across ALL cases in the group:
      - Petitioner name(s) of the *Lead case in the group* appended with "et al"
      - Docket number and document number of each case selected are listed in ascending order by docket number
  - Service is performed on all parties in all cases being filed in
  - QC work items are spawned for **each** docket entry created by the filing
  - The FiledBy value on the docket record for **each** entry indicates the party filing the document, even if they are not a party to a case in which the document is being docketed
  - Any attachments or supporting documentation for the document being filed are also filed with that document in all cases where docketed
  - Messaging throughout Petitioner flow is updated to reflect multiple cases are being filed in
  - At the final step in filing document, on the Review Page the Petitioner is presented with a reminder of all cases the document will be filed in
  - At the final step in filing document, Petitioner can cancel out of the workflow
  - The document created by clicking the Print Receipt link displayed after completing filing reflects all docket numbers in which the document was filed and appends "et al.," to the Petitioner names in the caption.
* The following document types should not be multi-docketed with this functionality (i.e., do not invoke this if the document being filed is one of the following event codes:
ACED
COED
M007
M083
PSDE

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Should tie to the same feature flag used by ustaxcourt/ef-cms-flexion#9594
* Need to test w/ IRS service agent
* Eligible document types include all documents currently available to be e-filed by petitioners
* should work on mobile for petitioners

**Questions from UX**

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
## THESE ARE OLD - DISREGARD - SEE UPDATED TEST CASES IN SEPARATE COMMENT


## Test scenarios
#### Scenario 1 - When a party attempts to file a document in a case that is in a set of consolidated cases, they are prompted to choose one or multiple cases to file the document in
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button the "file a doc" page loads and a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with after the the "file a doc" page loads. 


#### Scenario 2 - File a document page displays message of what cases user is filing in
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button the "file a doc" page loads and a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with after the the "file a doc" page loads. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.

#### Scenario 3 - Error occurs if “Proposed stipulated decision” is chosen to file in multiple consolidated cases
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button the "file a doc" page loads and a modal appears
5. Click on one of the checkboxes next to the case you would like to file your document in
6. Click on Add to Case(s) button
7. Select Proposed Stipulated decision
8. Click continue

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with after the "file a doc" page loads. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.
- [ ] A red vertical line displays next to the document dropdown and a red error message displays under the dropdown which reads “ Proposed Stipulated Decision must be filled for each case”

#### Scenario 4 - User can select who filed the document for each case in the file a document flow
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click the file a document button
4. Verify that after you click on “ok, I’m ready to file” button the "file a doc" page loads and a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.
8. Select a document and click continue
9. Verify that in “tell us about the parties filing the document(s) each case the document will be filed displays with checkboxes next to the filing parties 
10. Verify next to the filing party check box names the dockets those parties are included in are listed
11. Verify that respondent checkbox for filing party is listed separately at the bottom of the page

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with after the "file a doc" page loads. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.
- [ ] next to the filing party check box names the dockets those parties are included in are listed
- [ ] respondent checkbox for filing party is listed separately at the bottom of the page

#### Scenario 5 -On the Review page user can see what cases their document is filed in and what parties filed in each document
1. Login as any external user
2. Click on one of the docket numbers that is part of a consolidated case
3. Click the file a document button
4. Verify that after you click on “ok, I’m ready to file” button the "file a doc" page loads and a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Verify when the what document are you filing page loads, at the top displays a message that states, “ your document will be filled in docket numbers #, #, and #.
8. Select a document and click continue
9. Select the filing party/parties for each case
10. Click submit filing button
11. Verify on the review screen displays a card “Filed in these cases” 
12. Verify that in the “file in these cases” tile is the list of docket number and docket names that the document has been filed in
13. Verify on the review screen displays a card “Parties filing the document(s)”
14. Verify that in the “Parties filing the document(s)” tile is the list of docket numbers/names with the filing parties listed underneath each

Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with after the "file a doc" page loads. 
- [ ] Message appears at the top of the “What document are you filing” page that displays a message that states, “ your document will be filled in docket numbers #, #, and #.
- [ ] In the “tell us about the parties filing the document(s) each case the document will be filed displays checkboxes next to the filing parties
- [ ] Review screen displays a card “Filed in these cases”
- [ ] In the “file in these cases” tile is the list of docket number and docket names that the document has been filed in
- [ ] Review screen displays a card “Parties filing the document(s)”
- [ ] In the “Parties filing the document(s)” tile is the list of docket numbers/names with the filing parties listed underneath each

#### Scenario 6 -The document filed in scenario 5 displays in the docket record of each case filed in
1. Login as any external user
2.  Click on one of the docket numbers from scenario 5
3. Verify that in the docket record table the document from scenario 5 displays
4. Repeat step 2 & 3 for each case the document was filed to

Expected result
- [ ] The document displays on the docket record for each case the document was filed to

#### Scenario 7 -Once a document has been filed in the consolidated cases, the docket record will display Filed by party and the docket numbers for where the document is filed.
1. Login as any external user
2.  Find a consolidated case
3. Navigate to the docket record
4. Verify on the docket record that the documents filed by column displays the filing party along with what dockets they are filed in. Example: Pet. Bruce Campbell (113-19, 114-19, 115-19)

Expected result
- [ ] The documents filed by column displays the filing party along with what dockets they are filed in. Example: Pet. Bruce Campbell (113-19, 114-19, 115-19)

#### Scenario 8 - “Proposed stipulated decision” is chosen to file in one case of a consolidated cases group
1. Login as any external user
2.  Click on one of the docket numbers that is part of a consolidated case
3. Click The file a document button
4. Verify that after you click on “ok, I’m ready to file” button the "file a doc" page loads and a modal appears
5. Click on the checkboxes next to the cases you would like to file your document in
6. Click on Add to Case(s) button
7. Select Proposed Stipulated decision
8. Click continue
9. Verify no error message displays stating stipulated decision needs to be filed to a single case
9. Fill out information in the File a Document page and click review filing
10. Review the filing information and click submit filing.
11. Verify the document appears on the docket record


Expected result
- [ ] Modal appears “would you like to file your document in multiple cases” with list of cases in which chosen case is consolidated with and allows to choose one case after the "file a doc" page loads.
- [ ] No Error displays when selecting stipulated decision for one case
- [ ] Document is submitted to the case and displays on the docket record

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner that is a party in at least one case in a consolidated group files a document in one of the cases; New section for selecting additional cases is present on the File Your Document(s) page.

- Log in as a Petitioner that is a party to at least one case in a consolidated group. 
- Click on the docket number for one of the cases in the consolidated group
- Click File a document

Expected Results:
- [x] **NEW FUNCTIONALITY** - New section near the bottom of the page that is titled, "Which Cases Do You Want to File In?" that matches what is in the mockup.
- [x] **NEW FUNCTIONALITY** - Section includes radio buttons for "All in the consolidated group" and the docket number/Petitioner name(s) for the singular case that you are filing the document in.
- [x] **NEW FUNCTIONALITY** - Under "All in the consolidated group", it lists all of the docket number and Petitioner names for the cases in the consolidated group.
- [x] **NEW FUNCTIONALITY** - User can click either radio button and can only have one radio button selected at one time. 


#### 2) Petitioner selects the singular case radio button; Standard Review your Filing page displays.

- Continuing from the previous test
- Select a document from the dropdown (doesn't matter which one)
- Upload a document
- Select the radio button for the singular case that you are currently filing in.
- Click Review filing button

Expected results:
 - [x] The Review your filing page is the "standard" review page (only lists cards for Your Document(s), and Parties Filing The Documents). 



#### 3) Petitioner submits the filing; Document is added to the singular case in the consolidated group only.

- Continuing from the previous test
- Click Submit your Filing

Expected Results:
- [x] Green confirmation banner indicates successful addition to the docket record.



#### 4) Petitioner clicks the Print Receipt link from the Green confirmation banner; Print receipt includes only the singular docket number in which the document was filed; "et al." is NOT appended to the Petitioner name in the caption.

- Continuing from the previous test
- Click on the Print Receipt link

Expected Results:
- [x] New tab opens with the Receipt of filing document
- [x] Petitioners name in the case caption is the case caption of the case you are filing in (Might NOT be the Lead case, and it is NOT appended with "et al.")
- [x] Print receipt only shows the case docket number for the case that you filed the document in, shouldn't list any other docket numbers. 



#### 5) Petitioner views the document on the docket record; coversheet only refers to the singular case.

- Continuing from the previous test
- Click on the document title on the docket record

Expected Results:
- [x] Document opens in a new tab
- [x] Document includes a coversheet
- [x] Coversheet includes the Petitioner name of the singular case only in the group, and is NOT appended with the "et al."
- [x] Coversheet includes the docket number of each singular case in the group only.



#### 6) Petitioner navigates to each case in the consolidated group; none of the other cases in the group have the just filed document on the docket record.

- Continuing from the previous test
- Navigate to the case information tab
- Open each docket number that is in the consolidated group in a new tab
- Review the docket record in each case

Expected Results:
- [x] None of the other cases in the Consolidated group have the most recently filed document
- [x] The only case that has the document on the docket record is the singular case that you filed the document in.


#### 7) Review the logs to ensure that service was sent to all parties appropriately.

- Open Kibana
- Check service on all cases

- [x] Bulk email params list each party receiving electronic service
- [x] Bulk email response has a successful service message for each party receiving electronic service
- [x] Only the singular case in the consolidated group should have the log entries above.


#### 8) Docket Clerk accesses Document QC page; work item is created for the singular case that the document was filed in; can be QC'd as normal.

- Log in as a docket clerk or Case Services Supervisor
- Click on Document QC
- Click on Section document QC
- Find the document that you just filed in the consolidated case as the Petitioner in the previous test

Expected Results
- [x] There is an individual work item for the singular document filed in the case, and it is unassigned.
- [x] Work item displays the consolidated case icon appropriately
- [x] All other information in the table is displayed/linked as it normally should be
- [x] Consolidated case work item from the previous test can be filtered in view as per normal
- [x] Consolidated case work item from the previous test can be assigned to a docket clerk as per normal.
- [x] Clerk can complete QC as normal.



#### 9) Petitioner files a document in all of the cases in a Consolidated Group; Document is filed in each case in the consolidated group appropriately.

- Log in as the Petitioner that you used for test case 1
- Click on the docket number for one of the cases in the consolidated group
- Click File a document
- Select a document from the dropdown (doesn't matter which one)
- Upload a document
- Indicate that the Petitioner is filing the documents
- Select "All in the consolidated group" (this should be the default selection!)
- Click Review filing button
- Ensure that the additional cases that you checked in Test case above are present and are displaying the correct information.
- Click on Submit Your filing

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Green confirmation banner indicates successful filing in cases across the group.
- [x] After clicking on Print receipt:
     - [x] New tab opens with the Receipt of filing document
     - [x] **NEW FUNCTIONALITY** - Petitioners name in the case caption is the case caption of the LEAD case, and it is appended with "et al."
     - [x] **NEW FUNCTIONALITY** - All of the docket numbers that the documents were filed in are listed.



#### 10) Petitioner navigates to each case in the consolidated group; each case has the document on the docket record, each document matches what was filed in the original case.

- Continuing from the previous test
- Navigate to the case information tab
- Open each docket number that is in the consolidated group in a new tab
- Review the docket record and the individual documents in each case

- [x] **NEW FUNCTIONALITY** - Each case has the document that you uploaded for the one case present on the docket record.
- [x] **NEW FUNCTIONALITY** - Each document matches what was entered/added in the original case you were in when you filed the document.
- [x] **NEW FUNCTIONALITY** - Document numbers match what is listed on the coversheet.
- [x] **NEW FUNCTIONALITY** - Review the docket record
	- [x] **NEW FUNCTIONALITY** - The docket index is in the correct order in all cases
        - [x] **NEW FUNCTIONALITY** - The filed date is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The page count is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The document title is the same in all cases
        - [x] **NEW FUNCTIONALITY** - The filed by value indicates Petitioner's name in all cases (even thought this petitioner may NOT be a party on the case)
        - [x] **NEW FUNCTIONALITY** - The served date and served parties is correct in all cases



#### 11) Review the logs to ensure that service was sent to all parties appropriately

- Open Kibana
- Check service on all cases

- [x] Bulk email params list each party receiving electronic service
- [x] Bulk email response has a successful service message for each party receiving electronic service
- [x] Each case in the consolidated group should have the log entries for service.



#### 12) Docket Clerk accesses Document QC page; work items are created for each case that the document was filed in.

- Log in as a docket clerk or Case Services Supervisor
- Click on Document QC
- Click on Section document QC
- Find the documents that you just filed in the consolidated cases as the Petitioner in the previous test

Expected Results
- [x] **NEW FUNCTIONALITY** - There are individual work items for each document filed in each case, and they will be unassigned.
- [x] Work items display the consolidated case icons appropriately
- [x] All other information in the table is displayed/linked as it normally should be
- [x] Consolidated case work items from the previous test can filtered in view as per normal
- [x] Consolidated case work items from the previous test can be assigned to a docket clerk as per normal.



#### 13) Docket Clerk clicks on the document title of one of the documents from QC, Clerk can complete QC.

- Continuing from the previous test
- Click on the document name link to open the document for QC
- Review the information 

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is the Petitioner
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption , et al., docket/document numbers, etc.)

- Do not change any of the data while QCing.
- Click Complete

Expected Results:
- [x] Green confirmation banner
- [x] When viewing the processed tab, the document shows as QC'd as appropriate
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd



#### 14) Docket Clerk clicks on the document title of one of the documents from QC, Clerk can Complete and Send Message.

- As a docket clerk, click on Document QC
- Click on Section Document QC
- Find the documents that you filed in the consolidated cases as the petitioner in the previous tests
- Click on the Document name link to open the document for QC
- Review the information

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is the Petitioner
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption , et al., docket/document numbers, etc.)

- Do not change any of the data while QCing.
- Click Complete and Send Message

Expected Results:
- [x] The message modal appears and functions as normal (document is attached, recipients load appropriately, etc.)
- [x] Message sends successfully
- [x] Green confirmation banner indicating document was QC completed and message sent
- [x] When viewing the processed tab, the document shows as QC'd as appropriate (including having the consolidated icon)
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] When viewing case messages, the message is displayed as appropriate
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd



#### 15) Docket Clerk clicks on the document title of one of the documents from QC, Clerk edits/adds some data during QC; Clerk can complete QC.

- As a docket clerk, click on Document QC
- Click on Section Document QC
- Find the documents that you filed in the consolidated cases as the Petitioner in the previous tests
- Click on the Document name link to open the document for QC
- Review the information

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is the Petitioner
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption , et al., docket/document numbers, etc.)

- Update some of the data while QCing (examples: date received, document type, filed by, inclusions).
- Add in some test data into the Additional Info 1 field, and check the box for Add to cover sheet.
- Click Complete 

Expected Results:
- [x] Green confirmation banner indicating document was QC completed 
- [x] When viewing the processed tab, the document shows as QC'd as appropriate (including having the consolidated icon)
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] The document has a new coversheet with the information that you changed reflected appropriately
- [x] The other documents that were filed on the other cases will probably also have the updated coversheet. (Devs - is this true????)
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd



#### 16) Docket Clerk clicks on the document title of one of the documents from QC, Clerk checks Add to pending report; Clerk can complete QC, Pending item is captured appropriately.

- As a docket clerk, click on Document QC
- Click on Section Document QC
- Find the documents that you filed in the consolidated cases as the Petitioner in the previous tests
- Click on the Document name link to open the document for QC
- Review the information

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is Petitioner
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption, et al., docket/document numbers, etc.)

- Be sure that you check the box for add to pending report
- Click Complete 

Expected Results:
- [x] Green confirmation banner indicating document was QC completed 
- [x] When viewing the processed tab, the document shows as QC'd as appropriate (including having the consolidated icon)
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] On the Tracked Items tab of the case, there is an new pending report item for this document
- [x] Clicking on the Document title from the Pending report opens the document view of the document as per normal.
- [x] The Pending Report item appears as it should when running a query on the Pending report (be sure to take note of the Judge assigned to the case for when you run this report)
- [x] The other documents that were filed on the other cases are still in their original format, any pending items associated with them.
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd.



#### 17) Docket Clerk edits the document that was just filed and QC'd; Edits are saved correctly.

- Continuing from the previous test
- Navigate to the docket record of the case
- Click on the Edit link for the document
- Edit something (add an action, change the document type, update the filed by, strike the document...any of these things will be great to test with!)
- Click Save

Expected Results:
- [x] Green confirmation banner indicating Docket Entry changes saved
- [x] When viewing the docket record, the update you just made is saved, and is visible
- [x] The other documents that were filed on the other cases are still in their original format, without any of the changes you just made.



#### 18) Docket Clerk seals a document that was just filed and QC'd; Document seals appropriately.

- Continuing from the previous test
- Click the seal link for the document
- Select the seal level you want and click Seal


Expected Results:
- [x] Green confirmation banner indicating Docket Entry changes saved
- [x] When viewing the docket record, the document is sealed appropriately
- [x] The other documents that were filed on the other cases are still in their original format, and are not sealed.



#### 19) Petitioner files a document in all of the cases in a Consolidated Group; Petitioner includes supporting documents

- Log in as the Petitioner that you used for test case 1
- Click on the docket number for one of the cases in the consolidated group
- Click File a document
- Select a document from the dropdown (doesn't matter which one)
- Upload a document
- Check the box for attachments and Certificate of Service
- Add Supporting Documents (for some of them, check attachments and certificate of service, some of them leave the checkboxes blank)
- Indicate that the Petitioner is filing the documents
- Select "All in the consolidated group" (this should be the default selection!)
- Click Review filing button
- Ensure that the additional cases that you checked in Test case above are present and are displaying the correct information.
- Ensure that the supporting documents are displayed with the document
- Ensure that the Document Includes column includes the attachment and certificate of service info
- Click on Submit Your filing

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Green confirmation banner indicates successful filing in cases across the group.
- [x] After clicking on Print receipt:
     - [x] New tab opens with the Receipt of filing document
     - [x] **NEW FUNCTIONALITY** - Petitioners name in the case caption is the case caption of the LEAD case, and it is appended with "et al."
     - [x] **NEW FUNCTIONALITY** - All of the docket numbers that the documents were filed in are listed.
     - [x] The supporting documents are listed in the Documents filed column
     - [x] The Document Includes column lists the attachments and the certificate of service and date



#### 20) Petitioner navigates to each case in the consolidated group; each case has the document and the supporting document(s) on the docket record, each document matches what was filed in the original case.

- Continuing from the previous test
- Navigate to the case information tab
- Open each docket number that is in the consolidated group in a new tab
- Review the docket record and the individual documents in each case

- [x] **NEW FUNCTIONALITY** - Each case has the document that you uploaded for the one case present on the docket record.
- [x] **NEW FUNCTIONALITY** - Each case also has the Supporting documents that you uploaded for the one case present on the docket record.
- [x] **NEW FUNCTIONALITY** - Each document matches what was entered/added in the original case you were in when you filed the document.
- [x] **NEW FUNCTIONALITY** - Document numbers match what is listed on the coversheet.
- [x] **NEW FUNCTIONALITY** - Review the docket record
	- [x] **NEW FUNCTIONALITY** - The docket index is in the correct order in all cases
        - [x] **NEW FUNCTIONALITY** - The filed date is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The page count is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The document title is the same in all cases
        - [x] **NEW FUNCTIONALITY** - The filed by value indicates Petitioner's name in all cases (even thought this petitioner may NOT be a party on the case)
        - [x] **NEW FUNCTIONALITY** - The served date and served parties is correct in all cases



#### 21) Petitioner files a motion document in all cases in a consolidated group; Judge is able to stamp each motion individually; granting some, and denying others.

- Log in as a Petitioner that is associated with a consolidated group
- Click on the docket number link on the my cases page
- Click File a document
- Be sure to select a Motion document to file and upload a file
- Select Petitioner for the filer
- Select all cases in the consolidated group
- Click Review filing
- Click Submit your filing
- Next, as a docket clerk, QC each entry and send a message to the Judge/ADC
- Log in as a Judge/ADC for the consolidated cases
- Navigate to the cases
- Stamp grant and Stamp deny the motions, and send a message back to docket
- As docket, Add the Stamp Order to the docket record

Expected Results:
- [x] The entire workflow works as normal for each of the individual motions that were filed across the consolidated group
- [x] Each stamp order that you just added to the docket record is available in the Order Search

 

#### 22) Petitioner starts to file a document in all cases in a consolidated group; Cancels workflow; Petitioner is returned to either My Cases or the Case Docket Record.

- Log in as a Petitioner that is associated with a consolidated case group
- Click on a consolidated case docket number from the My Cases page
- Click File a Document
- Click Cancel at all of the screens during the workflow

Expected Results:
- [x] User is either returned to the docket record of the case, or back to the My Cases Screen as per usual behavior.
- [x] No documents are filed, no service



#### 23) Petitioner starts to file a document in all cases in a consolidated group; Clicks the back button during the workflow; Petitioner is returned to the previous screen.

- Log in as a Petitioner that is associated with a consolidated case group.
- Click on a consolidated case docket number from the My Cases page
- Click File a Document
- Click the Back button on all of the screens where it is present during the workflow

Expected Results:
- [x] User is returned to the previous screen; data that was entered previously is still present.



#### 24) Petitioner files a Decision type of document to a case in a consolidated group; Petitioner does not have the option to multi-docket the decision document.

- Log in as a Petitioner that is associated with a consolidated case group
- Navigate to a case in a consolidated group
- Click on the File a document button
- Be sure to select a decision type document (see list of documents in the A/C), and upload a file
- Select Petitioner as the filer

Expected Results:
- [x] The new section for the option to file in all cases in the consolidated group is not present
- [x] After submitting the filing, the Decision type document is only filed in the one case
- [x] The coversheet does not have the "et al.,", it only lists the caption of the case that you filed in (not necessarily the lead case), it only lists the docket number and document number of the individual case that you filed in.


*Repeat this test with all of these decision type of documents:
- [x] ACED
- [x] COED
- [x] M007
- [x] M083
- [x] PSDE



#### 25) Petitioner accesses DAWSON on a Mobile device; Petitioner can go through the workflows above and multi-docket on a mobile device.

- Log in as a Petitioner that is associated with a consolidated case group on a mobile device
- Click on the docket number link for one of the consolidated cases
- Click File a document

Expected Results:
- [x] All workflows outlined above work on a mobile device
- [x] Content on mobile screens are readable and usable.


#### 26) Regression test Story 9594 - Petitioner visibility across consolidated case group

- [x] Test cases for 9594 still pass



#### 27) Regression test with the FF set to off

- [ ] Petitioner cannot file across the consolidated group
- [ ] When the FF is off, Petitioner does not have visibility across the consolidated group (see story 9594)



#### 28) Regression test 9598.

- [x] Yes



#### 29) Other things to think about while testing

- What if the filing is really large, do we need to be concerned with a timeout?

**Comment by ttlenard** [comment]
@rgoshen @TomElliottFlexion  @shumway-tm 

Some testing feedback:
- Same issue as reported in 9598 - No updated confirmation banner when filing across the group
- We will definitely have some Coversheet funkiness when docket updates metadata when QCing a filing
     - This generates a new coversheet on the document they are QCing, and this new coversheet get's added to every other case document since they share the same Document ID.
     - page numbers get wonky though
     - The page numbers on the other case docket records do not get updated to reflect the additional coversheet(s) that were added when QCing.
- Service of documents when adding supporting documents can get big!  Received errors in kibana
     - Maximum sending rate exceeded Account Throttled
     - discussed this at standup on 5/16
     - ideas 
	- Mike will reach out to AWS to see if we could upgrade our limits, he will ask to see if this can be done on staging
	- Tim - idea to put this as an async?
	- Mike reported that all logs show that the emails did eventually send, but what if they end up in the dead letter que?
	- Mike would like to increase receives to 1000 instead of 3
	- Mike would also like a new story to add an alert in case something ends up in the Dead Letter Que - Chris/Mike to write a story to the board for this.
