### ISSUE TITLE
Usability Findings - Nov. 2019 - File a Petition - Pro-Se Petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7020]
Remaining Items from Nov Pro-Se Petitioner testing/File a petitions.  Original Story - ustaxcourt/ef-cms#6949

# Recommendations 

Complete report available: https://docs.google.com/presentation/d/1TV7nq-LTmqlr3oqYCRmajvDILRDrVDV2fLl7ruxZ1xM/edit?usp=sharing

**Dashboard / Landing Page** 
* Add external link icon for all petitioner tools (Post-MVP)

**Party Type / Contact Information** 
* Add “copy” address functionality for spouse information (Post-MVP)
* Update “All Fields Required” to be more visible throughout the form (Post-MVP)
* Consider redesign / relocation of the ODS form fields for businesses to immediately follow the party type selector (Post-MVP)
* Change language on “In Care Of” fields to exclude “(Your Name)” (Post-MVP)

**Case Procedure** 
* Add logic to provide eligibility information to users based on their specific case (Post-MVP)

**Trial Location**
* Consider adding suggested trial locations based on petitioner address (Post-MVP) 

**Review Screen** 
* Add more direct edit functionality (Post-MVP)
* Define service email more clearly, and add information about what this email will be used for throughout the case (Post-MVP)
* Revise reminder text for clarification around PDF inclusions/exclusions; consider co-locating with PDF previews (Post-MVP)

**Confirmation / Case Detail** 
* Define court terminology more clearly (especially “docket”) (Post-MVP)
* Add dynamic text to success message to say “You’ve been assigned docket # XXX” (Post-MVP)
* Add “what to expect” information after petition is submitted, including what happens next in the process, how petitioner will be notified of updates, etc. ) (Post-MVP)

**Comment by cholly75** [comment]
Will handle in specific stories.
