### ISSUE TITLE
Court: Ability to select which parties receive service

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7077]
* When a Court user (Petitions/Calendar and Docket) is serving a document, they should have the ability to select which party/parties get served

Note from Cheryl Crouse from January 2020 Round-Table testing: If an externally filed document has a COS with it, the docket record should not indicate it was served to all -- the docket record only indicates Service made by the Court (confirm this part!)

**Comment by cholly75** [comment]
Closing as duplicate of ustaxcourt/ef-cms#7500
