### ISSUE TITLE
Notice of Documents in the Nature of Evidence

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7081]
As a court, in order to properly notify parties that documents in the nature of evidence have been submitted, we need to generate a notice to parties in the case. 

Workaround for MVP was to allow the user to copy and paste the notice into a blank "notice" form. ustaxcourt/ef-cms#7003

**Comment by cholly75** [comment]
Closing as duplicate of ustaxcourt/ef-cms#8087
