### ISSUE TITLE
Introduce Rate Limiting for searches in report-only mode.

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#711]
Acceptance Criteria

- As a user of DAWSON, in order to prevent the servers from overloading and not getting a request back, throttle my searches so that I can only perform ___ per minute.
- As a user of DAWSON, if I try to search ___ or more times within 60 seconds, present me with a user friendly error that informs me I can only perform ___ searches per minute.
- As a system administrator of DAWSON, so that the Elasticsearch cluster can remain healthy, only allow searches the ES cluster is healthy (load < 70%) before attempting to conduct a search
- Figure out good messaging

TODO: 

- [x] Introduce limits in count-only mode (#735). 
- [x] (Remaining TODOs moved to #828)

**Comment by adunkman** [comment]
Our current rate limits are defined by #578.

**Comment by adunkman** [comment]
Messaging around this error should tell you how long you will be rate limited for.

**Comment by adunkman** [comment]
We can use IP throttling or WAF for this.

**Comment by adunkman** [comment]
Should be rolled out with Order + Opinion searches

**Comment by mmarcotte** [comment]
Andrew is making good progress, terraform and CircleCI futzing currently ongoing. 🤞 it's into a PR soon.

**Comment by mmarcotte** [comment]
Good luck Andrew! Droping the lessons learned in #18f-collab

**Comment by adunkman** [comment]
Successfully deployed to the `dev` environment for the private API endpoints, and working on the public API endpoints which requires configuring the public API’s API Gateway Stage with Terraform, which was previously implicitly created. Working on a script for this now.

**Comment by adunkman** [comment]
If no requests will be blocked, the graph should appear blank: 

![image](https://user-images.githubusercontent.com/14930/106520171-5ba9ba80-64aa-11eb-8047-c75f276ccb29.png)

If there would be blocked requests if we moved from `count` to `block` mode, they show up like this:

![image](https://user-images.githubusercontent.com/14930/106520136-4cc30800-64aa-11eb-8103-cf1cf30cfb36.png)

**Comment by mmarcotte** [comment]
@adunkman to introduce new ticket that will act as follow up for this one to enforce the rate limiting. This ticket will be to count the current behavior.
