### ISSUE TITLE
Welcome email improvements

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#713]
Since we will continue sending welcome emails to new Practitioners, we should consider some improvements based on user feedback.

1. Use a system font in the HTML version of the email to clearly show the difference between a 1, an l and an I.
2. Provide instructions in the welcome email to copy and paste the email rather than trying to retype it.
3. Eliminate the slash from line with the email address as the username to eliminate any possible confusion: 

    ````
    login: user@example.com
    pass: p4ssw0rd!
    ````

**Comment by adunkman** [comment]
Let’s pull in Kristen as needed here for UX consultation.
