### ISSUE TITLE
Refinement of Order search results ordering + case search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7137]
As a CMS user, in order to find the exact order that I'm looking for, I need the order search results to be returned in a manner that I expect.

Note:
On 4/13/20, the team removed decided to postpone refinement of the order search results ordering and test with users to find out if the default elastic search setting will work for users. We're currently using OTTB settings, but can configure based on user need. 
*Refine case search in this story? Case Search - when searching by petitioner name, if there is an exact match AND partial matches, display exact match first (top) and then display partial matches by relevancy below
* Need to also consider what happens when we load more, navigate away from the page and come back. Load issue

Here's what the tax court is currently using:
https://www.ustaxcourt.gov/orders_search_help.htm

**Notes**
* Previous bugs related to search results. 
Closed 11/30 - immediate issue is fixed but may be worth revisiting : [7029]( https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7029), [7136](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7136)

**Comment by cholly75** [comment]
This is component in the Search usability story - closing older issue.
