### ISSUE TITLE
User Forgot/Reset Password - Config and Validate?

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7153]
As a user of the system, in order to gain access to the system should I forget my password, I need the ability to reset my password. 

AC:
System user can reset their password and gain access to the system

Note - this may just be a configuration setting in Cognito.

**Comment by mmarcotte** [comment]
The problem that I found is that the user's email address is never confirmed. Programmatically created users don't receive the email to confirm their email address. We might be able to set that, but I haven't seen a way to send that confirmation email.
