### ISSUE TITLE
IRS: Summary of all service items

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7158]
As the IRS, in order to make sure that we've retrieved all documents served on us in a given day, we need a summary of all service items.

## Acceptance Criteria
* The `v2.yaml` API documentation is updated to reflect this change (recently added)
* The IRS Superuser has access to an API endpoint that lists all items served on the IRS (indicated by servedParty of R or B) on a specific day (12:00am-11:59:59pm ET) 
* Items should be listed oldest to newest
* List should have total count of items that have been served 
* If more than ## items are served on a specific day, there should be pagination. [May not need?]
* The API endpoint should be: https://api.dawson.ustaxcourt.gov/v2/reconciliation-report/{servedDate}  where {servedDate} is in DATE FORMAT yyyy-mm-dd
* The report JSON response at that API should be:
 {
     "reportTitle":"Reconciliation Report",
     "reconciliationDate":"2018-03-03",
     "totalDocketEntries": 55,
     "docketEntries":[
      {
         "docketNumber":"135-20",
         "description":"Petition",
         "docketEntryId":"3d27e02e-6954-4595-8b3f-0e91bbc1b51e",
         "eventCode":"P",
         "filedBy":"Petr. Kaitlin Chaney",
         "filingDate":"2021-01-05T21:14:09.031Z",
         "caseCaption":"Kaitlin Chaney, Petitioner",
         "servedAt":"2021-01-05T21:14:09.031Z"
      },
      {
         "docketNumber":"135-20",         
         "description":"Request for Place of Trial at Lubbock, Texas",
         "docketEntryId":"4d27e02e-6954-4595-8b3f-0e51aabc1b51e",
         "eventCode":"RQT",
         "filedBy":"Petr. Robin Michelle Nathan",
         "filingDate":"2021-01-26T17:25:38.186Z",
         "caseCaption":"Robin Michelle Nathan, Petitioner",
         "servedAt":"2021-01-05T21:14:09.031Z"
      }
      …
   ]
 
}

## Notes
* Any  considerations around sealed information? No, they should get all of it. 

* Can the user look up any date at any time? How long should the information be accessible for? If user queries a date, they should get all documents served on that date. 
* Is the assumption that we're displaying only items from the date of implementation forward, or do we need to consider past service? Whatever is easiest. 
* What should the API endpoint call look like if we're requesting an additional page? Court needs to determine if additional pages are needed - for Mike, include pagniation token - response would include a "getmore" item. IRS preference is to not have pagination. Ifw were able to serve all of them predictably, reliably and confidently, this is the desired approach. If pagination is needed, there's room to determine solution so it's easy for IRS to implement. Mike likes the idea of token, but doesn't want to solution too much.
* How do we indicate whether the report has more pages? See previous answer
* Is this only accessible to the IRS super user and nobody else? Yes, for now. 
* How will we test this? Log in to IRS super user account, access API and have a way to verify expected results. 
* Make sure structures of API/JSON for each document is consistent

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's mig env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by mmarcotte** [comment]
Getting this error when attempting to call endpoint with various dates:

```
{
    "message": "Cannot read property 'caseCaption' of undefined"
}
```

**Comment by kkoskelin** [comment]
Mike,  Can you tell me where this error was seen?  Was it in logs, or did it come over the wire instead of the expected payload?  What was the date you provided?

**Comment by matthopson** [comment]
PR to address ☝️ 
https://github.com/flexion/ef-cms/pull/8060

Will require migration (0024*)

**Comment by matthopson** [comment]
This is now fixed on the migration environment.
