### ISSUE TITLE
Myself as Counsel -- Appearance and Representation documents

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7188]
As the Court, so that the correct filing part displays on the docket record, certain documents filed by practitioners (private and IRS) relating to appearance and representation should show the practitioner's name as the filing party.

## Acceptance Criteria
* The filedBy for all `Request Case Access` documents except for `Motion to Substitute Party and Change Caption` are filed by a Practitioner/Counsel, whose name should display as the `filedBy` on the docket record.
* Motion to Withdraw as Counsel` and `Designation of Counsel to Receive Service` under the Appearance and Representation category are filed by a Practitioner/Counsel, whose name should display as the `filedBy` on the docket record.
* Name should display on docket record as Counsel [full name]

## Notes
* The filedBy for the `Motion to Substitute Party and Change Caption` is one of the petitioners already on the case or a new petitioner (not already in the case -- "Other").
* research the "Who are you filing on behalf of" - need who they are representing 
* Do irsPractitioner first documents also need to be treated this way? Do irsPractitioners need to eFile any of the documents under Appearance and Representation? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by cholly75** [comment]
Closed - resolved w/ ustaxcourt/ef-cms#7880
