### ISSUE TITLE
Development Team: Ensure sign-in at the production domain

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7191]
As a user of EF-CMS, so that I can be sure I’m entering my username and password on a trustworthy site, I need to be able to confirm the login page is trustworthy.

## Acceptance criteria ##
* The user-facing login pages are accessible at either EFCMS_DOMAIN or a variant of EFCMS_DOMAIN (auth.dawson.ustaxcourt.gov, for example).

**Comment by kbighorse** [comment]
Also, password managers like LastPass save passwords by domain by default. They are currently forced to save a `ustaxcourt.gov` password with every other identity on `amazoncognito.com`.

**Comment by cholly75** [comment]
Duplicate -resolved in Feb 2024.
