### ISSUE TITLE
Data Migration: Legacy Practitioners representing "Other Petitioners", Participants, and/or Intervenors

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7203]
As the Court, in order to make sure all legacy practitioner information is accurately captured in the new system, we need the ability to link practitioners with "Other Petitioners", Participants, and Intervenors.

As part of the data migration effort, we have allowed "Other Petitioners", Participants, and Intervenors to come in as "read-only" in the UI.  Legacy practitioners may be representing them.  As a result, in addition to have legacy practitioner information for the primary petitioner (and secondary(spouse), where relevant), we need to also allow a legacy practitioner to be "linked" to these other 'parties'.

## Acceptance Criteria: ##
* Allow data migration team to provide data linking legacy practitioner to "Other Petitioners", Participants, and/or Intervenors
* For **all** legacy practitioners, display who they are representing (primary P,spouse, "Other Petitioners", Participants, and Intervenors)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met
**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by ericsorenson** [comment]
Currently a Case has a list of PrivatePractitioner Users, each with optional `representingPrimary` and `representingSecondary` booleans.

Instead of defining the relationship in the PrivatePractitioner object, I'd like to add an optional `privatePractitionerBarNumbers` list to each `contactPrimary`, `contactSecondary`, `otherFilers`, and `otherPetitioners` objects. Validators will guarantee that the privatePractitioners are included in the case.

**Comment by ericsorenson** [comment]
After a conversation this morning we're leaning towards giving each petitioner a UUID, and referencing those IDs in a client list in the private practitioner object.

All `contactPrimary`, `contactSecondary`, `otherFilers`, and `otherPetitioners` objects will require UUIDs.

Private practitioners will lose the `representingPrimary` and `representingSecondary` booleans and gain a `representing` array.
