### ISSUE TITLE
Usability Study: Court users -  Petitions QC and other associated flows

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7204]
Description:
**Discover any issues users have completing an end-to-end QC of an e-filed petition** 

- Are users able to successfully enter statistics information during the Petition QC process? 
- Are users able to serve the Petition successfully? 
- Are users able to locate the Petitions they have already served?

**Discover any issues users have entering and processing a paper petition and associated documents**

- Are users able to locate where to add a petition received in paper? 
- Are users able to enter metadata and upload all documents? 
- How are users handling the Notice of Receipt of Petition?   

**Determine if users can locate and complete an Order during the Petition process**

- How are users identifying and tracking which Orders are needed?
- Does the user know how to create and serve any Orders associated with the Petition? 

**Discover feature gaps or workarounds required for MVP launch** 
- Are users able to capture all data points in the petition process? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met
**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by swongCO** [comment]
Report link: [https://drive.google.com/drive/folders/1207OwKbgiAcZ5r4hHFjtpzCDgBqJtCq4]
