### ISSUE TITLE
SPIKE: ClamAV

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7212]
As a development team, we need to determine the best approach for keeping ClamAV working efficiently. 

## Acceptance Criteria
* We've determined how to keep ClamAv working efficiently.
* Determine what solution should be and provide recommendation to the Court

## Notes:
* Options seem to be EC2 instances or Fargate.
* Fargate spinups will impact overall scan times
* Implementation will be done in another story (#6282)

**Comment by sutt0n** [comment]
Scalable EC2: https://cloudonaut.io/s3-virusscan-aws-security/

**Comment by sutt0n** [comment]
- EC2 monthly cost calculations (around $42) were almost half of Fargate's monthly cost calculations (around $85)
  - 2 CPUs, 8 GB RAM (can probably scale these resources down and save cost on Fargate)
- Debugging is potentially easier with Fargate (can run Docker image locally)
- Fargate log streaming already set up (would have to implement log streaming on EC2)
- Autoscaling is easier with Fargate

Summary: With Fargate, we can throw a valid config and a Dockerfile at AWS and they manage it for us; however, we own it. With EC2, we both manage _and_ own it. By using Fargate, we reduce a _lot_ of risk with regards to maintenance and difficulty with debugging.

Conclusion: Although it costs more, Fargate seems like a more viable option with regard to engineer friendliness, and setup and configuration -- i.e. "set it and leave it".

cc: @rachelschneiderman @codyseibert @matthopson
