### ISSUE TITLE
Court User: Cancel from signature page

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7215]
As a Court user, if I decide to not sign a document and cancel the "signature" process, I expect to be routed back to where I came from.

## Acceptance Criteria:
* If a Court user decides to cancel the signature process, he/she should be routed back to the previous screen he/she can from.

## Notes:
* Kristen will need to account for all the various ways a person gets to the **Sign Document** screen.

**Comment by klohman** [comment]
## Draft Design 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e90d0a38-5979-4a43-89c5-d8727a5baac4)

**Comment by cholly75** [comment]
This appears to be already completed.
