### ISSUE TITLE
Usability Study: Document-driven workflow - Court-Issued Documents

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7219]
## Description 
  Features to be tested 
- Messaging (with Order creation) 
- Proposed Stipulated Decision
- Add Court Issued Docket Entry 
- Serving Court Issued Documents

#### Research Goals 
**Discover issues for users communicating about court-issued documents via messaging**
* Are users able to send/receive messages about court-issued documents in their workflow? 
* Are user able to create and communication about orders in their workflow?

**Discover issues for users during the Proposed / Signed Stipulated Decision flow**
* Are users able to understand how to sign and save a Proposed Stipulated Decision? 
* Are users able to communicate about Stipulated Decisions vis messaging? 

**Discover issues for users adding a court-issued document to the docket record**
* Are users able to identify and locate draft documents to be added to the docket record? How do they usually locate these documents (messages, drafts)?
* Are users able to save an entry for a court-issued document for later service? How do users locate these documents once saved? 
* Are users able to complete service for court-issued documents? 
* How confident are user in the process of serving?

**Discover feature gaps or workarounds required for MVP launch**
* Are users able to complete all actions required for their jobs?
* Document any edge cases or questions from users

**Comment by swongCO** [comment]
3/14/23 - UX had a discussion with Chris. Going to put our efforts into research that align with future roadmap initiatives so will close this and create a new research story.
