### ISSUE TITLE
Long fields

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7223]
As the Court, we need a way to display long FiledBy, Filings and Proceedings, and Case Captions, in the UI.

The Court may have long FiledBy, Filings and Proceeedings, and Case Captions.  In order to avoid indefinite wrapping, we need a way to display these nicely in the UI.

## Acceptance Criteria:
* Allow long FiledBy, filings and proceedings, and case caption fields to display in a user-friendly manner in the UI

## Notes:
* Longest `FiledBy` field in legacy database is 2,000 characters.
* If we find fields that require more than 2,000, Mark will truncate before passing

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by klohman** [comment]
### Docket record (for Internal, External, Public)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/946f4d2c-2d34-43f6-988f-5f30e08a40e0)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ecead5f6-8e07-465b-9466-f91db0cb4809)
- Set each docket entry to 2 lines (max) 
- Truncate any data fields > 2 lines 
- Display ellipse (...) for truncated entries 
- Display fa-chevron-down icon only if row has data > 2 rows  

**On click of chevron-down  icon**
* expand selected row to full height (dynamic based on data)
* collapse any other expanded rows (only one row should be expanded at a time)  
* hide chevron-down-icon
* display chevron-up icon

#### Expanded Row 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6b2742dd-4adc-4631-b03b-736c1907a30e)
- Display fa-chevron-up icon for expanded row 
- display full data for all columns in the selected row (no truncation)

**on click of chevron-up icon**
* collapse selected row back to default state 
* Display chevron-down icon
* Hide chevron-up icon

### Document View  (Internal Only) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b5d8531e-f5dc-4a9d-90bf-378e9e07a93d)
**Document List table**
* truncate Filings and Proceedings after 2 lines 
* Display ellipses for truncated entries 
* no expand/collapse functionality 

**PDF viewer panel**
- Display Filed By on new line below Filed date  
- Filed by max width = 700px
- Display full Filed By (do not truncate) 


### Docket Record - Mobile View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1f452f62-c81b-44b7-a7d4-97ab202b6dac)

- No change to mobile docket record view 
- Display full Filed By, wrapping text 

### All other tables (for Internal, External, Public)
**Global change to all other tables**
- Table rows should display 2 lines (max) 
- Fields with data > 2 rows should be truncated 
- Display ellipse (...) for truncated data fields 

### Case Header 
**Case caption**
- increase width of case caption text to 700 px 
- remove the current margin-right 
![Screen Shot 2020-09-04 at 9.19.05 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/45b266ef-938e-435b-acf8-88c259354c84)


### Printable PDFs 
* No information should be truncated on Printable PDFs (ex. Printable Docket Record, Pending Report, Trial Session detail, etc.) 
* Long data fields should wrap and display the full text on all printable PDFs.

**Comment by klohman** [comment]
# Draft Test Scenarios 

### 6211 Test Scenarios 

Test data 
- Case xx1-20 
    - Add docket entry 
        - with long filings and proceedings 
    - Add docket entry 
        - with long Filed by 
    - Add docket entry - one line  

### **Internal Users**
#### 1a) Internal user sees docket entry with more than 2 lines on _Filings and Proceedings_ truncated on Docket Record 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filings and Proceedings displays chevron-down icon

#### 1b) Internal user expands truncated docket entry and sees full information for _Filings and Proceedings_
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
* Click chevron-down icon
Expected results
- [ ] Docket entry with long Filings and Proceedings is expanded after 2 lines (shows full text)
- [ ] Docket entry with long Filings and Proceedings no longer displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filings and Proceedings displays chevron-up icon

#### 1c) Internal user collapses expanded docket entry and returns to truncated view of _Filings and Proceedings_
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
* Click chevron-up icon
Expected results 
- [ ] Docket entry with long Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filings and Proceedings displays ellipses displays chevron-down icon

#### 2a) Internal user sees docket entries with more than 2 lines for _Filed By_ truncated on Docket Record 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filed by is truncated after 2 lines
- [ ] Docket entry with long Filed by displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed by displays ellipses displays chevron-down icon

#### 2b) Internal user expands truncated docket entry and sees full information for _Filed By_
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
* Click chevron-down icon
Expected results
- [ ] Docket entry with long Filed By is expanded after 2 lines (shows full text)
- [ ] Docket entry with long Filed By no longer displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed By displays chevron-up icon

#### 2c) Internal user collapses expanded docket entry and returns to truncated view of _Filed By_
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
* Click chevron-up icon
Expected results 
- [ ] Docket entry with long Filed by is truncated after 2 lines
- [ ] Docket entry with long Filed by displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed by displays ellipses displays chevron-down icon


#### 3a) Internal user sees docket entries with more than 2 lines for _Filed By and Filings and Proceedings_ truncated on Docket Record 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filed By and Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses displays chevron-down icon

#### 3b) Internal user expands truncated docket entry and sees full information for _Filed By and Filings and Proceedings_ 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
* Click chevron-down icon
Expected results
- [ ] Docket entry with long Filed By and Filings and Proceedings is expanded after 2 lines (shows full text)
- [ ] Docket entry with long Filed By and Filings and Proceedings no longer displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed By and Filings and Proceedings displays chevron-up icon

#### 3c) Internal user collapses expanded docket entry and returns to truncated view of  _Filed By and Filings and Proceedings_ 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
* Click chevron-up icon
Expected results 
- [ ] Docket entry with long Filed By and Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses displays chevron-down icon


### External Users
#### 4a) External user sees docket entry with more than 2 lines on _Filings and Proceedings_ truncated on Docket Record 
* Login as external
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filings and Proceedings displays chevron-down icon

#### 4b) External user sees docket entries with more than 2 lines for _Filed By_ truncated on Docket Record 
* Login as external 
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filed by is truncated after 2 lines
- [ ] Docket entry with long Filed by displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed by displays ellipses displays chevron-down icon

#### 4c) External user sees docket entries with more than 2 lines for _Filed By and Filings and Proceedings_ truncated on Docket Record 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filed By and Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses displays chevron-down icon


### Public Users
#### 5a) Public user sees docket entry with more than 2 lines on _Filings and Proceedings_ truncated on Docket Record 
* Go to public search
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filings and Proceedings displays chevron-down icon
 
#### 5b) Public user sees docket entries with more than 2 lines for _Filed By_ truncated on Docket Record 
* Go to public search  
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filed by is truncated after 2 lines
- [ ] Docket entry with long Filed by displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed by displays ellipses displays chevron-down icon

#### 5c) Public user sees docket entries with more than 2 lines for _Filed By and Filings and Proceedings_ truncated on Docket Record 
* Login as internal user 
* Navigate to a case xx1-20
* View Docket Record 
Expected results 
- [ ] Docket entry with long Filed By and Filings and Proceedings is truncated after 2 lines
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses
- [ ] Docket entry with one line displays with no ellipses 
- [ ] Docket entry with long Filed By and Filings and Proceedings displays ellipses displays chevron-down icon


#### 6a) Internal users see one docket entry expanded at a time 
* Login as internal user 
* Navigate to case xx1-20 
* Click chevron-down icon for entry with truncated filings and proceedings 
* Click chevron-down icon for entry with truncated filed by 
Expected results 
- [ ] entry with truncated filings and proceedings collapses 
- [ ] entry with truncated filings and proceedings displays chevron-down icon 
- [ ] entry with truncated filed by expands to full height 
- [ ] entry with truncated filed by displays chevron-up icon 

#### 6b) External users see one docket entry expanded at a time 
* Login as external user 
* Navigate to case xx1-20 
* Click chevron-down icon for entry with truncated filings and proceedings 
* Click chevron-down icon for entry with truncated filed by 
Expected results 
- [ ] entry with truncated filings and proceedings collapses 
- [ ] entry with truncated filings and proceedings displays chevron-down icon 
- [ ] entry with truncated filed by expands to full height 
- [ ] entry with truncated filed by displays chevron-up icon 

#### 6c) Public users see one docket entry expanded at a time 
* Go to public search 
* Navigate to case xx1-20 
* Click chevron-down icon for entry with truncated filings and proceedings 
* Click chevron-down icon for entry with truncated filed by 
Expected results 
- [ ] entry with truncated filings and proceedings collapses 
- [ ] entry with truncated filings and proceedings displays chevron-down icon 
- [ ] entry with truncated filed by expands to full height 
- [ ] entry with truncated filed by displays chevron-up icon 

#### 7) Internal users see full Filed by text on Document View 
* Login as internal user 
* Navigate to case xx1-20 
* Click document link for entry with long filed by 
* View Document View 
Expected results 
- [ ] Document View displays full text of Filed by 

#### 8) Internal users see truncated Filings and Proceedings on Document View 
* Login as internal user 
* Navigate to case xx1-20 
* Click document link for entry with long filings and proceedings 
* View Document View 
Expected results 
- [ ] Document View list truncates Filings and Proceedings after 2 lines 
- [ ] Document View list displays ellipses for truncated Filings and Proceedings 


#### 9) External users view full filed by on mobile 
* Login as external user on mobile device 
* Navigate to case xx1-20 
* Click document link for entry with long filed by 
* View Document Details 
Expected results 
- [ ] Document Details displays full text of Filed by


#### 10) Internal users see table rows truncated after 2 lines 
* Login as internal user 
* View tables (throughout application) 
Expected results 
- [ ] All table rows except Docket Record are truncated after 2 lines 
    - Case/Order/Opinion Search Results
    - Practitioner Search Results 
    - Blocked Cases Report 
    - Case Deadlines 
    - Case Pending Report list
    - Individual/Section Messages > Completed 
    - Individual/Section Messages > Sent 
    - Individual/Section Messages > Inbox 
    - Individual/Section Document QC > Inbox 
    - Individual/Section Document QC > In Progress 
    - Individual/Section Document QC > Processed / Served 
    - Case Statistics 
    - Case Inventory Report 
    - Case List (Petitioner/Practitioner/Respondent Dashboard)
    - Pending report 
    - Today’s Opinions
    - Trial Session > All Cases 
    - Trial Session > Open Cases
    - Trial Session > Inactive Cases 
    - Trial Session > Eligible Cases 
    - Working Copy Session List 
    - Judge’s Recent Messages
    - Correspondence 
    - Drafts 

#### 11) Internal/external/public user sees full case caption in Case Header 
* Login as user 
* Navigate to case with long case caption 
* View case header 
Expected results 
- [ ] Full case caption is displayed in Case Header 
- [ ] Case caption has max width = 700px


#### 12) Users see data on Printable Docket Record is not truncated 
* Login as internal user 
* Navigate to case xx1-20 
* Click Printable Docket Record 
expected results 
- [ ] Printable Docket Record displays full Filings and Proceedings and Filed by text for all docket entries 

#### 13) Users see data on printable reports is not truncated 
* Login as internal user 
* Click Reports 
* Run (all) reports 
expected results 
- [ ] Data is not truncated on printable PDFs 
    * Pending Report 
    * Trial Session Detail 
   * Case Inventory Report
