### ISSUE TITLE
Pro-Se Petitioners: Clinic Information on Dashboard

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7224]
As the Court, in order to provide our pro-se petitioners with information about clinics, we need to include some information on their dashboard.

## Acceptance Criteria:
* On a pro-se petitioner's dashboard (no cases and w/ cases), provide link to information on Court's website re: clinics (https://ustaxcourt.gov/clinics.html)

PR - ustaxcourt/ef-cms-flexion#7224

**Comment by klohman** [comment]
### Design Options 

#### V1 - Taxpayer Tools 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d1a3a33a-8448-4c90-9383-34d802aa515a)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/62fd2f33-d24b-4db8-8e5a-f9314b1d4771)

#### V2 - Clinic Card 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e4d15536-62b2-4ae9-a356-d6504fd70482)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ef7524d1-8ccd-4bfa-a0e1-4c64f1fcc18b)

**Comment by JessicaMarine** [comment]
@klohman They want to go with the card version (V2), but it should say: 

**Free Taxpayer Help**

You may be eligible for additional assistance and 
advice through a tax clinic or pro-bono program.

Link to: https://ustaxcourt.gov/clinics.html 
Link language: View Information on Clinics & Pro Bono Programs

**Comment by klohman** [comment]
#### Final Design 

Link URL : https://ustaxcourt.gov/clinics.html

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/58557339-ee87-4840-8216-c013d341d918)


![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8014b803-49f8-4a6a-83d9-d56b64700893)

**Comment by JessicaMarine** [comment]
Jessica reviewed 12.4.2020 -- moved to done
