### ISSUE TITLE
Design + Data Migration: Practitioners Exempt from eFiling

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7225]
**NOTE: De-prioritized from MVP.  We can manually address this for MVP by exporting a CSV of the Exempt_Atty table from the Blackstone database and manually marking each practitioner in the specific case(s) as "paper" service.**

As the Court, in order to identify our legacy practitioners who are exempt from eFiling, we need to pass that information from Blackstone to Dawson.

## Acceptance Criteria:
* CMS is able to accept an indicator that an attorney **on a specific case** is exempt from eFiling. [Note: Attorneys are exempt on a case-by-case basis] 
* Update data migration documentation, as appropriate
* Docket is able to mark a practitioner as exempt from efiling in a specific case
* All court users ~~and parties to the case~~ can see that a practitioner is exempt from efiling in a specific case, once marked by Docket
* Docket is able to un-mark a practitioner as exempt from efiling in a specific case
* Once a practitioner is "un-marked" as exempt, he/she should show up exactly as any other practitioner

## Notes:
* Per Mike McVicker: Added field eFileExempt (type bit) to Attorney entity. A bit = 1 means exempt. [Note: may be on the case-level and not the practitioner-level]

* Would a practitioner be exempt from e-filing from all cases, or does this need to be at the case level? 
* Do admissions clerks need access to mark a practitioner as exempt? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by klohman** [comment]
### Add Petitioner Counsel modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a09b2796-c65a-410c-affb-c18dc733f28f)

* Add “Exempt from eFiling” checkbox 
* Checkbox is optional  

**If “Exempt from eFiling” is checked**
On click of Add to Case button 
* Practitioner is added to case 
* “Exempt from eFiling” message displays for Practitioner 


### Edit Petitioner Counsel modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5e53d284-071b-453b-84a6-405387326cc0)

* Add “Exempt from eFiling” checkbox for each attorney 

**If “Exempt from eFiling” is checked**
On click of Apply Changes button 
* “Exempt from eFiling” message displays for Practitioner 

**If “Exempt from eFiling” is unchecked**
On click of Apply Changes button 
* “Exempt from eFiling” message is hidden for Practitioner 

### Case Detail > Case Information > Petitioner 

**Petitioner Counsel contact info**
* Display “Exempt from eFiling” message when checkbox is checked 
* Display for migrated data when eFileExempt = true

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b2cb5183-fa8e-4f40-bffd-fbb9168c214b)

**Comment by klohman** [comment]
### 6230 Test cases 

#### 1) Docket clerk adds private practitioner to a case and marks them as exempt from eFiling 
* Login as docket clerk 
* Navigate to case 2252-20 (dev)
* Click Case Information > Petitioner tab 
* Under Petitioner Counsel, search for bar number PT1111
* For “Who are you representing” = check petitioner name 
* Select Paper for Service Preference 
* Check “Exempt from eFiling” 
* Click Add to Case 
Expected results 
- [ ] Modal closes and success message displays (current functionality)
- [ ] test privatePractitioner3 displays under Petitioner Counsel 
- [ ] Exempt from eFiling message displays for test privatePractitioner3

#### 2) Docket clerk marks existing private practitioner on a case as exempt from eFiling 
* Login as docket clerk 
* Navigate to case 2039-20 (dev) 
* Click Case Information > Petitioner tab 
* Click “Edit” for Petitioner Counsel 
* For Test private practitioner 2, check “Exempt from eFiling”
* Click Apply Changes 
Expected results 
- [ ] Modal closes and success message displays (current functionality)
- [ ] test privatePractitioner2 displays under Petitioner Counsel 
- [ ] Exempt from eFiling message displays for test privatePractitioner2

#### 3) Docket clerk marks existing private practitioner on a case as not exempt from eFiling 
* Login as docket clerk 
* Navigate to case 2252-20 (dev)
* Click Case Information > Petitioner tab 
* Click “Edit” for Petitioner Counsel 
* For Test private practitioner3, uncheck “Exempt from eFiling”
* Click Apply Changes 
Expected results 
- [ ] Modal closes and success message displays (current functionality)
- [ ] test privatePractitioner3 displays under Petitioner Counsel 
- [ ] Exempt from eFiling message does not display for test privatePractitioner3

#### 4) Internal user sees that a private practitioner is exempt from eFiling on a case 
* Login as adc1
* Navigate to 2039-20 (dev)
* Click Case Information > Petitioner tab 
* View Petitioner Counsel information 
Expected results 
- [ ] test privatePractitioner2 displays under Petitioner Counsel 
- [ ] Exempt from eFiling message displays for test privatePractitioner2

#### 5) External parties do not see that a private practitioner is exempt from eFiling on case
* Login as test private practitioner2
* Click on case 2039-20 (dev)
* Click Case Information > Petitioner tab 
* View Petitioner Counsel information 
Expected results 
- [ ] test privatePractitioner2 displays under Petitioner Counsel 
- [ ] “Exempt from eFiling” message does not display for test privatePractitioner2
