### ISSUE TITLE
Tech Lead: Change Court User's role

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7229]
As the Court’s Tech Lead, I need the ability to change a court user’s role in the system, so I can ensure that they have access to the right functionalities. 

The Court will have employees who switch sections/jobs.  To accomidate this change, we will need to be able to change a user's role in the CMS.

## Pre-Conditions:
* User already exists in the CMS in a Court role

## Acceptance Criteria:
* Ability to change a court user’s role in the system (from one internal section to other internal section).  Note: This does not apply to people moving from internal-to-external or vice-versa. 
* After a Court user's role is changed, they should have access to everything a new user in their new role would have.
* After a Court user's role is changed, they do not need to have access to anything that they previously had access to. [Note: consider what to do about pending messages]

## Notes:
* Role is stored in Cognito and Dynamo -- may want to change it there and see what happens before developing different solution

**Comment by cholly75** [comment]
Already done.
