### ISSUE TITLE
Cognito issues (spike) + design tweaks to emails

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7235]
* Why does creating a new account ask for a PW when the user (pro se Petitioner) is going to get a temporary PW that has to be reset. **It doesn't. A pro se petitioner selects a password on account creation, and is not asked to reset it.**
* How long are temporary credentials good for?  May want to include that in all automated emails (pro se P; practitioners) that go out? **temporary_password_validity_days = 7**
* What happens if temporary credentials expire? **An administrator will need to generate an email with new temp credentials.**
* Subject line of email to practitioners -- "An account has been set up for you with the U.S. Tax Court" instead of “Update your email with the U.S. Tax Court" ✅
* For practitioner emails that go out, we need to ask them to confirm and update their contact information in the new system. Include verbiage in email. **This is a common email for all roles when an account is created by the court.**

Tasks
- [x] Fix bug in petitioner signup `PostConfirmation invocation failed due to error Socket timeout while invoking Lambda function.` https://github.com/flexion/ef-cms/pull/6590
- [x] Verify that a password needs to be reset after login.
- [x] Subject line of email to practitioners -- "An account has been set up for you with the U.S. Tax Court" instead of “Update your email with the U.S. Tax Court" ustaxcourt/ef-cms-flexion#6582
- [x]  For practitioner emails that go out, we need to ask them to confirm and update their contact information in the new system. Include verbiage in email.

**Comment by klohman** [comment]
@JessicaMarine

Updated email text. Let me know if you have revisions.

 ![Screen Shot 2020-09-30 at 11.13.16 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c52bdb1f-3772-410e-ae98-0e00b2d602dc)

**Comment by JessicaMarine** [comment]
@klohman revised email is good to go

**Comment by mmarcotte** [comment]
One thing I noticed is that users generated programmatically do not receive an email to verify their email address. Thus, there appears to be no means for them to reset their password on their own (or to initiate that process programmatically). And I don't see a way to programmatically send that email to verify their email. 

Can you confirm?

**Comment by mmarcotte** [comment]
Looks like ustaxcourt/ef-cms#7153 tracks the above issue.

**Comment by kkoskelin** [comment]
fix for post-confirmation lambda merged in ustaxcourt/ef-cms-flexion#6631 , once merged perhaps revisit this?

**Comment by klohman** [comment]
@kkoskelin @ericsorenson 
![Screen Shot 2020-10-06 at 8.48.30 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8e2949e9-560e-4d27-995f-83f1dbe208ab)

I saw a slight formatting issue on the email (from adding a practitioner)- temporary password should display on a new line (like it did previously)

**Comment by JessicaMarine** [comment]
Reviewed and meets AC. Jessica moved to done 10.7.2020

Will backlog work about auto-confirming email address when Court creates account (practitioners (CSV and through Admissions section); legacy petitioners; internal court users) ustaxcourt/ef-cms#7333
