### ISSUE TITLE
Logging strategy to have better control of what never gets logged

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7239]
When logging objects to the API logs, add functionality to filter out certain keys so that they never get logged. Here is a starter list, to which we should be able to add more in the future:

## Acceptance Criteria:
- [x] Do not log:
- [x]   * token
- [x]   * headers.authorization (bearer token)
- [ ] remove instances where console.log(...) to use one of `applicationContext.logger`:
  - [ ] `.error('errorMessageHere', err)`: an error has occurred, log this and include an object for context
  - [ ] `.warn('highVolume', data)`: useful for logging warnings about activity. Include any relevant info in data
  - [ ] `.notice('userLogin', user)`: useful for metrics and auditing the application's activity
  - [ ] `.info('message here', data)`: not logged to production, but light debugging in lower environments
  - [ ] `.debug('verboseLog', data)`:  messages you want to see for the developer, will not be logged on deployed instance

## Note:
* There are 110 console logs. 
* Mike Marcotte to backlog any additional work needed for post-MVP.

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the **prod** environment

**Comment by mmarcotte** [comment]
Add:
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`

to the never log list. Looks like the `AWS_ACCESS_KEY_ID` is showing up in some logs.

**Comment by adunkman** [comment]
Replaced by https://github.com/ustaxcourt/ef-cms/issues/524.
