### ISSUE TITLE
Filings and Proceedings column is not left aligned on Docket Record

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7242]
**Describe the bug**
The Filings and Proceedings column on the Docket Record is center aligning when wrapping for the external parties view. It seems to be wrapping and aligning properly (left - aligned ) for internal users and for the public view. 

**In which environment did you see this bug?**
stg 

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
Jessica's demo to Chief Judge

**To Reproduce**
1. Login as petitioner, privatePractitioner, irsPractitioner 
2. Click on case (example 487-20, 482-20)
3. View Docket Record 

**Expected behavior**
Filings and proceedings column should be left aligned, even when multiple lines. 

**Actual behavior**
First line is left aligned, and subsequent lines are sometimes centered, sometimes left aligned. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS Catalina
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 84.0.4147.89

**Smartphone (please complete the following information):**

**Additional context**
- the hyperlink portion may be treated differently than the other non hyperlinked text?
- this bug has been addressed before, but it could be that the external parties view was not included in the fix (??)![Screen Shot 2020-09-16 at 1.20.06 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a1a2530-cd68-4c73-a9f5-57a825e0ab85) 

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by rachelschneiderman** [comment]
https://github.com/flexion/ef-cms/pull/6560

Cause of bug - missing `text-left` class on the button containing the document description
