### ISSUE TITLE
Secondary Document not hyperlinked on Docket Record before QC is completed

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7243]
**Describe the bug**
Secondary document (i.e. document filed with Motion for Leave to File, or Motion for Leave to File Out of Time) is not hyperlinked on the Docket Record until it is QC'd. 
The primary document, primary supporting document, and the supporting document for thee secondary document are all hyperlinked on the Docket Record before and after QC

**In which environment did you see this bug?**
stg

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
Jessica's demo to Chief Judge 

**To Reproduce**
1. Login as petitioner 
2. Click on open case 
3. File a Motion for Leave to File [Motion for New Trial] 
4. Upload a PDF for the Motion for Leave to File and the [Motion for New Trial]
5. Submit 
6. Login as docket clerk 
7. Go to case (from above) 
8. View docket record 

**Expected behavior**
- The secondary document (Motion for New Trial) is hyperlinked on docket record before docket QC's it 

**Actual behavior**
- The secondary document (Motion for New Trial) is not hyperlinked on docket record before docket QC's it ![Screen Shot 2020-09-16 at 1.31.25 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ed3803c9-7363-4213-95d7-81a2bc350149)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac OS
 - Browser [e.g. chrome, safari] Chrome 

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by codyseibert** [comment]
https://github.com/flexion/ef-cms/pull/6548

cause of bug:
we were updating an incorrect field when attaching secondary documents
