### ISSUE TITLE
BUG: High priority items in QC Inbox not sorting correctly

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7247]
**Describe the bug**

**In which environment did you see this bug?**

**Business Impact/Severity Reasoning**
We have to process high priority items first. Otherwise, negatively impacts case processing for cases going to trial. 

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/3a552bfc-85b9-46f9-9c86-7c1fb41b83df)

**Comment by mariahkannenberg** [comment]
Original Story: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/1584

**Comment by kkoskelin** [comment]
https://github.com/flexion/ef-cms/pull/6513

**Comment by mariahkannenberg** [comment]
Calendared work items weren't getting high-priority flag set.
Something that slipped through AC and reviews
