### ISSUE TITLE
BUG: Completed work items not displaying in Processed tab

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7248]
Related to ustaxcourt/ef-cms#7291

**Describe the bug**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 1

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Login as docket clerk Go to Section Document QC Inbox
Complete a work item Go to Processed tab

**Expected behavior**
completed work items should display in Processed tab, sorted newest to oldest by Processed date

**Actual behavior**
all completed items are not always displaying in Processed tab
see case 324-20, I completed a Notice of Change of Address and it did not appear in thee Processed newer cases seem to work

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/771b358f-b7ef-48d3-ab82-cea1b9b0540a)

**Comment by sutt0n** [comment]
I'm unable to replicate this unless the work item's creation date has surpassed 7 days.
