### ISSUE TITLE
BUG: Practitioner Dashboard : Case that practitioner is not associated with is displaying in case list

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7249]
**Describe the bug**

**In which environment did you see this bug?**
stg

**Who did you log in as?**
privatePractitioner3

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Login as privatePractitioner3 Click on case 454-20

**Expected behavior**
Case 454-20 should not display on dashboard under Open Cases

**Actual behavior**
* case 454-20 is displaying under Open Cases but the privatePractitioner3 is not associated with the case

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/f0eb9991-265e-4664-b420-74cc5dba61f1)

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/17bd76d9-a7fc-44a8-a8b9-182f83c3c16d)

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/5f230d5d-8584-4dbf-8a2c-a620053401d5)

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/f30cf600-c8ed-4218-8cad-892a5059bb55)

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/a36af68d-6ace-4c8a-9be0-04f812cf1f58)

**Comment by mariahkannenberg** [comment]
KRISTEN:

@Reopening this bug- saw the same issue for irsPractitioner2 - case 446-20

case 446-20 shows no respondent counsel
irsPractitioner2 case list displays case 446-20 Screen Shot 2020-09-15 at 8.35.20 PM.png Screen Shot 2020-09-15 at 8.35.29 PM.png

**Comment by mariahkannenberg** [comment]
Kristen Lohman attached Screen Shot 2020-09-15 at 8.35.20 PM.png to this card Sep 15 at 7:36 PM
Reply
Kristen Lohman attached Screen Shot 2020-09-15 at 8.35.29 PM.png to this card Sep 15 at 7:36 PM
Reply
Kristen Lohman sent this card to the board
Sep 15 at 7:34 PM
Kristen Lohman moved this card from Doing to Bugs
Sep 15 at 7:34 PM
Kris Koskelin archived this card
Sep 14 at 3:14 PM
Kris Koskelin Sep 14 at 3:14 PM
Archiving since I'm unable to reproduce.

Reply
Kris Koskelin Sep 14 at 10:03 AM
Was the case 454-20 modified in some way just prior to this bug report? Is it possible that the delay inherent in elasticsearch would account for the discrepancy you were seeing?

Reply
Kris Koskelin Sep 14 at 9:59 AM
I just attached a screenshot of 454-20 Case Detail as seen by the user "privatePractitioner3" (in STG environment). I see the "Request Access to Case" button in the header, which is as it should be. I am not seeing this case show up under "Open Cases".

Reply
Kris Koskelin attached Screen Shot 2020-09-14 at 9.57.06 AM.png to this card Sep 14 at 9:57 AM
Reply
Kris Koskelin moved this card from Bugs to Doing
Sep 14 at 9:53 AM
Kris Koskelin joined this card
Sep 14 at 9:53 AM
Kristen Lohman attached Screen Shot 2020-09-09 at 10.37.14 AM.png to this card Sep 9 at 9:49 AM
Reply
Kristen Lohman attached Screen Shot 2020-09-09 at 10.37.19 AM.png to this card Sep 9 at 9:49 AM
Reply
Kristen Lohman copied this card from Bug template in list Bugs
Sep 9 at 9:37 AM

**Comment by klohman** [comment]
Moving to completed - cannot reproduce
