### ISSUE TITLE
BUG: Notice of Docket Change / Notice of Change of Address/ Notice of Trial/ Standing Pre Trial Order or Notice - these should be hyperlinked on Docket Record after it's added and page count is wrong

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7250]
**Describe the bug**
Related to 809. 810, 811, 812

**In which environment did you see this bug?**
stg

**Who did you log in as?**
petitioner1
docket clerk 2

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Login as petitioner File a document in a case
Login as docket clerk Go to Document QC Inbox
Select document filed by petition (above) Update Filing parties
Click Complete Add case to an Open trial session

**Expected behavior**
Notice of Docket Change is added to the Docket Record and is hyperlinked for all internal users and parties
Notice of Trial is added to the Docket Record and is hyperlinked for all internal users and parties
Standing PreTrial Order/ Notice is added to the Docket Record and is hyperlinked for all internal users and parties
Page count on docket record should match PDF page counts

**Actual behavior**
Notice of Docket Change is added but not hyperlinked
Notice of Trial is added but not hyperlinked
Standing PreTrial Order/Notice is added but not hyperlinked

page count displays as "0"

Please attach any relevant screenshots in the comments.
* see 497-20

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/be8aa3e0-1ecb-4df8-9085-73871fa9750b)

**Comment by klohman** [comment]
@matthopson Something to double check when this fix goes through, we need to make sure these documents are also being included when the judge "Downloads All Cases" on a trial session. I just saw that was not happening, but assume it's related to no PDF being there.

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6526

**Comment by matthopson** [comment]
The cause of this issue was simply not calling the `countPagesInDocument` and `updateDocketEntry` methods when generating these automatically issued documents the same way we do when we handle manual document filings.
