### ISSUE TITLE
BUG: eFiled Entry of Appearance is not displaying in Docket Document QC Inbox

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7251]
**Describe the bug**

**In which environment did you see this bug?**
stg

**Who did you log in as?**
privatePractitioner2

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
login as privatePractitioner search for docket number for a case the practitioner is not associated with
Click Request Access button Select Entry of Appearance as doc type
Complete form File Document
Login as docket clerk Go to Section Document QC Inbox

**Expected behavior**
* Entry of Appearance should display in Document QC Inbox

**Actual behavior**
* Entry of Appearance does not display in Document QC Inbox

Please attach any relevant screenshots in the comments.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
This bug is related to related to the dynamodb limit on the document QC response. Moving back to bug list until we have a larger discussion on the problem. - Rae

**Comment by klohman** [comment]
This issue to be addressed in https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/6420

Closing this bug as a duplicate.
