### ISSUE TITLE
BUG: Entry of Appearance language not matching after QC

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7253]
**Describe the bug**
Related to ustaxcourt/ef-cms-flexion#809, 810, 811

**In which environment did you see this bug?**
stg

**Who did you log in as?**
privatePractittioner1
docket clerk 2

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Login as privatePractitioner Go to a case not associated with
click Request Access Select entry of appearance as doc type
select primary petitioner as being represented Submit filing

login as docket clerk
Go to Document QC inbox
Select Entry of Appearance (filed above)
Click Complete button

**Expected behavior**
* entry of appearance entry should display "Entry of Appearance for [represented party]" for both internal and external users

**Actual behavior**

* Entry of Appearance docket entry displayed as "Entry of Appearance for [represented party]" on docket record before the document was QC'd

After being QC's the docket record updated to "Entry of Appearance" and
a Notice of Docket Change is being issued

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/5da9827f-d05b-47bf-ba06-bdfc85f88e83)

**Comment by rachelschneiderman** [comment]
I believe this bug has been fixed as part of the fix for this bug: 

https://trello.com/c/1R11j7Ut/809-notice-of-docket-change-is-being-generated-when-no-change-was-made

**Comment by rachelschneiderman** [comment]
Cause - document title was being overridden with initial document title after QCing.
