### ISSUE TITLE
BUG: Notice of Intervention/Notice of Election to Intervene/ Notice of Election to Participate not being served when eFiled

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7257]
**Describe the bug**
When efiled by a private Practitioner to request access to case, these documents are not being served. eFiled documents should be served when submitted
* Notice of Intervention
* Notice of Election to Intervene	
* Notice of Election to Participate	 

**In which environment did you see this bug?**
stg

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
regression testing

**To Reproduce**
1. Login as privatePractiioner 
2. Search for a case the practitioner is not associated with 
3. Click Request Access button 
4. Select Notice of Intervention / Notice of Election to Intervene / Notice of election to Participate as doc type
5. Complete form
6. Submit filing 

**Expected behavior**
* Document should be served on parties 
* Docket entry should display with served date and parties entered 

**Actual behavior**
* Document is not served on parties 
* Docket entry is displaying as Not Served 

**Screenshots**
![Screen Shot 2020-09-18 at 10.49.37 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bdb542ae-543b-4008-ada3-445d1c4afe45)

**Desktop (please complete the following information):**

**Additional context**
The other documents in the Request Access form seem to be working correctly. The Motion to Substitute Parties and Change Caption is being served when submitted. 

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by sutt0n** [comment]
Engineering notes: Met with @JessicaMarine and old documents that weren't automagically served upon creation for these document types will be served via an `umzug` migration and the `servedAt` date be set to its creation date, `createdAt`. Not worrying about SES (email service).

**Comment by mariahkannenberg** [comment]
Root cause - Related to docket entry migration
More thorough unit test
