### ISSUE TITLE
BUG: Service email not displaying Index number

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7258]
**Describe the bug**
Service email for documents is not displaying the Index number . 

**In which environment did you see this bug?**
stg

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
regression testing

**To Reproduce**
1. login as docket clerk 
2. Go to case with flexionustc+petitioner@gmail.com as petitioner 
3. Click Create menu and select Paper Filing 
4. Complete form 
5. CLick Save and Serve 
6. Login to flexionustc+petitioner@gmail.com

**Expected behavior**
Service email should contain Index no. for document corresponding to the docket record index no.

**Actual behavior**
index no. is blank

**Screenshots**
![Screen Shot 2020-09-18 at 2.34.32 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/14b377ed-afb8-4674-8f1e-0a7821191bde)
![Screen Shot 2020-09-18 at 2.34.42 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e3c14114-dbaa-4f34-a4d4-816536e6777e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Process for logging bug:
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

Severity Definition:
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by kkoskelin** [comment]
https://github.com/flexion/ef-cms/pull/6521

**Comment by matthopson** [comment]
This was mainly due to the way we generate those indexes. The logic needs to evaluate whether the document was served - which is a distinctly separate set of actions. The remedy is setting the docket entry as served, THEN updating the docketEntry on the docket record (which should evaluate whether to generate an index), THEN issuing service.

We have to break up the service flow a little - but only in how the code reads.
