### ISSUE TITLE
BUG: Deadline date not saving correctly

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7259]
**Describe the bug**
When entering a deadline, the date is changing to 12/31/00 

**Person Who Found the Bug**
Kristen 

**Business Impact/Reason for Severity**
Court will miss deadlines. Cannot accurately manage case load. 

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
regression testing 

**To Reproduce**
1. Go to case 
2. Click Create menu and select Deadline 
3. Select date 
4. Click Add Deadline 

**Expected Behavior**
Date entered should display on Deadlines table. 

**Actual Behavior**
Date entered does not display on Deadlines table; date is displaying as 12/31/00.

**Screenshots**
![Screen Shot 2020-09-18 at 2.53.05 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea723c37-8114-46da-b05f-6a5a616a2cff)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The USWDS datepicker expects date inputs to be returned in the MM/DD/YY format. We use `document.getElementById` on date inputs, which returns the input value as MM/DD/YYY. However,  When using a modal (as in the case of case deadlines), `document.getElementById` does not successfully find the date input, making us use `inputRef`. However, `inputRef` does not return the date in the expected format (MM/DD/YYY) but instead returns it as YYY/MM/DD. This was causing failures in the `castToISO` method in the date helper.

PR - https://github.com/flexion/ef-cms/pull/6514

**Process for logging bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

**Severity Definition:**
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by mariahkannenberg** [comment]
Related to date plug in?
Check to see if it's happening in all places where date selector is.

**Comment by mariahkannenberg** [comment]
Go through all the places where we're using the modal and make sure it's working correctly.
