### ISSUE TITLE
BUG: when Order is changed , PDF on Signature page is not updating

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7260]
**Describe the bug**
When creating an order, if you edit the Order title or the Order content and save, the generated PDF is still displaying the original Order on the Add Signature screen.

**Person Who Found the Bug**
Kristen 

**Business Impact/Reason for Severity**
* Affecting content of orders - which is how they direct parties to do things. Needs to be accurate. 

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
regression testing 

**To Reproduce**
1. Go to case 
2. Click Create menu and select Order 
3. Select Order for Dismissal 
4. Continue 
5. Enter text and Save 
6. Skip Signature
7. Click Edit link 
8. Click Edit Order title 
9. Select Order to Show Cause 
10. Click Continue 
11. Click Save 
12. View pdf on Apply signature page 

**Expected Behavior**
The generated PDF should display the updated Order title (Order to Show Cause) 

**Actual Behavior**
The pdf on the Apply Signature page displays the original Order title (Order for Dismissal). 
Oddly, when entering the order text in the text editor, if you click the PReview tab, the PDF displays the updated Order title, but it does not update it on the Apply Signature screen.

**Screenshots**
![Screen Shot 2020-09-18 at 3.12.24 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/47dad242-ea33-4114-a769-a65ae9a0641f)

![Screen Shot 2020-09-18 at 3.12.31 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/77935939-c5bd-45c9-aa58-757d7e130f2a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for logging bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

**Severity Definition:**
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by kkoskelin** [comment]
Looks like this one might have already been fixed on dev, just waiting for deploy to staging?
