### ISSUE TITLE
BUG: Upload PDF - when changing PDF, the new PDF is not displaying

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7262]
**Describe the bug**
For an uploaded PDF in the Drafts table, when you click Edit and change the PDF, the updated PDF is not displaying when you save. The PDF preview continues to show the original PDF. 

**Person Who Found the Bug**
Kristen 

**Business Impact/Reason for Severity**
* Court has wrong PDF - inacurate information. 

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
regression testing

**To Reproduce**
1. Go to case 
2. CLick Create menu and select Upload PDF 
3. upload a pdf 
4. Save 
5. Click the Edit link from the Drafts screen 
6. Click Change PDF 
7. Upload a new PDF 
8. Click Save 

**Expected Behavior**
The updated PDF should display in the PDF preview. 

**Actual Behavior**
The original PDF is displaying in the PDF preview, and it appears that the updated PDF was not saved. 
This is happening for PDF uploads in Drafts and the Correspondence file. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for logging bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

**Severity Definition:**
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by sutt0n** [comment]
Same bug is happening for `Correspondence` files
