### ISSUE TITLE
BUG: Drafts screen - There should never be no document selected

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7263]
**Describe the bug**
On the Drafts screen, there should always be a document selected from the list and displayed in the preview unless there are no draft documents. 

**Person Who Found the Bug**
Kristen

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**
regression testing 

**To Reproduce**
1. Go to Drafts screen 
2. Click Create menu and select PDF upload 
3. Save 
2. Click Create menu and select PDF upload 
3. Save
4. Click Delete on the second PDF uploaded
5. Click Yes, Delete

**Expected Behavior**
If there are documents in the Drafts table, the first document in the list should be selected and display in the preview 

**Actual Behavior**
No item is selected from the list. The preview panel displays with no actual PDF and includes Delete and View Full PDF links. 

**Screenshots**
![Screen Shot 2020-09-18 at 3.43.08 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/60d3a0b1-27a8-4465-a0e4-c0720e365164)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Multiple different paths leading to drafts screen, combined with the fact that all the actions done before arriving at this screen change the state of the app.

PR 1 - https://github.com/flexion/ef-cms/pull/6470
PR -2 https://github.com/flexion/ef-cms/pull/6520

**Process for logging bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

**Severity Definition:**
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by rachelschneiderman** [comment]
Fixing this bug will address currently failing smoketests, therefore, we will pick this issue up now over the other medium severity bugs in the backlog.

**Comment by klohman** [comment]
@rachelschneiderman @mrinsin Tested on stg and I'm still seeing the happening. Let me know if you want to pair.

**Comment by mrinsin** [comment]
Paths verified: 
- Consolidated all the different code actions that were setting the selected draft document to display
-  Newly uploaded pdf is the selected document on Drafts screen
-  Newly uploaded Order/Notice is the selected document on Drafts screen
- Deleting a draft no longer displays 'deleted' pdf after deletion. Now selects and displays default draft doc
- After Editing/Applying/Removing Signature on a draft doc, the newly updated document is selected
- Default behavior - when arriving at the drafts screen from somewhere unrelated, the first draft document is always selected

@klohman

**Comment by klohman** [comment]
@mrinsin 
Default behavior - when arriving at the drafts screen from somewhere unrelated, the first draft document is always selected

- this works some of the time, and maybe it's a caching issue (???) when i click to different tabs within the case, the last updated draft is selected. When I click to Document QC and search for the case and return, the  last updated draft is selected. But when i refresh and return to Drafts screen the first is selected.

**Comment by klohman** [comment]
@JessicaMarine The default behavior for Drafts screen (not linking directly from document link)  is that the first draft document will be selected - this currently requires a refresh, or the user to initiate another workflow that resets the case. I'd like to move this Bug to Closed, and add a UX Pain Point for the future to perhaps revisit when this refresh happens (when user clicks around within the case versus when they click away and back to the case).

**Comment by JessicaMarine** [comment]
@klohman I think having the first document selected as the default (if you're not linking directly from a particular document link) is perfectly fine, even if you start clicking around the case.

**Comment by klohman** [comment]
@mrinsin Can you make this change easily now? (See Jessica's comment above). If so, i can move back to In Progress and delete the Trello card i created.

**Comment by mrinsin** [comment]
@klohman Not sure how easy of a change this would be.. sorry! Might make sense to just have a Trello card for the requested change?

**Comment by klohman** [comment]
@mrinsin @JessicaMarine I'll keep this bug closed for now and enter another for the draft default state so we can prioritize appropriately.
