### ISSUE TITLE
BUG: "Migrated" showing under Filed by for RQT

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7264]
**Describe the bug**
"Migrated" is displaying under the Filed by for a minute entry for Request for Place of Trial. This should only display for migrated legacy cases and not for eFiled cases created in Dawson. 

**Person Who Found the Bug**
Kristen 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to case 420-20 in stg.
2. View docket record 

Not sure how to produce this result, but I've seen it on two cases that should not have it. 

**Expected Behavior**
A minute entry for RQT generated during eFiling the Petition should not have a Filed by. 

**Actual Behavior**
RQT Filed By column displays Migrated

**Screenshots**
![Screen Shot 2020-09-18 at 3.59.12 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/77c858b0-4b2f-4e2f-af22-f81520668851)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for logging bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 
* For critical and high-severity bugs, communicate immediately to project manager or tech lead
* For medium or low severity, review daily during stand up

**Severity Definition:**
* Critical defects usually block an entire system’s or module’s functionality, and testing cannot proceed further without such a defect being fixed. An example of a critical defect is an application’s returning a server error message after a login attempt.
* High-severity defects affect key functionality of an application, and the app behaves in a way that is strongly different from the one stated in the requirements, for instance, an email service provider does not allow adding more than one email address to the recipient field.
* Medium-severity defects are identified in case a minor function does not behave in a way stated in the requirements. An example of such a defect is a broken link in an application’s Terms and Requirements section.
* Low-severity defects are primarily related to an application’s UI and may include such an example as a slightly different size or color of a button.

**Comment by ericsorenson** [comment]
This is a direct result of one of our umzug migrations. It won't happen again, as we won't be running this migration anymore.

https://github.com/flexion/ef-cms/blob/develop/web-api/migrations/00030-docket-record-to-document.test.js#L161
