### ISSUE TITLE
BUG: Document title not displaying on "Are You Ready to Initiate Service" modal initiated from Document View

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7289]
**Describe the Bug**
When launching the "Are You Ready to Initiate Service" modal from the Document View, the document title is not populating. When launching this modal from the Document QC screen (/complete), the document title does display as expected. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Go to case 
2. Click Create menu and select Add Paper Filing 
3. Complete form and click Save for Later 
4. Click Document View 
5. Select newly added paper filing 
6. Click Serve on Document View screen 

**Expected Behavior**
"Are You Ready to Initiate Service" modal should open with document title displayed. 

**Actual Behavior**
"Are You Ready to Initiate Service" modal opens but document title is blank. 

**Screenshots**
![Screen Shot 2020-09-21 at 1.37.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ce87ec34-cfaf-4700-8ec1-7544f797d49a)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] chrome

**Cause of Bug, If Known**
unknwon

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**Comment by rachaelparris** [comment]
I can't recreate this. Moving to Review/QA to verify.

**Comment by klohman** [comment]
@rachaelparris I am able to recreate, but only following these exact steps:

1. Go to case
2. Click Create menu and select Add Paper Filing
3. Complete form and click Save for Later
4. On docket record, click the link for the unserved paper filing
5. Click Serve on Document View screen


![Screen Shot 2020-10-05 at 9.22.00 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/28753d81-f90a-4cdb-baa8-533489744b32)
