### ISSUE TITLE
BUG: Docket clerk removing PDF from un-served docket entry is not removing the PDF and the entry is still hyperlinked

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7290]
**Describe the Bug**
When a docket clerk saves a paper filing to the docket record with a PDF attached, then removes the PDF and saves, the original PDF that was supposedly removed is still displaying, and the docket entry is still showing as hyperlinked to that old PDF.  

**Business Impact/Reason for Severity**
User will end up with wrong document. Inaccurate info. 

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case 
2. Click Create menu and select PDF Upload 
3. Complete form including uploading PDF 
4. Click Save for Later 
5. Go to Document QC In Progress tab 
6. Click on the document you just added 
7. Click Remove PDF 
8. Click Yes, Delete 
9. Click Save for Later 
10. Navigate to case > Docket Record 
11. Click on hyperlink for document you added 
12. Go to Document QC In Progress tab 
13. Click on the document you just added 

**Expected Behavior**
Docket entry for a document without a PDF attached should not be hyperlinked. 
Docket entry without PDF should not display in Document View 
Document QC (/complete) screen for entry should not display the PDF that was removed and should display the incomplete docket entry alert. 

**Actual Behavior**
Docket entry for a document without a PDF attached is still hyperlinked 
Docket entry where I removed the PDF is displaying in the Document View and is still showing the deleted PDF
Document QC (/complete) screen for entry is still showing the deleted PDF 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - mac os
 - Browser [e.g. chrome, safari]- chrome

**Cause of Bug, If Known**
unknown

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6541

**Comment by matthopson** [comment]
Cause: The underlying code was not calling a delete for the given PDF. I'm not 100% sure, but it's possible this went unnoticed prior to consolidating DocketRecord and Document entities due to the way in which the document was fetched when they were separate.

In addition to the pdf not being deleted on s3, the `isFileAttached` flag was not being properly unset.
