### ISSUE TITLE
BUG: privatePractitioner/irsPractitioner not associated with case should see Public Printable Docket Record

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7292]
**Describe the Bug**

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
dev/ stg 

**Who were you logged in as?**
irsPractitioner1
privatePractitioner3

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Regression Testing

**To Reproduce**
* Login as irsPractitioner or privatePractitioner 
* Search for a docket number not associated with the practitioner 
* Click Printable Docket Record 

**Expected Behavior**
* PDF should be the Public Printable Docket Record (i.e. does not display the petitioner contact information) 

**Actual Behavior**
* Seeing internal docket record. PDF displays the petitioner contact info.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Endpoint (lambda) always told interactor to include the party detail. But the interactor never verified whether the requesting individual had permission to see it.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
https://github.com/flexion/ef-cms/pull/6543

**Comment by klohman** [comment]
Moving to Completed - cannot reproduce.
