### ISSUE TITLE
BUG: In staging and dev, when you Set Calendar for a trial session, the calendar is set but the modal does not close

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7293]
**This bug was previously closed - reopened 7/10/20**

**Describe the Bug**

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**

**Actual Behavior**
- When you click Set Calendar, modal display s
- When you confirm _ Yes, Set Calendar, the screen behind refreshes and shows the calendar as set but modal remains open 
- Notice of Trial is not being issued on the cases and Notice Issued is not being populated on Open Trial Sessions table 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Monolambda was not deployed correctly with the async lambda during a major refactor.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mariahkannenberg** [comment]
UX review - modal now closes but the spinner remains. The calendar is set but spinner never goes away. The Notice of Trial and Standing Pre Trial Order/Notice are being added to the docket record, but they are not hyperlinked. - Kristen (8/31/20)

**Comment by mariahkannenberg** [comment]
This is related to Spike: For previously `async: true` lambda functions, use SQS (Rachael 7/23/20)

**Comment by rachaelparris** [comment]
This appears to already be fixed. I will note that the spinner will spin for a while because there is actually work being done in the background that's being waited on. Eventually (when I tested it anyway) it does redirect to the paper service screen.
