### ISSUE TITLE
BUG: Edit Docket Entry - New cover sheet is generated but not displaying updated Filed Date / New cover sheet is generated when it should not

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7295]
**Describe the Bug**
This bug involves two closely related issues: 
 
1) When a docket entry's "Filed date" is edited via the "/edit-meta" screen, a new cover sheet is being generated and applied to document but the updated information is not displaying on that new cover sheet
2) When a docket entry is edited via the "/edit-meta" screen (but the Filed date is not changed), a new cover sheet is being generated but should not be generated. For example, if text is added to the "additional info" field, a new cover sheet is erroneously applied.
 
**Business Impact/Reason for Severity**
Impacts PDFs on the docket record. 

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to case 
2. Click Create menu and select Paper Filing 
3. Select Filed date - [9/21/20] 
4. Complete form 
5. Click Save and Serve
6. Click Edit link on docket entry 
7. Change FIled date 
9. Save 
10. View PDF 
11. Click on "edit" for e-filed docket entry 
12. Update any other field besides Filed date 
13. Save 
14. View PDF 

**Expected Behavior**
For docket entry where Filed By was changed, a new cover sheet should be applied displaying the updated FIled date
For docket entry where field other than Filed By was changed, cover sheet should not be re-created. 

**Actual Behavior**
A new cover sheet is applied to the document but it is not displaying updated Filed Date or document title.The original cover sheet displays original info behind the new cover sheet.  Docket entry displays updated Filed Date and filings and proceedings. 

**Screenshots**
![Screen Shot 2020-09-21 at 2.25.39 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a4534a3d-06fa-4ff1-b5a1-306ba3bd0c15)![Screen Shot 2020-09-21 at 2.25.49 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cb1aac42-341e-441e-92fe-eff71a1e37d6)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - mac OS
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
`updateDocketEntryMetaInteractor` was calling `addCoverSheetInteractor` but retrieveing the updated docketEntry form persistence, so the new `filedBy` date was not used in the coversheet.
Also, `addCoverSheetInteractor` was not being called with `replaceCoversheet: true`, which is why new coversheets were being prepended each time.

PR - https://github.com/flexion/ef-cms/pull/6536 
PR- https://github.com/flexion/ef-cms/pull/6565/

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
There is a test case written in this story stating that a new cover sheet should be applied in certain scenarios https://github.com/flexion/ef-cms/issues/3914 

@JessicaMarine Based on this morning's discussion, was this incorrect? I want to correct any documentation related to it if so.

**Comment by JessicaMarine** [comment]
@klohman I think that scenario is in error then.  The note in ustaxcourt/ef-cms#7007 says: This story doesn't cover changing PDFs, including those that are system-generated.

**Comment by JessicaMarine** [comment]
@klohman I just looked at that scenario (#4) in ustaxcourt/ef-cms#7007 closer and Tina must have added that when I was out -- I guess the correct behavior is that a new cover sheet is added when the *DATE* is changed, but nothing else

**Comment by klohman** [comment]
@mrinsin 

some comments from UX Review (that I'd like Jessica to also confirm)
- When the Filed date is edited on a docket entry, it should generate a new cover sheet, but the original cover sheet should still remain. The PDF should include new cover sheet, original cover sheet, and document. 

- The new cover sheet is showing the updated Filed Date but shows the original "Received Date". For this scenario, the Received Date and Filed date should be updated

@JessicaMarine Can you confirm that this ^^ is the expected functionality.

**Comment by JessicaMarine** [comment]
@klohman @mrinsin 

- When the Filed date is edited on a docket entry, it should generate a new cover sheet, but the original cover sheet should still remain. The PDF should include new cover sheet, original cover sheet, and document. [Jessica: Yes, this is fine]

- The new cover sheet is showing the updated Filed Date but shows the original "Received Date". For this scenario, the Received Date and Filed date should be updated [Jessica: The original "Received Date" is okay to remain, as long as the "Filed Date" is being updated.]

**Comment by klohman** [comment]
@mrinsin 
I'll move this back to In Progress. Just one thing to fix: 
- When the Filed date is edited on a docket entry, it should generate a new cover sheet, but the original cover sheet should still remain. The PDF should include new cover sheet, original cover sheet, and document.

**Comment by JessicaMarine** [comment]
@mrinsin Please wait until after design meeting on Monday to pick this back up.  We need some input from Joeliette to determine expected behavior.

**Comment by mariahkannenberg** [comment]
* both the filed date and the received date should update to the new date. A second cover sheet is generated to display the changed dates. The original cover sheet remains. 

* Jessica will backlog story to generate a notice of docket change and update the document title.
