### ISSUE TITLE
BUG: Filings and Proceedings for initial documents added after case creation but before Petition is served not displaying on Docket Record/ Document View

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7299]
**Describe the Bug**
When creating a case from paper, if you add PDFs after the case has been created, the Filings and Proceedings is not displaying on the entry. The docket entry is created and displays all other columns except Filing and Proceedings. This does not happen when those PDFs are added prior to case creation. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Document QC 
2. Click Start Petition 
3. Upload Petition 
4. Complete form
5. Click Create Case button 
6. Click Edit link 
7. Add PDF for RQT, ODS, APW 
8. Click Review Petition 
9. Serve Petition 

**Expected Behavior**
Initial documents added before Petition is served should be added to the docket record with Filings and Proceedings hyperlinked. 

**Actual Behavior**
Docket entry is created for initial documents but the Filings and Proceedings column is empty.  

**Screenshots**
![Screen Shot 2020-09-22 at 11.33.11 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c1a87f3f-dafe-4932-84e2-64f37ab87b75)

![Screen Shot 2020-09-22 at 11.40.12 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a1e4636e-05bb-4107-9760-6732b5b6f0f2)
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac os 
 - Browser [e.g. chrome, safari] chrome 

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6569
