### ISSUE TITLE
BUG: Open Trial Sessions table not displaying all columns consistently

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7302]
**Describe the Bug**
When I click on Trial Sessions from main navigation, the Open Trial sessions tab displays but is not showing all columns in the table. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Click Trial Sessions from main nav
2. Click New tab 
3. Click Open tab 

**Expected Behavior**
All columns for the table on the Open tab should display on load. 

**Actual Behavior**
When first clicking to the Open tab, the table is not displaying the No. of cases or Notice issued column. 

When you click to another tab (New, Closed, all) and then click back to the Open tab, all columns display. 

**Screenshots**
![Screen Shot 2020-09-23 at 1.36.26 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f5de2fc0-10b2-463b-8a53-596af4ae2279)

![Screen Shot 2020-09-23 at 1.41.06 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6ef836cf-acd7-457e-bb72-0f5bcf9b0940)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - mac os 
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
        * Blocks entire system's or module’s functionality
        * No workarounds available
        * Testing cannot proceed further without bug being fixed. 
* High-severity Defect
       * Affects key functionality of an application
       * There's a workaround, but not obvious or easy
       * App behaves in a way that is strongly different from the one stated in the requirements
* Medium-severity Defect
       * A minor function does not behave in a way stated in the requirements.
       * Workaround is available and easy
* Low-severity Defect
       * Mostly related to an application’s UI
       * Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
@klohman Is this a duplicate of [#6523](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/6523)?

**Comment by klohman** [comment]
@rachelschneiderman Sorry i didn't see this comment earlier! No, this is not a duplicate of 6523. For some reason, two columns aren't always displaying on the Open tab. The "No. of Cases" column can go away (that's what 6523 is about) but the "Notice Issued" column should display (consistently) on the Open tab. Let me know if there are more questions.

**Comment by rachelschneiderman** [comment]
@klohman No problem! I just tried to recreate on staging, dev, and my local and could not reproduce the problem. Let me know if you can!

**Comment by klohman** [comment]
@rachelschneiderman I can't reproduce now either. Maybe this was fixed by another bug fix! Moving to Closed. Thanks!
