### ISSUE TITLE
BUG: Error message on Judge's trial session download

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7304]
**Describe the Bug**
When trying to download cases for Phoenix, Arizona for Judge Gale, system throws a "File Compression Error" and cannot download the cases.  

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
jgale@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Login as Judge Gale 
2. Click on Phoenix, Arizona trial session from Upcoming trial sessions
3. Click on "Download all cases"

**Expected Behavior**
Progress bar displays while files are compressed and when completed, cases are downloaded successfully. 

**Actual Behavior**
File Compression Error displays and no cases are downloaded. 

**Screenshots**

![Screen Shot 2020-09-23 at 2.11.16 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5dc45619-f6a2-4cba-a980-41ff5b7f5423)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
Observations: shared/src/business/utilities/getChromiumBrowser.js produces `spawn ETXTBSY` on both `stg` and `dev`. See also: https://app.honeybadger.io/projects/69162/faults/68056264
This could be related to the fact that this js file contains 
`
const chromium = require('chrome-' + 'aws-lambda');
`
