### ISSUE TITLE
BUG: Error message when clicking on Trial Session link

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7307]
**Describe the Bug**
When clicking the trial session link from the Trial Sessions screen, error is thrown.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
clerk of court
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Trial Sessions
2. Click New tab
3. Click Washington,DC session for 2/8/21

**Expected Behavior**
App should route to Trial Session detail 

**Actual Behavior**
Error page displays

**Screenshots**
![Screen Shot 2020-09-25 at 4.04.15 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/61ba220f-3bc8-4abf-8177-6770ed4bd87b)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
Analysis:  the `eligible-cases` endpoint is returning a Case entity validation error.
