### ISSUE TITLE
BUG: Trial judge not displaying correctly when case is Scheduled for Trial

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7309]
**Describe the Bug**
When a case is scheduled for trial (i.e., manually added to a session that has not been set), the trial judge is displaying "Chief Judge" on the Case Information page instead of the actual trial judge assigned to the session. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
clerk of court 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case 
2. Click Case Information tab 
3. Click Add to Trial 
4. Select a trial session that has not been set 
5. Click Add Case 

**Expected Behavior**
- Trial information card displays as "Scheduled" 
- Place of trial displays New York,NY and hyperlinked 
- Start date displays as 01/06/21 
- Trial Judge displays as Judge Ashford
- Case status does not change 
- Case header displays judge as Chief Judge

**Actual Behavior**
Trial Judge on Trial Information card displays as Chief Judge 

**Screenshots**
![Screen Shot 2020-09-28 at 9.42.30 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7620de35-3ebc-4ad6-9116-f4ac79c101e2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6574
