### ISSUE TITLE
BUG: Case that is "Scheduled" for trial is displaying on the eligible case list for another trial session

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7311]
**Describe the Bug**
A case that was manually added to a New trial session and displays as "Scheduled" is showing in the eligible case list for another trial session. Per AC on [#3254](https://github.com/flexion/ef-cms/issues/3254), when a case is manually added to a session, it should not be picked up on any intervening trial sessions as eligible.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
clerk of court 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case > Case Information 
2. Click Add to Trial 
3. Add case to a New session (that has not been set) for a city other than the requested place of trial
4. Go to Trial Sessions and select a New session with the requested place of trial 

**Expected Behavior**
Case that is scheduled for trial for another session does not show on eligible list for another session. 

**Actual Behavior**
Case that is scheduled for trial for another session displays on eligible list for another session. 
example - 699-20 is scheduled for Houston, TX but displays on eligible list for Boise. 

**Screenshots**
![Screen Shot 2020-09-28 at 2.43.53 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1096371b-7b96-4e96-ab68-fb90a85b3db0)![Screen Shot 2020-09-28 at 2.44.16 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/691c6a63-15fe-4023-9225-c6bcff01266c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Filters were used to filter out blocked cases from eligible list. This bug may be able to be fixed in the same way. 

https://github.com/flexion/ef-cms/pull/6564#pullrequestreview-497799974

**Comment by sutt0n** [comment]
Unable to reproduce w/ @klohman & @matthopson
