### ISSUE TITLE
BUG: Address label page is not displaying In Care Of for petitioner contact info

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7315]
**Describe the Bug**
For petitioner's with an "In Care Of" in the contact information, the address label is only displaying the petitioner name and not displaying the c/o. This applies to the Notice of Receipt of Petition, and address label page for any served filings. 

**Business Impact/Reason for Severity**
Court will not mail documents to the right recipient -- could be considered ineffective service

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
demo to petitions for training

**To Reproduce**
1. Go to case with party type Estate w/ Executor 
2. Click Case Information 
3. Click Print Confirmation 
4. Add Paper Filing and Serve 

**Expected Behavior**
The address label should display the complete address including "In Care of" field. 

**Actual Behavior**
The address label is only displaying the petitioner name. 

**Screenshots**
![Screen Shot 2020-09-29 at 3.43.31 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fe68c098-ef3a-4801-8f0b-d261e3e65a2f)

![Screen Shot 2020-09-29 at 3.43.43 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c3db43cf-fb1a-4d97-97a6-2065900ae179)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
@JessicaMarine This bug is now fixed, but I'm wondering if this will impact the full address fitting into the window envelope properly. Do you want us to investigate this or leave as is? ![Screen Shot 2020-10-05 at 9.56.17 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8de9f034-38ce-4785-9cef-aafd87fc3d7e)

**Comment by JessicaMarine** [comment]
10.5.2020 -- Jessica confirmed that 7 lines of text does fit in window of window envelope.
