### ISSUE TITLE
BUG: App should remain on Drafts screen after draft document is deleted

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7318]
**Describe the Bug**
When user deletes a draft document, the app routes back to the Docket Record tab, but it should remain on the Drafts tab. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
internal user 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case
2. Click Create - PDF Upload 
3. Upload PDF and save 
4. Click Delete 
5. Click, Yes, Delete

**Expected Behavior**
Selected document should be deleted, and app should remain on the Drafts screen. 

**Actual Behavior**
Selected document is deleted, but the app routes to Docket Record tab. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
@klohman I tried to reproduce on local, dev, and staging, can't seem to get this bug to happen. Can we discuss together at some point?

**Comment by klohman** [comment]
@rachelschneiderman I tried several times on stg again and couldn't reproduce. I'll move to Closed and just reopen if it happens again.
