### ISSUE TITLE
BUG: Email Confirmation not working

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7319]
**Describe the Bug**

When trying to create a new account on the USTC's `test` environment, I received my email from Cognito to validate my email address. However, upon clicking the link a period of time went by before the process eventually failed with this error:

> PostConfirmation invocation failed due to error Socket timeout while invoking Lambda function.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

* USTC: Test
* Flexion: exp2

**Who were you logged in as?**
Couldn't login 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Just going to the site, logging in, trying to create a new user

**To Reproduce**
1. Go to https://app.exp2.ustc-case-mgmt.flexion.us/
2. Click on Sign Up
3. Enter in an email address that you manage
4. Click the link in the email confirmation
5. See error 

**Expected Behavior**

Auth flow should continue, and I should be able to login as a petitioner

**Actual Behavior**

I received an error

**Screenshots**

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
na

**Cause of Bug, If Known**

Not sure of the root cause, but the Lambda appears to not be responsive

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
ustaxcourt/ef-cms-flexion#6631
