### ISSUE TITLE
BUG: Error received when navigating to Petitions Section Document QC

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7323]
**Describe the Bug**
when clicking Section Document QC, app is routing to an error page. 

**Business Impact/Reason for Severity**
Petition section will be unable to access the work they need to do.

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitionsclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Login as petitions clerk 
2. Click Document QC from main nav
3. Click Switch to Section Document QC

**Expected Behavior**
App routes to Section Document QC Inbox

**Actual Behavior**
App displays error

![Screen Shot 2020-10-05 at 9.29.12 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/49da591f-dc43-4100-8ac6-be1743f76f19)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
Getting a 400 error from endpoint https://api-blue.stg.ustc-case-mgmt.flexion.us/sections/petitions/document-qc/inbox : "The WorkItem entity was invalid..."
```
"The WorkItem entity was invalid. {\"docketNumber\":\"'docketNumber' is required\",\"section\":\"'section' is required\",\"sentBy\":\"'sentBy' is required\"}. {\"assigneeId\":\"<undefined>\",\"completedByUserId\":\"<undefined>\",\"sentByUserId\":\"<undefined>\",\"workItemId\":\"c77d6f38-4aab-4827-91a0-9409c237ba44\",\"docketNumber\":\"<undefined>\",\"section\":\"<undefined>\",\"sentBy\":\"<undefined>\"}"
```

**Comment by matthopson** [comment]
The issue was bad data - an incomplete work item. Tried reproducing via several paths by which work items are created and was unable to recreate the condition. The offending item has been removed from dynamo.
