### ISSUE TITLE
BUG: Case not showing in search results on petitioner name

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7324]
**Describe the Bug**
When searching by petitioner name, a case with matching name is not displaying in search results.

**Business Impact/Reason for Severity**
Accurate search results are needed or it will undermine user's confidence in the system.  It could also potentially impact workflows.  Internal users need to search for cases by petitioner's name.

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
privatePractitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Go to Advanced Search 
2. Search by petitioner name (Jessica Marine) 

**Expected Behavior**
All cases with matching petitioner name (that are not sealed) should display in search results. 

**Actual Behavior**
Docket 180-20 has matching petitioner name (confirmed in Dynamo) that is not displaying in search results. This case has a sealed address, but that shouldn't prevent it from being searchable. I tried to recreate by sealing the address for another case, but was unable to reproduce this. 

Saw again when searching Sebastian Heller - case 39470-95 did not display in search results. This looks like Sebastian Heller is in the case caption but not the primary contact. I thought we were search both places, and if not, should we? 

**Screenshots**
![Screen Shot 2020-10-05 at 12.20.51 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/96fdb8c4-cd27-43b6-bbe4-460ded07a1f8)

![Screen Shot 2020-10-05 at 12.20.59 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/25e8f081-49a5-440a-b334-2eacdb840b18)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
- Issue with 180-20 was bad data. The petitioner contact information had `international` country type with `United States` as the country, so searching within the United States would not return this petitioner.
- Issue with 39470-95 is related to the fact that we are not checking caseCaption on non-exact searches.

This also raises another potential issue:
We don't run the non-exact query if there are results from the exact matches query. So if we have a "Test Petitioner" in case A as the petitioner name, and then another case (B) with "Test Petitioner" in the case title, searching for "Test Petitioner" will only return case A and not case B, because it would see an exact match and not continue with non-exact matches. This _could_ be problematic if we intend to prioritize case caption results along with exact match results.

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6650 - adds caseCaption to non-exact search query
