### ISSUE TITLE
Non-associated practitioner should not see private data in API response (Jessica & Mike to QA)

### ISSUE THREAD

**Issue by rachaelparris** [ustaxcourt/ef-cms#7326]
** Jessica & Eric to pair **

**Describe the Bug**
A non-associated practitioner should not be able to see private data in the API response when retrieving a case.

**Business Impact/Reason for Severity**
The Court needs to be very careful about who accesses which information.

**In which environment did you see this bug?**
dev, stg

**Who were you logged in as?**
privatePractitioner1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
testing

**To Reproduce**
1. Login as a private practitioner
2. Navigate to the case detail page for a case the practitioner is not associated with
3. View the API response in the network tab in the browser - contact details are visible

**Expected Behavior**
Contact details should not be returned in the API response.

**Actual Behavior**
A clear and concise description of what actually happened.
Contact details were returned in the API response.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by ericsorenson** [comment]
Small tweaks: https://github.com/flexion/ef-cms/pull/6737

**Comment by ericsorenson** [comment]
Next steps:

- [x] Integration tests to verify that all users are only seeing fields they're allowed
- [x] When authenticated petitioners and practitioners view cases they're not associated with, they should receive the PublicCase
- [x] External users are receiving unfiltered Cases

**Comment by ericsorenson** [comment]
We're currently seeing a 403 error when viewing an unassociated case. @rachelschneiderman and I are making a test, and then working on a fix.
