### ISSUE TITLE
BUG: - Date waived and Payment date(on case info) - picking date in future does not throw error and logs user out of system

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7329]
**Describe the Bug**
As a docket clerk, if I go to the Edit Petition Details screen, select "Waived" or "Paid" for Filing Fee, and enter a date in the future for the Date Waived or Payment date, I get logged out of the system. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
training demo

**To Reproduce**
1. Go to case that has "Not Paid" for Filing Fee
2. Click Case Information 
3. Click "Edit" link on Petition Details 
4. Select Waived for Fee paid
5. Select date in the future for Date waived 
6. Click Save 

1. Go to case that has "Not Paid" for Filing Fee
2. Click Case Information 
3. Click "Edit" link on Petition Details 
4. Select Paid for Fee paid
5. Select date in the future for Payment Date
6. Click Save 

**Expected Behavior**
App should display error "Enter a valid date waived."
App should display error "Enter a valid payment date."

**Actual Behavior**
Was logged out of system 

![Screen Shot 2020-10-06 at 2.49.57 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/703df262-611e-4ddb-87dd-f81ae073bed5)Received this error: 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6728

We were not validating these dates on the front end, and were therefore allowing bad data to reach the case, which tripped validation on a docket entry.
