### ISSUE TITLE
BUG: Migrated practitioner email not updating correctly

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7331]
**Describe the Bug**
Per Mark: if I pass an email address with the practitioner object on a case, that email address shows up under petitioner counsel, not the email address already associated with the practitioner. So you end up with multiple email addresses for the same practitioner.
All migrated practitioner information (address, phone, email, etc.) should be check against the practitioner database and, if different, be changed to whatever is in the database. 

**Business Impact/Reason for Severity**
Cannot have mismatched data for a practitioner between database and what's showing on case.

**In which environment did you see this bug?**
local?

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
data migration - discovered in 5595

**To Reproduce**
1. Load practitioner object with email 
2. Verify email on Practitioner Database 
3. Verify email in Practitioner info on cases

Refer to Mark if any problems replicating. - see slack convo https://flexion.slack.com/archives/CD58Y6799/p1602017335094900?thread_ts=1602004571.091200&cid=CD58Y6799

**Expected Behavior**
All migrated practitioner database should check against the database and, if different, be changed to whatever is in the database. 

**Actual Behavior**
Practitioner email in DB may be different than practitioner email seen on cases. 

**Screenshots**
![Screen Shot 2020-10-07 at 9.04.05 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/96a37625-dc79-4a76-8f27-4e9591c6de89)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
Mark has reviewed this, it just needs to be deployed to staging and then can be closed.

**Comment by JessicaMarine** [comment]
Mark Meyer tested and confirmed it looked good to him -- Moving to Done 10.9.2020
