### ISSUE TITLE
BUG: Create Order from Message does not attach Order to message if Order title is edited during flow

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7336]
We may want to test all paths that can be taken from this flow and ensure they are working correctly. 

**Describe the Bug**
When creating an order from the message detail, if you edit the Order title during the flow, the Order is saved to the Drafts but does not automatically attach to the message itself. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
training demo

**To Reproduce**
1. Go to Message Detail 
2. Click Create Order from message 
3. Select order type and Continue
4. Click on Edit ORder title 
5. Update order type 
6. Save Order 
7.  Skip Signature or Save Signature 

**Expected Behavior**
App should route back to Message Detail with new order attached to message. 

**Actual Behavior**
App routes to Drafts screen and new order is displayed in Drafts list, but the Order is not attached to the original message. 

**Screenshots**
Recording - https://drive.google.com/file/d/1tyuttLefeEqwwJOGZGHQ8c3AhFsHbgFN/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
**Additional related issues**

- if you click Cancel on the Create Order screen (when initiating from message) - it currently routes to the Docket Record but should return back to the Message Detail

**Comment by matthopson** [comment]
When creating an order from a message, clicking Edit Title was losing the parentMessageId, so the redirect route was not properly bringing the user back to the message, and instead routing to document detail. This ensures parentMessageId gets set when that sequence gets called.

https://github.com/flexion/ef-cms/pull/6692
