### ISSUE TITLE
eFiling code tweaks

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7337]
* If you select a motion after selecting REDC-Redacted—the option for objection, no objection, unknown, needs to show up.
* When you select M115-Motion for Leave to File & M014-Motion for Leave to File Out of Time—and then select amended, amendment, supplement, supplemental, response, reply, objection, or no objection for document type--you need to be able to pick the additional document from the docket record you are filing that for.  It shows all the documents in the drop down but when you click on a document, nothing will go in the field. 
* EXH-Exhibit(s)—Since you can only select Attachment(s) and not Exhibit(s).  Should there be an event code created for Attachment(s) and get rid of exhibits so that there is consistency?  If not, need a drop down to select the document that the exhibit(s) go to.  Otherwise, the docket record just shows “Exhibit(s)”.  The entry should be Exhibit(s) to Stipulation of Facts.

**Comment by cholly75** [comment]
Already done.
