### ISSUE TITLE
BUG: - Assign from Section QC - checkbox not selecting on first click (or delayed visual feedback)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7343]
**Describe the Bug**
In the Section Document QC Inbox, when selecting the checkboxes, there is a delay before the app displays the checkbox as checked. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
training demo

**To Reproduce**
1. Go to Document QC 
2. Switch to Section Document QC 
3. Check a few of the checkboxes for documents 

**Expected Behavior**
Checkbox should display as checked (immediately) after selected. 

**Actual Behavior**
There is a significant delay between when user clicks the checkbox and when it displays as selected. 
https://drive.google.com/file/d/1L0-E9m4fEl6pYcvw3TBvJwOkQebUlyWV/view?usp=sharing

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
We might need to consider using https://github.com/bvaughn/react-virtualized or some other kind of paging mechanism.  Even with 100 rows rendered in the traditional manner, my high-end macbook pro takes almost half a second to render a reaction to the click events.

**Comment by klohman** [comment]
@JessicaMarine There has been improvement in the delay when checking items on the Section Document QC, but I would recommend adding a story to the backlog about redesigning this screen with pagination, and/ or using the react component @kkoskelin discovered (http://bvaughn.github.io/react-virtualized/#/components/List)
