### ISSUE TITLE
BUG: Phone Number displaying as "optional" but throwing validation error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7346]
**Describe the Bug**
On the Edit Petitioner screen, the phone number field has an optional label but throws a validation error if blank. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case 
2. Click Case Information 
3. Click Petitioner 
4. Click Edit on Petitioner Contact info 
5. Remove phone number 
6. Save 

**Expected Behavior**
Phone number field should not display as optional. 

**Actual Behavior**
Phone number field shows as optional in label, but is a required field. 

**Screenshots**
![Screen Shot 2020-10-08 at 2.56.03 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/847651ce-86ae-4a54-b8dd-9abd7a3a0a09)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The contact info is displayed as a part of a reusable component - therefore the optional label showed up in all instances of the component
PR - https://github.com/flexion/ef-cms/pull/6706
PR- https://github.com/flexion/ef-cms/pull/6809

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
@JessicaMarine We solved this with the understanding the phone number is a required field. I spoke to Eric about a separate bug and was told that phone number should be optional. Can you confirm if we need to change the phone number field to optional? And is this only for petitioners, or for practitioners?

**Comment by JessicaMarine** [comment]
@klohman I would prefer phone number to be required, rather than optional.  But, if we make it required, I think we have to instruct them to enter N/A or No Phone if they don't have one.

**Comment by klohman** [comment]
@mrinsin For the phone number field (across the app) can we add this helper text?

 ![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8458a7b0-69a6-427f-be23-610e958326ff)

**Comment by mrinsin** [comment]
Sounds good - should I make it a part of this issue or a new one?

**Comment by JessicaMarine** [comment]
@mrinsin Please do as part of this story.  I pulled this back to "In Progress"
