### ISSUE TITLE
BUG: Case Information Tab causing a Blank Screen for case 300-20

### ISSUE THREAD

**Issue by ericsorenson** [ustaxcourt/ef-cms#7348]
**Describe the Bug**
Case Information Tab causing a Blank Screen for case 300-20 on Flexion's staging environment.

**Business Impact/Reason for Severity**
Can't see the Case Information

**In which environment did you see this bug?**
Flexion's staging

**Who were you logged in as?**
Test docketclerk1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
A training session discovered it. We were notified with Honeybadger.

**To Reproduce**
1. Go to https://app.stg.ustc-case-mgmt.flexion.us/case-detail/300-20 
2. Click on Case Information
3. The page goes blank.

![Screen Shot 2020-10-09 at 10.42.15 AM.png](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/31eb93fe-71d2-403f-8bcb-90e9c69d5612)

https://app.honeybadger.io/projects/69162/faults/68561604

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Firefox
 - Version 81

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
@rachaelparris @ericsorenson Is there any way to test this now that staging has been cleared? Should we move to Closed?

**Comment by rachaelparris** [comment]
To recreate the scenario that caused this:

1. Create a trial session without a judge
2. Create a case 
3. Add the case to the trial session created in step 1
4. View the case detail case information tab - trial judge should say `Not assigned` rather than causing an error
