### ISSUE TITLE
Accessibility Issue w/ Date Picker

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7349]
From Kris Koskelin's accessibility review ustaxcourt/ef-cms#7072:

* Date-picker issue: https://trello.com/c/u08W0P2Y/829-date-picker-year-not-visible -- the year is not always visible in the date-picker, and it's quite dreadful on the public UI at the moment. Making the start and end dates full-width (one above the other) would solve both problems

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/0051730f-25eb-4fee-a27e-6fa6c477256e)

## Notes:
* Kristen had a good suggestion of making each date-picker field wider, the start and end dates each on their own line rather than side-by-side

## Tasak 
- [x} update form design on advanced document search [(6736](https://github.com/flexion/ef-cms/pull/6736)

**Comment by kkoskelin** [comment]
Tested on https://stg.ustc-case-mgmt.flexion.us/ in both Chrome and Safari with keyboard and also MacOS voiceover in desktop mode and mobile.  Looks and works great! 👍

**Comment by JessicaMarine** [comment]
Tested by Kris -- moving to Done 10.14.2020
