### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7350]
From Kris Koskelin's accessibility review ustaxcourt/ef-cms#7072 (October 9, 2020):

* Should search results REMAIN on the page when we go back, rather than disappearing? I feel they should stay unless we activate a new search.
* Should there be a “back to search results” button? (Combine with above question)
* Should the label for (Case) “Search by Name” say instead “Search by Petitioner” (because they use name, date, country and state?) As a VO user, it might be more descriptive to me explaining the kind of search form I'm using -- that it's not just searching the name.

**Comment by cholly75** [comment]
Accessibility folded into general workflow/development.
