### ISSUE TITLE
BUG: Missing edit link for system-generated documents

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7354]
**Describe the Bug**
The "Edit" link is missing on docket entries that are system-generated documents. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Go to case (Calendared) 
2. View Notice of Trial and Standing pretrial Order 

**Expected Behavior**
Docket entry for Notice of Trial and Standing pretrial Order should have "Edit" link 

**Actual Behavior**
System generated documents do not have "Edit" link on docket entry. 

**Screenshots**
![Screen Shot 2020-10-09 at 3.50.15 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2425ae98-7c96-4520-801c-232128df3075)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6748

When this feature was created, we explicitly disallowed system generated documents. I was unable to track down exactly why, as it seems we tasked it outside of GH, and I can't find them. Confirmed with @klohman and @JessicaMarine that these system generated documents (event codes: NODC, NTD, SPTN, and SPTO) SHOULD be editable.
