### ISSUE TITLE
BUG: Unable to serve SDEC from message

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7356]
**Describe the Bug**
Error received when serving SDEC document from message detail. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to message with un-served SDEC 
2. Click on SDEC attachment 
3. Click Serve 

**Expected Behavior**
Document should be served (service emails, docket entry updated, served stamp applied to document, etc.) and app should remain on message detail with SDEC no longer displaying "Not Served. " 

**Actual Behavior**
Error received. 

**Screenshots**
![Screen Shot 2020-10-12 at 11.22.20 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3aa6d4b1-3b18-4d58-9cfc-1862afd3979f)

Screen recording - https://drive.google.com/file/d/1v7rZORf-GtIk3jldgKPLegAV6cKfyFsJ/view?usp=drivesdk

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/6740

The sequence was passing `documentId` instead of `docketEntryId` - this was likely missed in a refactor.
