### ISSUE TITLE
BUG: Updated draft document displaying outdated document info on Add Docket Entry screen

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7365]
**Describe the Bug**
When adding a Notice, then updating the document type (title) to Order or Decision, then clicking Add Docket Entry, the populated document type and docket entry preview still display the Notice information. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to case 
2. Click Create - Order/ Notice 
3. Select Notice 
4. Save 
5. Click Edit 
6. Click Edit title and update to Order or Decision doc type 
7. Save 
8. Skip or save signature 
9. Click Add Docket Entry 

**Expected Behavior**
For Orders and Decisions without signature, Add Docket Entry link should not even display (logged as [6747](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/6747)

For Orders and Decisions with signature, when clicking on Add Docket Entry - screen should display the current document type. 

**Actual Behavior**
Notice information is still displaying on Add Docket Entry screen.

**Screenshots**
Recording: https://drive.google.com/file/d/1_qma8iQTUkhBJFKnBrjV4-AbRhKzr1Ui/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
This should be resolved by the solution for ustaxcourt/ef-cms#7364
