### ISSUE TITLE
BUG: View PDF on Mobile is not clickable (petitioner)

### ISSUE THREAD

**Issue by kimschulke** [ustaxcourt/ef-cms#7366]
**Describe the Bug**
As a petitioner, after filing a document on mobile, I was not able to view PDF from docket record. When I click document link, it routes to "document details" page (as expected). It shows "view PDF" but when I click on it, nothing happens.

**Business Impact/Reason for Severity**
We've said the system is mobile-friendly for external parties.  Not being able to access PDFs is inconsistent with that messaging.

**In which environment did you see this bug?**
staging on mobile

**Who were you logged in as?**
Petitioner 
flexionustc+petitioner@gmail.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing on mobile 

**To Reproduce**
1. Go to docket record
2. Click on document link
3. Scroll down to View PDF on document detail page

**Expected Behavior**
View PDF should be clickable and should open the document and/or download the document to phone.

**Actual Behavior**
View PDF appears but is not clickable

**Screenshots**
![IMG-2381.JPG](https://images.zenhubusercontent.com/5f34386b28244c7b7db90198/c70030bc-28d1-4d96-82b4-595e40b9de13)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS?
 - Browser Safari
 - Version: software version 12.3.1

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by sutt0n** [comment]
I believe this is pop-up blocker related. @kimschulke / @klohman, could y'all try to replicate this but disable your popup blocker in the Safari settings on mobile? `Settings > search for "Safari" > Pop-ups`

**Comment by kimschulke** [comment]
Re-tested after following suggestion on pop-up blocker and it worked.

**Comment by klohman** [comment]
@sutt0n This is working but there are still some concerns / questions. It seems like some of the other links are just opening the PDF in another tab but in this instance, the popup blocker had to be disabled. I'm not experiencing this on. my device, but am curious what the difference is on the backend on how these links are treated and if we can better streamline it. @kimschulke Can you provide more details?
