### ISSUE TITLE
(NEEDED FOR FINAL) BUG: Document info not populated on Edit Docket Entry screen

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7371]
**Describe the Bug**
When clicking the Edit link on a system-generated document, the document information (document type, other fields concatenating the document title) are not populated on the form. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
testing bug (6713)

**To Reproduce**
1. Go to case 
2. Click Edit link on system-generated document 

**Expected Behavior**
Document type (and other fields) should populate based on the document information. 

**Actual Behavior**
Document type is blank for Standing Pre-Trial Order and Notice of Docekt Change. Document type is populated for Notice of Trial but missing date and location. 

**Screenshots**
![Screen Shot 2020-10-14 at 12.23.57 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/640d8f9e-fa3b-4d12-ac86-70419ceda1be)![Screen Shot 2020-10-14 at 12.23.45 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2ee070ef-d2c7-4fb4-b942-e73c8b20fb09)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Docket Entry for autogenerated notices did not add trialLocation and Date
PR - ustaxcourt/ef-cms-flexion#7109
PR- ustaxcourt/ef-cms-flexion#7115
PR - ustaxcourt/ef-cms-flexion#7121

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mariahkannenberg** [comment]
@mrinsin 

SPTO maps to Standing Pretrial Order in the document event codes for Court-generated documents

SPOS maps to Standing Pretrial Order for Small Case in the document event codes for Court-generated documents

**Comment by rachelschneiderman** [comment]
The final updates for the migration successfully ran on `dev` just now. The last fix for the migration script is the only item for this bug that did not make it into the 53.2 Sprint PR. Since @mmarcotte mentioned the migration won't be running on their environment I'm not sure it's necessary to pull in that change, but wanted to make that fact visible!
