### ISSUE TITLE
BUG:Cover sheet is not being added to eFiled documents

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7375]
**Describe the Bug**
When petitioner efiles a document, the coversheet is not being added. 

when adding a paper-filing to a case, the coversheet seems to be working as expected. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitioner - flexionustc+petitioner@gmail.com
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Login as petitioner 
2. Click into case 
3. File a document 
4. Click document link from docket record 

**Expected Behavior**
A coversheet should be applied to all eFiled documents when they are submitted. 

**Actual Behavior**
A coversheet is not generated. 

**Screenshots**

![Screen Shot 2020-10-14 at 3.34.51 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7539fea3-0664-45a0-b140-3fd51a6acb37)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
Unable to reproduce on any environment. Closing for now.
