### ISSUE TITLE
BUG: (Mobilie) - Filings and proceedings columns not left aligned

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7377]
**Describe the Bug**
Filings and proceedings column is center aligned on mobile. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitioner 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
mobile testing 

**To Reproduce**
1. Go to Docket Record 

**Expected Behavior**
Docket record columns should be left-aligned. 

**Actual Behavior**
Filings and proceedings is center-aligned. 

**Screenshots**
![Screenshot_20201014-151230.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fe1c0369-6771-4a7d-bfbc-3037b966a3d5)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - Google Pixel 3
 - OS: [e.g. iOS8.1] Android 10 
 - Browser [e.g. stock browser, safari]- Chrome 
 - Version [e.g. 22] 86

**Cause of Bug, If Known**
The filings and proceedings column contains buttons - button text by default is centered!

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
@klohman We tried locally and on dev and were not able to reproduce. It may be that a related bug fixed resolved this issue as well, let me know if you see it though!

![image.png](https://images.zenhubusercontent.com/5e331dde16551cf7ef3a8f50/c6b4fa4f-987f-4cb7-bc99-7a664f17a58a)

**Comment by klohman** [comment]
@rachelschneiderman 

Checked on my Android device - still seeing it on flexion prod 

![Screenshot_20201117-180350](https://user-images.githubusercontent.com/18366192/99461306-94041880-28ff-11eb-8631-d1a9ae7b77d3.png)
