### ISSUE TITLE
BUG: Docket number and case title is missing from Opinion/Order search results

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7382]
**Describe the Bug**
Docket number and case title columns are blank on Opinion and Order search results. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
training demo 

**To Reproduce**
1. Go to Advanced search 
2. Click opinions 
3. Search for opinion

(Same for Orders)

**Expected Behavior**
All columns in table are populated correctly. 

**Actual Behavior**
Docket number and case title columns are blank on Opinion and Order search results. This is populated for some cases, but not all.

**Screenshots**

![Screen Shot 2020-10-16 at 3.33.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5d7ae998-1d27-48b7-83a6-f1e25239e922)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
After extensive debugging, we discovered the problem was caused by incomplete re-indexing of the `efcms-docket-entry` index in the staging elasticsearch instance. We decided as a mob to wait for [this](https://github.com/flexion/ef-cms/pull/6866) PR to be merged before continuing to work on this bug as we believe it may solve the underlying problem (elasticsearch indices being re-indexed out of order).

**Comment by rachelschneiderman** [comment]
Unable to reproduce after [a fix](https://github.com/flexion/ef-cms/pull/6866) was introduced to use parent/child indexing for docket entries (related to [#6654](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/6654)). Closing.
