### ISSUE TITLE
BUG: Order Search Results: title misaligned

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7383]
**Describe the Bug**
Order search results with long titles are center-aligned, and the table is displaying outside of the visible area. 

May be related to the the use of a <button> for the order title text - need to update this anywhere else it appears

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
training demo

**To Reproduce**
1. Go to Advanced search 
2. Click order 
3. search for orders

**Expected Behavior**
Table columns should be left aligned, and table width should not expand past the max-width. 

**Actual Behavior**
Title is center aligned. Table is outside of visible window on right side. 
'
**Screenshots**

![Screen Shot 2020-10-16 at 3.40.02 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/80d04c8e-44a2-49a4-b958-0c3535f52b19)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Document title in the search results is embedded in a button element which has some default styling which included centering the text. We added a custom style to left align the text instead for buttons in advanced document search result.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
To clarify regarding expected behavior... this occurred because the string was unusually long without spaces.  
If this occurs, do you want the title simply cut off?  Should it overflow into next cell?  Should the table cell scroll horizontally? Should the title be forced to wrap even if it breaks arbitrarily in the middle of a word?

**Comment by klohman** [comment]
@kkoskelin Ah I see. In that case, maybe this isn't something we specifically need to solve since there is no use case when there would be such a long string without spaces. We do need to fix the alignment issue (which I saw happening with and without spaces for long titles).
