### ISSUE TITLE
BUG: Logged out of system during Order search

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7384]
**Describe the Bug**
When searching for an order by keyword "Order", system logs out. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 2

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Advanced Search 
2. Click Order 
3. Enter "order" as keyword and Search 

**Expected Behavior**
App should display search results. 

**Actual Behavior**
System logs out . 

**Screenshots**
https://drive.google.com/file/d/180attjRuGqJJm5AAX85GMMtMEZljyErm/view?usp=sharing

![Screen Shot 2020-10-16 at 3.47.22 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d55e0eef-534d-4d03-8d30-fafc61282a3c)

Recurred on October 19: 
https://drive.google.com/file/d/1KOGc0f5NrOTIqcx9NtGeFiNPwU5bMscW/view?usp=sharing
![Screen Shot 2020-10-19 at 12.01.50 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0d7cf1e1-6a86-4d11-aa3e-9e7c8f621ebc)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman I believe that this particular bug has been resolved by multiple means:
* @sutt0n put in a fix such that if the api returned a 400 status that the application would catch it and display a 400 error in the app itself.
* I wrote some recent code that limits the number of results returned from an elasticsearch query -- the absence of which was the cause of the original http 400 code.
