### ISSUE TITLE
BUG: (Mobile) Printable Docket Record - for Public- not displaying PDF

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7385]
**Describe the Bug**
For public users, the printable docket record is not displaying in PDF preview. 

This is also happening on the Print Confirmation screen. It may be related to the iframe on mobile? 

**Business Impact/Reason for Severity**
Anything public-facing is high priority for political purposes.

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
public

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to public search 
2. Search for a case 
3. Click Printable Docket Record 

**Expected Behavior**
Printable Docket Record PDF displays in PDF preview. 

**Actual Behavior**
PDF preview displays error. 

**Screenshots**
![Screenshot_20201019-094833.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a130781e-f479-4e8c-94ae-67fc8e5dea79)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - Pixel 3
 - OS: [e.g. iOS8.1] - Android
 - Browser [e.g. stock browser, safari] - Chrome

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
Initial analysis on Samsung Galaxy S9 with remote debugger on MacOS:
![Screen Shot 2020-10-20 at 11 18 20 AM](https://user-images.githubusercontent.com/2445917/96614672-02849500-12c6-11eb-86fe-88f8505b1ca9.png)

Debugger step-through indicates that it should be attempting to use url `https://app.stg.ustc-case-mgmt.flexion.us/temp-documents/c0eae9b4-afa0-401d-8f3c-938688adb7f5?AWSAccessKeyId=....`

**Comment by kkoskelin** [comment]
To test and develop locally against the CSP and my chrome android instance, I created a tiny express app with a content-security policy.  First, a tiny page with a PDF in an iframe which seems like it SHOULD have loaded (according to security policy), but did not:
![Screen Shot 2020-10-20 at 12 13 02 PM](https://user-images.githubusercontent.com/2445917/96621469-4380a780-12ce-11eb-9bef-5c71cddb50c8.png)

Then, the exact same iframe but with a content-security policy which also included the `data:` protocol:
![Screen Shot 2020-10-20 at 12 16 50 PM](https://user-images.githubusercontent.com/2445917/96621478-467b9800-12ce-11eb-80da-cf1e3dde4656.png)

**Comment by klohman** [comment]
Closing with suggestion for new item in backlog: 

Printable Docket Record is being treated differently on desktop and mobile for internal/external users vs. public users. Discrepency is in DocketRecordHeader.jsx . 

@JessicaMarine I noted in [#4010](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/4010) that there are inconsistencies in how PDFs are displayed across the app on desktop and mobile, and it's probably worth looking at these comprehensively and then implementing a solution that can meet all needs and remain consistent (if possible).
