### ISSUE TITLE
BUG: Petition PDF displaying error on PDF preview / STIN not displaying / Case search triggering error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7388]
**Describe the Bug**
I started new e-filed case as petitioner3@example.com, and several unexpected things are happening with this case (151-20) 
- the Petition is displaying an error in the PDF preview on Petition QC screen 
- the STIN is not displaying a PDF at all on the Petition QC screen 
- when searching for the case as an internal user, the app logs out with error

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitioner3
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
I was unable to reproduce this again, but these were the steps I followed when this case was created. 

1. Login as petitioner 
2. eFile case (petitioner + spouse)
3. Login as petitions clerk 
4. Click petition link from Document QC Inbox 

**Expected Behavior**
- the Petition displays in PDF preview on QC screen 
- the STIN displays in PDF preview on QC screen 
- when searching for the case as an internal user, the app routes to case detail 

**Actual Behavior**
- the Petition is displaying an error in the PDF preview on Petition QC screen 
- the STIN is not displaying a PDF at all on the Petition QC screen 
- when searching for the case as an internal user, the app logs out with error

**Screenshots**
![Screen Shot 2020-10-19 at 1.01.02 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f3d7c7b4-a329-4d8f-b087-5833ff5f1734)
![Screen Shot 2020-10-19 at 1.05.24 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0fac9e7d-46fb-4223-bd9d-e923ff56eca9)

![Screen Shot 2020-10-19 at 1.22.13 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b58d0beb-f213-4d48-89db-104a7561b050)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
I believe what happened here is that Mark migrated data into Flexion's staging that contained some cases from 2020. Updating our docket number counter for new cases is a manual process that was _not_ completed on staging, so the case you created was created with a docket number that was the same as one of the migrated cases. That caused some expected documents not to be found (because the documents were not migrated) and caused the errors you saw. I think the solution here is that next time a migration is run on one of our environments, we need to manually update the docket number counter.
