### ISSUE TITLE
Performance Tuning: getAllCatalogCases

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7394]
As the Court, we need to ensure that all cases eligible to have their status changed to “General Docket -- At Issue (Ready for Trial)" are getting their status changed.

## Acceptance Criteria:
* All cases eligible to have their status changed to `General Docket -- At Issue (Ready for Trial)` have their status changed
   * Cases in `General Docket -- Not at Issue` that have had any type of answer filed plus 45 days

## Notes:
* Potential Solutions: 
   * Only look for cases with a case status of `General Docket -- Not at Issue` 
   * Put all cases in queue
* 1MB limit being hit on DynamoDB when cases are being returned

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by rachelschneiderman** [comment]
PR: ustaxcourt/ef-cms-flexion#7003
