### ISSUE TITLE
Performance Tuning: getDocumentQc

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7396]
As the Court, in order to make sure that high priority items are not missed, we need high priority items to return first in any QC list.

## Acceptance Criteria:
* In the Production Environment, all high-priority items MUST be returned and show at the top of Docket's QC box

## Notes:
* getDocumentQc*For* gets work items for user/section
* not sorted by priority, so higher priority work items could not be returned
* Appears to max out around 600-700

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by rachaelparris** [comment]
Refactoring item related to this: https://trello.com/c/r01KJvkS/845-store-fewer-work-item-mappings-in-dynamo-and-use-elasticsearch-instead
