### ISSUE TITLE
Performance Tuning: getCaseByDocketNumber

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7397]
As the Court, in order to make sure that we see a complete case, we need to make sure the entire case can return.

## Acceptance Criteria:
* Stress test with larger case record(s)
* User can access entire case record [Do we need to list all items?]

## Notes:
* getCaseByDocketNumber retrieves values for a single case:
   * docket entries, practitioners, correspondences - could reach the 1M limit
* updateCase, setPriorityOnAllWorkItems, getMessagesByDocketNumber
* retrieve work items/messages for a single case
* we don’t ever delete these things, so they could build up over time and we do not filter out “inactive” work items or messages when retrieving
* "last key" check from DynamoDB for pagination (if applicable)

Case Size (statistics) provided by Mark:
The largest cases in terms of combined docket record PDF size are:

31183-15 (sealed): Over 700 docket-record entries many between 500 - 900 pages. Total size 49GB.
12131-18 (sealed): 300+ docket-records with many 500+ page PDFs. Total size 21.7GB
017431-17: 160 docket-records. Several of the PDFs are 1000+ pages, however not all are currently migrating. Total size 20GB.
26965-09: 295 docket-record entries. Similar to above. 91.8 GB
Large single documents. The truly gigantic PDFs have not migrated and Mike McVicker is still working on getting these to AWS.
Case 28210-15 provides one of the largest migrated PDFs in a non-sealed case. Docket index No. 29 is 800MB and 2749 pages long.

In terms of length, the winners for the longest docket records go to:

005576-12: 827 docket entries
029643-86: 808 docket entries
009382-83: 774 docket entries
040159-84: 769 docket entries
015907-84: 750 docket entries
031197-12: 519 docket entries

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the **prod** environment

**Comment by cholly75** [comment]
Done.
