### ISSUE TITLE
Load Test in Prod: getCaseInventoryReport

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7398]
As the Court, in order to make sure elasticsearch is not improperly limiting what returns for getCaseInventoryReport, we need to reconsider how getCaseInventoryReport is being returned.

## Acceptance Criteria:
* In the Production Environment w/Golden Data Set, ensure that all cases are returning on Case Inventory report depending on Judge and/or Case Status selection and doesn't time out - both in the UI and in the printable report
* System does not need to return closed cases
* Max numbers:
   * For all judges other than Chief Judge, the max number would be no more than 1,000 cases
   * The Chief Judge, he/she could have upwards of 15,000 b/c all cases not with another judge default to the chief judge

##  Notes:
* We believe this should be working, so this is a testing story. However, if there's something we need to fix, we'll do it in this story. 
* elasticsearch queries (all have a size limit of 5000 set)
* getCaseInventoryReport (uses paging already on the API side)
* Printable PDF for Chief Judge's inventory has been backlogged for post-MVP (#6939)

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by codyseibert** [comment]
@JessicaMarine some questions:

- should we remove the "closed cases" from the status drop down on this page since AC states "System does not need to return closed cases"? YES
- does this story also involve the "printable report" PDF as well?  The PDF is also limited to 5000 records which would mean the PDF is missing entries for "chief judge". YES; if we can, bump up to 15,000

Notes for myself:
- we will need to increase the `max_result_window` index setting to at least 20,000 so that the counts for chief judge come back accurate. Right now it is the default of 10,000, so if the chief judge has 15,000 cases, 5,000 will be missing from the total count.
