### ISSUE TITLE
Post-MVP Performance Tuning

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7402]
Confirm that no additional performance tuning is needed for:

* getElasticsearchReindexRecords
   * retrieves records that failed initial indexing via elasticsearch
   * these are deleted after they are eventually indexed, so even if we hit a limit here, the count will eventually go down
* getEligibleCasesForTrialSession
   * gets eligible case list for a trial session
   * has a limit in place (max cases on a trial session), and sorts by priority in returned results
* getEligibleCasesForTrialCity
   * gets counts for trial session planning report
   * the records are very small, so we should not hit a limit
   * Per Rachael these are based on a per-city count; no city would have over 5,000 at one time
* getBlockedCases
   * Only returning blocked cases for that selected place of trial. 
   * There should never be more than 5k per city.

**Comment by cholly75** [comment]
@mmarcotte @jimlerza - is this story still relevant?
