### ISSUE TITLE
BUG: (Mobile) - No response when clicking on document link from order or opinion search

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7406]
**Describe the Bug**
When clicking on document link from Opinion search results, nothing happens. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg 

**Who were you logged in as?**
public 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to public search 
2. Click Opinion tab
3. Search for opinion
4. Click document link from search results 

_Repeat for Order search_ 

**Expected Behavior**
Selected document PDF should open in new tab.

**Actual Behavior**
No response from app. 

**Screenshots**
https://drive.google.com/file/d/15Pvbedgr8qTj--xIa04Mc299UuH3sQFY/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - iPhone 8 (XCode simulator 
 - Version [e.g. 22]- 14 

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by ericsorenson** [comment]
@klohman on Safari for iOS, popups are blocked by default. They need to be enabled in the Safari control panel: ![file.jpg](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/d1f56338-0acc-4351-8fcf-99037e0fe150)

**Comment by klohman** [comment]
@ericsorenson For MVP (confirmed with Jessica), we want PDF links on mobile to open in current tab (instead of a new tab). We'll revisit later when we handle mobile redesign/optimizations.
