### ISSUE TITLE
BUG: Order search - judge filter not working correctly

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7407]
**Describe the Bug**
When filtering order search by judge, the selected judge is not always matching the search results. 

**Business Impact/Reason for Severity**
Public-facing aspects must work correctly

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
public 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Advanced Search
2. Click Order tab 
3. enter keyword and search 
4. Select judge = Buch

**Expected Behavior**
Only orders associated with judge Buch should display in search results. 

**Actual Behavior**
When filtering by Buch, orders associated with Judge Marvel are displaying. When filtering by Foley, orders associated by both Foley and Thornton are displaying. 

**Screenshots**
![Screen Shot 2020-10-20 at 11.50.25 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a1b784a0-8c90-4fe7-8331-80b65206b849)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
So far it appears that this relates to the way we are searching for judges' names.  Some names in the judge drop down have a "full name" which includes a middle initial.

A search for Foley (full name: "Maurice B. Foley") will return items also belonging to Thornton (full name: "Michael B. Thornton").  And the converse is true.

EDIT:  This is because our elasticsearch queries are truly querying fields as completely-indexed strings, and NOT searching according to a "perfect match" scheme.  Working on a fix, but this phenomenon may arise elsewhere.
