### ISSUE TITLE
BUG: Case Information tab does not appear for Petitioner

### ISSUE THREAD

**Issue by kimschulke** [ustaxcourt/ef-cms#7408]
**Describe the Bug**
Under Open Cases on Petitioner dashboard (flexionustc+petitioner@gmail.com), Case Information tab does not appear after clicking on docket record.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
flexionustc+petitioner@gmail.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Editing contact info for petitioner 

**To Reproduce**
1. Log into flexionustc+petitioner@gmail.com account
2. Click on an open case
3. View Docket Record
4. See error (no Case Information Tab)

**Expected Behavior**
I expected to see the Case Information Tab after clicking on docket record

**Actual Behavior**
A clear and concise description of what actually happened.
Docket record appears but, there is no tab for Case Info

**Screenshots**
![Screen Shot 2020-10-20 at 1.06.15 PM.png](https://images.zenhubusercontent.com/5f34386b28244c7b7db90198/b4548f6f-3a2e-486b-93f4-6a30d9f11ac3)

**Desktop (please complete the following information):**
 - MacOS Catilina 10.15.4
 - Chrome
 - Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@kimschulke was this on stg or dev or...?

**Comment by kimschulke** [comment]
@kkoskelin - this was in staging.

**Comment by matthopson** [comment]
@kimschulke 
I suspect this was an issue with updating the contact info breaking the case association for this user:

https://app.honeybadger.io/projects/69162/faults/68987499/1ff397c6-131b-11eb-874b-9d7c174c3a0d?q=occurred.before%3A%222020-10-21+0%3A00+UTC-7%22+occurred.after%3A%222020-10-20+0%3A00+UTC-7%22

Currently this case is unavailable on stg (data has been wiped, I think), but in other environments, I can't reproduce this. I think we need to close this until we see it show up again.

**Comment by kimschulke** [comment]
@matthopson - I think we can close this out. 

I know we are no longer using the "flexionustc+petitioner@gmail.com" account and the Case Info correctly shows up when signed in as "petitioner1@example.com"
