### ISSUE TITLE
BUG: Practitioner: Newly associated cases not displaying on dashboard case list

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7409]
**Describe the Bug**
After requesting access and being associated with a case, the new case is still not showing on the dashboard. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
flexionustc+privatepractitioner10@gmail.com
flexionustc+irspractitioner10@gmail.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to case (not associated with)
2. File a document (Entry of Appearance (for private) or Answer (for IRS)
3. VIew Open cases on dashboard 

**Expected Behavior**
New case should display on dashboard within a few minutes.  

**Actual Behavior**
New case is not displaying on dashboard (after 20 + minutes). 

Related to this bug: https://trello.com/c/W8bNAxoe/785-new-cases-not-displaying-on-practitioner-dashboard-case-list

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
I created a new case as flexionustc+petitioner and then served it as petitions clerk.  Afterward, I logged in as a private practitioner, filed an answer, and saw the case show on my "Open Cases" dashboard.  If I've missed something, let me know.  This might be another item fixed by the recent Elasticsearch work.

**Comment by klohman** [comment]
Closing - cannot reproduce 11/04
