### ISSUE TITLE
BUG: Case API returns validation error when attempting to retrieve an unknown case.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#7411]
.**Describe the Bug**

Requesting a case docket number which does not exist results in a validation error being returned and a `400` response code.

**Business Impact/Reason for Severity**

- This causes the UI to show a **We’re experiencing technical problems** error if an unknown docket number is retrieved.
- The API error is complicating/confusing to the IRS, as `The Case entity was invalid.` isn’t a particularly helpful error message.

**In which environment did you see this bug?**

https://stg.ef-cms.ustaxcourt.gov

**Who were you logged in as?**

clerkofcourt1@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Writing tests for the API endpoints under development for the IRS.

**To Reproduce**
1. Go to https://stg.ef-cms.ustaxcourt.gov
2. Login as any user
3. Attempt to a docket number which does not exist.
4. See error.

**Expected Behavior**

- The UI error shows a "case not found" message.
- The API returns a status code 404 and a not found message.

**Actual Behavior**

API returns: 

```json
"The Case entity was invalid. {\"caseCaption\":\"'caseCaption' is required\",\"caseType\":\"'caseType' is required\",\"docketNumber\":\"'docketNumber' is required\",\"partyType\":\"'partyType' is required\",\"procedureType\":\"'procedureType' is required\",\"sortableDocketNumber\":\"'sortableDocketNumber' is required\",\"userId\":\"'userId' is required\"}. {\"userId\":\"<undefined>\",\"judgeUserId\":\"<undefined>\",\"trialSessionId\":\"<undefined>\",\"caseCaption\":\"<undefined>\",\"caseType\":\"<undefined>\",\"partyType\":\"<undefined>\",\"procedureType\":\"<undefined>\",\"sortableDocketNumber\":\"<undefined>\"}"
```

**Screenshots**

![Screenshot of error page](https://user-images.githubusercontent.com/14930/96628484-48e6ed80-12e0-11eb-86d3-e1a3c91fe7aa.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Version: 86.0.4240.75 (Official Build) (x86_64)

**Cause of Bug, If Known**

- a2285afde8c1dccb9fdf0dede17260bc1fb90a7f introduced in https://github.com/flexion/ef-cms/pull/6020 — caused a behavior change where `getCaseByDocketNumber` returns a blank case object instead of `null`, causing existing 404 checks to miss.

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by adunkman** [comment]
I’m not able to label, but I would apply a Low or Medium severity to this bug. There is a workaround (contacting support or recognizing that the error message is incorrect).

**Comment by kkoskelin** [comment]
Note: this issue is also why we were seeing the following logs in Honeybadger:

> Error detected in: ef-cms dev (api)
> Full report at https://app.honeybadger.io/projects/69132/faults/69019452
> 
> Cannot read property 'contactId' of undefined

**Comment by kkoskelin** [comment]
@adunkman Please review; I believe this to be addressed.

**Comment by adunkman** [comment]
Looks great! Fixed in https://github.com/flexion/ef-cms/pull/6877, in PR to Court https://github.com/ustaxcourt/ef-cms/pull/499.
