### ISSUE TITLE
BUG: Document Download URL endpoint returns known bad URLs. (Review w/Andrew)

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#7412]
**Describe the Bug**

When a case or its docket entry isn’t found, the document download url endpoint returns a signed URL anyway.

**Business Impact/Reason for Severity**

- **Can result in retrieving sensitive documents to unauthorized users** if the docket entry ID is known — request a document download url for an invalid case number but the same docket entry ID, and a signed URL will be retrieved granting the user access to that document. 

- API consumers like the IRS requesting documents for docket entries which do not have documents are given a URL which is known not to work.

**In which environment did you see this bug?**

https://stg.ef-cms.ustaxcourt.gov

**Who were you logged in as?**

clerkofcourt1@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Writing tests for the API endpoints under development for the IRS.

**To Reproduce**
1. Go to https://stg.ef-cms.ustaxcourt.gov
2. Login as any user
3. Open the web inspector and copy the authentication header.
4. Make a request for a document download url, specifying any number as a docket number and any GUID as a docket entry id.
5. A signed document download URL is returned.

```bash
curl -H "Authorization: Bearer [token omitted]" -v https://api-blue.stg.ef-cms.ustaxcourt.gov/case-documents/999-99/99999999-8888-7777-6666-555555555555/document-download-url
```

**Expected Behavior**

I expected the endpoint to return a 404 if the docket number is not found, and a 404 if the docket entry ID was not found, and a 404 if the docket entry does not have a document attached. 

**Actual Behavior**

A signed document download URL is returned for any input.

**Cause of Bug, If Known**

- a2285af introduced in ustaxcourt/ef-cms-flexion#6020 causes the endpoint to succeed rather than throwing a validation error
- Endpoint already filters to case and docket entry to check for permissions, but does not reject the request if the case or docket entry are not found.

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by adunkman** [comment]
I cannot label this issue, but I would assign it as a High severity as it allows sensitive documents to be retrieved by unauthorized users.

**Comment by rachaelparris** [comment]
PR for this fix is here:
https://github.com/flexion/ef-cms/pull/6879

**Comment by adunkman** [comment]
Looks great — thanks for the fix! In sprint PR https://github.com/ustaxcourt/ef-cms/pull/499.

![Human dressed in a Koala suit dancing](https://media.giphy.com/media/tIR7TiaIaXih2AGStY/giphy.gif)
