### ISSUE TITLE
BUG: eFiled case - Has docket entries from another case

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7413]
**Describe the Bug**
As a petitioner, I eFiled a case and when I served it, the docket record displayed several entries that are not from this case. Also, the petition is not displaying as Served.  

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
petitioner1
petitionsclerk1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. login as petitioner 
2. e-file a case 
3. Login as petitions clerk
4. Serve case

**Expected Behavior**
Only documents associated with this case should be on the docket record. 

**Actual Behavior**
Docket record contains entries that are not part of this case. 

**Screenshots**

https://drive.google.com/file/d/1mT2_AGMgdmh786S-PaesKovweBqDoNjV/view?usp=sharing

![Screen Shot 2020-10-21 at 9.35.20 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/11a8996a-5602-4dfe-8290-d18ddfd60af8)

![Screen Shot 2020-10-21 at 9.35.32 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5ab1700e-7739-4ae8-a6e9-276a8334143c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
Possibly data-pollution from a migration load testing?  The data really IS in dynamodb.

![Screen Shot 2020-10-23 at 1 51 17 PM](https://user-images.githubusercontent.com/2445917/97042608-ecc9d680-1536-11eb-8363-96a44871f0c9.png)

**Comment by kkoskelin** [comment]
![Screen Shot 2020-10-26 at 11 03 09 AM](https://user-images.githubusercontent.com/2445917/97196781-df049300-177a-11eb-97d9-a048505d1ca0.png)
When I disable the new code which checks for duplicate docket numbers and set the docketNumberCounter back to a duplicate value (as 127-20 already existed, and I set counter from 27 to 26), this is the result (above).

**Comment by kkoskelin** [comment]
Although my confidence isn't 100%-perfect, I strongly suspect that this was a result of data *already* being in the database for this docket number as a result of running a migration or migration test.

The procedure we must follow should be as follows:
As a migration is about to begin, we may want to consider preventing creation of cases by petitioners or petitions clerks via the web interface?
As the migration occurs, the tax court will monitor the migrated case data to identify the "highest" docket number migrated for the current year.  

Suppose the highest docket number has been identified as "2673-20".  We will subtract 100 from the first number (2673 - 100 = 2573).  And the second portion will be converted to a four-digit year, so 20 -> 2020.  These will be used to create a new value to be manually updated in dynamoDb.
```
{
  pk: "docketNumberCounter-2020",
  sk: "docketNumberCounter-2020",
  value: 2573
}
```

This change will ensure that the next docket number created uses 100 + (2573 + 1) --> "2674-20"

Then the web interface should be verified for functionality and smoke tests.
