### ISSUE TITLE
BUG: Removed deadline still blocking case from trial

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7414]
**Describe the Bug**
When removing a deadline on a migrated case, the case is still blocked from trial with reason "Due date"

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
stg

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to migrated case with deadline 
2. Remove deadline 

**Expected Behavior**
Due date should not block case from trial once removed. 

**Actual Behavior**
Deadline is not showing under Tracked Items, but the case remains blocked and displays blocked reason "Due Date" 

**Screenshots**
![Screen Shot 2020-10-21 at 10.12.20 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6e7287cd-8b37-4ee8-9d72-979518a8bca2)

![Screen Shot 2020-10-21 at 10.12.28 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/66c089d7-a57e-4530-868f-b9fbaf07334f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by ericsorenson** [comment]
![image.png](https://images.zenhubusercontent.com/583eff35b9dc3c622022bdff/1f21a86a-5bff-4954-af6e-f8a7cf364d43)

A `Case.preferredTrialCity` value is required to create trial sort tags, and it is not required by validation rules. Migrated cases sometimes don't have it defined.

Perhaps we can require `preferredTrialCity` for cases with some status values?

**Comment by mariahkannenberg** [comment]
Also check other areas where we call this code - may need to be updated. 

Per @rachaelparris, we just need to check for trial city before we call createCaseTrialSortMappingRecords
