### ISSUE TITLE
BUG: API endpoint unknown to IRS.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#7416]
**Describe the Bug**

There is no single API endpoint which the IRS can access. 

**Business Impact/Reason for Severity**

The IRS needs to be able to retrieve documents in response to service emails. WIthout an API endpoint, they cannot retrieve temporary signed URLs needed to download those documents. 

**In which environment did you see this bug?**

https://stg.ef-cms.ustaxcourt.gov/

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Preparing a release to the IRS environment. 

**To Reproduce**
1. Go to https://stg.ef-cms.ustaxcourt.gov/
2. Login as any user
3. Observe there is no single API endpoint — there are two used, either `api-blue.stg.ef-cms.ustaxcourt.gov` or `api-green.stg.ef-cms.ustaxcourt.gov`.

**Expected Behavior**

I expected the API to be accessible at https://api.stg.ef-cms.ustaxcourt.gov/

(Note: we have since [manually patched this environment](https://ustaxcourt.slack.com/archives/C015SEE9CUU/p1603212065106800) in a temporary workaround).

**Actual Behavior**

There are two API endpoints used, either `api-blue.stg.ef-cms.ustaxcourt.gov` or `api-green.stg.ef-cms.ustaxcourt.gov`. The UI has prior knowledge to determine which endpoint to access, which the IRS will not have.

**Cause of Bug, If Known**

The implementation of a blue/green deploy strategy removed this endpoint.

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by adunkman** [comment]
I cannot tag this issue, but I would tag it as High severity because the app behaves in a way that is strongly different from the one stated in the requirements.

**Comment by rachaelparris** [comment]
Current task list:
- [x] 1 Create a wildcard certificate for west
- [x] 2 Create a custom domain for api.{zone_name} using the wildcard certificate
- [x] 3 Link the api.{zone_name} custom domain to the current color’s API gateway

**Comment by JessicaMarine** [comment]
@adunkman You added this; can you test it?

**Comment by adunkman** [comment]
There appears to be an authentication issue in this solution — a request to the current color environment is not reproducible at the non-color endpoint.

Reproduction steps: 

- I logged in to https://app.dawson.flexion.us using clerkofcourt1@example.com.
- I copied the Bearer authentication token from the request to https://api-green.dawson.flexion.us/users and replicated the request using `curl` in my terminal and the request succeeded.
- I repeated the `curl` request, but changed the URL to https://api.dawson.flexion.us/users and the request failed. 

<details>
<summary>The successfully reproduced request to api-green.dawson.flexion.us (with bearer token redacted).</summary>

```
➜ curl -H "Authorization: Bearer [REDACTED]" -v https://api-green.dawson.flexion.us/users
*   Trying 3.223.55.101...
* TCP_NODELAY set
* Connected to api-green.dawson.flexion.us (3.223.55.101) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api-green.dawson.flexion.us
*  start date: Oct 14 00:00:00 2020 GMT
*  expire date: Nov 12 23:59:59 2021 GMT
*  subjectAltName: host "api-green.dawson.flexion.us" matched cert's "api-green.dawson.flexion.us"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f94a3006c00)
> GET /users HTTP/2
> Host: api-green.dawson.flexion.us
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer [REDACTED]
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Wed, 04 Nov 2020 14:53:34 GMT
< content-type: application/json; charset=utf-8
< content-length: 376
< x-amzn-requestid: 2b7c78fd-6b6b-4b44-91ee-c8c096a847f2
< access-control-allow-origin: *
< x-amzn-remapped-content-length: 376
< x-amzn-remapped-connection: close
< x-amz-apigw-id: VfMBUHNGIAMF5ww=
< cache-control: max-age=0, private, no-cache, no-store, must-revalidate
< vary: Authorization
< x-content-type-options: nosniff
< etag: W/"178-2F7faAwSELbTE3BGa3yFsH5Q/KI"
< x-powered-by: Express
< x-amzn-trace-id: Root=1-5fa2c06e-1f3d7ce25e89dc5c5a485fdc;Sampled=0
< pragma: no-cache
< x-amzn-remapped-date: Wed, 04 Nov 2020 14:53:34 GMT
< 
* Connection #0 to host api-green.dawson.flexion.us left intact
{"entityName":"User","email":"clerkofcourt1@example.com","name":"Test clerkofcourt1","role":"clerkofcourt","userId":"a7088a5c-4fc3-4daa-b0ef-4a57b537a833","contact":{"address1":"234 Main St","address2":"Apartment 4","address3":"Under the stairs","city":"Chicago","countryType":"domestic","phone":"+1 (555) 555-5555","postalCode":"61234","state":"IL"},"section":"clerkofcourt"}
```

</details>

<details>
<summary>The failed request to api.dawson.flexion.us (with bearer token redacted).</summary>

```
➜ curl -H "Authorization: Bearer [REDACTED]" -v https://api.dawson.flexion.us/users 
*   Trying 107.20.17.160...
* TCP_NODELAY set
* Connected to api.dawson.flexion.us (107.20.17.160) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.dawson.flexion.us
*  start date: Oct 30 00:00:00 2020 GMT
*  expire date: Nov 28 23:59:59 2021 GMT
*  subjectAltName: host "api.dawson.flexion.us" matched cert's "*.dawson.flexion.us"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa959806c00)
> GET /users HTTP/2
> Host: api.dawson.flexion.us
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer [REDACTED]
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 403 
< date: Wed, 04 Nov 2020 14:53:39 GMT
< content-type: application/json
< content-length: 23
< x-amzn-requestid: de2bdc7d-6746-4c9a-a431-6ad8785d0241
< x-amzn-errortype: ForbiddenException
< x-amz-apigw-id: VfMCFFVRoAMFv4w=
< 
* Connection #0 to host api.dawson.flexion.us left intact
{"message":"Forbidden"}
```

</details>

**Comment by adunkman** [comment]
This is verified fixed — in discussion with Mrin, Rachel, and Rae we discovered that this error was created by a environment color switch which was being performed by Cody during the time I tested this story. 

We are unable to reproduce since the environments were switched.
