### ISSUE TITLE
SPIKE: Hunt down instances where user is logged out unexpectedly

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7417]
Occasionally the user gets logged out after a Lambda timeout or an operation fails. This spike would be to try to identify as many of these as we can, identify any possible patterns in their behavior, and help inform future Bug tickets to fix the problems.

Related to ustaxcourt/ef-cms#7340 which aims to fix the Lambda timeout issue.

Team members have indicated there are other places in the system where this occurs. Let's find 'em!

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the **prod** environment

**Comment by klohman** [comment]
@JessicaMarine @mmarcotte Is this still an issue happening frequently?

**Comment by JessicaMarine** [comment]
I think we've fixed the obvious ones, but the intent of that story (spike) was to have a place the team could log timeout errors so that we could implement the "Try Again or contact dawson.support@ustaxcourt.gov" error message for them.

________________________________

**Comment by mmarcotte** [comment]
This appears to happen when a JavaScript error has occurred.
