### ISSUE TITLE
Add Case summary to Practitioner Detail Page in Admin

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#742]
Acceptance Criteria:

As a member of the Court, so that I can know the status of every case for a given practitioner, I want a list of every Docket Number and its status for a practitioner where I can edit Practitioners.

Notes:

@mmarcotte  has some helpful DynamoDB queries to help generate this information.

**Comment by mmarcotte** [comment]
dupe of ustaxcourt/ef-cms#6649

**Comment by JessicaMarine** [comment]
Added to Flexion's backlog: https://github.com/flexion/ef-cms/issues/8036
