### ISSUE TITLE
BUG: Filing Party for Notice of Change of Address/Phone/Both

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7420]
**Describe the Bug**
When a practitioner or unrepresented petitioner changes their address in the system, it automatically generates a Notice of Change of Address/Phone/Both and sends that notice to the Docket QC Inbox.  When the Docket Clerk is QC'ing it, it requires a Filing Party.  There should be no filedBy for a system-generated Notice of Change of Address/Phone/Both

**Business Impact/Reason for Severity**
Forcing Docket Clerk to pick wrong filedBy

**In which environment did you see this bug?**
Staging

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Providing demo to court

**To Reproduce**
1. Log-in as a practitioner or petitioner
2. Change the address so that the system generates a notice
3. Log-in as a Docket Clerk and locate the notice
4. QC the notice

**Expected Behavior**
Filing Party should not be required on the QC page

**Actual Behavior**
Filing party is required.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e6c97fe4-4f90-439e-aeab-0b66b26c961e)

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7c7a5116-816f-4365-9024-488977667fce)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Closing - added AC to ustaxcourt/ef-cms#7106
