### ISSUE TITLE
Change PR Process to Court

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7423]
Purpose:
- Enable changes to get to the Court’s environments more quickly 
  - Enables the Court to demo and train against the Court’s data sets.
  - Enables Flexion freedom to adapt and change their environments and data sets as desired for testing.
- Enable the development team to look their best — accepts only work that meets acceptance criteria.
  - In-progress code slows down review process, leading to back-and-forth conversations about code changes.
  - Unfinished changes reduces the quality of the code base used in production, leading to stability concerns (and Sleepless Mike).

Vision:
- The Court can review and accept changes from Flexion in **two business hours**.
What we’re trying to get there: 
- Adjusting guidance on pull request generation to allow reviewing changes separated by completed Bug / Feature, to enable streamlined review.
- Tweaking the pull request review process on the Court side to streamline the code review checklist such that they can be completed in two business hours or less, not including back-and-forth discussion of changes.

New Acceptance Criteria for Flexion:
- [ ] Court is able to SEE all of the changes for a Bug / Feature comprehensively (entire PR) AND story/feature separate from other changes.
- [ ] Court is able to see all the changes for one chunk of work in one place and be able to see what's changed (the difference in code)
- [ ] The Court needs to be able to see a final version of the code - the sum of the pull requests. 
- [ ] Court only receives code that has been QAed on a Flexion environment with Full Data Set
- [ ] Changes associated with a critical bug or hotfix can be QAed on a Flexion environment with Full Data Set and suggested to the Court without requiring other Bugs / Features to be completed first.

What’s not changing:
- Jessica/Mike/Julia/Andrew/Mark/“The Court” still would like to be involved as soon as possible to collaborate on solutions as appropriate.

**Comment by cholly75** [comment]
@mariahkannenberg - is this still relevant? Not sure how drastically processes have changed here since the story was written.

**Comment by mariahkannenberg** [comment]
I don't think so. As we move toward continuous deployment, many of these things will just resolve

**Comment by cholly75** [comment]
Thanks! Closing.
