### ISSUE TITLE
BUG: `Docket Entry No.:` and `docketEntryNo:` (in the machine-readable portion) of service email are not diplaying "0" for STIN (Mike to QA test)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7424]
**Describe the Bug**
On service email, `Docket Entry No.:` and `docketEntryNo:` (in the machine-readable portion) for STIN not diplaying "0"; it is blank

**Business Impact/Reason for Severity**
IRS uses this information to download and auto-route documents; without it, their process is blocked

**In which environment did you see this bug?**
IRS reported bug

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
IRS reported bug

**To Reproduce**

**Expected Behavior**
`Docket Entry No.:` and `docketEntryNo:` (in the machine-readable portion) in service email should be displaying "0" for the STIN

**Actual Behavior**
`Docket Entry No.:` and `docketEntryNo:` (in the machine-readable portion) in service email are blank when serving a STIN
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/3c837778-68f3-404c-b75f-7567de602d0c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mmarcotte** [comment]
I have also observed this in the Smoketests that get sent out. 

> Document Type: Request for Place of Trial at Birmingham, Alabama
> Docket Entry No.:
> Filed by: Petr. Wile e Coyote
> Served: 10/23/20 1:04 pm ET

> ---- COMPUTER-READABLE DATA ----
> docketNumber: 538-20
> docketEntryNo:
> docketEntryId: e93a91bb-c47b-4104-b3d1-6eea51fde561
> eventCode: RQT

It may not just be limited to STIN
