### ISSUE TITLE
BUG: Public API endpoint unknown to health monitoring alerts.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#7427]
**Describe the Bug**

There is no single Public API endpoint for the health endpoint which health alerts can be configured to monitor. 

**Business Impact/Reason for Severity**

The Court Tech Lead needs to be notified when the application reports an unhealthy system status, and without a machine-readable endpoint, health alerts cannot be configured to send such notifications. 

Similar to https://github.com/flexion/ef-cms/issues/6864, but for the public API.

**In which environment did you see this bug?**

https://stg.ef-cms.ustaxcourt.gov/health

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Working on https://github.com/ustaxcourt/ef-cms/issues/250.

**To Reproduce**
1. Go to https://stg.ef-cms.ustaxcourt.gov/health
3. Observe there is no single API endpoint — there are two used, the UI accesses either:
    - https://public-api-green.stg.ef-cms.ustaxcourt.gov/public-api/health
    - https://public-api-blue.stg.ef-cms.ustaxcourt.gov/public-api/health

**Expected Behavior**

I expected the API to be accessible at https://public-api.stg.ef-cms.ustaxcourt.gov/

**Actual Behavior**

There are two API endpoints used, either `public-api-blue.stg.ef-cms.ustaxcourt.gov` or `public-api-green.stg.ef-cms.ustaxcourt.gov`. The UI has prior knowledge to determine which endpoint to access, which the configured Route53 Health Checks do not have.

**Cause of Bug, If Known**

The implementation of a blue/green deploy strategy removed this endpoint.

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by codyseibert** [comment]
EOD update: I managed to get most of the terraform code deployed to exp1, now I need to verify it works.

**Comment by codyseibert** [comment]
To verify, you could go to `https://public-api.dawson.flexion.us/public-api/health`

**Comment by adunkman** [comment]
Implemented in https://github.com/flexion/ef-cms/pull/7177, not yet included in a PR to the Court’s repo. 

Looks great! Thanks @codyseibert!
