### ISSUE TITLE
BUG: New eFiled case not displaying on petitioner / practitioner dashboard

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7428]
**Describe the Bug**
1) After e-filing a case, the petitioner's new case is not displaying on the dashboard. The petitioner dashboard still displays the original instructions (with no case list). 

2) After e-filing a case, the practitioner's new case is not displaying on the dashboard.

3) After filing a document in a case to be automatically associated, the case is not displaying on practitioner dashboard. <-- This has been logged previously (believe it was ES related).  

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Flexion prod

**Who were you logged in as?**
petitioner1@example.com
privatepractitioner2@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Login as petitioner/ private practitioner 
2. eFile a case 
3. View dashboard 

**Expected Behavior**
Case should display in Open case list on dashboard. 

**Actual Behavior**
Case is not displayed on dashboard. 

**Screenshots**
https://drive.google.com/file/d/1-K9CFMUTXz_TNTvlWHGVec2MVrPgDSD8/view?usp=drivesdk

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
@klohman We were unable to reproduce this locally, on dev, exp1, and prod. We are thinking it was related to an elasticsearch issue that has now been resolved. Can you confirm please?

**Comment by JessicaMarine** [comment]
This issue was persisting in the Court's environments.  Jessica tested on 11.24.2020 in Court's migration environment after migration against "final" code and it worked as expected. Moving to done.
