### ISSUE TITLE
BUG: formattedJudgeName will fail

### ISSUE THREAD

**Issue by kkoskelin** [ustaxcourt/ef-cms#7431]
**Describe the Bug**
If the function `getJudgeLastName` is called with the argument "Judge Abigail Van Buren", the correct last name is "Van Buren" but it will return "Buren".  Will also fail by returning "Jr." for "signedJudgeName: "Daniel A. Guy- Jr."

If the function `formatJudgeName` is called with "Special Judge Romero" or "Chief Judge Smythe", the titles will neither be removed by the current regex.

There may not *yet* be judges whose names will fail these calculations, but the issue could pop up and this should be considered.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Flexion Prod / public

**Who were you logged in as?**
n/a

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing Order Search functionality

**To Reproduce**
1. Go to https://dawson.flexion.us/
2. Click "Order"
3. Type the keyword "order" on the left side
4. Type the docket number 21517-18 on the right side for docket number
5. Click "Search"

**Expected Behavior**
The search results would properly reflect the signed judge name in the table.

**Actual Behavior**
The name was simply listed as "Jr." when the actual signed judge coming from the API was "Daniel A. Guy- Jr."

**Screenshots**
![Screen Shot 2020-10-27 at 10 49 47 AM](https://user-images.githubusercontent.com/2445917/97329946-9cf45380-1845-11eb-8cb5-c0c15bd20fab.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome

**Cause of Bug, If Known**
The file `shared/src/business/utilities/getFormattedJudgeName.js` uses a very simple method to attempt to acquire the last name from a string by splitting on spaces and taking the last element. This fails for "Daniel A. Guy- Jr." when the output ought to be "Guy" and not "Jr."

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
@kkoskelin

* "Jr" is no longer displaying , but now Judge Guy is displaying as "Guy-" 

 ![Screen Shot 2020-11-03 at 7.12.07 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1aa3842e-7ca9-450c-bdd5-68af4cc274a2)

**Comment by kkoskelin** [comment]
@klohman I know this is really weird but -- I swear, the hyphen is IN THE JUDGE NAME on the case.  It's really there in the original (unformatted) full name.  We *could* make a rule that says "remove any hyphen at the end of the name" but it would be better to figure out how it got in the name in the first place (surely it does not belong) and fix it at the source.
![Screen Shot 2020-11-03 at 9 13 31 PM](https://user-images.githubusercontent.com/2445917/98065113-7754e480-1e19-11eb-94b8-aec63ca823b0.png)

**Comment by klohman** [comment]
@kkoskelin Given that the original bug has been fixed, I'm ok to close this. @JessicaMarine Should this name be corrected, and if so, does this need to be done by MVP?

**Comment by JessicaMarine** [comment]
@kkoskelin @klohman Yes, the hyphen needs to come out of the name for MVP.

**Comment by kkoskelin** [comment]
After discussing with @mmarcotte and Mark, it turns out there was an errant hyphen in a text file he used to create and load the test migration data.  There is no bug in the source code for displaying or storing or retrieving the data, so that's good news.  Mark will update his text file for the next load and we ought to see this go away.
