### ISSUE TITLE
BUG: New deadline not displaying in Deadlines report

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7432]
**Describe the Bug**
Added a new case deadline and it is not displaying in the deadlines report. 

I checked the report right after adding, and also 20 minutes later and it's still not displaying. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Flexion Prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. go to case 
2. add deadline 
3. View deadlines report 

**Expected Behavior**
Deadline should display in report. 

**Actual Behavior**
Deadline does not display in report. 

**Screenshots**
https://drive.google.com/file/d/1tCz_EEfIg1Br13LnmaAwXLDWjRkUe7xY/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
@klohman We believe this issue popped up when elasticsearch issues were happening a few weeks ago. We just tried the steps to reproduce on prod and were able to see the deadline. Let us know if this isn't the case for you!

**Comment by klohman** [comment]
cannot reproduce 11/20- moving to done
