### ISSUE TITLE
BUG: Paper Service modal displaying unexpectedly

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7446]
**Describe the Bug**
After completing the QC on an e-filed document with a paper service party, when clicking on the document from the Document QC Processed tab, the "Print Paper Service" modal displays. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Flexion prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. efile Document (for case with paper party)
2. Login as docket clerk 
3. Click Document QC > Inbox 
4. Click efiled document 
5. Complete QC 

_i tried once with adding a Other Party, but the first time I encountered this, I did not add an Other party_

**Expected Behavior**
Print Service modal should not display when clicked from Processed tab. 

**Actual Behavior**
the "Print Paper Service" modal displays

**Screenshots**
https://drive.google.com/file/d/1M_JkJh0kbydqe56Q4DJqVIftxJQx5ivY/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
@klohman Unable to reproduce locally, on dev, or on prod. I believe this bug was fixed as part of [this](https://github.com/flexion/ef-cms/pull/6968) PR. The cause of the bug was that the modal was not included in the 'My Document QC' page so it was not able to open until the user navigated to a page where it was included, like the Case Detail page as seen in this bug report.
