### ISSUE TITLE
BUG: Trial Session Working Copy: All actions causing error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7447]
**Describe the Bug**
Any action on the judge's trial session working copy is triggering error. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
judge buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
discovered during court's testing

**To Reproduce**
1. Login as judge 
2. Go to trial session working copy
3. Add note, change filters, update trial status 

**Expected Behavior**
Action should not cause error. 

**Actual Behavior**
Error message is displaying. It appears that the action is still successful. 

**Screenshots**
![Screen Shot 2020-10-29 at 1.22.40 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/19b8ce3f-2698-48f6-b393-2eea00e6d320)

https://drive.google.com/file/d/1IMCS3yJ4HouJwl5f562-0VjeTGte_92z/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The `migrateTrialSessionInteractor` was not creating a corresponding TrialSessionWorkingCopy

PR - ustaxcourt/ef-cms-flexion#7002

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
Cannot reproduce locally, on dev, or prod. We were able to reproduce for the specific trial session shown in the video made for the bug report before prod database was cleared. We suspect that specific trial session was in a bad state due to either an incomplete migration or being very old.

**Comment by klohman** [comment]
Issue recurred 11/04/20

Screen recording: 
https://drive.google.com/file/d/1ncVXFt348FjrzjcsgP-FxD9DPwmgvqwR/view?usp=sharing

**Comment by kkoskelin** [comment]
![Screen Shot 2020-11-09 at 1 41 18 PM](https://user-images.githubusercontent.com/2445917/98588404-46e5ce00-2291-11eb-9e77-fc2d5fa576a8.png)
Must fix code to check for undef, add coverage for condition
