### ISSUE TITLE
BUG: Error when manually adding a case to a trial session

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7449]
**Describe the Bug**
When manually adding a case to a trial session, spinner displays and does not go away. Console displaying web socket error. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Flexion prod

**Who were you logged in as?**
petitions clerk
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Case Detail > Case Information 
2. Click "Add to Trial" 
3. Select trial sessino 
4. Click add

**Expected Behavior**
Case should be added to the trial session and the Trial info card should update accordingly. 

**Actual Behavior**
Spinner displays and does not go away. Console displaying web socket error. 

**Screenshots**
![Screen Shot 2020-10-29 at 2.26.18 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b0586268-1730-4464-b518-16850e62cdb9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Note: Need to test Special /Motion/ Hearing trial session after bug fix.

**Comment by rachelschneiderman** [comment]
Waiting to see if [this](https://github.com/flexion/ef-cms/pull/6998) PR resolves the issue. Will check back in a few days.
