### ISSUE TITLE
AWS DynamoDB Failover

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#745]
Currently, if a DynamoDB table is unavailable or deleted, there is no automatic failover to another availability zone. We should determine what failover strategy we can set up for DynamoDB and then implement its configuration.

## Acceptance Criteria
* Determine failover strategy for DynamoDB, including consideration for how clients connect to another instance if failover occurs
* Implement configuration for the failover or log a separate issue for the same

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated

**Comment by mmarcotte** [comment]
DDB currently performs failover if one DDB table is deleted or becomes unavailable. We tested this when we upgraded to the most recent version of DDB. We deleted a table, and it failed over to the other region.
