### ISSUE TITLE
Lockdown API URL to `api.`

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7450]
## Pre-Conditions
- Check out the work in https://github.com/flexion/ef-cms/issues/6864

## Acceptance Criteria

- During a deployment, a step should open up the deploying-color api endpoint `api-<deploying_color>.<efcms_domain>` to test the deploying color before we switch-colors
- The switch-colors step move `api-<deploying_color>.<efcms_domain>`  to `api.<efcms_domain>`, and disable `<deploying-color>.<efcms_domain>`.
- The currently deployed UI at `app.<efcms_domain>` talks only to `api.<efcms_domain>`.
- This makes `api-<current_color>.<efcms_domain>` obsolete, and it should not respond to requests.
- This also makes `app-<current_color>.<efcms_domain>` obsolete, and it should forward to `app.<efcms_domain>`
- In other words, `app-<deploying_color>.<efcms_domain>` and `api-<deploying_color>.<efcms_domain>` are only live between the step to open it up for testing and the `switch-colors` step.
- The API should reject a request from a user who is on an older version of the UI who is still on a page that has a previously deployed version of the app should be warned that their browser is out of date. (could be broken out into its own story)

## Mobile Design/Considerations
N/A

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Could create another issue to handle the final AC item.

## Definition of Done (Updated 8-3-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by cholly75** [comment]
@mmarcotte Is this still needed?

**Comment by cholly75** [comment]
Stale.
