### ISSUE TITLE
BUG: Not Served showing in Document View (COURT TO TEST)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7453]
**Describe the Bug**
For migrated documents that are LegacyServed is yes, the document/service information is displaying correctly on the Docket Record.  However, it is still showing "Not Served" on the Document View.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**
Any Court user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing

**To Reproduce**

**Expected Behavior**
"Not Served" would not display above PDF viewer in Document View.

**Actual Behavior**
"Not Served" in red is showing above PDF viewer in Document View.
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/2c747e8f-5953-48c8-a1af-fcfb20cef590)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
`isLegacyServed` flag was not being checked in documentViewerHelper
PR-#7108

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
@JessicaMarine would you happen to remember the docket number of the case for which you saw this bug?

**Comment by JessicaMarine** [comment]
@mrinsin It was in the Court's test environment. You won't be able to reproduce this in Flexion's prod because you don't have PDFs in that environment.

**Comment by mrinsin** [comment]
We faked some data on prod to be legacy served and were able to verify the fix!

**Comment by JessicaMarine** [comment]
Moving to Done.  Will test on the Court's environments/revive if reported again.
