### ISSUE TITLE
Pen Testing Security Concern: NoSQL Injection

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7454]
The Court engaged a third-party (NSSPlus) to perform penetration testing and  a vulnerability assessment of DAWSON.  NSSPlus reported a low-risk security vulnerability relating to NoSQL Injection.  NSSPlus' findings and recommendations are included in Notes below.

## Acceptance Criteria:
* Remediate low-risk security vulnerability relating to NoSQL Injection

## Notes:
* See section 6.3 of this report for NSSPlus' findings and recommendations re: NoSQL Injection: 
[https://app.zenhub.com/files/152320868/1ac6d946-6c42-4bdd-bea2-40d603b8ca97/download](https://app.zenhub.com/files/152320868/1ac6d946-6c42-4bdd-bea2-40d603b8ca97/download)

**Comment by mmarcotte** [comment]
While I 👍 the catching of exceptions from the Search client, I think I side with the testers that the queries shouldn't be being making it to the data store. We should be rejecting searches that have special characters. Perhaps we can use Joi to validate what is a valid search query.

**Comment by JessicaMarine** [comment]
Moving this story to done!  Any additional work (e.g., rejecting searches that have special characters) will be added to the search stories.
