### ISSUE TITLE
Pen Testing: Found API Key

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7455]
The Court engaged a third-party (NSSPlus) to perform penetration testing and  a vulnerability assessment of DAWSON.  NSSPlus reported an informational item relating to Found API Key.  NSSPlus' findings and recommendations are included in Notes below.

## Acceptance Criteria:
* Remediate issue found by NSSPlus re: Found API Key

## Notes:
* See section 7.2 of this report for NSSPlus' findings and recommendations re: Found API Key: 
[https://app.zenhub.com/files/152320868/622ca15d-173e-49d3-80eb-c50f7d9024d1/download](https://app.zenhub.com/files/152320868/622ca15d-173e-49d3-80eb-c50f7d9024d1/download)

**Comment by codyseibert** [comment]
It appears that those keys are related to a flexion honeybadger key which we have removed since this was committed.  I do not think this is an issue due to this key being inactive now and since the court isn't using honeybadger at this point.

**Comment by ericsorenson** [comment]
Modifications to the history of the court's repository can't be made with a pull request from a fork. 

https://github.com/rtyley/bfg-repo-cleaner is a great tool for modifying git history.

**Comment by mariahkannenberg** [comment]
Court to address
