### ISSUE TITLE
Pen Testing: found Report.html

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7456]
The Court engaged a third-party (NSSPlus) to perform penetration testing and  a vulnerability assessment of DAWSON.  NSSPlus reported an informational item relating to found Report.html.  NSSPlus' findings and recommendations are included in Notes below.

## Acceptance Criteria:
* Remediate issue found by NSSPlus re: found Report.html

## Notes:
* See section 7.3 of this report for NSSPlus' findings and recommendations re: found Report.html: 
[https://app.zenhub.com/files/152320868/89a78659-94f0-40c1-a499-6666575a1c1f/download](https://app.zenhub.com/files/152320868/89a78659-94f0-40c1-a499-6666575a1c1f/download)

**Comment by ericsorenson** [comment]
Report.html was removed when we switched from parcel to webpack.

**Comment by cholly75** [comment]
Thanks @ericsorenson - closing issue.
