### ISSUE TITLE
BUG: Paper Petition : Not Displaying in Document QC > In Progress after case creation or save for later

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7458]
**Describe the Bug**
As petitions clerk, when adding a paper petition and creating the case, the Petition is not displaying in the Document QC In Progress box. When clicking Save for Later on Review Screen, the Petition still does not display in the Document QC In Progress box. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Document QC 
2. Click Start a Petiiton 
3. Complete form 
4. Click Create Case 
5. Click Document QC 
6. Click In Progress tab 

**Expected Behavior**
petition should display in Document QC > In Progress tab when case is created and until Petition is served. 

**Actual Behavior**
Petition is not displaying in Document QC > In Progress tab 

**Screenshots**
https://drive.google.com/file/d/1HnfSRe13Q8fxn79ZJX82G4NS1sFT8VVV/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman this one may also have been resolved by the elasticsearch re-indexing.  I tried but was unable to replicate.
