### ISSUE TITLE
BUG: Eligible Case list : L & P cases are not being sorted to top

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7459]
**Describe the Bug**
L & P cases should be prioritized in the eligible case list for a "New" Trial Session. Currently, these cases are not prioritized and are just sorted by docket number. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Trial Sessions from main nav
2. Click New tab
3. Click Trial Session link 

**Expected Behavior**
L & P cases are sorted to top of list of eligible cases. 

**Actual Behavior**
L & P cases are not prioritized and are just sorted by docket number. 

**Screenshots**
![Screen Shot 2020-11-02 at 3.47.59 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/47d47e6a-5a59-4421-ad74-2ec7323e53e6)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
@kkoskelin I saw this issue reoccur today: 

- I updated case status and trial location on two cases (one was an L case) and the L case did not sort to top of Eligible list. 

![Screen Shot 2020-11-04 at 11.45.38 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cb7be386-d1c7-4fc6-8a42-9f8cc91d734a)

**Comment by kkoskelin** [comment]
@klohman I had originally followed the AC very "strictly" and applied the priority sorting only to cases with suffixes "L" and "P".  However, Small Lien/Levy has code "SL" (seen also in your screenshot).  I've created a pull request to add "SL" to the set of changes.

**Comment by kkoskelin** [comment]
![Screen Shot 2020-11-04 at 3 53 26 PM](https://user-images.githubusercontent.com/2445917/98171778-e718ad00-1eb5-11eb-91dc-2818ca5adc61.png)
