### ISSUE TITLE
Resiliency: Establish risk mitigation and acceptance documentation

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#746]
During resiliency testing work done in #247, questions came up about what we'd like to do in the near future and what we are willing to accept as risks at the moment. This story covers documenting risk acceptances and talking to tech lead Mike Marcotte to determine the same. 

## Acceptance Criteria
* Add a document to the ef-cms repo which will list out resiliency risks and document whether we currently accept each risk or have infrastructure set up to mitigate the risk.
* Collaborate with Mike Marcotte and team on the unanswered questions in the document.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated

**Comment by julialeague** [comment]
Logged an issue for setting up DynamoDB alerts: https://github.com/ustaxcourt/ef-cms/issues/780

**Comment by adunkman** [comment]
Closed by https://github.com/ustaxcourt/ef-cms/pull/795.

**Comment by julialeague** [comment]
#795 introduced the resiliency documentation created as a result of the work in this issue. Follow-up issues are logged.
