### ISSUE TITLE
BUG: Case Inventory Report not displaying cases matching criteria

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7461]
**Describe the Bug**
Case Inventory Report is displaying "no cases matching" when there are matching cases in the system. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
petitions clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Reports > Case Inventory Report 
2. Select case status (with known cases matching) 

**Expected Behavior**
Cases matching criteria should display in report. 

**Actual Behavior**
Cases matching criteria are not displaying in report. 

**Screenshots**
![Screen Shot 2020-11-03 at 7.25.28 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/85168c9d-be96-40ee-b45b-bace2474dadd)

![Screen Shot 2020-11-03 at 7.25.43 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/726de9e7-9183-4897-92fa-9e6e338280d2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman is it possible this bug, reported in prod, was purely a symptom of the elasticsearch issues that were resolved this morning?  It sure seems like it.  I'm not able to replicate -- plenty of cases show up for me as a petitions clerk when changing the filter status values.

**Comment by klohman** [comment]
@kkoskelin Thanks for checking. I will close - this was reported prior to the ES being indexed.
