### ISSUE TITLE
BUG: Error received when clicking on trial session link

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7465]
**Describe the Bug**
When clicking on trial session location link, app routes to Error screen. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
judge buch 
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Trial Session list 
2. Click New tab 
3. Click Mobile, Alabama link 

**Expected Behavior**
App should route to trial session detail 

**Actual Behavior**
app routes to Error page. 

**Screenshots**
![Screen Shot 2020-11-04 at 11.37.41 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/07a5aaa6-cb0d-4b01-895d-85f941f0c469)

https://drive.google.com/file/d/1AFl0GxffXD8snYZEpTVAmJymfEAN2trs/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
The logs show this request:
`
2020-11-04T22:01:50.804Z	e522bd70-d3c0-444b-9f25-388584998e94	INFO	Event {"headers":{"accept":"application/json, text/plain, */*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,ru;q=0.8","authorization":"Bearer <token>","cache-control":"no-cache","dnt":"1","host":"api-green.dawson.flexion.us","origin":"https://app.dawson.flexion.us","pragma":"no-cache","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-site",
"user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
"x-amzn-trace-id":"Root=1-5fa324ce-2b19aad40c25de4625bd48ea","x-forwarded-for":"24.196.144.171","x-forwarded-port":"443","x-forwarded-proto":"https","content-length":"4","connection":"close"},"path":"/trial-sessions/6a4347ca-924e-47d7-8e77-2ef689a2d494/eligible-cases","pathParameters":{
"trialSessionId":"6a4347ca-924e-47d7-8e77-2ef689a2d494"}, "queryStringParameters":{"fields":"isManuallyAdded,caseCaption,privatePractitioners,irsPractitioners,caseType,qcCompleteForTrial,docketNumber,docketNumberSuffix,removedFromTrialDate,removedFromTrial"},"body":"{}"}
`

shortly followed by
`
2020-11-04T22:01:50.874Z	e522bd70-d3c0-444b-9f25-388584998e94	ERROR	ValidationException: Provided list of item keys contains duplicates
    at Request.extractError (/var/task/api.js:28920:27)
    at Request.callListeners (/var/task/api.js:31675:20)
    at Request.emit (/var/task/api.js:31642:10)
    at Request.emit (/var/task/api.js:38107:14)
    at Request.transition (/var/task/api.js:37433:10)
    at AcceptorStateMachine.runTo (/var/task/api.js:35224:12)
    at /var/task/api.js:35235:10
    at Request.<anonymous> (/var/task/api.js:37449:9)
    at Request.<anonymous> (/var/task/api.js:38109:12)
    at Request.callListeners (/var/task/api.js:31687:18) {
  code: 'ValidationException',
  time: 2020-11-04T22:01:50.873Z,
  requestId: 'OTDTLEH0LKPN89DL26JF3ONP6BVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 13.66872310566466
}
`

**Comment by rachaelparris** [comment]
I'm not able to recreate this on prod anymore. @klohman are you able to?
