### ISSUE TITLE
(related to 7010)BUG: Practitioner Dashboard: Practitioner removed from case, but case still displays on dashboard

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7470]
**Describe the Bug**
After removing a practitioner from a case, the case is still displaying on the practitioner's dashboard. When user clicks into the case, they only see the public view of the case. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk 
privatePractitioner1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Login as docket clerk 
2. Go to case (case has petitioner counsel) 
3. Remove petitioner counsel 
4. Login as petitioner counsel 

**Expected Behavior**
Case no longer displays on practitioner dashboard

**Actual Behavior**
Case is still displaying on dashboard 

**Screenshots**
https://drive.google.com/file/d/1HMoTOxj0urjg7GrJZ9UisB6CATFLw_b2/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
The fix for ustaxcourt/ef-cms#7471 (PR https://github.com/flexion/ef-cms/pull/7079) should resolve this issue as well.
