### ISSUE TITLE
BUG: Document QC-  Item still displaying in Inbox after QC is complete

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7471]
**Describe the Bug**
After completing QC on a document, the document is remaining in the Document QC Inbox. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Document QC inbox
2. Click document link 
3. Complete QC 

**Expected Behavior**
Completed item should not display in the Document QC Inbox, and should display in the Processed box. 

**Actual Behavior**
After completing QC on a document, the document is remaining in the Document QC Inbox. 

**Screenshots**
https://drive.google.com/file/d/1OHVkB47qVt9EE7iGgO3ZJhwB5WmXrjDv/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
If you wait a bit and then refresh does it go away? Just want to make sure this isn't ES taking its time updating the indexed records.

**Comment by klohman** [comment]
@matthopson It's been almost 10 minutes and I'm still seeing them there

**Comment by matthopson** [comment]
Thanks! That's important to know!
