### ISSUE TITLE
BUG: Order search - unexpected search results

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7481]
**Describe the Bug**
When searching for keyword "order" , I get more results when filtering than when original searching only by keyword. 
**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
private practitioner 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to advanced search > Orders 
2. Search keyword "order" 
3. Filter by petitioner name 

**Expected Behavior**
Filtered results should be fewer than original search - matching results should be keyword AND filter

**Actual Behavior**
Filter results are more than original search. 

**Screenshots**
https://drive.google.com/file/d/14L0XpT3egmGulzO8nRyk7FICg4RGAIcQ/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman I've added the `Search` tag to this issue.
I think we may have to re-examine the Expected results
```
**Expected Behavior**
Filtered results should be fewer than original search - matching results should be keyword AND filter
```
Maybe this should be connected to the Elasticsearch spike, and maybe the ES trello card.  At issue IMO is how we index the different fields, and how we expect Elasticsearch to process and return results.

The searches are not actually like strict SQL clauses which MUST be matched -- at least, not in their current configuration.  Rather the results are a list of things which match to a greater or lesser extent the search terms provided.  BEST matches should continue to always be at the very top of the list, but more terms might mean more rows which can possibly match one or more criteria.  Think of ES current implementation a bit like a Google Search -- you could get a nearly endless list of results, but with the right terms you'll nearly always get the best matches shown on the first page.

Again, I think I've got to investigate precisely how we are indexing and searching fields to make sure that some fields are searched only with the strictest of matching, something facilitated by changing the indexing settings.
