### ISSUE TITLE
BUG: Print Paper Service screen not displaying PDF preview

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7483]
**Describe the Bug**
After adding and serving a paper document, the PDF preview is not displaying on the print screen. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case with paper service
2. Add paper filing 
3. Serve

**Expected Behavior**
PDF preview should display on print screen. 

**Actual Behavior**
App routes to print screen but the PDF preview is not displaying. 

**Screenshots**

![Screen Shot 2020-11-06 at 2.59.24 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4d76a9c8-31b3-4795-89cf-e5254721c868)
https://drive.google.com/file/d/14-Bxv625FsytqSPcYNk2M7cPIemh9ETF/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The DocketEntry entity did not have `category` as a field, however, that field was relied upon for determining if a docket entry was to be added to the p[ending report on creation. The value of `pending` on the docket entry was also following a path during QC that did not generate a pdfPreviewUrl.

PR- ustaxcourt/ef-cms-flexion#7082

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
`web-client/src/presenter/sequences/fileDocketEntrySequence.js` calls `setPdfPreviewUrlAction` on line 51 -- but there is no previewUrl in the props stream.
