### ISSUE TITLE
BUG: Case matching criteria not displaying in case inventory report

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7484]
**Describe the Bug**
Case matching report criteria is not displaying on Case Inventory Report

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to case 105-20 (confirm status and judge)
2. Go to Case Inventory Report 
3. enter status and judge 

**Expected Behavior**
Cases matching criteria display on case inventory report 

**Actual Behavior**
Case matching report criteria (105-20) is not displaying on Case Inventory Report

**Screenshots**
https://drive.google.com/file/d/1lFpHwxkifgAZDYiSaXfGmW-IlnSBn-Sy/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
@klohman The case (105-20S) does show up when I try this on prod. Could it be possible that you needed to hit enter on the `ctrl+f` once more after loading all search results? That's what I did and was able to see the case!
