### ISSUE TITLE
BUG: Sort order of cases on Inventory Report

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7488]
**Describe the Bug**
Cases on Case Inventory report are not sorting by docket number correctly (oldest to newest) consistently. Could be related to cases older than 2010 sorting unexpectedly

If I run a Case Inventory report for Judge Holmes, I get a case count of 255 cases, and the oldest showing in the UI is a 2010 docket number (5242-10). He’s got 255 cases in his inventory, so I can hit the “Load More” button. For the first 8 clicks, it adds cases to the bottom of the list (i.e., more recent cases). On the 9th click (if I counted correctly) it added several pre-2010 cases to the top of the list. It seems like those cases should have been at the top of the list to begin with.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's test environment (by Judge Buch); replicated in Flexion's prod (Jessica)

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing

**To Reproduce**
1. Go to Case Inventory 
2. Select Judge Holmes
3. Run Report 
4. Load all case results

**Expected Behavior**
Cases should display sorted oldest to newest by docket number for all cases returned in the report. 

**Actual Behavior**
5242-10 is displaying as the first (oldest) case in the report on initial load. After the list is fully expanded, 1144-05 is displaying first in the list. 

**Screenshots**
Initial Load: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/57271bff-1b9a-4b68-b37a-1a0e027ad507)
Fully Expanded: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/301e8bf2-c3ce-4eb5-83b0-f2c686a6df61)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Cannot reproduce on flexion prod 11/23.

**Comment by codyseibert** [comment]
This fix will require a re-index on prod
