### ISSUE TITLE
BUG: Names with hypens NOT returning in case search

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7489]
**Describe the Bug**
In Docket No. 17000-15W, petitioner's name is "Whistleblower 17000-15W".  When logged in as a Court user, if you search for "Whistleblower 17000-15W" in Case Search, it doesn't show up in results.  If you search for "Whistleblower 17000" it does.

**NOTE:**  Same thing happens when I put "Coca-Cola" in the search box.  It doesn't return 31183-15, but "Coca" does.  I think it's the hypen

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's test environment

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing

**To Reproduce**
1. Log in as any court user
2. Go to Advanced > Case Search
3. Type "Whistleblower 17000-15W" in search box.
4. Results do not return docket no. 17000-15W; they should.

**Expected Behavior**
When you search for "Whistleblower 17000-15W" in case search box, docket no. 17000-15W should return in the results.

**Actual Behavior**
When you search for "Whistleblower 17000-15W" in case search box, docket no. 17000-15W does not return in results.  When you search for "Whistleblower 17000" in case search box, docket no. 17000-15W **does** return in results.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
After updating a petitioner name with a hyphenate, search shows it is returning the correct results on dawson.flexion.us

![Screen Shot 2020-12-07 at 9 13 39 AM](https://user-images.githubusercontent.com/2445917/101368269-8ee61980-386c-11eb-8014-47db8ff9d2b9.png)

**Comment by klohman** [comment]
Creating new bug related to display of the max search results message
