### ISSUE TITLE
(NEED for FINAL) Court User: List of documents on Document View

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7491]
As a Court user, I would like the table of documents in a case to scroll, so that I can see the documents by the PDF viewer.

## Acceptance Criteria:
* Make the list of documents on the Document View at a fixed height and make scrollable so user can view the list of documents side-by-side with the PDF viewer

**Comment by matthopson** [comment]
Per our discussion, I've updated this, and will move it back to ready for review when we get it on prod.
