### ISSUE TITLE
BUG: Removing from Trial Session fails to update caseStatus and highPriority on workItem

### ISSUE THREAD

**Issue by kkoskelin** [ustaxcourt/ef-cms#7492]
**Describe the Bug**
After removing a case from a trial session, the Section Document QC Inbox still shows a work item with high priority and status of "Calendared".

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
prod

**Who were you logged in as?**
docketclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Tryng to replicate an entirely different bug which was showing two work items from the same case whose status was "General Docket" in which one item showed a high priority indicator but the other did not ustaxcourt/ef-cms#7473

**To Reproduce**
1. Navigate to Section Document QC, Inbox.  
2. Find "580-20" in the page
3. See the red high priority indicator in its row, and a status of "Calendared"
4. Go to Case detail for 580-20
5. Click "Case Information"
6. See that there is no trial session scheduled.

**Expected Behavior**
After removing a case from trial, I expect all work items to be set `highPriority: false` and to be updated with the case's new status, "General Docket - At Issue (Ready for Trial)".

**Actual Behavior**
I clicked "Remove from Trial" on 580-20.  The case itself is correctly updated. Its Case Details page shows it is not scheduled for trial and the status is correct. However, Section Document QC Inbox still shows a work item "high priority" and "Calendared".

**Screenshots**

![Screen Shot 2020-11-17 at 4.03.43 PM.png](https://images.zenhubusercontent.com/5bbf750502b9b3375461a416/f23d7d38-fe26-4cf4-b5d5-8c76ec1e66eb)
![Screen Shot 2020-11-17 at 4.29.23 PM.png](https://images.zenhubusercontent.com/5bbf750502b9b3375461a416/f7792cb0-75c8-4c63-8c6f-9df4c865f0ec)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
I've found that the dynamodb record itself for the work-item is also showing highPriority: true and General Docket -- meaning that what we're seeing is not merely an Elasticsearch quirk.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Cannot reproduce 11/23/20 on flexion prod.
