### ISSUE TITLE
BUG: Document QC Inbox - clicking on document causing error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7496]
**Describe the Bug**
When clicking on a document title from the Docket Document QC Inbox, the screen goes blank and console shows errors. 
This is not happening for all documents in the inbox, only some. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Go to Section Document QC Inbox 
2. Click document link

**Expected Behavior**
App routes to QC screen

**Actual Behavior**
Blank screen displays. 

**Screenshots**

https://drive.google.com/file/d/1EX0_rf9JZ9KbA8qbdUHRLhuITUJfJfG1/view?usp=sharing
![Screen Shot 2020-11-18 at 12.51.29 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5bcf64ed-37d8-4d07-8690-684095dc7942)![Screen Shot 2020-11-18 at 12.51.29 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bc5298f0-aa59-4770-9cde-cd69cfdb6c4b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
The issue is that some cases were overwritten via migration, but work-item records were not cleaned up. I just merged a PR that solves this issue by ensuring that all work item records get removed when a case is migrated with the same docket number as an existing case.

This fix will prevent this from happening in the future. I think to clean up the prod environment, we'll need to run a new migration just to clear all the records out, or clear the db.
