### ISSUE TITLE
(NEED FOR FINAL) BUG: Judge associations not consistent on reports (Case Inventory, Deadlines)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7499]
**Describe the Bug**
Cases assigned to the Chief Judge and to Judge Foley are not displaying correctly on the case inventory report. 
When selecting Chief Judge or Foley and status "Jurisdiction Retained" on the Case Inventory Report, the same cases are displayed. 

On the deadlines report, Chief Judge displays with no cases (for today's date) and Foley displays with several cases that are actually associated with Chief Judge (not Foley). 

Pending report _seems_ to be working correctly, but we should confirm with various scenarios. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexon prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Case Inventory Report 
2. Select Jurisdiction Retained
3. Select Chief Judge
4. Run Report 
5. Select Foley and rerun report
6. Go to Deadlines report 
7. Select Chief Judge filter 
8. Selet Foley filter

**Expected Behavior**
Cases assigned to Judge Foley should display in the report when Foley is selected. 
Cases assigned to the Chief Judge role (not Chief Judge Foley) should display in the report when Chief Judge is selected. 

Reference test cases around Chief Judge vs. Judge Foley https://github.com/flexion/ef-cms/issues/4830

**Actual Behavior**
Same cases are displaying for both Chief Judge and for Judge Foley on the Case Inventory report. 
Deadlines report is displaying cases associated with Chief Judge when Foley is selected. 

**Screenshots**
![Screen Shot 2020-11-19 at 1.43.02 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1b3f18ed-449e-4817-a7d7-e2efb49f621d)

![Screen Shot 2020-11-19 at 1.43.14 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c2e5ef4e-4ed2-488c-b3a6-9f02d8fbb408)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
There are 8 open cases associated with Judge Foley:
011682-18	Polo Square Partners LLC, William Swank, Jr., Tax Matters Partner	Foley, Maurice
025440-18	Edward M. Lopez & Julia Munoz	Foley, Maurice
005274-19	Lora K. Brownstein	Foley, Maurice
005311-19	Richard A. Brownstein	Foley, Maurice
005312-19	Richard A. Brownstein & Lora K. Brownstein	Foley, Maurice
017252-18	Paul V. Wojdak	Foley, Maurice
013128-13	Estate of James R. Flandreau, Deceased, John L. Curtis, Executor	Foley, Maurice
021103-18	Mahdad Berenji & Rebeca Motaharnia	Foley, Maurice

**Comment by JessicaMarine** [comment]
Jessica can manually change the Jurisdiction Retained cases to fix that issue.  Mark changed the judge migrated with deadlines and that fixed the other issue. Moved to Done.
