### ISSUE TITLE
Docket Clerk: Trigger error when place of trial and procedure type don't match

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7508]
Currently, docket is presented with all trial location options when modifying metadata.  Need to build some logic into that so that it triggers an error when place of trial and procedure type don't match.  

Example:  Case has Fresno, CA as preferredTrialCity.  Judge issue order removing "S".  When docket processing that order removing the "S", the system should alert them that the city is no longer valid/compatible with regular procedure type.

**Comment by cholly75** [comment]
Will not do.
