### ISSUE TITLE
Court: Remove/hide header, deploy date/time, and implement footer

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7509]
As the Court, in order to make sure we're ready to go live, we need a few tweaks to the prod URL:

Acceptance Criteria:
* Remove/hide from the Court's production env the top banner that says "This is a testing site for the U.S. Tax Court and not intended for public use. To learn more about starting a case, visit the U.S. Tax Court website."
* Remove/hide from the front end Court's production env the deploy date/time (bottom right). Display in code for reference.
* Implement footer in all environments.

**Comment by klohman** [comment]
### Footer 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0b070c76-1cac-49c8-8e79-827f9495c9f3)

**FAQs link** 
* opens url in new tab:  https://ustaxcourt.gov/dawson.html

**Privacy** 
* routes to Privacy page /privacy

**Contact Us**
* routes to Contact Us page /contact

### Privacy Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a3e5d11f-5acc-46af-98d0-34044ebca5cb)

### Contact Us Page
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c97a06e8-3ab6-4043-bebf-a5af85a06b91)

**Comment by JessicaMarine** [comment]
Jessica reviewed 12.2.2020 -- moved to done
