### ISSUE TITLE
BUG: "Unservable" documents displaying as Not Served on docket record for public users

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7512]
**Describe the Bug**
Court -issued documents that are not servable are displaying as "Not Served" on the public docket record for legacy cases and new cases. 

Possibly related to [#7164](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7164)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 17784-12 (legacy case)
2. View docket entries 65 and 69
3. Go to 13331-20 (new case)
4. View docket entry for ROA 
**Expected Behavior**
Unservable documents should not show the "Not Served" message on the docket record. 

**Actual Behavior**
Unservable documents are displaying the "Not Served" message on the. public docket record. 

**Screenshots**
![Screen Shot 2020-11-25 at 8.54.08 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b6daa1dc-4520-4a92-9428-95895b9bcff0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
Combining with ustaxcourt/ef-cms#7511
