### ISSUE TITLE
BUG: Court-issued documents other than Orders and Opinions should not be visible to public

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7514]
**Describe the Bug**
Notice of Trial is hyperlinked on public docket record. Only orders and opinions should be hyperlinked on public docket record.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod/court environments

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
Notice of trial is not hyperlinked on public docket record. 

**Actual Behavior**
Notice of Trial is hyperlinked on public docket record. Only orders and opinions should be hyperlinked on public docket record.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
These event codes should not be visible to the public 

SDEC- not visible (Special logic we should already have built) 
NOT
FTRL
HEAR
NTD
PTRL
TRL
ROA
MISC 
HE
TE
USCA
ES
RM 
TRAN - logic not visible for 90 days?  
CTRA- logic not visible for 90 days? 
RTRA- logic not visible for 90 days? 
EDIT (By Kris): transcript code requirements are now captured in https://github.com/flexion/ef-cms/issues/7170

**Comment by matthopson** [comment]
@JessicaMarine Status: PR merged to dev. Needs a prod deploy for QA.

**Comment by klohman** [comment]
Verified fix on Flexion Prod 11/30/20 except for CTRA, RTRA @matthopson @JessicaMarine CTRA and RTRA are visible to public currently. 

Fix does not include logic for CTRA, RTRA - which will be addressed in https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7170
