### ISSUE TITLE
BUG: Mobile - Printable Docket Record not scrolling in iframe (can only view page 1)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7519]
**MAKE SURE THIS FIX DOESN'T IMPACT INTERNAL USERS**

**Describe the Bug**
Viewing the printable docket record on iPad, the iframe is not scrollable and only the first page of the PDF is visible. 
This seems to be happening on all mobile views. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod
court environment 

**Who were you logged in as?**
public

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to case 
2. Click Printable Docket Record 

**Expected Behavior**
PDF should display in iframe and user should be able to scroll within frame to view all pages of PDF. 

**Actual Behavior**
PDF displays only the first page and does not allow scroll to view additional pages. All PDF controls are also hidden (print, download, etc.) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - iPad)S 14.2
 - Browser [e.g. chrome, safari] - Chrome 
 - Version [e.g. 22] 87.0.4280.77

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - iPad Pro 

Court employee saw this bug on this device: 
 iPadAir, Model # MF010LL/A; software version 12.3.1, Safari

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman @ericsorenson this has me thinking that we might want to create alternate paths for mobile/touchscreen vs the rest.  The PDFs in iframes don't work on android, so we link directly (for example).  Perhaps this should be the standard?

**Comment by klohman** [comment]
> @klohman @ericsorenson this has me thinking that we might want to create alternate paths for mobile/touchscreen vs the rest. The PDFs in iframes don't work on android, so we link directly (for example). Perhaps this should be the standard?

Agree.

**Comment by kkoskelin** [comment]
This will need to be discussed further -- it seems that it is a very specific problem we are solving, that of displaying a PDF in an iframe on Safari on iOS (ipad, etc).  There are no workable css hacks that will allow us to make the PDF scrollable in the iframe.  So -- do we create a browser- or platform-specific hack that launches the pdf in the entire window?  Do we go full-screen for the PDFs for all users?  Something else?

**Comment by klohman** [comment]
@kkoskelin There was a reason we chose to display this in an iframe and I'm not sure if it was due to a Chrome issue. Let's investigate/discuss if we "need" to continue to use the iframe to solve any other problem (i'd hate to solve one problem only to create another). 

To solve [6841](https://github.com/flexion/ef-cms/issues/6841), we made the decision to just open up PDFs in the current browser window across all devices.

**Comment by kkoskelin** [comment]
I'm not sure that we really have a path forward for this, because users of Safari on iOS will all have this problem, and the only way to work around it is to send users directly to the PDF (for printable docket record) or else attempt to detect the platform (that of Safari on iOS) and provide a "download" button.  I don't think that any kind of clever platform-detection is an ideal solution, but it's worth noting that *anywhere* in the app where we place PDFs within iframes will become a problem for users with ipads, iphones, etc.

**Comment by matthopson** [comment]
Dropping until we can discuss some additional findings.

**Comment by matthopson** [comment]
As discussed, here's the branch for method for opening the pdf from a modal. This allows us to generate the pdf and create a real link that can be clicked by the user, which prevents mobile safari from silently blocking the pdf from opening in a new tab programatically.

Branch: `7181-bug-printbale-dr-mobile`
Note: Will likely need updates to integration and pa11y tests to complete

![Screen Shot 2020-12-24 at 9.15.10 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/937919a6-403e-4653-9d78-a8c9683cffee)

![Screen Shot 2020-12-24 at 9.15.25 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/647cd758-e5bd-4e2a-8e36-fcc24b540980)

![Screen Shot 2020-12-24 at 9.15.46 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/e0df6579-bc91-4638-bbc6-431030d1fd77)

**Comment by klohman** [comment]
@JessicaMarine This fix applies across all the Printable Docket Record links. Do we want to retain the PDF opening in an iFrame for internal users, or are we ok to use this flow and open the PDF in a new tab for internal?

**Comment by JessicaMarine** [comment]
@klohman I am okay with this being applied for internal users as well.

**Comment by JessicaMarine** [comment]
Judge Buch tested on an iPad. He reports he had no issues opening and scrolling through a long Printable Docket Record.
