### ISSUE TITLE
BUG: Cases checked as complete not being added to trial session when calendar is set

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7522]
**Describe the Bug**
* Cases that were checked as "QC Complete" on eligible list were not added to session list when calendar was set. 
* User navigated to Case Detail screen after Calendar was set for trial session (instead of remaining on Trial session detail) 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
petitions clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to a case 
2. Manually add case to trial session that has not been set 
3. Go to trial session 
4. Check "QC Complete" for the manually added case and other eligible cases 
5. Set Calendar 

**Expected Behavior**
* All cases checked as "QC Complete' should be added to trial session. 
* App should remain on Trial Session detail with updated information 

**Actual Behavior**
Only manually added case was added to trial session . 
App navigated back to  the Case Detail for the manually added case

**Screenshots**
https://drive.google.com/file/d/1-Rnku36oz7eVXtcCly9VQKH1wGgqEcPN/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
When retrieving eligible cases when setting trial session, the eligible cases buffer was not included in the limit.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
@klohman When verifying this bug fix, there seems to be some weirdness with blocked cases showing up in the sit of eligible cases for a trial session, so I would recommend ensuring that you are checking QC complete for only non-blocked cases! Meanwhile the Mraechael mob is looking into the blocked cases showing up as eligible issue!

**Comment by klohman** [comment]
Confirmed on flexion prod: 
added 10820-20 manually to Reno, NV session 01/04/21
checked QC complete for 10820-20 and 11724-20 and set calendar 
both cases were added to session (as expected)
