### ISSUE TITLE
Court: Indicator on Sealed Documents

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7525]
As the Court, in order to make sure everyone can identify sealed documents, we need a better indicator on the docket record.

## Pre-Conditions
* Sealed legacy document is on a case

## Acceptance Criteria
* Court users and parties can easily identify a sealed legacy document when looking at the docket record (both on computer and printable) 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
#### Docket Record (internal and external parties) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ef9d20d1-5501-45ed-92f4-f3b3e77e2569)

* Display sealed icon (fa-lock) in icon column for sealed document entry 
* If entry has other icon (paper, etc.), the sealed icon should take priority and be displayed 


#### Mobile Docket Record 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e04939dc-0383-476d-b494-fa59e0d2e6fa)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a589f0b-9001-4b3a-8d45-28bdaa011d7b)

* Display sealed icon (fa-lock) in icon column for sealed document entry 
* Display icon and "Document is sealed" on mobile Document Detail 


#### Printable Docket Record (internal and external parties) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8b442a3a-7040-4ab6-aa92-1955d40487b5)

* Display sealed icon (fa-lock) in icon column for sealed document entry

**Comment by klohman** [comment]
### 7199 Sealed Documents Test 

Test data 
- Case xxx-20 
    - Has legacy sealed document 
    - Private Practitioner 1 is associated 

#### 1) Internal user views docket record with legacy sealed document 
* Login as internal user 
* Go to case xxx-20 
Expected results 
- [ ] Case displays Sealed warning in header 
- [ ] Sealed docket entry displays lock icon 

#### 2a) External party views docket record with legacy sealed document 
* Login as private Practitioner 1
* Go to case xxx-20 
Expected results 
- [ ] Case displays Sealed warning in header 
- [ ] Sealed docket entry displays lock icon 

#### 2b) External party views docket record with legacy sealed document on mobile device 
* Login as private Practitioner 1
* Go to case xxx-20 
* Click document hyperlink
Expected results 
- [ ] Case displays Sealed warning in header 
- [ ] Sealed docket entry displays lock icon on docket entry 
- [ ] Mobile document detail displays “Document is sealed” message with lock icon

#### 3) Internal user views Printable Docket Record with legacy sealed document 
* Login as internal user 
* Go to case xxx-20 
* Click Printable Docket Record 
Expected results 
- [ ] Sealed docket entry displays lock icon on PDF 

#### 4) External party views Printable Docket Record with legacy sealed document 
* Login as Private Practitioner 1  
* Go to case xxx-20 
* Click Printable Docket Record 
Expected results 
- [ ] Sealed docket entry displays lock icon on PDF
