### ISSUE TITLE
BUG: Internal header - logout option becomes hidden on smaller screen before breakpoint

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7528]
**Describe the Bug**
there is a browser width where the logout button is hidden from view and not accessible
**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
all

**Who were you logged in as?**
judge buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Login as judge 
2. Change browser width 

**Expected Behavior**
All header options should be accessible to user.

**Actual Behavior**
there is a browser width where the logout button is hidden from view and not accessible before the width hits the breakpoint to change to. mobile header. 

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f646de7-bff3-4eb9-bc43-fa29e8b075dc)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
For Judges, the CSS breakpoint may be even more concerning.

At a width of 1265px, the user menu already begins to run off the screen:

![Screen Shot 2020-12-04 at 1 55 36 PM](https://user-images.githubusercontent.com/2445917/101208897-77bee600-3638-11eb-805d-b5033edaeec9.png)

It may be necessary to reconsider additional css break-points that could influence how the top menu is rendered (Dashboard, Messages, Document QC, Trial Sessions, Reports)

**Comment by kkoskelin** [comment]
For the very widest menu (for that of a Judge) on the "smallest" screen before we trigger a breakpoint, we can allow the menu selections to degrade gracefully, wrapping to second or third lines:

![Screen Shot 2020-12-07 at 4 04 49 PM](https://user-images.githubusercontent.com/2445917/101411539-c671b780-38a6-11eb-9a02-49b0711b4117.png)

**Comment by klohman** [comment]
@JessicaMarine Please see the possible fix for this above. This isn't the optimal solution as you can see.  Kris and I were talking about some other design updates we could try to the header to solve for this, but I'm not sure that effort belongs in this bug fix or should be addressed separately. Let us know if the above addresses the immediate need or if you want to explore other design updates

**Comment by JessicaMarine** [comment]
@kkoskelin @klohman This isn't pretty, but it will address the most immediate issue -- the ability to log out
