### ISSUE TITLE
BUG: Migrated cases are Calendared and Blocked

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7529]
**Describe the Bug**
Some migrated cases are showing as Calendared and also Blocked from Trial. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to migrated Calendared case (26824-14)

**Expected Behavior**
Case that is Calendared should not show Blocked  [see comment from Jessica below]

**Actual Behavior**
Some migrated cases are showing as Calendared and also Blocked from Trial. 

**Screenshots**
![Screen Shot 2020-12-02 at 4.01.06 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c1620443-ccd2-48ed-88af-c3900e438233)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Case entity did not have strict validation around blocked/automaticBlocked status when a case is calendared.
PR - ustaxcourt/ef-cms-flexion#7263

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
If a case is already set for trial (Status=Calendared) and something that would otherwise initiate a blocked status happens (i.e., due date added or pending item), the case shouldn't be blocked.  Basically, Calendared status trumps Blocked.  If case comes out of Calendared status, and it has a due date or pending item at that point, it *should* be blocked.

**Comment by klohman** [comment]
> If a case is already set for trial (Status=Calendared) and something that would otherwise initiate a blocked status happens (i.e., due date added or pending item), the case shouldn't be blocked. Basically, Calendared status trumps Blocked. If case comes out of Calendared status, and it has a due date or pending item at that point, it _should_ be blocked.

Yes, if the due date remains after the case is removed from trial, it is still blocked. When I removed the due date while it was Calendared the block was still displaying.

**Comment by klohman** [comment]
Confirmed 26824-14 on flexion prod is no longer showing Blocked while Calendared. When removed from the trial session, the Blocked label does appear and the case is blocked from being added to another session (as expected).
