### ISSUE TITLE
BUG: Migrated case w/ Calendar and Blocked- when due date is removed, case remains blocked until case is also removed from trial

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7530]
**Describe the Bug**
When a migrated case is showing Calendared and Blocked [7218](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7218), when the deadline is removed, the case still displays as Blocked. When the case is removed from the trial session, the block is removed. 

This could be resolved by the fix for 7218 since a case should never be in this state. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to case that is Calendared and Blocked (due date)
2. Remove due date

**Expected Behavior**
Blocked status should be removed when the deadline is removed. 

**Actual Behavior**
Block remains on case until case is removed from trial. 

**Screenshots**
https://drive.google.com/file/d/1C2bxPDiGTh4mmDTH2H5gwGCtAY2En1h5/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
Will be fixed by the migration run for ustaxcourt/ef-cms#7529

**Comment by klohman** [comment]
Fixed by ustaxcourt/ef-cms#7529, cases are no longer Calendared and Blocked so cannot reproduce.
