### ISSUE TITLE
BUG: Attorney with updated employer cannot be manually removed from case

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7535]
**Describe the Bug**
When trying to remove respondent counsel that has since left the IRS from a case, the counsel is remaining on the case. This is probably related to the counsel now having the employer of "Private" instead of "IRS". 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod/ court environment

**Who were you logged in as?**
docket 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 991-06 
2. Remove John Aletta 

**Expected Behavior**
Counsel should be removed from case. 

**Actual Behavior**
Counsel is not removed from case

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
Add logging to the migration we write so there is a record of what cases practitioners were removed from.

**Comment by JessicaMarine** [comment]
@mrinsin @rachaelparris Can you please confirm that you added this as a logging event so that I will be able to manually check all the ones that were changed/removed when we deploy to the Court's prod. cc: @mmarcotte

**Comment by mrinsin** [comment]
@JessicaMarine @mmarcotte This is a screenshot of some of the CloudWatch logs detailing that a practitioner with x bar number is being removed (from yesterday's Flexion prod migration):

![image](https://user-images.githubusercontent.com/20514925/103139869-b246fc00-4695-11eb-8c49-70533e4eb6b7.png)

**Comment by JessicaMarine** [comment]
PO reviewed; can move to done after UX review.

**Comment by klohman** [comment]
No changes to review for UX. Backlogging story to address attorney employer updates https://flexion.slack.com/archives/CHMLA049H/p1609163539491700?thread_ts=1609163201.491600&cid=CHMLA049H
