### ISSUE TITLE
BUG: USTC Logo display on PDF

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7536]
**Describe the Bug**
The USTC logo is displaying incorrectly on generated PDFs. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
any user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Generate any PDF (order, trial session, reports) 

**Expected Behavior**
Logo should display as
![Screen Shot 2020-12-03 at 2.23.02 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8b375316-1416-464b-ab3b-5c2627c12b8c)

**Actual Behavior**
Logo is displaying as ![Screen Shot 2020-12-03 at 2.23.40 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/99da4651-17d6-4678-8490-5d55d79e4c14)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman after further review, it appears that what we are seeing is only a matter of rendering of a PDF within an iframe on chrome when we are zoomed out.  If you load a printable docket record (for example) and click the (+) zoom feature within the pdf viewer iframe tools, you see the logo rendered clearly.

Additionally, if you download the PDF and open it in Preview or another app, I think the logo also renders correctly.  Recommending we close this.

![Screen Shot 2020-12-04 at 11 50 57 AM](https://user-images.githubusercontent.com/2445917/101196919-03c81200-3627-11eb-97b3-232d4b6d878a.png)

**Comment by klohman** [comment]
Closing based on investigation above.
