### ISSUE TITLE
BUG: legacy secondary contacts with e-access are not properly associated with cases

### ISSUE THREAD

**Issue by rachaelparris** [ustaxcourt/ef-cms#7537]
**Describe the Bug**
To check if a user is associated with a case, we only check caseRecord.userId or caseRecord.contactPrimary.contactId, but some legacy cases are migrated with a contactSecondary that should also have access to the case.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
local, all environments

**Who were you logged in as?**
petitioner who is a secondary contact on a case with e-access

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
implementing ustaxcourt/ef-cms#7534

**To Reproduce**
1. Login to flexion prod as `aprilturner@example.com` with our regular testing password.
2. View case 5201-20 - note that the case information tab is missing and the File Document button is missing.

We also created an integration test that currently fails to test this scenario. The test is in `externalUserViewsLegacySealedDocuments.test.js` on branch `secondary-contact-with-eaccess-case-association`.

**Expected Behavior**
The contact secondary with e-access should be able to view the case with full access the same as an associated user.

**Actual Behavior**
The contact secondary with e-access receives the public view of the case they are associated with.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Confirmed with aprilturner@example.com has party access to case 5201-20
