### ISSUE TITLE
BUG: Uploaded PDF names cut off on petitioner Review Your Case screen

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7538]
**Describe the Bug**
The uploaded PDF filenames are cut off and not wrapping on the Review Your Case screen for petitioners 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
petitioner1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. login as petitioner 
2. create case 
3. Complete wizard - to step 5

**Expected Behavior**
PDF filenames should display full name, wrapping if necessary. 

**Actual Behavior**
Filename is cut off. 

**Screenshots**
![Screen Shot 2020-12-04 at 11.15.35 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/199fbb48-092d-46d8-9d03-8de8dc9eb40d)![Screen Shot 2020-12-04 at 11.15.35 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e087fb67-1ec6-4627-801f-1a45ba796e26)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
I recall working on this, and making a deliberate decision to hide any overflow of the filenames.  It is only during this one multi-step process that the actual PDF filenames are shown -- that is, the filenames as they were provided at the time of upload during petition creation.  (However, if you mouse over the links, there should be a tooltip that reveals the complete filename.)

Later, they are simply given generic/placeholder names.  It might be more prudent to immediately discard the user-provided filename, because the name of the original file is discarded, never recorded in the system. We simply store pdf data as "Petition" or "STIN", etc.  This might be a solution, to embrace more generic labels on these links.

**Comment by klohman** [comment]
> I recall working on this, and making a deliberate decision to hide any overflow of the filenames. It is only during this one multi-step process that the actual PDF filenames are shown -- that is, the filenames as they were provided at the time of upload during petition creation. (However, if you mouse over the links, there should be a tooltip that reveals the complete filename.)
> 
> Later, they are simply given generic/placeholder names. It might be more prudent to immediately discard the user-provided filename, because the name of the original file is discarded, never recorded in the system. We simply store pdf data as "Petition" or "STIN", etc. This might be a solution, to embrace more generic labels on these links.

@kkoskelin I didn't remember that solution but I see now what you mean. I think your proposed solution would work - assuming that when they originally upload the PDF, the Petition and STIN upload fields still show the actual filename. I'd be fine with just displaying the generic name on the Review screen.
