### ISSUE TITLE
BUG: Spacing is off on Petitioner and Spouse Contact Info

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7539]
**Describe the Bug**
There is extra spacing under the spouse name on the Spouse Contact Info on the Review Your Case screen and the Cast Detail > Case Information > Petitioner card

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
petitioner1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Login as petitioner
2. Create case with party type = Petitioner & Deceased Spouse 
3. Submit case 
4. View Case Info > Petitioner tab 

**Expected Behavior**
Spacing between petitioner name and address should be the same as the spacing between the address and phone number. 

**Actual Behavior**
There is extra vertical space between petitioner name and address and spouse name and address / in care of.

**Screenshots**
![Screen Shot 2020-12-04 at 11.38.58 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a1fbc775-7564-4f02-8090-a697523540b8)
![Screen Shot 2020-12-04 at 11.40.35 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1ab0ba6c-c53b-4aa3-ac88-425d727770f2)![Screen Shot 2020-12-04 at 11.40.35 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ce618c9e-8589-46d5-8fde-f32786ef29ed)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by mariahkannenberg** [comment]
Closing. Has been included in UM batch 1 e2e
