### ISSUE TITLE
BUG: Public Search for Sealed Case

### ISSUE THREAD

**Issue by matthopson** [ustaxcourt/ef-cms#7541]
**Describe the Bug**

### Search by Docket Number: ###
When searching for some sealed cases by docket number, the page does not redirect to the case. In the network tab, and error is thrown. When visiting this case directly as a public user the same error is thrown:
```
The PublicCase entity was invalid. {isSealed: "'docketEntries[9].isSealed' contains an invalid value"}
isSealed: "'docketEntries[9].isSealed' contains an invalid value"
```

This is currently reproducible with the following docket numbers:
`13330-20`, `27788-11`, `13840-16`, `25867-15`
But does not on:
`120-20`

### Search by Petitioner Name: ###
When searching for a petitioner name found in one of those mentioned docket numbers, you will see a result come back - but you shouldn't for a sealed case. Again, clicking on that case will result in the previously-mentioned error.

**Business Impact/Reason for Severity**
Searching for a case by a petitioner's name may return a case that would otherwise be sealed / unavailable for public reference.

**In which environment did you see this bug?**
Flexion's prod (public)

**Who were you logged in as?**
public user (non-authed)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing

**To Reproduce**
1. Go to dawson.flexion.us
2. 
  - A) Search by docket number for case 13840-16
  - B) Search by petitioner name "Julie Gonzalez"

**Expected Behavior**
A) User should be taken to case, and see that it's sealed
B) Sealed case with petitioner Julie Gonzalez should NOT show in results (13840-16)

**Actual Behavior**
A) Case not found is displayed in results and there's an error in the console.
B) Sealed case with petitioner Julie Gonzalez (13840-16) is displayed in the search results.

**Desktop (please complete the following information):**
Desktop, MacOS

**Smartphone (please complete the following information):**
iPhone, iOS 14

**Cause of Bug, If Known**
There may be a connection with legacy sealed cases.

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@matthopson I've reviewed the docket numbers provided, and as far as I can tell, each of them behave as expected in public search when looking directly for the docket number and also when searching for the petitioner names.  can you confirm?

**Comment by matthopson** [comment]
Yup, appears to be fixed now! Thanks!
