### ISSUE TITLE
BUG: Mobile Printable Docket Record Cut Off

### ISSUE THREAD

**Issue by matthopson** [ustaxcourt/ef-cms#7543]
**Describe the Bug**
It seems the printable docket record pdf is being cut off after the first page on the mobile view.

**Business Impact/Reason for Severity**
Can only view the first page in the printable docket record on mobile

**In which environment did you see this bug?**
Flexion's Prod

**Who were you logged in as?**
irsPractitioner1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual Testing

**To Reproduce**
1. Log into app.dawson.flexion.us as irsPractitioner1 on mobile
2. Go to case 500-20
3. View the printable docket record and compare to the case detail's docket record.

**Expected Behavior**
All pages of the printable docket record should be viewable.

**Actual Behavior**
Only the first page of the printable docket record is viewable.

**Screenshots**
![Screen Shot 2020-12-04 at 2 00 27 PM](https://user-images.githubusercontent.com/1891789/101214315-13505680-3639-11eb-8fad-6432acd32156.png)

**Desktop (please complete the following information):**
Not reproducible

**Smartphone (please complete the following information):**
iPhone 6s, iOS 14
iPhone 12, iOS 14

**Cause of Bug, If Known**
unknown

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Duplicate of [7181](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7181)
