### ISSUE TITLE
BUG: Migrated Primary User Not seeing right view of case (May be related to #7236)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7544]
**Describe the Bug**
A primary user (petitioner) who was migrated, is associated with the case, but not seeing the right view.  They are seeing the public view of the case.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's mig environment

**Who were you logged in as?**
petitioner who is the primary contact on a case with e-access

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
QC'ing

**To Reproduce**
1. Login to the Court' mig as `19920B8527E8EB17D2F21BCA85C5336B@mig.ef-cms.ustaxcourt.gov` with our regular testing password.
2. Click on 25481-16 from the user's dashboard
3. Note that petitioner has public view of case.  

**Expected Behavior**
The primary petitioner with e-access should be able to view the case with full access the same as an associated user.

**Actual Behavior**
The primary petitioner with e-access receives the public view of the case they are associated with.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/8bbb0ea8-cf32-4c6f-b6c1-8a1843e5f07c)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
@JessicaMarine This has already been addressed and is in the Sprint 55 PR to the court.
https://github.com/ustaxcourt/ef-cms/pull/620/files#diff-bf3d8ee18ec57fb4082d7498abc1da71b174bc3f92e8984f407c103f6cd4932fR81
