### ISSUE TITLE
BUG: Message Table Wrapping

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7547]
**Describe the Bug**
The message table is wrapping based on width of case title which is causing the message column to be very narrow.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Jessica

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
QC'ing

**To Reproduce**

**Expected Behavior**
Message column on messaging table should be primary focus so should drive/control the column width/wrapping for other columns

**Actual Behavior**
Case title seems to be driving the column widths/wrapping

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/d4ea0f2b-171d-4490-abf0-829f513d9ccb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Confirmed corrected on flexion prod 
![Screen Shot 2020-12-09 at 8.52.41 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/69451a31-a4ea-46d9-8f01-705785be1733)
