### ISSUE TITLE
BUG: Migrated Due Dates on Calendared Cases not associated with judge on the case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7548]
**Describe the Bug**
Due to the way the cases, trial sessions, and deadlines were migrated, none of the due dates on calendared cases are showing up as being associated with the judge on the case.  Instead, they are all showing as associated with the Chief Judge.  This impacts deadlines on 332 cases: https://slack-files.com/TD3DSU09Y-F01GBLY1CUA-86911ac15f

Cases 5924-20 and 23024-19 are examples.  Judge Goeke is associated with the case because these cases are calendared for trial on his trial session, but the judge listed on the deadlines report is the "Chief Judge" for these deadlines, not Judge Goeke. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Jessica

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
Judge associated with case is associated with deadline on deadline report.

**Actual Behavior**
Chief Judge is associated with deadline on deadline report.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
ustaxcourt/ef-cms-flexion#7268

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Confirmed (spot-checked) on flexion prod 
5924-20
23024-19
13830-19
5838-20
7996-20
