### ISSUE TITLE
BUG: Scanned PDF is not displaying in viewer after PDF is created

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7552]
**Describe the Bug**
After scanning one or more batches of a document and clicking Create PDF, the generated PDF is not displaying in the PDF viewer. If the entry is saved, the PDF does display on the docket record. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
court environment 

**Who were you logged in as?**
docket 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to case 
2. Click Create - then Paper Filing 
3. Scan batch 
4. Create PDF

**Expected Behavior**
PDF generated from the scanned batches should display in the PDF preview. 

**Actual Behavior**
PDF viewer does not display PDF. 

**Screenshots**
![Screen Shot 2020-12-08 at 1.44.28 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5c61de71-3bfa-4e9e-a3ee-ae5ce7b7a7d8)

Screen recording: https://us02web.zoom.us/rec/share/OIeBUzAUYNqWwgIue69dy4G4Tc32xh_NpWV0sJsYHucKoYCg3rik9jnzDiTlIgMR.ONxejrhblA91dThS 
[NOTE: At the end of the video, Deborah clicks on the wrong "in-progress" document on the docket record; the 2-page document IS there]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
To access zoom recording, we'll need a code @JessicaMarine :
![Screen Shot 2020-12-10 at 8 34 45 AM](https://user-images.githubusercontent.com/2445917/101785646-9ef73680-3ac2-11eb-97f3-0cefd261ca96.png)

**Comment by JessicaMarine** [comment]
@kkoskelin Passcode is: `&#Jt2!^S`

**Comment by mrinsin** [comment]
The engineers tried a few ways to scan a document to reproduce this bug (however Mike tried it out on the staging environment and it DID work). @mmarcotte is going to try to sync up with Deborah to get more information, but until then we have added a 'Could not reproduce' label.

**Comment by JessicaMarine** [comment]
@mmarcotte This might be another instance of the Court's network wreaking havoc...

**Comment by mmarcotte** [comment]
@JessicaMarine -- could be. 

Where I thought the Court's network was going to be an issue was in finding the scanner. In reviewing the video, it would appear that she was able to connect to the scanner and perform the initial scan. In fact I could even hear the scanner whirring in the background audio.

However, the operation of creating the PDF does _something_ to pass the file from State to DAWSON, which generates the PDF. This handoff failed, perhaps due to some security policy, and I would need to see Deborah's Network tab or Developer console to troubleshoot further... 

FWIW, this works great for me at home (in the Test env as well as Staging). I'll ask Joe to try to get me set up with a scanner on my virtual machine?! For now, I think this troubleshooting is going to be all Court side, and it can be tabled for now for Flexion.
