### ISSUE TITLE
BUG: Blocked cases showing up in list of eligible cases for a trial session

### ISSUE THREAD

**Issue by mrinsin** [ustaxcourt/ef-cms#7557]
**Describe the Bug**
Viewing the eligible case list for a trial session displays cases that are blocked or automatic blocked

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
prod

**Who were you logged in as?**
petitionsClerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Verifying a different bug fix

**To Reproduce**
1. Go to a new, un-calendared trial session (eg. Albuquerque, NM)
2. View the case detail for some of the cases in the list of eligible cases (eg 1623-12, 13039-11)
3. Notice that these cases are blocked

**Expected Behavior**
Blocked cases must not show up in the list of eligible cases for a trial session.

**Actual Behavior**
Blocked cases show up in the list of eligible cases for a trial session.

**Screenshots**
![image](https://user-images.githubusercontent.com/20514925/101668924-08653f80-3a06-11eb-8641-8b67446e3101.png)

![image](https://user-images.githubusercontent.com/20514925/101669042-3a76a180-3a06-11eb-8b89-8a9e2d267ba1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
PR - ustaxcourt/ef-cms-flexion#7291

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Confirmed 1623-12, 13039-11 no longer showing as eligible for Albuquerque, NM. 
Also selected a case that was eligible, blocked, and confirmed it no longer displays on eligible list ( 13249-19)
