### ISSUE TITLE
BUG: "Miscellaneous" should not be added to coversheet or to document title on docket record

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7558]
**Describe the Bug**
When adding a paper-filing with event code "MISC", the word "Miscellaneous" is added to the document title on the docket entry and to the coversheet and it should not be in either place. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Go to case 
2. Add paper filing for MISC 

**Expected Behavior**
"Miscellaneous" should not be displayed as part of document title in docket entry or cover sheet. 

**Actual Behavior**
the word "Miscellaneous" is added to the document title on the docket entry

**Screenshots**
![Screen Shot 2020-12-09 at 6.20.50 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dae35fb0-ea7e-40bd-9825-ca37aa71c1b4)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
PR - ustaxcourt/ef-cms-flexion#7301

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
@klohman Do we also need to not display the word 'Miscellaneous' on this screen when adding a paper filing - 
![image](https://user-images.githubusercontent.com/20514925/101797637-1f1b9d00-3abf-11eb-92a9-7bc3aa5f67c9.png)

**Comment by klohman** [comment]
@mrinsin Yes, it should not say "Miscellaneous" as part of the document title (wherever else that may appear)

**Comment by klohman** [comment]
Confirmed on flexion prod ![Screen Shot 2020-12-11 at 1.36.42 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/94ecb586-f8ca-4684-93d5-96bd32364bf4)
