### ISSUE TITLE
BUG: MISCL code should not be displayed in document type dropdown for paper-filings

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7560]
**Describe the Bug**
The MISCL (Miscellaneous (Lodged)) document type should not display in the doc type dropdown for paper-filings. 

Currently, you can select MISCL as the doc type, but it throws an error when trying to save and serve the document. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. go to case 
2. add paper filing 
3. select MISCL as doc type 

**Expected Behavior**
MISCL should not be in the dropdown as selectable. MISCL should be the default code if someone picks "lodged" on a paper-filed doc.

**Actual Behavior**
MISCL is selectable in the dropdown and an error is received when trying to save. 

**Screenshots**
Error received ![Screen Shot 2020-12-10 at 1.32.29 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ac27ba9c-557e-4daf-99ea-e32480306a76)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
.

**Comment by sutt0n** [comment]
Reason for the bug: The `MISCL` event code was not filtered from the dropdown prior to being shown, with a scenario of `Not in dropdown`. The specific event code was added as an entity constant and filtered out in the presenter prior to being rendered in the view and a specific unit test was added to cover this test case.

**Comment by klohman** [comment]
Update looks good

![Screen Shot 2021-01-19 at 3.15.35 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8a3bacbb-0569-4585-9424-d840c7c4cfc2)


![Screen Shot 2021-01-19 at 3.15.20 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/39c8b6b8-c0ef-4c45-ae79-382842c5f759)
