### ISSUE TITLE
BUG: Legacy Served Documents not Hyperlinked on Party's View of case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7562]
**Describe the Bug**
Legacy Served documents (or documents without service information) are not hyperlinked on party's view of the case.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**
Court's prod

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
IRS attorney and Private Practitioner

**To Reproduce**
https://www.zoomgov.com/rec/share/xcJfDrPp12VOcrf10hvgQ78PXZvraaa81HJM-vEFzE9VxxKZdLKUzS59t-tmPuTY

**Expected Behavior**
All documents, except for sealed documents, should be hyperlinked

**Actual Behavior**
Some documents -- appears to be legacy served or no service info. -- are not hyperlinked.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
PR- ustaxcourt/ef-cms-flexion#7318

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Confirmed legacy served doc is hyperlinked for external party 

Logged in as legacy IRS practitioner associated with case 
![Screen Shot 2020-12-14 at 10.51.06 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b4f0d7de-b174-416e-8874-12ac78c60968)


Logged in as non-legacy private practitioner associated with the case 
![Screen Shot 2020-12-14 at 10.55.55 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e3842acf-b8f4-434d-b616-166040be8d64)


Confirmed when document is sealed, it is no longer hyperlinked to parties 
![Screen Shot 2020-12-14 at 10.58.34 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8950c7d3-c405-4d43-9f34-05671357821c)


@JessicaMarine We tested this by updating a new docket entry to isLegacyServed. Is any other testing needed before closing?

**Comment by klohman** [comment]
@JessicaMarine Added PDF to migrated docket entry 3 on this case, and is working as expected 

Logged in as legacy irs practitioner 

![Screen Shot 2020-12-14 at 12.06.56 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f5627cd1-783d-47bd-ae72-e744634b1aec)

**Comment by JessicaMarine** [comment]
@klohman sounds good.  I will close bug.
