### ISSUE TITLE
BUG: Cases without P as initial document won't allow documents to be eFiled

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7563]
**Describe the Bug**
Any case that has a different code than P for the petition is being treated as if the Petition hasn't been filed, which prevents any eFilings.

Example: 10084-16W

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's Production

**Who were you logged in as?**
IRS Attorney & Private Attorney

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

https://www.zoomgov.com/rec/share/xcJfDrPp12VOcrf10hvgQ78PXZvraaa81HJM-vEFzE9VxxKZdLKUzS59t-tmPuTY

**Expected Behavior**
All legacy/migrated cases should be treated as the Petition has been served.

**Actual Behavior**
DAWSON doesn't think the Petition has been served, so it's preventing any additional eFilings.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachaelparris** [comment]
To simplify, it was decided to allow e-filing if _any_ document in the case has been served or legacy served, rather than explicitly checking that the petition document is served.

**Comment by rachaelparris** [comment]
You should be able to login as practitioner user `872F61D587AE7BE9397AD716FBACCF82@dawson.ustaxcourt.gov` and see that a document is able to be filed in case `10084-16W` now.

**Comment by JessicaMarine** [comment]
Jessica tested -- working as expected -- closing
