### ISSUE TITLE
BUG: Legacy Petitioner: Error received when editing petitioner contact information

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7565]
**Describe the Bug**
 as a legacy petitioner ,  trying to update petitioner or spouse information on a case, app throws error and logs out. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
xroberts@example.com (legacy petitioner login) 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to case 18117-19S
2. Go to Case Info > Petitioner 
3. Click edit on petitioner contact info
4. update address
4. save 

**Expected Behavior**
Contact info should be updated and app routes back to Case info 

**Actual Behavior**
Error displays and app logs out when updating petitioner or spouse contact info

**Screenshots**

https://drive.google.com/file/d/18jdGmjZwf0Hr60LKR6F4ycR3rAVC9Srk/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
@klohman I believe this bug is no longer present? I tried to replicate on two different cases and did not see any issues.

**Comment by klohman** [comment]
@kkoskelin 

Saw this again on dev logged in as flexionustc+legacyPetitioner@gmail.com
User is associated-  interactor needs to check primary and secondary user ID instead of user id on the case (per Rachel)

**Comment by klohman** [comment]
@klohman Need to retest service email for Edit Petitioner contact info after this bug is fixed
