### ISSUE TITLE
BUG: Migrated cases Petition Confirmation showing error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7566]
**Describe the Bug**
Petition confirmation for migrated cases is displaying error. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
xroberts@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 18117-19S
2. Click Case Info tab > Print Confirmation 

**Expected Behavior**
Migrated cases should NOT display the Print Confirmation link. 

**Actual Behavior**
Petition confirmation for migrated cases is displaying error. 

**Screenshots**
![Screen Shot 2020-12-11 at 2.28.04 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cf88ed29-ea0e-44ae-be4b-8d607b8f486a)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
PO reviewed; can move to done after final UX review.
