### ISSUE TITLE
BUG: Users getting error when trying to create a case at the same time

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7569]
May be related to refactoring item https://trello.com/c/2QEF1PN7

**Describe the Bug**

Petitions clerk gets kicked out of the system when trying to create paper cases. In the logs, we are observing the error:

```
Error: docket number already exists!
    at Object.exports.createDocketNumber (/var/task/api.js:498813:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.createCaseFromPaperInteractor (/var/task/api.js:781741:24)
    at async /var/task/api.js:934037:10
    at async /var/task/api.js:933669:23
    at async exports.handle (/var/task/api.js:933444:20)
    at async /var/task/api.js:60404:22
```

**Business Impact/Reason for Severity**

We will have multiple users creating multiple cases at the same time. And this needs to work more smoothly, both for petitioners and docket clerks as new cases get created.

**In which environment did you see this bug?**

USTC Test

**Who were you logged in as?**

petitionsclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**

Petitions Clerk should get either an error message about what happened (and not kicked out), or the creation gets successfully retried

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
Looks like the error was the result of the user inputting received date prior to 2020.  Closing this issue as user error.
