### ISSUE TITLE
Exact matches: Case Search Usability

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7574]
As the Court, in order to make sure our users are having a good user experience, we need to make some usability tweaks to the search features.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

**Other exact match stories:** Orders ustaxcourt/ef-cms#7580; Opinions ustaxcourt/ef-cms#7581; Practitioners ustaxcourt/ef-cms#7582

## Pre-Conditions

**Updated AC** 

* Exact matches need to be sorted to top of results
   We define exact matches as exact words in the exact order OR  exact words in any order
* If there are no matches, inform the user
* If user elects to perform a partial match search, display exact matches then partial matches    
* We define partial match as any words in any order 
* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the petitioner name field and replace with space
* No fuzzy search
* All users are informed that sealed cases will not return in a search
* Search does not search contactprimary.secondaryname

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
### 7355 - Display matches for case search 
Updated AC
* Exact matches need to be sorted to top of results
* We define exact matches as exact words in the exact order (first) OR exact words in any order (second) 
    - For example, if Bob Jones is entered 
      - First priority - matches Bob Jones 
     - matches Jones Bob 
     - matches Bob [another word] Jones

* If there are no matches, inform the user
* If user elects to perform a partial match search, display exact matches then partial matches 
* We define partial match as any words in any order
       - For example, if Bob Jones is entered 
      - First priority - matches Bob [Something] 
     - matches Jones [Something] 

* Inform users that no advanced syntax is supported in search
* Strip all special characters in the petitioner name field and replace with space
* No fuzzy search 
   - For example: if "Rob Jones" is entered 
     - "Robert Jones" does not match

### NEW - Display matches for order search
Updated AC
* Exact keyword matches need to be sorted to top of results 
* We define exact matches as exact words in the exact order
    * For example, if innocent spouse is entered --First priority - matches innocent spouse

* If search keyword and petitioner name, matches need to be sorted as:
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in any order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in any order]

* If search keyword and petitioner name, show no results
    * Keyword exact match (exact words in exact order) + petitioner name [no exact match]
    * Keyword exact match (exact words in any order) + petitioner name [no exact match]

* If search keyword and docket number / judge / start-end date combo, matches sorted as: 
    * Keyword exact match (exact words in exact order) + docket number/judge/start-end date [exact match]
    * Keyword exact match (exact words in any order) + docket number/judge/start-end date [exact match]


* If there are no exact matches, inform the user (no partial match search) 
* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the keyword field and replace with space 
* No fuzzy search
    * For example: if "Rob Jones" is entered
        * "Robert Jones" does not match



### NEW - Display matches for opinion search
Updated AC
* Exact keyword matches need to be sorted to top of results 
* We define exact matches as exact words in the exact order
    * For example, if innocent spouse is entered --First priority - matches innocent spouse

* If search keyword and petitioner name, matches need to be sorted as:
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in any order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in any order]


* If search keyword and petitioner name, show no results
    * Keyword exact match (exact words in exact order) + petitioner name [no exact match]
    * Keyword exact match (exact words in any order) + petitioner name [no exact match]

* If search keyword and docket number / judge / opinion type/ start-end date combo, matches sorted as: 
    * Keyword exact match (exact words in exact order) + docket number/judge/opinion type/start-end date [exact match]
    * Keyword exact match (exact words in any order) + docket number/judge/opinion type/start-end date [exact match]

* If there are no exact matches, inform the user (no partial match search) 
* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the keyword field and replace with space 
* No fuzzy search
    * For example: if "Rob Jones" is entered
        * "Robert Jones" does not match


### NEW - Display matches for practitioner search 
Updated AC
* Exact matches need to be sorted to top of results 
* We define exact matches as exact words in the exact order (first) OR exact words in any order (second)
    * For example, if Bob Jones is entered
        * First priority - matches Bob Jones
    * matches Jones Bob
    * matches Bob [another word] Jones

* If there are no exact matches, inform the user 
* If there are no exact matches, user can perform a partial match search 
* We define partial match as any words in any order - For example, if Bob Jones is entered - First priority - matches Bob [Something]
    * matches Jones [Something]
* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the practitioner name field and replace with space 
* No fuzzy search
    * For example: if "Rob Jones" is entered
        * "Robert Jones" does not match

**Comment by codyseibert** [comment]
# Test Scenarios

7355 - Display matches for case search

- exact match on contactPrimary.name
  - add a case with the contactPrimary.name of "Bob Jones"
  - add a case with the contactPrimary.name of "Jones Bob"
  - add a case with the contactPrimary.name of "Bob Smith Jones"
  - add a case with the contactPrimary.name of "Bobby Jones"   // won't show up
  - add a case with the contactPrimary.name of "Bob Jonesy"   // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.secondaryName will NOT be returned in search results, field not searched by ES

- exact match on contactSecondary.name
  - add a case with the contactSecondary.name of "Bob Jones"
  - add a case with the contactSecondary.name of "Jones Bob"
  - add a case with the contactSecondary.name of "Bob Smith Jones"
  - add a case with the contactSecondary.name of "Bobby Jones" // won't show up
  - add a case with the contactSecondary.name of "Bob Jonesy" // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on caseCaption
  - add a case with the caseCaption of "Bob Jones"
  - add a case with the caseCaption of "Jones Bob"
  - add a case with the caseCaption of "Bob Smith Jones"
  - add a case with the caseCaption of "Bobby Jones" // won't show up
  - add a case with the caseCaption of "Bob Jonesy" // won't show up
  - user searches for case by "Bob Jones"
  - expect Bob Jones is first
  - expect Bob Smith Jones is second
  - expect Jones Bob is third
  - expect Bobby Jones to NOT be returned
  - expect Bob Jonesy to NOT be returned

- exact match on contactPrimary.name, contactSecondary.name, caseCaption
  - add a case with the contactPrimary.name of "Bob Jones" // 1
  - add a case with the contactSecondary.name of "Bob Jones" // 2
  - add a case with the caseCaption of "Bob Jones" // 3
  - add a case with the contactPrimary.name of "Jones Bob" // 4
  - user searches for case by "Bob Jones"
  - expect 5 results
  - expect order of results to match comments above, where "exact phrase" matches are ranked higher than entries which contain all terms out of order
 
- do a search that results in 0 records
  - user searches for case by "Unknown Petitioner Name"
  - expect 0 results
  - expect some type of alert to have a link where user can click to view more non-exact matches

### **_postponed_**
The tests below for "partial matches" include results which only match a subset of search terms. This work will be completed in another story.
- Partial match on contactPrimary.nem
  - add a case with contactPrimary.name of "Bob Evans" // 1
  - add a case with contactPrimary.name of "Jones Evans" // 2
  - add a case with contactPrimary.name of "Bob Trisha Evans" // 3
  - add a case with contactPrimary.name of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

- Partial match contactSecondary.name
  - add a case with contactSecondary.name of "Bob Evans" // 1
  - add a case with contactSecondary.name of "Jones Evans" // 2
  - add a case with contactSecondary.name of "Bob Trisha Evans" // 3
  - add a case with contactSecondary.name of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

- Partial match on caseCaption
  - add a case with caseCaption of "Bob Evans" // 1
  - add a case with caseCaption of "Jones Evans" // 2
  - add a case with caseCaption of "Bob Trisha Evans" // 3
  - add a case with caseCaption of "Bobby Evans" // do not expect them to be returned
  - user searches for "Bob Jones"
  - expect 3 results
  - expect order to match comments above

**Comment by JessicaMarine** [comment]
@klohman I have reviewed all the new proposed AC and agree with it.  @mariahkannenberg Were we still going to split these up?

**Comment by klohman** [comment]
## Design 

### Public Search screen 
* Update header on public search screen 

### Case Search Updates 

* add helper instructions for "Petitioner Name" field 
- "Advanced syntax search (*, “”, - , etc. ) is not supported at this time."

### Exact Match Query w/ matches
* execute only exact match (AND) queries
* Display results (sorted as defined in tests) 
* Display number of matches 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/21606c34-c8c0-4ffc-bea1-ffc0ada66315)

### Exact query w/ no matches
If there are no matches:  
* Display "No Matches Found" 
* Display search tips alert 

 ![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a3fb551-93fc-4825-97a7-0d09c9e069ea)

### Exact query w/ max number of search results 
If there are over the max number of search results: 
* Display 100 results 
* Display max results alert 
* Display "100 matches shown" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ed9d7654-d2a3-4aa4-9366-b2c1e4917e78)

**Comment by klohman** [comment]
## Updated language for case search instructions

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7390bd56-8d00-4965-b87b-11b7a77bb8b5)

**Comment by JessicaMarine** [comment]
PO Review:
1) When I perform an Advanced Search when logged in as an IRS Practitioner.  I get the error message that says "More than 100" but the matches shown count is 200: https://files.slack.com/files-pri/TD3DSU09Y-F01H0NVLH9V/image.png
2) Need to remove "or excluding partial matches" from the error messages when more than 100 results.
