### ISSUE TITLE
Concurrent Searches: Order and Opinion search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7583]
As a user, so that I can have a great experience searching for orders and opinions in DAWSON when many users are searching, I want the system to be optimized to support many concurrent order and opinion searches.

Pre-conditions:
* 7368 is complete
* 7374 is complete

Acceptance criteria:
 - When concurrent order and opinion searches of 500/minute; 8.3/sec are performed on the full data set:
   - searches don't time out (#7368)
   - user isn't logged out (#7374)
   - all functionality that utilized ES aren't broken (identify them all)
- If ES is showing any strain (look at Amazon dashboard to see if CPU usage is stuck at 100%), limit the total rate at which all users can make requests against any endpoints using the efcms-docket-entry index
- If search go beyond the performance threshold, user receives a message specific to the scenario and directing them to next steps.

Note:
* How do we mimic #of searches when testing? Gatling can be used; users can also search
* There are 3.7 M documents - how many are orders and opinions? **1,589,356**
* Import the Court's order and opinions into Flexion's env.
* (it appears the endpoint returns improper CORS headers when data exceeds a certain volume, causing the frontend to consider the request unauthorized).

Tasks:
 - [ ] Identify what's not working in Court's env (Mike)
 - [x] Identify possible search combinations
 - [ ] Enlist help of AWS for support (Mike)
 - [x] Import Court orders and opinions into Flexion's prod env.
 - [ ] Make a PR w/#7343 to see if it fixes the logout issue. (Story ustaxcourt/ef-cms#6491)

**Comment by cnelsonflexion** [comment]
Adding some draft messages until we understand the order of events:

**We are experiencing a high number of search requests. Please stand by.
We are experiencing a high number of search requests. Your results will appear in a few moments.
We are experiencing a high number of search requests. Please wait ## minutes/seconds and try your search again.
We are experiencing a high number of search requests. We will retry your search automatically in ## minutes/seconds/**

**Comment by klohman** [comment]
What is the length before this message appears? What actions can the user take?

**Comment by cnelsonflexion** [comment]
Given the delay is only 10 seconds, I don't think we need messaging around it if someone gets caught in the throttle.

**Comment by codyseibert** [comment]
at hour ~14:50, I ran a load test using 50 users for 10 minutes against the court/migration environment.  Attached are the results.  Overall, the ES cluster didn't seem to be fully overwhelmed (max of 90% cpu usage).
![es-migration-rate-limiter-results](https://user-images.githubusercontent.com/1868782/125847355-eef277b6-97e4-4919-81d3-3682330450e9.png)
[es-migration-rate-limiter-results.pdf](https://github.com/flexion/ef-cms/files/6825835/es-migration-rate-limiter-results.pdf)

**Comment by codyseibert** [comment]
Some of the 400 errors are related to this error where number of pages is not defined because some legacy docket entries do not have s3 documents associated with them.  We will need to add a fix for this. ![Screen Shot 2021-07-15 at 3 48 49 PM](https://user-images.githubusercontent.com/1868782/125848614-6dc55f0e-3ee9-436b-acfa-4c21ccd555cd.png)
