### ISSUE TITLE
Concurrent Searches: Opinion search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7584]
As a user, so that I can have a great experience searching opinions in DAWSON, I want the system to be optimized to support many concurrent searches.

Pre-conditions:

Acceptance criteria:
 - When concurrent opinion searches of 1000 [what is target #?] users are performed on the full data set:
   - searches don't time out (identify queries)
   - all functionality that utilized ES aren't broken (identify them all)
- If ES is showing any strain, limit the rate at which users can make requests against any endpoints using the efcms-docket-entry index
- If search go beyond the performance threshold, user receives a message specific to the scenario and directing them to next steps.

Note:
* How do we mimic #of searches when testing? Gatling can be used; users can also search
* There are 3.7 M documents - how many are orders and opinions?
* Import the Court's order and opinions into Flexion's env.
* Order of operations - prioritize all stories, identify the queries, test them in the Court's env to confirm what's not working to confirm we're optimizing correctly.
* (it appears the endpoint returns improper CORS headers when data exceeds a certain volume, causing the frontend to consider the request unauthorized).

Tasks:
 - [ ] Identify what's not working in Court's env (Mike)
 - [ ] Identify possible search combinations
 - [ ] Enlist help of AWS for support (Mike)
 - [ ] Import Court orders and opinions into Flexion's prod env.
 - [ ] Make a PR w/#7343 to see if it fixes the logout issue. (Story ustaxcourt/ef-cms#6491)

**Comment by JessicaMarine** [comment]
Added to ustaxcourt/ef-cms#7583
