### ISSUE TITLE
Opinion Search: AND keyword search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7585]
As a Court employee, in order to locate the most relevant documents, I need to have more control over how my keyword search is executed.

## Acceptance Criteria
* User is able to search using multiple keywords/phrases using the equivalent of boolean operator “AND” and retrieve results containing BOTH keywords/phrases (including exact match) 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by mariahkannenberg** [comment]
Needs More Info - The story linked in AC is for exact match. I think this may be the wrong story. Need clarification.

**Comment by cholly75** [comment]
@mariahkannenberg good catch, I've edited this story to revise the AC and restrict it to the AND keyword, like we did for Orders - I'll enter a similar but separate story for the OR operator.

**Comment by cholly75** [comment]
Opinion 1:
- title: `Opinion 1 welcome to flavortown`
- contents: `Opinion 1 welcome to flavortown`

Opinion 2:
- title: `Opinion 2
- contents: `Opinion 2 welcome to flavortown`

Opinion 3:
- title: `Opinion 3 welcome to flavortown`
- contents: `Opinion 3 lorem ipsum`


Test Cases:

`welcome + flavortown` in document title and contents: returns 1, 3

`welcome + flavortown` in document title only: returns 1, 2, 3

`welcome + flavortown` in contents only: returns 1, 2, 3

`"welcome to flavortown" + opinion` in document title and contents: returns 1, 2, 3

`"welcome to flavortown" + opinion` in document title only: returns 1, 2, 3

`"welcome to flavortown" + opinion` in document contents only: returns 1, 2, 3

`"welcome to flavortown" + "opinion 1"` in document title and contents: returns 1

`"welcome to flavortown" + "opinion 3 welcome"` in document title only: returns 3

`"opinion 3" + "lorem ipsum"` in contents only: returns 3

`flavortown welcome + "welcome to"` in document title and contents: returns 1, 2, 3

`flavortown welcome + "opinion 3"` in document title only: returns 3

`ipsum lorem + "opinion 3"` in contents only: returns 3

**Comment by TomElliottFlexion** [comment]
Screenshots to illustrate the above:
NOTE: following Kris's example, I made a _local_  change to reveal the complete document title (instead of just document type e.g. "T.C. Opinion") so we could see which ones were being returned in the searches.![Screen Shot 2021-09-02 at 1.28.48 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/89a9d085-59fc-443e-a07c-85754963a201)![Screen Shot 2021-09-02 at 1.27.43 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/a45743e3-40b5-43e5-897e-5abbe2b44aeb)![Screen Shot 2021-09-02 at 1.36.56 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/d2cfc017-d2cb-40e1-ae96-d6d853701be4)![Screen Shot 2021-09-02 at 1.38.14 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/1f9626d6-a6b4-41a5-b634-aed7c14d9d88)

**Comment by TomElliottFlexion** [comment]
![Screen Shot 2021-09-02 at 1.38.40 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/6d34138b-f9f2-4a99-9ff6-5cd3956ddaae)
![Screen Shot 2021-09-02 at 1.39.04 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/1bdb85b6-589a-4330-a8ac-b5b00c20e67c)
![Screen Shot 2021-09-02 at 1.39.31 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/539dd3e6-f765-4893-abca-727ea9250749)
![Screen Shot 2021-09-02 at 1.39.59 PM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/74536466-3677-4eb1-966a-7dc0c781ece7)

**Comment by TomElliottFlexion** [comment]
No code changes
