### ISSUE TITLE
Order and Opinion - Coming Soon

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7586]
As a user, so that I am aware that all order and opinion search are not functional (but coming soon), I need to be made aware.

## Acceptance Criteria
* Public and practitioners are aware that order and opinion search is coming soon
* Public and practitioners are able to see the order and opinion tabs, but not the pages, and this are not able to perform a search.
* Public is not able to access the order and opinion search API
* Today's opinions still works after changes are made

## Notes
* Leave Tabs
* Display tab, but don't make it clickable. 
* Leave as is for internal users

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [x] Does this work implement new authentication or security controls?
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
![Screen Shot 2020-12-21 at 10.25.20 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4a7b92cc-4e3c-4403-b28f-6d3452a98ad3)
