### ISSUE TITLE
BUG: Petitioner names with special characters (') are not displaying in search results

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7588]
**Describe the Bug**
Petitioner names with special characters (') are not displaying in case search results. When searching for name D'Angelo, the apostrophe is stripped out during the search, and is not being matched with the petitioner name "D'Angelo" 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion 

**Who were you logged in as?**
public 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
integration test found this 

**To Reproduce**
1. Go to public search 
2. Search for a petitioner name with apostrophe 

**Expected Behavior**
Petitioner name with apostrophe should come back as a match 

**Actual Behavior**
Petitioner name with special characters (') is not coming back as a match. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
@JessicaMarine  is this bug a part of PR 58? (Asking because we don't see a PR label)

**Comment by JessicaMarine** [comment]
@mrinsin  yes, I just hadn't added the lane yet.

**Comment by klohman** [comment]
Searched for D'Angelo and received expected results. Created a case for Mary O'Reilly and searched O'Reilly and got back results.
