### ISSUE TITLE
BUG: Some New trial sessions are throwing an error

### ISSUE THREAD

**Issue by rachaelparris** [ustaxcourt/ef-cms#7589]
**Describe the Bug**
Some new trial sessions are throwing an error.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Clicking on a new trial session

**To Reproduce**
1. Visit https://app.dawson.flexion.us/trial-session-detail/0adbf66e-6f5c-4f92-883f-7afcde53040c

**Expected Behavior**
Should see the new trial session

**Actual Behavior**
An error is thrown `Provided list of item keys contains duplicates`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by sutt0n** [comment]
Unable to reproduce this error with user flows; discussed with @matthopson and @rachaelparris and concluded this to be bad data _only_ in the Flexion environments from a previously migration that has been since fixed. Closing per @klohman! 😄
