### ISSUE TITLE
BUG: View Full PDF is opening in same window

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7593]
**Describe the Bug**
As an internal user, when I click on "View Full PDF", it is now opening that PDF in the same window.  It should open the full PDF in a new tab.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod; replicated in Flexion's prod

**Who were you logged in as?**
Internal User

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 10836-19 (or any case that has a PDF)
2. Click a document hyperlink to route to the Document View
3. Click "View Full PDF" 
4. Note that the PDF opens in the same window, not a new tab 

**Expected Behavior**
When you click on "View Full PDF" the PDF opens in a new window

**Actual Behavior**
When you click on "View Full PDF" it is opening in the same window.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The action that determines how to open the PDF was not defaulting to open in a new tab. - ustaxcourt/ef-cms-flexion#7431 (Matt, Mrinalini, Rae)

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
@mrinsin @klohman When I try to click on "View Full PDF" for a document attached to a message, nothing happens.  Can we ensure that everywhere an internal user has that "View Full PDF" option, it is working.

**Comment by klohman** [comment]
@mrinsin I checked the View Full PDF links on Document View, Drafts and Correspondence and they are all working as expected. The link on the message detail seems to be the only issue

**Comment by mrinsin** [comment]
@JessicaMarine the message detail link update is on Flexion's prod!
