### ISSUE TITLE
Display PDFs consistently across the application

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7595]
As a user of the system, I need to be able to view PDFs consistently across devices so that I can complete my workflow without interruption.

## Pre-Conditions
none
## Acceptance Criteria
* We have established and documented all scenarios for displaying PDFs across the system, user and device

* PDF links accessed by an internal user only open consistently on all devices
   - View Full PDF (Correspondence)
   - View Full PDF (Drafts)
   - View Full PDF (Document View)
   - View Full PDF (Message)
   - Trial Session Planning Report
   - Case Inventory Report
   - Pending Report (Case)
   - Trial Calendar
   - Print Paper Service

* PDF links accessed by parties and internal users open in consistently on all devices
  - Print (Petition) Confirmation
  - Printable Docket Record (Parties/internal)

* PDF links accessed by parties only open in consistently on all devices
  -  Filings and Proceedings (Parties)

* PDF links accessed by the public open consistently on all devices
  - Printable Docket Record (Public)
  - Todays Opinions
  - Todays Orders
  - Filings and Proceedings (Public)

* PDF links accessed by all users for document search open consistently on all devices.
   - Order Search
   - Opinion Search

Per Judge Buch: He'd like to right-click and be able to open PDFs.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by codyseibert** [comment]
another pdf to consider will be the practitioner case list pdf implemented in ustaxcourt/ef-cms#7777
