### ISSUE TITLE
Changes Needed for In-Person Trial Sessions

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7604]
When the Court returns to in-person trial sessions, we need to make sure everything is updated to account for new policies/procedures adopted during the pandemic.

## Acceptance Criteria
* Update SPTN content

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
## Add Trial Session form 

**In Person**
if “In Person” is selected, display the following fields: 
* Add Chambers phone number (new field)

**Chambers phone number**
* Is optional to create session 
* Is required to set the calendar 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/27112fb3-aa02-4fdd-9640-f652f44526e6)

##  Trial Session Detail  

**Courthouse Location card**
if “In Person” is selected, display the following fields: 
* Display “Courthouse Location” as card title 
* Display Address 
* Display Chambers Phone number 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f7343a4e-40c6-405b-844b-3e1828abcc73)

**Comment by cholly75** [comment]
This was done in August 2021.
