### ISSUE TITLE
BUG: [Date] field not displaying in docket entry for Court-Issued documents

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7606]
**Describe the Bug**
The date field entered when adding specific court-issued documents is not displaying on the docket entry. 

Is impacting at least these event codes:
OAPF
OAP
OF
OFFX 
OFWD
OODS
OPFX
OPX
OPFX
ORAP
OROP
OSCP
NTD

**Business Impact/Reason for Severity**

**In which environment did you see this bug?** 
prod , flexion prod

**Who were you logged in as?**
petitions clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to case 
2. Upload PDF + sign 
2. Add Docket entry for event code listed above

**Expected Behavior**
Date entered in date field should display as part of the document title in docket entry 

**Actual Behavior**
Date is missing from docket entry. 

**Screenshots**

![Screen Shot 2020-12-29 at 1.54.36 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a0cd31f6-6bdd-4fff-a858-828ecc92e6d8)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
ustaxcourt/ef-cms-flexion#717

Form dates were not being correctly computed when docket entry is saved and/or served. 

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
Jessica tested each of the affected document types in the Court's staging env. and everying posted to the docket record as expected:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/539ad634-1683-4c0e-931d-200954341c9c)
