### ISSUE TITLE
BUG: Signature is turning vertical on save

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7607]
**Describe the Bug**
When a Docket Clerk signed a Proposed Stipulated Decision, upon save, the signature turned vertical:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/5b6f0a67-9379-4678-9e14-17739762f02d)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's Prod

**Who were you logged in as?**
Docket Clerk (Craig Taublib)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
Signature stays where it is applied

**Actual Behavior**
Signature turned vertical on save. ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/34abf669-f39d-4cb6-9cc1-63fe466ea51d)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
UX - fix looks good
![Screen Shot 2021-01-05 at 1.59.22 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/edd703e9-6d77-4521-ba4c-31a2d640da1a)

**Comment by JessicaMarine** [comment]
PO unable to test since fix has been implemented.  Looks like a PDF that previously had the same issue can be signed correctly. Moving to done!
