### ISSUE TITLE
BUG: Scrolling on modal (iPad)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7609]
**Describe the Bug**
When Judge Buch was trying to send a message using an iPad, the whole forward message modal did not appear in the window and there was no way to scroll to hit Send.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court' prod

**Who were you logged in as?**
Judge Buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
Ability to hit Send on messaging modal

**Actual Behavior**
Cannot see Send button on message modal on iPad.
![Image from iOS (1).jpg](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/423e5c1d-b2a2-42dc-a21b-82d991513167)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
USWDS has a new modal component. Should we explore using that as part of the solution to this bug if it is not as straightforward as simply adding scrolling to the modal?
