### ISSUE TITLE
BUG: Completed messages still showing in Inbox

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7610]
**Describe the Bug**
Multiple users have reported a completed message still showing in their inbox in the Court's prod environment:

**(1) Docket # 25515-18; user is Patty Hodge.  Message was completed by Darlene Counts in Docket, but is still showing in Patty's inbox**
![image](https://user-images.githubusercontent.com/40871081/103379817-f2064d00-4ab4-11eb-9144-5d3452981c9b.png)

**(2) Docket # 23915-18; user Lanette Hushon.  Lanette completed the message but it is still showing in her inbox over 24 hours**
![image (2).png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/c7cc23ea-51fa-4e61-ae51-62fa8f154854)
 ![image (1).png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/79524a4c-a49c-4938-bcc8-96fc75043ed9)later.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
Message will clear from everyone's inbox when completed by any Court user.

**Actual Behavior**
Completed message still showing in user's inbox.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mmarcotte** [comment]
Here are the four messages in the system for that case:

```json
{
  "attachments": [
    {
      "documentId": "cd7e842f-2de1-4767-8c05-98b8e7e37d8b"
    }
  ],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609269771.843001,
  "caseStatus": "Jurisdiction Retained",
  "caseTitle": "Marc Levin & Cindy Levin",
  "completedAt": "2020-12-29T17:24:23.920Z",
  "completedBy": "Darlene Counts",
  "completedBySection": "docket",
  "completedByUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7",
  "completedMessage": "Served",
  "createdAt": "2020-12-29T17:24:07.269Z",
  "docketNumber": "25515-18",
  "docketNumberWithSuffix": "25515-18",
  "entityName": "Message",
  "from": "Darlene Counts",
  "fromSection": "docket",
  "fromUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7",
  "gsi1pk": "message|df13c74c-6037-4360-9eab-7babeec9d89f",
  "isCompleted": true,
  "isRead": true,
  "isRepliedTo": false,
  "message": "Served",
  "messageId": "33e17195-7517-4ebe-a6b8-acc174ed4348",
  "parentMessageId": "df13c74c-6037-4360-9eab-7babeec9d89f",
  "pk": "case|25515-18",
  "sk": "message|33e17195-7517-4ebe-a6b8-acc174ed4348",
  "subject": "Order",
  "to": "Patricia Hodge",
  "toSection": "weilersChambers",
  "toUserId": "a55ca8b5-4c9c-46a4-a60e-ee0480e5888f"
}
```

```json
{
  "attachments": [
    {
      "documentId": "cd7e842f-2de1-4767-8c05-98b8e7e37d8b"
    }
  ],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609262647.371001,
  "caseStatus": "Jurisdiction Retained",
  "caseTitle": "Marc Levin & Cindy Levin",
  "createdAt": "2020-12-28T17:46:14.751Z",
  "docketNumber": "25515-18",
  "docketNumberWithSuffix": "25515-18",
  "entityName": "Message",
  "from": "Patricia Hodge",
  "fromSection": "weilersChambers",
  "fromUserId": "a55ca8b5-4c9c-46a4-a60e-ee0480e5888f",
  "gsi1pk": "message|df13c74c-6037-4360-9eab-7babeec9d89f",
  "isCompleted": false,
  "isRead": true,
  "isRepliedTo": true,
  "message": "Order is now attached.",
  "messageId": "979c4524-0831-45f5-8b1d-f3cbf521364a",
  "parentMessageId": "df13c74c-6037-4360-9eab-7babeec9d89f",
  "pk": "case|25515-18",
  "sk": "message|979c4524-0831-45f5-8b1d-f3cbf521364a",
  "subject": "Order",
  "to": "Darlene Counts",
  "toSection": "docket",
  "toUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7"
}
```

```json
{
  "attachments": [],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609262506.767001,
  "caseStatus": "Jurisdiction Retained",
  "caseTitle": "Marc Levin & Cindy Levin",
  "createdAt": "2020-12-28T16:34:10.138Z",
  "docketNumber": "25515-18",
  "docketNumberWithSuffix": "25515-18",
  "entityName": "Message",
  "from": "Patricia Hodge",
  "fromSection": "weilersChambers",
  "fromUserId": "a55ca8b5-4c9c-46a4-a60e-ee0480e5888f",
  "gsi1pk": "message|df13c74c-6037-4360-9eab-7babeec9d89f",
  "isCompleted": false,
  "isRead": true,
  "isRepliedTo": true,
  "message": "Please process.  Thank you.",
  "messageId": "df13c74c-6037-4360-9eab-7babeec9d89f",
  "parentMessageId": "df13c74c-6037-4360-9eab-7babeec9d89f",
  "pk": "case|25515-18",
  "sk": "message|df13c74c-6037-4360-9eab-7babeec9d89f",
  "subject": "Order",
  "to": "Darlene Counts",
  "toSection": "docket",
  "toUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7"
}
```

```json
{
  "attachments": [],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609262506.734001,
  "caseStatus": "Jurisdiction Retained",
  "caseTitle": "Marc Levin & Cindy Levin",
  "createdAt": "2020-12-28T16:57:34.952Z",
  "docketNumber": "25515-18",
  "docketNumberWithSuffix": "25515-18",
  "entityName": "Message",
  "from": "Darlene Counts",
  "fromSection": "docket",
  "fromUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7",
  "gsi1pk": "message|df13c74c-6037-4360-9eab-7babeec9d89f",
  "isCompleted": false,
  "isRead": true,
  "isRepliedTo": true,
  "message": "There is no order attached.",
  "messageId": "e20b4e06-98b9-477c-b8c8-cb6ac76bdb17",
  "parentMessageId": "df13c74c-6037-4360-9eab-7babeec9d89f",
  "pk": "case|25515-18",
  "sk": "message|e20b4e06-98b9-477c-b8c8-cb6ac76bdb17",
  "subject": "Order",
  "to": "Patricia Hodge",
  "toSection": "weilersChambers",
  "toUserId": "a55ca8b5-4c9c-46a4-a60e-ee0480e5888f"
}
```

**Comment by mmarcotte** [comment]
Here are more messages from 23915-18

```json
{
  "attachments": [
    {
      "documentId": "d5b6cc32-8adb-4c8e-a317-43ced0675308"
    }
  ],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609256239.187001,
  "caseStatus": "Closed",
  "caseTitle": "Daniel Shalom & Betty Sharafi-Shalom",
  "completedAt": "2020-12-28T16:55:48.516Z",
  "completedBy": "Lanette Hushon",
  "completedBySection": "kerrigansChambers",
  "completedByUserId": "6a734ea0-fa60-4371-a6b8-8cb7a68b3fbc",
  "createdAt": "2020-12-28T15:20:24.320Z",
  "docketNumber": "23915-18",
  "docketNumberWithSuffix": "23915-18",
  "entityName": "Message",
  "from": "Kerrigan",
  "fromSection": "kerrigansChambers",
  "fromUserId": "3adacd2c-d266-4041-9698-b8fe431bbf7c",
  "gsi1pk": "message|a386c728-9d57-43b3-b577-70f31e7f545d",
  "isCompleted": true,
  "isRead": true,
  "isRepliedTo": false,
  "message": "please double check me.  Thanks",
  "messageId": "a386c728-9d57-43b3-b577-70f31e7f545d",
  "parentMessageId": "a386c728-9d57-43b3-b577-70f31e7f545d",
  "pk": "case|23915-18",
  "sk": "message|a386c728-9d57-43b3-b577-70f31e7f545d",
  "subject": "PROPOSED STIPULATED DECISION by Resp. & Petrs. Daniel Shalom & Betty Sharafi-Shalom",
  "to": "Lanette Hushon",
  "toSection": "kerrigansChambers",
  "toUserId": "6a734ea0-fa60-4371-a6b8-8cb7a68b3fbc"
}
```

```json
{
  "attachments": [
    {
      "documentId": "f1419cea-bf25-45b4-a7db-4e0d9009e2b1"
    }
  ],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609256818.240001,
  "caseStatus": "Closed",
  "caseTitle": "Daniel Shalom & Betty Sharafi-Shalom",
  "createdAt": "2020-12-28T16:55:28.931Z",
  "docketNumber": "23915-18",
  "docketNumberWithSuffix": "23915-18",
  "entityName": "Message",
  "from": "Lanette Hushon",
  "fromSection": "kerrigansChambers",
  "fromUserId": "6a734ea0-fa60-4371-a6b8-8cb7a68b3fbc",
  "gsi1pk": "message|ac1c2069-178a-4c55-b33a-f743a7fe60d2",
  "isCompleted": false,
  "isRead": true,
  "isRepliedTo": true,
  "message": "SD has been signed -- thanks!",
  "messageId": "ac1c2069-178a-4c55-b33a-f743a7fe60d2",
  "parentMessageId": "ac1c2069-178a-4c55-b33a-f743a7fe60d2",
  "pk": "case|23915-18",
  "sk": "message|ac1c2069-178a-4c55-b33a-f743a7fe60d2",
  "subject": "Stipulated Decision",
  "to": "Darlene Counts",
  "toSection": "docket",
  "toUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7"
}
```

```json
{
  "attachments": [
    {
      "documentId": "f1419cea-bf25-45b4-a7db-4e0d9009e2b1"
    }
  ],
  "aws:rep:deleting": false,
  "aws:rep:updateregion": "us-east-1",
  "aws:rep:updatetime": 1609256827.274001,
  "caseStatus": "Closed",
  "caseTitle": "Daniel Shalom & Betty Sharafi-Shalom",
  "completedAt": "2020-12-29T15:47:06.740Z",
  "completedBy": "Darlene Counts",
  "completedBySection": "docket",
  "completedByUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7",
  "completedMessage": "Served",
  "createdAt": "2020-12-29T15:46:58.007Z",
  "docketNumber": "23915-18",
  "docketNumberWithSuffix": "23915-18",
  "entityName": "Message",
  "from": "Darlene Counts",
  "fromSection": "docket",
  "fromUserId": "752d4ce4-ee52-44a2-99d5-68841efaaef7",
  "gsi1pk": "message|ac1c2069-178a-4c55-b33a-f743a7fe60d2",
  "isCompleted": true,
  "isRead": false,
  "isRepliedTo": true,
  "message": "Served",
  "messageId": "cea2d39d-ee61-445d-b262-36f406c3d022",
  "parentMessageId": "ac1c2069-178a-4c55-b33a-f743a7fe60d2",
  "pk": "case|23915-18",
  "sk": "message|cea2d39d-ee61-445d-b262-36f406c3d022",
  "subject": "Stipulated Decision",
  "to": "Lanette Hushon",
  "toSection": "kerrigansChambers",
  "toUserId": "6a734ea0-fa60-4371-a6b8-8cb7a68b3fbc"
}
```

**Comment by JessicaMarine** [comment]
@mmarcotte One more: Docket No. 11240-20S

**Comment by JessicaMarine** [comment]
Also reported in:
7744-20
1039-20
10327-20S
714-20W
19654-19L
2644-20

**Comment by mariahkannenberg** [comment]
Jessica's Observation
Docket clerk replies to a message and then completes it (they stay on message page)
The message gets hung up in the inbox of the recipient.

**Comment by klohman** [comment]
## Tests (Drafts) 
#### User completes message that is in their Inbox 
* Login as adc1 
* Go to case 101-21
* Send message with document attached to docketclerk1
* Login as docketclerk1
* Go to case 101-21
* Complete message from adc1
Expected results 
- [ ] Message does not display in docketclerk1 Inbox 
- [ ] Message does not display in Docket Section Inbox 
- [ ] Message displays in Completed box for docketclerk1
- [ ] Message detail screen displays as “Completed” 
- [ ] Message displays in Case Detail > Case Messages > Completed


#### User completes message that is in another user’s Inbox 
* Login as docket clerk1
* Go to case 101-21
* Send message with document attached to petitions clerk1
* Login as judge Buch 
* Go to case 101-21
* Complete message from docket clerk 1 
* Login as petitions clerk 1 
Expected results 
- [ ] Message does not display in petitions clerk1’s Inbox 
- [ ] Message does not display in Petitions Section Inbox 
- [ ] Message displays in Complete box for Judge Buch 
- [ ] Message detail screen displays as “Completed” 
- [ ] Message displays in Case Detail > Case Messages > Completed

**Comment by rachaelparris** [comment]
We added some of the data to Flexion's prod to verify that the completed messages do not show up in the inbox. The message detail is [here](https://app.dawson.flexion.us/messages/13341-20/message-detail/df13c74c-6037-4360-9eab-7babeec9d89f). We also verified that those messages are no longer in the petitions or docket inboxes.
