### ISSUE TITLE
BUG: Updating Address not removing 2nd line

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7611]
**Describe the Bug**
In 1232-20, I updated the address to change the first line and remove the second line in its entirety for both petitioners.  On save, the first line retained the change.  The second line didn't delete -- the apt information stayed -- on the contact info on the Case Info. tab.  The Notice of Change of Address picked up the change correctly for both petitioners.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod; able to reproduce in Flexion's prod

**Who were you logged in as?**.
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 1232-20.
2. Change Ps' addresses by changing line 1 and deleting line 2 (apartment info)
3. Save.
4. Note that the addresses on the Case Info. tab updated line 1, but retained line 2
5. Note that Notice of Change of Address is correct.

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by sutt0n** [comment]
Reason: We were updating contact information based on a merged object of old information and new information; however, the new information associated with `Address 2` (including `Address 3` and `Title`) was not being sent over the wire via the API call from the UI since it was an empty value. In order to fix this, a default value for these optional fields are used in-case they're `undefined`.

**Comment by klohman** [comment]
UX review on dev - ready for prod deploy and PO review
