### ISSUE TITLE
Other Petitioners: Edit Contact Info.

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7612]
As the Court, in order to make sure we always have current information for a party, we need the ability to change contact information for other petitioner(s).

## Acceptance Criteria
- Other Petitioner(s) can edit their own address and phone number (See ustaxcourt/ef-cms#6549) 
- Docket can edit address and/or phone number of other petitioner(s) (See ustaxcourt/ef-cms#6789)
- Counsel of the party can edit address and/or phone number of other petitioner(s)
- When the address and/or phone of an other petitioner is edited, a Notice of Change of Address/Phone/both is generated, added to the docket record, and served (See ustaxcourt/ef-cms#6886)
- Other petitioner(s) can edit their email address (See ustaxcourt/ef-cms#6890)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by mark-meyer** [comment]
Currently users like Intervenors in the `otherFilers` and `otherPetitioner` lists can only see the public version of cases even when the case appears in their cases once logged in. Intervenors and otherPetitioners who are associated with the case should be able to view the full case.

**Comment by klohman** [comment]
## Test cases 

#### 1) Petitioner / counsel / docket edits petitioner contact information - [see test 9 in Test Matrix ](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)

#### 2) Petitioner updates their email  - [see test 12 in Test Matrix ](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)

**Comment by klohman** [comment]
7458 UX Review 

- Other petitioner updating email is not sending the verify email to the new email 
    - Steps to recreate 
        - Add email to other petitioner + activate email 
        - Login as other petitioner 
        - Update email 
        - Should receive a verify email 


**UPDATE** - Confirmed working on dev

**Comment by JessicaMarine** [comment]
@TomElliottFlexion  (as point person)
PO Review:
*  I think something is not working correctly if a practitioner changes a person's address.  On `mig` in 180-20, I have one person getting paper service.  Logged in as practitioner and changed contact info. for several of the parties.  It updated the info, and generated the Notices of Change of Address/Phone, but did not route that item to Docket's QC for paper service.
* Why is USA listed in the address on the Notice of Change of Address, but nowhere else in the app?
