### ISSUE TITLE
BUG: QC items not displaying in Judge's QC box

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7615]
**Describe the Bug**
Multiple judges have reported items that have been filed, but not yet QC'd, are missing from their QC box.  It appears that only cases with the status "Calendared" are showing up in the QC box.

Judge Toro reports -- 17513-17 entry ustaxcourt/ef-cms#6510
Judge Goeke reports --6225-16 (Petr. Reply Brief on 12/30), 6488-18 (a proposed decision), and 8056-19 (Status Report).

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
All items waiting to be QC'd by Docket should display in the appropriate Judge's QC box

**Actual Behavior**
Items are showing on the docket record as waiting to be QC'd but are not showing in the Judge's QC box

From Docket Number 17513-17 (Judge Toro -- Assigned-Case):

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/d1028fe7-db27-4857-afad-cd1541847580)

Judge Toro's QC box:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/dd8aa4e9-2007-4ec1-be78-dad6fdc89fe6)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Pr- ustaxcourt/ef-cms-flexion#7475

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Tested on flexion prod with Judge Buch - e-filing documents for both a Calendared case and Assigned-Case associated with Judge Buch

![Screen Shot 2021-01-06 at 12.28.20 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/135513fe-23db-42e2-9661-f9744da7c1ad)
