### ISSUE TITLE
BUG: Edit Docket Entry: Unable to select previous document when doc type is updated to Reply

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7619]
**May also related to [7510](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7510)**

**Describe the Bug**
When editing a docket entry, if you update the document type to "Reply", you cannot select any previous documents from the "Which document are you replying to?" dropdown. Document are visible in the dropdown, but when you select one, it is not showing in the UI. 

Confirmed this bug is applicable to all Nonstandard A document types. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
court / flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to case 
2. Click Edit for externally or paper-filed document type 
3. Update doc type to "Reply" 
4. Select a previous document in the "Which document are you replying to?" dropdown

**Expected Behavior**
Selected document should populate in the dropdown. 

**Actual Behavior**
No document is selected in dropdown. 

**Screenshots**
https://drive.google.com/file/d/1Z3-tqHbilv3P6Qhcjg2kykJRo1NvfPE2/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
### 7473 tests 

#### 1) Docket clerk edits paper-filed docket entry and updates doc type to nonstandard A type 
* Login as docket clerk 
* Go to case 
* Add Paper filing [ any document type other than nonstandard a]
* Save and Serve 
* Click edit link for docket entry 
* Update document type to nonstandard A
    * Redacted
    * Notice of No Objection
    * Notice of Objection
    * Reply
    * Sur-Reply
    * No Objection 
    * Objection
    * Opposition
    * Response Brief in Support
    * Memorandum in Support
* Select previous document from dropdown 
* Save 
Expected results 
- [ ] On select of doc type, previousDocument dropdown displays 
- [ ] Selected document displays in previousDocument dropdown
- [ ] on save, docket entry is updated to reflect selected doc type and previousDocument

#### 2) Docket clerk edits e-filed docket entry and updates doc type to nonstandard A type 
* Login as party
* Go to case 
* E-file document [ any document type other than nonstandard a]
* Submit
* Login as docket clerk
* Go to case
* Click edit link for docket entry 
* Update document type to nonstandard A
    * Redacted
    * Notice of No Objection
    * Notice of Objection
    * Reply
    * Sur-Reply
    * No Objection 
    * Objection
    * Opposition
    * Response Brief in Support
    * Memorandum in Support
* Select previous document from dropdown 
* Save 
Expected results 
- [ ] On select of doc type, previousDocument dropdown displays 
- [ ] Selected document displays in previousDocument dropdown
- [ ] on save, docket entry is updated to reflect selected doc type and previousDocument

**Comment by sutt0n** [comment]
Reason: The previous document wasn't being set correctly on the form when a file was selected, and upon saving, it did not update the respective docket entry with the document as an object. It was attached to the docket entry, and unit tests were written.
