### ISSUE TITLE
Docket Clerk: Docket entry preview

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7622]
As a Docket Clerk, to ensure the correct docket entry language is going to be added to the docket record, I need to see the full preview.

## Pre-Conditions
* Docket Clerk is adding a document (paper filed or Court-issued) to the Docket record.

## Acceptance Criteria
* Docket Clerk can see the docket entry preview in its entirety
* Ensure the preview is present on all "Add Docket Entry" screens
* Consider co-locating docket entry preview with the form (UX feedback)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by rosiehsmith** [comment]
Somewhat related, in the document view, a very long description will lead the preview to bump down the pdf outside of the page like so:

![image1.png](https://images.zenhubusercontent.com/602ac5596b87084099686a43/49dafb60-0d5d-457a-95cf-8c026fe6beab)![image2.png](https://images.zenhubusercontent.com/602ac5596b87084099686a43/a3729aad-bbfd-44b4-a82d-433871261f0c)
