### ISSUE TITLE
BUG: eFiled documents not getting cover sheet; page count is 0

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7625]
**Describe the Bug**
There are several documents that have been eFiled that did not get a cover sheet and the docket entry shows 0 as the page count. The issue is compounded when it's a Proposed Stipulated Decision.  If you encounter a Proposed Stipulated Decision without a cover sheet, you will NOT be able to sign it because when you click "Apply Signature", the very first thing the system is doing is trying to remove a cover sheet that doesn't exist.  You get logged out of the system.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Docket Clerk/Jessica Marine

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**

All eFiled documents should have a cover sheet, and the docket record should correctly indicate how many pages are in the document.
If a cover sheet can't be applied, the PDF should be rejected, not uploaded, and the user would see the 400 error

**Actual Behavior**
In 14810-19:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/bcd5f269-d949-47ff-aab4-879668b1719a)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e0612e16-5324-45f1-8754-43c495af2cb1)

In 3860-20:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/881ad7f4-931a-4a5b-87db-e0d1db5db447)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/8d694827-1f75-473a-9b2b-4bbcd97341ef)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the prod environment.
 - [x] Bug has been tested in Flexion's prod (UX or Engineering).

**Comment by sutt0n** [comment]
@JessicaMarine @mmarcotte 
A note on replication: I was only able to replicate this while watching the network tab and refreshing right _before_ the coversheet is added (last step during a document's upload from the `File a Document` view). Going through the normal flow of logging in as a petitioner/practitioner and eFiling a document, I was unable to replicate this on Flexion's prod environment.

**Comment by sutt0n** [comment]
From discussions w/ @mmarcotte last night regarding these two docket numbers:

```Error: Input document to `PDFDocument.load` is encrypted. You can use `PDFDocument.load(..., { ignoreEncryption: true })` if you wish to load the document anyways.
    at new EncryptedPDFError (/var/task/api.js:670594:20)
    at new PDFDocument (/var/task/api.js:676783:54)
    at Function.<anonymous> (/var/task/api.js:676865:15)
    at step (/var/task/api.js:634992:17)
    at Object.next (/var/task/api.js:634923:14)
    at fulfilled (/var/task/api.js:634877:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)```

It seems that the `validate` endpoint fails for 3860-20, and so the docket entry remains; however, the `coversheet` request is not fired off because of the validation request that fails before it.

**Comment by sutt0n** [comment]
The reason this bug wasn't caught by a test was due to a lack of encryption check during the PDF's validation process. A unit test will be added for this scenario.

**Comment by klohman** [comment]
Tested on flexion prod 101-21 using encrypted PDF [https://app.zenhub.com/files/152320868/ec075da6-86f0-4a37-ad5f-de022d0f3e83/download](https://app.zenhub.com/files/152320868/ec075da6-86f0-4a37-ad5f-de022d0f3e83/download)

Encrypted PDF was not uploaded and added to the docket record. Error message was received, blocking the pdf from being uploaded
![Screen Shot 2021-01-11 at 3.50.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fd46d256-717a-49f1-aa74-c968d2bb7851)


### Other test scenarios
a) Worked as expected - received error 
b) Worked as expected - received error 
c) Did not receive error - got a spinner that never went away. 
d) Uploaded pdf as a docket clerk (to draft documents) - got a spinner that never went away
