### ISSUE TITLE
BUG: Updating field in concatenated document title during QC or Edit Docket Entryis not updating document title

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7626]
**Describe the Bug**
If I update a field that is concatenating the document title and Complete QC, the document title is not being updated correctly. 
* the updated document title is not being saved on the docket entry 
* No new coversheet is being generated
* No NODC is being generated 
* Message attach document dropdown shows old document title 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual test

**To Reproduce**
1. Go to Document QC 
2. Select a document (must be a nonstandard document that has a field concatenated title- example is Declaration in Support of; Reply) 
3. Update the "Who Signed This?"
4. Click Complete 

**Expected Behavior**
* the updated document title should display on the docket entry 
* A new coversheet should be generated with updated document title 
* A NODC should be generated 
* Message attach document dropdown shows new document title 

**Actual Behavior**
* the updated document title is not being saved on the docket entry 
* No new coversheet is being generated
* No NODC is being generated 
* Message attach document dropdown shows old document title 

**Screenshots**
![Screen Shot 2021-01-06 at 1.53.51 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c642ac4f-e148-4cc8-87cb-d64a2bbeee1b)

![Screen Shot 2021-01-06 at 1.54.11 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2629feb4-abab-42d7-8de6-711163509da2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
### 7492 Test Scenarios - QC Screen 

#### 1) Docket clerk updates free text fields in document title and completes QC (Scenario B doc) 
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Ratification
* Enter “for testing” into What are you ratifying field 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Ratification 
* Update “What are you ratifying field” to “for testing 7492”
* Click Complete and Send Message 
Expected results 
- [x] Subject line in message modal displays as “Ratification for testing 7492” 
- [x] “Ratification for testing 7492” displays as attached to message
- [x] the updated document title should display on the docket entry = “Ratification for testing 7492”
- [x] A new coversheet should be generated with updated document title
- [x] A Notice of Docket Change is added to the docket record with updates reflected


#### 2) Docket clerk updates free text fields in document title and completes QC (Scenario C doc) 
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Affidavit in Support
* Enter “John Smith” into name field 
* Select “Petition” as previous document
* Submit filing 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Affidavit 
* Update “name” field to “John Jones”
* Click Complete and Send Message 
Expected results 
- [x] the updated document title should display on the docket entry = “Affidavit of John Jones in Support of Petition”
- [x] A new coversheet should be generated with updated document title
- [x] A Notice of Docket Change is added to the docket record with updates reflected 


#### 3) Docket clerk updates free text fields in document title and completes QC (Scenario D doc) 
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Amended Certificate of Service
* Select “Petition” as previous document
* Enter “01/19/21” into date field
* Submit filing 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Amended Certificate of Service 
* Update “date” field to “1/20/21”
* Click Complete and Send Message 
Expected results 
- [x] the updated document title should display on the docket entry = “Amended Certificate of Service of Petition 01/20/21”
- [x] A new coversheet should be generated with updated document title
- [x] A Notice of Docket Change is added to the docket record with updates reflected 

#### 4) Docket clerk updates free text fields in document title and completes QC (Scenario E doc) 
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Motion to Change Place of Trial
* Select “New York, New York” as location
* Submit filing 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Motion to Change Place of Trial
* Update “location” field to “New Orleans, LA”
* Click Complete and Send Message 
Expected results 
- [x] the updated document title should display on the docket entry = “Motion to Change Place of Trial to New Orleans, LA”
- [x] A new coversheet should be generated with updated document title
- [x] A Notice of Docket Change is added to the docket record with updates reflected 

#### 5) Docket clerk updates free text fields in document title and completes QC (Scenario F doc) 
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Supplement
* Select “Petition” as previous document
* Select “Second” as iteration
* Submit filing 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Supplement
* Update iteration to “First” 
* Click Complete and Send Message 
Expected results 
- [x] the updated document title should display on the docket entry = “First Supplement to Petition”
- [x] A new coversheet should be generated with updated document title
- [x] A Notice of Docket Change is added to the docket record with updates reflected 

#### 6) Docket clerk updates secondary document field in document title and completes QC (Scenario H doc) 
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Motion for Leave to File 
* Select “Administrative Record” as secondary document
* Submit filing 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Motion for Leave to File Administrative Record 
* Update secondary document to “Stipulation of Facts”
* Click Complete and Send Message 
Expected results 
- [x] the updated document title should display on the docket entry = “Motion for Leave to File Stipulation of Facts ”
- [x] A new coversheet should be generated with updated document title
- [x] A Notice of Docket Change is added to the docket record with updates reflected

**Comment by JessicaMarine** [comment]
Reviewed by PO 1.24.2021 -- functionality works as expected but cannot move to Done until Bug Resolution Steps are checked off by engineering team.
