### ISSUE TITLE
BUG: Complete QC and Send Message: Updates to document title are not appearing in send message modal

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7628]
This may not have been explicitly defined in the AC. 

**Describe the Bug**
When the document title has been updated during QC and clerk clicks Complete and Send Message, the document title in the message modal is still displaying the original document title. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Reported by Jessica

**To Reproduce**
1. Go to Document QC Inbox 
2. Select a document 
3. Change document type 
4. Click Complete and Send 

**Expected Behavior**
Updated document title should display as subject line and attachment. 

**Actual Behavior**
Original document title is displaying as subject line and attachment. 

**Screenshots**
![Screen Shot 2021-01-06 at 2.23.48 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/53a97977-4374-4f1c-abfd-1e0be6cd4c00)

![Screen Shot 2021-01-06 at 2.23.54 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b313b9f5-5995-4566-82d5-7e59fbe07141)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
### 7494 Test Scenarios 

#### 1) Docket clerk enters text into Additional Info 1 field and adds to coversheet and sees document title when selecting Complete and Send Message
* Login as docket clerk 
* Go to Document QC Inbox
* Select a document = Answer
* Enter text into Additional Info 1 = “which has additional info”
* Check "Add to Coversheet"
* Click Complete and Send Message 
Expected results 
- [x] Subject line displays as “Answer which has additional info” 
- [x] “Answer which has additional info” displays as attached to message 


#### 2) Docket clerk enters text into Additional Info 1 field and does not add to coversheet and sees document title when selecting Complete and Send Message 
* Login as docket clerk 
* Go to Document QC Inbox
* Select a document = Motion for New Trial 
* Enter text into Additional Info 1 = “which has additional info”
* Do not check "Add to Coversheet"
* Click Complete and Send Message 
Expected results 
- [x] Subject line displays  as “Motion for New Trial” 
- [x] “Motion for New Trial” displays as attached to message 

~~3) Docket clerk updates free text fields in document title and sees correct document title when selecting Complete and Send Message~~ moved to 7492
* Login as petitioner 
* Go to case 
* File a document 
* Select doc type = Ratification
* Enter “for testing” into What are you ratifying field 
* Login as docket clerk 
* Go to Document QC Inbox
* Select Ratification 
* Update “What are you ratifying field” to “for testing 7494”
* Click Complete and Send Message 
Expected results 
- [ ] Subject line displays as “Ratification for testing 7494” 
- [ ] “Ratification for testing 7494”  displays as attached to message

#### 4) Docket clerk updates document type to a different scenario and sees correct document title when selecting Complete and Send Message 
* Login as docket clerk 
* Go to Document QC Inbox
* Select document 
    * Standard 
* Update document type 
    * Nonstandard A = Redacted
    * Nonstandard B = Motion to Calendar and Consolidate
    * Nonstandard C = Declaration in Support
    * Nonstandard D = Amended Certificate of Service
    * Nonstandard E = Motion to Change Place of Submission of Declaratory Judgment Case
* Click Complete and Send Message 
Expected results 
- [x]  Subject line displays as [updated document type] with fully concatenated title 
    * Nonstandard A = “Redacted [Document Name]”
    * Nonstandard B = “Motion to Calendar and Consolidate Docket Numbers [docket numbers]”
    * Nonstandard C = "Declaration of [Name] in Support of [Document Name]"
    * Nonstandard D = "Amended Certificate of Service of [Document Name] [Date]"
    * Nonstandard E = "Motion to Change Place of Submission of Declaratory Judgment Case to [Place]"
- [x]  [updated document type] with fully concatenated title displays as attached to message 
    * Nonstandard A = “Redacted [Document Name]”
    * Nonstandard B = “Motion to Calendar and Consolidate Docket Numbers [docket numbers]”
    * Nonstandard C = "Declaration of [Name] in Support of [Document Name]"
    * Nonstandard D = "Amended Certificate of Service of [Document Name] [Date]"
    * Nonstandard E = "Motion to Change Place of Submission of Declaratory Judgment Case to [Place]"

**Comment by mariahkannenberg** [comment]
May be related to order of operations. Is the updated title saved yet?

**Comment by JessicaMarine** [comment]
Reviewed by PO 1.24.2021 -- functionality works as expected but cannot move to Done until Bug Resolution Steps are checked off by engineering team.
