### ISSUE TITLE
BUG: Edit Docket Entry: Not retaining all data in fields for Motion for Leave to File and causing errors when changing doc type

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7631]
#### Related to [7508](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7508)

**Describe the Bug**
When editing a paper-filed docket entry, some of the data fields for document type Motion for Leave to File are not being retained from the original form. 

Example: When edited a Motion for Leave to File Exhibits, the secondary document dropdown is not displayed at all and should be displaying Exhibits. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
support ticket 

**To Reproduce**
1. Go to case 
2. Add Paper Filing - Motion for Leave to File 
3. Select Exhibits as secondary doc 
4. Save and Serve 
5. Click Edit for the Motion for Leave entry 
6. Change doc type 
7. Save

**Expected Behavior**
Secondary document dropdown should be displayed on edit screen with Exhibits selected. 
When document type is updated, the secondary document should not be required. 

**Actual Behavior**
Secondary document dropdown field is not displaying on Edit Docket Entry form. When changing the doc type to a type not requiring the secondary document, an error is received. 

**Screenshots**
https://drive.google.com/file/d/1XnyaZN3L93A_TaUioJtksKahv-xaehyW/view?usp=sharing

![Screen Shot 2021-01-07 at 11.08.39 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/62d100a3-4b09-4e66-be2f-e2ded35ec6f3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by mmarcotte** [comment]
Perhaps related, we have observed a number of these showing up in the error logs:
```
The Case entity was invalid. {"secondaryDocument":"'docketEntries[19].secondaryDocument' is not allowed"}
The DocketEntry entity was invalid. {"secondaryDocument":"'secondaryDocument' is not allowed"}
```

**Comment by klohman** [comment]
## 7506 Tests

#### 1) Docket clerk edits paper-filed entry doc type to Motion for Leave to file 
* Go to case
* Add Paper Filing for Motion for Leave to File [any document]
* Save and Serve
* Edit docket entry 
Expected results 
- [x] Secondary document field displays with [any document] selected


#### 2) Docket clerk edits paper-filed entry doc type to Motion for Leave to File out of Time
* Go to case
* Add Paper Filing for Motion for Leave to File Out of Time [any document]
* Save and Serve
* Edit docket entry 
Expected results 
- [x] Secondary document field displays with [any document] selected

#### 3) Docket clerk edits e-filed entry doc type to Motion for Leave to file 
* Login as petitioner 
* Go to case
* E-file Motion for Leave to File [any document]
* Login as docket clerk 
* Go to case
* Edit docket entry 
Expected results 
- [x] Secondary document field displays with [any document] selected


#### 4) Docket clerk edits e-filed entry doc type to Motion for Leave to File out of Time
* Login as petitioner 
* Go to case
* E-file Motion for Leave to File Out of Timr[any document]
* Login as docket clerk 
* Go to case
* Edit docket entry 
Expected results 
- [x] Secondary document field displays with [any document] selected

#### 5) Docket clerk updates Motion for Leave to File to another doc type 
* Go to case
* Add Paper Filing for Motion for Leave to File [any document]
* Save and Serve
* Edit docket entry 
* Update doc type to Brief 
* Complete form
* Save 
Expected results 
- [x] Secondary document field is hidden when doc type is updated 
- [x] Which document is this brief in support of? Field is displayed when doc type is updated 
- [x] On save, no error is received for missing secondary document 
- [x] On save, docket entry reflects the updates 

#### 6) Docket clerk updates Motion for Leave to File Out of Time to another doc type 
* Go to case
* Add Paper Filing for Motion for Leave to File [any document]
* Save and Serve
* Edit docket entry 
* Update doc type to Response [anything]
* Complete form
* Save 
Expected results 
- [x] Secondary document field is hidden when doc type is updated 
- [x] What is this responding to? Field is displayed when doc type is updated 
- [x] On save, no error is received for missing secondary document 
- [x] On save, docket entry reflects the updates

**Comment by kkoskelin** [comment]
This bug occurred because `Case.prototype.updateDocketEntry` was using `Object.assign()` to override *only* the provided key/value pairs on a given docket entry, not actually replacing it entirely.  The updated tests now inspect the entirety of the updated docket entry, not just the key/value pairs that we expected to change.
