### ISSUE TITLE
BUG: Edit Docket Entry: Required fields not displaying when doc type is updated to Scenario H document

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7632]
#### Related to [7506](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7506)

**Describe the Bug**
When editing a paper-filed docket entry and updating document type to scenario H document, the required secondary document is not displaying in the form. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
verifying support ticket 

**To Reproduce**
1. Go to case 
2. Edit docket entry (for paper filed doc)
3. Update doc type to MOtion for Leave to File or Motion for leave to file out of time

**Expected Behavior**
Secondary document field should display and be required. 

**Actual Behavior**
Secondary document field is not displaying.

**Screenshots**
![Screen Shot 2021-01-07 at 11.40.06 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8852c41e-e1ab-4092-8714-1f2db978d75e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
### 7508 Tests

#### 1) Docket clerk updates paper-filed entry doc type to Motion for Leave to file 
* Go to case
* Add Paper Filing (any type except for scenario H)
* Save and Serve
* Edit docket entry 
* Update doc type to Motion for Leave to File 
* Save
Expected results 
- [x] Secondary document field displays when doc type is updated
- [x] Secondary document field is required 
- [x] on save, docket entry reflects updates 

#### 2) Docket clerk updates paper-filed entry doc type to Motion for Leave to file out of time
* Go to case
* Add Paper Filing (any type except for scenario H)
* Save and Serve
* Edit docket entry 
* Update doc type to Motion for Leave to File Out of Time
* Save
Expected results 
- [x] Secondary document field displays when doc type is updated
- [x] Secondary document field is required 
- [x] on save, docket entry reflects updates 

#### 3) Docket clerk updates e-filed entry doc type to Motion for Leave to file 
* Login as petitioner 
* Go to case 
* eFile a document (any type except for scenario H)
* Login as docket clerk 
* Go to case
* Edit docket entry 
* Update doc type to Motion for Leave to File 
* Save 
Expected results 
- [x] Secondary document field displays when doc type is updated
- [x] Secondary document field is required 
- [x] on save, docket entry reflects updates 

#### 4) Docket clerk updates e-filed entry doc type to Motion for Leave to file out of time
* Login as petitioner 
* Go to case 
* eFile a document (any type except for scenario H)
* Login as docket clerk 
* Go to case
* Edit docket entry 
* Update doc type to Motion for Leave to File Out of Time
* Save
Expected results 
- [x] Secondary document field displays when doc type is updated
- [x] Secondary document field is required 
- [x] on save, docket entry reflects updates 

#### 5) Docket clerk updates Motion for Leave to File entry to Motion for Leave to file out of time 
* Go to case
* Add Paper Filing  for Motion for Leave to File [any document type]
* Save and Serve
* Edit docket entry 
* Update doc type to Motion for Leave to File out of time [any document type]
* Save 
Expected results 
- [x] Secondary document field displays when doc type is updated 
- [x] Secondary document field is required 
- [x] on save, docket entry reflects updates 

#### 6) Docket clerk updates Motion for Leave to File Out of time entry to Motion for Leave to file 
* Go to case
* Add Paper Filing  for Motion for Leave to File Out of Time[any document type]
* Save and Serve
* Edit docket entry 
* Update doc type to Motion for Leave to File [any document type]
* Save 
Expected results 
- [x] Secondary document field displays when doc type is updated 
- [x] Secondary document field is required 
- [x] on save, docket entry reflects updates

**Comment by mariahkannenberg** [comment]
Original designs and user story:

https://github.com/flexion/ef-cms/issues/980

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/2e0713ea-0edd-494b-857f-03eae4d96c0e)

![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/2da46ec5-1b23-47d4-b414-51fe6a8836f7)

**Comment by mariahkannenberg** [comment]
Original design notes...
• If Nonstandard H document type is selected, show secondary document category field and document type field and secondary "Select" button

secondary Document Category field and document type field is required

Document Type field is populated with documents within the selected category
• "Motion for Leave to File" and "Motion for Leave to File Out of Time" should not be selectable as a secondary document
• The required fields for the secondary document should follow the same pattern as described above for Nonstandard Documents.

on click of secondary select, show "Read only" view displaying both primary and secondary documents
