### ISSUE TITLE
BUG: Validation error on messages

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7633]
**Describe the Bug**
Judge Toro was trying to respond to a message sent from Jessica Marine.  He entered a message and hit "Send" and got a validation error:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/1e13f1c1-eead-4284-b1fa-7382d3c489fd)

It appears that this error is caused by entering too many characters in the "Add message" box.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
USTC production

**Who were you logged in as?**
Judge Toro

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Replying to a message

**To Reproduce**
1. Go to the messaging inbox
2. Click on a message
3. Reply to the message
4. Enter more than 500 characters
5. Click Send

**Expected Behavior**
* If character count exceeds max allowed, provide user with a helpful error.
* No validation error when text is entered in message body less than max character count.

**Actual Behavior**
Unhelpful validation error appeared when text was entered in message body that exceeded 500 characters.

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e22c39b5-dc66-4985-a607-f0b2cb7afe87)
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
PR - 7604

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by mmarcotte** [comment]
I believe this is due to it being greater than 500 characters. Perhaps it's best to increase that limit while also providing better error messaging.

**Comment by mariahkannenberg** [comment]
Reproduced on Flexion prod and added steps to bug. Seems like it's a character limit issue as noted above.

**Comment by klohman** [comment]
* related to field character limit - increase limit to 700
* show error message when character limit reached

**Comment by klohman** [comment]
@JessicaMarine @rachaelparris 

Did we want to increase the character limit here to 700? ![Screen Shot 2021-01-19 at 11.04.22 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aaf19f1c-5c06-40c9-8e47-2e7c529128a4)

**Comment by JessicaMarine** [comment]
@klohman yes, I think you added a comment to increase to 700

**Comment by klohman** [comment]
Reviewed on dev - ready for PO review after prod deploy 

![Screen Shot 2021-01-19 at 3.40.20 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f3aef071-49fe-4fc3-834d-75b3f385e659)
