### ISSUE TITLE
BUG: Validation messaging shifting submit buttons

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7635]
**Describe the Bug**
If user attempts to submit a form but it produces validation errors, the vertical size of the form itself "grows". when validation requirements are met and the validation messages/decorations disappear on "blur", such as the user trying to click a "submit button", does the button move OUT from beneath the user's mouse, requiring them to re-target the submit button and try a second time?

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
any user 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
issue moved from Trello UX Pain Points

**To Reproduce**
1. As a docketclerk using a pointing device (touchpad or mouse), log into https://ui-dev.ustc-case-mgmt.flexion.us/search advanced search and select the "Order" tab.
2. Without typing anything into the search box, click "Search" button.
3. See the form validation banner above the search form, and the field-level validation just below the input.
4. Type "dismiss" (or any other word) into the search form without touching your mouse/touchpad.
5. Move (but don't click) your mouse until it hovers over the bottom-half of the "Submit" button.
6.  Click just one time.

**Expected Behavior**
 - on "blur" of the search field, validation occurs and the banner & field-level validation messages (mentioned above in step 3) disappear, AND
- when the validation goes away, the form and the button shift upward on the page
- and the button shifts out from beneath the mouse
- and the "click" event doesn't occur on the button itself
- the user must then re-target the submit button to click a second time.

**Actual Behavior**
- validation should occur and make the warnings go away
- the button does NOT shift out from beneath the mouse

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by klohman** [comment]
Notes from Trello card: 

Suggestions:
- do not use the warning message banner when its addition/removal changes the vertical (y-axis) coordinates of a submit button
- use only the field-level validation
- make the height of the search box fixed such that addition/removal of the field-level validation does not alter the height of the search box

Additional Note:
- it is likely there are other search forms with validation which may exhibit this behavior; we'll need to watch out for it.

**Comment by kkoskelin** [comment]
DEMO: https://www.awesomescreenshot.com/video/2297850?key=f82175f1d4e0ddeb9cba15b11aea4ef1
