### ISSUE TITLE
BUG: Selected document in drafts not being retained when navigating within a case

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7639]
**Moved from Trello UX Pain Points**

**Describe the Bug**
The default behavior for Drafts screen (not linking directly from document link) is that the first draft document will be selected - this currently requires a refresh, or the user to initiate another workflow that resets the case

If possible, the draft screen should retain the selected document when a user clicks within a case, but if they click away from a case and back, it should return to the default selection (first document).

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
internal user 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
moved from Trello UX Pain points

**To Reproduce**
1. Go to case
2, Go to Drafts (with multiple draft documents) 
3. Select the second draft 
4. Click to another tab 
5. Click back to Drafts tab

**Expected Behavior**
The second document selected in drafts remains displayed. 

**Actual Behavior**
Drafts defaults to displaying the first document in list. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
@klohman What counts as "navigating within a case" vs "navigating away from a case and back"?

**Comment by klohman** [comment]
Could we define "within a case" as anywhere the case header is displaying?

**Comment by matthopson** [comment]
PR: https://github.com/ustaxcourt/ef-cms/pull/1247
