### ISSUE TITLE
BUG: Case Detail> Petitioner Counsel - Spacing is off on represented parties  (Link to story and close)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7640]
**Moved from Trello UX Pain Points 

**Describe the Bug**
Petitioner Counsel - "Representing"
- spacing between field label and data should be decreased (should be the same as Service Preference and Party type in example screenshot)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bbccf011-e042-438e-be7b-d5827df2ab61)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
Should we close this bug since this page is being redesigned?

**Comment by JessicaMarine** [comment]
@klohman Please consider when re-designing Parties tab.

**Comment by rachelschneiderman** [comment]
This has been addressed as part of the party redesign stories, closing.
