### ISSUE TITLE
BUG: Edit Docket Entry - Page never loads; receiving spinner and error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7642]
**Describe the Bug**
When trying to edit a docket entry (entry number 4 on 12844-20), the page never loads and the spinner displays indefinitely. Error is received in console. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
verifying support ticket 

**To Reproduce**
1. Go to 12844-20
2. Click Edit link on entry 4

**Expected Behavior**
Edit docket entry screen should display. 

**Actual Behavior**
 the page never loads and the spinner displays indefinitely. Error is received in console. 

**Screenshots**
https://drive.google.com/file/d/1zrqDeThvFmh0PurOjbcD7I5NEBUFvPdQ/view?usp=sharing

![Screen Shot 2021-01-08 at 8.56.37 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6fbe4ba3-6fce-45c9-b661-0d80bc08a7e3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by JessicaMarine** [comment]
I encountered the same issue in 9851-20 entry 4.

**Comment by klohman** [comment]
Both of these docket entries have a processing status of "pending" - if that could be the cause of this error 

![Screen Shot 2021-01-14 at 9.45.15 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4c7174fd-8866-4359-9d77-ff651f2968ee)

**Comment by klohman** [comment]
## 7524 Tests

#### 1) Docket clerk clicks edit for new paper-filed docket entry 
* Login as docket clerk 
* Go to case 
* Add Paper Filing for Response [anything]
* Save and Serve
* Click Edit link on docket entry 
Expected	results
- [x] App routes to Edit Docket Entry screen 
- [x] Doc type field is populated with Response 
- [x] What is this document responding to field is populated with [anything]

#### 2) Docket clerk clicks edit for new e-filed docket entry 
* Login as petitioner 
* Go to case 
* E-file Response [previous document]
* Login as docket clerk 
* Go to case 
* Click Edit link on docket entry 
Expected	results
- [x] App routes to Edit Docket Entry screen 
- [x] Doc type field is populated with Response 
- [x] What is this document responding to field is populated with selected previous document 

#### 3) Docket clerk clicks edit for new court-issued docket entry 
* Login as docket clerk 
* Go to case 
* Create, sign, and save court-issued document [Order of Dismissal] 
* Save and serve
* Click Edit link on docket entry 
Expected	results
- [x] App routes to Edit Docket Entry screen 
- [x] Doc type field is populated with Order of Dismissal 

#### 4) Docket clerk clicks edit for legacy externally filed docket entry 
* Login as docket clerk 
* Go to case 
    * Case must have legacy 
* Add Paper Filing for Response [anything]
* Save and Serve
* Click Edit link on docket entry 
Expected	results
- [x] App routes to Edit Docket Entry screen 
- [x] Doc type field is populated with Response 
- [x] What is this document responding to field is populated with [anything]

#### 6) Docket clerk clicks edit for legacy court-issued docket entry 
* Login as docket clerk 
* Go to case 
* Click Edit link on on legacy court-issued docket entry [Order of Dismissal] 
Expected	results
- [x] App routes to Edit Docket Entry screen 
- [x] Doc type field is populated with Order of Dismissal

**Comment by kkoskelin** [comment]
Appears to have been fixed by ustaxcourt/ef-cms-flexion#7569

**Comment by kkoskelin** [comment]
The bug was because the `ExternalDocumentNonstandardA` was the type of external document on the docket entry in question -- which was a Response to an Order.  However, this case appeared to have been migrated, and as such, the `previousDocument` property was not populated.  The function responsible for generating the document title expected it to have a value when it did not, causing an error referencing a property on `undefined`.

Work done by @rachaelparris and @rachelschneiderman yesterday appears to have fixed the problem, by making the definition of `previousDocument` optional in all title generation functions in the External Documents.  Now reviewing all test scenarios to ensure nothing has been missed.

**Comment by klohman** [comment]
UX Review - able to reach Edit Docket Entry screen for 12844-20 entry 4 and 9851-20 entry 4[Uploading... Screen Shot 2021-01-15 at 1.41.59 PM.png]
