### ISSUE TITLE
BUG: Entered and Served Date not applied

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7643]
**Describe the Bug**
A Proposed Stipulated Decision was eFiled on 12/28/2020.  It was signed and served on 1/6/2021.  The "Entered and Served 1/6/2021" was **NOT** applied to the bottom of the document.

Here is the PDF that caused problems: [https://app.zenhub.com/files/152320868/96ba5b2d-8349-4320-80d2-ae99cab3c502/download](https://app.zenhub.com/files/152320868/96ba5b2d-8349-4320-80d2-ae99cab3c502/download)

**Business Impact/Reason for Severity**
The entered and/or served date kicks off a series of statutory deadlines.  It is unacceptable for the Court to issue a Decision without it!

**In which environment did you see this bug?**
Court's Prod

**Who were you logged in as?**
Judge Carluzzo reported (Jessica confirmed)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
"Served" or "Entered and Served" date applied to every document that is served.

**Actual Behavior**
No "Entered and Served" date applied to document.
[https://app.zenhub.com/files/152320868/1dd42704-ff4f-4a1f-97cf-eaf1ff625ac9/download](https://app.zenhub.com/files/152320868/1dd42704-ff4f-4a1f-97cf-eaf1ff625ac9/download)
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by rachelschneiderman** [comment]
Hotfix PR to court: https://github.com/ustaxcourt/ef-cms/pull/748
