### ISSUE TITLE
BUG: Error received when serving document with extremely long title

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7644]
**Describe the Bug**
When entering a docket entry for a document (court-issued or paper-filed) with an extremely long title and serving, system throws 400 error. 

When e-filing a document as a party with document title over max character count, the app throws error on submit. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
verifying support ticket 

**To Reproduce**
**Court-issued**
1. Go to case 
2. Create Order 
3. Add docket entry 
4. Enter description - enter a lot of text> 3000 characters 
5. Save and serve 

**paper-filed**
1. Go to case 
2. Add Paper filing  
3. Select Response 
4. Enter description - enter a lot of text> 3000 characters 
5. Save and serve 

**e-filed**
1. login as petitioner 
2. go to case 
3. Select "Statement" as doc type 
4. Enter description - enter a lot of text> 3000 characters 
5. Complete form and click Submit your filing 

**Expected Behavior**
If title or fields making up the title are longer than allowed, user should be advised of what the issue is.  Better error messaging. 

**Actual Behavior**
App routes to 400 error page ( for court-issued and paper filed docs) 
App throws upload error when e-filing document. 

Notes:
*Possibly break this into multiple issues if it gets really big. 

**Screenshots**
https://drive.google.com/file/d/1ob1fgbINrPQTm5ABYyDzpXLl8znB3BEW/view?usp=sharing
![Screen Shot 2021-01-11 at 8.38.02 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/755abce2-75fc-4665-a91e-434bed70cdad)

![Screen Shot 2021-01-13 at 12.23.32 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f4722070-f072-4c89-9c40-e6ed18a5940a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Current character limit for doc title - DOCUMENT_TITLE: STRING.max(3000)

If this is related to the issue, we can re-evaluate and possibly reduce this limit (discuss with Jessica if applicable)

**Comment by klohman** [comment]
- Document title < 3000 characters 
Court-issued
    - petitionerNames
    - freeText  < 500
    - judge 
    - docketNumbers < 500
    - Date 
    - Trial location <100
External docs
    - previousDocument.documentTitle (assume <3000)
    - freeText < 500
    - documentTitle (assume <3000)
    - serviceDate 
    - trialLocation <100
    - ordinalValue 
    - documentType (longest is 123 characters) 
    - secondaryDocument
    - freeText2 < 500

- Additional info 1 < 500 characters 
- Additional info 2 < 500 characters

**Comment by klohman** [comment]
## 7533 Tests 

Need to test these document scenarios / type: 
CourtIssuedDocumentTypeA
CourtIssuedDocumentTypeB
CourtIssuedDocumentTypeC
CourtIssuedDocumentTypeD
CourtIssuedDocumentTypeH
ExternalDocumentNonStandardB
ExternalDocumentNonStandardC
ExternalDocumentNonStandardI
ExternalDocumentNonStandardJ

#### 1) Docket clerk enters 1000 characters into free text field court-issued document and serves
* Login as docket clerk 
* Go to case 
* Create, sign and save Order 
* Add Docket entry 
* Select “O” as doc type 
* Enter 1000 characters in “What is this order for?” field 
* Save and serve 
Expected results 
- [x] Order docket entry is added to docket record with complete document title displayed 
- [x] Order is served on parties 


#### 2) Docket clerk enters 1001 characters into free text field court-issued document and serves
* Login as docket clerk 
* Go to case 
* Create, sign and save Order 
* Add Docket entry 
* Select “O” as doc type 
* Enter 1001 characters in “What is this order for?” field 
* Save and serve 
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters. 


#### 3) Docket clerk enters 1000 characters into docketNumbers field for paper-filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “M067” as doc type 
* Enter 1000 characters in Docket Numbers field
* Save and serve 
Expected results 
- [x] Motion docket entry is added to docket record with complete document title displayed 
- [x] Motion is served on parties 


#### 4) Docket clerk enters 1001 characters into docketNumbers field for paper filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “M067” as doc type 
* Enter 1001 characters in Docket Numbers field
* Save and serve 
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters. 


#### 5) Docket clerk enters 1000 characters into freeText field for paper-filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “APPL” as doc type 
* Enter 1000 characters in freeText field
* Save and serve 
Expected results 
- [x] docket entry is added to docket record with complete document title displayed 
- [x] document is served on parties 


#### 6) Docket clerk enters 1001 characters into freeText field for paper filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Select “APPL” as doc type 
* Enter 1001 characters in freeText field
* Save and serve 
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters. 


#### 7) Docket clerk enters 500 characters into additional info1 field for paper-filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Enter 500 characters in additional info1 field
* Save and serve 
Expected results 
- [x] docket entry is added to docket record with complete document title displayed 
- [x] document is served on parties 


#### 8) Docket clerk enters 501 characters into additional info1 field for paper filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Enter 501 characters in additional info1 field
* Save and serve 
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 

#### 9) Docket clerk enters 500 characters into additional info2 field for paper-filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Enter 500 characters in additional info2 field
* Save and serve 
Expected results 
- [x] docket entry is added to docket record with complete document title displayed 
- [x] document is served on parties 


#### 10) Docket clerk enters 501 characters into additional info2 field for paper filed document and serves
* Login as docket clerk 
* Go to case 
* Add paper Filing
* Enter 501 characters in additional info2 field
* Save and serve 
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 

#### 11) Party enters 1000 characters into freeText field for e-filed document 
* Login as petitioner / private practitioner/ IRS practitioner
* Go to case 
* Click File a Document 
* Select “APPL” as doc type 
* Enter 1000 characters in freeText field
* Submit
Expected results 
- [x] docket entry is added to docket record with complete document title displayed 
- [x] document is served on parties 


#### 12) Party enters 1001 characters into freeText field for e filed document 
* Login as petitioner / private practitioner/ IRS practitioner
* Go to case 
* Click File a Document 
* Select “APPL” as doc type 
* Enter 1001 characters in freeText field
* Submit
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters. 

#### 13) Docket clerk enters 500 characters into additional info1 field for e-filed document and completes QC
* Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 500 characters in additional info1 field
* Complete QC
Expected results 
- [x] docket entry is updated on docket record with complete document title displayed 


#### 14) Docket clerk enters 501 characters into additional info1 field for e filed document and completes QC
* Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 501 characters in additional info1 field
* Complete QC
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 

#### 15) Docket clerk enters 500 characters into additional info2 field for e-filed document and completes QC
* Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 500 characters in additional info2 field
* Complete QC
Expected results 
- [x] docket entry is updated on docket record with complete document title displayed 


#### 16) Docket clerk enters 501 characters into additional info2 field for e filed document and completes QC
* Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 501 characters in additional info2 field
* Complete QC
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 


#### 17) Docket clerk enters 1000 characters into free text field when editing court-issued docket entry
* Login as docket clerk 
* Go to case 
* Edit docket entry 
* Select “O” as doc type 
* Enter 1000 characters in “What is this order for?” field 
* Save
Expected results 
- [x] Order docket entry is updated on docket record with complete document title displayed 


#### 18) Docket clerk enters 1001 characters into free text field when editing court-issued docket entry
* Login as docket clerk 
* Go to case 
* Edit docket entry 
* Select “O” as doc type 
* Enter 1001 characters in “What is this order for?” field 
* Save
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters. 

#### 19) Docket clerk enters 1000 characters into docketNumbers field for e-filed document and completes QC
*  Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 1000 characters in additional info2 field
* Complete QC
Expected results 
- [x] Motion docket entry is added to docket record with complete document title displayed 


#### 20) Docket clerk enters 1001 characters into docketNumbers field for e-filed document and completes QC
*Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 1001 characters in additional info2 field
* Complete QC
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 


#### 21) Docket clerk enters 1000 characters into freeText field for e-filed document and completes QC
* Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 1000 characters in freeText field
* Complete QC
Expected results 
- [x] docket entry is added to docket record with complete document title displayed 
**QC process is not blocked but the updated title is not displaying - already logged as [7492](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7492)


#### 22) Docket clerk enters 1001 characters into freeText field or e-filed document and completes QC
* Login as docket clerk 
* Go to Document QC Inbox
* Select e-filed document 
* Enter 1001 characters in freeText field
* Complete QC
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters

#### 23) Docket clerk enters 1000 characters into free text field when editing paper-filed or e-filed docket entry
* Login as docket clerk 
* Go to case 
* Edit docket entry (nonstandard B)
* Enter 1000 characters in freeText field 
* Save
Expected results 
- [x] docket entry is updated on docket record with complete document title displayed 
**Saving is not blocked but the updated title is not displaying - already logged as [7492](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7492)

#### 24) Docket clerk enters 1001 characters into free text field when editing paper-filed or e-filed docket entry
* Login as docket clerk 
* Go to case 
* Edit docket entry (nonstandard B)
* Enter 1001 characters in freeText field 
* Save
Expected results 
- [x] App displays page error message: Limit is 1000 characters. Enter 1000 or fewer characters. 

#### 25) Docket clerk enters 500 characters into additional info1 field for paper or e-filed document when editing docket entry
* Login as docket clerk 
* Go to case
* Edit docket entry  
* Enter 500 characters in additional info1 field
* Save 
Expected results 
- [x] docket entry is updated on docket record with complete document title displayed 


#### 26) Docket clerk enters 501 characters into additional info1 field for paper or e-filed document when editing docket entry
* Login as docket clerk 
* Go to case
* Edit docket entry  
* Enter 501 characters in additional info1 field
* Save
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 

#### 27) Docket clerk enters 500 characters into additional info2 field for paper or e-filed document when editing docket entry
* Login as docket clerk 
* Go to case
* Edit docket entry  
* Enter 500 characters in additional info2 field
* Save 
Expected results 
- [x] docket entry is updated on docket record with complete document title displayed 


#### 28) Docket clerk enters 501 characters into additional info2 field for paper or e-filed document when editing docket entry
* Login as docket clerk 
* Go to case
* Edit docket entry  
* Enter 501 characters in additional info2 field
* Save
Expected results 
- [x] App displays page error message: Limit is 500 characters. Enter 500 or fewer characters. 


### Need to work with engineers to test these - it may be difficult to reach the max limit 

#### 29) Docket clerk sees error message when document title limit is reached for court-issued documents on Add Docket Entry screen  
* Login as docket clerk 
* Go to case 
* Create, sign and save Order 
* Add Docket Entry 
* Enter characters to reach > 3000 for complete document title 
* Save and Serve
Expected results 
- ~~[] Display page level error: “Docket entry must be 3000 characters or fewer. Update this docket entry and try again."~~
**Cannot reach 3000 characters in UI for court-issued documents**

#### 30) Docket clerk sees error message when document title limit is reached for paper-filed documents on Add Docket Entry 
* Login as docket clerk 
* Go to case 
* Add Paper filing 
* Enter characters to reach > 3000 for complete document title 
* Save
Expected results 
- [x] Display page level error: “Docket entry must be 3000 characters or fewer. Update this docket entry and try again.”  

#### 31) Docket clerk sees error message when document title limit is reached for e-filed documents on QC screen 
* Login as docket clerk 
* Go to Document QC Inbox 
* Select e-filed document 
* Enter characters to reach > 3000 for complete document title 
* Save
Expected results 
- [x] Display page level error: “Docket entry must be 3000 characters or fewer. Update this docket entry and try again.”  

#### 32) Docket clerk sees error message when document title limit is reached for documents on Edit Docket Entry screen
* Login as docket clerk 
* Go to case
* Select Edit link on docket entry 
* Enter characters to reach > 3000 for complete document title 
* Save
Expected results 
- [ ] Display page level error: “Docket entry must be 3000 characters or fewer. Update this docket entry and try again.”

**Comment by klohman** [comment]
* increase freeText fields to 1000 characters and show error message when reached 
* any field that has a character limit , display error message when reached 
* if document title max limit is reached, show global error message - page level only

**Comment by rachaelparris** [comment]
Scenarios to verify:
* Create order modal

**Comment by JessicaMarine** [comment]
@klohman @mrinsin @rachaelparris We can mob to test this on Monday!  Have a great weekend.
