### ISSUE TITLE
BUG: Today's Orders not Left Aligned

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7645]
**Describe the Bug**
The Order column on "Today's Orders" is not left-aligned:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/ed186ed2-affc-435b-8555-41dfa3be23ef)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court production

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to dawson.ustaxcourt.gov/todays-orders
2. Note items longer than 1 line are not left aligned

**Expected Behavior**
The Order column of "Today's Orders" is left aligned.

**Actual Behavior**
The Order column of "Today's Orders" is not left aligned.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The link for order title is inside a button, a button's text styling default is centered text.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
Update looks good 
 ![Screen Shot 2021-01-19 at 11.02.04 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/139becf5-0e51-49e5-b36b-f6670b6af985)
