### ISSUE TITLE
Prevent service email from sending to parties when anything fails, including documents

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7647]
As the IRS, so that I don't receive emails with broken links to PDFs, I do not want to receive an email when the document fails to be uploaded and processed successfully. 

## Pre-Conditions
* Petitioner or practitioner has e-filed a petition or uploaded a document to a case

## Acceptance Criteria
* Prevent service email from sending parties on a case when anything fails between PDF upload and adding the document to the docket record
      * Parties include IRS, Petitioners, and Counsel
   
## Notes
* This came from the refactoring backlog meeting. Per Mike, there are other functions that could fail after the email goes out. Discuss what they are, if they need to be added to this story or to the backlog. 
* What are all the things that could fail and prevent a document from being "linkable" in a service email to IRS

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by TomElliottFlexion** [comment]
Went the route of moving around existing code to send service emails last in the flows involving uploaded PDF manipulation, rather than splitting out SES into its own endpoint.
