### ISSUE TITLE
BUG: Trial Session info. not showing in UI correctly

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7648]
**Describe the Bug**
We have several cases in the Court's production where they were set for trial on session ustaxcourt/ef-cms#6491 and then added for hearing on session ustaxcourt/ef-cms#6492.  For some reason, the information displaying in the Trial card is no longer the session ustaxcourt/ef-cms#6491 information, but is the session ustaxcourt/ef-cms#6492 information. Also, the judge has been updated from the session ustaxcourt/ef-cms#6491 judge to the hearing (session ustaxcourt/ef-cms#6492) judge.  Attempts to manually fix this fail as the case is still showing on (and is associated with) trial session ustaxcourt/ef-cms#6491.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Any court user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**

**Expected Behavior**
Trial session and hearing session information are kept separate and apart.

**Actual Behavior**
Hearing information seems to return in the UI as the trial information and associated judge.

**Screenshots**

This case should have 3/1/2021 Chicago (Nega) listed in Trial card: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/9b6a606f-93bf-423e-a0f1-f6c09e6615a1)

Case is still showing on that session despite *not* having that info. show up under Case Info:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/98eea3ae-2e38-4c7e-b944-24ef41e0a06d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by mrinsin** [comment]
Hotfix PR: https://github.com/ustaxcourt/ef-cms/pull/761/
