### ISSUE TITLE
BUG: Service stamp turning vertical

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7649]
**Describe the Bug**
The "Served" or "Entered and Served" date applied by the system at the bottom of the page is turning vertical on save on some PDFs.  Likely related to: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7447

**Business Impact/Reason for Severity**
Unable to process some documents (including decisions)

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
ADC

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Sign and serve target PDF (Rae has one)
2. Notice that "Entered and Served" date is applied vertically on the page and not at the bottom

**Expected Behavior**
Service date applied to bottom of PDF remains horizontal.

**Actual Behavior**
Entered and Served date turning vertical.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/a7fb9e98-81b8-4cf7-997b-3ff330784a43)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by klohman** [comment]
## 7549

#### 1) Docket clerk serves Order with “Entered and Served” stamp from Drafts screen
* Login as docket clerk 
* Go to case 
* Upload PDF (rotated PDF) 
* Apply Signature 
* Add Docket entry 
* Select code “O” for document type 
* Select Entered and Served for service stamp
* Save and Serve 
Expected results 
- [x] Served stamp is applied to PDF as “Entered and Served [today’s date] 
- [x] Served stamp is applied horizontally at the bottom of page 1

#### 2) Docket clerk serves Order with “Served” stamp from Drafts screen
* Login as docket clerk 
* Go to case 
* Upload PDF (rotated PDF) 
* Apply Signature 
* Add Docket entry 
* Select code “O” for document type 
* Select Served for service stamp
* Save and Serve 
Expected results 
- [x] Served stamp is applied to PDF as “Served [today’s date] 
- [x] Served stamp is applied horizontally at the bottom of page 1

#### 3) Docket clerk serves Order with “Entered and Served” stamp from Message detail screen
* Login as docket clerk 
* Go to case 
* Upload PDF (rotated PDF) 
* Apply Signature 
* Create message and attached uploaded PDF
* Go to message detail
* Add Docket entry 
* Select code “SDEC” for document type 
* Select Entered and Served for service stamp
* Save and Serve 
Expected results 
- [x] Served stamp is applied to PDF as “Entered and Served [today’s date] 
- [x] Served stamp is applied horizontally at the bottom of page 1

#### 4) Docket clerk serves Order with “Served” stamp from Message detail screen
* Login as docket clerk 
* Go to case 
* Upload PDF (rotated PDF) 
* Apply Signature 
* Create message and attached uploaded PDF
* Go to message detail
* Add Docket entry 
* Select code “ORAP” for document type 
* Select Served for service stamp
* Save and Serve 
Expected results 
- [x] Served stamp is applied to PDF as “Served [today’s date] 
- [x] Served stamp is applied horizontally at the bottom of page 1
