### ISSUE TITLE
BUG: Pretrial Memos are accessible by public

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7652]
**Describe the Bug**
It was brought to the Court's attention that some pretrial memos are showing up as hyperlinks in the public view of the docket record.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Public

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to dawson.ustaxcourt.gov
2. Search for 20584-11
3. Note that the Pretrial memos (entries ustaxcourt/ef-cms#6495 & 14) are hyperlinked
4. When you click on the hyperlink, it retrieves the document

**Expected Behavior**
(If more pervasive than pre-trial memos, fix everywhere.)
Memos are not hyperlinked
Public users cannot get signed URLs for memos
Only orders and opinions are publicly accessible.

**Actual Behavior**
Prertrial memos are publicly accessible.
Hyperlink is fetching the document

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
This bug was caused by the code checking the documentType instead of eventCode in order to determine the accessibility for the docket entry. There was a mismatch in the reported document between the documentType and eventCode that made the docket entry appear as if it was publicly available. Now the code checks the document eventCode against a whitelist of publicly accessible eventCodes.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by klohman** [comment]
**Cannot reproduce on flexion prod - generic test cases below**

## 7555 tests

#### 1) Party files Pretrial Memorandum and it is inaccessible to the public 
* Login as petitioner / private practitioner/ IRS practitioner 
* Go to case 
* File Pretrial Memorandum 
* Go to public search 
* Search for case 
Expected results 
- [ ] Pretrial memorandum entry is visible on docket record 
- [ ] Pretrial memorandum is not hyperlinked 
- [ ] Pretrial memorandum PDF is not accessible by public 

#### 2) Docket clerk adds paper-filing for Pretrial Memorandum and it is inaccessible to the public
* Login as docket clerk 
* Go to case 
* Add Paper Filing for Pretrial Memorandum 
* Save and Serve 
* Go to public search 
* Search for case 
Expected results 
- [ ] Pretrial memorandum entry is visible on docket record 
- [ ] Pretrial memorandum is not hyperlinked 
- [ ] Pretrial memorandum PDF is not accessible by public

**Comment by mariahkannenberg** [comment]
Notes:
If more pervasive than pre-trial memos, fix everywhere.

**Comment by mariahkannenberg** [comment]
const EVENT_CODES_NOT_VISIBLE_TO_PUBLIC = [
  'SDEC',
  'NOT',
  'FTRL',
  'HEAR',
  'NTD',
  'PTRL',
  'TRL',
  'ROA',
  'MISC',
  'HE',
  'TE',
  'USCA',
  'ES',
  'RM',
  ...Object.keys(EVENT_CODES_NOT_VISIBLE_TO_PARTIES_FOR_TIME_PERIOD_MAP),
];

**Comment by mariahkannenberg** [comment]
If court-issued, look on blacklist. If not on blacklist, it's publicly available.
If not court-issued, not publicly available. 

Discussion on 1/14/21 - use whitelist instead of blacklist.
Anything on order search or opinion search would be on the whitelist
Document testable parameters for event codes. 
For Kristen to test, we can migrate a case to get it into same status.

**Comment by klohman** [comment]
@JessicaMarine 

543-20 on prod is in the same state as the original docket entry, and now displays no hyperlink for public view 
![Screen Shot 2021-01-15 at 12.10.41 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/43d09109-85dd-4c55-ab03-3e133f412256)
