### ISSUE TITLE
BUG: Public docket record:  Displaying wrong event code for Lodged documents

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7660]
**Describe the Bug**
Lodged documents are displaying the incorrect event code on the public docket record. They display MISCL for the internal/parties view of the docket record, but are displaying the actual document event code for public users. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
public user 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Login as petitioner 
2. Go to case 
3. File a Motion for Leave to File Administrative Record (including PDF for both documents)
4. Login as docket clerk 
5. go to case 
6. Add Paper Filing for Lodged "Motion for New Trial" 
7. Go to public case search 

**Expected Behavior**
Lodged entries display MISCL for the the internal, parties, and public view of the docket record. 

**Actual Behavior**
Public view is displaying the actual document event code for public users. 

**Screenshots**
![Screen Shot 2021-01-15 at 9.28.01 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6b4453d4-edf5-4f0c-b711-633ffae4cb56)

![Screen Shot 2021-01-15 at 9.26.49 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/be5bc80a-97d9-4f44-a2e9-3711e1b248f2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by matthopson** [comment]
This is due to the lodged flag not being present on the Public Docket Entry entity, which is addressed with ustaxcourt/ef-cms#7661. 
https://github.com/flexion/ef-cms/pull/7654

Here's a screenshot of an Administrative Record with lodged from the public view after that fix.
![Screen Shot 2021-01-25 at 2.15.56 PM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/7a8d6605-8d95-446d-88fc-1e46f8a7a8b8)
