### ISSUE TITLE
BUG: Public docket record: Not displaying parenthetical information on docket entries

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7661]
**Describe the Bug**
The public docket record view does not display any parenthetical information on entries, for example: 
* (Lodged)
* (Attachments) 
* (Objections) 
* (CS mm/dd/yy)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
public 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Login as docket clerk 
2. Go to case 
3. Add Paper filing - Motion
4. Check Attachments box, Certificate of Service box
5. Select Objections - Yes 
6. Save and Serve
7. Go to to public view of case 

**Expected Behavior**
Full docket entry, including parenthetical text, should display for public users. 

**Actual Behavior**
Parenthetical text is not displayed in docket entries.

**Screenshots**
Internal/party view of record
![Screen Shot 2021-01-15 at 10.39.18 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/65cc9472-a8cc-48dd-8d90-42f06a1236d4)

Public view 
![Screen Shot 2021-01-15 at 10.48.19 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c8aeb02d-1f3b-44c3-8e4b-7071c99ed8c0)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by matthopson** [comment]
@JessicaMarine These do not show up because some fields are missing on the Public Docket Entry entity, compared to the internal one.

```
certificateOfService
certificateOfServiceDate
objections
lodged
```

I'd assume since these are to be present in the UI, it's safe to include the fields in the entity and send them over the wire, but since we've been super cautious about what we send back from the API for public, we just wanted to confirm that this would be ok.

**Comment by JessicaMarine** [comment]
@matthopson Yes, these are okay to include

**Comment by matthopson** [comment]
PR: https://github.com/flexion/ef-cms/pull/7654

**Comment by klohman** [comment]
Verified public docket is now displaying parenthetical info

![Screen Shot 2021-01-26 at 1.40.36 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d403d2d9-e1c6-4f57-a197-9317fe69441b)
