### ISSUE TITLE
BUG: Electronic signatures not viewable in PDF preview

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7664]
**Describe the Bug**
When a party is eFiling a document that has been electronically signed, the eSignature does not display in the PDF previewer modal, so they are not sure whether it will be there when filed.  Note:  It does actually show on the filed version, but it's causing a lot of uncertainty on the part of the filer.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
IRS reported

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as IRS attorney
2. Attempt to file a PDF that has been electronically signed. Sample: [https://app.zenhub.com/files/152320868/15f57d3a-c3a5-43d6-b400-138fc425101d/download](https://app.zenhub.com/files/152320868/15f57d3a-c3a5-43d6-b400-138fc425101d/download)
3. Note that the eSignature does not appear on the document when viewed in the PDF viewer on the "Review Your Filing" screen

**Expected Behavior**
Electronic signature is visible in PDF viewer

**Actual Behavior**
IRS attorney trying to eFile a document that was eSigned did not see signature on PDF when reviewing before filing:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/0c14c3ff-f9ad-4fe8-b95a-e6c661986103).

Once filed, the electronic signature does appear on the PDF:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/c0b4f446-d0f6-4e11-89a0-9b571cab37e9)

**Desktop (please complete the following information):**
Edge Version:   87.0.664.41 (Official build) (64-bit)
Abode info: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/63a12e61-647b-4c48-9784-bc8ab8ab55ba)

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by klohman** [comment]
## 7584 Tests 

#### 1) External user uploads digitally signed PDF when filing a Petition 
* Login as petitioner / private practitioner 
* Create case 
* Upload digitally signed STIN 
* Upload digitally signed Petition
* Select Corporation as party type 
* Upload digitally signed ODS
* Review petition  
* View PDF previews on Review Your Case screen 
Expected results 
- [x] PDF preview displays digital signature 
- [x] On submit, PDF on docket record displays digital signature 

#### 2)  Private practitioner user uploads digitally signed PDF when requesting access to case 
* Login as private practitioner 
* Search for case w/o petitioner counsel 
* Click Request Access 
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [x] PDF preview displays digital signature 
- [x] On submit, PDF on docket record displays digital signature 

#### 3)  irs Practitioner user uploads digitally signed PDF when filing first IRS document 
* Login as irs practitioner 
* Search for case w/o respondent counsel 
* Click File First IRS Document 
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 4)  irs Practitioner user uploads digitally signed PDF when requesting access to case 
* Login as irs practitioner 
* Search for case w/ respondent counsel 
* Click Request Access
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 5) External user uploads digitally signed PDF when filing a document 
* Login as petitioner / private practitioner / irs practitioner
* Go to case on your dashboard 
* Click File a Document 
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [x] PDF preview displays digital signature 
- [x] On submit, PDF on docket record displays digital signature 

#### 6)  Docket clerk user uploads digitally signed PDF when adding paper filing 
* Login as docket clerk 
* Go to a case 
* Add Paper Filing 
* Upload digitally signed PDF 
* View PDF preview 
* Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 7) External user uploads digitally signed PDF when filing a Petition on mobile device 
* Login as petitioner / private practitioner 
* Create case 
* Upload digitally signed STIN 
* Upload digitally signed Petition
* Select Corporation as party type 
* Upload digitally signed ODS
* Review petition  
* View PDF previews on Review Your Case screen 
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 8)  Private practitioner user uploads digitally signed PDF when requesting access to case on mobile device 
* Login as private practitioner 
* Search for case w/o petitioner counsel 
* Click Request Access 
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 9)  irs Practitioner user uploads digitally signed PDF when filing first IRS document on mobile device 
* Login as irs practitioner 
* Search for case w/o respondent counsel 
* Click File First IRS Document 
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 10)  irs Practitioner user uploads digitally signed PDF when requesting access to case on mobile device 
* Login as irs practitioner 
* Search for case w/ respondent counsel 
* Click Request Access
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature 

#### 11) External user uploads digitally signed PDF when filing a document on mobile device 
* Login as petitioner / private practitioner / irs practitioner
* Go to case on your dashboard 
* Click File a Document 
* Upload digitally signed PDF 
* Complete form
* Review Filing 
* View PDF previews on Review Your Filing screen
Expected results 
- [ ] PDF preview displays digital signature 
- [ ] On submit, PDF on docket record displays digital signature

**Comment by mariahkannenberg** [comment]
In the modals, the individual pages are being rendered upon a <canvas> I think. odd - kris
Kristen aslo tested in other places, and only seems to be happening in preview modal.

**Comment by sutt0n** [comment]
Reason for bug: Mozilla's PDF.js dist (used for previewing) doesn't support signature widgets in PDFs, and therefore does not render them. Switched our previewer to `pdf-lib`
