### ISSUE TITLE
BUG: Scroll on dropdown missing

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7665]
**Describe the Bug**
The IRS reports that when they are trying to eFile documents, the scroll on the dropdown for "previously filed" documents is missing.  They could navigate using the up and down arrows, but this is not intuitive. Using Windows 10 with chromium Microsoft Edge browser.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
IRS attorney

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Using Windows 10 with chromium Microsoft Edge browser
1. Login as irsPractitioner1
2. Go to 21409-16
3. Try to file a Reply to...
4. Note that when you open the "What document are you filing a reply to?" dropdown, there is no obvious way to scroll up and down.

**Expected Behavior**
Scroll bar should be present on all dropdowns that are more than what is initially shown

**Actual Behavior**
Scroll bar not present.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/084a4244-d28f-4b13-90a8-9c99ec569c03)

**Desktop (please complete the following information):**
Windows 10 with chromium Microsoft Edge browser.

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
Tried creating scenarios on Windows 10 + Edge in which there were enough entries to warrant a scrollbar in the drop-down menu, and then also having entries whose titles were very, very long.  Unable to replicate the problem:

![Screenshot (3)](https://user-images.githubusercontent.com/2445917/119401359-0126ab00-bca1-11eb-8559-6db66c7da011.png)
![Screenshot (2)](https://user-images.githubusercontent.com/2445917/119401362-01bf4180-bca1-11eb-8a83-d7d2097dda49.png)
![Screenshot (1)](https://user-images.githubusercontent.com/2445917/119401364-01bf4180-bca1-11eb-919b-dc50bbe59758.png)

I'm wondering if it is still possible to replicate this issue by the IRS user or anyone with windows + edge?

**Comment by JessicaMarine** [comment]
@kkoskelin I am still able to replicate this in `mig` in 21409-16 but I think the issue is something a little different.  In that case, the titles of the documents still run off the page (to the right) versus being truncated. As a result, the vertical scroll is just too far to the right to see it.  I thought we had fixed this issue by truncating the length of documents listed in all dropdowns to 100 characters. https://github.com/flexion/ef-cms/issues/8065
