### ISSUE TITLE
BUG: Notice of Docket Change not generated with Attachment and C/S info changes

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7666]
**Describe the Bug**
When Docket is QC'ing a document and changes the "attachment" information (either selecting it or de-selecting it) and/or the certificate of service information (either selecting it, de-selecting it, or changing date), a notice of docket is not being generated.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as a Docket Clerk
2. QC a document and change "attachment" information (either selecting it or de-selecting it) and/or the certificate of service information (either selecting it, de-selecting it, or changing date)
3. Note that a Notice of Docket Change does not generate.

**Expected Behavior**
A Notice of Docket Change should generate when the Docket Clerk changes "attachment" information (either selecting it or de-selecting it) and/or the certificate of service information (either selecting it, de-selecting it, or changing date) on an eFiled document

**Actual Behavior**
A Notice of Docket Change is **not** being generated when the Docket Clerk changes "attachment" information (either selecting it or de-selecting it) and/or the certificate of service information (either selecting it, de-selecting it, or changing date) on an eFiled document

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by rachelschneiderman** [comment]
Original Story:
https://github.com/flexion/ef-cms/issues/3247

**Comment by klohman** [comment]
UX Review 

* When changing the Attachments during QC 
    - a new cover sheet was applied (and should not have been)

* When changing the Attachments during QC 
  - a new cover sheet was applied (and should not have been)

* When changing the date of Certificate of Service: 
   - a new cover sheet was applied (and should not have been)
