### ISSUE TITLE
BUG: Judge not able to open working session copy of the trial session (HOTFIX)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7667]
**Describe the Bug**
Judge is unable to open his working session copy of the trial session. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court Prod; able to replicate for 1/20 Washington DC session in Flexion's prod

**Who were you logged in as?**
Judge Carluzzo

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as Judge Carluzzo
2. Click on a trial session that's assigned to Judge Carluzzo

**Expected Behavior**
Judge Carluzzo's session copy opens up when he clicks on it. 

**Actual Behavior**
When he clicks on a trial session that is his, instead of opening the session copy, the system delivers an error message "We're experiencing technical problems. Try again or contact..."

He CAN, however, open other judges' working copy.

Related to misspelling of his name?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
proceedingType was made required on TrialSession entities and a migration script was added to default that value on trial sessions that did not have a proceedingType set. However, the migration did NOT default that value on hearings (which are also TrialSession entities) which was causing the case object to not validate.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by JessicaMarine** [comment]
Discovered this is likely due to not updating the hearing entity on cases.  400 error also being generated when trying to generate "Deadlines" report.
