### ISSUE TITLE
BUG: Updating a court issued document to a document type that does not require a coversheet should remove the existing coversheet, if it exists

### ISSUE THREAD

**Issue by rachelschneiderman** [ustaxcourt/ef-cms#7668]
**Describe the Bug**
When a court issued document is edited and the eventCode is changed from a document that requires a coversheet to one that does not, the coversheet is not removed from the document.

We currently do not have a good way to verify/identify if a coversheet is present on a given document. We can make the assumption that one is present based on the document's eventCode, but we can't be positive without adding some additional logic.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
local

**Who were you logged in as?**
docketclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Fixing bug ustaxcourt/ef-cms#7618

**To Reproduce**
1. Login as a docketclerk
2. Go to a case
3. 'Upload PDF'
4. Add a docket entry from the uploaded PDF, select 'HE' as the eventCode
5. Edit the docket entry
6. Change the eventCode to 'SOP'
7. See that the coversheet has not been removed from the document

**Expected Behavior**
The coversheet should have been removed from the document.

**Actual Behavior**
Coversheet is not removed from the document.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rosiehsmith** [comment]
For further context, was this related to AC in an existing story? We'd like to make sure any related regressions are covered when completing this.
