### ISSUE TITLE
BUG: White Screen when clicking on message

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7673]
**Describe the Bug**
There are times when I click on a message, either from my inbox or from within a case, and all I get is a white screen.  I recorded this error:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/9ff782d8-1899-42a2-8ebf-07f9f1c5c2b5)

When I refresh, the message loads, but the following is recorded in the log:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/1ea3e720-5687-433f-affa-80e262b0c06a)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Jessica Marine

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Click on a message from Message Inbox or from Case Messages within a case
2. Note that you are routed to a white screen (happens about 80% of the time but **NOT** every time)
3. Click refresh
4. Note the message loads

**Expected Behavior**
* Message loads when clicking on it without the need to hit refresh

**Actual Behavior**
* When clicking on a message, gets a white screen

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by kkoskelin** [comment]
ustaxcourt/ef-cms-flexion#7646

**Comment by kkoskelin** [comment]
Why not caught by test? It could have been caught only by a cypress test that interacts with the react form that relied upon being able to deconstruct the result of a helper.

**Comment by kkoskelin** [comment]
To verify: 
As a docket clerk
 * navigate to a case detail
 * Create > New Message. Select Section:Docket, recipient: Test DocketClerk1 (or yourself), add a subject and message.  do not choose any documents.  Send.
 * Upon success, navigate to Messages > Inbox and scroll to the bottom, locating your message, and click its title
 * Message should open up, showing the detail but no attachments.
 * Compose a reply on this message, selecting an attachment
 * Upon success, attachment will be shown.

If you can complete this workflow, the issue is resolved.

**Comment by JessicaMarine** [comment]
@kkoskelin I was able to run through the flow above, but I wanted to clarify that it wasn't the attachment in the iFrame that was coming up blank, it was the whole screen.  Does the solution above still resolve that?

**Comment by kkoskelin** [comment]
@JessicaMarine yes, your original issue was replicated in local environments before the code fix was in place in a mob. After we identified the issue in a view "helper" and addressed it, the problem no longer occurred.
