### ISSUE TITLE
BUG: Completed Messages Still Displaying in **SECTION** inbox and as "In Progress" within a case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7675]
**Describe the Bug**
Although we've corrected the bug (#7452) that was still displaying completed messages in an individual's inbox, the problem is persisting for the **section** inbox and on the "In Progress" messages on a case.

Related to https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7452

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as Jessica Marine
2. Go to individual inbox
3. Note that the completed message in 4888-20S is no longer showing in my personal inbox.
4. Go to section inbox.
5. Note that completed message in 4888-20S **IS** still showing in the section inbox.
6. Go to the case messages within 4888-20S.
6. Note that the completed message is still showing as "In Progress"

**Expected Behavior**
* Completed messages do not appear in **any** inbox or as "In Progress" within a case.

**Actual Behavior**
* Completed message still displaying in section inbox.
* Completed messages are still displaying as "In Progress" within a case.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/744499ab-7c1d-4509-9cb3-11aa085f6b93)

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e2ac72d7-21ba-4162-8dc8-420859ad08ca)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by matthopson** [comment]
As with ustaxcourt/ef-cms#7610, completed messages were not being filtered out of the user inbox query on ElasticSearch. Adding this filter on the section inbox query resolves the problem.

https://github.com/flexion/ef-cms/pull/7651

**Comment by matthopson** [comment]
Update: Addressing the messages stuck in Case Messages > In Progress

The same filters that exist when fetching messages for the user inbox did not exist in this section (though we fetch the messages directly from dynamo here). This issues is not easy to reproduce, but I managed to recreate the state from the given example messages. Here's a screen recording before and then after the fix that demonstrates both the section and case message bugs.

Before Fix
https://images.zenhubusercontent.com/152320868/15e8862c-394f-44a1-be47-4bd5f2f5aebd/screen_recording_2021_01_26_at_7_49_31_am.mov

After Fix
https://images.zenhubusercontent.com/152320868/2249cc7b-a819-47e7-9c35-214cea85b4a3/screen_recording_2021_01_26_at_7_51_27_am.mov

And I should have also demonstrated that those messages in the case detail are now completed.
![Screen Shot 2021-01-26 at 7.54.57 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/1637cfd6-4a96-4b13-9e8c-2f3e35a6c198)

**Comment by JessicaMarine** [comment]
Unable to test in Flexion's environment.  Will log additional bug if doesn't fix issue in Court's prod.
