### ISSUE TITLE
BUG: Edit Docket Entry: Unable to save / error thrown when updating doc type to MISC

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7676]
**Describe the Bug**
When editing a docket entry and changing the doc type to MISC, the form will not save. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
verifying bug 

**To Reproduce**
1. Go to case 
2. Click "Edit" for externally filed or paper-filed document 
3. Update doc type to MISC 
4. Click Save 

**Expected Behavior**
Form should save and updates should be reflected on the docket record. 

**Actual Behavior**
Form is not submitted. 

**Screenshots**
![Screen Shot 2021-01-25 at 3.13.59 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4aea50dc-d006-4881-91e9-d90fced7dcb7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by klohman** [comment]
## 7652 Tests

#### 1) Docket clerk updates document type to MISC when editing docket entry (new entry) 
* Login as docket clerk 
* Go to case 
* Click Edit for non-migrated externally filed or paper filed document 
* Change document type to MISC 
* Enter description 
* Click Save
Expected results 
- [ ] App routes to Docket Record with success message displayed 
- [ ] Entry is updated with new document type (MISC) and description under Filings and Proceedings 

#### 2) Docket clerk updates document type to MISC when editing docket entry (migrated entry) 
* Login as docket clerk 
* Go to case 
* Click Edit for migrated externally filed or paper filed document 
* Change document type to MISC 
* Enter description 
* Click Save
Expected results 
- [ ] App routes to Docket Record with success message displayed 
- [ ] Entry is updated with new document type (MISC) and description under Filings and Proceedings

**Comment by JessicaMarine** [comment]
Resolved by ustaxcourt/ef-cms#7706
