### ISSUE TITLE
BUG: Completing document in QC is not removing it from the Document QC Inbox

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7681]
**Describe the Bug**
Completed QC items are displaying in Document QC Inbox. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing 

**To Reproduce**
1. Go to Section Document QC 
2. Click on document link  (Reply to Simultaneous Opening Brief) 
3. Complete QC 

**Expected Behavior**
Completed item does not display in Inbox. Complete item displays in Processed box. 

**Actual Behavior**
Complete item is still displaying in Inbox. Completed item also displays in Processed box (inconsistently).

**Screenshots**
https://drive.google.com/file/d/1uM0CWUuWHm0ZbA4wzTGUPGd7xvucbP1A/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by JessicaMarine** [comment]
Closing -- after retesting with a new case and a document qc item (that wasn't messed up on Flexion's prod via the deploy mishap regarding 7673), we were unable to replicate 7672, and it seems that since this isn't on the court's environment, it's related to 7673 as initially assumed. should 7672 be closed since its problem is the same as 7673?
