### ISSUE TITLE
BUG: New work items (documents) not showing up in Section Document QC Inbox

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7682]
**Describe the Bug**
New e-filed documents are not displaying in Section Document QC inbox. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
testing 

**To Reproduce**
1. Login as party 
2. Go to case and efile a document 
3. Login as docket clerk 
4. Go to Section Document QC Inbox

**Expected Behavior**
New document should display in Inbox. 

**Actual Behavior**
New document does not display in Document QC Inbox. the document displays as needing QC on the docket record. 

**Screenshots**
![Screen Shot 2021-01-27 at 1.33.05 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9820f1cf-3ffc-444c-a476-ff432598b85c)
![Screen Shot 2021-01-27 at 1.33.22 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/157bd323-f620-484f-87a0-688002639ff1)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by kkoskelin** [comment]
What we've researched:
* we have used a script `test-elasticsearch.js` to communicate directly with the production instance of Elasticsearch that is supposed to be returning a work item -- but isn't.
* We wrote a query limiting the `pk` and `sk` to the item we expected to find, but it was not found.
* the work item itself *does* indeed appear to have been created in DynamoDB, but the stream to elasticsearch did not create the corresponding record.
Further analysis is ongoing.

**Comment by matthopson** [comment]
Some additional thoughts:

Looking at Section Document QC (for docketclerk), it's clear there's a gap in work items being indexed by elasticsearch - it goes from Jan 26, skips the 27, and then today (Jan 28) work items are showing up again. The last deploy to production was the day before (Jan 25). That day, we saw two failures while making that deploy that seemed to be related to network issues that were affecting the East Coast very heavily.

We've had a successful deploy this morning and things seem to be working as expected. We are no longer able to reproduce this issue.

**Comment by JessicaMarine** [comment]
Closing -- due to Elasticsearch issue in Flexion's prod.  Not able to reproduce
