### ISSUE TITLE
BUG: Updated full document title not displaying in document dropdown

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7683]
**Describe the Bug**
Additional Info information is not displaying in the document title in the previous document dropdown. 
- Edit Docket Entry 
- QC screen 
- File a document  

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual

**To Reproduce**
From QC screen 
- Login as petitioner 
- eFile Exhibits 
- Login as docket clerk 
- Click on Exhibits from QC Inbox
- Enter "First" in additional info 1 and click the add to coversheet
- Complete QC 
- Go to case 
- Add Paper filing 
- Select Amended 
- Select previous document Exhibits

**Expected Behavior**
The previous document dropdown should display the full document title, including additional info. 

**Actual Behavior**
The previous document dropdown does not display the additional info text. 

**Screenshots**
![Screen Shot 2021-01-28 at 10.19.07 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/54bd5fec-d2c2-442f-8cda-6a4f2155784f)
![Screen Shot 2021-01-28 at 10.19.15 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/993d1397-f151-4e7c-951b-9dfb77a6617c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
PR - https://github.com/flexion/ef-cms/pull/7795
`previouslyFiledDocument` was not computing full document title based on `addToCoversheet` value

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by rachelschneiderman** [comment]
I'm not seeing this fix on dev. Need to investigate.

**Comment by klohman** [comment]
![Screen Shot 2021-02-16 at 4.20.19 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ffec74a6-b3df-40a5-b89c-1042281f226f)

* Updated doc title now displays in document dropdown

**Comment by JessicaMarine** [comment]
@rachelschneiderman and team:

1. Log-in as IRS counsel Anne D. Melzer (DA0124) on `MIG`
2. Go to 4498-20
3. File a "First Amended Exhibit(s) to Stipulation of Facts (Exhibit 1-J)":
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e317696f-24a7-4fd8-8124-064174a08442) 

4. Note that the full concatenated title doesn't carry through to the:
File Your Document(s) screen:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/6fd0d138-9b9e-4a07-837d-753fb06bddc3)

Review Your Filing screen:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/f5a9ed06-7ca1-4640-97db-c38a26b301da)

Docket record:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/da64f911-ab66-40d3-9df6-86c34d71306a)

QC box:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/ffb2e5ee-c7e4-4e06-872e-adbae6d0f685)

The QC screen:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7ea92c9e-cf46-4331-aead-516c0f1b835f)

Or the cover sheet:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/141237b6-b782-42c6-b362-378ae85e6fea)

**Comment by rosiehsmith** [comment]
https://github.com/flexion/ef-cms/pull/7812
