### ISSUE TITLE
BUG: Typing a case detail URL w/ suffix or w/ a docket # that doesn't exist blank page

### ISSUE THREAD

**Issue by kkoskelin** [ustaxcourt/ef-cms#7685]
**Describe the Bug**
When typing a case detail URL w/suffix or with a docket number that does not exist, the user is directed to a blank page.

Note:
* When typing a case detail URL w/ suffix, the best solution would be to redirect the user to the case detail URL **w/o** the suffix
* When typing a case detail URL for a case (docket #) that doesn't exist, ensure that the user gets the "Case does not exist" error page

**Business Impact/Reason for Severity**
A "case not found" message should not break the app.

**In which environment did you see this bug?**
Court Mig

**Who were you logged in as?**
petitioner1@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Searching for a case by typing in the url for `/case-detail/1239-20S`

**To Reproduce**
1. Log in as petitioner1@example.com
2. paste the following url and go to `https://app.mig.ef-cms.ustaxcourt.gov/case-detail/1239-20S`
3. Page goes white/blank and dev tools show 404 error in console
4. Remove the "S" from the URL and note that the case loads

5. paste the following url and go to `https://app.mig.ef-cms.ustaxcourt.gov/case-detail/16000-20`
6. Note the white/blank screen and dev tools showing 404 error in console

**Expected Behavior**
* If user enters case detail URL with a suffix, the system should redirect the user to the case detail URL **w/o** the suffix so that the case loads
* If user enters case detail URL for case that doesn't exist, user should be routed to "Case does not exist" error page

**Actual Behavior**
Page went entirely blank after server returned the 404.

QUESTIONS: should we alter the `/case-detail/{docketNumber}` route to ignore suffixes perhaps? I'd suggest "yes".
Add'l info:  also fails similarly with a case which truly does not exist: https://dawson.flexion.us/case-detail/12222229-88

**Screenshots**
![Screen Shot 2021-01-28 at 12.48.22 PM.png](https://images.zenhubusercontent.com/5bbf750502b9b3375461a416/b4e4f41f-3ff3-4b55-9aa3-5310dc8bdbdb)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by kkoskelin** [comment]
This also seems to produce a similar app-breaking 404 when using the public interface (i.e. not logged-in)

**Comment by klohman** [comment]
Meets expected results 

**URL for casae that does not exist**
![Screen Shot 2021-03-10 at 4.11.48 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f4c24f06-bd86-4211-a91f-44fd763b3012)

**URL with suffix is routed to case**
![Screen Shot 2021-03-10 at 4.12.30 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/27c27801-7560-46cf-9dcd-42713201fd6b)
