### ISSUE TITLE
BUG: Signature not displaying in Firefox

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7687]
**Describe the Bug**
The signature of an IRS attorney is not showing up in Firefox.  It displays on the PDF in Chrome.

View of document in Chrome:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/fd7a6965-aee9-4045-a13f-8d807fbdce05)

View of same document in Firefox:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/23b6d2bb-a782-41b8-b75b-fad12fe24ff4)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 5752-20S in Chrome
2. Click on Proposed Stipulated Decision
3. Note that the R's counsel signature is on the document
4. Go to 5752-20S in Firefox
2. Click on Proposed Stipulated Decision
3. Note that the R's counsel signature is **not** on the document 

**Expected Behavior**
*PDFs (including signatures on them) should display consistently across browsers

**Actual Behavior**
* Signature is not displaying on PDF in Firefox
* Signature is displaying on PDF in Chrome

A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
Just a note for this: IF this signature is applied electronically and is considered a layer in the document like the eSigned sig, it may be the same issue we moved away from in the other viewer implementation. That old implementation relied on pdf.js (by Mozilla), which is also used natively in Firefox.

**Comment by kkoskelin** [comment]
Good news on this front: the `pdf.js` library appears to have implemented signatures per https://github.com/mozilla/pdf.js/pull/13214 
However, I cannot say when this code will make its way into a Firefox release, or if perhaps it is already working.
@JessicaMarine can we identify an actual real-life PDF with this kind of e-signature that is safe to be provided here?  One that developers can use for testing against chrome/edge/firefox/safari?

**Comment by JessicaMarine** [comment]
@kkoskelin Here is the offending PDF.
[https://app.zenhub.com/files/152320868/8cce53a4-ca6b-4a13-a552-1f29140143dd/download](https://app.zenhub.com/files/152320868/8cce53a4-ca6b-4a13-a552-1f29140143dd/download)

**Comment by kkoskelin** [comment]
The above link has a PDF which has been altered (sanitized?) in some manner.  However, this one appears to have the signature we desire for purposes of testing: [esig.pdf](https://github.com/flexion/ef-cms/files/6541590/esig.pdf)

**Comment by calixteman** [comment]
Signature display is available in Firefox beta (89) so next release will have it.

**Comment by kkoskelin** [comment]
Many thanks, @calixteman for the update!  Since a fix is forthcoming for Firefox *and* the number of affected internal users (those for whom it is most critical to see signatures) are using chrome/edge, closing this.
