### ISSUE TITLE
BUG: Unable to QC Entry of Appearance, Substitution of Counsel, or Limited Entry of Appearnance

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7688]
**Describe the Bug**
Docket clerk is unable to QC an entry of appearance or substitution of counsel or Limited Entry of Appearance.  Likely an issue will **ALL** request case access filings.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod; able to reproduce in Court's mig

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log into Court's `mig` environment as a Docket Clerk
2. Go to Section QC box
3. Select Entry of Appearance in 18623-18S (4th item down)
4. Try to Complete
5. Note that it just spins
6. Try to Complete & Send
7. Note that nothing happens

**Expected Behavior**
* Docket clerk is able to `Complete` or `Complete & Send` from the QC screen for an entry of appearance and substitution of counsel

**Actual Behavior**
* Docket clerk is **NOT** able to `Complete` or `Complete & Send` from the QC screen for an entry of appearance and substitution of counsel
* When trying to `Complete` the item, it just spins
* When trying to `Complete & Send`, nothing happens.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by klohman** [comment]
Errors received on court migration when completing 
![Screen Shot 2021-02-01 at 11.37.47 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9d3a9e96-252a-45d7-8b88-f76407d94433)
