### ISSUE TITLE
Bench Opinions: Include in Opinions Search

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7692]
As the Court, in order to have all of our opinions appear in the same place, Bench Opinions should be displayed in Opinions Search.

## Preconditions
* Bench opinion is served.

## Acceptance Criteria:
(Note: AC should include non-standard testing, deployment, documentation or security requirements)
* Bench Opinions (Doc Code OST) should appear as results in Opinion Search
* A bench opinion in a sealed case should return in the opinion search and the document should be viewable
* Unserved bench opinions do not return in Opinion search results
* opinion search type checkbox label is "Bench Opinion (Order of Service of Transcript)" 
* no changes to court issued event code or schema

## Notes
* OST =  Order of Service of Transcript (Bench Opinion)
* Should OST still display in Today's Orders? No.
* Should OST be searchable under Order Search? No.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Update to UI 
* Reorder Opinion type options (per user research) 
* Update "Bench" to "Bench Opinion (Order of Service of Transcript)" (per AC) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8145ec3d-92e3-46d0-89ed-5029c578ca79)

**Comment by klohman** [comment]
## 7704 Test Scenarios 

#### 1) Court user searches using Opinion search and sees served bench opinion In results 
* Create, save, and serve OST in case xx1-21 
    * Opinion has keyword “laughs”
* Login as court user 
* Go to Opinion search 
* Search keyword “laughs”
Expected results 
- [x] OST opinion in case xx1-21 returns in results 

#### 2) Court user searches using Opinion search and does not see unserved bench opinions in results 
* Create, save, and serve OST in case xx1-21 
    * Opinion has keyword “laughs”
* Create, save OST in case xx2-21 (do not serve) 
    * Opinion has keyword “laughs”
* Login as court user 
* Go to Opinion search 
* Search keyword “laughs”
Expected results 
- [x] OST opinion in case xx1-21 returns in results 
- [x] OST opinion in case xx2-21 does not return in results 

#### 3) Court user searches for bench Opinion in sealed case and sees bench opinion in results 
* Create, save, and serve OST in sealed case xx3-21 
    * Opinion has keyword “Andy” 
* Create, save OST in sealed case xx4-21 (do not serve) 
    * Opinion has keyword “Andy” 
* Login as court user 
* Go to Opinion search 
* Search keyword “Andy”
Expected results 
- [x] OST opinion in case xx3-21 returns in results 
- [x] OST opinion in case xx4-21 does not return in results 

#### 4) Court user searches for bench Opinion in unsealed case and views Opinion PDF 
* Scenario 2 
* Click PDF link for case xx2-21 
Expected results 
- [x] PDF document opens in new tab 

#### 5) Court user searches for bench Opinion in sealed case and views Opinion PDF 
* Scenario 3 
* Click PDF link for case xx3-21 
Expected results 
- [x] PDF document opens in new tab 

#### 5) Court user searches by Bench Opinion and date range using Opinion search and sees matching bench opinions in results 
* Create, save, and serve OST for case xx5-21
    * Date [current date]
* Go to opinion search 
* Search for 
    * Opinion type = OST 
    * Custom date - start date = [current date]
Expected results 
- [ ] OST opinion in case xx5-21 returns in results 


#### 6) Court user views option to search by "Bench Opinion (Order of Service of Transcript)"
* Login as court user 
* Go to Opinion search 
Expected results 
 - [ ] Opinion type field includes"Bench Opinion (Order of Service of Transcript)"

**Comment by klohman** [comment]
Note: We can probably remove the "judge" portion from this AC: "Bench Opinions can be filtered by Judge and/or Date Range" 

- the judge association and filtering will be handled in ustaxcourt/ef-cms#8060 

@cholly75

**Comment by cholly75** [comment]
@klohman Done!

**Comment by ujahio** [comment]
https://github.com/flexion/ef-cms/pull/9010
