### ISSUE TITLE
BUG: IRS seeing wrong service indicator on primary petitioner before being associated with case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7694]
**Describe the Bug**
Before an IRS attorney is associated with a case, they are seeing the wrong service indicator on the primary petitioner.  They will see "Electronic", but then it switches to "Paper" after being associated with case.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's Prod; able to re-create in Court's mig

**Who were you logged in as?**
IRS attorney

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in to Court's mig as an IRS attorney (who is not associated with 5084-20)
2. Go to 5084-20
3. Note that the primary petitioner's service indicator is "Electronic" even when there is no email displayed
4. File an Entry of Appearance to become associated with the case
5. Note that the primary petitioner's service indicator is really "Paper"

**Expected Behavior**
* IRS will see petitioner's accurate service indicator before they are associated with the case

**Actual Behavior**
* IRS attorneys are seeing Electronic as service indicator on **primary** petitioner before they are associated with the case, even though the Petitioner's real service indicator is Paper
* This does not seem to be affecting the secondary petitioner

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e30cd646-9795-4535-868d-4002d7dc1184)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/bf089e8c-7b5b-4836-9274-a46d491f4cea)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/b1ebcdd9-0f5f-404d-80f0-d1346a486f5e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Flexion prod environment.
 - [x] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by klohman** [comment]
* This is happening on migration for legacy petitioners with counsel as well, and a service indicator of "none" 
* This does not happen on Migration with a new paper filed case. IRS attorney sees "Paper" when not associated.

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/7757

The cause of the issue was the PublicCase entity was not conveying the `isPaper` flag, which affects how the service indicator is computed for the petitioner.
