### ISSUE TITLE
BUG: Unable to add trial transcript to docket record

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7699]
**Describe the Bug**
Docket Clerk is unable to add a trial transcript to the docket record.  ~~The attorneys on the case were also inexplicitly removed.~~(move to separate bug)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod; able to reproduce in Court's mig

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 16724-19
2. Upload the following document through "Upload PDF": [https://app.zenhub.com/files/152320868/2ca8bdfe-84ee-4cce-9ade-66265cc93fac/download](https://app.zenhub.com/files/152320868/2ca8bdfe-84ee-4cce-9ade-66265cc93fac/download) or note that the PDF is already in the Drafts tab
3. Try to add the Trial Transcript to the Docket Record: Transcript of Los Angeles, CA (Remote Proceeding) (Partial Trial) (Volume 1) on 10/29/20

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/40357eaa-e01b-4091-9ee2-7c9ea281af18)
4. Note that the system throws a 400 error.

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/5b55d063-d791-4d50-80bb-78cc85ea71b2)

**Expected Behavior**
* Docket Clerk can add PDF of transcript to docket record

**Actual Behavior**
* System is throwing error when Docket Clerk tries to add PDF of transcript to the docket record

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

Document contents were being retrieved whenever a case was being retrieved

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Court's migration environment.
 - [ ] Bug has been tested in Court's migration environment (UX or Engineering).

**Comment by JessicaMarine** [comment]
Eric and Jessica pair to troubleshoot -- discovered that when uploading the PDFs through the "PDF Upload" feature, it's adding the entire content of the PDF to the case entity which is causing it to size out.  Tried with 2 separate PDFs -- same result.

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/9007cdf2-72f0-4ad9-8585-a4dc88563121)

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/63ddca32-4b07-4aad-bf61-af514129b851)

**Comment by mmarcotte** [comment]
It appears that we are again hitting the 1MB limit for our DynamoDB. 

When I query this case in DynamoDB, I get a `LastEvaluatedKey`, which means we need to use that in [order to retrieve more information](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html). When I use that key as an `ExclusiveStartKey` in a subsequent query I get the rest of the information including:

```
{
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|0a0fb8d6-398f-4e17-9da7-90e2b921730e' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|12cbd9d5-5caf-4b80-8bab-c17fe6e2ff6f' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|3dc9c312-068a-4aed-b70f-6fe562b9cb47' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|8a3503ec-e9eb-4307-a488-9b87029b7adb' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'privatePractitioner|f28a9bfe-68b8-4df2-ae7b-6d305115b39c' }
  },
```

amongst other items.

It would appear that `getCaseByDocketNumber` needs to paginate if `LastEvaluatedKey` exists in the response.

**Comment by sutt0n** [comment]
It appears there may be two problems here: 

1) `documentContents` getting stored onto `Case.docketEntries` and bloating the Case item
2) The Case item becoming too large, thus resulting in necessary pagination (causation of ustaxcourt/ef-cms#6491?)

**Comment by sutt0n** [comment]
After some discussion, a second bug will be created to address item 2 in the previous comment.

Furthermore, a migration will be created to remove a nested `draftOrderState.draftOrderState` on the docket entry (after investigation, it was determined that was being added after modifying a draft order), and fix the problem with nesting the `draftOrderState` property.

Draft PR: https://github.com/ustaxcourt/ef-cms/pull/846
