### ISSUE TITLE
BUG: getCaseByDocketNumber larger than 1MB

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7703]
**Describe the Bug**
When `getCaseByDocketNumber` is larger than 1MB, part of the case gets dropped.  In 16724-19, the case was larger than 1MB (due to bug addressed in ustaxcourt/ef-cms#7699) and the attorneys on the case (4 respondent's counsel & 1 practitioner's counsel) got dropped -- no longer showing in UI and not able to access the case. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Docket Clerk -- saw that the attorneys were missing in the UI
Practitioners -- not able to access case anymore

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Docket Clerk -- trying to add transcript to docket record
Practitioners -- trying to view case files

**To Reproduce**
1. Go to16724-19
2. Note that no practitioners are shown in the UI for respondent or petitioner

**Expected Behavior**
* Case larger than 1MB returns entire case

**Actual Behavior**
* Case larger than 1MB is not returning entire case (see comment)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
`LastEvaluatedKey` was not being used to retrieve full case.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the Court's migration environment.
 - [x] Bug has been tested in Court's migration environment (UX or Engineering).

**Comment by JessicaMarine** [comment]
From @mmarcotte:

It appears that we are again hitting the 1MB limit for our DynamoDB. 

When I query this case in DynamoDB, I get a `LastEvaluatedKey`, which means we need to use that in [order to retrieve more information](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html). When I use that key as an `ExclusiveStartKey` in a subsequent query I get the rest of the information including:

```
{
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|0a0fb8d6-398f-4e17-9da7-90e2b921730e' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|12cbd9d5-5caf-4b80-8bab-c17fe6e2ff6f' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|3dc9c312-068a-4aed-b70f-6fe562b9cb47' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'irsPractitioner|8a3503ec-e9eb-4307-a488-9b87029b7adb' }
  },
  {
    pk: { S: 'case|16724-19' },
    sk: { S: 'privatePractitioner|f28a9bfe-68b8-4df2-ae7b-6d305115b39c' }
  },
```

amongst other items.

It would appear that `getCaseByDocketNumber` needs to paginate if `LastEvaluatedKey` exists in the response.

**Comment by DWLarsen** [comment]
Checking if my access let's me comment.  Disregard.

**Comment by TomElliottFlexion** [comment]
PR here: https://github.com/flexion/ef-cms/pull/7788

**Comment by klohman** [comment]
Counsel for petitioner and respondent now displaying

![Screen Shot 2021-02-16 at 3.55.12 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c310e78f-be01-4d7b-ae3e-7ced8f0a47a4)
