### ISSUE TITLE
BUG: Transcript should be viewable after 90 days

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7705]
**Describe the Bug**

Respondent counsel should have access to a Transcript document since it is after the 90 days from when it was filed. 

**Business Impact/Reason for Severity**

Documents need to be made available to relevant parties in a timely manner.

**In which environment did you see this bug?**

* Court's Prod
* Migration Environment

**Who were you logged in as?**

`2c895af2-b486-4b79-ac5f-838e03c6b78c` (IRS Practitioner - Albert Brewster) 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Reported via Support Tickets

**To Reproduce**

1. Run `npm run admin:become-user 2c895af2-b486-4b79-ac5f-838e03c6b78c` to associate your account with that user
2. Go to https://app.mig.ef-cms.ustaxcourt.gov/
3. Login with your account and become that user
4. Navigate to case: 13063-18
5. Scroll down to docket index 53, 07/07/20, TRANSCRIPT OF 7/2/20 RECEIVED. (TELEPHONIC HEARING)

**Expected Behavior**

Trial transcripts (doc code `TRAN`) should be accessible (hyperlinked and viewable) to parties since it's after 90 days.  See https://github.com/flexion/ef-cms/issues/3909

**Actual Behavior**

It is not clickable

**Screenshots**

<img width="1904" alt="Screen Shot 2021-02-11 at 10 56 00 AM" src="https://user-images.githubusercontent.com/5023502/107661928-c0f26e00-6c57-11eb-82f8-458ba8d076d7.png">

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by rachaelparris** [comment]
Legacy transcript added on dev on case `105-21` - index 6.

**Comment by klohman** [comment]
Tested legacy transcript in 105-21, and 3 other unservable docs (HE, USCA, PRTL), with expected results

**Comment by JessicaMarine** [comment]
PO Review:  The 90-day clock does not seem to be running from the trial/hearing date.  I backdated a trial/hearing to 10/1/2020 and the transcript was still not viewable to the parties.
