### ISSUE TITLE
BUG: Unable to edit migrated Order (code "O") due to validation error

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7711]
**Describe the Bug**
When trying to edit a docket entry for a migrated Order (with event code O), user receives an error message to select a service stamp and cannot save any changes. 

The service stamp (Entered or Entered and Served) is required when adding a "O" event code to the docket record, but should be ignored after the entry is served. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court migration

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
validating bug for Jessica

**To Reproduce**
1. Go to 15108-19
2. Click Edit link for entry ustaxcourt/ef-cms#6499
3. Update anything and click Save 

**Expected Behavior**
Updates should be saved to the docket entry. 

**Actual Behavior**
Validation error is received to select a service stamp. The service stamp field does not display on this form.

Per Jessica - For orders, we need the ability to update the docket entry language -- not the served/entered & served info.  Can we ignore the serviceStamp when editing migrated "O" entries

**Screenshots**
![Screen Shot 2021-02-18 at 1.36.48 PM.png](https://images.zenhubusercontent.com/5bd7271
508843955cc24d3d0/1bc59df3-a21d-45b6-96bd-5ab071e4f827) 

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]- Chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
The serviceStamp does not seem to be set for migrated entries with code "O" but is a required field for that event code. 

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
When I created a new entry with event code "O", i see serviceStamp on the docket entry. This seems to be missing for migrated entries. 

 ![Screen Shot 2021-02-18 at 1.45.15 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/30387889-ddba-4269-bfd8-025ba964b921)

**Comment by rachaelparris** [comment]
Legacy order added to 105-21 on dev - index 5
