### ISSUE TITLE
Edit note on hearings after case is scheduled (Dave S)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7713]
As a Docket Clerk, I need the ability to edit a calendar note for a hearing without removing and re-adding the case.

## Pre-Conditions
Case has been set for hearing

## Acceptance Criteria

* Docket clerk has the ability to edit a calendar note on a hearing
* Docket clerk cannot delete a calendar note on a hearing
* When a docket clerk adds a calendar note after the case is added to trial, the calendar note displays on the Trial Session screen and the Printable Trial Session PDF
* When a docket clerk edits a calendar note after the case is added to trial or hearing, the updated calendar note displays on the Trial Session screen and the Printable Trial Session PDF

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court Mig env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
Test Scenarios 
 
#### 1) Docket Clerk adds a case to hearing with calendar note and then edits note
* Login as docket 
* Go to case 
* Add case to hearing 
* Click Add / Edit Calendar Note 
* Update text in note field 
* Click Save 
Expected results 
On click of Add/Edit Calendar Note 
- [x] Add/Edit Calendar Note modal displays 
- [x] Note field is populated with current note text 
On click of Save 
- [x] Modal closes 
- [x] Updated note text displays on the Hearings Card 

#### 2) Docket Clerk adds a hearing note, if character validation fails, display error message: Limit is 200 characters. Enter 200 or fewer characters.
* Login as docket clerk 
* Go to case 
* Click Set for Hearing 
* Enter text in note field = 201 characters 
* Save 
Expected results 
- [x] Error message displays on note field : “Limit is 200 characters. Enter 200 or fewer characters.”

#### 3) Docket Clerk edits a hearing note, if character validation fails, display error message: Limit is 200 characters. Enter 200 or fewer characters.
* Login as docket clerk 
* Go to case 
* Click Set for Hearing  
* Enter text in note field = 200 characters 
* Click Add Case 
* Click Add/Edit Calendar note 
* Update text in note field = 201 characters
Expected results 
- [x] Error message displays on note field : “Limit is 200 characters. Enter 200 or fewer characters.”

#### 4) Docket Clerk adds a case to hearing, then edit a calendar note and views note on Trial Session screen
* Login as docket clerk 
* Go to case 
* Add to hearing
* Click Edit link, and Add/Edit Calendar Note 
* Enter text in note field 
* Click Save
* Click trial location link on trial card 
Expected results 
- [x] App routes to Trial Session Detail 
- [x] Calendar Note displays on case list table 

#### 5) Docket Clerk adds a case to trial, then adds a calendar note and views note on Printable Trial Session
* Scenario 4
* Click Print link on Trial Session Detail 
Expected results 
- [x] App routes to Printable Trial Session PDF  
- [x] Calendar Note displays on the Printable Trial Session PDF

**Comment by cnelsonflexion** [comment]
![hearings-editmenu.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/c2bc04de-1ff1-4947-8bec-64d197ffb939)

Hearings Card - edit menu

**Comment by cnelsonflexion** [comment]
![hearing-addeditnote.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/db58c2e8-bc09-483f-a2f5-0ef44e7bc650)

Hearing Add/edit note modal

**Comment by klohman** [comment]
@matthopson @codyseibert @dsalls 

Only thing I saw in my review is that the Delete option should not be there for notes for Hearings. The note on a hearing is required so it cannot be blank. When I deleted all the text and saved, system bumped me out. Same thing happened when i clicked Delete here

![Screen Shot 2021-02-26 at 4.21.41 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eebc8606-f70d-47be-a0e1-eb744ad5991c)

**Comment by matthopson** [comment]
The issue with delete note is fixed on dev. We didn't see any requirements indicating the hearing note is required. This is going to need more thought, because we're re-using trial session and trial session note entities for validation - which have the note as optional OR max 200 characters.
