### ISSUE TITLE
BUG: IRS Superuser sees endless spinner when viewing a case without a Petition docket entry

### ISSUE THREAD

**Issue by rachaelparris** [ustaxcourt/ef-cms#7718]
**Describe the Bug**
The IRS Superuser sees an endless spinner when viewing a case detail for a legacy case without a Petition docket entry.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
local

**Who were you logged in as?**
irsSuperuser@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Investigating [this](https://trello.com/c/Mk2FImhM/873-look-for-places-where-we-get-a-petition-document-by-event-code-and-check-its-servedat-date) trello card

**To Reproduce**
1. Create a local migrated case without a Petition docket entry by modifying the seed data or using dynamo admin. (Legacy cases do not necessarily have a Petition docket entry, and this is valid.)
2. Log in as the IRS Superuser and navigate to the case detail for that case.

**Expected Behavior**
The case detail is displayed

**Actual Behavior**
A spinner is displayed and a console error is thrown.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
FYI: I believe this issue is only on a local dev environment. The IRS Super User belongs to another User Pool that isn't accessed by the normal login flow. They get authenticated only to access the v1 and v2 APIs.
