### ISSUE TITLE
Spike: Find all the instances where the app is failing quietly

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7719]
## Acceptance Criteria
* Find all of the instances where the app is failing quietly, so we can come up with a plan for addressing failures - both on the back end (logging) and in the UI
    * Go through interactors and persistence methods and note if they look they're not handling an exception properly. 
 * User stories are created to address areas where we want to improve or create logging and error messages [(new story)](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8074)
* When stories are created, add the questions below in the notes section.  

## Notes
- What detail can/should appear in logs to aid in diagnosis? Add this question to the user story when we create. 
- When should errors be thrown all the way up to the lambda handler? Add this question to the user story when we create. 
- If some unforeseen error occurs, what's the least obtrusive way to communicate it to the user? Add this question to the user story when we create. 

### Use Cases
- [x] Case Association (Cody, Rosie, Jojo)
- [x] Case Association Request (Cody, Rosie, Jojo)
- [x] Case Consolidation
- [x] Case Deadline
- [x] Case Inventory Report
- [x] Case Note
- [x] Case Statistics
- [x] Correspondence
- [x] Court Issued Document
- [x] Court Issued Order
- [x] Docket Entry
- [x] Document
- [x] Edit Docket Entry
- [x] External Document
- [x] Health
- [x] Manual Association
- [x] Messages
- [x] Migration
- [x] Notifications
- [x] PDF
- [x] Pending Items
- [x] Practitioners
- [x] Public
- [x] Serve Case To IRS
- [x] Start Case
- [x] Trial Sessions
- [x] Users
- [x] Work Items

### Persistence 

* Note: Look into if these methods are using AWS SDK, and verify return the type versus throwing an exception. For example, `SES.sendBulkTemplatedEmail` returns an error for a given email instead of an exception.

- [x] Cognito
- [x] Dynamo
  - [x] Case Deadlines
  - [x] Cases
  - [x] Correspondence
  - [x] Documents
  - [x] Helpers
  - [x] Messages
  - [x] Notifications
  - [x] Trial Sessions
  - [x] User Case Notes
  - [x] Users
  - [x] Work Items
- [x] Dynamsoft
- [x] ElasticSearch
  - [x] Case Deadlines
  - [x] Messages
  - [x] Work Items
- [x] LocalStorage
- [x] S3
- [x] SES

**Comment by matthopson** [comment]
- Start with try/catch blocks in interactors to verify errors are making their way up
- Generic handler for lambda already decorates lambda to log errors and return to user
- Empty error() path in sequences

**Comment by sutt0n** [comment]
Here is a list of missing error handling on front-end:


### Missing Error Handlers (UI)
- [ ] Delete Other Statistics `deleteOtherStatisticsSequence`
- [ ] Deleting Trial Session `deleteTrialSessionSequence`
- [ ] Sealing a Case `sealCaseSequence`
- [ ] Submitting Deficiency Statistics `submitAddDeficiencyStatisticsSequence`
- [ ] Submitting Other Statistics `submitAddOtherStatisticsSequence`
- [ ] Editing Deficiency Statistics `submitEditDeficiencyStatisticsSequence`
- [ ] Editing Other Statistics `submitEditOtherStatisticsSequence`
- [ ] Submit Trial Session `submitTrialSessinoSequence`
- [ ] Update Practitioner User `submitUpdatePractitionerUserSequence`
- [ ] QC Complete for Trial `updateQcCompleteForTrialSequence`
- [ ] Update Trial Session `updateTrialSessionSequence`
- [ ] Validate Primary Contact `validatePrimaryContactSequence`
- [ ] Validate Secondary Contact `validateSecondaryContactSequence`
