### ISSUE TITLE
Docket Clerk: Ability to add additional information when adding a Minute Sheet to the docket record

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7721]
As a Docket Clerk, in order to provide more information about what happened at a trial or hearing, I need to the ability to add some additional text to the docket entry when adding a Minute Sheet.

## Acceptance Criteria
* When adding a the following to the docket record, docket clerk needs the ability to add some additional free-text to be appended to the end of the document title:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/c985d992-1f26-4544-ad74-3c7f5e0e0f00)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* What should the character limit be? Same as orders for free text 
* Is this field required? No
* Any concerns with old documents (before this change)? Moot. Only concern if it was a required field.
         * All examples are Scenario **F**

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by matthopson** [comment]
- What should the character limit be?
- Is this field required?
- Any concerns with old documents (before this change)?

*All examples are Scenario F

**Comment by klohman** [comment]
## Add Docket Entry screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3d13d788-47b8-4203-9f02-d06d1cc81422)

#### Description field 
* Add Description field to form if these codes are selected: 
    - FTRL
    - PTRL 
    -  TRL
    - HEAR 

* Description field is optional 
* Character limit = 1000
    - if over character limit, display error: “Limit is 1000 characters. Enter 1000 or fewer characters.”

#### Docket entry preview 
* Preview should include text entered in Description field 
* Preview format : [Document type] [Judge name] at [Trial location]. [Description]

## Docket entry (Docket Record)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c0a587d8-fc8f-4c27-83a0-df35ebb638ec)

* Entry format : [Document type] [Judge name] at [Trial location]. [Description]
* Description is included in the document title (everywhere the document title displays in app) 

## Edit Docket Entry screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/881236d0-9c41-461b-b275-b789b8b141bf)

#### Description field 
* Add Description field to form if these codes are selected: 
    - FTRL
    - PTRL 
    -  TRL
    - HEAR 

* Description field is populated if text was entered and saved 

* Description field is optional 

* Character limit = 1000
    - if over character limit, display error: “Limit is 1000 characters. Enter 1000 or fewer characters.”

#### Docket entry preview 
* Preview should include text entered in Description field 
* Preview format : [Document type] [Judge name] at [Trial location] [Description]

**Comment by klohman** [comment]
## 7863 Test Scenarios 

#### 1) Docket clerk selects [FTRL, PTRL, TRL, HEAR] as document type when adding a docket entry 
* Login as docket clerk 
* Go to case 
* Upload PDF (4 times) 
* Add Docket Entry 
* Select document type 
   - FTRL 
   - PTRL 
   - TRL 
   - HEAR 

Expected results 
- [x] Judge’s name, Trial location, and Description field display in form


#### 2) Docket clerk adds description with 1001 characters for [FTRL, PTRL, TRL, HEAR]  when adding docket entry 
* Scenario 1
* Enter 1001 characters into Description field 
* Complete form 
* Click Save Entry 
Expected results 
- [x] Error message displays on Description field : “Limit is 1000 characters. Enter 1000 or fewer characters.”

#### 3) Docket clerk adds description with 1000 characters for [FTRL, PTRL, TRL, HEAR]  when adding docket entry and views preview
* Scenario 1 
* Select Judge Buch as judge 
* Select Mobile, Alabama as trial location
* Enter 1000 characters into Description field 

Expected results 
- [x] Docket entry preview displays accurately 
       - If FTRL selected , preview displays as “Further Trial before Judge Buch at Mobile, Alabama. [description text]”
       - If PTRL selected , preview displays as “Partial Trial before Judge Buch at Mobile, Alabama. [description text]”
       - If TRL selected , preview displays as “ Trial before Judge Buch at Mobile, Alabama. [description text]”
       - If HEAR selected , preview displays as “Hearing before Judge Buch at Mobile, Alabama. [description text]”

#### 4) Docket clerk sees description in docket entry for [FTRL, PTRL, TRL, HEAR]
* Scenario 3 
* Click Save Entry 
* View Docket Record 
Expected results 
- [x] Docket entry  displays accurately for each doc type: 
       - If FTRL selected , entry displays as “Further Trial before Judge Buch at Mobile, Alabama. [description text]”
       - If PTRL selected , entry displays as “Partial Trial before Judge Buch at Mobile, Alabama. [description text]”
       - If TRL selected , entry displays as “ Trial before Judge Buch at Mobile, Alabama. [description text]”
       - If HEAR selected , entry displays as “Hearing before Judge Buch at Mobile, Alabama. [description text]”
- [x] Document title hyperlink includes the description text 

#### 5) Docket clerk edits docket entry for [FTRL, PTRL, TRL, HEAR]
* Scenario 4
* Click Edit link next to docket entry 
   - FTRL 
   - PTRL 
   - TRL 
   - HEAR 
Expected results 
- [x] App routes to Edit Docket entry screen 
- [x] Document type field is populated 
   - FTRL 
   - PTRL 
   - TRL 
   - HEAR 
- [x] Judge field is populated = Judge Buch 
- [x] Trial location is populated = Mobile, Alabama
- [x] Description field is populated = [description text]

#### 6) Docket clerk does not add description for [FTRL, PTRL, TRL, HEAR] when adding a docket entry 
* Upload PDF (4 times) 
* Add Docket Entry 
* Select document type 
   - FTRL 
   - PTRL 
   - TRL 
   - HEAR 
* Select Judge = Ashford 
* Select Trial location = Phoenix, Arizona 
* Filed date = [current date]
* Click Save Entry 
Expected results 
before Save Entry:
- [x] Docket entry preview displays accurately: 
       - If FTRL selected , entry displays as “Further Trial before Judge Ashford at Phoenix, Arizona. ”
       - If PTRL selected , entry displays as “Partial Trial before Judge Buch at Phoenix, Arizona.”
       - If TRL selected , entry displays as “ Trial before Judge Ashford at Phoenix, Arizona.  ”
       - If HEAR selected , entry displays as “Hearing before Judge Ashford at Phoenix, Arizona. ”
After Save Entry: 
- [x] Docket entry on Docket Record displays accurately: 
       - If FTRL selected , entry displays as “Further Trial before Judge Ashford at Phoenix, Arizona. ”
       - If PTRL selected , entry displays as “Partial Trial before Judge Buch at Phoenix, Arizona. ”
       - If TRL selected , entry displays as “ Trial before Judge Ashford at Phoenix, Arizona.  ”
       - If HEAR selected , entry displays as “Hearing before Judge Ashford at Phoenix, Arizona. ”
