### ISSUE TITLE
Public: Sortable Today's Orders (Smaller story)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7724]
As the public, in order to find the substantive orders issued by the Court, I need the ability to sort Today's Order by page number.

## Pre-Conditions
* More than one order appears on Today's Orders

## Acceptance Criteria
* User should be able to sort the list of Today's Orders by page count.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* What should the default sort be (served datetime / page count)? The way it currently is served date and time.
* Can you toggle between this sorting method and another (the current, default sort perhaps) sorting method? Ability to switch the sort to change to page count. 
* Are we sorting what what's visible (within the paginated set), or all, pre-pagination? If more than 100 is it sorting that 100 or everything? A user would expect it to sort everything. 

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by matthopson** [comment]
- What should the default sort be (served datetime / page count)?
- Can you toggle between this sorting method and another (the current, default sort perhaps) sorting method?
- Are we sorting what what's visible (within the paginated set), or all, pre-pagination?

**Comment by cnelsonflexion** [comment]
![TodaysOrders.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/fb6c99ad-c841-4212-a0d3-a70cce48a609)

**TEST CASES**

- Browse to Today’s Orders

**Expected results** 
- [x] Sort control should appear above table of entries
- [x] Table of entries should be sorted by newest by default
- [x] Select control should have the following options:
- Sort by oldest
- Sort by newest
- Sort by pages (descending)
- Sort by pages (ascending)

**Sort by newest**
- [ ] Reorders the table entries with the record(s) created most recently appearing in order according to the date/time attribute.

**Sort by oldest**
- [ ] Reorders the table entries with the oldest record(s) created appearing in order according to the date/time attribute.

**Sort by pages (descending)**
- [ ] Reorders the table entries with the record(s) containing the highest page count appearing first, followed by the record with the second highest, and so on.
- [ ] Records containing an identical number of pages should be ordered via secondary sort of **newest**

**Sort by pages (ascending)**
- [ ] Reorders the table entries with the record(s) containing the lowest page count appearing first, followed by the record with the second lowest, and so on.
- [ ] Records containing an identical number of pages should be ordered via secondary sort of **newest**

**Multi-page sort**
- [ ] If the number of records exceeds 100 resulting in paging, the total results should be sorted by the selected sort option.

**Comment by kkoskelin** [comment]
web-api/elasticsearch/efcms-docket-entry-mappings.js will be getting a new type for the "numberOfPages" column and will necessitate a reindexing before this column can be used for sorting.
