### ISSUE TITLE
BUG: Signature/Served stamp overlay issue

### ISSUE THREAD

**Issue by mrinsin** [ustaxcourt/ef-cms#7728]
**Describe the Bug**

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
mig

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
quarterly testing the Stip Decision flow

**To Reproduce**
1. Log in as private practitioner, e-file a proposed stip decision on a served case
2. Log in as a docket clerk, complete QC and send message with the proposed stip decision attached, to Judge Ashford
3. Log in as Judge Ashford, sign the proposed stip decision (place the signature at the bottom of the pdf) and reply to the message
4. Log in as docket clerk, serve the Stip Decision

**Expected Behavior**
* The Stipulated Decision PDF should display the signature stamp (complete with Judge label) and the served stamp
* Don't allow the signature stamp to be applied so low on the page that the Served stamp would occupy same space

**Actual Behavior**
The judge label line (from the signature stamp) and the served stamp compete for the same spot - only one of those stamps shows up at a time

**Screenshots**
How it looks when the signature and served stamp are in the same part of the PDF:

![image.png](https://images.zenhubusercontent.com/5e5e93c9fa78057303bcc6ac/4a658109-c9c2-447c-ae16-6285414889ee)

How it looks when they are on different parts of the PDF:

![image.png](https://images.zenhubusercontent.com/5e5e93c9fa78057303bcc6ac/d8c046c5-13a4-4940-925e-11254a74e34d)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by sutt0n** [comment]
Note: Could restrict signature area by a percentage of the y-axis before applying/signing.

**Comment by klohman** [comment]
* Seeing an overlap when creating an Order through the system, signing, and serving. This doesn't seem to be a problem when signing uploaded PDFs



#### Apply Signature screen 
* after creating the Order in the system, this is where i placed the signature on the Apply Signature screen (above the restricted area) 
![Screen Shot 2021-03-09 at 9.26.04 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d0a280ef-52fa-462e-b50b-e28e88cb1387)

#### Saved Signature 
* This is after the signature is saved...signature is in slightly different place 
![Screen Shot 2021-03-09 at 9.26.41 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7759beee-f6bd-4d60-a537-a993cc26012f)

#### After Service 
* served stamp applied over the signature 

![Screen Shot 2021-03-09 at 9.27.44 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8587e3f7-9c37-4891-b746-00e018fd47ba)
