### ISSUE TITLE
BUG: Logged out when trying to view document QC processed tab

### ISSUE THREAD

**Issue by mrinsin** [ustaxcourt/ef-cms#7730]
**Describe the Bug**
Docket clerk is logged out of the app when trying to view Section Document QC Processed tab

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing

**To Reproduce**
1. Log in as docket clerk
2. Navigate to Section Document QC > Processed tab

**Expected Behavior**
User should be able to view documents in Processed tab

**Actual Behavior**
User is logged out of app, network tab shows error on /served endpoint call but no error or response printed
NOTE - looking at Kibana logs, the request to `/served` seems to have returned a 200 status.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5e93c9fa78057303bcc6ac/abe9ee10-a712-41c0-ac01-5df0d2e43835)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - Chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by rosiehsmith** [comment]
Could not reproduce this on migration

**Comment by JessicaMarine** [comment]
@rosiehsmith I'm seeing that this couldn't be reproduced on `mig`, but this is still happening on the Court's test environment.  I will check to see if this still happens when we deploy PR63 to `prod`.  If so, we'll need to revive this bug.

**Comment by JessicaMarine** [comment]
@rosiehsmith This is still occurring on the Court's prod environment after deploying PR 63.  I'm guessing that the data in `mig` is out of date enough that it's not happening there any more.  @mmarcotte we might need to run a glue job to `mig` to refresh the data to see if this bug can be reproduced there.

**Comment by rachelschneiderman** [comment]
Need to wait to pick this up until glue job on prod has been completed.

**Comment by rosiehsmith** [comment]
Reproduced this on migration after the glue job.
