### ISSUE TITLE
BUG: success message styling is off - Print receipt and Clear links display below message after filing a document

### ISSUE THREAD

**Issue by mrinsin** [ustaxcourt/ef-cms#7731]
**Describe the Bug**
success message styling is off - Print receipt and Clear links display below message after filing a document

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration

**Who were you logged in as?**
privatepractitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Go to an open case
2. File a document
3. Submit your filing

**Expected Behavior**
Print receipt, clear and success alert should be aligned appropriately

**Actual Behavior**
Alignment is off

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5e93c9fa78057303bcc6ac/51e82716-dc6f-4b7d-a789-279ac1542f24)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iOS (iPhone 11 pro max, iPhone SE) and Android (Google Pixel)

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
@klohman Need design guidance on what this should look like

**Comment by klohman** [comment]
updated design 

![image](https://user-images.githubusercontent.com/18366192/113928226-7c4d0400-97bc-11eb-9821-a89375a27a39.png)
