### ISSUE TITLE
BUG: Add Court Issued Docket Entry - "Judge" title not added to docket entry

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7737]
**Describe the Bug**
"Judge" title is not displayed in the docket entry for court-issued documents when Judge's name is selected. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod

**Who were you logged in as?**
docket 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual 

**To Reproduce**
1. Go to case 
2. Add Court-Issued Docket Entry 

applies to these event codes: 
OAJ
OD
ODD
OJR
OSUB
DEC
OAD
ODJ
SDEC
MOP
SOP
FTRL
 HEAR
 PRTL
TRL
TCOP

**Expected Behavior**
"Judge" title should be displayed in the docket entry when judge's name is selected. For example, Ashford is selected for OAJ , docket entry should display "Order that case is assigned to Judge Ashford"

**Actual Behavior**
"Judge" title is not displaying in the docket entry when judge's name is selected. For example, Ashford is selected for OAJ , docket entry should display "Order that case is assigned to Ashford"

**Screenshots**
![Screen Shot 2020-12-17 at 1.10.17 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e362ac77-082c-48c8-a8cf-c61adaed3abe)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [x] Fix has been deployed to dev environment.
 - [x] Fix has been deployed to the stage environment.
 - [x] Bug has been tested in staging (UX or Engineering).

**Comment by matthopson** [comment]
#### Reason for bug:
When we refactored how judge names were being stored, we dropped the "Judge" part of the name, and added a `judgeTitle` field. We were not putting these together when generating document titles.
