### ISSUE TITLE
Partial Matches: Case search usability

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7742]
As the Court, in order to make sure our users are having a good user experience, we need to make some usability tweaks to the search features.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

## Pre-Conditions
* If user elects to perform a partial match search, display exact matches then partial matches 
  * Keyword exact match (exact words in exact order)
  * Keyword exact match (exact words in any order)
  * Keyword partial match (any words in any order)
* We define partial match as any words in any order
    - For example, if Bob Jones is entered 
   - Matches Bob 
   -  Matches Jones 

* Consider whether to reject searches that have special characters. Perhaps we can use Joi to validate what is a valid search query.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
## Design 

* Add checkbox for "Include partial matches" 

## Exact Match query only 
**include partial matches checkbox is unchecked**
* execute exact match query only 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8904813e-4d43-4887-b42e-c279c687898a)

## Exact and partial match queries 
**include partial matches checkbox is checked**
* execute exact match query and partial match query 
* results are sorted exact match then partial match  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d18b8a0f-865c-4cc2-81a2-64ff0f92704a)

## Exact or exact and partial match queries - No Result 
**include partial matches checkbox is checked or unchecked**
* Display No Matches Found 
* Display tips alert 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1ccd375a-1483-4afa-8c4c-b0ce263c3547)

## Exact or exact and partial match queries - max results 
**include partial matches checkbox is checked or unchecked**
* Display 100 matches 
* Display max results  alert 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4936766a-3899-4960-b947-1748fa2d914b)
