### ISSUE TITLE
Partial Matches: Search usability (HOLD)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7743]
As a user, so that I may expand my order search, I want to see partial matches in the search results.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

## Acceptance Criteria 
* User  should see an indication that my search request is “processing” after starting a search
* If user elects to perform a partial match search, display exact matches then partial matches 
* If search keyword and petitioner name, matches need to be sorted as:
  * Keyword exact match (exact words in exact order) + petitioner name [exact words in exact order]
  * Keyword exact match (exact words in any order) + petitioner name [exact words in exact order]
  * Keyword exact match (exact words in exact order) + petitioner name [exact words in any order]
  * Keyword exact match (exact words in any order) + petitioner name [exact words in any order]
  * Keyword exact match (any of the words in any order) + petitioner name [exact words in exact order]
  * Keyword exact match (any of the words in any order) + petitioner name [exact words in any order]
* If search keyword and petitioner name, show no results
  * Keyword exact match (exact words in exact order) + petitioner name [no exact match]
  * Keyword exact match (exact words in any order) + petitioner name [no exact match]
* If search keyword and docket number / judge / start-end date combo, matches sorted as: 
  * Keyword exact match (exact words in exact order) + docket number/judge/start-end date [exact match]
  * Keyword exact match (exact words in any order) + docket number/judge/start-end date [exact match]
  * Keyword exact match (any of the words in any order) + docket number/judge/start-end date [exact match]

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by mariahkannenberg** [comment]
Not sure if we need this one. First, implement exact match, then find out if users still need.

**Comment by cholly75** [comment]
Closing issue - we have search live and will reopen if we determine a need based on feedback.
