### ISSUE TITLE
BUG: Switching between Year/Period when adding Statistics to Deficiency Case clears form

### ISSUE THREAD

**Issue by sutt0n** [ustaxcourt/ef-cms#7749]
**Describe the Bug**
When logged in as a Docket Clerk, I attempted to add a statistic to a deficiency case; when adding the year/period statistic, I selected `Period` after entering `Deficiency` and `IRS Notice` penalties/amounts, and it cleared the amounts on the form. After clearing the form, and attempting to save, it fails validation.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
USTC Migration

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Login as a Docket Clerk
2. Navigate to a Deficiency case type.
3. Go to Case Information
4. Go to Statistics
5. Add New Year/Period
6. Enter Year
7. Enter Statistics
8. Select Period
9. Enter Period
10. Save

**Expected Behavior**
The penalties/deficiencies should not have been cleared after switching from Year to Period, and I should have been able to enter a Period and save with no validation errors.

**Actual Behavior**
Form was cleared, thus triggering validation errors after switching from Year to Period upon save.

**Screenshots**
![bug-statistics](https://user-images.githubusercontent.com/1116426/109992472-ead80700-7cd0-11eb-8342-93bb3c3aaa46.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 85.0.2 (64-bit)

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by JessicaMarine** [comment]
This is not a bug.
