### ISSUE TITLE
BUG: Superuser Should Receive Notice of Change of Address service email

### ISSUE THREAD

**Issue by kkoskelin** [ustaxcourt/ef-cms#7754]
**Describe the Bug**
The IRS Superuser should receive emails for Notice of Change of Address, but did not.

**Business Impact/Reason for Severity**
The court is obligated to provide service emails to the IRS for these events.

**In which environment did you see this bug?**
court migration

**Who were you logged in as?**
private practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
quarterly testing.

**To Reproduce**
0. Set yourself up to receive emails on behalf of the IRS Superuser.
1. Log in as a private practitioner who has multiple open cases (2 is enough).
2. Go to "My Account" selection in User Menu.
3. Click "Edit" in the "My Contact Info" card.
4. Make a change to the street address, and submit, waiting for the progress bar to indicate that all associated cases have been updated.
5. Visit each of the cases and view petitioner respondent information to confirm the address was updated in each.
6. On each case, verify that a Notice of Change of Address was added to the docket record.
6. Check email and verify that as the IRS Superuser, you received an email 

See also: "DAWSON Test Matrix - Features" shared quarterly testing document under the "Service Emails" sheet, test task ustaxcourt/ef-cms#6497.

**Expected Behavior**
Expected that the IRS Superuser would receive an email when the address was changed.

**Actual Behavior**
Other parties got emails, but IRS Superuser did not.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by TomElliottFlexion** [comment]
Superuser _is_ receiving emails for `NCA` type documents. Leaving bug open to clarify documents being added to docket record _before_ the petition is served.

**Comment by JessicaMarine** [comment]
Not a bug -- Superuser is receiving service emails for `nca` document **unless** those documents are added to the docket record before the petition is served.
