### ISSUE TITLE
BUG: No edit link appears on Correspondence document when viewed from message inbox preview

### ISSUE THREAD

**Issue by TomElliottFlexion** [ustaxcourt/ef-cms#7755]
**Describe the Bug**
When a Correspondence document is accessed from message inbox, the `Edit` button does not appear. `Edit` link appears if the correspondence is viewed from the Document Detail "Correspondence" tab.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
USTC Mig
**Who were you logged in as?**
Docket clerk
**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing
**To Reproduce**
1.  Go to Message Inbox 
2. Click on a correspondence document
3. Notice that `Edit` button is not present on document preview

**Expected Behavior**
Expected `Edit` button to be present

**Actual Behavior**
`Edit` but was not present. It was present when the correspondence was viewed from the Document Detail "Correspondence" tab.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
@klohman Can you confirm if this is a bug?  I don't think we have the edit button from the message, do we?

**Comment by klohman** [comment]
@JessicaMarine The edit link should appear on the message detail for Correspondence files for user roles that have permission to edit those files. I'm not sure but we may have mistakenly removed the link when fixing this previous bug (#7022) that had to do with edit correspondence permissions.
