### ISSUE TITLE
BUG: 'Served Date' stamp is not visible on PDF preview of served document

### ISSUE THREAD

**Issue by TomElliottFlexion** [ustaxcourt/ef-cms#7759]
**Describe the Bug**
'Served Date' stamp is not visible on PDF preview of a served document.

**Business Impact/Reason for Severity**
Inconsistent UI behavior
**In which environment did you see this bug?**
USTC mig
**Who were you logged in as?**
Docket clerk
**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing
**To Reproduce**
1. Go to 'Message Inbox'
2. Click on message with a **draft** **order ** document that has been **saved** but **not served**
3. Click `Serve` button to serve document
4. Scroll down and notice the lack of a 'Served' stamp on the PDF preview. Do **not** click on the document under 'Attachments' on the left.
5. Reload page, click on the document under 'Attachments' or click 'View Full PDF' to see the stamp appear.

**Expected Behavior**
Expected to see the 'Served' stamp on the PDF preview.

**Actual Behavior**
Needed to reload or click on document to see the 'Served' stamp on the PDF preview.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
Note for engineers - probably due to previous version of document being cached in state.
