### ISSUE TITLE
BUG: PDF Signature Stamp Slightly Off

### ISSUE THREAD

**Issue by matthopson** [ustaxcourt/ef-cms#7764]
**Describe the Bug**
The placement of the signature stamp when saved is slightly off from it's placed in the UI.

**Business Impact/Reason for Severity**
Not impacting functionality, but for accuracy, requires anticipating this offset when placing a signature.

**In which environment did you see this bug?**
dev, mig

**Who were you logged in as?**
adc

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Working on a bug (7827).

**To Reproduce**
1. File a document that requires a signature.
2. Log in as adc and sign the document, paying special attention to where it is placed (it helps to use elements in the PDF to align it).
3. After saving the signature placement, note the position of the signature is slightly off (down and to the right at a roughly square amount).

**Expected Behavior**
Signature should be saved exactly where it was placed in the UI.

**Actual Behavior**
Signature is off slightly.

**Screenshots**
Placing a signature aligned with the first line of text, edge of the opening paren aligned under the F.
<img width="632" alt="Screen Shot 2021-03-12 at 7 29 43 AM" src="https://user-images.githubusercontent.com/1891789/111171794-ddd9d400-856a-11eb-82a2-2af5514fde4e.png">

Note the saved signature is slightly down and to the right of where it was placed.
<img width="944" alt="Screen Shot 2021-03-12 at 7 30 03 AM" src="https://user-images.githubusercontent.com/1891789/111171817-e3cfb500-856a-11eb-8100-832284425a86.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
Does this need to be pixel-perfect? Is there an acceptable level of accuracy?

Note for engineers - fonts are different in the two screenshots. Width of the signatures is also different.
