### ISSUE TITLE
BUG: Upgrading to USWDS 2.11.x produces undesirable artifacts

### ISSUE THREAD

**Issue by kkoskelin** [ustaxcourt/ef-cms#7773]
**Describe the Bug**
As a developer, I ran the `reset-dependencies.sh` script (which removes all modules, removes `package-lock.json` and reinstalls everything).  The specified version of `"uswds": "^2.10.3"` resulted in installation of minor version upgrade to `2.11.1` which introduces new design for USWDS icons.

Related PR to prevent minor-version upgrade: https://github.com/flexion/ef-cms/pull/8030

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Local development environment

**Who were you logged in as?**
petitionsclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing local workflow

**To Reproduce**
1. Edit your `package.json` to use `"uswds": "^2.10.3"`
2. Run the `./reset-dependencies.sh` script and then start your local development environment
3. Go to a case detail page
4. Create and sign an order.
5. See the misaligned checkmark icon and repeated background image on the success dialog.

**Expected Behavior**
Design should be consistent with what is found at `/style-guide`

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**
![Screen Shot 2021-03-18 at 10.23.16 AM.png](https://images.zenhubusercontent.com/5bbf750502b9b3375461a416/af83c1ce-14f2-44ae-8623-629ac44f088d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Upgrades to the USWDS minor version 2.11.x introduce changes into how SVG icons are being displayed and handled.  It is likely that the developer who handles this will need to revisit the USWDS design guidelines, review the `/style-guide` page to ensure things are displaying correctly, and then make some select changes to alert dialogs and the associated CSS.

Desired design:
![Screen Shot 2021-03-18 at 11.49.08 AM.png](https://images.zenhubusercontent.com/5bbf750502b9b3375461a416/2e2ac805-247c-4bfd-ae9f-10a88b854256)

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
Other issues: 

Page level errors 
<img width="899" alt="Screen Shot 2021-03-18 at 12 41 45 PM" src="https://user-images.githubusercontent.com/18366192/111666168-d8d68800-87e9-11eb-8b77-42a582de240f.png">

Warning message
<img width="1365" alt="Screen Shot 2021-03-18 at 12 59 28 PM" src="https://user-images.githubusercontent.com/18366192/111666221-e25ff000-87e9-11eb-83f7-4c399c79c46a.png">

<img width="926" alt="Screen Shot 2021-03-18 at 1 01 55 PM" src="https://user-images.githubusercontent.com/18366192/111666506-27842200-87ea-11eb-935d-2f79c53ba286.png">

<img width="853" alt="Screen Shot 2021-03-18 at 1 03 41 PM" src="https://user-images.githubusercontent.com/18366192/111666738-61edbf00-87ea-11eb-98fd-a1b1b21cca9d.png">

**Comment by matthopson** [comment]
PR: https://github.com/ustaxcourt/ef-cms/pull/994

**Comment by matthopson** [comment]
Deploying to exp1 for UX review by @klohman

**Comment by mmarcotte** [comment]
Currently deployed in the `test` env
