### ISSUE TITLE
Court: Ensure no duplicate service

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7781]
As the Court, in order to provide our parties with assurances in our service process, we should not have duplicate service.

## Pre-Conditions
* Service is initiated 

## Acceptance Criteria
* As a Court user initiating service, my first attempt to serve a document should prevent subsequent attempts.
* Party/counsel does not receive multiple emails serving the same document

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
We likely had a bug fix for this

Somehow, a Petitions Clerk was able to serve the IRS a new petition twice. Perhaps it was a double click, perhaps they had the case open in two tabs. 

They initiated two identical API requests within the course of 2.5 seconds to `/cases/14831-20/serve-to-irs`
* Mar 2, 2021 @ 08:56:41.241
* Mar 2, 2021 @ 08:56:43.719

These identical requests went about their business and did what they were supposed to do.

The first thing these handlers need to do is to prevent an identical request coming in. It would lock the case/document while it performs its task. And then hopefully leave it in a state where it cannot be served again. 

Both requests were running concurrently a they ended:
* Mar 2, 2021 @ 08:56:45.819
* Mar 2, 2021 @ 08:56:50.334

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
Design may be needed - pair with designer when this is picked up.

**Comment by matthopson** [comment]
Cody determined, you could use the keyboard to continue to submit the submit button - even when the spinner was being displayed.

This PR disables that as well as creates some state when a document is in the process of being served and prevents it from being served by two people at once (or from two separate tabs at the same time).

https://github.com/flexion/ef-cms/pull/8601

**Comment by klohman** [comment]
**UX review** 


**From Add Docket Entry screen** 
- when clicking enter multiple times on service action, app is throwing an error, then taking me to the docket record. No service emails are received 
https://drive.google.com/file/d/1f8rZv76Qq25-PC1UefN_Tu0jHljNRwwk/view?usp=drivesdk


- when serving as normal (one click), no service email is received
