### ISSUE TITLE
BUG: Petitions Clerks receiving error trying to update a Case

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7784]
**Describe the Bug**

Observed in the error logs

> TypeError: Cannot read property 'toRawObject' of undefined
>     at Object.exports.saveCaseDetailInternalEditInteractor

Petitions Clerk Ashlie Grice was attempting to call `/cases/2047-21` with a PUT request and generated that error

POST DATA

```
{
  "entityName": "Case",
  "associatedJudge": "Chief Judge",
  "qcCompleteForTrial": {},
  "status": "New",
  "noticeOfAttachments": false,
  "orderDesignatingPlaceOfTrial": true,
  "orderForAmendedPetition": false,
  "orderForAmendedPetitionAndFilingFee": true,
  "orderForFilingFee": false,
  "orderForOds": false,
  "orderForRatification": false,
  "orderToShowCause": false,
  "archivedDocketEntries": [],
  "statistics": [
    {
      "entityName": "Statistic",
      "irsDeficiencyAmount": "10417.00",
      "irsTotalPenalties": "2083.00",
      "year": "2017",
      "yearOrPeriod": "Year",
      "statisticId": "e80bc0c7-11b1-45c3-aa10-15f7f0aef61e",
      "lastDateOfPeriod": null
    }
  ],
  "correspondence": [],
  "archivedCorrespondences": [],
  "docketEntries": [
    {
      "entityName": "DocketEntry",
      "isDraft": false,
      "pending": false,
      "userId": "23f53824-1c1b-4cad-876e-0b7ce045e472",
      "workItem": {
        "entityName": "WorkItem",
        "assigneeId": "23f53824-1c1b-4cad-876e-0b7ce045e472",
        "assigneeName": "Ashlee Grice",
        "associatedJudge": "Chief Judge",
        "caseIsInProgress": true,
        "caseStatus": "New",
        "caseTitle": "Ralph Thomson & Uta Thomson",
        "createdAt": "2021-03-19T19:10:36.346Z",
        "docketEntry": {
          "createdAt": "2021-01-22T05:00:00.000Z",
          "docketEntryId": "8883db26-04cc-4000-b0bb-9fd96bf15d9f",
          "documentTitle": "Petition",
          "documentType": "Petition",
          "eventCode": "P",
          "filedBy": "Petrs. Ralph Thomson & Uta Thomson",
          "isFileAttached": true,
          "isPaper": true,
          "receivedAt": "2021-01-22T05:00:00.000Z",
          "userId": "23f53824-1c1b-4cad-876e-0b7ce045e472"
        },
        "docketNumber": "2047-21",
        "docketNumberWithSuffix": "2047-21",
        "highPriority": false,
        "isInitializeCase": true,
        "section": "petitions",
        "sentBy": "Ashlee Grice",
        "sentBySection": "petitions",
        "sentByUserId": "23f53824-1c1b-4cad-876e-0b7ce045e472",
        "updatedAt": "2021-03-19T19:10:36.346Z",
        "workItemId": "268e8dde-5a5f-4735-9900-347b1ebd125e"
      },
      "addToCoversheet": false,
      "createdAt": "2021-01-22T05:00:00.000Z",
      "docketEntryId": "8883db26-04cc-4000-b0bb-9fd96bf15d9f",
      "documentTitle": "Petition",
      "documentType": "Petition",
      "eventCode": "P",
      "filedBy": "Petrs. Ralph Thomson & Uta Thomson",
      "filingDate": "2021-01-22T05:00:00.000Z",
      "index": 1,
      "isFileAttached": true,
      "isMinuteEntry": false,
      "isOnDocketRecord": true,
      "isPaper": true,
      "isStricken": false,
      "mailingDate": "Postmark 01/15/2021",
      "partyPrimary": true,
      "partySecondary": true,
      "processingStatus": "pending",
      "receivedAt": "2021-01-22T05:00:00.000Z"
    }
  ],
  "isSealed": false,
  "hearings": [],
  "otherFilers": [],
  "otherPetitioners": [],
  "contactPrimary": {
    "countryType": "domestic",
    "name": "John R. Thomson",
    "address1": "P.O. Box 453",
    "city": "Dingmans Ferry",
    "state": "PA",
    "postalCode": "18328",
    "phone": "N/A"
  },
  "contactSecondary": {
    "countryType": "domestic",
    "name": "Uta Thomson",
    "address1": "P.O. Box 453",
    "city": "Dingmans Ferry",
    "state": "PA",
    "postalCode": "18328",
    "phone": "N/A"
  },
  "privatePractitioners": [],
  "irsPractitioners": [],
  "caseCaption": "John R. Thomson, Petitioner",
  "caseType": "Deficiency",
  "createdAt": "2021-03-19T19:10:36.345Z",
  "docketNumber": "2047-21",
  "docketNumberSuffix": null,
  "hasVerifiedIrsNotice": true,
  "irsNoticeDate": "2020-11-30T05:00:00.000Z",
  "isPaper": true,
  "mailingDate": "Postmark 01/15/2021",
  "partyType": "Petitioner",
  "petitionPaymentDate": null,
  "petitionPaymentStatus": "Not Paid",
  "petitionPaymentWaivedDate": null,
  "procedureType": "Regular",
  "receivedAt": "2021-01-22T05:00:00.000Z",
  "sortableDocketNumber": 21002047,
  "useSameAsPrimary": true,
  "initialDocketNumberSuffix": "_",
  "initialCaption": "Ralph Thomson & Uta Thomson, Petitioners",
  "hasPendingItems": false,
  "noticeOfTrialDate": "2021-03-19T19:10:36.345Z",
  "docketNumberWithSuffix": "2047-21"
}
```

**Business Impact/Reason for Severity**

Court functionality for petitions clerks updating cases is impaired

**In which environment did you see this bug?**

Court Production

**Who were you logged in as?**

Ashlee Grice (petitionsclerk)
 
**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Monitoring Logs

**To Reproduce**

We will need to investigate

a) how to replicate that request via the UI
b) why that request fails,

**Expected Behavior**

The case should be updated properly

**Actual Behavior**

Error 400

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by JessicaMarine** [comment]
Petitions Clerk accidentally started case with 2 petitioners (petitioner and spouse).  Tried to change to just petitioner.  Issue will be resolved by refactoring and other user management stories.
