### ISSUE TITLE
BUG: Service on Other Petitioners/Intervenors/Participants

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7786]
See notes in "Actual Behavior" for discussion on 3/31 about scope of bug. 

**Describe the Bug**
It doesn't appear that other petitioners or intervenors/participants (basically anyone other than primary and secondary) are getting served.

**Business Impact/Reason for Severity**
The Court has a legal obligation to serve all parties to a case.

**In which environment did you see this bug?**
Migration

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Login as a Docket Clerk
1. Go to 11350-18
2. Note that there is an intervenor on the case
3. Create an order
4. On the "Create Docket Entry" screen, note that the intervenor is not listed under the Service information
5. Serve the Order
6. Note that no paper service is generated for the intervenor

**Expected Behavior**
All parties to the case get service

**Actual Behavior**
Other petitioners/intervenors/participants don't appear to have a service preference, so they are not getting served.

* Serve all users via paper for immediate fix (Backlog complete solution)
* Display service indicator in UI
* Change Other petitioners/intervenors/participants to paper service and make sure they're part of aggregate
* Retain users' initial service preference for when we work on the complete solution

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by JessicaMarine** [comment]
@mariahkannenberg Need immediately:
1. Display service indicator for otherFilers and otherPetitioners in UI
2. Change all otherFilers and otherPetitioners to paper service
[3. Retain any information about eService for future implementation]
4. Include otherFilers and otherPetitioners in the service aggregator

**Comment by matthopson** [comment]
PR: https://github.com/ustaxcourt/ef-cms/pull/988

**Comment by JessicaMarine** [comment]
PO Review Complete -- Paper service now shows up in UI for Intervenor in 11350-18 and paper service is generated when trying to serve an Order
