### ISSUE TITLE
BUG: External document received between 7pm-12am Eastern will receive extra cover page when QCed

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7787]
**Describe the Bug**

A docket clerk who completes QC of a document received between 7pm and 12am Eastern will errantly generate a second cover page because the system things the document was received "the following day" due to Zulu time on receivedAt. 

`getNeedsNewCoversheet` is receiving:

```
currentDocketEntry.receivedAt: 2021-03-23T02:25:17.469Z, 
updatedDocketEntry.receivedAt: 2021-03-22
```

**Business Impact/Reason for Severity**

Legal documents cannot have a duplicate cover sheet; this is also causing problems with signing Proposed Stipulated Decisions

**In which environment did you see this bug?**

Court Staging, Integration tests

**Who were you logged in as?**

docketClerk2@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Attempting a deploy between 7pm and 12am.

**To Reproduce**
1. Wait until 7pm Eastern
2. Login as a test petitioner, and file a Certificate of Service on an existing case
3. Login as a Docket Clerk and Complete QC the document
4. Observe that the document went from 2 pages to 3, and now has two cover sheets.

**Expected Behavior**

The system should know that the document was received on the current day according to Eastern time. It should not generate a second cover page on the document

**Actual Behavior**

The system generates a second cover page. 

NOTE: If they change the date during regular business hours, and a cover sheet already exists on the document, I suspect this will also cause a duplicate cover sheet to get created.

**Screenshots**

<img width="1834" alt="Screen Shot 2021-03-23 at 12 00 25 AM" src="https://user-images.githubusercontent.com/5023502/112090930-cc945700-8b6a-11eb-9c39-2e883521fe3c.png">

**Cause of Bug, If Known**

receivedAt thinks it's tomorrow because it is not adjusting for timezone.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by JessicaMarine** [comment]
PO Review complete
