### ISSUE TITLE
Include Service Indicator for Petitioner in v1 API

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#779]
The API that we use to distribute information about a case or document needs to indicate the service preference for all parties on the case. Right now it appears to be lacking in the v1 API. We need to bring this information in to help inform users of the API how parties need to be served.

- [x] Include service indicator
- [x] Change `case.noticeOfTrialDate` to `trialDate`
- [x] Include `trialLocation`

**Comment by JessicaMarine** [comment]
v1 improply includes `case.noticeOfTrialDate` It should be`trialDate` instead.  Also should include `trialLocation`

**Comment by mmarcotte** [comment]
Put together the revised API into the IRS test environment. So they have time to test it and make sure that it works with their system.

Possible worry about changing the path of the API itself ("v2")

**Comment by adunkman** [comment]
Ensure `serviceIndicator` is in both petitioner and practitioner.

**Comment by JessicaMarine** [comment]
@adunkman we should include `preferredTrialCity` and `trialLocation` in version 2.
