### ISSUE TITLE
Court: Improve PR process, which is impeding the flow of code to the court

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7791]
As the Court in order to deploy finished code on the Court's schedule, we need to not be impeded by the current PR process.

## Pre-Conditions
* There is finished code.

## Acceptance Criteria
- Find a way that makes PR review easier for Mike without reducing code quality
- Court needs ability to deploy a specific “chunk” of finished code, while other work is in progress
- The “chunk” needs to be flexible, meaning that the court needs the ability to change what’s in that chunk while work is in progress
- Define an experiment for improvement
- Inspect the experiment 

Notes:

- Review last 5 PRs from the Court to determine if there’s a pattern of things we’re not doing a good job at the prevent him from getting to the PR in the first place (tools?)
- We need to determine where the code deployed to in the Court’s environments
- Where QA is happening
- Is there a different path for bugs vs feature work?
- Court doesn't want to have 3 production like environments - too expensive.
 - The DOD is updated with checkboxes to reflect the new flow - including checkboxes for Mike
- 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by matthopson** [comment]
I just want to raise a note about how things are tested in this workflow. Ideally code for bug fixes would stay separate from story work - which means keeping an environment in sync with the court's, OR working from the court's env. Just something we need to consider, as I think the safest and cleanest way to approach this is to effectively base of the environment that is MOST up to date with court's production - whether that's the testing env or a clone on Flexion's side.

**Comment by sutt0n** [comment]
# Experiment for Improvement

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1116426/112529130-ef915780-8d72-11eb-9a4f-1f97083b0abc.png">


## Flow Description
- [Flexion] Feature (e.g. "Story") branches are created from `court/staging`, and merged into `court/migration`.
  - [Flexion] UX Reviews done on any Flexion environment, merged into `court/migration` after UX Review passes, and then into `court/staging` after PO approval.
  - `court/migration` will be an aggregate environment for stories prior to `court/staging`
- [Flexion] Hotfixes / bugs are created from `court/staging`, and merged into `court/test`. [Court] After PO approval, they're merged into `court/staging`.
  - [Flexion] UX Reviews only as needed on the `court/test` environment
- Features are QA'd in the `court/migration` environment (`migration`).
- Hotfixes / bugs are QA'd in the `court/test` environment (`test`).
- Note: Feature branches going into `court/staging` will be going individually, not as a group.

**Comment by matthopson** [comment]
## Story Workflow (Batched)
Step | Branch / Env. | Board / Column | Labels | Note | Who
-- | -- | -- | -- | -- | --
Assign issue to point person |   |   |   | Add point person to story in GitHub. <br/><br/>Update in GitHub if point person changes.  | Flexion Engineer
Create small PRs into `develop` branch | dev |   | +`Needs Blue / Green Migration` (as needed)<br />+`Needs ES Reindex` (as needed) | Use other Flexion envs to test if necessary (i.e. exp1). Flexion code review takes place in these PRs. Work (`develop` branch) can be merged into `mig` any time.  | Flexion Engineer
UX Review | dev / Any other Flexion env (exp1, exp2, exp3) / mig |   |   |   | Flexion Engineer + UX
Merge `develop` branch into Court’s Migration | Court’s Migration | QA | -`Engineering`<br />+`Needs PO Review `|  | Flexion Engineer
PO Reviews on Court’s Migration | Court’s Migration |  Done  | -`Needs PO Review` <br/>+`PO Review Provided` (if needed)  | Address issues on `develop` branch, re-merge into Court’s Migration <br/> <br/> When approved, PO will post in story.   | PO + Flexion Engineer
  |   |   |   | **Once all the stories in the batch are Done**   |
Flexion makes Batch PR from `develop` into Court’s Staging | Court's Staging |   |  |  | Flexion Engineer  
Court Tech Lead reviews PR | Court's Staging |   |   | Address issues / PR comments on PR branch.  | Tech Lead + Flexion Engineer
Court Tech Lead merges to staging | Court’s Staging |   |   |  | Tech Lead
Update Flexion's dev | `develop`  |  |  |  Back-merge Court's staging branch into Flexion's `develop`  | Flexion Engineer




## Bug Workflow
Step | Branch / Env. | Board / Column | Labels | Note | Who
-- | -- | -- | -- | -- | --
Assign issue to point person |   |   |   |  Add point person to bug in GitHub. <br/><br/> Update in GitHub if point person changes.  | Flexion Engineer
Create bug branch from Court’s Staging | Court’s Staging -> New Branch | In Progress | +`Engineering` |   | Flexion Engineer
Commit changes to bug branch. | Bug Branch / Any Flexion env (dev, exp1, exp2, exp3) |   | +`Needs Blue / Green Migration` (as needed)  | Use Flexion envs to test functionality/deploy if necessary.   | Flexion Engineer
  |   |   |   | Separates Flexion / Court Envs   |
Flexion makes PR from bug branch into Court’s Test environment | Court’s Test | QA | -`Engineering`<br />+`Code Review Needed` |   | Flexion Engineer  
Request review from Flexion engineers |   |   |   | PR can be merged with review from both Court’s Tech Lead and at least ONE Flexion engineer   | Flexion Engineer
Court’s Tech Lead merges to Court’s Test | Court’s Test |   | -`Code Review Needed`<br />+`Needs PO Review` | Do NOT delete branch   | Tech Lead
PO Reviews on Court’s Test | Court’s Test |   |  | If tech lead review needed, PO to add label `Needs Tech Lead Review` and contact tech lead. <br /><br />Issues found during review can be fixed on the bug branch with a new PR to test   | PO / Tech Lead
When PO/Tech Lead Review done |   |  | +`Needs STAGING Deploy` |   | PO / Tech Lead 
Court Tech Lead merges to staging | Court’s Staging |   |   |   | Tech Lead
Court Tech Lead moves to done |   | Done | -`Needs STAGING Deploy` |   | Tech Lead  
Flexion Engineer deletes feature branch  | Feature Branch |   |   | Safe to delete bug branch  | Flexion Engineer
Deploying work to migration environment |  Migration |  |  |  Run switch colors after blue-green migration passes | Flexion Engineer (Point Person)




## Feature Workflow
Step | Branch / Env. | Board / Column | Labels | Note | Who
-- | -- | -- | -- | -- | --
Assign issue to point person |   |   |   | Add point person to story in GitHub. <br/><br/>Update in GitHub if point person changes.  | Flexion Engineer
Create feature branch from Court's Staging | Court’s Staging -> Feature Branch | In Progress | +`Engineering` | You may also work off an existing feature branch if stories are intended to be coupled.   | Flexion Engineer
Create small PRs into feature branch | Feature Branch / Any Flexion env (dev, exp1, exp2, exp3) |   | +`Needs Blue / Green Migration` (as needed)<br />+`Needs ES Reindex` (as needed) | Flexion code review takes place in these PRs. Feature may be merged into dev / migration / any other Flexion env as needed.  | Flexion Engineer
UX Review on dev | dev / Any other Flexion env (exp1, exp2, exp3) / mig |   |   | Merge feature branch into other branches without deleting feature branch.  | Flexion Engineer + UX
  |   |   |   | Separates Flexion / Court Envs   |
Merge feature branch into Court’s Migration | Court’s Migration | QA | -`Engineering`<br />+`Needs PO Review `| Do NOT delete branch   | Flexion Engineer
PO Reviews on Court’s Migration | Court’s Migration |   | -`Needs PO Review` <br/>+`PO Review Provided`   | Address issues on feature branch, re-merge into Court’s Migration <br/> <br/> When approved, PO will post in story.   | PO + Flexion Engineer
Flexion makes PR from feature into Court’s Staging | Court's Staging |   | +`Code Review Needed` | Ensure this feature branch is up-to-date with staging. <br/> <br/> Flexion Engineer sends Court Tech Lead a slack message to notify that it's ready for code review.  | Flexion Engineer  
Court Tech Lead reviews PR | Court's Staging |   |   | Address issues on feature branch, comments in pull request.  | Tech Lead
Court Tech Lead merges to staging | Court’s Staging |   |   |  | Tech Lead
Court’s Tech Lead moves to done |   | Done | -`Code Review Needed` |   | Tech Lead
Flexion Engineer deletes feature branch  | Feature Branch |   |   |  | Flexion Engineer
Update Flexion's dev | `develop`  |  |  |  Back-merge Court's staging branch into Flexion's `develop`  | Flexion Engineer

**Comment by matthopson** [comment]
### Feature Branching
Feature branches should remain up to date with the Court’s staging environment. Ideally a feature will represent a single story, but there are some cases where a feature branch may be an aggregate of multiple related stories. In this flow, the feature branch should be continually updated with the Court’s staging branch while other stories are based off the feature branch.

### Merge Conflicts
Merge conflicts will happen, but that’s ok! We’ve created two distinct paths by which code is pushed to production (or more specifically the Court’s staging environment). There will absolutely be times where code is out of sync between them, and one of the easier ways of resolving conflicts between these two is to give one priority. Often times the bug flow is going to reach the Court’s staging environment faster. The unit of work is likely smaller than that of a story, and review takes place on the Court’s testing environment. Stories, on the other hand, tend to live on a longer time scale and have the opportunity to be merged in a safer aggregate environment (the Court’s migration environment) that is continually updated with things going into staging. For this reason, it should be more reasonable to resolve conflicts that arise from the bug workflow’s fast path to staging on the migration environment - usually as a result of keeping a given feature branch continually up to date with the Court’s staging branch.

### Migration / ES Reindex Labels
In this new flow, if you're working on either a story or bug and realize a migration or re-index will be needed, that is the time to apply the appropriate label on the issue so that it is abundantly clear when glancing at the issue on the board. This is not only a good trigger for the Court's Tech Lead to note this for deployment, but also a good way for engineers working on other stories or bugs to be aware of this. It would be a good idea to call these out during our morning discussion. If you are deploying work to the migration environment, you are responsible for switching the colors on the migration environment after the blue-green deployment passes.

**Comment by mariahkannenberg** [comment]
# User Stories
- A defined unit of new work focused on the needs of the user.
- Not defined in technical or design terms.
- Can be achieved with paper and pencil if necessary. (Technology-agnostic terminology)
- Development is complete when all of the user's needs (acceptance criteria) have been met at production quality AND the steps taken to fulfill the user's needs have been demonstrated.
- Priority defined by the product owner
- Work progresses through the user story flow

#### What is a user? 
Any person who uses the system to achieve their business or personal needs.

#### What does production quality mean?
All of the items in the DOD have been completed.

# Bugs
- A defined unit of work focused on the needs of the user.
- Not defined in technical or design terms.
- Acceptance criteria from a previously completed user story is unintentionally no longer being met.
- Priority defined by the product owner
- Work progresses through the user bug flow

# Refactoring
- A defined unit of work that has no impact to the user.
- Doesn't give obvious business value to the user.
- The purpose is to make the system easier for engineers to maintain and expand.
- When completed, refactoring reduces the friction engineers experience during development.
- Priority defined by the engineering team
- Uses story workflow

# Edge Cases
 - A use case that was intentionally or unintentionally left out of a user story
 - Often discovered by the end user
 - Varied in terms of importance and urgency
- Priority defined by the product owner
- Workflow determined by steps to resolve from Bug / Story definitions

**Comment by JessicaMarine** [comment]
@matthopson Thoughts?

## STORY CHECKLIST ##
- [ ] Flexion Engineer: Assign issue to point person, Move story to *In Progress* column & Add `Engineering` tag 	 	 	
- [ ] Flexion Engineer: Create feature branch from Court's **Staging**
- [ ] Flexion Engineer: Create small PRs into feature branch [Note: PRs should be reviewed by another Flexion engineer]	
- [ ] Flexion Engineer & UX: UX Review (locally or on Flexion dev, exp1, exp2, exp3)	
- [ ] Flexion Engineer: Merge feature branch into Court’s **Migration**; Move story to *QA* column; Remove `Engineering` tag & Add `Needs PO Review` tag	
- [ ] Court PO: Review on Court's **Migration** [Note: PO will add `PO Review Provided` if additional engineering work needed]
- [ ] Flexion Engineer: Once PO has approved story, make PR to Court's **Staging**; Remove `Needs PO Review` tag & Add `Court Code Review Needed` tag
- [ ] Court Tech Lead: Code Review
- [ ] Court Tech Lead: Merge to **Staging**; Remove `Court Code Review Needed` tag & Move story to *Done*
- [ ] Flexion Engineer: Delete Feature Branch

## BUG CHECKLIST ##
- [ ] Flexion Engineer: Assign issue to point person; Move story to *In Progress* column & Add `Engineering` tag	 	 	 	
- [ ] Flexion Engineer: Create bug branch from Court's **Staging**
- [ ] Flexion Engineer: Create small PRs into bug branch (if needed)	
- [ ] Flexion Engineer: Make PR from bug branch to Court's **Test**; Move to *QA* column & Add `Court Code Review Needed` tag	
- [ ] Second Flexion Engineer: Review PR
- [ ] Court Tech lead: Review PR
- [ ] Court Tech Lead: Merge PR to Court's **Test**; Remove `Court Code Review Needed` tag & Add `PO Review Needed` tag
- [ ] Court PO: Review on Court's **Test**; Once complete, add `Needs STAGING Deploy` tag
- [ ] Court Tech Lead: Merge to **Staging**; Remove `Needs STAGING Deploy` tag & Move to *Done*
- [ ] Flexion Engineer: Delete Bug Branch

**Comment by mariahkannenberg** [comment]
Revisit DOD on Wed during grooming. Do we want the checklist that Jessica suggested above?

**Comment by mariahkannenberg** [comment]
All that's left on this one it to do the inspection. However, want to wait until some stories have been completed and gone through the flow before we inspect.
