### ISSUE TITLE
BUG: Message Dropdown width not constant

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7793]
**Describe the Bug**
When one of the documents in the "Add Document(s)" list on the messaging modal is too long, the dropdown box expands to the right indefinitely.  If you are on one screen, that means the dropdown is cutoff and you don't have access to the scroll: 

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/4eec5c1a-a9a6-4902-9cfc-f18352670b81)

If you have two screens, it will extend it to the second screen, but cut off part of the left side:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/57d7557c-2aa9-49f2-837d-9bd4aaf009f8)

**Business Impact/Reason for Severity**
User is unable to select the correct document to attach to a message

**In which environment did you see this bug?**
Court's production; able to reproduce mig

**Who were you logged in as?**
Judge Buch

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Working; sending a message

**To Reproduce**
1. Go to 4507-20
2. Try to send a message
3. Select the "Add Document(s)" dropdown
4. Note that the long entries push the size of the box to the right and either off the page (if 1 monitor) or onto the second monitor (if one exists).

**Expected Behavior**
* The dropdown width would be fixed and the text of long entries would wrap
* The user would have the scroll bar on the right side of the dropdown
* The dropdown would not extend off the page

**Actual Behavior**
* The dropdown is extending off the page/on to a second monitor
* The scroll on the right side of the dropdown is inaccessible (may be the same as https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7585)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
could be related to the component on Edge 


on Edge 

![Screen Shot 2021-03-25 at 3.56.29 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2e323691-ce6c-4259-af1d-3c123fa38305)



vs. on Chrome 
![Screen Shot 2021-03-25 at 3.56.40 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/12908e68-4f91-4ccd-94de-a196305e4ea7)

**Comment by JessicaMarine** [comment]
Discussed with Judge Buch and team.  Issue w/ how Edge treats the drop-down box.  Agreed to truncate document description to 100 characters.
