### ISSUE TITLE
SPIKE: Sonarcloud

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7795]
As a team, determine what value Sonarcloud is providing, and whether or not we should keep, abandon, or consider alternatives. 

## Pre-Conditions

- [x] Everyone understands what Sonarcloud does
- [x] Everyone understands what Sonarcloud has done for us in the past

## Acceptance Criteria
- [x] Some investigation has been made into alternatives
- [x] Decide whether to reintroduce, abandon, or replace Sonarcloud
   - [x] If reintroducing, create a story to add Sonarcloud back into the CircleCI flow.
   - [x] If abandoning, document decision
   - [x] If replacing, create a story to add it into the build steps

## Notes
* Do we feel like we need code quality checks?
* How often has Sonar cloud produced an issues of value that aren't "code smells"
* How often has Sonar cloud produced a significant issue

**Comment by rosiehsmith** [comment]
After investigation, we feel confident the functionality Sonarcloud is covered by a combo of ESLint and our code coverage tools, therefore we're going to abandon usage of Sonarcloud. We looked into the security alerts & code duplication warnings that it was providing as well and found it not to provide value. 

We're going to experiment with IDE-integrated code quality analysis tools (like DeepScan) and will revisit how this goes in a week at standup.
