### ISSUE TITLE
SPIKE: Figure out why search doesn't work

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7796]
As a development team, so that search performs well with many users, we need to investigate solutions that allow users to receive results quickly and not get logged out or timed out, and reduce impact to other critical systems that depend on elastic search.
 
## Pre-Conditions
* Engineers have reviewed the notes below and the previous documentation in https://github.com/ustaxcourt/ef-cms/issues/872
* The ES cluster for mig is configured to match production (@mmarcotte)
* All Order and Opinion PDFs (including legacy PDFs) in target environment (mig?) are scraped and indexed in ES and available for search (#8325)

## Acceptance Criteria
Figure out why advanced search doesn't work:
- [x] Develop a list of systems affected by a laden ES cluster
- [x] Document - with this given data set and X concurrent searches, this is the line in code where bottleneck exists. (Documented in USTC 872) (Note: This could be different depending on what type of search we’re performing.) 8.5 requests/second (approximating 40 concurrent users)
- [x] Utilize load testing to establish baseline metrics for searches per second for cases (already have)
- [x] Utilize load testing to establish baseline metrics for searching through a production-like set of documents. 

 ____________

## Notes 
- During pre-launch load testing, Court found that concurrent searches would spike elastic search CPU. If the load spikes to 100, the rest of the app starts to flail, because so many things are using ES for indexing. 
- One core problem is that the lookup on `caseCaption` and `isSealed` on the Case when searching upon the Docket Entry index makes ES work too hard (at least for Advanced Document Search).
- Another core problem, (if we abandoned the Parent/Child Join) is when a Case receives an update, we would have to update ALL of the docket entries with the `caseCaption` or `isSealed` 
  - this possibly could create a backlog of items that need to be processed by the Streams Interactor
  - this also makes it difficult during blue/green migrations. The Docket entries would have to exist in ES in order to receive the update... unless when you index a docket entry, it also looks up the record for the Case
-  Perhaps the elephant in the room is the documentContents and where / when / how you index that information into ES. This is information that doesn't change often. Do we need to index this upon every blue/green deploy? Can it be decoupled from the docket entry index? It takes a long time and is expensive. 
* Makes elastic search inoperable. Anything that relies upon ES, would take longer or be slowed down or now respond with valid information. This is why we pulled search out of MVP. 
* Should we be allowing public functionality to impact internal user functionality?
* Prevent public from impacting internal users
* Internal users should also not be negatively impacted when performing concurrent searches

* As a public user, What is "quick?"
* What is meant by "degrade system performance"
* What does cost effective mean? Changing this batch to old way of indexing may make it slower. The only way to speed it up, would be to throw more money at it.
* Will removing the parent/child relationship increase indexing times, and thereby increase deploy times? What is a reasonable cost change (%?) to offset the deploy time.

**Comment by mariahkannenberg** [comment]
https://flexion.slack.com/archives/CD58Y6799/p1620672221465800

**Comment by matthopson** [comment]
Services / Features By ES Index

`efcms-case-deadline`
- Case Deadlines

`efcms-case`
- Case Advanced Search
- Case Public Search
- Blocked Cases Report
- Case Inventory Report
- Get Case By User ID
- Get First Single Case
- Get Ready For Trial Cases
- Get Case Deadlines (report)

`efcms-docket-entry`
- Advanced Document Search (USES JOIN ON CASE)
- Pending Items (USES JOIN ON CASE)
- Reconciliation Report

`efcms-message`
- showing when users have new messages (notifications)
- Messages (user / section, inbox / completed)

`efcms-user-case`
- Indexed Cases for User (open / closed cases, verify user pending email)

`efcms-user`
- Practitioner By Name

`efcms-work-item`
- Document QC (user / section)

**Comment by kkoskelin** [comment]
Add to `errors.js` and then use this new ServiceUnavailableError thrown by searchClient.js in the "catch".
```
/**
 * ServiceUnavailableError error
 *
 * @type {module.ServiceUnavailableError}
 */
module.exports.ServiceUnavailableError = class ServiceUnavailableError extends (
  Error
) {
  /**
   * constructor
   *
   * @param {string} message the error message
   */
  constructor(message = 'Service unavailable') {
    super(message);

    this.statusCode = 503;
  }
};
```

**Comment by sutt0n** [comment]
We've curated a number of hit points to optimize ElasticSearch performance for both the `efcms-docket-entry` index and the advanced document search (see ustaxcourt/ef-cms#7892) itself (partially noted from the Tasks list above):

- Use Slow log on mig to identify specific problem queries: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html#index-modules-slowlog
- Set replicas to `2`
- Increase shard count to `4`
- Investigate index mapping fields index types
- Remove parent-child setup (de-normalize)
- Error handling for `503`s (https://github.com/flexion/ef-cms/issues/8072#issuecomment-849895441)
- Potentially use Auto-Tune https://aws.amazon.com/blogs/big-data/introducing-auto-tune-in-amazon-es/
- Utilize `filter` ElasticSearch context (#8326 related)
  - Migration for `isOrder` and `isOpinion` flags on DocketEntry entity and remove `eventCode.S` terms filter
  - Increase filter index cache percentage (default is 10%)

cc: @codyseibert @kkoskelin @matthopson @mmarcotte

**Comment by codyseibert** [comment]
[Order_search_6_users_1_replica_1_shard.pdf](https://github.com/flexion/ef-cms/files/6593015/Order_search_6_users_1_replica_1_shard.pdf)
[Order_search_8_concurrent_1_replica_1_shard.pdf](https://github.com/flexion/ef-cms/files/6593016/Order_search_8_concurrent_1_replica_1_shard.pdf)
[Order_search_10_concurrent_1_replica_1_shard.pdf](https://github.com/flexion/ef-cms/files/6593017/Order_search_10_concurrent_1_replica_1_shard.pdf)

**Comment by codyseibert** [comment]
[Base_Line_Order_Search_1_replica_1_shard.pdf](https://github.com/flexion/ef-cms/files/6593033/Base_Line_Order_Search_1_replica_1_shard.pdf)

**Comment by sutt0n** [comment]
[BaseLine_Order_Search_10_users_1_replica_1_shard.pdf](https://github.com/flexion/ef-cms/files/6593346/BaseLine_Order_Search_10_users_1_replica_1_shard.pdf)

**Comment by sutt0n** [comment]
[Order_Search_15_users_2_replicas_4_shards.pdf](https://github.com/flexion/ef-cms/files/6593571/Order_Search_15_users_2_replicas_4_shards.pdf)
