### ISSUE TITLE
BUG: Same practitioner displaying multiple times in practitioner search results

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7801]
**Describe the Bug**
Multiple results are displaying for practitioner search that include identical information. The bar number links to the same practitioner page, yet there are several results in the list. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration / court's prod

**Who were you logged in as?**
docket

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to Advanced Search > Practitioner 
2. Search for "buch" under practitioner name

**Expected Behavior**
Each result in the list should be unique. 

**Actual Behavior**
There are multiple rows listed for the same bar number (BR1335)

**Screenshots**
![Screen Shot 2021-03-31 at 4.49.15 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a3dc5874-75ed-4596-bbd1-86bd43959e4a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
@kkoskelin In `test` when I search for practitioner name `ciraolo`, I'm still getting more than 1 of the same result:![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/0fb7005b-8f00-4cfa-b412-9e16edc38fb8)
