### ISSUE TITLE
BUG: Notice of Trial is 2 pages

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7804]
**Describe the Bug**
The Notice of Trial is 2 pages.  The signature block is going over to a 2nd page.  It should all be on 1 page.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**.
Court's prod

**Who were you logged in as?**
Jessica Marine

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Re-serving a document

**To Reproduce**
1. Go to 2040-20S
2. Click on the link for the Notice of Trial (entry ustaxcourt/ef-cms#6497).
3. Note that the signature block is being pushed to a second page.
[https://app.zenhub.com/files/152320868/41235720-9514-476c-ad7a-3c21dc4ea34b/download](https://app.zenhub.com/files/152320868/41235720-9514-476c-ad7a-3c21dc4ea34b/download)

**Expected Behavior**
The entire Notice of Trial is 1 page.

**Actual Behavior**
The signature block is being pushed to the second page so the Notice of Trial is becoming a 2-page document.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by codyseibert** [comment]
![Screen Shot 2021-04-08 at 5 54 30 PM](https://user-images.githubusercontent.com/1868782/114101273-7b3ad600-9893-11eb-9a41-fda4669d6e88.png)

Just to keep a note, I think the issue is related to the case caption being 2 lines which is pushing all the content down making another page.  I'm going to look into this tomorrow more.

**Comment by codyseibert** [comment]
I asked @JessicaMarine and she mentioned we should remove the white space directly above and below the boxes to allow for at least 2 extra lines to help fix this issue for 95% of all case captions.

**Comment by codyseibert** [comment]
two additional changes were requested by @JessicaMarine for this pdf since I am already working in that file:
(1) Password should be Passcode (4 places)
(2) Grammar issue -- Your Meeting ID and Passcode for the remote proceeding are:
