### ISSUE TITLE
BUG: Petition being served multiple times

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7805]
**Describe the Bug**

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

**Who were you logged in as?**
Justine Miles

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Serving Petition in 3092-21

**To Reproduce**
1. Log in as Justine Miles
2. Process an eFiled petition
3. Review "Completed" tab
4. Note that petition was served 3 times
   10:27:23
   10:27:35
   10:27:59
5. Review docket record and note page count by Petition is "0"

**Expected Behavior**
* Petition is only served 1 time
* Page count is accurately reflected on docket record.
* If the PDF uploaded during case creation is not able to be processed, the case should not be created.

**Actual Behavior**
* Petition served 3 times
* Page count is 0

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/3a0fefab-d524-421f-bb83-49ac40fac2e2)

https://files.slack.com/files-pri/TD3DSU09Y-F01T7AQQ77F/screen_shot_2021-04-05_at_11.44.27_am.png

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Looks like system is trying to calculate page count and is failing

> TypeError: n.catalog.Pages(...).traverse is not a function
>     at t.computePages [as populate]

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by mmarcotte** [comment]
Appears that the problem was in the PDF that was uploaded. I was able to replicate this in the `test` environment.

Find this PDF in the migration documents S3 bucket `e6bd925f-9071-4271-9260-d0c40924a94c`

Use it to create a petition.

Observe that the process fails with an error 400. 

An error like this is logged on the POST request to add a `/coversheet`:

```
TypeError: n.catalog.Pages(...).traverse is not a function
    at t.computePages [as populate] (/var/task/api.js:2892:1266)
    at t.access (/var/task/api.js:2626:281)
    at l.getPages (/var/task/api.js:2892:6035)
    at l.getPageCount (/var/task/api.js:2892:5946)
    at l.insertPage (/var/task/api.js:2892:6640)
    at Object.exports.addCoverToPdf (/var/task/api.js:3176:1920)
    at async Object.exports.addCoversheetInteractor (/var/task/api.js:3176:2560)
    at async e.logResults (/var/task/api.js:8204:122)
    at async /var/task/api.js:7968:690
    at async exports.handle (/var/task/api.js:7966:1162)
```

And yet the petition is created. Then when the clerk goes to process the petition, everything "looks good". The petition should not have been created if the PDF is bad. When the clerk serves the petition, the same error is re-encountered and logged.
