### ISSUE TITLE
BUG: Petitions Clerk unable to serve order

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7807]
**Describe the Bug**
In 15197-20, a Petitions Clerk prepared and served an Order.  The Order showed up on the Service list as being served, but was not added to the docket record:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/166ea980-afd5-4268-8475-0dcb10979147)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7c620685-1b8e-470d-aa14-96bdf656d772)

  Additionally, the Order was still in drafts w/ the Served stamp on it:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/a33ce38b-3d60-4d98-8569-b1cfdc5d4780)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's Production

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Serving an Order

**To Reproduce**
1. Go to 15197-20
2. Prepare an Order
3. Add to Docket Record & Serve
4. Note that Order did not get added to docket record; it shows up in Drafts w/ the served stamp on it; and it shows as Served on the "Completed" tab

NOTE: Validation Error

> The Case entity was invalid. {“servedPartiesCode”:“‘docketEntries[5].servedPartiesCode’ is not allowed to be empty”}

**Expected Behavior**
* When an Order is served, it is applied to the docket record; it has the served stamp on it; and it is removed from the drafts folder

**Actual Behavior**
* Order remained in drafts tab w/ served stamp on it
* Order wasn't added to docket record

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by matthopson** [comment]
I mentioned to @mmarcotte that I'm unsure if we should keep npm update in the bug DOD, as it feels a little out of place. He mentioned that we should consider only updating dependencies via this flow if necessary to fix the bug. Something I think is worth discussing with the team a little.

**Comment by JessicaMarine** [comment]
I discovered an issue when testing ustaxcourt/ef-cms#7807.  I'm torn on whether this is a separate bug or needs to be fixed as part of this one.  When a practitioner files a case on behalf of a petitioner, the practitioner's email is being linked to the petitioner.  If I remove the practitioner from the case, the system defaults the petitioner to `Electronic` service b/c it sees that email address.  Of course, that's not correct.  The practitioner email doesn't belong to the petitioner and the petitioner needs to get paper service. -- Going to log the email issue (petitioner getting practitioner's) as a separate bug.

**Comment by matthopson** [comment]
Adding this for reference: PR: https://github.com/ustaxcourt/ef-cms/pull/1017
