### ISSUE TITLE
Docket Clerk: Remove (Other) Petitioner from case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7829]
[Is this functionality already covered by ustaxcourt/ef-cms#7165 and the UI changes that will be implemented by ustaxcourt/ef-cms#7822?]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to remove any petitioner from an existing case.
 
## Pre-Conditions
- Petitioner is associated with a case
 
## Acceptance Criteria
- Docket Clerk needs the ability to remove one petitioner from a case at a time.
- At least one petitioner must remain in the case at all times.
- Once removed from a case, the removed petitioner should no longer have any access to the case, except for the public view.
- If the petitioner being removed from the case is represented by counsel, the counsel should also be removed from the case unless he/she is still representing a remaining party.
- Consider all the areas that the Petitioner needs to be removed from.
- Once petitioner is removed from the case, they are not "searchable" in the case, order and opinion searches
- User should no longer get service

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![remove party link.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/959987c3-2c6e-4655-8a6a-590d96ccddfe)

![remove party confirm other.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/1127e7cb-8d7d-438c-94fb-d760af1b7830)

Test cases

Logged in as docket clerk. 
- Browse to a case with a participant
- Case Information -> Parties -> Petitioner(s) & Counsel
- Click edit on a Petitioner

Edit Participant Screen
- [x] At the bottom of the form, include a link “Remove this Party”
- [x] Display confirmation modal to remove and update case caption.

Expected results 
- [x] App routes back to Parties ->Petitioner(s) & Counsel
- [x] Display success alert “Petitioner Successfully Removed”

**Comment by mariahkannenberg** [comment]
Notes from 5/27/21 Standup. No need to create v3 API for retrieving all petitioners on the case. We don't need to do this now. We can create a story in the future if it comes up. The IRS is still working to adopt v2. (Per Mike)
