### ISSUE TITLE
Docket Clerk: Remove Intervenor from case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7830]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to remove an intervenor from an existing case.
 
## Pre-Conditions
- Intervenor is associated with a case
 
## Acceptance Criteria
- Docket Clerk needs the ability to remove the intervenor from the case.
- Once removed from a case, the removed intervenor should no longer have any access to the case, except for the public view.
- If the intervenor being removed from the case is represented by counsel, the counsel should also be removed from the case unless he/she is still representing a remaining party.
- Consider all the areas that the Intervenor needs to be removed from.
- Once intervenor is removed from the case, they are not "searchable" in the case, order and opinion searches
- User should no longer get service

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
*No requirement that an intervenor remain in the case

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![remove party link.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/959987c3-2c6e-4655-8a6a-590d96ccddfe)

![remove party confirm intervenor.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/05c8f3c5-c643-481a-8af1-4c810e8ad7e5)

Test cases

Logged in as docket clerk. 
- Browse to a case with a participant
- Case Information -> Parties -> Intervenor/Participants & Counsel 
- Click edit on a Participant

Edit Participant Screen
- [x] At the bottom of the form, include a link “Remove this Party”
- [x] Display confirmation modal to remove and update case caption.

Expected results 
- [x] App routes back to Parties -> Intervenor/Participants & Counsel
- [x] Display success alert “Intervenor Successfully Removed”

**Comment by klohman** [comment]
Additional test cases (post 8131 refactor):

#### 1) Serve court issues document for case with removed intervenor
- [x] Removed intervenor does not appear under service parties on Add Docket Entry screen
- [x] Removed intervenor does not receive service (either paper or electronic) 

#### 2) Serve paper-filed document for case with removed intervenor
- [x] Removed intervenor does not appear under filing parties on Add Paper Filing screen
- [x] Removed intervenor does not receive service (either paper or electronic) 

#### 3) eFile a document for case with removed intervenor
- [x] Removed intervenor does not appear under filing parties on File a Document screen
- [x] Removed intervenor does not receive service (either paper or electronic) 

#### 4) Add counsel to a petitioner 
- [x] Removed intervenor does not appear under represented parties on Add Counsel screen

#### 5) Remove intervenor represented by counsel (counsel only represents this party) 
- [x] Intervenor counsel is removed from the case (does not display in UI 
- [x] Intervenor counsel does not receive service 
- [x] Intervenor counsel does not see case on their dashboard

#### 6) Remove intervenor represented by counsel (counsel represents another party still on case)
- [x] Counsel displays as representing remaining party 
- [x] Intervenor counsel receives service for remaining party 
- [x] Intervenor counsel sees case on their dashboard

**Comment by klohman** [comment]
## Feedback 

- On the Edit Party Information form, the Petitioner Type field needs to be updated to match the “Role type” on the Add Party form. The current field only has “petitioner” as the role, so when I went to edit an Intervenor, that field mistakenly is populated by petitioner instead of intervenor. 

- On the Edit Party Information form, “Remove this petitioner” should be updated to “Remove this Party”
- After removing intervenor, success message should say “Intervenor Successfully Removed” and the Intervenor/Participant tab should be selected (unless there are no more intervenors or participants on the case) 
- The title of the Intervenor/Participant tab should be “Intervenor/Participant(s)”
