### ISSUE TITLE
Docket Clerk: Remove Participant from case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7831]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to remove a participant from an existing case.
 
## Pre-Conditions
- Participant is associated with a case
 
## Acceptance Criteria
- Docket Clerk needs the ability to remove a participant from the case. 
- Once removed from a case, the removed participant should no longer have any access to the case, except for the public view.
- If the participant being removed from the case is represented by counsel, the counsel should also be removed from the case unless he/she is still representing a remaining party.
- Consider all the areas that the participant needs to be removed from.
- Once participant is removed from the case, they are not "searchable" in the case, order and opinion searches
- User should no longer get service

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* There is no requirement that there be any participants remaining on a case; all can be removed

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![remove party link.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/959987c3-2c6e-4655-8a6a-590d96ccddfe)

![remove party confirm.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/4b5f893f-552b-4c87-934b-1f656b0190c5)

Test cases

Logged in as docket clerk. 
- Browse to a case with a participant
- Case Information -> Parties -> Intervenor/Participants & Counsel 
- Click edit on a Participant

Edit Participant Screen
- [x] At the bottom of the form, include a link “Remove this Party”
- [x] Display confirmation modal to remove and update case caption.

Expected results 
- [x] App routes back to Parties -> Intervenor/Participants & Counsel
- [x] Display success alert “Participant Successfully Removed”

**Comment by klohman** [comment]
Additional test cases (post 8131 refactor):

#### 1) Serve court issues document for case with removed participant
- [ ] Removed participant does not appear under service parties on Add Docket Entry screen
- [ ] Removed participant does not receive service (either paper or electronic) 

#### 2) Serve paper-filed document for case with removed participant
- [ ] Removed participant does not appear under filing parties on Add Paper Filing screen
- [ ] Removed participant does not receive service (either paper or electronic) 

#### 3) eFile a document for case with removed participant
- [ ] Removed participant does not appear under filing parties on File a Document screen
- [ ] Removed participant does not receive service (either paper or electronic) 

#### 4) Add counsel to a petitioner 
- [ ] Removed participant does not appear under represented parties on Add Counsel screen

#### 5) Remove participant represented by counsel (counsel only represents this party) 
- [ ] participant counsel is removed from the case (does not display in UI 
- [ ] participant counsel does not receive service 
- [ ] participant counsel does not see case on their dashboard

#### 6) Remove participant represented by counsel (counsel represents another party still on case)
- [ ] Counsel displays as representing remaining party 
- [ ] participant counsel receives service for remaining party 
- [ ] participant counsel sees case on their dashboard
