### ISSUE TITLE
Admissions Clerk: Grant eAccess to all petitioners

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7832]
As an admissions clerk, so that all petitioners can gain electronic access to the system, I need the ability to grant them access.
 
## Acceptance Criteria
- Admissions clerk can add an email address for any petitioner who did not previously have one
- When Admissions Clerk adds the email address:
   - A new cognito account is created if one doesn't already exist for the email (See ustaxcourt/ef-cms#7708)
   - Existing cognito account is linked if the emails match (See ustaxcourt/ef-cms#7678)
- When a new Cognito account is created, the petitioner receives an email to verify their account
- Petitioner is able to verify their Cognito account and gain access to the system
- When Admissions Clerk adds the email address, if a cognito account already exists with that email, the case is linked to that user's account
- When a user is linked to a case (either through the new Cognito account or linkage to existing one), they have access to the case:
  	- It shows on their dashboard
  	- They have the associated view
  	- They can e-file documents
- Once the petitioner has verified their email, service information is updated to "electronic," unless they're represented by counsel
- Once the petitioner has verified their email, they begin receiving electronic service at the email that was added
- If petitioner has a verified email, service preference can be manually changed between paper, electronic, and none without an error being generated
- Issue from E2E UM testing: pending email not displaying on petitioner card despite showing correctly in the edit petitioner form
- Issue from E2E UM testing: When granting eAccess to petitioner on closed case, user can log in but service indicator is not updated to electronic

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Test cases

#### 1) Any Petitioner gains e-access to a case  - [see test 8 in Text Matrix](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)


#### 2) Add verified email to petitioner on Closed case 
* Expected results 
- [x] petitioner/intervenor/participant  service indicator updates to Electronic
- [x] Email displays under petitioner/intervenor/participant card as current email address

#### 3) Docket clerk/ admissions clerk changes any petitioner with a verified email service indicator to electronic 
* Login as docket clerk/admission clerk 
* Go to case
* Edit Party info for any petitioner 
   - petitioner has service indicator = None 
   - petitioner has verified email 
* Update service indicator to "Electronic" 
* Save
Expected results 
- [ ] Service indicator is updated and displays as Electronic 
- [ ] Petitioner receives service at their service email

**Comment by klohman** [comment]
8137 UX Review 

- Expected - if petitioner is represented by counsel, their service indicator should not change 
    - Actual - Service indicator auto-updated to Electronic 
    - Steps to reproduce 
        - Add petitioner to case 
        - Add counsel for petitioner
        - Add email to petitioner + activate 

- Activated email did not receive service email 
    - Add new email to petitioner + activate 
    - Create and serve Order 
    - Actual - no service email was received to the emai
