### ISSUE TITLE
Docket Clerk: Manage Practitioner(s) Associated with all Petitioners

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7835]
As a Docket Clerk, in order to make sure that a party’s representation is correct, I need the ability to manage the practitioner(s) associated with all petitioners.
 
## Acceptance Criteria
- Docket Clerk can manually add a practitioner for any petitioner on the case. (See ustaxcourt/ef-cms#6819)
- When a practitioner is added for a petitioner, the service preference for that petitioner should change to None.
- When a practitioner is added for a petitioner, it should be obvious in the UI that the party is represented by counsel.
- When a practitioner is added to any petitioner on a case, the practitioner should have full access to the case: see associated view, be able to eFile documents, have case on Dashboard.
- Docket Clerk can manually remove a practitioner from any petitioner on the case. (See ustaxcourt/ef-cms#6820)
- When a practitioner is removed from a petitioner, the service preference for that petitioner should change back to their service preference before they had counsel. [Okay to default to paper, if unclear]
- When a practitioner is removed for a petitioner, it should be obvious in the UI that the party is no longer represented by that counsel.
- When a practitioner is removed as the practitioner for all parties on a case, the practitioner should no longer have full access to the case: see public view, no longer able to eFile documents, case should not be on Dashboard.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Note for this AC- When a practitioner is removed from a petitioner, the service preference for that petitioner should change back to their service preference before they had counsel. 
    - This needs to account for when the counsel is removed completely from the case AND when counsel is updated to no longer represent a specific petitioner 
* Practitioner is able to edit contact information for any petitioner they represent ?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
Test cases:

- [x] Add counsel to any added petitioner [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] Request Access (as private Practitioner) representing added petitioner  [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] View Printable Docket Record with added petitioner and counsel [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] remove counsel for petitioner (counsel only represents that intervenor)  [(test 6)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] update counsel (change who they represent but don't remove them)  [(test 6)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438) (feedback being addressed in ustaxcourt/ef-cms#7890)

**Comment by klohman** [comment]
Feedback (to be addressed in ustaxcourt/ef-cms#7890)- otherwise all AC are met 

- [x]  Logged in as unassociated private Practitioner- Printable Docket is displaying all petitioner contact information
- [x] When counsel is edited (change who the counsel represents), Unrepresented petitioner service preference remains as none and does not revert back to original

**Comment by mariahkannenberg** [comment]
No engineering work done on this.
