### ISSUE TITLE
Docket Clerk: Manage Practitioner(s) for Intervenor

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7836]
As a Docket Clerk, in order to make sure that a party’s representation is correct, I need the ability to manage the practitioner(s) associated with an intervenor.
 
## Acceptance Criteria
- Docket Clerk can manually add a practitioner for an intervenor on the case. (See ustaxcourt/ef-cms#6819)
- When a practitioner is added for the intervenor, the service preference for that intervenor should change to None.
- When a practitioner is added for the intervenor, it should be obvious in the UI that the party is represented by counsel.
- When a practitioner is added to the intervenor on a case, the practitioner should have full access to the case: see associated view, be able to eFile documents, have case on Dashboard.
- Docket Clerk can manually remove a practitioner from the intervenor on the case. (See ustaxcourt/ef-cms#6820)
- When a practitioner is removed for the intervenor, the service preference for that intervenor should change back to their service preference before they had counsel. [Okay to default to paper, if unclear]
- When a practitioner is removed from the intervenor, it should be obvious in the UI that the party is no longer represented by that counsel.
- When a practitioner is removed as the practitioner for all parties on a case, the practitioner should no longer have full access to the case: see public view, no longer able to eFile documents, case should not be on Dashboard.
- Issue from E2E UM testing: Counsel for intervenor with no email is not displaying "No email provided" (displays as expected for counsel on petitioner card)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* (implied) but maybe we note that the practitioner must be a private practitioner to represent an intervenor
* Practitioner can edit the contact information for the intervenor they represent 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
Test cases:

- [x] Add counsel to any added intervenor [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] Request Access (as private Practitioner) representing added intervenor  [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] View Printable Docket Record with added intervenor and counsel [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] remove counsel for intervenor (counsel only represents that intervenor)  [(test 6)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] update counsel (change who they represent but don't remove them)  [(test 6)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438) (feedback being addressed in ustaxcourt/ef-cms#7890)
- [x] view display of counsel info on intervenor card 
      - No email - display "No email provided" 
      - pending email - display "email address (Pending)" 
       - current email. - display " [email address] "

**Comment by klohman** [comment]
## Intervenor / Participant Counsel display on card 

#### With active email 
- no changes 

#### No email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3b444538-ae72-43a8-a22f-d0a347b2299e)


#### Pending email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4a50610a-4341-4d50-bdbd-16777d0f26a4)
