### ISSUE TITLE
Docket Clerk: Manage Practitioner(s) for Participants

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7837]
As a Docket Clerk, in order to make sure that a party’s representation is correct, I need the ability to manage the practitioner(s) associated with a participant.
 
## Acceptance Criteria
- Docket Clerk can manually add a practitioner for a participant on the case. (See ustaxcourt/ef-cms#6819)
- When a practitioner is added for the participant, the service preference for that participant should change to None.
- When a practitioner is added for the participant, it should be obvious in the UI that the party is represented by counsel.
- When a practitioner is added to a participant on a case, the practitioner should have full access to the case: see associated view, be able to eFile documents, have case on Dashboard.
- Docket Clerk can manually remove a practitioner from a participant on the case. (See ustaxcourt/ef-cms#6820)
- When a practitioner is removed for a participant, the service preference for that participant should change back to their service preference before they had counsel. [Okay to default to paper, if unclear]
- When a practitioner is removed from a participant, it should be obvious in the UI that the party is no longer represented by that counsel.
- When a practitioner is removed as the practitioner for all parties on a case, the practitioner should no longer have full access to the case: see public view, no longer able to eFile documents, case should not be on Dashboard.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* (implied) but maybe we note that the practitioner must be a private practitioner to represent participant
* Practitioner can edit the contact information for the participant they represent 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Add Petitioner Counsel modal
* Participant should appear under “Who is this counsel representing” as (firstname lastname, Participant) with service type displayed
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2cfc5847-df05-4d8f-9f06-b0bd0546e3b9)


## Edit Petitioner Counsel screen
* Participant should appear under “Who is this counsel representing” as (firstname lastname, Participant) with service type displayed

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f06e30b2-7cb0-426c-96af-a732e84904f1)

**Comment by klohman** [comment]
Test cases:

- [x] Add counsel to any added participant [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] Request Access (as private Practitioner) representing added participant  [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] View Printable Docket Record with added participant and counsel [(test 5)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] remove counsel for participant (counsel only represents that intervenor)  [(test 6)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)
- [x] update counsel (change who they represent but don't remove them)  [(test 6)](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438) (feedback being addressed in ustaxcourt/ef-cms#7890)
- [x] view display of counsel info on participant card 
      - No email - display "No email provided" 
      - pending email - display "email address (Pending)" 
       - current email. - display " [email address] "

**Comment by mariahkannenberg** [comment]
No engineering work required for this.
