### ISSUE TITLE
Participant: Edit Contact Info.

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7841]
As the Court, in order to make sure we always have current information for a party, we need the ability to change contact information for a participant.

## Acceptance Criteria
- A participant can edit their own address and phone number (See ustaxcourt/ef-cms#6549) 
- Docket can edit address and/or phone number of a participant (See ustaxcourt/ef-cms#6789)
- Counsel of the party can edit address and/or phone number of other participant(s)
- When the address and/or phone of a participant is edited, a Notice of Change of Address/Phone/both is generated, added to the docket record, and served (See ustaxcourt/ef-cms#6886)
- A participant can edit their email address (See ustaxcourt/ef-cms#6890) 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Test cases 

#### 1) Participant / counsel / docket edits participant contact information - [see test 9 in Test Matrix ](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)


#### 2) Participant updates their email  - [see test 12 in Test Matrix ](https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438)

**Comment by klohman** [comment]
8152 UX Review 

- Participant updating email is not sending the verify email to the new email 
    - Steps to recreate 
        - Add email to Participant + activate email 
        - Login as Participant 
        - Update email 
        - Should receive a verify email 


**UPDATE** - Confirmed working on dev
