### ISSUE TITLE
BUG: Stipulated Decision not selected as message attachment after saving docket entry

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7845]
**Describe the Bug**
After saving a Stipulated Decision to the docket record (but not serving) from the message screen, the Stip Decision is not selected by default when returning to the message. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
 mig

**Who were you logged in as?**
docket 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing  7839

**To Reproduce**
1. Go to case 
2. Add Paper Filing and Serve- Proposed Stip Decision 
3. Create message w/ PSDE attached 
4. Go to message - Sign Stipulated Decision 
5. From message, click Add Docket Entry for SDEC 
6. Save entry. 

**Expected Behavior**
SDEC should be selected from the message attachments. 

**Actual Behavior**
PDSE (first attachment) is selected when returning to message screen. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
@klohman Is this the same bug as ustaxcourt/ef-cms#7727?
