### ISSUE TITLE
BUG: Edit link for Correspondence does not display on PDF preview via message detail view

### ISSUE THREAD

**Issue by sutt0n** [ustaxcourt/ef-cms#7847]
**Describe the Bug**
When logged in as a Docket Clerk and viewing a Correspondence document via the Message Detail view, the `Edit` link does not display.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
USTC Migration

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Login as docketclerk
2. Find a case
3. Add other documents along with correspondence
4. Send a message to yourself with correspondence document in 3
5. Open message, click on Correspondence document

**Expected Behavior**
The `Edit` link should have displayed in the PDF Preview component under the message detail view (when viewing a message).

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/1116426/115447863-96d0a580-a1de-11eb-8338-a39861497a98.png">

**Actual Behavior**
The `Edit` link did not display in the PDF Preview component under the message detail view.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
Duplicate of ustaxcourt/ef-cms#7627.
