### ISSUE TITLE
BUG: Public view of WRIT docket entry is not hyperlinked

### ISSUE THREAD

**Issue by rosiehsmith** [ustaxcourt/ef-cms#7851]
**Describe the Bug**
As a public user looking at a case with a served WRIT, the docket entry is not hyperlinked. 

**Business Impact/Reason for Severity**
Public users should be able to access court-issued WRIT documents from the public docket record

**In which environment did you see this bug?**

mig

**Who were you logged in as?**

irsPractitioner2

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

manual testing

**To Reproduce**
1. As an docketClerk, upload a pdf with document type WRIT to a case.
2. Serve the WRIT docket entry.
3. Login as irsPractitioner2 and search for the case.
4. In the docket record, look for the WRIT entry.

**Expected Behavior**
WRIT (served) docket entry is hyperlinked.

**Actual Behavior**
WRIT (served) docket entry is NOT hyperlinked.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
Is `WRIT` included in const EVENT_CODES_NOT_VISIBLE_TO_PUBLIC = [

**Comment by rosiehsmith** [comment]
Good question - after looking that up, yes, you're right. Is this not a bug then?

**Comment by JessicaMarine** [comment]
Not a bug. Closing :)
