### ISSUE TITLE
BUG: petitioner contact card displays on printable docket record with counsel

### ISSUE THREAD

**Issue by rosiehsmith** [ustaxcourt/ef-cms#7852]
**Describe the Bug**
As a public user viewing a case with counsel (petitioner counsel, respondent counsel, or both) the printable docket record is displaying the petitioner contact card.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
mig

**Who were you logged in as?**
irsPractitioner2

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
manual testing

**To Reproduce**
1. Login as a public user (irsPractitioner2)
2. Go to case 4373-21 with counsel
3. Click Printable Docket Record
4. View the PDF, and see that the petitioner contact displays

**Expected Behavior**
Petitioner contact card should not display in the printable docket record if the case has counsel (petitioner counsel, respondent counsel, or both).

**Actual Behavior**
Petitioner contact card displays in the printable docket record if the case has counsel (petitioner counsel, respondent counsel, or both).

**Screenshots**
![image](https://user-images.githubusercontent.com/16403861/115576342-43129a80-a278-11eb-969b-2600d93a113a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
Not a bug.  IRS practitioners *can* see the contact information for cases they are not yet associated with.  I tested this when not logged in and it is working correctly.
