### ISSUE TITLE
BUG: Add Petitioner button not displaying in Case Information > Petititoner view

### ISSUE THREAD

**Issue by sutt0n** [ustaxcourt/ef-cms#7853]
**Describe the Bug**
While logged in as a docket clerk and viewing a case with `General Docket - Not At Issue`, I navigated to the `Case Information > Petitioner` tab and expected an `Add Petitioner` button via manual testing; however, this button did not appear.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court Migration

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual Testing

**To Reproduce**
1. Login as Docket Clerk
2. Navigate to case (used `4001-21`)
3. Go to `Case Information`
4. Go to `Petitioner` - no `Add Petitioner` button found

**Expected Behavior**
Expected to see `Add Petitioner` button.

**Actual Behavior**
`Add Petitioner` button was not shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/1116426/115583481-8af0ec00-a28f-11eb-883a-b3f83ff1092e.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
This work hasn't been deployed to `mig` yet.  Closing for now.
