### ISSUE TITLE
BUG: Several pages of PDF are not viewable on Safari (iOS)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7854]
**Describe the Bug**
Judge Pugh is not able to view pages 27 - end of document in dkt 21959-16, entry 238 – the PDF appears BLANK -- on her MacBook Pro (apple) or iPhone.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod.  Able to replicate on iPhone in mig.

**Who were you logged in as?**
Judge Pugh (any user with access to PDFs in 21959-16)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
**On a Mac or iPhone, using Safari**
1. Log in as a user with access to 21959-16 (any court user)
2. Go to entry ustaxcourt/ef-cms-flexion#238.
3. Scroll to page 27.
4. Note that page 27 to the end of the PDF are blank pages.

**Expected Behavior**
* User can see all PDF content in all browsers (except IE)

**Actual Behavior**
* User is not able to see all PDF content in Safari

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/bd2c6390-695d-4c40-9f73-9984cc65b015)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
@JessicaMarine I think this may be an issue with the original document + Mac's pdf renderer. If you look at where the pages get cut off in another browser that allows the page to be viewable, it seems to go unelectable text - almost like the document was partially OCR'd, or otherwise processed in some way that made some of the text readable and left the rest unreadable. Downloading the PDF on a Mac and opening it in preview will also produce these results where the pages don't show up - so it's unlikely there is anything that can be done about it.

**Comment by JessicaMarine** [comment]
Advised Judge Pugh that it is an issue with the underlying PDF.  Closing bc not a bug.
