### ISSUE TITLE
Order Search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7855]
As a user of the system, so that I may search for and find orders in a way I'd expect to, I need order search to be designed in a way that fits my mental model for searching and finding orders.

Acceptance Criteria:
* Users do not get logged out or timed out when performing searches or when many concurrent searches are performed
* Users can perform a search using exact matches
* Users can perform a search using partial matches
* Improve user experience for returning results (rate limiting)
* Other usability enhancements are completed based on research

**Comment by cholly75** [comment]
Done.
