### ISSUE TITLE
BUG: IRS Practitioner sees petitioner contact information on printable docket record before being associated with the case

### ISSUE THREAD

**Issue by rachaelparris** [ustaxcourt/ef-cms#7861]
**Describe the Bug**
IRS Practitioner sees petitioner contact information on printable docket record before being associated with the case. It is valid for the petitioner contact information to display on the case information screen, but they should get the public view of the printable docket record according to ustaxcourt/ef-cms#7602.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Migration

**Who were you logged in as?**
IRS practitioner not associated with case

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing

**To Reproduce**
1. Login as an IRS practitioner
2. View case detail for a case you are not associated with
3. View Printable Docket Record

**Expected Behavior**
Petitioner contact information should not display on the printable docket record.

**Actual Behavior**
Petitioner contact information is displayed on the printable docket record.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
This is not a bug.  We allow the IRS to see a practitioner's contact information before being associated with the case.  @klohman Do we need to update the testing scenario?

**Comment by klohman** [comment]
I referred back to the story [7441]( https://github.com/flexion/ef-cms/issues/7441 ) where we granted the IRS the ability to see petitioner info and it specifically says they should be seeing the public Docket Record. Did we make changes after this?

**Comment by matthopson** [comment]
https://github.com/ustaxcourt/ef-cms/pull/1103
