### ISSUE TITLE
BUG: Admission Clerk Unable to Edit Practitioner Information

### ISSUE THREAD

**Issue by rachelschneiderman** [ustaxcourt/ef-cms#7862]
**Describe the Bug**
Unable to save edits to a practitioner's information as an admissions clerk.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
https://mig.ef-cms.ustaxcourt.gov/

**Who were you logged in as?**
admissionsclerk1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Manual testing for 7839

**To Reproduce**
1. Log in as admissionsclerk1
2. Search for a practitioner by bar number
3. Edit practitioner address
4. Save edits
5. Observe progress spinner displays and nothing ever happens.

**Expected Behavior**
After submitting edits to a practitioner's information. The changes should be saved and the user should be navigated back to the practitioner detail page with a success message. 

**Actual Behavior**
Progress spinner displays indefinitely. Nothing ever happens.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
@rachelschneiderman Is this a bug or does it have to still do with the email address on those practitioner accounts?

**Comment by rachelschneiderman** [comment]
@JessicaMarine I totally forgot about this. I just tried to reproduce on a practitioner with a valid email and it worked! Thanks for remembering! I will close this bug.
