### ISSUE TITLE
BUG: Alignment and margins on Case Search Form Fields

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7865]
**Describe the Bug**

The headers don't align and the buttons break out of the container buttons don't on the Public Case Search Form

**Business Impact/Reason for Severity**

Just looks sloppy

**In which environment did you see this bug?**

Any

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Going to main page

**To Reproduce**
1. Go to https://mig.ef-cms.ustaxcourt.gov/

**Expected Behavior**

Would expect these headers to line up:

* Country
* State
* Year filed

Would expect the light blue container to include the dark blue of the buttons and have some padding or margins around the buttons themselves.

**Actual Behavior**

The headers aren't aligned

The buttons break out of the blue backgrounds

**Screenshots**

<img width="1731" alt="Screen Shot 2021-04-22 at 10 38 01 PM" src="https://user-images.githubusercontent.com/5023502/115811087-161bd000-a3bd-11eb-9aa7-342ce8989b22.png">

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser Chrome
 - Version Version 89.0.4389.128 (Official Build) (x86_64)

**Cause of Bug, If Known**

CSS is annoying

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
Included in ustaxcourt/ef-cms#7825.
