### ISSUE TITLE
BUG: 10/4 Detroit session getting 400 error

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7866]
**Describe the Bug**
When trying to open the 10/4 Detroit session (under the New tab), you get a 400 error.  Error in console is:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/1cfc9f28-2d74-4382-994c-9aa491906d04)

**Business Impact/Reason for Severity**
Unable to see the eligible cases or cut this calendar

**In which environment did you see this bug?**
Prod; able to replicate in `mig`

**Who were you logged in as?**
Any court user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as a Court user
2. Go to the 10/4 Detroit session under the New tab
3. Note that you get a 400 error when clicking on the session

**Expected Behavior**
* Session opens up without error

**Actual Behavior**
* 400 error; unable to open session

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/239910eb-cc68-49eb-af3f-36951a373091)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
After quite a bit of digging, I've determined there are a few things happening here:

The main reason THIS error is being thrown is there are multiple `eligible-for-trial-case-catalog` records coming back with the same docket number, so the batchGet on dynamo is throwing a "duplicate keys" error.

Going back to the root of the problem, it is possible to end up with these additional records by doing the following.

1) Create a case of type Deficiency with a given preferred trial location
2) Create a trial session for that ^ city
3) Go to the created case and ensure its status is NOT ready for trial
4) Add the case to the trial session
5) Change the case status to Ready For Trial
6) Change the case type to CDP
7) Delete the trial session
8) go to another trial session from the same city (where this case would be eligible)
9) Note that it throws a 400

**Comment by matthopson** [comment]
PR to prevent this state. https://github.com/ustaxcourt/ef-cms/pull/1120
Mike is correcting the offending case (13999-20) mapping records.
