### ISSUE TITLE
BUG: Records modified in the UI during a blue/green deploy are not being migrated

### ISSUE THREAD

**Issue by rachelschneiderman** [ustaxcourt/ef-cms#7869]
**Describe the Bug**
Records being updated during a migration deploy are not being updated. 

**Business Impact/Reason for Severity**
Unable to view messages and/or QC items.

**In which environment did you see this bug?**
USTC production

**Who were you logged in as?**
docketclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Attempting to view messages.

**To Reproduce**
1. Start a deployment with a migration.
2. Before switching colors, update an entity (using the UI) that would have been changed/updated during the migration and save that update.
3. View that entity in dynamo and see that the record was not migrated/updated.

**Expected Behavior**
Records that are updated in the UI during a deploy that has a migration should also be migrated before being saved into the destination table.

**Actual Behavior**
Records updated in the UI are not migrated before being saved into the destination table.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
Migration scripts were not being added into `migration.js`, the handler that is responsible for updating data that is being updated live in the UI while a migration deploy is in progress.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
Comments left in: https://github.com/ustaxcourt/ef-cms/pull/1125

Trying to ensure that the blue/green migrations do not overwrite "newer" records that have been migrated by live updates. If the older records that are being migrated overwrite the newer record, we would experience data loss.
