### ISSUE TITLE
Party Redesign: Docket Clerk - Edit Party Information

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7872]
As a Docket Clerk, in order to update party information, I need the ability to edit party information in a more user friendly way.

## Acceptance Criteria
* Docket clerk can edit and save party information
* Docket Clerk can edit the petitioner type for a party
* Docket Clerk can seal an address

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Edit Party Information (replace/updates the Edit Petitioner Information form)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ad18993a-2d75-4a54-b2ec-deb20648670c)

**Petitioner type**
* Populates with current petitioner type (Petitioner)
* Intervenor and Participant will be added in future stories 

**Seal address**
Add Seal Address checkbox 

**Form content**
Same as current Edit Petitioner Information form


~~## On Save~~

## On Checking Seal Address
Display Seal Address modal

**On Save and Seal Address is NOT checked**
App routes to Parties page with success message 
Updates are saved and display in UI 

**Seal Address IS checked**
Display Seal Address modal

**On Yes, Seal Address** 
Modal closes and app reloads page with Seal Address checkbox disabled 
Display success Alert "Address sealed
Address displays as sealed in UI 
Any other updates on form are saved and display in UI 
If changes were made to the address or phone, no Notice of Change of Address/Phone/both would be generated

## Seal Address modal 
![sealaddress.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/09f629f7-eafa-49c7-89d1-e49edbe3488b)

~~if Seal Address checkbox is checked - on Save - show modal~~
~~No changes to modal content~~

**Comment by klohman** [comment]
#### 1) Docket clerk edits petitioner information 
* Login as docket clerk 
* Go to case 
* Click Case Info > Parties 
* Click Edit link for petitioner ustaxcourt/ef-cms#6491 
* Update petitioner info 
* Save 
Expected results 
- [x] Form title displays as Edit Party Information 
- [x] Current functionality is unchanged 
    - If address / phone is updated, Notice of Change of Address / Phone is generated 
    - If service is updated, petitioner receives service through update method

#### 2) Docket clerk seals petitioner address 
* Login as docket clerk 
* Go to case 
    * Case has at least 2 petitioners 
* Click Case Info > Parties 
* Click Edit link for petitioner ustaxcourt/ef-cms#6491 
* Check “Seal Address” checkbox 
~~* Save ~~
* Click Yes, Seal Address
Expected results 
On Save, 
- [x] Seal address confirmation modal displays 
On Yes, Seal Address
- [x] Modal closes and app routes to Parties tab with success message displayed 
- [x] Petitioner 1 address displays as sealed 
    - Shows red in UI for docket clerks 
    - Is hidden for other court users 
    - Does not appear on Printable Docket Record

**Comment by klohman** [comment]
#### 6) Docket clerk edits petitioner information 
* Login as docket clerk 
* Go to case 
* Click Case Info > Parties 
* Click Edit link for petitioner ustaxcourt/ef-cms#6491 
* Update petitioner info 
~~* Save ~~
Expected results 
- [x] Form title displays as Edit Party Information 
- [x] Petitioner type field displays and is populated with "Petitioner" 
- [x] Current functionality is unchanged 
    - If address / phone is updated, Notice of Change of Address / Phone is generated 
    - If service is updated, petitioner receives service through update method

#### 7) Docket clerk seals petitioner address 
* Login as docket clerk 
* Go to case 
    * Case has at least 2 petitioners 
* Click Case Info > Parties 
* Click Edit link for petitioner ustaxcourt/ef-cms#6491 
* Check “Seal Address” checkbox 
* Save 
* Click Yes, Seal Address
Expected results 
On Save, 
- [ ] Seal address confirmation modal displays 
On Yes, Seal Address
- [ ] Modal closes and app routes to Parties tab with success message displayed 
- [ ] Petitioner 1 address displays as sealed 
    - Shows red in UI for docket clerks 
    - Is hidden for other court users 
    - Does not appear on Printable Docket Record
