### ISSUE TITLE
Party Redesign: Update the Add Petitioner form to accommodate all party types

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7873]
As a Docket Clerk, in order to accommodate all party types, I need the original petitioner form to be updated to include all party types. 

## Acceptance Criteria
* Docket Clerk can manage all party types in one form

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Add Party form 

**REPLACES “Add Petitioner” form** 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/045304ef-29e7-41d2-be3e-4c8937d6f9d6)

**Petitioner type**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7a625665-cdd6-441f-8440-0fcd4ab84208)

Dropdown options include: 
Petitioner 
Intervenor (TBD ustaxcourt/ef-cms#7827)
Participant (TBD 8133)

**Form content** * identical to current “Add Petitioner” 
 
#### On Save 
app routes to Parties screen with success message (no changes)
Party is added to case and displays in UI (no changes)

**Comment by klohman** [comment]
## Test Cases 

#### 1) Docket clerk adds petitioner to case 
* Login as docket clerk 
* Click Case Info > Parties 
* Click Add Party 
* Select “Petitioner” for Petitioner Type 
* Complete form
* Save 
Expected results 
- [ ] Form title displays as Add Party 
- [ ] Petitioner Type field displays the following options 
    - Petitioner
- [ ] On save, petitioner is added and current functionality is unchanged (see 5386) 
- [ ] Added petitioner displays in Petitioners & Counsel tab
