### ISSUE TITLE
Party Redesign: Case header update - represented indicator

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7874]
As a Court User, so that I know when a party is represented by counsel, I need see when a party is represented.

## Acceptance Criteria
* Court users are aware when any party (excluding respondent) is represented by counsel from anywhere in the case

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Case Header Update- Represented Indicator 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7ca58f99-7e99-44c8-abf0-b4c40f6de6b5)

* Display "Represented" indicator if any party other than respondent (petitioner, intervenor, participant) is represented by counsel

**Comment by klohman** [comment]
## Test Cases

#### 1) Court user (all) sees indicator when party is represented by counsel 
* Login as court user 
* Go to case 
    * Case w/ petitioner/ intervenor/ participant counsel 
    * Case w/o petitioner/ intervenor/ participant counsel
    * Case w/ respondent counsel only
Expected results 
- [x] Represented indicator displays for Case w/ petitioner/ intervenor/ participant counsel 
- [x] Represented indicator does not display for Case w/o petitioner/ intervenor/ participant counsel 
- [x] Represented indicator does not display for Case w/ respondent counsel only
