### ISSUE TITLE
BUG: File names in Trial Session download are too long for Windows machines to open

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7877]
**Describe the Bug**
When downloading a trial session, the individual documents on each case are saved with the following naming convention: Filed Date_Index #_Description (e.g. 2019-01-22_0001_Petition) (0001 is the docket record index number, use the fully concatenated document title).  Windows machines cannot open files that names longer than 255 characters.  Given that some of the descriptions (doc titles) are longer than that, any zip file that has a file name longer than 255 character results in the zip file being invalid and unable to be opened.

Potential Solution: Truncate the file names to an acceptable length.

**Business Impact/Reason for Severity**
Need to access zip file.

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Judge Urda

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as Judge Urda [**Note: Need to be on a Windows machine to replicate issue**]
2. Download all cases on his 4/26/2021 NY trial session
3. Note that you cannot open the resultant zip file on a Windows machine

**Expected Behavior**
* Judge can open zip file

**Actual Behavior**
* Zip file is invalid and cannot be open.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/3b9ff994-af98-48fe-8b0e-ba307998fb6e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
FYI, @JessicaMarine :  The code changes I'm making will indeed ensure that the file names do not exceed 255 characters.  However, the case still remains that the *overall* path length permitted by Windows could be exceeded.  In this case, you may have to move your ZIP file to `c:\temp` instead of `C:\Users\Jessica.Marine\OneDrive - The United States Tax Court\Downloads\`.  This is a known problem with Windows.  If you encounter this error again, please save the ZIP itself so we can try to look at its contents together.

**Comment by JessicaMarine** [comment]
@kkoskelin I am unable to download a trial session that has a document longer than 255 characters. This is the error in the Error logs:
TimeoutError: Connection timed out after 300000ms

I was testing using Judge Urda’s San Antonio session in `test` environment

**Comment by mmarcotte** [comment]
This error was actually reported by the fix in ustaxcourt/ef-cms#7844. the `onError` handler for the `applicationContext.getPersistenceGateway().zipDocuments({...)` call.
