### ISSUE TITLE
BUG: Petitioner able to eFile documents before Petition served.

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7885]
**Describe the Bug**
In 3648-21, the petitioner was able to eFile additional documents **before** the Petition was served.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Create an account as a petitioner
2. eFile a Petition
3. Note that petitioner has ability to eFile documents even though the Petition hasn't been served.

**Expected Behavior**
* Parties should not be able to eFile any documents in a case until the Petition is served

**Actual Behavior**
Petitioner eFiled 26 documents in case before Petition was served.
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/708ff2ed-95b6-436b-882d-b7fb3a897bb4) ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/d1e35039-7624-4e16-91d9-1aa73004fc44)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
It seems likely that this case was paper-filed and created by a petitions clerk, hence the "Letter" entry.

However, the "File a Document" button would have become visible to the petitioner when they logged in, because this button is shown on the condition that *any* docket entry on the case is regarded as "served":
```
const caseHasServedDocketEntries = rawCase => {
  return !!rawCase.docketEntries.some(isServed);
};
```

Additionally, the `fileExternalDocumentInteractor` attempts to check *only* the ROLE_PERMISSIONS of the user, but checks no conditions specifically on the case.

We will probably need to check the case specifically to determine whether the _Petition_ has been served, like this:
```
const caseHasServedPetition = rawCase => {
  // FIXME do this
  return !!rawCase.docketEntries.some(isServed);
};
```

And then in the interactor, we have an additional block:
```
if (!Case.caseHasServedPetition(caseToUpdate)) {
  throw new UnauthorizedError('Unauthorized');
}
```

**Comment by JessicaMarine** [comment]
@kkoskelin This case was eFiled by a petitioner.  The Court added the paper filing that came in after the case was initiated, but before the petition was served.  The petition has still not been served in the case and the petitioner has eFiled 26 additional documents.

**Comment by matthopson** [comment]
Pull request: https://github.com/ustaxcourt/ef-cms/pull/1213

**Comment by matthopson** [comment]
Moving to blocked while we sort out some concerns about this behavior and some conflicting behavior that needs to be addressed.

**Comment by matthopson** [comment]
PR closed after discussion with PO. This is an edge case that docket clerks will need to be aware of for now. We also discussed the potential for a user story that could be created to help with messaging on this if desired.
