### ISSUE TITLE
BUG: Docket Clerk cannot change case type to deficiency b/c case doesn't have statistics

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7888]
**Describe the Bug**
In 1139-21, a Docket Clerk was trying to change the case type from CDP (Lien/Levy) to Deficiency.  When they tried, they got an error saying Deficiency requires at least 1 statistics.  This seems to be a chicken and the egg issue:  You can't change a case type to deficiency because there isn't any case statistics entered, but you can't enter the required statistics until the case type is deficiency.

**Business Impact/Reason for Severity**
Unable to get case type into correct status

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**
Docket Clerk (Arraja Green)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Working -- trying to change the case type in 1139-21 in response to an order

**To Reproduce**
1. Login as Docket Clerk
2. Go to 1139-21L
3. Try to change case type from `CDP (Lien/Levy)` to `Deficiency`
4. Note the error: "statistics" must contain at least 1 items
5. Note that you cannot enter the statistics necessary to meet the validation *until* the case type is deficiency

**Expected Behavior**
Docket Clerk can change case type to Deficiency and then enter statistics

**Actual Behavior**
Docket Clerk is prevented from changing case type to Deficiency b/c no statistics; but no statistics can be entered until case status is Deficiency

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
PR https://github.com/ustaxcourt/ef-cms/pull/1228
