### ISSUE TITLE
Replace Quill

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7896]
As an engineering team, so that we may provide a plugin that supports WIZIWIG functionality in the app, we need to replace Quill, which has a security vulnerability.

## Acceptance Criteria
* Investigate an alternative for Quill
* Share pros and cons of alternatives with the court
* Experiment to find the best fit
* New editor should have **at least** as much functionality as Quill:
   * Ability to copy/paste from Word and retain formatting
   * Ability to copy/paste from other sources (e.g., WordPerfect) -- OK if formatting drops
   * Ability to change font size
   * Basic formatting options (bold, underline, italics)
   * Advanced formatting options (bullets, numbered list, indent in/out)
* Content started with Quill needs to be editable with the new editor post deploy
~~* Replace Quill with new editor~~ [Per Jessica: Hold implementation for new story]

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
From the refactoring item:
* Replace Quill with another WYSIWYG editor as it has a known security vulnerability that will likely not be fixed as the library has been abandoned. The decision to replace was voted on here. https://flexion.slack.com/archives/CD4PNKEPK/p1620748555241100
* Possible replacement: https://www.slatejs.org

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
![image.png](https://images.zenhubusercontent.com/5bc501b8601657183131caf3/ef11eee4-b8cb-4ea2-9371-18f6514bc7aa)

**Comment by kkoskelin** [comment]
I stand by my original suggestion of TinyMCE5 + "PowerPaste" functionality which is highly compatible with MS Word paste.  Demo here:
https://www.tiny.cloud/tinymce/features/powerpaste#powerpaste-demo

**Comment by rachaelparris** [comment]
Recommendation from the team is TinyMCE.

Covers all features [for premium tiers]
Would have to talk to sales team for custom pricing 

Pros: 
* Meets more AC than all the other editors we tried
* Easier to implement than any other editor
* Toolbar is more customizable than other editors
* More supported and widely used than other editors
 
Cons:
* List formatting was not retained when copying from Word (although this was an issue with every editor we tried)
* Any font formatting was not retained when copying from other sources (Google drive, Google sheets)

Notes:
* Allows user to choose different fonts (might be something we can disable) and also retains different fonts when pasting from Word (might be something we can fix)

**Comment by mrinsin** [comment]
Amazing spreadsheet comparing features of the editors we tried, made by @klohman - [here](https://docs.google.com/spreadsheets/d/1qRkP2j9S4WFKh855prOdIh9LRZycUuX9cAabin5yQ4E/edit?ts=60db4fd3#gid=0)

**Comment by JessicaMarine** [comment]
Because the potential replacement for Quill involves a fee, Jessica to check with Judge Buch and Stephanie to see if we should be considering other options (e.g., Word) with broader functionality.  This is a business decision. Will create new story with broader AC if ^^^ or to implement TinyMC.  Keep Quill (with known vulnerability) for now.

Note:  Other concern -- Tiny MC is hosted by a 3rd party, so it would involve a slight security concern in that we'd be exposing our UI to them.
