### ISSUE TITLE
BUG: Order of Dismissal for Lack of Jurisdiction is showing on docket record as an externally-filed document

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7898]
**Describe the Bug**
In 225-21, entry ustaxcourt/ef-cms-flexion#11, the Docket Clerk added an Order of Dismissal for Lack of Jurisdiction to the docket record.  However, it looks like DAWSON is treating it as an externally-filed document -- it has a red star next to it like it hasn't been QC'd; if you click on it, it gives you the option to QC; if you QC the item and then click "edit" it loads external-filed documents in the dropdown

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod; also exists in `mig` and `test`

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as a Docket Clerk
2. Go to 225-21
3. Note that entry ustaxcourt/ef-cms-flexion#11 (Order of Dismissal for Lack of Jurisdiction) is behaving as an externally-filed document

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by JessicaMarine** [comment]
@mmarcotte Can you see if there is anything in the logs from Kayla Merchlinsky on May 10th that might explain what happened here.

**Comment by rachaelparris** [comment]
This bug occurred when two docket clerks were creating a docket entry for the same draft document at the same time. To recreate, login as `docketclerk1` in one browser and `docketclerk2` in a second browser. Create a draft order on a case, then open the Add Docket Entry screen for that draft order on both browsers. `Save and Serve` the docket entry as `docketclerk1`, wait about a minute, then `Save Entry` as `docketclerk2`.
