### ISSUE TITLE
BUG: 11/1/2021 NYC session is throwing 400 error

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7899]
**Describe the Bug**
The 11/1/2021 NYC trial session -- under New -- is throwing a 400 error

**NOTE: Similar thing happened before: https://github.com/flexion/ef-cms/issues/8186**

**Business Impact/Reason for Severity**
Need to cut this calendar THIS week

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to New trial sessions
2. Click on 11/1/2021 NYC session (https://app.dawson.ustaxcourt.gov/trial-session-detail/212c8774-e46b-497e-8597-63a8c97bf5e4)
3. Observe that the trial session detail does not open and you get a 400 error
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/e7a9d342-7254-49b3-be72-40b2366eaf2a

**Expected Behavior**
Trial session detail opens w/ list of eligible cases

**Actual Behavior**
400 error

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/0b1a5d4e-c9bf-4e31-a15e-230c45e8b6d0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
Looks like the case that caused this is
115-20

And it appears that adding L to the Case may have triggered the error. That's what happened today.

**Comment by mmarcotte** [comment]
We ended up with four mapping records for that case

![Screen Shot 2021-06-01 at 6.10.11 PM.png](https://images.zenhubusercontent.com/5f172596f365e24f3ab7b0c3/5f94a522-dd2c-4a18-b92f-fe97372abf4a)

Could this be because `createCaseTrialSortMappingRecords(...)` adds two, but doesn't check that it needs to remove records as `updateCaseTrialSortMappingRecords(...)` does

**Comment by mmarcotte** [comment]
![Screen Shot 2021-06-02 at 10.35.59 AM.png](https://images.zenhubusercontent.com/5f172596f365e24f3ab7b0c3/d48328db-c419-4550-8223-b92d7ad82a60)
![Screen Shot 2021-06-02 at 10.35.55 AM.png](https://images.zenhubusercontent.com/5f172596f365e24f3ab7b0c3/42226aba-cbe6-4a70-bf00-85de9e944061)
![Screen Shot 2021-06-02 at 10.35.52 AM.png](https://images.zenhubusercontent.com/5f172596f365e24f3ab7b0c3/5c6e6626-167e-4ba8-9bf4-d79d1f17f714)
![Screen Shot 2021-06-02 at 10.35.47 AM.png](https://images.zenhubusercontent.com/5f172596f365e24f3ab7b0c3/2d2103e8-c59b-4c11-88d8-4e25b7a1825a)

**Comment by matthopson** [comment]
Was unable to reproduce the bug via the application, but was able to recreate the data state and verify that this fix will prevent multiple sets of sort records from being created.

https://github.com/ustaxcourt/ef-cms/pull/1303

Mike, manually removed the other problematic mapping records for the given case, and the trial session loads as expected.
