### ISSUE TITLE
BUG: Cannot load case

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7910]
**Describe the Bug**

Case that exists in the system is unretrievable as a logged in user. Validation error is saved to the logs:

```
The Case entity was invalid. {"documentType":"'docketEntries[845].documentType' is required","eventCode":"'docketEntries[845].eventCode' is required","judge":"'docketEntries[845].judge' is required","signedAt":"'docketEntries[845].signedAt' is required","signedJudgeName":"'docketEntries[845].signedJudgeName' is required","userId":"'docketEntries[845].userId' is required"}
```

**Business Impact/Reason for Severity**

Need access to the case, which is set for trial within a week

**In which environment did you see this bug?**

prod

**Who were you logged in as?**

any

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

load the case

**To Reproduce**

1. Login as any Court user
2. Search for case `6944-11`
3. See that case is not found.
4. See error in logs

**Expected Behavior**

load the case properly

**Actual Behavior**

Case not found

**Cause of Bug, If Known**

Probably case is getting too large.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
Duplicate of ustaxcourt/ef-cms#7909
