### ISSUE TITLE
Court: Monitoring ES health

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7911]
As DAWSON support staff, in order to monitor the well being of the application and make future decisions about search, we need to gather search metrics from production.

## Acceptance Criteria
* Court can capture search metrics from prod using the logger:
   * Number of requests and request time in Kibana
   * ES cluster health
      * CPU Utilization
      * Cluster Search rate (not document search rate)
       * Memory pressure.
* Logger pulls cluster every 5 minutes
* Kibana visualization that demonstrates requests per minute
* Ability to identify spikes in search to correlate with ES health / load

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- Consider using a health check endpoint to query the node health / Kibana search rates and writing log entry back to Kibana for easier computation / visualization

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Blocked:
* Precondition not met
* AC incomplete
* Search not working well

**Comment by klohman** [comment]
Could we include these metrics? 

Usability Metrics 

* Top search terms 
* Terms with no results 
* Number of searches with no results 
* Terms with too many results (over 100)
* Daily total searches 
* CTR

* Could we track how often users enter unsupported characters?

**Comment by cholly75** [comment]
@mmarcotte - this might be the story for monitoring efforts.

**Comment by mariahkannenberg** [comment]
Needs More Info - Cody to give a demo and weigh in on how this story may overlap with ustaxcourt/ef-cms#7949

**Comment by mmarcotte** [comment]
I'm going to revisit this story and possibly incorporate it into the health status that we already have. i just don't think this is worth your time at present.
