### ISSUE TITLE
BUG: Practitioner contact info. not updating on cases

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7916]
**Describe the Bug**
As the request of an attorney (bar no. EA0154), an Admissions Clerk updated her address and phone number.  Although the address and phone was updated on the practitioner's profile, the change did **not** carry through to the practitioner's cases and **no** Notice of Change of Address and Phone was generated.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod; when tried to replicate on `mig` it wouldn't let me update the address on the profile

**Who were you logged in as?**
Admissions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as Admissions Clerk
2. Update the address and phone number of practitioner EA0154
3. Note that the address and phone update on the profile but did not carry through to her cases
4. Note that no Notice of Change of Address and Phone were generated in her open cases (49 of them)

Open Cases: 10345-18, 10453-18, 10494-18, 11020-20, 11865-20, 11866-20, 12674-20, 13926-19, 15310-18, 15981-17, 16258-08, 16711-08, 17338-19, 18290-18, 21033-18, 21034-18, 21035-18, 26889-16, 26890-16, 26891-16, 28951-14, 2897-15, 330-19, 3823-19, 4421-19, 479-20, 494-20, 498-19, 6105-16, 6118-19, 6128-19, 6141-19, 6793-19, 7669-14, 7670-14, 7689-20, 7734-20, 7735-20, 7737-20, 7740-20, 7798-20, 7799-20, 7801-20, 7814-20, 7841-20, 8103-19, 8154-19, 8336-20, 948-21

**Expected Behavior**
When Admissions updates a practitioner's address or phone number, it:
   * updates the information on the profile
   * updates the information in each of the practitioner's cases
   * generates a Notice of Change of [Address/Phone/both] in all open cases and any case closed 6 months or less.

**Actual Behavior**
When Admissions updates a practitioner's address or phone number, it:
   * updates the information on the profile
   * does **NOT** update the information in each of the practitioner's cases
   * did **NOT** generate a Notice of Change of Address and Phone in all open cases and any case closed 6 months or less.
**Screenshots**
Update address and phone on profile:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/350e4ab0-7e41-42ab-a46f-00bdb0e96edf)

Old address and phone on case:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/2eca01d2-e3e8-435b-849e-5ef347da1c91)

No Notice of Change of Address and Phone was generated:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/aae794c6-5b7d-4af4-8b25-e5f12e8ebc78)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
Blocked by issue in bug ustaxcourt/ef-cms#7915 - can pick up when that is resolved

**Comment by mmarcotte** [comment]
<img width="1789" alt="Screen Shot 2021-06-21 at 3 45 33 PM" src="https://user-images.githubusercontent.com/5023502/122818908-c025b480-d2a7-11eb-9bd7-e8fd46e55d30.png">

Getting the spinning screen and no JS errors in `test`.

**Comment by rachaelparris** [comment]
This is happening on `test` for that particular user (bar number `EA0154`, userId `68928744-8f8b-4b49-8b1c-d7ca90252b6e`) because the Cognito user associated with that email address does not exist on `test`. I manually removed the email from Dynamo so it doesn't try a Cognito lookup, and I'm now able to edit the practitioner user.

**Comment by mmarcotte** [comment]
right on, that must be it. I will test again with that in mind.
