### ISSUE TITLE
BUG: Wrapping on order generator is off

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7919]
**Describe the Bug**
When copying/pasting from Word to the order generator, the text wrapping is not being retained.

NOTE: Similar issue in https://github.com/flexion/ef-cms/issues/8178 (ask @matthopson) 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod; able to reproduce in test

**Who were you logged in as?**
Internal user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to any case
2. Create an order
3. Copy and paste text from Word into the order generator
4. Note that the text doesn't wrap correctly

**Expected Behavior**
Copy and pasted text from Word will wrap

**Actual Behavior**
Copy and pasted text from Word is not wrapping

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/b12e4639-c360-4d0a-a996-d893fdb74fd9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
Food for thought: https://www.tiny.cloud/tinymce/features/powerpaste/

**Comment by matthopson** [comment]
So it looks like the original fix for this was reverted in this PR: https://github.com/flexion/ef-cms/pull/8268

**Comment by rachaelparris** [comment]
Reverting the revert PR ustaxcourt/ef-cms-flexion#8268 reproduces the bug that PR was created to resolve - the editor disappears after typing a single character. That bug never made it to prod because @rachelschneiderman caught it before it made it there. `preserveWhitespace={true}` is on the live code, too. I'll look for a few more things to try, but it seems like changing to `preserveWhitespace={!!editorDelta}` is not an option.

**Comment by rachaelparris** [comment]
For future reference, the "official" fix at this point is to remove the `preserveWhitespace` option completely from the Quill editor. Somehow in multiple bug fixes and reverts, that option ended up back in the code with this past deploy. There isn't a way to test copy and pasting from Word, so the history will have to suffice.

**Comment by matthopson** [comment]
I was just summed via email. Good to see some old faces / names :)

**Comment by kkoskelin** [comment]
@matthopson ![](https://y.yarn.co/8a5e585c-730c-4667-a6a3-b017e4934035_text.gif)
