### ISSUE TITLE
SPIKE - User Research - Current Order search experience

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7920]
## Acceptance Criteria
* Document usability issues with the current Order search experience 
   - Order find-ability 
   - UI interactions 
   - Expected vs. actual results

Feedback from users to be collected in Mural: https://app.mural.co/invitation/mural/flexion6734/1624030866039?sender=uac81c807303039588f330143&key=824d6200-f786-4ca7-80f1-a0f1a50a407a

* All feedback was gathered during week of 6/21/2021 using court's DEV environment.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
#### Issue 1
**From user** 

I searched for ESI.  Now that might look like an odd search, but I wrote two orders on the subject of electronically stored information, and throughout the order, I referred to it as ESI. 

In my view, this was a very narrow search.  There are many, many orders (and many of mine) that refer to electronically stored information.  As I understand the current logic (and as demonstrated by some of my other searches), if I had searched for “electronically stored information” it would have returned anything with those words, regardless of whether they were used together in a phrase or separated.  For example, it would have returned an order with the sentence “petitioners electronically searched for information stored on its system.”  So my thinking was that if I searched for ESI, it would only bring up the two orders in which I used that term.

 
Instead, it returned a multitude of off-topic orders.  For example, the search returned any order that had the word design (or any variation of that word, designated, designation, etc.).  Obviously, the results would not be helpful in a real world search.


We either need to truncate a search so that it only searches for whole words or we need a way to cause it to do that.

**Comment by klohman** [comment]
**From user feedback**

* The library, daily, has to identify orders/opinions/dockets that are mentioned in the news.  Some days we are trying to identify the “perfect” order that a judge told his/her law clerk to find.  If it is an opinion, we use other online resources (Bloomberg, Lexis and Westlaw, for example).   Orders can be a bit harder to identify if we are limited in the information we are given.   Basic Boolean searching would be very helpful.

* When I am searching for an order, why do I have to search by keyword first and then modify by name of petitioner, for example?  Can we have more search flexibility on orders?  If use the incorrect keyword at the start, the only place the results are going is downhill.   If I know there was a recent order reported in the news about petitioner John Smith, but that is all I know, searching orders may be tough.  (A John Smith cases search shows a 2013 case at the top and opinions has the same default as orders.) Not usually helpful when we are dealing with some articles/newspapers that are vague in their reporting.   Even vague articles are important to report to the Court.

* When I searched for “cannabis” in orders:
I see a “load more” rather than a count of the number of documents retrieved.  It usually helps a user and decreases frustration if they know how many more times they are going to see “load more”.
Some of the orders have “cannabis” in the petitioner’s name.  In others it will take more viewing to see their relevance or a control f.  Can we highlight the search term?
Is there a way to make the judge column sortable?  If I wanted to know which judge had the most cannabis orders, I can do it in a click.
I am seeing no explanation of whether you can use Boolean on this search screen or not.  I would put some language on top of the search box.  “Cannabis” produces 30 orders.  “ Cannabis or marijuana” produces 2.   “Cannabis or marijuana or weed” produces zero.

* Most databases want a search phrase surrounded by quotes.  If I enter “innocent spouse” in orders I get an error message.  Maybe something that indicates not to use quotation marks.  Innocent spouse without quotes produces results.

**Comment by klohman** [comment]
There doesn’t appear to be a way to search Dawson by opinion cite.  Is that something that will be added later?  What is someone supposed to do if they want to search for an opinion by cite or party name but doesn’t know the topic (since party name is a narrowing option only at this point)? 
I tried searching for citations as a keyword and it didn’t work well.  Sometimes I could find the opinion it if I dug deep in the results list and sometimes I’d get zero results.  This is true for both TC opinions and TC Memos.  I tried with and without quotation marks.  I did not get the error message when using quotation marks that Nancy received.  I got results they just weren’t useful results. 
To give you examples try searching for TC Memo 2020-1 (you get 3 results – none are TC Memo 2020-1 and none include that cite in the opinion).  If you just search 2020-1, I’m stopped at 100 results and none are TC Memo 2020-1.  Ideally if I search for TC Memo 2020-1 as a cite, I should only pull one document.  If I search 2020-1 as a cite, I’d expect at most 2 opinions (the TC Memo and the TC Summary)
I tried searching for 156 T.C. No. 11 – quotation marks or not I got the same results – 3 results – none of which are 156 TC No. 11.
I also get different results if I search for tc memo 2020-1 vs t.c. memo. 2020-1 (I’m assuming searching Dawson isn’t case sensitive.)
If I run a search and narrow the results, are the narrowing filters only being applied to the 100 documents pulled in my original search or is the system going back to everything in Dawson and running the search as a new search?
 

When you open a document in your results list, there is no way to go back to the results list.  Once the pdf is open if you click on the browser back button you’re taking back to the default case search page and your search strategy and results list are gone.  If this is a quirk that will exist in only in the test environment then that’s not a big deal, but if it’s going to be the same in the live environment that’s not ideal.
 

There is a bench opinion option on the opinions tab.  Will they also be searchable via the Orders search?  Unlike the other 3 types of opinions, bench opinions are generally not picked up by the paid services so Dawson will be the main access point for bench opinions.  If bench opinions can be pulled in both places great, if not we’re forcing people to run duplicate searches. 
Is there a way to search orders and opinions at the same time?  Maybe using check boxes where the default is all orders and opinions but the user can select whatever types of documents they want (orders and bench opinions or TC & Memo etc.).
 

If a case is sealed because a specific document is sealed will the orders and opinions that aren’t sealed be available through this search or are they still off limits for now?  I tried to find the Estate of Michael Jackson opinion and couldn’t pull it up – I know that case is currently sealed for everyone except Tax Court employees (and I wasn’t signed in if that’s even an option in the test environment.).  But since the opinion was made public in the Today’s Opinion page when it was published, I was hopeful I could find it.
 

How precise does a user have to be when using the party name field?  Do I have to use the full name or can I use just the last name for example?  I tried to search for Estate of Jackson and got zero results. Do I have to use the full name and what do I do if I don’t know it (especially middle names/initials)?  I tried this with a different estate case that isn’t sealed and couldn’t find it either (I usually only know Estate of [last name]).  In other services I’d probably search estate /5 [last name] in the case name/title field to find the opinion.
 

I agree with Nancy that Boolean searching would be very helpful.  Not just AND, OR, and BUT NOT but also within a certain number so “innocent spouse” /10 cannibals
 

If I’m narrowing a search by docket number or party name does that just narrow the top 100 hits or does it rerun the search and then narrow by docket number/party name?  If my document wasn’t in the first 100 hits how am I ever going to find it?
 

Lastly and this might be a question for Jessica – how are the parallel citations for TC opinions going to be handled?  This was a problem in Blackstone as well.  Hopefully it will be easier in Dawson.  I mentioned this problem to some of your colleagues (Corey and Kristen) when Nancy and I met with them earlier this year.

**Comment by klohman** [comment]
Devs to investigate

* Search for ESI returned off-topic orders without keyword 

* Search for Cannabis produces 30 orders. “ Cannabis or marijuana” produces 2. “Cannabis or marijuana or weed” produces zero.

*  If I enter “innocent spouse” in orders I get an error message. Maybe something that indicates not to use quotation marks. Innocent spouse without quotes produces results.

* I tried searching for citations as a keyword and it didn’t work well. Sometimes I could find the opinion it if I dug deep in the results list and sometimes I’d get zero results. This is true for both TC opinions and TC Memos. I tried with and without quotation marks. I did not get the error message when using quotation marks that Nancy received. I got results they just weren’t useful results. 
    * To give you examples try searching for TC Memo 2020-1 (you get 3 results – none are TC Memo 2020-1 and none include that cite in the opinion). If you just search 2020-1, I’m stopped at 100 results and none are TC Memo 2020-1. Ideally if I search for TC Memo 2020-1 as a cite, I should only pull one document. If I search 2020-1 as a cite, I’d expect at most 2 opinions (the TC Memo and the TC Summary) 
    * I tried searching for 156 T.C. No. 11 – quotation marks or not I got the same results – 3 results – none of which are 156 TC No. 11.
    * I also get different results if I search for tc memo 2020-1 vs t.c. memo. 2020-1 (I’m assuming searching Dawson isn’t case sensitive.)

* If I run a search and narrow the results, are the narrowing filters only being applied to the 100 documents pulled in my original search or is the system going back to everything in Dawson and running the search as a new search?


* How precise does a user have to be when using the party name field? Do I have to use the full name or can I use just the last name for example? I tried to search for Estate of Jackson and got zero results. Do I have to use the full name and what do I do if I don’t know it (especially middle names/initials)? I tried this with a different estate case that isn’t sealed and couldn’t find it either (I usually only know Estate of [last name]). In other services I’d probably search estate /5 [last name] in the case name/title field to find the opinion.

* If I’m narrowing a search by docket number or party name does that just narrow the top 100 hits or does it rerun the search and then narrow by docket number/party name? If my document wasn’t in the first 100 hits how am I ever going to find it?

* So I tried the key word “the” with the petitioner name “Govea”. It responds with “No matches found”. But if I search for “Phipps” with case name Govea, I get hits. If I open one of those orders, the word “the” is there. (This is likely because the word "the" is ignored when searching - need to confirm)

* Searching LITC (Low income taxpayer clinic) The search yielded 12 orders generally under all judges (no specific judge selected).  But it did not contain anything older than 2012. Expected see older Orders

**Comment by kkoskelin** [comment]
My answers are shown in blockquotes below. -- Kris
---
Devs to investigate

1. Search for ESI returned off-topic orders without keyword
  > I would very much like to identify a docket entry that I can inspect which would have been expected to show in results. 

2. Search for Cannabis produces 30 orders. “ Cannabis or marijuana” produces 2. “Cannabis or marijuana or weed” produces zero.
  > advanced syntax (i.e. using 'OR') is currently unsupported.  As a result, the query discards "or" (regarded as a "stop word" like articles and conjunctions) and looks for documents which match all three terms "cannabis", "marijuana", and "weed".

3.  If I enter “innocent spouse” in orders I get an error message. Maybe something that indicates not to use quotation marks. Innocent spouse without quotes produces results.
  > the current search will have stripped any quotation marks from your query and both should have performed identically.  It is possible that the initial search produced an error as a result of our elasticsearch cluster being under heavy load.  I was able to perform this query both with and without quotation marks.

4. I tried searching for citations as a keyword and it didn’t work well. Sometimes I could find the opinion it if I dug deep in the results list and sometimes I’d get zero results. This is true for both TC opinions and TC Memos. I tried with and without quotation marks. I did not get the error message when using quotation marks that Nancy received. I got results they just weren’t useful results. 
    * To give you examples try searching for TC Memo 2020-1 (you get 3 results – none are TC Memo 2020-1 and none include that cite in the opinion). If you just search 2020-1, I’m stopped at 100 results and none are TC Memo 2020-1. Ideally if I search for TC Memo 2020-1 as a cite, I should only pull one document. If I search 2020-1 as a cite, I’d expect at most 2 opinions (the TC Memo and the TC Summary) 
      > It does appear that sometimes documents say "T.C. Memo", sometimes "TC. Memo".  Additionally, because the current order search supports neither advanced syntax nor exact-phrase matching, the dash in "2020-1" is removed, and your query would attempt to match documents which contain all of the following: "TC", "Memo", "2021", "1" (the latter may be discarded, unsure).
    * I tried searching for 156 T.C. No. 11 – quotation marks or not I got the same results – 3 results – none of which are 156 TC No.
      >  Since exact-phrase search is currently unsupported, this query would have been split on space-characters and the best matching documents would be those which contain as many of the following as possible:"156", "t.c.", "no.", "11"
11.
    * I also get different results if I search for tc memo 2020-1 vs t.c. memo. 2020-1 (I’m assuming searching Dawson isn’t case sensitive.)
      > The string "tc" is indeed distinct from "t.c.".  Each search will respectively return documents which match the terms provided. Some contain "TC", but it seems perhaps "T.C." is more common.  If it is extremely important to treat these two strings as equivalent for both indexing and searching, we will need to investigate whether a transform can be written to accomplish this.

5. If I run a search and narrow the results, are the narrowing filters only being applied to the 100 documents pulled in my original search or is the system going back to everything in Dawson and running the search as a new search?
    > The entire search is being executed a second time using the filter information, after which time the search results are "capped" at 100 before being returned.  It is entirely possible that upon "narrowing" your search, you may still get 100 documents, many of which did not appear in your initial search results.

6. How precise does a user have to be when using the party name field? Do I have to use the full name or can I use just the last name for example? I tried to search for Estate of Jackson and got zero results. Do I have to use the full name and what do I do if I don’t know it (especially middle names/initials)? I tried this with a different estate case that isn’t sealed and couldn’t find it either (I usually only know Estate of [last name]). In other services I’d probably search estate /5 [last name] in the case name/title field to find the opinion.
    > Presuming we are talking about the field labeled "Case title / Petitioner's name" here -- what was in the keyword field in your query?  The current syntax for searching on case title or petitioner name follows the same as keyword searches at the moment: it takes your query and searches for items which contain all keywords (where "of" is discarded) like "estate", "Jackson"

7. If I’m narrowing a search by docket number or party name does that just narrow the top 100 hits or does it rerun the search and then narrow by docket number/party name? If my document wasn’t in the first 100 hits how am I ever going to find it?  
    > Please see the answer to (5) above.  Providing additional search terms will improve the accuracy of your search, the scope of which goes beyond the first 100 documents.

8. So I tried the key word “the” with the petitioner name “Govea”. It responds with “No matches found”. But if I search for “Phipps” with case name Govea, I get hits. If I open one of those orders, the word “the” is there. (This is likely because the word "the" is ignored when searching - need to confirm)
    > correct, "the" is a stop-word (see also answer to (2)).  It is likely that by providing *only* a stop-word in the keyword field that the search engine simply gives up.  If we believe that there is a use-case for allowing users to search for orders or documents by providing the "narrow your search" inputs but without any keyword/phrase, this could be accomplished.

9. Searching LITC (Low income taxpayer clinic) The search yielded 12 orders generally under all judges (no specific judge selected).  But it did not contain anything older than 2012. Expected see older Orders 
    > When I performed this search, I searched for "LITC" in the keyword/phrase field, and provided start date of 06/03/1992 and end date of 06/29/2013.  I received four results, one of which was from 2010.  Is it possible this term is being indexed as "L.I.T.C."?  Can you provide alternative keywords to search for that will guide me to a document which contains "LITC" but doesn't turn up in search results?

**Comment by klohman** [comment]
## Findings 

* Users need flexibility in their search criteria. Requiring keyword search limits their ability to perform all the queries they need, and forces them to use workarounds that can be problematic. The ability to search by keyword, judge or date range would allow users to more easily get to the information they are looking for, without entering unwanted search terms. 

* Users expect some Boolean search functionality and instructions on what is and isn’t supported when searching in our application. They were confused by the result sets returned when using Boolean terms and were unaware that it was not supported due to poor in-app messaging. Long term, Boolean search would be essential for users to trust and use Dawson search.

* Although not all searches were intended to retrieve exact matches (i.e. those using some Boolean connectors), users expected the use of quotes to provide them with matches of the exact term or phrase. This is the familiar behavior of most other databases and result sets confused users. 

* Searching by citation number does not provide users with consistent, accurate results. Some users stopped testing search early because of this. Long term, users need a way to easily search for documents by citation.  

* Users have a variety of use cases for searching documents in Dawson. The current scoped search separating Orders and Opinions limits them to what they can retrieve in one search, and requires two separate search inputs and queries. This was frustrating to users who are looking for more broad information.

* Users are not clear of some search functionality in the current UI. When using the options to “Narrow your results” they were unsure if the new search was filtering the current result set, or performing another search. It is unclear both from an instructional perspective and from the result set. From technical review: The entire search is being executed a second time using the filter information, after which time the search results are "capped" at 100 before being returned. It is entirely possible that upon "narrowing" your search, you may still get 100 documents, many of which did not appear in your initial search results.

* Users were very frustrated by the link behavior of the document results. When clicking to view any document, the PDF opens in the current tab and the result set and search criteria are lost. Users need a way to quickly preview and assess documents and easily navigate their current result set without interruption. 

* Users expect to see the total number of results from their search, and there was some frustration at the results being capped at 100. Users need more feedback from the system to understand their results quickly. 

* Users need more flexibility in manipulating their result sets. Advanced controls like sort (judge, date) would benefit users who know exactly what they are looking for in the system. 

* Users can pretty easily tell if they are retrieving relevant documents or not, but it requires effort on their part to individually view any document that doesn’t have the search criteria in the document title. They need a better way to know how relevant a result is to their criteria. We need to understand what datapoint is best to provide them that confidence, whether it’s a keyword match count, quick document preview, ES ranking score, etc.

## Recommendations 
* Fix high priority usability issues 
    * Update document link behavior - at minimum, open in new tab 
    * Display total result count; reconsider how to handle over 100 results 
    * Add more descriptive instructions on what search syntax is/is not supported 

* Add prioritized user stories for new features to backlog 
   * Exact match 
   * Basic boolean search 
   * Search result navigation and modification

*Continue research with users
  * Collect search usage metrics 
       * Most popular search terms 
       * Success rate of searches (large number of hits, no result searches, etc)
 * Collect user feedback
    * Validate new features (exact match, boolean operators, search navigation)
    * Validate if OCR and exact match updates improve citation search 


## Proposed User Stories (High Priority New Features)

**As a Court employee, in order to locate documents with specific keywords, I need to be able to retrieve documents with only those exact keyword/phrases.** ustaxcourt/ef-cms-flexion#8645
    * Acceptance Criteria 
        * User is aware that they can search for exact matches 
        * User is able to indicate if they want an exact match 
        * User is able to search for an exact match on a single keyword 
        * User is able to search for an exact match on a phrase 
        * When exact match is indicated by user, the result set includes only matches that include the exact keyword/phrase  
	

**As a Court employee, in order to locate the most relevant documents, I need to have more control over how my keyword search is executed.** ustaxcourt/ef-cms#7951
    * Acceptance Criteria 
        * User is aware that they can search using basic (AND, OR, NOT) boolean connectors 
        * User is able to search using boolean operator “AND” and retrieve results containing both keywords 
        * User is able to search using boolean operator “OR” and retrieve results containing either keyword
        * User is able to search using boolean operator “NOT” and retrieve results excluding the specified keywords

**As a Court employee, in order to locate relevant documents more quickly,  I need a way to navigate search results and assess their relevancy.** ustaxcourt/ef-cms-flexion#8548
    * Acceptance Criteria 
        * User can easily preview documents from their search results 
        * Search criteria and result set is retained until the user indicates they want to clear or start a new search 
        

**As a Court employee, in order to locate relevant documents more quickly,  I need a way to modify search results and prioritize what’s most important.** ustaxcourt/ef-cms#7953
* Acceptance Criteria
           * User can sort their search results  
                   * Date
           * User can eliminate results within a returned set via filtering


## Long-Term Considerations
* More advanced search options 
    * Proximity search 
* More flexibility in search criteria 
    * Search by any criteria (keyword, judge, or date)
    * Search across document types (Orders + Opinions) 
    * Citation search
