### ISSUE TITLE
BUG: Records not reliably getting indexed into Elasticsearch

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7925]
**Former Title**

BUG: Attorney not returning in name search

**Describe the Bug**
When an Admissions Clerk searched for Thomas Michael Affeldt (AT0018) by name, no results returned.  They were able to find him by bar number.

Additionally Open/Closed cases are coming up empty in dashboards for some practitioners.

When doing a compare with the `test` environment, we observed more cases existing in `test` than in `prod`, even though it's based off of the same DDB information:

```
efcms-search-test-beta
{
  count: 988471,
  _shards: { total: 1, successful: 1, skipped: 0, failed: 0 }
}
efcms-search-prod-beta
{
  count: 976163,
  _shards: { total: 1, successful: 1, skipped: 0, failed: 0 }
}
```

When looking at some of the case records in Prod that are missing, their `aws:rep:updatetime` timestamp is from when the last blue/green migration occurred (1624148859.003002). This must be when the record was not indexed.

**Business Impact/Reason for Severity**

Cases, Practitioners, UserCases cannot go missing.

**In which environment did you see this bug?**

Prod; was **not** able to reproduce on `mig`

**Who were you logged in as?**

Admissions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to Practitioner Search
2. Performing a practitioner name search for `Affeldt` or `Thomas Michael Affeldt`
3. Note that Thomas Michael Affeldt (AT0018) does not return in the results

**Expected Behavior**
Thomas Michael Affeldt (AT0018) would be in the result when performing a practitioner name search for `Affeldt` or `Thomas Michael Affeldt`

**Actual Behavior**
Thomas Michael Affeldt (AT0018) is NOT in the result when performing a practitioner name search for `Affeldt` or `Thomas Michael Affeldt`

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/f976569f-14f2-4e90-bd94-a17af1053c21)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rachaelparris** [comment]
Waiting for more info, cannot currently reproduce the issue. Moving back to bug column for now.

**Comment by mmarcotte** [comment]
Upon updating the record in DDB, the record was re-indexed and is now findable via Practitioner Search. 

🤔 hmm, so what happened? there must be others in this state. Does the lookup by Bar Number use DDB and bypass ES and that's why that search worked?

**Comment by rachaelparris** [comment]
@mmarcotte Yep, the lookup by bar number performs a Dynamo query instead of using ES and that's why it worked.

**Comment by matthopson** [comment]
I've seen this crop up on exp and dev. Smoketests will fail on searching by name (but will pass via bar number). I can manually update the record in the UI and re-run the smoketests and they will pass.

**Comment by mmarcotte** [comment]
Blocked by https://github.com/flexion/ef-cms/issues/8536
