### ISSUE TITLE
Automate triggering of Blue/Green Migration

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7928]
## Pre-Conditions

- Review spike: https://github.com/flexion/ef-cms/issues/8073

## Acceptance Criteria

- As a Developer deploying to any environment, so that I can remove human error out of the equation, automate the steps for triggering a blue/green migration
  - setting the destination table in dynamodb
  - setting the migrate flag to true
  - ensuring that destination resources don't exist; (deleting them could be manual for now, but [this story here](https://github.com/flexion/ef-cms/issues/8507) automates that process)
    - destination DDB tables (east & west)
    - destination ES cluster or index
- As a developer deploying to any environment, so that I understand the updated deployment process, I need the blue-green-migration.md document to be up to date with the latest changes made by this adjustment.

## Mobile Design/Considerations

None

## IRS API Considerations

None

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

- Just an idea: trigger if PR that gets merged has a label of `Blue/Green Migration`

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by codyseibert** [comment]
I think to implement an effective solution, we need to first work on ustaxcourt/ef-cms#7933
