### ISSUE TITLE
Add Read-Only Smoketests for Production

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7931]
## Pre-Conditions

- Review spike: https://github.com/flexion/ef-cms/issues/8073
 - ustaxcourt/ef-cms#7930

## Acceptance Criteria

- As a Tech Lead, so that I can have added assurance that a deployment was successful, have a smoketest that performs read-only operations on DAWSON
  - hits all frontend public UI
  - logs in as a general user and is presented with the user's dashboard
- As a Tech Lead, so that I know my system is secure, disable any Cognito used to perform these smoketests after the smoketest is complete (whether it fails or succeeds)
- As a developer deploying to any environment, so that I understand the updated deployment process, I need the `blue-green-migration.md` document to be up to date with the latest changes made by this adjustment.
- Solution  tested in Flexion PROD environment for most accurate quality assurance

## Mobile Design/Considerations

None

## IRS API Considerations

None

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
@mmarcotte let's work together and backlog a story with the inventory of pages/cases we want a general user to be able to navigate to in these tests on production. Changed the AC for now to verify that the user is presented with their dashboard as confirmation that they're in the system upon login.

**Comment by mariahkannenberg** [comment]
Everything passed in prod successfully. Ready for acceptance, unless feedback.
