### ISSUE TITLE
BUG: uploaded PDF documents are not normalized to standard document width

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7939]
**Describe the Bug**

When you go to apply a signature to a proposed stip decision, the document is zoomed in (perhaps scanned in at higher resolution). It makes it impossible to apply the signature.

**Business Impact/Reason for Severity**

Judges need to apply their signature reliably

**In which environment did you see this bug?**

Prod, Test

**Who were you logged in as?**

Judge Gustafson

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Helpdesk

**To Reproduce**

1. Become user Judge/Gustafson
2. Navigate to case 9746-20
3. Navigate to Drafts
4. Attempt to Apply Signature to the Proposed decision
5. See issue where the document is zoomed in

**Expected Behavior**

The document should be normal size and conform to the window.

**Actual Behavior**

The document is overly zoomed in

**Screenshots**

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
The attached file has pages with width of 2400px, which far exceeds the width of coversheets (866px).  Use this attached file to see behavior related to adding coversheets and signatures (as a docket clerk) for a stipulated decision from a paper filing.
[big-stip-dec.pdf](https://github.com/flexion/ef-cms/files/6756500/big-stip-dec.pdf)

**Comment by mariahkannenberg** [comment]
Converted to story ustaxcourt/ef-cms#7959
