### ISSUE TITLE
SPIKE: Assist with documentation of decision to use DynamoDB

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7941]
As a tech lead, so that I can understand the decision to use DynamoDB, I need to discuss and document the decision.

## Pre-Conditions

- [ ] A quorum of folks present who were present when the decision to use DynamoDB was made.

## Acceptance Criteria

- [ ] Compile any and all thoughts to help document the decision to use DynamoDB as a data store. 
- [ ] Timebox: 45min. 

## Notes

We're documenting [over here](https://github.com/ustaxcourt/ef-cms/pull/1377) at the moment. So we could just add and revise that. @mmarcotte would be happy to be note taker.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Flexion to provide feedback on final notes from Kris and Matt.

**Comment by mariahkannenberg** [comment]
Court to merge. Will add more if needed.

**Comment by mmarcotte** [comment]
Completed with https://github.com/ustaxcourt/ef-cms/pull/1377
