### ISSUE TITLE
BUG: In-Browser scanning has stopped working for Clerks

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7943]
**Describe the Bug**

After deploying batch 1, Docket and Petitions clerks reported that scanning stopped working for them. They simply get the spinning wheel.

While attempting to replicate the issue, I was able to observe a Content Security Policy error complaining about:

```
Refused to create a worker from 'data:text/javascript;base64,...s=' because it violates the following Content Security Policy directive: "worker-src blob:".
```

Made this attempt to resolve that CSP error, but other errors persisted. It appears that it could be related to a major upgrade that batch 1 introduced for image-blog-reduce.

**Business Impact/Reason for Severity**

It saves time to scan directly in via the browser

**In which environment did you see this bug?**

Prod, then any

**Who were you logged in as?**

Docket, Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Reported by Clerks

**To Reproduce**

1. Login, and navigate to a page where you would scan a document
2. Attempt to scan
3. Get spinning interstitial page
4. See error in the console

**Expected Behavior**

Scanning works as it had before the update

**Actual Behavior**

Spinning interstitial page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Edge, Chrome
 - latest

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
Eliminating the CSP issue (caused by an upgrade of image-reduce-blob) was not the solution to fixing the scanning situation.  It appears right now that some kind of webpack-related issue may be to blame. More notes to follow.
