### ISSUE TITLE
BUG: Indexing starts prematurely on Blue/Green Deploy

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7944]
**Describe the Bug**

While doing a recent blue/green deploy to production, I noticed that ~2,000 documents had been indexed into Elasticsearch while the migration was still happening. How could this have happened? We disable the trigger in the step before we initiate the migration. 

The step before is supposed to disable the trigger, and that did happen. However, the migration may have started before it was fully disabled.

It would seem that there is a transitional state of `Disabling` before the state is `Disabled`. 

**Business Impact/Reason for Severity**

Indexed items prematurely may rely on other information when they get indexed.

**In which environment did you see this bug?**

Prod

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Deploying

**To Reproduce**
1. Initiate a Blue/Green migration
2. Cancel the migration before you re-enable the Lambda trigger
3. Observe that some items got indexed anyways

**Expected Behavior**

Items shouldn't be indexed into Elasticsearch until after the Migration completes

**Actual Behavior**

Items were indexed into Elasticsearch before the Migration completed

**Screenshots**

<img width="1382" alt="Screen Shot 2021-06-30 at 11 42 38 PM" src="https://user-images.githubusercontent.com/5023502/124062629-0644eb80-d9ff-11eb-8954-a89c2a6bec74.png">
<img width="1789" alt="Screen Shot 2021-06-30 at 11 28 30 PM" src="https://user-images.githubusercontent.com/5023502/124062631-0644eb80-d9ff-11eb-889d-4acd5c0faa1d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
In the script `web-api/disable-deploying-dynamo-stream-trigger.sh` should there be a "sleep" statement of 30-90 seconds (more?) after the disabling?  To ensure all triggers that were queued are complete?
Is there another way to determine if there are triggers already queued which we must wait for?
This script makes a change for `--region us-east-1` -- is this the only region in which the stream trigger operates?

**Comment by mrinsin** [comment]
We ended up adding a 1 minute long sleep to the script that disabled the deploying stream and that seemed to fix the issue on `experimental3`. We explored other theories as to why this was happening but were unable to prove those theories to be true.

**Comment by mmarcotte** [comment]
This still occurred during tonight's deploy. Scratching my head for how it happened. It appeared to pick up events right as the migration was starting. I'm going to reach out to AWS support to get a better understanding for how this could happen even as the report says the Trigger was disabled.

Deploying Color Streams Lambda (you'll notice the indexing event right at 2:11 UTC)
<img width="1789" alt="Screen Shot 2021-07-10 at 10 35 40 PM" src="https://user-images.githubusercontent.com/5023502/125181082-70b01580-e1cf-11eb-8c4c-45a3b0f0a960.png">

Migration Lambda (started at 2:11 UTC)
<img width="1789" alt="Screen Shot 2021-07-10 at 10 35 27 PM" src="https://user-images.githubusercontent.com/5023502/125181083-7148ac00-e1cf-11eb-9d3b-211be569a7e9.png">

The deploy step with the Disabled report:
<img width="1789" alt="Screen Shot 2021-07-10 at 10 35 08 PM" src="https://user-images.githubusercontent.com/5023502/125181084-7148ac00-e1cf-11eb-8748-203981a95636.png">

**Comment by mariahkannenberg** [comment]
Hold on this one until Mike hears back from AWS.

**Comment by mmarcotte** [comment]
This occurred again on a deploy to `test` on Friday July 16th. Here are some observations:

First the trigger was disabled:

* Event Time: 2021-07-16T04:42:07Z
* CloudTrail EventID: 6fdf7252-2c75-4102-a61a-21862e60fbef

Circle reports this response back in the response from disabling the trigger:

* "LastModified": "2021-07-16T04:42:07.100000+00:00",

So those match up. Now observing the lambda's activity, it starts after this time. and continues for 23 seconds:

- 2021-07-16T00:42:37.481-04:00 through
- 2021-07-16T00:43:00.464-04:00

**Comment by matthopson** [comment]
@mmarcotte Just wanted to check back on this and see if we've heard anything from AWS?

**Comment by mariahkannenberg** [comment]
Trim horizon fixed. Moving to tech review

**Comment by mmarcotte** [comment]
https://github.com/flexion/ef-cms/pull/8673 this solved it!
