### ISSUE TITLE
BUG: Alignment of "links" in public view of case is off

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7946]
**Describe the Bug**

In the list of documents for a public case, the alignment is off. The words in the row with the SPTO should all be on the same line.

<img width="1969" alt="Screen Shot 2021-07-01 at 2 47 17 AM" src="https://user-images.githubusercontent.com/5023502/124079168-d0abfc80-da16-11eb-96d6-371190b42eb1.png">

**Business Impact/Reason for Severity**

Not a clean interface

**In which environment did you see this bug?**

Prod

**Who were you logged in as?**

Not logged in

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Testing

**To Reproduce**

1. Go to https://dawson.ustaxcourt.gov/case-detail/14703-19
2. See error

**Expected Behavior**

The items in the same row should be on the same line

**Actual Behavior**

The link to the document is not on the same line horizontally.

**Screenshots**

**Desktop (please complete the following information):**
Mac, Chrome

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by matthopson** [comment]
PR https://github.com/ustaxcourt/ef-cms/pull/1447
