### ISSUE TITLE
Search - Logging Order Search User Data v1

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7949]
As a development team, so that we may understand how users are utilizing Order search, I would like to collect data from user input.

## Acceptance Criteria

Data to capture for each query:
- search terms used
- filters selected
- logged in role
- number of results returned
- time of query

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- Reporting will be handled in a separate story.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
@mariahkannenberg Added more specific metrics; this is more of a comprehensive list than what we actually need to go live internally, so I'd like to discuss with dev to see if there are logical groupings here that make sense to split out into different stories and narrow down what we actually think is most feasible/important for go-live.

**Comment by matthopson** [comment]
@cholly75 @mmarcotte  I don't want to prescribe a solution here as the team may have some better ideas - but Google Analytics / custom events feels like a great option to explore with this. What is the likelihood that it could be considered?

**Comment by cholly75** [comment]
@matthopson @mmarcotte I think we can at least consider it; I'd like to understand a few things around how to implement it, what sort of costs may be associated with it (as I understand it, there's a free version and a not-so-free version), care and feeding, etc. I will check with the CIO to see if there's anything he's aware of that might specifically proscribe against it.

**Comment by klohman** [comment]
@cholly75 Another tool we may be able to utilize is [Hotjar](https://www.hotjar.com/). There is a free option if we wanted to test it out. They can provide heatmaps (which I believe is also possible though Google analytics) but they also can provide actual recordings of user sessions. I've used this tool in the past and it can really provide a starting point for deeper user research.

**Comment by cholly75** [comment]
Thanks @klohman ! 

I'm also wondering if Elastic Search has any OOB metrics/reporting that we can/should pair with a solution like GA or hotjar to get a comprehensive picture?
