### ISSUE TITLE
Order Search: AND keyword search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7951]
As a Court employee, in order to locate the most relevant documents, I need to have more control over how my  keyword search is executed.

## Acceptance Criteria
* User is able to search using multiple keywords/phrases using the equivalent of boolean operator “AND” and retrieve results containing BOTH keywords/phrases (including exact match) 
* When run on full data set, searches return expected results, do not return results outside of design scope; search remains performant

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Question for Engineers: How hard would it be to implement exact search AND operators in same search.  For example: "motion for summary judgment" and denied
* Don't need to support multiple boolean operators in a single search for now

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by kkoskelin** [comment]
Advanced syntax search documentation for engineers: ~~https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-query-string-query.html#query-string-syntax~~
After further review, would instead recommend the `simple_query_string` syntax that is extremely fault-tolerant: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#supported-flags

**Comment by kkoskelin** [comment]
https://github.com/flexion/ef-cms/issues/8546 contains the initial seeds that will support the requested boolean operators (and more)

I highly recommend that we encourage search-users to make use of the logic operators directly supported by the Elasticsearch tools (e.g. `-`, `+`, `|` and others) rather than attempt to provide support for the words `AND`, `OR`, `NOT`.  There lies the opportunity for MANY bugs and unnecessary development time and testing to create a "translation layer" with complicated parsing.

We may even wish to support search flags beyond those shown here, particularly `ESCAPE` (the ability to search for `Coca\-Cola`) and `PRECEDENCE` (search for `Pugh +(dismissal | judgment)`.

**Comment by klohman** [comment]
- Keyword AND keyword in document title and contents 
- Keyword AND keyword in document title only 
- Keyword AND keyword in contents only

- “Exact match Keyword phrase” AND keyword in document title and contents
- “Exact match Keyword phrase” AND keyword in document title only
- “Exact match Keyword phrase” AND keyword in document contents only 

- “Exact match Keyword phrase” AND “Exact match keyword phrase” in document title and contents
- “Exact match Keyword phrase” AND “Exact match keyword phrase” in document title only
- “Exact match Keyword phrase” AND “Exact match keyword phrase” in contents only 

- Keyword phrase AND “Exact match keyword phrase” in document title and contents
- Keyword phrase AND “Exact match keyword phrase” in document title only
- Keyword phrase AND “Exact match keyword phrase” in contents only
