### ISSUE TITLE
Order Search: Add more descriptive instructions

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7956]
As a Court user, so that I may understand what types of searches are or are not supported, I need to be informed about what syntax is or isn't supported.

## Pre-Conditions
* 

## Acceptance Criteria
* Users are informed of what search syntax is/is not supported w/r/t fields
* If there are user requirements for special characters, the user is informed

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Consider whether to reject searches that have special characters. Perhaps we can use Joi to validate what is a valid search query.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Blocked - Hold until after usability testing

**Comment by klohman** [comment]
### Order Search with instructions 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/25677606-61a8-44df-bff7-224b50598e04)

#### Mobile 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3d41986c-76f6-4adb-9de7-6e0fef6e7e0b)

### Search Examples PDF 
* On click of link, PDF should open in new tab 

[https://app.zenhub.com/files/152320868/8eab2140-5d4f-43f5-9905-c5da6b68aa9a/download](https://app.zenhub.com/files/152320868/8eab2140-5d4f-43f5-9905-c5da6b68aa9a/download)

**Comment by cholly75** [comment]
@klohman In the instructional FAQ, do we want to mention a note about how the exact match will ignore special characters?

**Comment by ttlenard** [comment]
@klohman  I noticed that the FAQ we indicate that the pipe character means "OR", but in the UI, it doesn't explicitly say that.  Is this ok?

**Comment by klohman** [comment]
@TomElliottFlexion 

[https://app.zenhub.com/files/152320868/cb6c3396-b7c3-4fcb-af68-ec9e06437995/download](https://app.zenhub.com/files/152320868/cb6c3396-b7c3-4fcb-af68-ec9e06437995/download)

**Comment by cholly75** [comment]
Minor edit - can we add a blurb to the OR instructions on the "Searching for Documents in DAWSON" page to explicitly say the pipe character is located above the backslash key on the keyboard?

**Comment by klohman** [comment]
@TomElliottFlexion Updated PDF per PO comments is attached.

[https://app.zenhub.com/files/152320868/ffe41d15-6a44-4873-9f7f-e3534802acf7/download](https://app.zenhub.com/files/152320868/ffe41d15-6a44-4873-9f7f-e3534802acf7/download)

**Comment by ttlenard** [comment]
I have a few items for feedback.

General Question regarding the use of "Guy Fieri" and "Sam Fieri".  Are using these names of actual people in the help documents advisable for when this goes to the public?  Just wondering if we should use more generic names?  Maybe it doesn't matter though???

Found a misspelled word in the help doc: 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/92fee342-2bec-4e16-83de-580b2cfc5bd7)

I believe this should be "Documents"?
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/550c6022-80cb-48c5-8495-1ae7b2e59c7c)

**Comment by kkoskelin** [comment]
I am unable to make the requested changes at this time -- the changes are all needed within the how-to-use-search.pdf document and I do not have the source from which the PDF was generated. May need to wait for Tom or Kristen.
