### ISSUE TITLE
Usability Testing: Order Search Round #2

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7957]
As a development team, so that we may test the usability of search features before making them available to the public, we need to perform usability testing. 

## Pre-Conditions
* Order search is available in the Court's production environment (#8544)

## Acceptance Criteria
* All Court users can provide usability feedback 
* Targeted usability testing is performed with a small group of users in the Court's prod environment
* Results of the study are documented
* User stories from results are added to the backlog

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1e8876d5-9855-41ef-a954-4f50be426ec0)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/34597c13-a4b9-4451-9697-ed1abab433ae)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a34c1ba7-23b9-4546-b7de-c4bb541f7b5c)
