### ISSUE TITLE
BUG: Error 400 when trying to change Petitioner Type while creating a petition

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7961]
**Describe the Bug**

While creating a new petition, and editing the details to correct the Party information, was able to generate a 400 error. The response included the error message.

> Petitioner was not found on case 629-21.

This is when trying to change `Petitioner & spouse` to `Petitioner`

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

Prod/Any

**Who were you logged in as?**

Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Observing Petitions section

**To Reproduce**
1. Login as a Petitions Clerk
2. Start creating a petition, and do **Petitioner and Spouse** and get to the Review step
3. Edit the Parties information before serving the petition
4. Change to **Petitioner** from **Petitioner and Spouse**
5. Re-enter in Petitioner information
6. Click Review Petition and see Error

**Expected Behavior**

Petition changed to **Petitioner**

**Actual Behavior**

Error 400 with validation error

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by rosiehsmith** [comment]
It appears that this was fixed by ustaxcourt/ef-cms#7927 and it hadn't been merged at the point that this bug was logged.

**Comment by mmarcotte** [comment]
Hmm, I was just able to make this happen in our Staging environment, which has the latest and greatest.
