### ISSUE TITLE
BUG: Line through "Trial Session Planning Report" on Trial Sessions Page

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7962]
**Describe the Bug**

Simple UI alignment annoyance. The horizontal line to break up the content on the Trial Sessions page is going through the link for the Trial Session Planning Report. 

<img width="1462" alt="Screen Shot 2021-07-12 at 9 53 23 AM" src="https://user-images.githubusercontent.com/5023502/125299609-4d808580-e2f7-11eb-8d24-ab352df742c9.png">

**Business Impact/Reason for Severity**

Looks off

**In which environment did you see this bug?**

Prod

**Who were you logged in as?**

Anyone with Trial Sessions access

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Testing deployment

**To Reproduce**

1. Login as a user with Trial Sessions access
2. Click on Trial Sessions
3. See line through link

**Expected Behavior**

Design should probably weigh in, but the link should be above or below the line.

**Actual Behavior**

Line goes through the text.

**Screenshots**

<img width="1462" alt="Screen Shot 2021-07-12 at 9 53 23 AM" src="https://user-images.githubusercontent.com/5023502/125299609-4d808580-e2f7-11eb-8d24-ab352df742c9.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser Chrome
 - Version 91

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
https://github.com/ustaxcourt/ef-cms/pull/1478
