### ISSUE TITLE
BUG: Deadlines for Carluzzo showing up in filtered list for Chief Judge

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7964]
**Describe the Bug**
When filtering the deadlines report for "Chief Judge", there are deadlines for Judge Carluzzo showing up

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**
Internal User

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to deadlines report
2. Set date range for 7/1/2021 to 7/31/2021
3. Set Judge filter to "Chief Judge"
4. Note that there are deadlines for Judge Carluzzo in the filtered list

**Expected Behavior**
Only deadlines for cases with "Chief Judge" display when the list is filtered by "Chief Judge"

**Actual Behavior**
Deadlines for Judge Carluzzo's cases are displaying when list is filtered by "Chief Judge"

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/75fad474-593b-406e-85cc-6b5f8318ea13)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by mariahkannenberg** [comment]
Happening in production, but not Flexion envs. Need someone from the Court to help reproduce.

**Comment by kkoskelin** [comment]
The associated judge name is being searched with the term "Chief Judge", or else just the last name of the judge ("Carluzzo", "Toro", etc).  However, the strings stored on the case deadlines sometimes contain just the surname, but sometimes title.
![Screen Shot 2021-07-13 at 10 18 50 AM](https://user-images.githubusercontent.com/2445917/125480179-f81d34a6-d126-4fda-bcee-a1b1a40bf35d.png)
In the above search, we were filtering on the phrase "Chief Judge".  Both terms "chief" and "judge" were being found in the associated judge value of "Chief Special Trial Judge Carluzzo", hence, it was being returned.
I may have a way to work around this. But in the meantime, I wonder if there is something we can do to standardize the formatting of the associated judge strings on the case deadlines.  Even within the search results, sometimes they show "Judge Urda", but other times simply "Urda" (other examples below).
![Screen Shot 2021-07-13 at 10 20 40 AM](https://user-images.githubusercontent.com/2445917/125480556-c45a2743-13bf-487e-8ad8-b401df7b6cf4.png)

If we are able to land on an exact formatting of the associated judge value, we will also be able to create more accurate and efficient searches in the future.
