### ISSUE TITLE
BUG: 13133-21 is still showing as `New` even after Petition has been served

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7966]
**Describe the Bug**
13133-21 is still showing as `New` even after Petition has been served

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod (case hasn't been copied to mig yet)

**Who were you logged in as?**
Jessica Marine

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Issuing orders

**To Reproduce**
1. Go to 13133-21
2. Note that the Petition (docket entry 1) has been served on IRS but case status is still showing as `New`

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/0957ae5b-d873-4b33-901a-21a288034356)

**Expected Behavior**
Once the petition has been served, the case status automatically changes to `General Docket -- Not at Issue`

**Actual Behavior**
Case Status did not update to `General Docket -- Not at Issue` when petition was served
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/9d6d8899-2463-4cdb-b0dc-a6ddc1bd7fb7)
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/afd22121-328f-47c1-8005-5145bf069820)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
It's a mystery. No other API calls should have changed the status back to New. Changing its status from New to General is one of the first things serving the petition to the IRS does. So, something else afterwards in that process must have reverted that. It's not evident how. Should this happen again, we would want to compare the two requests.

Another tool that may help in troubleshooting would be some sort of a DB transaction audit log to observe the various PUT calls and identify the code that is making that call.
