### ISSUE TITLE
BUG: Case JSON has noticeOfTrialDate when no Notice of Trial has been issued

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7967]
**Describe the Bug**
Case JSON has noticeOfTrialDate when no Notice of Trial has been issued

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod; able to replicate in mig

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 12000-21 in `mig` (or any case)
2. Note that the case JSON reflects a noticeOfTrialDate of 6-22-2021 when no Notice of Trial has been issued on the case

**Expected Behavior**
* noticeOfTrialDate is populated on the case JSON only when a Notice of Trial has been issued
* If more than one Notice of Trial has been issued over the life-cycle of the case, the date of the latest Notice of Trial should display as noticeOfTrialDate 

**Actual Behavior**
* noticeOfTrialDate is displaying even when a Notice of Trial hasn't been issued
* It looks like this is picking up the served date of the petition

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/f7846425-f602-4cfe-a9e5-9dfe97f9d3ba)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
@cholly75 @JessicaMarine  This issues has been present since this field was first added to the case entity (about 18 months ago). This PR removes the default date (sets to current timestamp) when a Case is created.

https://github.com/ustaxcourt/ef-cms/pull/1565

What about the old data? Do we need to correct these? If so we will likely need a migration and probably a way of looking at each case record to determine if there is a notice of trial on the docket record and then removing this field if not.

**Comment by matthopson** [comment]
Will do a migration to clean up old data.

**Comment by matthopson** [comment]
Migration PR: https://github.com/ustaxcourt/ef-cms/pull/1590

**Comment by ttlenard** [comment]
I looked in a few random cases and no longer saw the Notice of Trial Date in the JSON. I also looked at a few random cases that had a trial date and they HAD a Notice of trial date in the JSON, so this looks good to me! Thank you.
