### ISSUE TITLE
BUG: Trial Session generated by Smoketests is throwing 400 error

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7968]
**Describe the Bug**

When trying to access the [December, 2022 Mobile Alabama Trial Session](https://app.test.ef-cms.ustaxcourt.gov/trial-session-detail/c7c79235-839a-4612-b4f3-1d9b9e45b752), you get a 400 error on the Test environment. This was a recently created (7/14/2021) by running smoketests in that environment. Cases were also added of course by the smoketests. It has recent production data.

We've seen this behavior in the past, and it's somewhat unclear what caused it. Perhaps changing the details of certain cases? We ended up needing to remove two of the records to clean the data up. These are two bugs where we worked on this before:

- https://github.com/flexion/ef-cms/issues/8384
- https://github.com/flexion/ef-cms/issues/8186

**Business Impact/Reason for Severity**

Trial Sessions are important functions of the Court, and they need to work reliably.

**In which environment did you see this bug?**

Test

**Who were you logged in as?**

Internal User

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Running Smoketests. Observed the failure during the tests, and then replicated it by logging in

**To Reproduce**

1. Login as an Internal User
2. Click on Trial Sessions
3. Scroll down to Mobile, Alabama December 2022, and click on it

NOTE: how this trial session got in this state is unclear, but it was a result of smoketests and a mixture of smoketest data and recently glued production data

**Expected Behavior**

The trial session should work

**Actual Behavior**

The Trial Session produces a 400 error trying to get the Eligible Cases

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
Just adding some thoughts on this.

It's probably not the trial session that's to blame here, as this issue crops up when there are duplicate trial sort tags for a given case. I'd also add it's possible the smoke test isn't responsible, and maybe just exposed it. I'd kinda like to try and query the db for duplicate trial sort records that may have come over from prod.

**Comment by codyseibert** [comment]
![Screen Shot 2021-07-29 at 3 22 43 PM](https://user-images.githubusercontent.com/1868782/127553270-4d285607-66a9-4e65-9331-341df8071d70.png)

We think the only case that is potentially broken is 12449-20 because it has 4 mapping records which results in duplicate batchGet requests.

**Comment by matthopson** [comment]
We were able to reproduce the issue by reverting the bug fix from https://github.com/ustaxcourt/ef-cms/pull/1303 and unsetting high priority status on a case. This would have been how cases were probably getting into this state when we originally looked at this bug (but didn't find it).

The fix we implemented ensured we couldn't have duplicates, as existing records would be queried and deleted before adding new ones.

When we disabled that code that queries it, unmarked a case as high priority, we observed duplicate records for that case. Creating a trial session in that preferred trial session manually produced the 400 as expected. Further, running smoketests that created a trial session on that preferred trial session also produced the 400.

@codyseibert and I were able to run a query to determine there were a few cases with duplicate trial sort mapping records. We created a trial session in that environment with the preferred trial city for case 12449-20 (screenshot in previous comment), and produced the 400.

I think we need to run this query on production (though it should be good with this since there was a recent glue job), and manually correct the records where there are more than 2 (since there are so few that need to be corrected).

**Comment by adunkman** [comment]
The duplicate key error is present only when there are duplicate `eligible-for-trial-case-catalog` records with different Case Types AND different Case Priority Symbols.

**Comment by mariahkannenberg** [comment]
Blocked - waiting for Mike to return.

**Comment by adunkman** [comment]
[The discussion thread in Slack](https://ustaxcourt.slack.com/archives/C015SEE9CUU/p1627656751001500) contains the context and suggested fix, leaving a breadcrumb for Mike later. 😄

**Comment by mariahkannenberg** [comment]
Mike deleted the record, but needs to verify. Andrew to reach out to Mike.

**Comment by mariahkannenberg** [comment]
Continue to hold for Mike.
