### ISSUE TITLE
Order Search: OR keyword search

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7969]
As a Court employee, in order to locate the most relevant documents, I need to have more control over how my keyword search is executed.

## Acceptance Criteria
* User is able to search using multiple keywords/phrases using the equivalent of boolean operator “OR” and retrieve results containing EITHER keyword/phrase (including exact match) 
* When run on full data set, searches return expected results, do not return results outside of design scope; search remains performant

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Question for Engineers: How hard would it be to implement exact search AND operators in same search.  For example: "motion for summary judgment" and denied
* Don't need to support multiple boolean operators in a single search for now

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
- Keyword OR keyword in document title and contents 
- Keyword OR keyword in document title only 
- Keyword OR keyword in contents only

- “Exact match Keyword phrase” OR keyword in document title and contents
- “Exact match Keyword phrase” OR keyword in document title only
- “Exact match Keyword phrase” OR keyword in document contents only 

- “Exact match Keyword phrase” OR “Exact match keyword phrase” in document title and contents
- “Exact match Keyword phrase” OR “Exact match keyword phrase” in document title only
- “Exact match Keyword phrase” OR “Exact match keyword phrase” in contents only 

- Keyword phrase OR “Exact match keyword phrase” in document title and contents
- Keyword phrase OR “Exact match keyword phrase” in document title only
- Keyword phrase OR “Exact match keyword phrase” in contents only
