### ISSUE TITLE
BUG: Cannot Create or Edit Trial Session Time to values between 12:00 PM - 12:59 PM

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7971]
**Describe the Bug**
When creating or editing a Trial Session, when "12" is entered in the hours field for the Time, it will always change the AM/PM data on the Trial Session to "a.m." Attempting to use the AM/PM radio buttons to switch to "p.m." does not work, and the change is ignored. This happens regardless of the value entered in the minutes field for the Time.

**Business Impact/Reason for Severity**
Docket cannot schedule any Trial Sessions for times between 12:00 PM - 12:59 PM.

**In which environment did you see this bug?**
Mig/Prod

**Who were you logged in as?**
docketclerk1@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Following up prod bug report

**To Reproduce**
1. Go to Trial Sessions.
2. Click the "New" heading.
3. Click the Location hyperlink for a Trial Session in the results list
4. On the Session Information page, click the Edit hyperlink.
5. In the hours field in the Time section of the screen, enter "12". In the minutes field, enter "00".
6. Click the "pm" radio button [NOTE: there is no indication that the radio button has been selected; this is documented in bug XXXXXX]
7. Click the Save button at the bottom of the screen.

**Expected Behavior**
The Date field on the Session Information screen reflects the time of the session as "12:00 p.m.".

**Actual Behavior**
The Date field on the Session Information screen reflects the time of the session as "12:00 a.m.".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 91.0.864.70

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
@cholly75 the steps to reproduce don't work for me -- is docket clerk supposed to see an "edit" link on the session information page.  EDIT: after I created a trial session as a trial clerk, I was able to edit the same session and replicate.

**Comment by cholly75** [comment]
@kkoskelin Yeah, I get it as docket:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/f786cca7-6cfb-44d2-bad0-f01fad38a5fa)

**Comment by cholly75** [comment]
This is still occurring in MIG - edited trial session in Fresno, CA for 11/11/21 to change the time to 12PM and saved. The Trial Session info screen still shows the time as 12AM.
