### ISSUE TITLE
BUG: Document got served then lost during Blue/Green Migration

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#798]
**Describe the Bug**

While we were conducting a Blue/Green migration in Production, a user was serving a document. They received the service email, and the PDF made it to S3. However, upon switching colors, the record was lost to the old table. For some reason the stream was not properly subscribed to the old table. We should have copied that record over to the new table.

Document info:
```
docketNumber: 9552-19
docketEntryNo: 31
docketEntryId: b5eb1f7f-7174-4527-ab12-5a746b47e253
eventCode: SUPM
```

```
docketNumber: 9552-19
docketEntryNo: 30
docketEntryId: 21b9552a-a653-4f86-a008-c46673b6468c
eventCode: M014
```

**Business Impact/Reason for Severity**

We can't have served documents go missing.

**In which environment did you see this bug?**

USTC Production

**Who were you logged in as?**

N/A 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

User was e-filing and serving a document while a blue green migration was happening.

**To Reproduce**

1. Start a BG migration
2. File and Serve a document
3. Switch colors
4. Does the document exist in the new DB table?

**Expected Behavior**

The document should be in the new table after switching colors.

**Actual Behavior**

The service email completed, the PDF is in S3; however, the items were no longer in the DB.

**Screenshots**

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by JessicaMarine** [comment]
Moved to Flexion's backlog: https://github.com/flexion/ef-cms/issues/7663
