### ISSUE TITLE
BUG: Unable to retrieve case by searching petitioner name

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7981]
**Describe the Bug**
Bug was reported by Jen Preston. 

Per Jen's email: 
In this case I couldn’t find the case by party name only docket number.  But all I had to start was the party name.  Our case was settled by stipulated decision which is why there isn’t an opinion that was referenced.  What I ended up doing was tracking down the district court file where our stipulated decision order was attached as part of an appendix.  That gave me the docket number so I could find the case.

The case is:
Katholos v. Commissioner
Docket No. 19011-16

It’s a sealed case but that shouldn’t be an issue for me because I was logged into the system.  Searching by Katholos pulls up zero hits.  Searching by 19011-16 pulls up the case.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
prod 
confirmed on migration 

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
reported by end user 

**To Reproduce**
1. Go to advanced case search 
2. Search for "Katholos" in petitioner name 

**Expected Behavior**
Case 19011-16 should display in search results. 

**Actual Behavior**
Case 19011-16 does not display in search results. 19011-16 can be searched and accessed by docket number only. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
The petitioner's place of residence is not in the United States (the default country that is searched upon). Changing to international brings back the expected result.

**Comment by mmarcotte** [comment]
So, looks like it's working as we would expect.
