### ISSUE TITLE
BUG: Quick fix for Petitions' Inbox/In Progress box

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7984]
**Describe the Bug**
The Court needs a quick fix for https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8625

**Business Impact/Reason for Severity**
Petitions are not getting served; taxpayers could be assessed prematurely

**In which environment did you see this bug?**
Prod; able to reproduce in `mig`

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Reviewing backlog

**To Reproduce**
1. Log in as Petitions Clerk
2. Go to section In Progress box
3. Note that 5936-21 and 8092-21 are not In Progress
4. Go to each case
5. Note that the case is `New` and not served; it should be In Progress

**Expected Behavior**
* The proper cases appear in the Inbox and In Progress
* If only 1,000 cases can return, they must be the 1,000 oldest
* Cannot count the 1,000 over the two boxes

**Actual Behavior**
* System is only returning 1,000 items and is arbitrarily deciding which ones to show
* Cases are not showing in the In Progress box that should be there

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/5c2c31b4-510a-4418-be9a-e31232e6081a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by ericsorenson** [comment]
https://github.com/ustaxcourt/ef-cms/pull/1516

**Comment by JessicaMarine** [comment]
@ericsorenson When you click on a Petition from the Petition Section Inbox, you get a blank white screen.  It doesn't seem to be routing correctly.  This same issue does *not* seem to be present when clicking on a Petition from the In Progress box. This seems to only be happening with Petitions added from smoke tests.  Thoughts?
