### ISSUE TITLE
BUG: Data validation firing when editing a Docket entry type to "Order"

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7985]
**Describe the Bug**
When editing a docket entry to the type of "Order", the data validation requiring a selection for Service (Served||Entered and Served) is preventing the entry from being saved. 

**Business Impact/Reason for Severity**
Cannot save a docket entry that has been edited to type "Order" - data validation prevents this (see attached screenshot).

**In which environment did you see this bug?**
TEST and MIG

**Who were you logged in as?**
docketclerk1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Report from production user.

**To Reproduce**
1. Go to Docket 18515-19
2. Edit docket entry index 9
3. Select "Order" from the Document Type dropdown.
4. Note that the Service radio buttons do not display.
5. Click the Save button.
6. Note that data validation triggers and the record is not saved.

**To Reproduce (from Kris)**
1. Open a case detail page and Create > PDF Upload
2. Add docket entry for pdf you uploaded. Specify "Returned Mail" as document type.
3. Save changes to verify "Returned Mail" entry is present.  Click "Edit" link on Docket Record view.
4. Change document type to "Order" and click save.
5. Validation fires and complains as seen below:
![Screen Shot 2021-08-11 at 1 43 48 PM](https://user-images.githubusercontent.com/2445917/129085606-12a330d5-094f-4c59-bd59-6b1455dcb11f.png)

**Expected Behavior**
Service buttons do not display; user can select the "Order" value and save the edited docket entry without triggering data validation.

**Actual Behavior**
Service radio buttons do not display but user cannot save edited docket entry as type "Order".

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/d9071138-ada3-4717-9ff9-33e9caaee0e1)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
Blocked because it is unclear whether this is a valid workflow:
Is it possible to create a docket entry for a non-Order (say, a "Returned Mail" document) and convert it to an order (which must go through the draft order workflow with signing) in this way? what would that look like?  Seeking answers.

**Comment by mariahkannenberg** [comment]
This story is not a bug, it was a use case/flow that wasn't created yet. Here is the story in the "New" backlog. https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7474

**Comment by cholly75** [comment]
Thanks @mariahkannenberg - I'll close this then.

**Comment by cholly75** [comment]
@mariahkannenberg - just found ustaxcourt/ef-cms#7711, which appears to be the same issue? Let's talk about it tomorrow. I believe the issue is that the served vs. entered and served validation is firing when an order type is being changed to another order type (a detail only in the steps to reproduce, not the story proper, so that's on me).

**Comment by cholly75** [comment]
@kkoskelin @mariahkannenberg - the issue is specific to when a docket clerk changes a given Order from a specific order type to a generic Order, which is supported in the UI. The served selection validation should not be firing in this case, as there is no (and should not be an) option to select Served vs. Entered and Served.

**Comment by mariahkannenberg** [comment]
Matt and Mariah to pair to investigate today.

**Comment by cholly75** [comment]
@matthopson @mariahkannenberg Entered story 8866 for this as discussed, referencing 7474
