### ISSUE TITLE
Order Search: Special Character Usage

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7987]
As a user, I need to use commonly used special characters -, &, and . as literal characters when searching for content so that I can find documents that include these characters as part of names or text.

## Acceptance Criteria

- Both exact and non-exact match search types accommodate the use of these characters (dash, ampersand, period)
- Using these characters literally has no other function impacting the search results returned
- Searches that do not use these characters continue to function as normal
- These characters can be used literally in combination with any logical functions also supported by search

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Examples of expected search behavior:

Search term: Coca-Cola 
Search term: "Coca-Cola"
Search term: coca cola
Should all return results containing “Coca-Cola”

Search term: Johnson & Johnson
Search term: johnson johnson
Search term: "Johnson & Johnson"
Should all return results containing “Johnson & Johnson”
 
Search term: Girardi & Assoc.
Search term: girardi & assoc.
Search term: girardi assoc.
Search term: "Girardi & Assoc."
Should all return results containing “Girardi & Assoc.”

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by codyseibert** [comment]
Notes from discussion

Search term: "coca cola"
should not return any documents that only have "Coca-Cola"

Search "T.C. Memo"
Search "TC Memo"
Search "TC. Memo"
Document has "T.C. Memo" in Title

**Comment by mariahkannenberg** [comment]
Blocked - Batch 5 still on migration. Need to test with data. Deploy to test?

**Comment by cholly75** [comment]
Ampersand appears to be reading as null in the search query.

I searched for "& johnson" (exact match) and got results back that contained no ampersand.

I also searched for "johnson & johnson" (exact match) and got back a single result containing the text "johnson johnson" in the Order.

Do we know why & is not parsed as an exact match literal?

The - and . appear to be working correctly.

**Comment by kkoskelin** [comment]
> Do we know why & is not parsed as an exact match literal?
>

It may be necessary to change some of our indexer settings per https://stackoverflow.com/questions/51785404/search-special-characters-with-elasticsearch/51793767

**Comment by kkoskelin** [comment]
The current search index configuration cannot treat all symbols and punctuation as "token characters" (i.e. parts of a word to be indexed) because it would conflict with the desire to *sometimes* treat them as word (token) delimiters.  E.g. if search text contains
```
firmname & assoc. petitions the court
```
you will not be able to search for the word `assoc` because in the above text, the word is `assoc.`
