### ISSUE TITLE
Court: Content Changes Needed to Notice of Receipt of Petition

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7988]
As the Court, in to incorporate remote proceedings into our longer term procedures, we need to make content changes to the Notice of Receipt of Petition.

## Acceptance Criteria
* New content changes should match: [https://app.zenhub.com/files/152320868/36cca211-ed43-496e-8359-dc5d71c7a6a1/download](https://app.zenhub.com/files/152320868/36cca211-ed43-496e-8359-dc5d71c7a6a1/download)
* Deploy to production, but do not release

The changes needed are highlighted: [https://app.zenhub.com/files/152320868/21a844d7-f345-4b9b-9244-d5a8524add6f/download](https://app.zenhub.com/files/152320868/21a844d7-f345-4b9b-9244-d5a8524add6f/download)

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Current version: [https://app.zenhub.com/files/152320868/9fcdc1bb-da5f-4db4-9f57-3fad7f03395d/download](https://app.zenhub.com/files/152320868/9fcdc1bb-da5f-4db4-9f57-3fad7f03395d/download)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
Moving this up in priority, as it's possible that we'll get the order to implement this on very short notice; @mariahkannenberg can we get this done and put the change behind a feature flag so the work is completed and we can just flip it on when required? If not, we'll just have to be ready to swarm on it for rapid deployment.

**Comment by matthopson** [comment]
https://github.com/flexion/ef-cms/pull/8696

**Comment by matthopson** [comment]
@klohman @cholly75 Here is the updated document template as generated by our template generator tests.
[https://app.zenhub.com/files/152320868/cce7b504-d558-43b4-bd8a-3d1e254d033d/download](https://app.zenhub.com/files/152320868/cce7b504-d558-43b4-bd8a-3d1e254d033d/download)

And just for comparison here is the current document template generated by the same test suite.
[https://app.zenhub.com/files/152320868/c4a18d67-5d91-4397-8d80-f055a4dcdbc1/download](https://app.zenhub.com/files/152320868/c4a18d67-5d91-4397-8d80-f055a4dcdbc1/download)

**Comment by cholly75** [comment]
@matthopson @klohman Looks good!

**Comment by mariahkannenberg** [comment]
BLOCKED - Waiting for batch 5 to get off of mig.

**Comment by cholly75** [comment]
@matthopson Story 8714 has been added to track activating these changes in the live DAWSON environment when appropriate.

**Comment by matthopson** [comment]
Thanks!
