### ISSUE TITLE
Court: Re-implement Notice Setting Case for Trial for In-Person Proceedings

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7989]
As the Court, in order to return to in-person proceedings, we need to re-introduce a Notice Setting Case for Trial for in-person proceedings

## Acceptance Criteria
* If a case is set for trial at a **IN-PERSON** session as part of the automated scheduling process, the Notice Setting Case for Trial should match the following content: [https://app.zenhub.com/files/152320868/b30cadf7-f833-4089-b39e-90559c794603/download](https://app.zenhub.com/files/152320868/b30cadf7-f833-4089-b39e-90559c794603/download)
* Need to fully test in-person flow to figure out what is missing or needs to be changed to implement the separate notice
* Nothing in the remote proceedings flow should be changed by this work

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

Changes needed:

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
@rachelschneiderman Looks good, I think there's one issue with the in person version of the Notice Setting Case for Trial - in graf 2/line 1, there's a space missing between the words "parties" and "request" that needs to be corrected:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/21b5efb5-2af5-4689-b89e-e7c8e5b8d9c2)

Something else came up when testing the in person flow for this, which is that the Standing Pretrial Order that's generated along with the Notice Setting Case for Trial has an incorrect header for in-person sessions: it lists the city and state correctly, however it also includes the text "Remote Proceeding". This should not be present on the headers for the SPO generated for in-person trial sessions. Please let me know if this needs to be fixed as part of this or another story.

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/55bfdcea-798a-4fc3-846a-584e2cc62c0a)

Thanks!
Chris

**Comment by mariahkannenberg** [comment]
Check content for consistency in spacing after periods. @rachelschneiderman

**Comment by cholly75** [comment]
Hi @JessicaMarine When testing this again the in-person documentation looks good, when I checked the remote proceedings docs I found this as the header:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/9e3e9f9b-23b0-4565-bde0-f5248fa8df29)

Is that desired behavior, or do we still want the location and "Remote Proceeding" in the header of the PT memo for remote proceedings?

**Comment by cholly75** [comment]
@rachelschneiderman It looks like the remote proceeding version of the PT Memo lost the city/state and "Remote Proceeding" text on the header. This should be part of the header text in remote proceeding cases. The in person changes look good!
