### ISSUE TITLE
Court: Content Changes for SPTO (Regular Cases) - Release with 8663

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7990]
As the Court, to incorporate longer-term procedures for both in-person and remote proceedings, we need to make content changes to the Standing Pretrial Order.

## Acceptance Criteria
* New content changes (starting underneath the case caption/docket number) should match: [https://app.zenhub.com/files/152320868/b8aba75f-c76f-4a05-b362-a8b08bbdc7c7/download](https://app.zenhub.com/files/152320868/b8aba75f-c76f-4a05-b362-a8b08bbdc7c7/download)

* The changes needed are detailed here: [https://app.zenhub.com/files/152320868/69b8a86a-6560-4143-a49c-9c0a8264965d/download](https://app.zenhub.com/files/152320868/69b8a86a-6560-4143-a49c-9c0a8264965d/download)
* Ensure E2E flow works correctly.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Current DAWSON version: [https://app.zenhub.com/files/152320868/fa16f203-fbd1-45f8-b858-8d13e10ecdfe/download](https://app.zenhub.com/files/152320868/fa16f203-fbd1-45f8-b858-8d13e10ecdfe/download)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by JessicaMarine** [comment]
Very minor feedback on the Standing Pretrial Order:
- Can we try to bump the text size up just slightly on the entire first 3 pages.  It just looks too small to me.
- The 3rd and 4th underlined lead-in sections (Electronic Filing (eFiling) and Communication Between the Parties -- it looks like the period is an extra space away.  Please delete that extra space.
- The spacing on the numbered paragraph 3 is off across that entire section:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/d4b9a517-b4d8-430f-b355-732355223888)

**Comment by JessicaMarine** [comment]
@TomElliottFlexion Some additional feedback:
- For paragraph 3, there should be a line added before subpar. A between subpar. A & B
- In paragraph 7, there is an extra space between the opening parens and www.ustaxccourt.gov
- In paragraph 7, please switch the last two words to `numbering pages`
- Please check the spacing after each period.  It can be 1 or 2 spaces, but it should be consistent throughout the entire document

**Comment by TomElliottFlexion** [comment]
An updated PDF: [https://app.zenhub.com/files/152320868/cff76f81-e44e-4df4-8dd7-1eb27399a51a/download](https://app.zenhub.com/files/152320868/cff76f81-e44e-4df4-8dd7-1eb27399a51a/download)
