### ISSUE TITLE
Court: Content Changes for SPTO for Small Cases - Release with 8662

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7991]
As the Court, to incorporate longer-term procedures for both in-person and remote proceedings, we need to make content changes to the Standing Pretrial Order for Small Cases.

## Acceptance Criteria
* New content changes should match: [https://app.zenhub.com/files/152320868/988d7eea-a0ea-4a16-9d49-627c25b116d0/download](https://app.zenhub.com/files/152320868/988d7eea-a0ea-4a16-9d49-627c25b116d0/download)

* The changes needed are highlighted: [https://app.zenhub.com/files/152320868/0713b9f9-17fd-4b3c-8269-6aa829db6902/download](https://app.zenhub.com/files/152320868/0713b9f9-17fd-4b3c-8269-6aa829db6902/download)
* Ensure E2E flow works correctly.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Current version in DAWSON: [https://app.zenhub.com/files/152320868/3be084dc-6305-4430-a1b2-5ffb843e9957/download](https://app.zenhub.com/files/152320868/3be084dc-6305-4430-a1b2-5ffb843e9957/download)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by JessicaMarine** [comment]
Feedback:
- In the box, can we break the text after "at" so that the bolded time and date are on a new line -- we'll want to do the same on the regular Standing Pretrial Order
- Increase the font size across the first 4 pages slightly
- The spacing is off across the entire first 4 pages.  It looks like it is 1.5 line spacing instead of 1.  Let's try to make it spaced more like the regular Standing Pretrial Order.

**Comment by JessicaMarine** [comment]
@TomElliottFlexion Some additional feedback:
- Please switch the last two words of paragraph 7(f) to `numbering pages`
- Please check the spacing after each period.  It can be 1 or 2 spaces, but it should be consistent throughout the entire document

**Comment by TomElliottFlexion** [comment]
An updated version of the Order for small cases: [https://app.zenhub.com/files/152320868/bab80ac5-a519-4e8f-85d1-40067e9a33b6/download](https://app.zenhub.com/files/152320868/bab80ac5-a519-4e8f-85d1-40067e9a33b6/download)

**Comment by klohman** [comment]
@TomElliottFlexion Couple of things on SPTO: 

* add space between for and summary here "forSummary" 

![Screen Shot 2021-08-02 at 4.06.17 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/619be688-b6d5-4b78-9e6d-92d182f8694d)


* add space to break up "toProceed" here
 ![Screen Shot 2021-08-02 at 4.07.31 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a67010ae-4362-4c26-92af-e20108224d4f)
