### ISSUE TITLE
BUG: Indexing does not complete after Blue/Green Migration

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7992]
**Describe the Bug**

The last three deployments have resulted in ES indexes that are incomplete. On a production sized data set, the total document count was only around 10 million, and it should have been above 12 million. Items are missing from every index; it's not just one. Can we replicate this with a smaller data set?

At first I thought it was stopping prematurely, but now I'm wondering if items are getting lost on the other side of the process. It could be happening with our advanced usage of the Lambda trigger and its StreamPosition on the DynamoDB stream. Right now we use LATEST, and maybe we should use AT_TIMESTAMP and specify the moment before we started the migration.

This seems more pronounced with the `sleep 90` that we added on the step that disables the trigger. FWIW, AWS recommended 120 to allow the hosts to fully shut down. At the same time, I know we're populating records into the Stream via Migrations only after this 90 second window has elapsed. It just appears that this stream and trigger aren't working the way we would expect them to work.

https://docs.aws.amazon.com/kinesis/latest/APIReference/API_StartingPosition.html

We could investigate to see which records are missing and try to figure out when they were migrated. Is there a pattern? Were they migrated first? Last? At various times during the migration? I believe `test` has a more complete index, and we could use that to see which records are missing.

**Business Impact/Reason for Severity**

Having a fully indexed database is vital for the application to function properly

**In which environment did you see this bug?**

Prod, Mig

**Who were you logged in as?**

N/A 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Blue/Green Migration

**To Reproduce**

1. Start a B/G migration
2. Observe the final count indexed into ES. 
3. Are you sure it matches up with what is in the DB?

**Expected Behavior**

All records fully indexed into ES. On a production sized data set, this should be over 12M

**Actual Behavior**

Only about 10M records re-indexed

**Screenshots**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
This has been merged to Court's test env via https://github.com/ustaxcourt/ef-cms/pull/1535

**Comment by matthopson** [comment]
Mark confirmed counts were accurate with a deploy with this change.

**Comment by mariahkannenberg** [comment]
Andrew merged PR to test.

**Comment by mariahkannenberg** [comment]
@adunkman to test w/@Tenille
