### ISSUE TITLE
BUG: Header wraparound using Microsoft Edge

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7993]
**Describe the Bug**
In some cases, when court users view DAWSON on the Order Search screen using the Microsoft Edge browser, the header navigation wraps and the Reports link moves to the left side of the screen:

**Business Impact/Reason for Severity**
Changing persistent navigation is disorienting and can cause confusion for the user

**In which environment did you see this bug?**
MIG

**Who were you logged in as?**
Chambers user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Validating testing 

**To Reproduce**
1. Log in as a chambers user
2. Navigate to the Advanced/Order search.
3. Note the change in the header organization on the UI.

**Expected Behavior**
The header links remain static in a single file row across the top of the screen.

**Actual Behavior**
The header link for Reports wraps around back to the left side of the screen.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/05a65999-cf24-465f-ab22-c79b1ee76f92)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
@cholly75 After some investigation, I think we need to create a new story rather than treat this as a bug. The underlying issue is the header navigation has grown as the application has grown, and the responsive breakpoints don't accommodate that well. 

Fixing this issue in THIS SPECIFIC scenario doesn't fix it in a slightly smaller viewport. The solution here is going to require some design input to overhaul this header navigation to accommodate all screen sizes. @klohman

**Comment by cholly75** [comment]
@matthopson makes sense. I'll close this issue, as I can't even repro this anymore.
