### ISSUE TITLE
BUG: Document Title Has Duplicate Text

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7996]
**Describe the Bug**
For docket 9261-17, three entries (162/163/164) have duplicate text in their titles; the document reflects this as well, however when viewing the Edit screen for the entry, the correct title is shown in the dropdown list for the "Which document are you redacting?" field. Additionally, multiple notices of docket change were generated for these entries.

**Business Impact/Reason for Severity**
Inaccurate document title; notices of docket change being generated unnecessarily; need to prevent this from happening on other documents
  
**In which environment did you see this bug?**
PROD/MIG

**Who were you logged in as?**
Docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Look for Docket 9261-17, entry 162
2. Note the duplication of the text "to First Stipulation of Facts (1-J through 59-J)" in the title (screenshots attached)
3. Click the Edit link for the docket entry.
4. Note that the correct title appears in the "Which document are you redacting?" field

**Expected Behavior**
Document title does not contain duplicated text

**Actual Behavior**
Document title has duplicated text

**Screenshots**

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/59cc2cf4-ea6e-48da-bf66-422fd1b10684)

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/508729a5-581d-4813-a056-979dc9ca9bf9)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
I am still seeing the duplicate text in the document titles in the TEST environment.  Need to kick this one back.

**Comment by mariahkannenberg** [comment]
Tenille still seeing the bug on test on the specific case re: in bug. Tenille to reach out to Kris.

**Comment by kkoskelin** [comment]
The titles on these docket entries are generated when they get edited -- and it is this act of generation that caused the duplicate strings.  To test fully, one must attempt to edit the docket entry.  For the case in question, edit docket entry 162 as a docket clerk and do the following:
1) locate the menu for "Which document are you redacting?"
2) change the selection from `Exhibit(s)... 1-J through 59J)` to `Exhibit(s) ... (60-J through 102.5J)`
3) change the selection again as above, but reverse it.  repeat several times, changing from one kind of "Exhibit(s)" to the other.

The menu:
![Screen Shot 2021-08-19 at 11 28 27 AM](https://user-images.githubusercontent.com/2445917/130107835-c9a5fdfb-ddd2-4329-ad1e-0e73c73e9372.png)

_In the MIGRATION environment:_
Every time you change from one document to another, you'll see the docket entry preview title grow longer and longer:
![Screen Shot 2021-08-19 at 11 28 41 AM](https://user-images.githubusercontent.com/2445917/130107861-9964bfb6-fa70-48f2-a525-1f0f5523731e.png)

_In the TEST environment:_ it is our hope that this docket entry preview "growth" does not occur, and that saving the docket entry change one more time will repair the long titles that have already been saved in the database.

**Comment by kkoskelin** [comment]
After speaking with @ttlenard and reviewing the `test` environment, the bug is fixed, though some docket entry document titles have "duplicate text" strings in them already as a result of editing them prior to the bugfix.
