### ISSUE TITLE
BUG: Checkboxes on Section QC Page are not working

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#7998]
**Describe the Bug**
The Checkboxes in the Section Document QC are not registering as being checked.  In the screen shot below, you can see that I have the top 3 cases selected, but the checkbox is not registering.

**Business Impact/Reason for Severity**
We have confirmed that this issue is NOT happening in Production, so if this bug is not addressed with the next deploy, it will introduce this bug into PROD.

**In which environment did you see this bug?**
MIG
Still need to test to see if this is happening in TEST (on Friday PM it appeared that the generic users were not loaded, so I could not log into TEST)
Note: This is NOT Happening in PROD

**Who were you logged in as?**
docketclerk1@example.com
petitionsclerk1@example.com

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing the application (and just learning the workflow!)

**To Reproduce**
Go to the Section Document QC page
Click on a few of the Checkboxes (I selected the top 3)
Notice that the little selection box in blue indicates that you selected 3, but the checkboxes are NOT selected.

You can also de-select one of your (blank) checkboxes, and notice that the little selection box in blue will also remove that selection.

**Expected Behavior**
If you select a checkbox, it should fill in letting the user know that it was selected.

**Actual Behavior**
If you select a checkbox, there is no indication that the box is selected.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/963fc347-e332-4e7d-9e0a-b91752413d58)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rosiehsmith** [comment]
This is due to a bug with USWDS's radio buttons and checkboxes: https://github.com/uswds/uswds/issues/4251

Looks like USWDS just fixed this issue today. https://github.com/uswds/uswds/pull/4262/files

**Comment by mariahkannenberg** [comment]
Failed smoke tests in USTC test env. @adunkman To perform manual color switch. Fix is now visible. Tenille to verify.
