### ISSUE TITLE
BUG: Cover sheet is not getting updated with the "Additional Info 1" data (after I check the box to add to cover sheet) while completing QC on a document as a Docket Clerk

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8004]
**Describe the Bug**
The cover sheet is not getting updated with the information that I enter into the "Additional Information 1" field when I check the box to "add to cover sheet"

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
TEST and MIG.  Not sure if this is happening on PROD?

**Who were you logged in as?**
docketclerk1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the app - learning!

**To Reproduce**
1. Be sure that you are a docket clerk
2. Go to your Document QC and select a document 
3. When the document panel opens, click "Complete QC"
4. Add in some information in the "Additional Information 1" field
5. Check the box for the "Add to Cover Sheet" checkbox
6. Complete the rest of the fields on QC form, and select "Complete"
7. Go to the Docket and notice that the Docket title is now updated with whatever you added in the "Additional Information 1" field, and there is a Notice for Docket change entry as well.
8. Open your updated Docket entry that has the updated title, and notice that there are two cover sheets in the document, but the updated text is not added to the new cover sheet.

**Expected Behavior**
Whatever information you add into the Additional information 1 field (and if you check the box for "add to cover sheet") should be added to the updated Cover sheet title.

**Actual Behavior**
Information added to the "additional Information 1" is not getting added to the cover sheet when you have the "add to cover sheet" checkbox checked.

**Screenshots**

After hitting Complete QC, you get this form.  Add in something in Additional Info 1 and click add to cover sheet.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/f4a91227-8cef-4b6a-970c-6fcb4ed33887)

When viewing the updated docket entry, the title is correctly updated, and there are now two cover sheets, but neither of them have the updated title.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1873b157-01b4-4477-a52b-f3184ef93608)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
Fixed with https://github.com/ustaxcourt/ef-cms/pull/1548
