### ISSUE TITLE
Search: Usability Improvement Package #1

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8005]
As a search user, I would like to make interacting with the search function and results in DAWSON more intuitive and user-friendly.

## Acceptance Criteria

- Search query can be executed by pressing the ENTER button the keyboard

- When a Docket number link is clicked from the returned search results list, the Docket screen displays in a new browser tab

## Mobile Design/Considerations

- Make sure that opening docket links in new tabs functions properly on mobile

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
These are based on UX recommendations stemming from usability research conducted with court personnel.

1. W/R/T the ENTER key, feedback from the team is that search is already working this way in some parts of DAWSON; we should extend this to the Order/Opinion searches as well.

2.W/R/T the Docket result link opening in a new tab, we will want to make sure that the app continues to function normally in the new window, and double-check that mobile users are not negatively impacted. Additionally, are there other areas of the app that this is/should be extended to?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Design Update for Search results 

* Move docket number column to the far left of the search results table 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4ec66021-27be-4cbb-a203-b5fb17bcc959)

**Comment by klohman** [comment]
## 8725 Test Cases 

#### 1) Court user initiates a search using the Enter key 
* Go to Order search 
* Enter keyword 
* Click Enter key 
Expected results 
- [x] Enter key triggers search 
- [x] Search triggered by Enter key works the same as when triggered by Search button

#### 2) Court user clicks document link and views Order PDF in a new tab 
* Go to Order search 
* Run search query 
* Click document link from result set 
Expected results 
- [x] Document PDF opens in new tab 

#### 3) Court user clicks document link and views Order PDF in a new tab on mobile device 
* Go to Order search on mobile device
* Run search query 
* Click document link from result set 
Expected results 
- [x] Document PDF opens in new tab

**Comment by klohman** [comment]
Small nit - can we better align the Order document link in the table? It's slightly lower than the rest of the row content. 

![Screen Shot 2021-08-09 at 2.25.16 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2065cb7c-132c-4f80-8a51-f0271074da85)
