### ISSUE TITLE
BUG: Trial Session Problems - Buttons missing/not working appropriately

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8015]
**Describe the Bug**
The AM/PM radio button in the Create Trial sessions workflow is not functioning.  When I click on either button, it appears that nothing happens.  In addition, the radio button for Proceeding type of in person or Remote are also not working, but you can tell that something is happening, as the fields change when you attempt to click the buttons.

After I created the Trial session, I can click on the Complete QC checkboxes, but the Set Calendar button is missing.  You can tell that the button is there,  because your mouse pointer turns to a hand when hovering over the spot where the set calendar button is located, t's just not showing up on the screen.

This is happening on TEST, but not on MIG

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

TEST
Note: This is NOT happening in MIG

**Who were you logged in as?**

Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

General testing

**To Reproduce**
1. Go to Trail Sessions tab
2. Click on the Create new Trial Session
3. Enter a time and click on AM. Notice that the button does not work for either AM or PM
4. Click on In person or Remote proceeding, notice that the button doesn't work, but that the different fields do show up depending on which proceeding type you select
5. After you create the trial session, go back in to the session to QC eligible cases. Notice that the Set Calendar button is missing.  
6. Hover over the area where this button lives on the screen, and notice that the mouse pointer turns to a hand where the button is, so the button is there, it is just not visible.

**Expected Behavior**
Radio buttons should show indication that user selected them. Set calendar button should be visible to user.

**Actual Behavior**
A clear and concise description of what actually happened.
Radio Buttons are not showing up as being selected. Set Calendar button not appearing for user.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/29f41f13-e242-4b6a-8068-eca5bf535a2b)

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/9ee9c3c7-e6cf-42a2-a2a1-609bebab869f)

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/22710941-1c96-4ed4-b215-7ae574c8b02c)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]  Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mariahkannenberg** [comment]
Blocked - may be fixed when envs are updated.

**Comment by ttlenard** [comment]
I just tested this again on the TEST environment. All was working. No longer seeing issues with buttons not working, and I can see the "Set Calendar" button as well.  I believe we can cancel this ticket?

Thanks everyone!

**Comment by mariahkannenberg** [comment]
Chris to add a note and then close.

**Comment by cholly75** [comment]
USWDS issue resolved - see 8693 for similar issue. Can no longer reproduce.
