### ISSUE TITLE
BUG: As a Trial Clerk, I am unable to download all cases in a trial session

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8016]
**Describe the Bug**
Trial Clerks are unable to download all cases in their Session Copy of a Trial

Question for the Devs: Is this workflow in the automated smoketests?  Not sure if it should be?  Please advise.

**Business Impact/Reason for Severity**
Will be high severity once in person proceedings are back.

**In which environment did you see this bug?**
MIG
TEST

**Who were you logged in as?**
Trial Clerk
Note: when logged in as a Judge, this problem does NOT happen.  All works as expected.

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

General Testing

**To Reproduce**
1. Log in as a Trial Clerk, and be sure that you have a trial session assigned to you
2. Click on Trial Sessions
3. Open a upcoming trial session and click Download all cases
4. See compression error

**Expected Behavior**
When you click on download all cases, you should get a zip folder downloaded to your computer with all of the docket entries added to case folders

**Actual Behavior**
A clear and concise description of what actually happened.
When I click Download all cases, I receive a file compression error.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/eee886f5-8e2e-40db-965b-2fe864ed80a4)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
The issue here is that a trialClerk does not have permission to batch download a trial session. Since this is a permissions change, I'm just pinging @klohman and @cholly75 for awareness. This is probably some obvious missed AC from way back and not a big deal, but just wanted to let you know.

PR: https://github.com/ustaxcourt/ef-cms/pull/1562

**Comment by cholly75** [comment]
@matthopson Confirming - will let you know tomorrow.

**Comment by cholly75** [comment]
@matthopson Confirmed.
