### ISSUE TITLE
Search: Exact match for special characters

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8017]
As a Court user, so that I can find documents that have an exact match, I need special characters to be considered as part of the exact match. 

## Pre-Conditions
ustaxcourt/ef-cms#7987 (Original Story)

## Acceptance Criteria
* When a Court user conducts an exact match search **using** a special characters (dash, ampersand, period), the results should return **only** items that have the special characters in them
* When a Court user conducts an exact match search that **does not use** special characters (dash, ampersand and period), the results should **not** return items with special characters in them

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* This one might be problematic, esp. the period because sentences have periods and the last word in a sentence would be overlooked. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Sample Test Cases:

Search term: coca cola
Should NOT return results containing “Coca-Cola”
Search term: coca cola
Should return results containing “Coca Cola”

Search term: "johnson & johnson"
Should NOT return results containing "johnson johnson"

**Comment by cholly75** [comment]
Search term: "Coca-Cola"
Should return results containing “Coca-Cola”
Should not return results that do NOT contain "Coca-Cola"
Should not return results containing ONLY "coca cola", "-cola", "coca-"

Search term: "Johnson & Johnson"
Should return results containing “Johnson & Johnson”
Should not return results that do NOT contain "Johnson & Johnson"
Should not return results containing ONLY "johnson johnson", "Johnson", or "johnson-johnson"

Search term: "Girardi & Assoc."
Should return results containing “Girardi & Assoc.”
Should not return results that do NOT contain "Girardi & Assoc."
Should not return results containing ONLY "Girardi Assoc.", "Girardi & Assoc", "Girardi Assoc", "Girardi", "Assoc.", "Girardi&Assoc."
