### ISSUE TITLE
SPIKE: Investigate options for use of special characters

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8018]
As a product owner, so that I can write acceptance criteria that doesn't conflict with OOB functionality of Elastic Search, I need to know what my options are for the use of special characters dash, ampersand and period. 

## Acceptance Criteria
- PO understands under what conditions we can and cannot expect searches using special characters -, &, and . to return results

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by TomElliottFlexion** [comment]
Matrix of special use characters in order search and their results https://docs.google.com/spreadsheets/d/1QolUAtg2kfT2Bv4NYxfzJhuz-jup4Ei1uPZxEHh1odE/edit#gid=0
Thanks @kkoskelin 

Of note: 
- "-" and "&" will return the same results whether or not they are included in the search, regardless of exact phrase matching. 
- "." Is a sentence boundary but not a word boundary, so it is treated as the end of a word and ignored when preceded or followed by a space (e.g. end of a sentence) but treated as part of a word when not (e.g. I.R.S.)

**Comment by TomElliottFlexion** [comment]
Note: ASCII-folding is not currently supported by advanced search: If a document contains diacritics (e.g. ñ ö) they will not return on searches unless that EXACT character is provided (Cortés vs. Cortes). This could provide difficulty when searching for names. There is a feature available that could easily be turned on to support this.

**Comment by TomElliottFlexion** [comment]
Note: "-" character is the "NOT" operator (currently not supported, but coming in ustaxcourt/ef-cms#7970). The results of the search matrix are likely to change once we enable this "NOT" operator.
