### ISSUE TITLE
Order Search: Search terms using abbreviations with and without periods

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8019]
As a Court user, so that I can find documents with abbreviations, I need the search results to return items with abbreviations regardless of whether they have a period in them or not. 

## Acceptance Criteria
* User can perform a search using abbreviations and no periods and return **results that don't have periods**
* User can perform a search using abbreviations and no periods and return **results that do have periods**

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Test Case Examples:
Search term: `"T.C. Memo"`
Should return results containing “T.C. Memo", "TC. Memo" and "TC Memo" 

Search term: `"TC Memo"`
Should return results containing “T.C. Memo", "TC. Memo" and "TC Memo" 

Search term: `"TC. Memo"`
Should return results containing “T.C. Memo", "TC. Memo" and "TC Memo"

**Comment by cholly75** [comment]
I need to think about this one some more. I don't want periods to behave differently in absence of any indication whether the user is searching for abbreviations or not.

**Comment by kkoskelin** [comment]
Suggestion: this may require a text transformation for very specific strings:
"T.C." -> "TC"
Do this for the text which gets indexed by the streams, but also for the text provided in search inputs.
Because the period/dot is regarded as a token separator, the only solution I see is to transform the text into a single token of "TC".
