### ISSUE TITLE
BUG: Trial Clerks Session notes say "Judges Notes" instead of "User Notes"

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8021]
**Describe the Bug**
As a trial clerk, when I am in a Session copy of a trial, and I click on add note in the Session notes area, The name of the text box says "Judges Notes" instead of User Notes.  This is confusing, because it is not the judge that is making this note, it is the Trial Clerk.

I did a little digging around in GitHub and I believe that this was previously addressed in ustaxcourt/ef-cms-flexion#4455?  I think this was a task in the story ustaxcourt/ef-cms#7062? (still learning how to navigate around in GitHub...)

**Business Impact/Reason for Severity**
Low Severity - Trial Clerks can still add notes, it is just a confusing label.

**In which environment did you see this bug?**
MIG

**Who were you logged in as?**
Trial Clerk 1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
General Testing

**To Reproduce**
1. log in as a trial clerk
2. Be sure that you have a case that you are assigned to
3. Click on Trial Sessions
4. Find the Trial session that you are assigned to as a trial clerk
5. Click to open the session.  
6. Click on add note in the Session notes area at the top of the page.
7. Notice that it says Judges Notes in the pop-up text box.

**Expected Behavior**
When a trial clerk clicks on add notes in a session copy, they should not see a label that says Judges Notes.

**Actual Behavior**
A clear and concise description of what actually happened.
When a trial Clerk clicks on the add note in the session notes, it says Judges Notes.

**Screenshots**

Click on add note in the session Notes area:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/792668a6-b5e6-4d16-969b-0019be1d5b6c)

Notice that it says Judges Notes, not "User notes":
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/0a23bf69-df1c-4768-a78f-b571363de00b)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]  Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
PR: https://github.com/ustaxcourt/ef-cms/pull/1578

**Comment by ttlenard** [comment]
I tested over on TEST and it looks great!  The Session notes now say "User Notes" instead of Judges notes. Thank you!
