### ISSUE TITLE
Court: Prevent Change of Telephone Number Notices From Being Marked As Served Before Petition Has Been Served

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8022]
As a system, I want to prevent Change of Telephone Number notices from being marked as served before the petition for a case has been been served, so that I do not inaccurately reflect the state of the docket.

## Acceptance Criteria
- When a Change of Telephone Number notice has been generated for a party, the docket entry should not show as Served on dockets the party is attached to for which the associated Petition has not been served.
- When the associated Petition has been served, if the the Change of Telephone Number notice has been QC'ed then it  should be marked as Served and an email should be sent as per the normal service procedure along with the other pending QC'ed documentation.
-When a Change of Telephone Number notice has been generated for a party, once it has been QC'ed it should be Served and marked as such for all docket entries whose associated Petition has been served as per the normal service procedure.
-This is the desired flow regardless of the party committing the change of telephone phone number.
-This is the desired behavior regardless of whether the parties receive paper or electronic service.

 
## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
We want this behavior to be universal in the system; no notices should show as served until the Petition for the associated docket has been served.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
Flows for context: 
https://github.com/flexion/ef-cms/issues/4661

**Comment by mariahkannenberg** [comment]
Being addressed in 8763
