### ISSUE TITLE
BUG: Docket Clerks receiving 400 Error when completing QC on Simultaneous Reply Brief from Respondent

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8023]
**Describe the Bug**
This was reported by two Docket Clerks on PROD.  When a Simultaneous Reply Brief is filed by the Respondent, and the Docket Clerk attempts to QC it, they get a 400 Error on clicking Complete. This is on docket no. 5769-20 in PROD.

**Business Impact/Reason for Severity**
High Severity - unable to complete QC

**In which environment did you see this bug?**
PROD
MIG

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Ensure that there is a Simultaneous Reply Brief that has been filed by respondent
2. Log in as a docket clerk 
3. Go to Document QC
4. Find the Simultaneous reply brief document
5. Open document to perform the QC
6. Click on Complete
7. Receive 400 Error
8. (I also attempted to click "complete and send message" and this got the same results.)

**Expected Behavior**
Docket clerk is able to complete the QC of the Simultaneous Reply Brief from the respondent.

**Actual Behavior**
A clear and concise description of what actually happened.
Docket Clerk receives 400 error when trying to complete the QC of the Simultaneous Reply Brief from Respondent.

**Screenshots**

Click on Complete in the QC area
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/aae02dab-ce29-4c2e-a8f0-fc1a5bd5a5ea)

Notice the error message
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/466298b0-a6f8-4e57-a04c-3dc0b958adf1)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by sutt0n** [comment]
I was able to replicate:

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/1116426/129393139-d7e736b0-b17c-4561-b434-2b8223b4f4bb.png">

**Comment by kkoskelin** [comment]
Steps to replicate locally:

1. Log in as petitions clerk, and save and serve a new petition.  
2. Assign irsPractitioner ("barNumber": "RT6789") as respondent
3. Log in as irsPractitioner@example.com (same bar number as above) and file a document: Simultaneous Reply Brief. Filing parties are "Respondent" _only_.
4. Log in as docket clerk.  Locate the Simultaneous Reply Brief in the Section QC Inbox and click the title to review.
5. Locate the heading "Who is filing this document?" and be sure that only "Respondent" is selected.
6. (open developer tools) Click "Complete"
7. See network error that complains about validation.

This bug seems to be related to Bug ustaxcourt/ef-cms#7958 and code in PR ustaxcourt/ef-cms-flexion#1453.  The file `web-client/src/presenter/actions/setFilersFromFilersMapAction.js` puts `form.filedBy` value into the `filers` array, but in this case the value is "Resp." which is _not_ a valid UUID.  The value of "filedBy" on DocketRecords seems to always be a string and never a UUID.

cc: @mrinsin

**Comment by kkoskelin** [comment]
See PR https://github.com/ustaxcourt/ef-cms/pull/1589 --

> Bugfix addresses ustaxcourt/ef-cms#8023 by rolling back changes made to fix bug ustaxcourt/ef-cms#7958, whose tests still pass.
> Code will need to be deployed to a production-like environment to be able to verify that both bug workflows are fixed.

**Comment by ttlenard** [comment]
No longer receiving the error. Thank you!

**Comment by ttlenard** [comment]
I also tested the bug flow in ustaxcourt/ef-cms#7958, and was still able to change the filed by successfully w/o receiving an error.
