### ISSUE TITLE
BUG: Unable to use the document feeder while using the scan feature in DAWSON

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8026]
**Describe the Bug**
Justine Miles and Santrisha Mapson in the Petitions section are unable to scan into Dawson particularly it continuously spins, and the image does not load.  

Shawn Norman checked her laptop, and she can scan in Adobe but having issues scanning into Dawson.  She is scanning in Adobe for the interim, but we need assistance with her not able to scan into Dawson.  Chris, Tenille, and Mike all attempted to do the workflow, but we do not have the same scanner that Justine does.  Here are some of our notes:

Notes from Chris:
I get the spinning behavior when using the automatic document feeder (ADF), but _not_ the flatbed option.
I get the same behavior on both Chrome and Edge
I can scan to Windows and Adobe normally using any method.
Developer tools in both types of scanning don’t report any obvious related errors, aside from the fact that using the ADF just hangs after calling dynamsoft.webtwain.initiate.js, and using the flatbed completes normally. It’s possible someone more developer-tool-savvy than me might be able to mine more info.
On my home computer (using Chrome), when I click the Change link for the Scanner selection in DAWSON, I get two options:
EpsonB3F6F5 (XP-7100 Series)
WIA - EpsonB3F6F5 (XP-7100 Series)

Selecting (b) – which is the only option I have on my Court laptop, aside from some weird Kodak scanner I’ve never heard of nor owned – results in not being able to use the ADF to scan into DAWSON.

Selecting (a) – Works just fine.

Conclusion: It looks like there’s potentially an issue with the Windows Imaging Application driver for a given scanner/printer being used when using the ADF in the DAWSON interface?

More thoughts from Mike:
Covering bases, Chris and I paired trying to troubleshoot and replicate the Scanning issue. I really don’t think it’s a DAWSON Dynamsoft issue, though we are overdue for upgrading that Software!
We were able to replicate the scanning woes if the scanner was prefixed with WIA-, but is for my scanner prefixed with TW- . This would be something to look for with the user who’s experiencing issues scanning. It really sounds like a laptop problem and NOT a DAWSON problem.

I suspect they have had intermittent issues scanning and they have just gone unreported as they have a tedious workaround. Additionally, the move from Webpack to Parcel did create serious issues with scanning that Cody worked to fix. This could be something else related to that. It’s really hard to know why this is happening for users as there isn’t really any feedback in the Console for what is happening — probably because the Dynamsoft application is gobbling up the error messages. I still think it’s advisable that we catch the software up to the latest as part of routine maintenance. And finally, I think we should address the CSP issue that some users are observing. I am not.

**Business Impact/Reason for Severity**

high

**In which environment did you see this bug?**

PROD, MIG

**Who were you logged in as?**

Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Using the Application

**To Reproduce**
1. Log in as a petitions clerk
2. Click on Document QC
3. Click on Start a Petition
4. Fill out the information on the left side of the screen.
5. Be sure that you select Scan.
6. Be sure that you do not select Flatbed (this works fine), its the feeder that isn't working.

**Expected Behavior**
Should be able to use the feeder to scan

**Actual Behavior**
A clear and concise description of what actually happened.
Error message appears when attempting to use the feeder to scan

**Screenshots**

This is from Justine
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/d3f17efb-d9ac-4916-b5c8-6113e1212f12)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mariahkannenberg** [comment]
Reach out to Justine or Santrisha. These are the specific users having these problems. 
Step 1 - Flexion engineers to try to recreate locally. Chris too. 
Dynamsoft update - Court to help facilitate update.

**Comment by mariahkannenberg** [comment]
Get TWAIN printer drivers for the two users as next step.

**Comment by mariahkannenberg** [comment]
@mmarcotte Looking into TWAIN drivers for the two court users

**Comment by mariahkannenberg** [comment]
Nothing more for Flexion to do on this. Mike waiting until next week when McVicker is back.

**Comment by mmarcotte** [comment]
Moved to https://github.com/ustaxcourt/ef-cms/issues/1627
