### ISSUE TITLE
Search: User Feedback

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8028]
As a search user, I want to be able to provide feedback to the DAWSON development team so that I can communicate what's working well and what isn't regarding search.

We would like to be able to collect data from search users regarding their DAWSON search experience in a way that allows us to collect data, analyze it, and make decisions based on that data.

## Acceptance Criteria

- Feedback mechanism does not interfere with other DAWSON operations
- Feedback mechanism can be accessed by any DAWSON user (internal only for now)
- Data received via feedback mechanism can be easily accessed by DAWSON project team
- Feedback mechanism is designed to collect data answering specific questions regarding usability, experience, and suggestions
- Feedback mechanism content and questions can be easily changed when desired

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
#### Search Feedback Survey 

1. How would you rate your experience with search? [binary response]
    * Good, I was able to find what I needed 
    * Bad, I was not able to find what I need or I was not able to use the search tool 

2. Overall, how easy or difficult was using DAWSON search? [linear scale]
    * 1 - Very easy to use 
    * 5 - Very difficult to use 

3. Please tell us more about your experience. [free text] 

If you are interested in sharing more about your experience, [set up a time to meet with us](https://calendly.com/ustc-user-research/ustc-user-interview-search). 
  

**Notes**
* The link routes to the scheduling app I use to set up user interviews/testing so people can schedule times to speak.  
* The scheduling app collects user name and contact info - so I did not include those questions in the form. I'm not sure if we'd want to collect that unless the participant elects to share more feedback.

**Comment by cholly75** [comment]
@klohman - here's a link to your survey in MS Forms: https://forms.office.com/Pages/DesignPage.aspx?fragment=FormId%3DffQzvB8vfUKKwjrrqKsOvTVbiWEK6y1AtToWYyLphJdUNE9USVM1NkxBNDJBQUFLQ1U4SzZVVUg3Mi4u%26Token%3D710f2eb37349426d8c0ed11ff1fcedbd

**Comment by klohman** [comment]
@cholly75 I don't have access to login to MS Forms. If that's how we are going to implement, can we talk about how to disseminate the responses? Maybe a daily export?

**Comment by cholly75** [comment]
@klohman Yeah, Forms lets me export to Excel - attached is an example

[https://app.zenhub.com/files/152320868/4b87d69e-1670-4fc7-bd11-591c0205c42c/download](https://app.zenhub.com/files/152320868/4b87d69e-1670-4fc7-bd11-591c0205c42c/download)

**Comment by cholly75** [comment]
@klohman 

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/1cc20ca7-8ec6-4b28-979a-7c7343188199)

**Comment by klohman** [comment]
@cholly75 Looks good! Is there a way to include the link to my calendar to schedule interviews?

**Comment by cholly75** [comment]
@klohman *sigh* remind me to tell you some time how much I hate snip n' sketch. :) Here's page 2, conveniently left off the initial shot.

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/2e135fc1-6d8f-43f4-b660-a3e9158c374c)

**Comment by klohman** [comment]
## Updated search page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8fb41768-0d60-4837-abb5-043446828b38)

* Add "Send Feedback" button to be displayed on all advanced search screens in header. 
* On click of button, open [MS Form page] in new tab 

@cholly75 Can you add the link to the official MS Form?

**Comment by cholly75** [comment]
@klohman Here's the "short URL" version - lemme know if we end up needing the long version:

https://forms.office.com/r/J1AHm7d3BE

**Comment by ttlenard** [comment]
This looks good to me!
