### ISSUE TITLE
SPIKE: Document decision to use a monolambda for API processing

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8030]
As a tech lead, so that I can understand the decision to use a monolambda with Express, I need to discuss and document the decision with folks who were here at the time that decision was made.

## Pre-Conditions

- [ ] A quorum of folks present who were present when the decision to employ a monolamda with express was made.
- [ ] Folks involved could spend a few minutes to prepare for the meeting by reading the notes that @adunkman has pre-[prepared here](https://github.com/ustaxcourt/ef-cms/pull/1508/files#diff-df8012a0760baa85ac4fbcc579f7ce6094aa9eaf58833116f6dcc2f88e600951).

## Acceptance Criteria

- [ ] Compile any and all thoughts to help document the decision to use a monolambda
- [ ] Timebox: 45min. 

## Notes

We're documenting [over here](https://github.com/ustaxcourt/ef-cms/pull/1508/files#diff-df8012a0760baa85ac4fbcc579f7ce6094aa9eaf58833116f6dcc2f88e600951) at the moment. So we could just add and revise that. @mmarcotte would be happy to be note taker.

**Comment by matthopson** [comment]
I'm fairly certain the notes in Sprint 43 document this decision, which - it appears much of this was used for the notes that were provided by Andrew.

https://github.com/ustaxcourt/ef-cms/pull/280

A search in slack for "delete the stacks" is one example of the suffering that was experienced early on with the previous infrastructure.

**Comment by cholly75** [comment]
@mmarcotte Is this what you were looking for, or is further discussion needed?
