### ISSUE TITLE
Performance: Users Getting Logged Out

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8033]
As a user, I would like to stay logged into DAWSON for the entirety of my shift so that I can use the system.

Court users from multiple departments are reporting a high degree of unexpected logouts in the system on a daily basis. Anecdotally, this number is between 5-10 times a day, and has increased in frequency.

- Ref. ustaxcourt/ef-cms#7629 for work previously done to address this
- Original story for timeout due to inactivity: https://github.com/flexion/ef-cms/issues/837
- Open story. Have we addressed? https://github.com/flexion/ef-cms/issues/7728

## Acceptance Criteria

- Conditions affecting user logouts are identified and entered into the backlog for remedy
- Logs are analyzed to determine potential root causes for unexpected user logouts.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- I believe there is some evidence to suggest this behavior is related to having multiple DAWSON tabs open? 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
8/27 - Another Court user (Susan Culbreath) reported getting logged out.  This person indicated that it always happened to her around 5PM ET.  She confirmed that she typically has 2 DAWSON tabs open.
