### ISSUE TITLE
Court: Add Identifier To Notes Tab When Case Notes/Judge Notes Exist

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8034]
As a court user, I would like the Notes tab to display an indicator when there are case notes populated for a case.

User feedback indicates that the Notes feature would benefit from an identifier similar to the one used for Tracked Items that displays when there are in fact Notes to read; this would both notify anyone that they should read the notes and drive user adoption of the Notes feature.

## Acceptance Criteria
- There is a visual identifier on the Case Notes tab if there are one or more Case Note or Judge Note entries attached to the Case and the logged in user has visibility to the Notes entries.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Option 1 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/84408ac5-439d-40c5-985c-23c13edee853)

## Option 2 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6b1ba7dc-942a-4f5f-a7e5-3563817400b0)

**Comment by cholly75** [comment]
Clarification: the indicator should be on the Notes tab, not the Case Messages tab (I referred to the Notes tab as the Case Notes tab, so I apologize for the confusion).

Also, option 2 is the preference - I like the post-it as opposed to the warning exclamation.

**Comment by cholly75** [comment]
Updated terminology in story to be more accurate

**Comment by cholly75** [comment]
@TomElliottFlexion 

Test Cases:

1. When there is an entry in the Case Notes for a case, if the logged in user has visibility to the Case Notes field then an indicator should display on the Notes tab.

2. When there is an entry in the Judge Notes for a case, if the logged in user has visibility to the Judge Notes field then an indicator should display on the Notes tab.

3. If there are entries in both the Case Notes and the Judge Notes for a case, if the logged in user has visibility to either field then an indicator should display on the Notes tab.

4. If there is an entry in the Judge Notes for a case and no entry in the Case Notes, and the logged in user does not have visibility to the Judge Notes field, then no indicator should display on the Notes tab.

5. If there is an entry in the Case Notes for a case and no entry in the Judge Notes, and the logged in user does not have visibility to the Case Notes field, then no indicator should display on the Notes tab.

6. If no entries exist for either Case Notes or Judge Notes for a case, then no indicator should display on the Notes tab.
