### ISSUE TITLE
BUG: The "submitted date" changes to today's date when a petitions clerk is Reviewing Petitions that have been submitted electronically

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8036]
**Describe the Bug**
The submitted date on an electronically submitted petition represents the date it was submitted, until a petitions clerk reviews the electronically submitted petition.  Once they review it, the submitted date will change to today's date.  (The filed date that is on the cover sheet in the actual uploaded document remains the correct date, but the date in DAWSON switches to Today's date once the Petitions clerk goes in to review it.  They are unable to edit this field to ensure that the correct date is input.

Question for the Chris- since we are seeing that the submitted date is whenever the petitions clerk reviews it, and NOT the actual submitted date from the petitioner...how important is this data field to have this info correct?  This most likely happened to all eFiled petitions?  Not sure how we could get the correct date back in there - it is on the cover sheet of the actual petition...is this stored anywhere else?

**Business Impact/Reason for Severity**
med severity???

**In which environment did you see this bug?**
PROD/MIG

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
This was reported from a court Petitions Clerk 

**To Reproduce**
1. Log in as a petitions clerk
2. go to the Section Document QC tab and find a petition that was electronically submitted that needs QC
3. Open the petition and click on the case info tab.
4. Notice the Date received date.  For my example, it was back in May 2021. Also notice the filed date in the document itself.
5. click on Review petition.  Notice that the Date Received switched to today's date on the Case Details tile.
6. Click Edit in the Case Details, and it will bring you back to be able to review the petition.
7. Now notice that the Date received show's today's date, and not the date that it showed before. This field is not editable, and you cannot get this date to go back to the date it was submitted.

**Expected Behavior**
Date Received should remain the date that the electronic case was received by the court. Not the date that the petitions clerk reviews it.

**Actual Behavior**
A clear and concise description of what actually happened.
Once a petitions clerk starts the review of the electronically submitted petition, the date received switches to today's date.

**Screenshots**

Case info tab - notice the date received. Also notice the filed date on the cover sheet in the document itself.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1a716222-f6a8-4349-963d-f339b5603631)

After you click review petition, Notice that the date received changes to today's date in the Case Details tile
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/d5936a70-140a-4a0a-85f8-c73e4abef664)

If you click edit on the case details tile, it will bring you back to the petition details, but you cannot get the date submitted to go back to the real date. The only pace it is correct is on the cover sheet of the petition.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/a78a7f01-ef19-47ee-bb95-2a68073e5acc)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
PR to address bug going forward: https://github.com/ustaxcourt/ef-cms/pull/1602

Migration coming in a separate PR.

**Comment by ttlenard** [comment]
I just tested this and I am still seeing the Date Received switch over to today's date: 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/52796936-e363-4e4f-b7b9-eb4ab4fc2480)

This petition was filed on 6/1:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/eb40287f-e063-4e30-9de4-73ffea1c324d)

I was in this record on MIG: https://app.mig.ef-cms.ustaxcourt.gov/case-detail/9368-21/documents/5034dd2d-47e4-4646-b645-8d4b6b867474/review

**Comment by matthopson** [comment]
@ttlenard This isn't on MIG. AFAIK, this fix is only on the test environment.

**Comment by ttlenard** [comment]
FACE SLAP.  I will retest on TEST...ahh geez...

**Comment by ttlenard** [comment]
This looks great on TEST.  Thank you Matt!! (and sorry for my mishap with the environments)
