### ISSUE TITLE
BUG: When editing a "Pre-DAWSON" docket entry, I get an error to "select a filing party", even though there is data in this field

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8038]
**Describe the Bug**

As a docket clerk, if I go into a docket record that was migrated into DAWSON, and attempt to edit the "Filed by" field, I get an error to "select a filing party" after I click save, even though I have data in this field.

This was reported by a docket clerk on the following docket record on PROD: Dkt. No. 592-18 Morgan Entry 33 and 37

I was able to recreate the issue on MIG, but as reported by the Docket clerk, it doesn't seem to happen ALL the time.  For example, I was actually able to update the docket entries that she listed on MIG, but when I attempted to update a few others in this case, as well as in other cases, I got the same error that she reported.

**Business Impact/Reason for Severity**
High Severity

**In which environment did you see this bug?**
PROD, MIG

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Go to a case that was prior to the Release of DAWSON. (I was in 592-18). Be sure that you are a docket clerk.
2. Click on the edit link next to a docket entry
3. Change the "filed by" field that currently says "See Filings and Proceedings" to something else like the petitioners name, or Resp.
4. Click Save
5. Notice that you received an error indicating that you need to add a filing party, even though you have data in this field.

**Expected Behavior**
Docket clerks should be able to edit the docket entry information without any erros.

**Actual Behavior**
A clear and concise description of what actually happened.
When a Docket Clerk edits the docket entry "Filed By" field, they get an error indicating that they need to add a filing party.

**Screenshots**

Pick any entry in the Docket record, and then click on edit link.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5b03b35c-b674-4b21-9705-3ccb11c653ae)

Update the Filed By field to something besides "See Filings and Proceedings". Click save. Notice the error:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/d2b669d0-fb68-4ab8-997e-d0fc79105f82)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edige

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
just waiting on a small typo fix

**Comment by ttlenard** [comment]
Tested this and it appears to be working as needed. Thanks!

**Comment by mariahkannenberg** [comment]
Ready for Mike's review. @mmarcotte
