### ISSUE TITLE
Opinion Search: OR keyword search

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8040]
As a Court employee, in order to locate the most relevant documents, I need to have more control over how my keyword search is executed.

## Acceptance Criteria 
(Note: AC should include non-standard testing, deployment, documentation or security requirements)
* User is able to search using multiple keywords/phrases using the equivalent of boolean operator “OR” and retrieve results containing EITHER keyword/phrase (including exact match) 
* When run on full data set, searches return expected results, do not return results outside of design scope; search remains performant

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - []  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [] Automated test scripts have been written
 - [] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [] Verify that language for docket record for internal users and external users is identical
 - [] New screens have been added to pa11y scripts
 - [] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [] Interactors should validate entities before calling persistence methods
 - [] Code refactored for clarity and to remove any known technical debt
 - [] Acceptance criteria for the story has been met
 - [] Deployed to any Flexion environment for UX Review
 - [] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
Test cases (identical to OR operator tests for Orders) - the following scenarios should all produce results matching title/contents containing the search query:

Keyword OR keyword in document title and contents

Keyword OR keyword in document title only

Keyword OR keyword in contents only

“Exact match Keyword phrase” OR keyword in document title and contents

“Exact match Keyword phrase” OR keyword in document title only

“Exact match Keyword phrase” OR keyword in document contents only

“Exact match Keyword phrase” OR “Exact match keyword phrase” in document title and contents

“Exact match Keyword phrase” OR “Exact match keyword phrase” in document title only

“Exact match Keyword phrase” OR “Exact match keyword phrase” in contents only

Keyword phrase OR “Exact match keyword phrase” in document title and contents

Keyword phrase OR “Exact match keyword phrase” in document title only

Keyword phrase OR “Exact match keyword phrase” in contents only

**Comment by kkoskelin** [comment]
@cholly75 per your instructions, the above requirements are the same as for that of Order Search.  These searches both ultimately use the same underlying search mechanism which already is supporting the OR operator, e.g.
` bananas | oranges`
We can probably send this one directly to PO review as there is no work to be done.  I can already see this 'OR' search working correctly in the court's migration environment.
