### ISSUE TITLE
BUG: Cannot open "Order or Notice" workflow from "Paper Filing" page

### ISSUE THREAD

**Issue by kkoskelin** [ustaxcourt/ef-cms#8055]
**Describe the Bug**
When viewing case detail, if you navigate to the "Paper Filing" page but then instead attempt to open "Order or Notice", the page goes blank and an error occurs in the console.

The workflow described below would entail first abandoning the form used to create a paper filing -- but it's easy enough to arrive there if you accidentally select the wrong item from the "Actions" menu.  A work-around would be to navigate *back* to the case detail and create an order or notice from there.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
local, mig

**Who were you logged in as?**
docketclerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
creating test data for another story in my local environment

**To Reproduce**
1. Log in as docketclerk
2. Open case detail page
3. From the "Actions" menu, click "Paper Filing"
4. While on the "Add Paper Filing" page, choose "Order or Notice" from the "Actions" menu.

**Expected Behavior**
Expected the "Order or Notice" modal to appear as it would had you made the selection directly from the Case Detail page.

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**
Video to reproduce: https://www.awesomescreenshot.com/video/5067072
Screenshot of error console:
![Screen Shot 2021-09-01 at 1 09 58 PM](https://user-images.githubusercontent.com/2445917/131721997-36a5c2e7-8c44-40f2-bda5-9646160e4ac9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Confirmed this is happening in PROD as well.

**Comment by ttlenard** [comment]
I tested this and I am no longer seeing the blank screen while navigating from Paper Filing to an Order. Thank you!
