### ISSUE TITLE
BUG: When Editing a docket entry, I get an error to enter a valid date, even when the date is valid

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8062]
**Describe the Bug**
This bug was reported by a Docket Clerk (Patricia Anchors) in Prod.

When a docket clerk edits a certain type of docket entry (Docket entry ustaxcourt/ef-cms-flexion#4 in 2332-21), the date field gives an error message that they must enter a valid date (even though it is a valid date).  What is happening is that the date has to be today or in the future, and cannot be in the past. If docket edits any docket entry where this date field is in the past, it will ALWAYS throw an error. 

Existing logic is in place when adding this type of docket entry the date must be today or in the future, but when editing this type of docket entry, this logic should not be in place.

**Question**
What document types include this date field when **adding** the docket entry?  We need to be sure that the date logic is removed when **editing** these types of documents that have this date field.  Maybe Kristen has this information?

**Business Impact/Reason for Severity**
No work around currently exists

**In which environment did you see this bug?**
PROD
MIG

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Editing a docket entry

**To Reproduce**
1. Log in as a Docket Clerk
2. Go to Docket 2332-21, and click edit for docket entry ustaxcourt/ef-cms-flexion#4
3. On the Actions Tab, put in today's date.
4. On the Document Info tab, put in the date of 05/10/2021
5. Click Save
6. You will get an error message indicating that you must enter a valid date.

**Expected Behavior**
Docket Clerks should be able to enter in a date in the past in this field while editing a docket entry.

**Actual Behavior**
A clear and concise description of what actually happened.
When entering in a date in the past, an error message occurs and states that the user must enter a valid date.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/48fe3bc0-62fd-4df0-bc01-756d4e1f226b)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by matthopson** [comment]
PR: https://github.com/ustaxcourt/ef-cms/pull/1651

**Comment by ttlenard** [comment]
Tested this and I am now able to edit a date in the past. Thank you!
