### ISSUE TITLE
BUG: Max character count error on document title displaying erroneously

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#8064]
**Describe the Bug**
When adding a paper-filing with event code MISC and leaving the description field blank, the character limit error is displaying as well as the validation error on the description field. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration

**Who were you logged in as?**
docket clerk 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
UX review of a story

**To Reproduce**
1. Go to case 
2. Add Paper Filing = MISC
3. Leave Description blank
4. Save 

**Expected Behavior**
Validation error on the description field should display. The character limit error for document title should not display. 

**Actual Behavior**
 the character limit error is displaying as well as the validation error on the description field display

**Screenshots**
If applicable, add screenshots to![Screen Shot 2021-09-10 at 10.13.41 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5b2a3a01-e2d8-4183-84be-66c36cb2c2ad) help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Confirmed only Description field validation error displays now

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/67b3e7b3-e224-43a0-98fd-45db6adce801)

**Comment by cholly75** [comment]
Confirmed character limit validation still fires correctly.

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/15a51b98-2a40-497b-aff0-824c133b0b2a)
