### ISSUE TITLE
BUG: Editing Paper-Filing with event code MISC before serving routes to wrong screen

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#8065]
**Describe the Bug**
When editing an unserved paper-filing with event code MISC (or MISCL), the app is routing to the "Edit Docket Entry" screen" (/edit-court-issued) instead of the Edit Paper Filing screen (/complete). 

Notes: Event code MISC is on both the internal events and court-issued events lists (intentionally). However, when this code is added as a paper-filing and saved, it seems to be routing incorrectly to the court-issued screen, which prevents users from editing the correct fields (and possibly causing other downstream issues). 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
migration 

**Who were you logged in as?**
docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
ux review/manual testing 

**To Reproduce**
1. Go to case 
2. Add Paper Filing with event code = MISC
3. Save Entry 
4. Go to Document QC > In Progress 
5. Click on MISC document link 

**Expected Behavior**
Editing a paper-filed document with event code MISC from the In Progress tab should route to the Edit Paper Filing screen. 

**Actual Behavior**
Editing a paper-filed document with event code MISC from the In Progress tab is routing to the Edit Docket Entry screen. 

![Screen Shot 2021-09-10 at 10.18.43 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a64e07d9-3f16-498e-ae41-c8b4622245ac)

![Screen Shot 2021-09-10 at 10.19.18 AM.png]
(https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dfc62c97-a92e-4a7c-863f-8def21042484)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
Tested this today 9-21-21, and now I am seeing the "edit paper filing" screen rather than the edit docket entry screen. Thank you so much for fixing this!
