### ISSUE TITLE
BUG: Migration blocked by overloaded segment

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8067]
**Describe the Bug**

When performing a migration in Production, one of the segments repeatedly timed out after 15minutes of Lambda execution, which is the maximum. It processed as many records as it could, but the segment has become too overloaded.

The `pk` that appears to be overloaded is `section-outbox|docket`. 

It appears the codebase really only looks for records that are seven days old, and it's quite likely that we have items in the database greater than that. Perhaps we could make use of [Dynamo TTL](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html)?

Here are [notes from the Deployment](https://github.com/ustaxcourt/ef-cms/wiki/2021-09-11-(Saturday)-Deployment) that failed.

Seems like it boils down to a business decision about whether or not we want to store these records long-term. We could archive them somewhere, or just rely on the application logs to determine what happened. I have flagged for @JessicaMarine and @cholly75 .

**NOTE:** We should also perform any fix for this situation for petitions as well.

**Business Impact/Reason for Severity**

Currently cannot deploy to Production without reverting a number of pull requests.

**In which environment did you see this bug?**

Production

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Deploying to production

**To Reproduce**

Unclear, I have performed a glue job to `ustc:develop`. We'll investigate that segment, and see if we can try to replicate migrating that segment.

**Expected Behavior**

Segment gets migrated properly and reliably under 15min.

**Actual Behavior**

Segment times out after 15minutes of execution trying to migrate the records.

**Screenshots**

**Cause of Bug, If Known**

Overloaded records in a DynamoDB partition with the pk of `section-outbox|docket`. 

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mariahkannenberg** [comment]
Blocking this until we get a business decision on deleting data from @JessicaMarine or @cholly75

**Comment by mariahkannenberg** [comment]
Moved to New - Mike taking ownership to resolve in Court envs.

**Comment by mmarcotte** [comment]
Solved with https://github.com/ustaxcourt/ef-cms/pull/1669 See PR notes for more context.
