### ISSUE TITLE
BUG: Orders that are 2 or more pages in Length have two different font types

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8068]
**Describe the Bug**
An Order that is 2 or more pages have two different font types.  The Text of the Order is Times New Roman, but the Header (where it has the docket # and page #) is Calibri (I think?)  These fonts need to both be Times New Roman to be consistent.

**Business Impact/Reason for Severity**
This is low severity

**In which environment did you see this bug?**
PROD
MIG

**Who were you logged in as?**
Law Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
This was reported by a Law Clerk

**To Reproduce**
1. Create an Order that is 2 or more pages in length
2. Click on Preview
3. Notice that the content of the Order is in Times New Roman, but the header on page 2 (and every page after that) is in Calibri Font.

**Expected Behavior**
Font should be consistent on all pages of Orders. Preferably all font should be Times New Roman.

**Actual Behavior**
A clear and concise description of what actually happened.
Font differences in Orders that are 2 or more pages in Length

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/f79db53b-e68d-4e22-bb15-23202c23fb0b)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]  Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
@mrinsin @codyseibert - still seeing this behavior on TEST:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/3502f71f-d6db-44e2-a57a-e3dc253086f0)
