### ISSUE TITLE
Court: Prevent parties from being served cases documents before the petition is served, even when other documents have already been served in the case

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8069]
As a party in a case, when a document has already been served before the petition, I need my petition to be served before any other documents in the case are served.

This is related to Story [8763](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8763).  8763 solved the issue with all brand new cases that didn't yet have any other document served in the case, but the existing cases where other documents had already been served before the petition, the AC did not pass, and documents were able to continue to be served.  This story is to address the cases that are in this status.

## Pre-Conditions
A case has a petition that has not yet been served, but other documents in the case have been served.

## Acceptance Criteria

- Parties in a case are served the petition before all other service

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
The following are the examples that I had indicated in the comments of 8763.

For the records that had served docket entries (ex. 12861-21, 14945-21)) when the petition was not yet served, I was able to:

File and EA by Private Practitioner (bullet ustaxcourt/ef-cms#6492 in 8763)
File an Answer by Respondent (bullet ustaxcourt/ef-cms#6493 in 8763)
When Private Practitioner updates their contact info, it will not update, but WILL update in ones where the petition is served (bullet ustaxcourt/ef-cms#6497 in 8763)
When IRS Practitioner updates their contact info, it will not update, but WILL update in ones where the petition is served. (Bullet ustaxcourt/ef-cms-flexion#9 in 8763)
I was able to edit docket entries, but I can't remember what document types generate a notice of docket change. (Bullet ustaxcourt/ef-cms-flexion#10 in 8763)
Was able to add the funky and new case to a calendared trial, but I didn't see a notice come through on either. Don’t' think that this would happen? Wasn't able to get this case back to NEW Status after I tested this. (20064-21) (Bullet ustaxcourt/ef-cms-flexion#11 in 8763)

Also of note: I checked the logs and I couldn't find service emails for these cases, even though a service date was in DAWSON.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
Resolved via ustaxcourt/ef-cms#8073
