### ISSUE TITLE
BUG: Court user is unable to serve documents

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8073]
**Describe the Bug**
Docket clerk indicated that they are unable to serve paper filing documents in this case: 15977-18 and also 25605-15W.  They are getting an error message that states "Document cannot be served until the Petition is Served".  In this particular case, the Petition was served back in 2018.

## Acceptance Criteria
* Parties in a case must be served the petition before all other service
* Once the Petition has been served, all other documents on the docket record can be served.
* Attempting to serve a document before the Petition has been served results in a validation error or warning to the user
* This applies to both legacy and non-legacy cases

Note:  UI validations/warnings originally implemented in ustaxcourt/ef-cms#8014 are still valid/approved

**Business Impact/Reason for Severity**
Critical - court users are unable to serve documents.

**In which environment did you see this bug?**
PROD
MIG

**Who were you logged in as?**
Docket

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Go to case 15977-18 or 25605-15W
2. Click on add paper filing
3. Notice that you get the error message "Document cannot be served until the Petition is served"
4. If you look at the docket record, there are multiple documents that have already been served on this case, including the petition.

**Expected Behavior**

Court should be able to serve documents if the Petition has already been served

**Actual Behavior**
A clear and concise description of what actually happened.
Court user is unable to serve documents in this case.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/4322bf7a-838b-469c-bc1f-a63d4444e53a)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
I do notice that in this case, there is not a capital "P" Petition on the Docket.  The Petitions in this case appear to have event codes "MISC" and "PTFR".  While testing the story [8763](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8763) last week, we ran into problems with still being able to serve documents when the petition had not yet been served.  It was explained in our DevOps call that the query was looking for ANY document that had been served already, so I am having a hard time with understanding why this is happening in this case this morning.

**Comment by kkoskelin** [comment]
For the sake of 8763, the story was specifically depending upon finding not just any document, but specifically a _Petition_ which had been served by looking in the docket entries for an item with event code `P`.

Indeed, code in the repository relies upon the Petition being filed with `P` code, and not `PTFR`.
Fixes needed:
* identify complete list of document codes which are Petitions (if more than `['P', 'PTFR']`
* update `Case.getPetitionDocketEntry` to successfully identify all petition types
* update `Case.isAssociatedUser` (search for `isPetitionServed`) to use the updated functionality above

**Comment by ttlenard** [comment]
FYI - We just got another report of Docket getting this error. Here is the docket #: 25605-15W

**Comment by ttlenard** [comment]
I copied these same test cases over from 8763.  I also copied over a few more test cases that had failed with those 9 cases that existed on Prod. These came out of a comment on 8763 as well. It was the comment related to Service workflows.

**1) Docket clerk adds docket entry when case status = NEW**

- Login as docket clerk
- Go to case with status = NEW
- Create, save, sign Order
- Add Docket Entry for Order
- Save
Expected results
- [ ] Warning messaging displays on Add Docket Entry screen
- [ ] Save and Serve button is hidden
On Save,
- [ ] Docket entry is added to Record but not served

**2) Docket clerk adds docket entry when case status = NEW and accesses document from In Progress tab**
Scenario 1
- Go to Document QC > In Progress tab
- Click on Order link
Expected results
- [ ] Warning messaging displays on Edit Docket Entry screen
- [ ]  Save and Serve button is hidden

**3) Docket clerk views unserved court-issued document in Document View**
- Scenario 1
- Go to Document View and select Order
Expected results
- [ ]  Warning messaging displays on Document view
- [ ]  Serve button is hidden

**4) Docket clerk views message with unserved court-issued document attached**
- Scenario 1
- Send message with Order attached
- View message
Expected results
- [ ]  Warning messaging displays on Message screen
- [ ]  Serve button is hidden

**5) Docket clerk adds paper filing when case status = NEW**
Login as docket clerk
- Go to case with status = NEW
- Add Paper Filing
- Save
Expected results
- [ ]  Warning messaging displays on Add paper filing screen
- [ ]  Save and Serve button is hidden
On Save,
- [ ]  Docket entry is added to Record but not served

**6) Docket clerk adds paper filing when case status = NEW and accesses document from In Progress tab**
- Scenario 5
- Go to Document QC > In Progress tab
- Click on paper filing link
Expected results
- [ ] Warning messaging displays on Edit Paper filing screen
- [ ]  Save and Serve button is hidden

**7) Docket clerk views unserved paper filing document in Document View**

- Scenario 5
- Go to Document View and select paper filing
Expected results
- [ ]  Warning messaging displays on on Document View
- [ ]  Serve button is hidden

**8) Docket clerk views message with unserved paper-filing document attached**

- Scenario 5
- Send message with paper filing attached
- View message
Expected results
- [ ] Warning messaging displays on Message screen
- [ ]  Serve button is hidden

**9) Practitioner updates their contact information and has case status = NEW**
- Login as practitioner
- Has at least 1 case with status = NEW
- Has at least 1 case with status = General Docket
- Update address/phone number
Expected results
- [ ]  Updated address/phone displays in UI in Practitioner DB
- [ ] Updated address/phone displays in case with status = NEW
- [ ] Updated address/phone displays in case with status = General Docket
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is added to docket record for cases (Open cases and Closed cases within last 6 months) without status = NEW
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is served for cases (Open cases and Closed cases within last 6 months) without status = NEW
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not added to Docket Record on any cases with status NEW
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not served on any cases with status NEW

**10) Admissions clerk updates practitioner contact info with case status = NEW**
- Login as admissions clerk
- Go to practitioner
- Has at least 1 case with status = NEW
- Has at least 1 case with status = General Docket
- Update address/phone number
Expected results
- [ ]  Updated address/phone displays in UI
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is added to docket record for cases (Open cases and Closed cases within last 6 months) without status = NEW
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is served for cases (Open cases and Closed cases within last 6 months) without status = NEW
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not added to Docket Record on any cases with status NEW
- [ ]  Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not served on any cases with status NEW

**11) File an Entry of Appearance by a Private Practitioner**
- Login as practitioner
- Has at least 1 case with status = NEW
- Attempt to File an Entry of Appearance
Expected Results
- [x] Warning messaging displays
- [x] User is unable to file an Entry of Appearance

**12) File an Answer by Respondent**
- Login as a respondent
- Search for a docket record with a status of NEW
- Attempt to File First IRS Document
Expected Results
- [x] Warning messaging displays
- [x] User is unable to file an answer

**13) Petitioner eFile's a document**
- Login as a petitioner
- Has at least 1 case with status = NEW
- Attempt to eFile a document
Expected Results
- [x] Warning messaging displays
- [x] User is unable to eFile a document

**14) Serve a document on a Case that doesn't have a Captital P Petition in it**
- Login as a docket clerk
- Go to 15977-18
- Click add Paper Filing
- Add a paper filing
- Serve the document
Expected Results
- [x] No warning message appears
- [x] User is able to Serve the document

**Comment by mariahkannenberg** [comment]
Blocked - Waiting for Court to finalize test cases. Once test cases are done, review w/engineers.

**Comment by ttlenard** [comment]
Here are the specific Docket entries that had issues. Will be good to test with these cases:

- 15977-18 or 25605-15W (these are older cases that do not have the captial "P" Petition).
- These are the cases in Prod where the petition wasn't yet served, but other documents in the case were:
- 11701-21
- 19688-21
- 3756-21
- 18628-21
- 22635-21
- 18624-21
- 3668-21
- 5687-21
- 17600-21
- 18629-21

**Comment by mariahkannenberg** [comment]
Unblocked - test cases complete.

**Comment by matthopson** [comment]
@cholly75 being able to ensure expected behavior for external users such as IRS Super user, is dependent on exposing the case status to the PublicCase entity. It wouldn't necessarily be displayed in the UI, but it would be part of the network request.

**Comment by matthopson** [comment]
PR, pending ☝️
https://github.com/ustaxcourt/ef-cms/pull/1668

**Comment by cholly75** [comment]
@matthopson Yes, this is fine.

**Comment by kkoskelin** [comment]
Please see:
https://github.com/ustaxcourt/ef-cms/pull/1668/commits/98348f184785eae8c15dcd1a43f40cfa11bbdd77
I have updated this PR expections of the v1 and v2 endpoints.
I am not altering the "contract", because frequently we *do* have values being returned for `contactPrimary` and `status`.  Only now they will be returned more frequently.
I believe this should not compromise any functionality of applications consuming the outputs of these endpoints.
cc: @cholly75 @mariahkannenberg @mmarcotte

**Comment by ttlenard** [comment]
All tests passed!  Thank you everyone for the hard work on this!  I made sure to test with some of those specific cases listed above, and logic seems to be working for each scenario identified!

**Comment by ttlenard** [comment]
We are awaiting IRS environment testing
