### ISSUE TITLE
Court: Public Terminal with Access to All Unsealed Documents/Cases

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#8075]
As the Court, in order to satisfy the requirements of Rule 27(b)(2), we need to provide a public terminal at the Courthouse in Washington, DC that provides a public user access to all unsealed cases and all unsealed documents within an unsealed case.

Rule 27(b) provides:
(b) Limitations on Remote Access to Electronic Files: Except as otherwise directed by the Court, access to an electronic file is authorized as follows: 
  (1) The parties and their counsel may have remote electronic access to any part of the case file maintained by the Court in electronic form; and 
  **(2) any other person may have electronic access at the courthouse to the public record maintained by the Court in electronic form,** but may have remote electronic access only to: 
    (A) The docket record maintained by the Court; and 
    (B) any opinion, order, or decision of the Court, but not any other part of the case file.

We need to create a new user role intended to be logged in only from the physical device on premise at the Court's location, that can access all unsealed cases and unsealed documents within an unsealed case, in addition to being able to utilize case, Order, and Opinion search.

## Acceptance Criteria
* Public terminal user may access a computer (IP specific) at the Courthouse in Washington to view:
   * All unsealed cases
   * All unsealed documents in an unsealed case
* No user may access this view outside of the US Tax Courthouse in Washington, DC
* Besides the additional docket entries being hyperlinked to the documents, the public terminal user should otherwise have the public view of the case :
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/001edc0d-b023-4c0c-af2f-3381e92000b5)
* Terminal User can view search functionality and results within the confines of the existing public view
* Terminal User can view Docket Record view as seen in screenshot
* All unsealed documents in Docket Record view are clickable hyperlinks that open the clicked document in a new tab
* Documents opened can only be viewed; there is no other functionality available
* Terminal User cannot navigate elsewhere in the DAWSON application
* Terminal User cannot be logged in from anywhere other than the physical device at the Court's location
* Special Testing: As this user should be functionally locked to the on-premise court device providing access, we will need to either spoof the arranged IP address for testing or devise another method of testing this prior to live deployment.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Questions
* How do we maintain login for this user from this location? Strong password - user w/own role - Cognito acct stores in PW manager. Like any other user.
* Should the terminal user have access to Order/Opinion search prior to general public/external user access? No.
* Are users given a login/PW? No, they're kept in PW manager. 
* What's the purpose of the login? There aren't AC for login. 
* Does it require the intervention of a court employee? No. 
* Is it a problem is someone snaps a photo of a kiosk screen. no.
* Is it browser based? Yes.
* Would we be removing print buttons? Yes, from docket record. 
* Anything else we need to disable? UI controls inside the app that don't meet AC
* Who will be responsible for deploying correctly? Folks at Court.
* What will device be? PC running edge at court. 
* Where will security be handled (outside of user role/permission)? By the court. No need to worry about security of machine and browser. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
@JessicaMarine - added a few specifics to AC, please review.

**Comment by cholly75** [comment]
Test Cases (quick):

1) Terminal User logs in, is presented with appropriate landing page
2) Terminal User can access Case Search
3) Terminal User can access Order Search (if externally available)
4) Terminal User can access Opinion Search (if externally available)
5) Terminal User cannot access Order Search (if not externally available)
6) Terminal User cannot access Opinion Search (if not externally available)
7) Terminal User searches for unsealed Case, is presented with results, can click link to Docket Record
8) Terminal User searches for sealed Case, case does not return in results
9) Docket Record view displays all unsealed elements of Docket Record as clickable links
10) Sealed elements of Docket Record are not hyperlinked
11) Links on Docket Record view open appropriate document in new tab
12) Terminal User cannot navigate elsewhere in the application other than the Search UI, Docket Record, and Document tabs.

**Comment by klohman** [comment]
Design TBD. Will need to pair with engineering on technical solution.

**Comment by mmarcotte** [comment]
Word back from CIO at the Court is that it would be no problem to lock down an IP Address for this Public Terminal. So we are good to go with this as a way to keep the terminal secure. 👍

**Comment by codyseibert** [comment]
We are waiting to hear back from a AWS support ticket to figure out why api gateway authorizers are not caching our policies.

**Comment by codyseibert** [comment]
@mmarcotte heads up, before deploying this to an environment, we need to create a record in the efcms-deploy-$ENV table that looks like so.  I'll try to remember to also put this on the batch PR when it is created.

```
{
  "ips": [],
  "pk": "allowed-terminal-ips",
  "sk": "allowed-terminal-ips"
}
```

**Comment by codyseibert** [comment]
AWS responded saying caching is working as expected when they create the authorizer using our same setup.  I do observe caching, but I am just curious why it takes about 4-5 requests until it is fully cached.  I think we can get this deployed at this point.

**Comment by mariahkannenberg** [comment]
Blocked by batch 10, but should be resolved today

**Comment by ttlenard** [comment]
@cholly75  Some testing feedback: Everything looked great, but I do have some feedback on test case 11 above.  When clicking on the docket record, the document does not open in a new tab, but instead opens in the current tab.

**Comment by liadmccabe** [comment]
@ttlenard from a usability standpoint, I would recommend that the document not open in a new tab.  There are a few usability and accessibility issues that could potentially arise from opening in a new tab, particularly if it's being done on a public terminal. These are the main ones that come to mind (information below borrowed from highly respected UX best practices NNgroup):

- More windows or tabs increase the clutter of the user’s information space and require more effort to manage (as this will be a public terminal, it is possible previous users will have forgotten to close out their tab and it could ultimately results in a lot of open tabs adding to visual clutter)
- New windows or tabs can cause disorientation, with users often not realizing that a new window or tab has opened.
- Less-technical users struggle to manage multiple windows and tabs
- New windows or tabs prevent the use of the Back button for returning to the previous page and force the user to spend effort to find their way back to the previous content.
- New windows or tabs are not inclusive for blind or low-vision users — especially when they open outside of the area that's magnified. 

Typically a good reason to open in a separate tab would be if the user will need to refer to that content in order to complete a task in another window, however that does not seem to be the case here.  So my recommendation from a UX perspective would be to open in the same tab.

NNgroup article for reference: https://www.nngroup.com/articles/new-browser-windows-and-tabs/

**Comment by ttlenard** [comment]
Thanks @liadmccabe . I appreciate the thoughts and perspectives you provided.  I talked with court folks on Friday and they said that historically, the typical users that use this terminal are reporters or researchers reviewing multiple cases and documents.  I think it will be great to discuss with @cholly75 today if he is back today.

**Comment by mariahkannenberg** [comment]
Lia's recommendation above is more focused on users who only need to look at one document, not the use case of being able to open multiple, navigate through them and then compare documents.

Keep an eye out for usability issues when users open a doc in a new tab.

**Comment by cholly75** [comment]
@ttlenard - Let's make sure the Terminal user tests get added to the test matrix; we will want to make sure we check this role when we do testing from now on.

**Comment by ttlenard** [comment]
@cholly75 will do - I'll get it added to the Test Matrix
