### ISSUE TITLE
BUG: Docket clerk is unable to create an Order in case 7100-21, receives 400 error

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8077]
**Describe the Bug**
This issue was reported by Docket.  When attempting to create an Order in Docket 7100-21, she continually receives a 400 error. We are unable to re-create this issue in MIG or in TEST.

She tried to complete this all throughout the day on 9/23 (9 different times), and continued to receive this error. I also verified in the Kibana Logs.

Are you able to access these logs? Here are all the 400 errors that she received.

https://search-info-4vkmt6q7gikrqmth5bknb4mj6u.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-23T11:00:00.000Z',to:'2021-09-23T17:00:00.000Z'))&_a=(columns:!(user.email,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f8384e80-2516-11eb-82a4-0f6df8788ac7,key:user.email,negate:!f,params:(query:'cheryl.crouse@ustaxcourt.gov'),type:phrase),query:(match_phrase:(user.email:'cheryl.crouse@ustaxcourt.gov'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f8384e80-2516-11eb-82a4-0f6df8788ac7,key:request.method,negate:!t,params:(query:GET),type:phrase),query:(match_phrase:(request.method:GET)))),index:f8384e80-2516-11eb-82a4-0f6df8788ac7,interval:auto,query:(language:kuery,query:'7100'),sort:!())

**Business Impact/Reason for Severity**
High?

**In which environment did you see this bug?**
PROD

**Who were you logged in as?**
Docket

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. In prod, log in as a docket clerk (it was Cheryl Crouse) who experienced this
2. Navigate to docket 7100-21
3. Click Create, select Order
4. She received a 400 Error.

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

The error message that Cheryl sent: 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/36e571fe-80b9-46f0-92ac-eeb517f60f6f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by rosiehsmith** [comment]
we found a little bit more info looking at the logs for whoever can pick this bug up
![image](https://user-images.githubusercontent.com/16403861/134587610-11c1b051-4128-40e5-9cc5-0538147b0a59.png)
with this query 
https://search-info-4vkmt6q7gikrqmth5bknb4mj6u.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-23T15:30:00.000Z',to:'2021-09-24T05:30:00.000Z'))&_a=(columns:!(user.email,message,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f8384e80-2516-11eb-82a4-0f6df8788ac7,key:level,negate:!f,params:(query:error),type:phrase),query:(match_phrase:(level:error))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f8384e80-2516-11eb-82a4-0f6df8788ac7,key:environment.stage,negate:!f,params:(query:prod),type:phrase),query:(match_phrase:(environment.stage:prod))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f8384e80-2516-11eb-82a4-0f6df8788ac7,key:user.email,negate:!f,params:(query:'cheryl.crouse@ustaxcourt.gov'),type:phrase),query:(match_phrase:(user.email:'cheryl.crouse@ustaxcourt.gov')))),index:f8384e80-2516-11eb-82a4-0f6df8788ac7,interval:auto,query:(language:kuery,query:''),sort:!())

**Comment by ttlenard** [comment]
@mmarcotte  I just got a report from Docket that this same issue that Cheryl was experiencing on the 23rd and 24th of September also happened to Stephen Currence  (Docket 17546-21). I checked the logs and was able to confirm.  

UPDATE: I actually just tweaked my Kibana query, and looks like Cheryl attempted again on the 28th, and Stephen attempted again on the 29th and had the same result.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/229dc606-ecbc-498a-bac4-f5bb04ae1b67)

**Comment by mmarcotte** [comment]
We were unable to replicate or find solid evidence in the logs to explain how https://github.com/flexion/ef-cms/issues/8976 happened. Somehow the docket entry got tagged with the `isPendingService` flag, but service did not complete. We couldn't find any information in the logs about the previous attempt. 

The last trace of the attempt was that the Work Item `work-item|9faa7809-6540-40d7-bc36-063830760f38` was created at `2021-09-23T13:20:51.336Z`, moments before the failures started. Cannot find any evidence in the logs as to what failed, so we are introducing this logger entry to help report failures whenever they happen. 

It's still curious why the flag wasn't unset in the catch block.
