### ISSUE TITLE
BUG: Opinion Content Unsearchable

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8078]
**Describe the Bug**
There are opinions which are not searchable via keyword/phrase in DAWSON due to the manner in which the PDFs were scraped for content upon upload. Based on analysis by @kkoskelin it appears that the method for scraping content from November 2020 until August 9 2021 was inserting spaces into the scraped content which is stored in s3. Accordingly, the indexed content for these documents consists largely of one- and two-letter words instead of the complete words in the original content.

We need to identify the problematic content and replace it with searchable content that accurately reflects the uploaded Opinions.

Analysis from Kris:

_"FYI I'm seeing this bugfix PR https://github.com/flexion/ef-cms/pull/8754

The pdf scraping logic and robustness is FAR from perfect.  We had written this code once, which resulted in the ingestion of PDFs directly from Blackstone whose words all ran together in one big string.  I think we can probably find bug reports for that behavior.  To fix that, we were introducing spaces.  However, it seems that non-Blackstone PDFs  would then produce broken words (extra spaces) as you've discovered.

The above PR addressed this.  Assuming that the blackstone PDFs to be scraped are far and few between from now on, we're unlikely to have those issues, I would hope.

The above PR was merged on August 9, 2021.
It reverses a change committed to the repository here https://github.com/flexion/ef-cms/commit/274bce689ba8442008b8dec39b0333372b23373d#diff-a91ea43ebd7cdd9d7bdb86de9bd729a063f8cb2da60be9c524357937ea5bbb91 in November 2020.

Documents 3 and 7 were ingested during this time.  Document 6 was ingested on August 23rd -- so that is consistent.

It is possible that there are many PDFs uploaded and ingested during this time also exhibit the same issues in their stored and indexed document contents like:
documentContents: "↵↵ 157 T.C . No. 3↵UNITED STATES TAX C OUR T↵B OB B Y LEE R OGER S, Pe titione r v. ↵C OM M ISSIONER   OF INTER NAL R EVENUE, R e sponde nt↵Doc ke t No. 17985-19W . File d  August 2, 2021.↵P subm itte d nine  c la im s (c olle c tive ly , the  c la im ) for a↵whistle blowe r a wa rd unde r I.R .C . se c . 7623 to the  IR S W histle blowe r↵Offic e  (W B O).  The   c la im  a s se rte d  tha t c e rta in individua ls ha d↵c onspire d to c om m it “ gra nd the ft through c o nve rsion”  of the  a sse ts of↵P’ s m othe r.  Afte r re vie wing P’ s c la im , a  c la ssifie r from  a n  IR S↵ope ra ting division re c om m e nde d tha t the  c la im   be  re je c te d be c a use  it↵fa ile d to m e e t thre shold c rite ria  se t out in the  re gula tions unde r I.R .C .↵se c . 7623.  The  W B O the n issue d P a  le tte r purporting to re je c t  the↵c la im  on a n a lte rna tive  ground, sta ting:  “ T h e  c la im  ha s be e n re j e c te d↵be c a use  the  IR S de c ide d not to pursue  the  inform a tion y ou provide d.”...

But it is also probably quite difficult to identify which docket entries these are.  I have some thoughts on how we might identify and address this, but it will involve some custom scripts to first search the system for problematic candidates, analyzing their document contents to see if they "look funny", and re-scraping.

--Kris"_

**Business Impact/Reason for Severity**
High - potentially a large number of opinions are affected in this way, and it needs to be remedied before going live with Opinion search.

**In which environment did you see this bug?**
MIG

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1) View Docket 17985-19 – Docket Entry ustaxcourt/ef-cms#6520 - Opinion dated 8/2/21, 157 T.C. No. 3
2) Use Opinion search to search for almost any exact string in the content portion of the document, including petitioner name "BOBBY LEE ROGERS"
3) Note that there are no matches found.
4) Analysis of content for this opinion in s3 provides the following content sample:

"↵↵ 157 T.C . No. 3↵UNITED STATES TAX C OUR T↵B OB B Y LEE R OGER S, Pe titione r v. ↵C OM M ISSIONER   OF INTER NAL R EVENUE, R e sponde nt↵Doc ke t "...

**Expected Behavior**
1) View Docket 17985-19 – Docket Entry ustaxcourt/ef-cms#6520 - Opinion dated 8/2/21, 157 T.C. No. 3
2) Use Opinion search to search for almost any exact string in the content portion of the document, including petitioner name "BOBBY LEE ROGERS"
3) Opinion 157 T.C. No. 3 appears in the search results

**Actual Behavior**
1) View Docket 17985-19 – Docket Entry ustaxcourt/ef-cms#6520 - Opinion dated 8/2/21, 157 T.C. No. 3
2) Use Opinion search to search for almost any exact string in the content portion of the document, including petitioner name "BOBBY LEE ROGERS"
3) Opinion 157 T.C. No. 3 does not appear in the search results

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Meeting with @mmarcotte on Monday to see if we can identify # of Opinions uploaded during the time this content parsing was in place.

**Comment by kkoskelin** [comment]
because we clearly have had situations in which we've both *added* and *removed* a commit that adds a space between parsed item strings within `scrapePdfContents`, I'd like to suggest that we collect those items in an array instead of string-appends (e.g. `string += ' ' + item.str;`).  We can then analyze the number of one-character or two-character tokens, which can drive whether we will then join all these tokens using an empty string or a string containing a single space.

**Comment by cholly75** [comment]
This is being tracked on the 18F board, closing here.
