### ISSUE TITLE
BUG: Trial Session Mapping Records Data Issue

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8079]
**Describe the Bug**

We attempted to address this a few times before, but we were unable to identify the fix. Instead we fixed the data on the server to resolve the problem.

It appears that the problem is due to a race condition. 

A [previous solution deleted the mapping](https://github.com/ustaxcourt/ef-cms/pull/1303/files#diff-6836aafcd66549093ae6efe88eb994aaead3dae5f9f01af5e304085496a4e07eR21-R40) records before recreating them -- attempting to ensure that multiple mapping records (what causes the error) cannot happen. However, some endpoints call this function multiple times in one API call. And since DynamoDB is eventually consistent, we end up with duplicate eligible case mapping records. 

NOTE: the difference of the timestamp -- they must be passing in different case information to the function when it gets called.

NOTE ALSO: to prevent the issue from creating a High or Critical Severity bug, the Court is [working on a fix to de-dupe the docket numbers](https://github.com/ustaxcourt/ef-cms/pull/1673) returned by the mapping records query. 

**Business Impact/Reason for Severity**

Medium / [Stopgap solution](https://github.com/ustaxcourt/ef-cms/pull/1673) has been created, but need to fix the underlying data issue.

**In which environment did you see this bug?**

Prod / Other

**Who were you logged in as?**

Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Trying to load a Trial Session
Querying the: `eligible-for-trial-case-catalog|<docket-number>` gsi1pk

**To Reproduce**

NOTE: Since this is a race condition bug, it may not happen every time
NOTE ALSO: Other endpoints call `createCaseTrialSortMappingRecords(...)` via helper functions. We need to solve for all of them. These may also cause the data issue. Here's a list of them:

* UpdateCaseAutomaticBlock
* checkForReadyForTrialCaseInteractor
* prioritizeCaseInteractor
* unblockCaseFromTrialInteractor
* unprioritizeCaseInteractor
* updateCaseContextInteractor
* updateCaseDetailsInteractor
* updateCaseTrialSortTagsInteractor
* deleteTrialSessionInteractor
* removeCaseFromTrialInteractor

1. Login as a docket clerk on `test` (or `mig`)
2. Navigate to a case (`5103-21` is one that triggered this error in `prod`) and change its Priority 
3. Perform a DynamoDB Query for gsi1pk: `eligible-for-trial-case-catalog|5103-21`.
4. Observe duplicate mapping records.

**Expected Behavior**

Should only have one mapping record per case type / `skPrefix`

**Actual Behavior**

Observing duplicate mapping records per case type / `skPrefix`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mmarcotte** [comment]
This could even be considered refactoring with https://github.com/ustaxcourt/ef-cms/pull/1673

**Comment by ujahio** [comment]
Going to close this "bug" as it has been converted to a devex task to be voted on. 

https://trello.com/c/3hcRPCta/1023-refine-stopgap-solution-that-addresses-duplicate-trial-session-mapping-records-data-issue
