### ISSUE TITLE
BUG: Websocket does not gracefully re-connect when there is network latency

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8080]
**Describe the Bug**
When network or connectivity issues interrupt a connection for a user that has an operation in progress waiting to be completed (ex.: setting a calendar, downloading cases for a trial session), the UI becomes non-responsive with no indication as to whether the operation has completed. Even if the connection is subsequently restored, the user session does not appear to pick up where it left off or provide an indication as to the current state of the operation.

In addition, for operations that require follow-up steps (ex.: printing paper service documents post-calendar set) this means that the user is effectively kicked out of the associated flow. 

Court users experienced issues when setting calendars for trials that had 50+ cases. Calendar Clerks had QC'd 50+ cases, and then clicked Set Calendar.  What resulted was the "Spinner of Doom".  They left it spinning for over 2 hours, but the Print Paper service screen never appeared on the UI, so they thought it was still "working" in the background.  After checking the the logs, all of the service emails did get sent, and the job completed, but the user had no way of knowing since the UI continued to have the spinner.  Chris and Tenille were able to recreate this behavior on MIG as well.  We think it may happen when there is network latency (the court was experiencing some network latency that day, and also Tenille's network sometimes bonks out in the afternoon.) because the Calendar clerk was able to set a large calendar the next day, and we were able to have success when testing in MIG as well.

Is this issue related to what was talked about in this SPIKE on the DevEx Board?  Seems there are other workflows in DAWSON that may also experience this "spinner of doom"?

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/08c667ac-973b-4a0a-966a-512692e117f9)

**Business Impact/Reason for Severity**
Medium

**In which environment did you see this bug?**
PROD

**Who were you logged in as?**
Petitions/Calendar

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Setting calendars

**To Reproduce**
1. Go to trial sessions and click on the NEW tab
2. Click on a city
3. Ensure that there are around 100 cases that have the QC checkbox filled in
4. Click Set Calendar
5. UI shows the spinner
6. Monitor the Kibana logs
7. Watch as all of the service emails go through (Bulk Email Params)
8. When it finishes, you will get the "Request ended: POST  /async/trial-sessions/...../generate-notices - this is how you know it is completed
9. Notice on the UI, that the spinner is still spinning and it won't stop to let the use know that the process is completed.

**Expected Behavior**
The user shouldn't get stuck on the "spinner of doom" when the process completes.

**Actual Behavior**
A clear and concise description of what actually happened.
The user experienced the "spinner of doom" and didn't know that the process completed, and they were not able to access the print paper service screen. (they ended up printing the information manually - now we know that we can access those PDF's in S3- thank you!)

**Screenshots**

Here are all of the trial sessions that got hung up when Calendar Clerk set the calendar on on Sept. 23rd
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5ec1db9b-7fdf-46c8-ba8c-72fde8791c15)

This was where I double checked that all of the service emails had gotten sent out:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/de626547-8740-402a-b0e3-63e87e707df7)

This is in MIG, after the calendar was set and the process was completed. I had also experienced the spinner of doom. There was nothing on the console showing under the Websocket tab:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/4d167677-4c29-4e88-8480-643c7d23ecc4)

This is in MIG, after the calendar was set and the process completed. I was looking to see if there were any errors, but I didn't see any?
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/b3087393-8dc8-4e63-8f6f-be84bf441f51)

One more from MIG:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/6fea8f40-bc39-404c-b923-59fd63341c3d)

Chris had a successful set calendar workflow in MIG and took some screen grabs for me for what the WS tab looked like for him:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/de223b1f-feaf-4c5f-af62-5a868fb899e7)

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/fbbc4b28-2e8b-476b-a19d-1897d6466455)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Addressed with ustaxcourt/ef-cms#8109
