### ISSUE TITLE
Petitions: Auto-Generate Notice of Attachments in the Nature of Evidence

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8087]
As a Petitions clerk, so that I may easily generate needed documentation , I need to have DAWSON generate a draft of a Notice of Attachments in the Nature of Evidence automatically when I indicate that one is needed for a case.

Currently, when a Petitions Clerk indicates that a Notice of Attachments in the Nature of Evidence (NANE) is needed for a case, they check the appropriate box at the time of paper Petition entry or QC of eFiled Petition. After the Petition is served, the Petitions Clerk must then manually create the notice via copying and pasting content from outside DAWSON into a blank Notice (via the order generator).

As this notice is standard text across all petitions, if the clerk indicates that the notice is needed we would like this notice to be automatically generated as a draft entry attached to the case upon Petition service, at which point the clerk can review, edit, delete, and add as a docket entry through normal existing process.

We anticipate additional stories to auto-generate other notices and orders in the same manner; ideally the framework for auto-generating the NANE can be extended to include other documentation.

## Acceptance Criteria
* If the Notice of Attachments in the Nature of Evidence box is checked when the clerk Serves the Petition, a Notice of Attachments in the Nature of Evidence (the NANE) is generated and saved as a Draft document at the time the Petition is served.
* After Case is created and before service of the petition, the UI indicates that NANE is pending generation
* The generated NANE is created with the standard Notice format (Case caption/docket number at the top followed by title and text of the notice, followed by the Clerk of the Court's signature)
* The title of the generated NANE is "Notice of Attachments in the Nature of Evidence"
* The **body** content of the generated NANE is identical to the attached document:
[https://app.zenhub.com/files/152320868/3b12ba1b-3d13-4237-8277-8e07cd375834/download](https://app.zenhub.com/files/152320868/3b12ba1b-3d13-4237-8277-8e07cd375834/download)
   - ETA: The Chambers Phone Number should be added in the Judge box in the upper half of the document, under the Judge name.
* The generated NANE can be interacted with in the same manner as any other Draft notice from the Drafts view.

## Test Cases
* Petitions clerk starts new petition, checks box for "Notice of Attachments in the Nature of Evidence" in the Case Info tab and completes all other required info and creates Case. NANE is not generated. UI reflects pending NANE generation. Petition is served; NANE is generated and appears as a Draft document attached to case.
* Petitions clerk starts new petition, checks box for "Notice of Attachments in the Nature of Evidence" in the Case Info tab; checks at least one other box for a notice/order that is not currently auto-generated; completes all other required info and creates Case. NANE is not generated. UI reflects pending NANE generation. Petition is served; NANE is generated and appears as a Draft document attached to case.

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/ff2715c3-be36-4762-97c2-8bfcda2e9d0e)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be ready for grooming.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by swongCO** [comment]
When a petition is being created, the user gets to the page where they're able to click "Serve" and the petition will be entered into the system. There is a notification component that lists the orders/notices needed that the user had selected in the previous step.

Here's the existing notification for reference:
![Existing notification of orders needed.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/c74acb69-515a-41e9-9782-f61caa512975)

The modified component will have these changes:
- Add a new section with the title "Orders/Notices Automatically Created in Drafts After Service" after the existing section
- Follow font style, alignment and spacing as the existing title
- In the new section, add "Notice of Attachments in the Nature of Evidence" as a line item
- Change the font weight of the line items in both sections from semi-bold to regular
- NOTE: as other stories regarding the orders are completed, they will move from the top section to the bottom one as line items
![Petition order notification.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3133bb3e-f676-4163-b2fe-a9eb0825c2bf)
https://www.figma.com/file/YY2nO1WyLFfZGuSJdejVRY/USTC-%7C-Petitions-%7C-Auto-generate-NANE-8993?node-id=2%3A9

**Comment by swongCO** [comment]
![Drafts tab counter 1.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/5cfd1bab-f46e-463f-9ad5-0a2f33b7a06e)
![Drafts tab counter 1-double digits.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/dc35ed95-2bdc-4ee2-ab37-a27545d1f8bf)
- When an order/notice is automatically created for the user, it will display in the Drafts tab in the navigation
- There will be an icon that displays the number of drafts currently in the tab
- Icon specs: shape=circle; size=16px; 1px outside border #005EA2; white background; text=Source Sans Pro Semibold, 13px, center alignment, letter spacing -5%, centered horizontally & vertically within circle
- The icon will allow for two digits
- The icon will follow the behavior as other icons in tabs (like Notes and Tracked Items)
- The icon will not display if there are no drafts
https://www.figma.com/file/YY2nO1WyLFfZGuSJdejVRY/USTC-%7C-Petitions-%7C-Auto-generate-NANE-8993?node-id=5%3A8

![Drafts tab counter 2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/c570bb13-eade-4b1d-8628-5f4ab347ce8e)
![Drafts tab counter 2-double digits.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/efac5dc1-97e3-4cfa-bde4-809ba8533f51)
- When the user clicks on the Drafts tab, the auto-created "Notice of Attachments in the Nature of Evidence" will be selected and displayed in the preview pane
- The NANE title will be pre-populated
https://www.figma.com/file/YY2nO1WyLFfZGuSJdejVRY/USTC-%7C-Petitions-%7C-Auto-generate-NANE-8993?node-id=5%3A10

**Comment by ttlenard** [comment]
**### Test Cases**

**1. Petitions clerk starts new Paper petition, Only checks box for "Notice of Attachments in the Nature of Evidence" in the Case Info tab and completes all other required info and creates Case. NANE is not yet generated, but the UI reflects a pending NANE generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition, STIN, and RQT under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button, and select a trial location.
- Next, Select the radio button that the fee was paid and indicate a payment date and method.
- Under the Orders/Notices Needed section, select the checkbox for "Notice of Attachments in the Nature of Evidence". Leave all other checkboxes unchecked.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with a new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] The "Notice of Attachments in the Nature of Evidence" should be below the above section header, and will be in regular font.


**2. Petitions Clerk serves the petition. NANE is generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there is 1 draft.

**3. The draft NANE is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [x] On the left hand side of the page under the Drafts, you should see a new "Notice of Attachments in the Nature of Evidence" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Notice should be in the standard Notice format (caption, US Tax Court, tax court seal, signature by Clerk of the court, etc.), and should include the standard body language that is here: https://app.zenhub.com/files/152320868/3b12ba1b-3d13-4237-8277-8e07cd375834/download
- [x] Petitions Clerk has the ability to Edit, Delete, Add Docket Entry, or View Full PDF.

**4. Add the NANE as a docket entry and Serve it.**
- Continuing from the previous test case, click "Add Docket Entry"
- Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print NANE for Paper Service" screen

Expected Results
- [x] NANE is added as a docket entry and shows as served
- [x] The number icon no longer appears on the Drafts tab


**5. Petitions clerk starts new Paper petition, checks boxes for multiple Orders as well as checks the box for "Notice of Attachments in the Nature of Evidence" in the Case Info tab and completes all other required info and creates Case. NANE is not yet generated, but the UI reflects a pending NANE generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition and STIN under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button, and check the box for "Order to show cause".
- Leave the Trial location blank. This will ensure that the checkbox is checked for "Order Designating Place of Trial"
- Next, Select the radio button that the fee was paid and indicate a payment date and method.
- Under the Orders/Notices Needed section, select the checkbox for "Notice of Attachments in the Nature of Evidence", and select one or two other Orders needed (doesn't matter which ones.)
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with 2 Section Headers.  One that states "Orders/Notices Needed" and new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] The Orders that you selected should be under the section Header "Orders/Notices Needed" and will be in regular font.
- [x] The "Notice of Attachments in the Nature of Evidence" should be under the section header "Orders/Notices Automatically Created in Drafts After Service", and will be in regular font.


**6. Petitions Clerk serves the petition. NANE is generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there is 1 draft.

**7. The draft NANE is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [x] On the left hand side of the page under the Drafts, you should see a new "Notice of Attachments in the Nature of Evidence" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Notice should be in the standard Notice format (caption, US Tax Court, tax court seal, signature by Clerk of the court, etc.), and should include the standard body language that is here: https://app.zenhub.com/files/152320868/3b12ba1b-3d13-4237-8277-8e07cd375834/download
- [x] Petitions Clerk has the ability to Edit, Delete, Add Docket Entry, or View Full PDF.

**8. Add the NANE as a docket entry and Serve it.**
- Continuing from the previous test case, click "Add Docket Entry"
- Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print NANE for Paper Service" screen

Expected Results
- [x] NANE is added as a docket entry and shows as served
- [x] The number icon no longer appears on the Drafts tab

**Comment by swongCO** [comment]
Minor updates to number counter specs in Drafts tab. Added mockups of double digits inside number counter.

**Comment by swongCO** [comment]
Updated title of new section to "Orders/Notices Automatically Created in Drafts After Service"

**Comment by cholly75** [comment]
@rosiehsmith @Absolutestunna @shumway-tm Looks great, one piece of feedback - can we get a new paragraph indent on the first line of text when we create the draft notice (see attached sample text for example)?
