### ISSUE TITLE
Petitions: Auto-Generate Order Designating Place of Trial

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8088]
As a Petitions clerk, so that I may easily generate needed documentation , I need to have DAWSON generate a draft of an Order Designating Place of Trial automatically when I indicate that one is needed for a case.

When a petitioner submits a petition but does not include the RQT form (Request for Place of Trial), the Court will designate a place of trial for them based on their ZIP code and address. In these situations, an Order Designating a Place of Trial is issued for transparency.

Currently, when a Petitions Clerk indicates that an Order Designating Place of Trial is needed for a case, they check the appropriate box at the time of paper Petition entry or QC of eFiled petition. After the Petition is served, they must then create the Order via copying and pasting content from outside DAWSON into a blank Order, after which DAWSON adds the appropriate header, caption/docket information, and title to the first page.

If the clerk indicates an Order Designating Place of Trial is needed, then when the Petition is served, we would like this Order to be automatically generated as a draft order in the case, at which point the clerk can review, edit, delete, apply a signature, and add as a docket entry through normal existing process. The generated draft will need to generate some content dynamically based on information present during case creation.

## Pre-Conditions
See 8993 for UX specs: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8993

## Acceptance Criteria
* If the Order Designating Place of Trial box is checked when the clerk serves the Petition, an Order is generated as a Draft document at the time the Petition is served.
* The generated order is created with the standard Order format (Case caption/docket number at the top followed by title and text of the Order)
* The title of the generated order is "ORDER"
* The content of the generated order is dependent on the selected value during case entry:
   - If the type of case is "Regular", the body content is identical to the attached document, excepting one value: [https://app.zenhub.com/files/152320868/7e6b0d29-b694-46e8-b4ae-d3e9f5baad0d/download](https://app.zenhub.com/files/152320868/7e6b0d29-b694-46e8-b4ae-d3e9f5baad0d/download)
       - The value for the [FILED_DATE] token in the content is derived from the filed date of the Petition
       - The value for the [TRIAL_LOCATION] token in the content is typically manually entered by the Petitions clerk when drafting the order, and chosen based on the petitioner or counsel's given ZIP code.
  - If the type of case is "Small", the body content is identical to the attached document, excepting one value:[https://app.zenhub.com/files/152320868/50b8d648-e200-4d0f-bff9-80896681fc9e/download](https://app.zenhub.com/files/152320868/50b8d648-e200-4d0f-bff9-80896681fc9e/download)
       -  The value for the [FILED_DATE] token in the content is derived from the filed date of the Petition
       -  The value for the [TRIAL_LOCATION] token in the content is typically manually entered by the Petitions clerk when drafting the order, and chosen based on the petitioner or counsel's given ZIP code.
* The generated draft order should not auto-apply the signature of the Chief Judge.  The clerk will do this.
* The generated draft order can be interacted with in the same manner as any other Draft order from the Drafts view (edit, delete, apply a signature, and add as a docket entry).

## Notes
* Clerks will manually have to enter the Trial Location. We would replace this token with [TRIAL LOCATION] in a red font or similar callout to let them know that they need to manually enter.
* Order Designating Place of Trial event code is "O"

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be ready for grooming.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Petitions clerk starts new Paper petition, Only checks box for "Order Designating Place of Trial" in the Case Info tab and completes all other required info and creates case. Order is not yet generated, but the UI reflects a pending Order generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition and STIN under the Documents section of the screen (do not upload anything for the RQT)
- Click on the Case Info tab
- Fill in the Date Received and Mailing Date 
- For the Case Procedure radio button, select Regular
- Leave the Trial Location blank, and check the box for Order Designating place of Trial
- Indicate that the Filing Fee was paid (add in payment date and payment method)
- Leave all of the boxes under the Orders/Notices Needed section unchecked.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with a new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] The "Order Designating Place of Trial" should be below the above section header, and will be in regular font.


**2. Petitions Clerk serves the petition. Order Designating Place of Trial is generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there is 1 draft.

**3. The draft Order Designating Place of Trial is the appropriate Order template for Regular proceeding types, is formatted correctly, and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [x] On the left hand side of the page under the Drafts, you should see a new "Order" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be "Order", etc.), and should include the standard body content that is here for a Regular tax court case (it should have the text applicable for a regular proceeding type): https://app.zenhub.com/files/152320868/7e6b0d29-b694-46e8-b4ae-d3e9f5baad0d/download
- [x] The Filed Date in the Order should be the served date of the petition
- [x] Trial Location should not be populated yet, but easily noticeable that updated data should be added there (red text?), and the Petitions Clerk should be able to manually add this information in when editing the draft Order. 
- [x] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF.

**4. Edit the Order Designating Place of Trial with the Trial Location, add it as a docket entry, and Serve it.**
- Continuing from the previous test case, click the Edit button to edit the draft Order.
- DAWSON will open up the Order Generator page.
- Update the Trial Location (in red text?) with the City, State of the closest courtroom to the Petitioner's home address
- Ensure that the font size/color is no longer standing out, and is the same as the rest of the body of the Order.
- Click Save
- Click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order Designating Place of Trial" screen

Expected Results
- [x] Order Designating Place of Trial is added as a docket entry and shows as served
- [x] The Order Event Code is "O" on the Docket Record
- [x] The number icon no longer appears on the Drafts tab

**5. Petitions clerk starts new Paper petition, checks boxes for multiple Orders as well as checks the box for "Order Designating Place of Trial" in the Case Info tab and completes all other required info and creates Case. Order  Designating Place of Trial is not yet generated, but the UI reflects a pending Order Designating Place of Trial generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition and STIN under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received and Mailing Date fields
- For the Case Procedure radio button, select small
- Leave the Trial Location blank, and check the box for Order Designating Place of Trial
- Check the box for "Order to show cause"
- Select the radio button that the fee was NOT paid. This will automatically check the box for Order for Filing Fee
- Under the Orders/Notices Needed section, select the checkbox for a few other Orders.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with 2 Section Headers.  One that states "Orders/Notices Needed" and new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] Some of the Orders (that have not yet had a story to be auto-created) that you selected should be under the section Header "Orders/Notices Needed" and will be in regular font.
- [x] The "Order Designating Place of Trial", and all other Orders/Notices that were selected that have been coded to be auto-created should be under the section header "Orders/Notices Automatically Created in Drafts After Service", and will be in regular font.


**6. Petitions Clerk serves the petition. Order Designating Place of Trial, and all other Orders/Notices that were selected that have been coded to be auto-created are generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there are drafts. This number should reflect the total number of draft Orders/Notices created.

**7. The draft Order Designating Place of Trial is the appropriate Order template for small proceeding types, is formatted correctly, and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [x] On the left hand side of the page under the Drafts, you should see a new "Order" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be "Order", etc.), and should include the standard body content that is here for small proceeding types: https://app.zenhub.com/files/152320868/50b8d648-e200-4d0f-bff9-80896681fc9e/download
- [x] The Filed Date in the Order should be the served date of the petition.
- [x] Trial Location should not be populated yet, but easily noticeable that updated data should be added there (red text?), and the Petitions Clerk should be able to manually add this information in when editing the draft Order.
- [x] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF

**8. Edit the Order Designating Place of Trial, add it as a docket entry, and Serve it.**
- Continuing from the previous test case, click the Edit button to edit the draft Order.
- DAWSON will open up the Order Generator page.
- Update the Trial Location (in red text?) with the City, State of the closest courtroom to the Petitioner's home address
- Ensure that the font size/color is no longer standing out, and is the same as the rest of the body of the Order.
- Click Save
- Click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order Designating Place of Trial" screen

Expected Results
- [x] Order Designating Place of Trial is added as a docket entry and shows as served
- [x] The Order Event Code is "O" on the Docket Record
- [x] The number icon no longer appears on the Drafts tab

**Comment by cholly75** [comment]
@codyseibert @TomElliottFlexion @shumway-tm - bit of a swerve on this previously reviewed story. The Court has changed direction and would like the FILED_DATE token to reflect the petition filed date as opposed to the served date as previously requested. I've created a new story to address this (#9487) for the other auto-generated docs that use this token. I was thinking that since this story has not yet gone to staging we can hold it to make the correction prior to going live with it, but if that's not the right way to handle this we can address with 9487. Thoughts?
