### ISSUE TITLE
BUG: Items unreliably getting removed from ES after removing an IRS Practitioner from Case

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8092]
Timebox:
* 1 day - going through the UI and deleting practitioners to reproduce
* 1 -2 days - looking through the code to see where a bug may potentially be happening

**Describe the Bug**

NOTE: This bug may be difficult to reproduce as it may involve a Race condition.

Recent deployments have exposed that sometimes records are remaining in Elasticsearch after they have been removed from Dynamo. So far every occurrence of this has been removing an IRS Practitioner from a Case. Two types of records have remained in ES

`efcms-user` records:

```
[
  'case|10870-19',
  'irsPractitioner|fbb65c48-6106-450f-8b8e-07b82b606e49'
]
[
  'case|10870-19',
  'irsPractitioner|66692668-2c07-442c-a10c-4575377aa7b7'
]
```

and these `efcms-user-case` records

```
[ 'user|fbb65c48-6106-450f-8b8e-07b82b606e49', 'case|10870-19' ]
[ 'user|66692668-2c07-442c-a10c-4575377aa7b7', 'case|10870-19' ]
[ 'user|593072d7-6b7e-4c70-a5ec-a466a01901b6', 'case|10870-19' ]
[ 'user|9a0b668b-993b-4e97-87fc-038106650cdb', 'case|16000-21' ]
```

are some examples, and if you search in ES you can find API calls where each of them should have been removed from ES.

* `Request ended: PUT /case-parties/10870-19/counsel/66692668-2c07-442c-a10c-4575377aa7b7` 

We also observed this in a recent `prod` deploy [as documented here](https://github.com/ustaxcourt/ef-cms/wiki/2021-09-18-(Saturday)-Deployment#missing-records-in-destination-cluster). 

**Business Impact/Reason for Severity**

Deployments will be challenging and unpredictable until this is resolved.

**In which environment did you see this bug?**

Prod / Mig

**Who were you logged in as?**

N/A 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Performing a Blue Green migration and comparing the counts of the Elasticsearch indices

**To Reproduce**

1. Remove an IRS Practitioner from a case
2. Look in Dynamo to ensure that the correct records are gone (see above pk/sk examples)
3. Search in Elasticsearch to see if the records are still present

NOTE: If you cannot predictably replicate this, you may have to look for a race condition causing this problem

**Expected Behavior**

Records should reliably be removed from Elasticsearch when removing Counsel from a case

**Actual Behavior**

Stale records remain in Elasticsearch

**Screenshots**

<img width="1807" alt="Screen Shot 2021-10-01 at 3 20 30 PM" src="https://user-images.githubusercontent.com/5023502/135675747-a28c60f1-e420-48be-838b-b42488027323.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by mrinsin** [comment]
The fix for this bug assumes that `getIndexedCasesForUser` is no longer called anywhere in the code. However, 7643 was the story in which `getIndexedCasesForUser` was deleted, therefore the PR for this fix will fail the build until batch 9 (https://github.com/ustaxcourt/ef-cms/pull/1624) has been merged into ustaxcourt:staging.
