### ISSUE TITLE
BUG: Using the highlighter tool on the document view tab causes a "Leave site?" pop-up to appear every time I click on a document

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8095]
Note - This bug could be split up if needed. 

It's ok to separate out the black background and the missing signature line. I've emailed the court user to see if I can get more info to see if we can recreate these behaviors. (T.L. 10/22/21)

**Describe the Bug**
This bug was reported by Judge Buch and Ann Murray.

This issue was occurring in Docket 13999-20. After using the highlighter to highlight some text in a document on the Document view tab, Ann gets the "Leave Site" pop-up now every time she clicks on documents in the document view tab.  Ann is also experiencing a black background in the uploaded minute sheet (docket entry ustaxcourt/ef-cms-flexion#13, and she cannot see that a signature was applied to an order. 

I was able to recreate the highlighter issues on TEST environment in docket 13999-20 and 14000-20.  I was NOT able to recreate the black background on the minute sheet, or the missing signature.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
PROD
TEST

**Who were you logged in as?**
buchsChambers1

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**

1. Go to docket 13999-20 in TEST (or any docket record).
2. Click on docket record document view
3. Click on the highlighter and highlighted some rows in the docket (I did docket index ustaxcourt/ef-cms-flexion#10). I also used the pen feature to circle some text.
4. Leave the text highlighted and click on a different document
5. You will get the pop-up modal asking Leave site?  
6. Click "Leave" and you will be able to go to a different docket entry.
7. Click on docket entry ustaxcourt/ef-cms-flexion#10 again, and get the pop-up modal again. (I get this every time I click on a document to view, even though I didn't edit anything)
8. Click Leave and it will return you to docket entry 10
9. You should still see the highlighted text and the circle. Use the PDF editor Eraser to remove them.
10. Click off docket entry ustaxcourt/ef-cms-flexion#10, you will still get the pop-up "Leave Site?" modal.

Note: Ann also experienced a black screen on the uploaded minute sheet, and she couldn't see the signature on the Order, even though others CAN see it. (See screen grabs below). I was unable to recreate this issue.

Some more notes: I tried logging out, clearing site data, clicking control F5, and I cannot seem to get the "Leave site?" pop up to disappear.  I also tested this on docket 14000-20 as well and experienced the same behavior.

**Expected Behavior**
Should be able to use the highlighter tools and not experience the continued "Leave Site?" pop-up.  Also, these highlights should NOT persist or be saved.

**Actual Behavior**
A clear and concise description of what actually happened.
The highlighted sections remain when viewing the document, and the Leave site pop-up comes up after each time that you click on different documents.

**Screenshots**

Examples of the text I highlighted in 13999-20
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2e528325-f16f-4cab-a507-66ab52378f76)

The Leave site? pop-up that comes up every time you click on a different document to view. (This happens in the docket record AND in the Drafts view.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1a124b45-6412-42c8-a83d-bdaf0be2fba9)

Here is what Ann sees when she views the Minute Sheet (Docket entry ustaxcourt/ef-cms-flexion#13 on PROD)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/e4cc0443-5831-4d25-8c90-eb8b4242de10)

Here is what Ann sees when she views the Order (Docket entry # 14 on PROD). Notice there is no signature showing for her, but if I view it, there IS a signature.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/337c18ed-8006-4b3e-bf4f-8920cf7963fa)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
On Wednesday's Standup, it was suggested to test to see if this behavior was happening on a Chrome Browser.  I tested it on Chrome and the PDF viewer tools are different.  See screen grab. There isn't a highlighter tool when viewing in Chrome.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/9cf4533e-2b8d-4ed0-9957-c099ad82bd80)

**Comment by kkoskelin** [comment]
It may be the case that the highlighter tool is available only to Windows users of Microsoft Edge. I tried to replicate it using Edge on MacOS but could not find any option to enable a highlighter tool.

**Comment by TomElliottFlexion** [comment]
We were able to reproduce the "Leave site" modal issue on a Windows 10 VM w/Edge (as well as Edge on MacOS). It seems this is the default behaviour of the Edge PDF renderer: editing a PDF (by adding highlighting or pen marks) and navigating away from it triggers a confirmation to make sure the user is aware that their changes may not be saved. 
To reproduce outside of DAWSON: 
1. Navigate to PDF in Edge (http://africau.edu/images/default/sample.pdf) 
2. Use tool (pen or highlighter) to draw on PDF.
3. Click the "back" button.
4. Notice "Leave Site?" confirmation modal.

**Comment by TomElliottFlexion** [comment]
We couldn't reproduce the PDF issues around the missing signatures or the black background. This may need its own bug with more steps to reproduce (PDF renderer and version, OS, Edge version) @cholly75 @ttlenard

**Comment by ttlenard** [comment]
@TomElliottFlexion I am ok with separating out the black background and the missing signature from this bug. I have emailed the court user that reported this and will see if I can get additional information about what version of Microsoft Edge she is using, and if she is using any PDF extensions on her Edge Browser. Thanks for diving in to this!

**Comment by TomElliottFlexion** [comment]
Questions for Monday: We _should_ be able to disable to edit toolbar entirely for the pdf previewer. Since the buggy behaviour stems from the native Edge PDF viewer, this may be our only option for preventing these modals. Is this a solution we want to explore? Does the Court make use of the built-in PDF editing tools? @cholly75 @ttlenard @liadmccabe

**Comment by ttlenard** [comment]
I received more information from Ann regarding the black screen and missing signature.  Her responses are the ones in red: 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/4cce742d-ed90-4e38-97c1-f1e8b5d3ba1e)

**Comment by mariahkannenberg** [comment]
Blocked - Need to decide if we're going to fix this bug, as it appears to be an issue outside of the system.

**Comment by cholly75** [comment]
Discussing solution and trade-offs w/ court stakeholders on 10/27

**Comment by cholly75** [comment]
Additional report this morning - petitions clerk scanned in a file, clicked the Add Comment button on the toolbar attempting to edit the caption. Now when clicking Create PDF on any scanned document or uploading any document, the first/second pages are blank, even in new cases.

@TomElliottFlexion can we discuss how we might be able to at least get the user's browser to forget about this so they're not stuck with the behavior once triggered?

**Comment by kkoskelin** [comment]
> Additional report this morning - petitions clerk scanned in a file, clicked the Add Comment button on the toolbar attempting to edit the caption. Now when clicking Create PDF on any scanned document or uploading any document, the first/second pages are blank, even in new cases.
> 
> @TomElliottFlexion can we discuss how we might be able to at least get the user's browser to forget about this so they're not stuck with the behavior once triggered?

So this is a different bug with a different cause?  Perhaps file it separately but link it to this with an "Edge PDF" label?  Seems like a recurring theme.

**Comment by cholly75** [comment]
Yep, I can do that.

**Comment by mariahkannenberg** [comment]
Remedy with 9105.
