### ISSUE TITLE
Workflow Continuation When Spinning Wheel Persists While Calendaring

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8100]
As a court user, so that I can continue to do my job, I need to be able to resume printing paper service documents for calendared trials when the spinner wheel does not return me to the UI .

Intermittently, though frequently, when when setting the calendar for a trial session, the user does not advance past the "spinning wheel" graphic presented at the time the operation is kicked off, despite operations appearing to complete (based on looking at logfiles). The result of this is that the next step of the workflow - printing paper documents for service, etc. - is unavailable for the user as they must refresh their browser screen or open a new tab to continue working in DAWSON, as the UI maintains the spinning wheel.

We would like a method for the user to continue the workflow once this occurs, or prevent it from occurring in the first place.

## Acceptance Criteria
* When the spinning wheel graphic persists past the point of operation completion, user is navigated to or can navigate to the appropriate place in the UI to continue printing paper service documentation.
* If the workflow operation itself has been interrupted or fails, user is notified.

## Notes
* Test cases and AC may need to be modified once the root cause of the issue is discovered.
* Depending on root cause, may need additional stories to implement fixes for other areas in the application

## Test Cases
* Court User adds cases to Trial Session, clicks Set Calendar. While calendaring, user presented with spinning wheel icon. Operation completes successfully, but spinning wheel persists in UI. User is presented/directed to UI for retrieving/printing paper documents associated with cases in session.
* Court User adds cases to Trial Session, clicks Set Calendar. While calendaring, user is presented with spinning wheel icon. Operation does not complete successfully, user is notified of same.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
1) Continue troubleshooting bug to identify root cause 
2) Re-write story w/specific w/out making assumptions of root cause ("break in connection")
