### ISSUE TITLE
BUG: Formatting issue on the title of the Notice of Change of Email Address on the Docket Record

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8101]
**Describe the Bug**
There is a formatting issue on the title of the Notice of Change of Email Address on the Docket Record. This is only occurring in the UI on the screens when an IRS practitioner is filing the first document in a case, and when a Private Practitioner is first filing an Entry of Appearance to get access to the case. The formatting of the title of the notice appears to be formatted correctly everywhere else.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
MIG

**Who were you logged in as?**
IRS Practitioner
Private Practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing functionality

**To Reproduce**
1. Preconditions: The case needs to have an unrepresented Petitioner, Intervenor, or Participant (The screen grabs that I show have all 3 associated with the case), and the case needs to be in any status besides NEW or Closed for more than 6 months.
2. Log in as one of the above parties and change and verify the email address. This will autogenerate a Notice of Change of Email Address for [party].
3.Log in as a Private Practitioner and navigate to the case
4. You should see the "Request access to case" button on the top left of the screen, and you should also see that the Notice of Change of Email Address for [party] has a formatting error where the "Addressfor" is combined. (See Screen grabs below)
5. After you click on "Request access to the case", you will notice that the title of the Notice of Change of Email address on the Docket record no longer has the formatting issue.
6. Go back to step 3, and instead of Private Practitioner, log in as and IRS Practitioner, follow the same steps, and you will see the same formatting issue on the "File First IRS Document" screen (see screen grab below)

**Expected Behavior**
"Addressfor" should not be combined on the title of the docket record when and IRS practitioner or Private Practitioner are viewing the docket record.

**Actual Behavior**
A clear and concise description of what actually happened.
"Addressfor" is combined on the title

**Screenshots**

Here is a screen grab of when a private practitioner is requesting access to case:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/05c10541-a8f0-4336-b6ce-5fde0e1b43cb)

Here is a screen grab of when an IRS practitioner is filing the first document in a case:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/0b6ac463-0658-46fd-8774-509e9d6f018f)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Confirmed in TEST
