### ISSUE TITLE
External: Order Search (Public User)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8102]
As a public, non-credentialed user of DAWSON, so that I can find specific Orders in the public record, I need to be able to search Orders.

## Pre-Conditions
ustaxcourt/ef-cms#8093

## Acceptance Criteria
* A public, non-credentialed user can access Order search
* Order Search UI for these users does not have internal "Feedback" button displayed in UI
* Clicking the Docket link from the Order Search results list for a case navigates the user to the public, non-logged in user view of the Docket Record in the same tab
* Clicking the Document link from the Order Search results list navigates the user to the Order in a new tab
* "Coming Soon" text is removed from Order link in the UI
* Appropriate boilerplate text added above search UI (similar to Case search boilerplate)
* Order search for the public user behaves the same way it does for internal court users w/r/t filters, operators, and controls, with an exception:
   * Sealed documents are never returned in Order search results
   * Orders belonging to Sealed cases are not returned in Order search results

## Notes
* We want to continue to hide this feature from the public user in the live environment until the Court has determined that it should be activated.

## Test Cases
* Public user accesses Order Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab **TL PASS (11/15/21)**
* Public user accesses Order Search, searches for sealed Order, Order is not returned in results list. **TL PASS (11/15/21)**
* Public user accesses Order Search, searches for Order in Sealed case, Order is not returned in results list. **TL PASS (11/15/21)**
* Public user accesses Order Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab. **TL PASS (11/15/21)**
* Public user accesses Order Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab. **TL PASS (11/15/21)**
* Public user accesses Order Search, searches for Order, results list is returned. User clicks on link to Docket record, Docket record is opened with public UI in same tab. **TL PASS (11/15/21)**

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by liadmccabe** [comment]
Engineers, in order to keep the design consistent across the platform,  please add the "how to search" box to public search as well. It currently is only available to internal search.

Also, please update boiler plate to include affiliated documents.  Please see verbiage below:

Anyone can search for a case in our system for cases filed on or after May 1, 1986.
- If you aren’t affiliated with a case, you will only see limited information about that case.
- Sealed cases and affiliated documents will not display in search results.

**Comment by codyseibert** [comment]
dev review completed on https://dev.ustc-case-mgmt.flexion.us/, everything seems good to me

**Comment by ttlenard** [comment]
As discussed in Standup, I have a few comments: 1) the AC mentions the Boilerplate text for Order search, but this appears the same as what it says for Case.  Maybe we can reference searching for "an Order" rather than a case on that first sentence and call it good?  2) I'm still getting the "wait 1 minute" warning while performing searches while testing. Is this something that we need to adjust now that we have already tested the search limitation story?

**Comment by cholly75** [comment]
@mrinsin - New behavior since introducing fixes for 9077 last week. Searching via public user for "facebook" as a keyword results in "Error, we're experiencing technical problems". I didn't see this last week when testing. Expected result should be 7 unsealed orders (based on comparative search in PROD). Thanks!
