### ISSUE TITLE
Search: Messaging for 429/Search Limitation

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8107]
As a DAWSON user, so that I understand why my search isn't returning results, I need appropriate messaging when search hasn't been executed.

Currently, the user messaging that returns when the server returns a response code of 429 is targeted at the individual user and originally developed when the user-specific limiting story was developed. With the impending go-live of public search and additional mechanisms in place to potentially limit searching on a system-wide basis, we would like the UI to reflect a broader, less user-centric message when these 429 responses are received.

## Acceptance Criteria
* When the search limit has been reached, the user is informed if a certain wait time threshold is met

## Test Cases
* Search triggers 429 response, UI reflects new messaging

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios have been refined to meet all acceptance criteria 
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by liadmccabe** [comment]
I think this is fine to move forward to engineering without needing immediate design work, but I would like to review what the new message says when it's developed, if someone could loop me in at that time.

EDIT to add:

Here are some potential options, but many need more context to make sure these make sense.  Bottom line, the messages should be clear in terms of what the problem is and what the user can do while making sure not to 'blame' the user.

Search is experiencing high traffic
Please wait 1 minute before trying your search again

This page isn’t working
Please wait 1 minute before trying your search again.

Cannot submit search
Please wait 1 minute before trying your search again.

Unable to load results
Please wait 1 minute before trying your search again.

Submit Search Failed
Please wait 1 minute before trying your search again.

**Comment by liadmccabe** [comment]
As per team consensus and UX best practices, this is the recommended message to be used and is now ready for engineering: 

Search is experiencing high traffic
Please wait 1 minute before trying your search again
