### ISSUE TITLE
External: Order Search (Private/IRS Practitioner)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8108]
As a private or IRS practitioner, so that I can find specific Orders in the public record, I need to be able to search Orders.

## Pre-Conditions
ustaxcourt/ef-cms#8093

## Acceptance Criteria
* A private/IRS practitioner and can access Order search
* Order Search UI for these users does not have internal "Feedback" button displayed in UI
* Clicking the Docket link from the Order Search results list for a case to which the private/IRS practitioner is not associated navigates the user to the public, non-logged in user view of the Docket Record in the same tab
* Clicking the Docket link from the Order Search results list for a case to which the private/IRS practitioner is associated navigates the user to the private practitioner view of the Docket Record in the same tab
* Clicking the Document link from the Order Search results list navigates the user to the Order in a new tab
* "Coming Soon" text is removed from Order link in the UI
* Appropriate boilerplate text added above search UI (similar to Case search boilerplate)
* Order search for the private/IRS practitioner behaves the same way it does for internal court users w/r/t filters, operators, and controls, with an exception:
   * Sealed Orders and Orders belonging to Sealed cases to which the private/IRS practitioner is not associated are never returned in Order search results
   * Sealed Orders and Orders belonging to Sealed cases to which the private/IRS practitioner is associated are returned in Order search results

## Notes
* We want to continue to hide this feature from the public user in the live environment until the Court has determined that it should be activated.
* Do we need a separate story for IRS practitioner, or would this work be tackled at the same time given that the rules would be the same? We can handle them together in this story. 

## Test Cases
* Private practitioner accesses Order Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab - **TL PASS (11/15/21)**
* Private practitioner accesses Order Search, searches for sealed Order in case for which the private practitioner is not associated, Order is not returned in results list. **TL PASS (11/15/21)**
* Private practitioner accesses Order Search, searches for Order in Sealed case to which the private practitioner is not associated. Order is not returned in results list.  **TL PASS (11/15/21)**
* **TL PASS (12-6-21) - TL FAIL (11/22/21) I used 20442-18 -** Private practitioner accesses Order Search, searches for sealed Order in case for which the private practitioner is associated, Order is returned in results list.  ** TL FAIL. I used 30219-12 (11/15/21)**
* **TL PASS (12-6-21) - TL FAIL (11/22/21) I used 11613-21 -** Private practitioner accesses Order Search, searches for Order in Sealed case to which the private practitioner is associated. Order is not returned in results list. ** TL - Shouldn't this one Say Order IS returned?  Order is NOT returned as of today. I used 21584-18 (11/15/21)**

* Private practitioner accesses Order Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab.  **TL PASS (11/15/21)**
* Private practitioner accesses Order Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab.  **TL PASS (11/15/21)**
* Private practitioner accesses Order Search, searches for Order, results list is returned. User clicks on link to Docket record for which the party is not associated, Docket record is opened with public UI  **TL PASS (11/15/21)**
* Private practitioner accesses Order Search, searches for Order, results list is returned. User clicks on link to Docket record for which the party is associated, Docket record is opened with private practitioner UI **TL PASS (11/15/21)**

* IRS practitioner accesses Order Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab **TL PASS (11/15/21)**
* IRS practitioner accesses Order Search, searches for sealed Order in case for which the IRS practitioner is not associated, Order is not returned in results list. **TL PASS (11/15/21)**
* IRS practitioner accesses Order Search, searches for Order in Sealed case to which the IRS practitioner is not associated. Order is not returned in results list. **TL PASS (11/15/21)**
* **TL PASS (12-6-21) - TL FAIL (11/22/21) I used 20442-18 -** IRS practitioner accesses Order Search, searches for sealed Order in case for which the IRS practitioner is associated, Order is returned in results list.  ** TL FAIL (11/15/21) - I used 30219-12 - IRS practitioner is now part of this case**
* **TL PASS (12-6-21) - TL FAIL (11/22/21) I used 11613-21 -** IRS practitioner accesses Order Search, searches for Order in Sealed case to which the IRS practitioner is associated. Order is not returned in results list. ** TL - Shouldn't this one Say Order IS returned?  Order is NOT returned as of today. I used 21584-18 (11/15/21)**
* IRS practitioner accesses Order Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab. **TL PASS (11/15/21)**
* IRS practitioner accesses Order Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab. **TL PASS (11/15/21)**
* IRS practitioner accesses Order Search, searches for Order, results list is returned. User clicks on link to Docket record for which the party is not associated, Docket record is opened with public UI **TL PASS (11/15/21)**
* IRS practitioner accesses Order Search, searches for Order, results list is returned. User clicks on link to Docket record for which the party is associated, Docket record is opened with IRS practitioner UI **TL PASS (11/15/21)**

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by liadmccabe** [comment]
Engineers, please update boiler plate to include language about affiliated documents:

Anyone can search for a case in our system for cases filed on or after May 1, 1986.
- If you aren’t affiliated with a case, you will only see limited information about that case.
- Sealed cases and affiliated documents will not display in search results.

**Comment by rosiehsmith** [comment]
In order to test with a sealed order on mig you can use docketNumber 30219-12 @cholly75

**Comment by ttlenard** [comment]
**As discussed in Standup:** 1) the AC mentions the Boilerplate text for Order search, but this appears the same as what it says for Case. Maybe we can reference searching for "an Order" rather than a case on that first sentence and call it good? 2) I'm still getting the "wait 1 minute" warning while performing searches while testing. Is this something that we need to adjust now that we have already tested the search limitation story?

**Additional items found after standup:** 3) both Private Practitioner and IRS Practitioner are NOT able to view sealed Orders  or Sealed cases that they are associated with.  I have some comments in the test cases section above.

**Comment by ttlenard** [comment]
Tested this again 11/22/21.  I am still not able to get search results to return for Orders in Sealed cases that I am associated with as a IRS practitioner or Private practitioner. Here are the steps that I am doing for the test cases.
1. Docket clerk adds counsel (I did PT4444 and RT6666) to a sealed case with no individual sealed documents.  I used docket 11613-21)
2. Docket clerk adds counsel (I did PT4444 and RT6666) to a sealed case that also has individual sealed documents.  I used docket 20442-18.
3. Log in as Private Practitioner6 (or IRS Practitioner 6).
4. Notice that you have those sealed cases associated with your account on your main dashboard.
5. Very via the Case search that you can search for these cases via the docket number.
6. Next, click on Order Search tab.  Enter docket number of these two cases, the Case titles, or you can also try adding in the case titles to the keyword search as well.  No results will appear.

**Comment by ttlenard** [comment]
Here is another test scenario that I ran through today, where I came up with a few issues.

Docket seals a Case without Orders and without counsel, serves an Order, and then a single counsel is added.  This new counsel attempts to search for the order
	
- No counsel, Seal, Serve, add counsel, search
		○ Used Docket 29314-21 
		○ No counsel on this case
		○ Docket seals case
		○ Serves order "Test for 9077"
		○ Adds Counsel
			§ PT4444
			§ RT6666
		○ Log in as PT4444 and perform search
			§ Case Search 
				□ Searching by docket case returns sealed case
				□ Searching by case title returns sealed case
			§ Order Search (logged in as Private practitioner 6)
				□ Searching by docket returned order
				□ Searching by case title had no return
				□ Searching by keyword/phrase ("9077" and "Test") had no return
                                    Searching by Judge (Foley) and date (11-23-21) had no return

**Comment by cholly75** [comment]
@mrinsin - logging in as private practitioner is returning order results in a sealed case to which they are not affiliated - Log in as private prac (any of them) in MIG, do an order search for either docket 21959-16  or the phrase "Judgment filed 3/18/21" and you will see. This docket is not affiliated with the private prac and is sealed.

**Comment by cholly75** [comment]
Further info - it appears that this behavior exhibits itself once "Unseal a Case" has been clicked on a sealed case, even though the case is not unsealed because of the presence of sealed individual documents on the case. So we need to make sure that these cases still do not appear in the order search for practitioners.

**Comment by ttlenard** [comment]
Some Feedback: 

Private Practitioner 6 is associated with these two docket #'s
20442-18 (this one has individual sealed Orders/docs and the whole case is default sealed)
11613-21 (this one has the entire case sealed - no individual docs sealed)

Both cases return in Order Search for this Practitioner (which is great), but I notice that I am not seeing the lock symbol for any of the search results when searching 20442-18.  I see the lock symbol for all of the Orders returned when searching 11613-21. See screen captures below.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/e6b9dbe5-83f5-4c27-b475-af57ee027091)

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/ea9cf6d8-6165-46e6-ac23-95c5c7239bd1)

**Comment by ttlenard** [comment]
The above issue appears to be a regression issue. I searched for this same case (20442-18) in Prod as a docket clerk, and I see the lock symbol on all of the documents.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/552d3a56-f41e-4367-94fa-a54fa6d3f392)

**Comment by cholly75** [comment]
@ttlenard in MIG does the docket clerk search also show the incorrect behavior (i.e., different behavior than in PROD)?

**Comment by ttlenard** [comment]
@cholly75 - in MIG, as a docket clerk, when doing an Order search for 20442-18, I do not see any lock symbols

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/513125e5-f8bd-42df-95ec-73e5a8229ab4)

**Comment by cholly75** [comment]
OK, then yeah - this is a regression bug affecting internal search as well. Good catch!
