### ISSUE TITLE
BUG: User clicking PDF Viewer icon when uploading petitions causes all scanned/uploaded docs to have incorrect pages

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8113]
**Describe the Bug**

While creating a case, a petitions supervisor attempted to use the Add Comment function in the Edge PDF viewer to edit a scanned document. After doing this, subsequently when the PDF is created, the created file replaces the first two pages of the PDF with a blank page and the second page of the document she was originally trying to edit the caption for.

NOTE: This behavior was reported by one person. As reproducing appears to trigger a permanent condition, I have not replicated this in pre-production as of yet. While ustaxcourt/ef-cms#8095 may address removing the toolbar entirely, the critical component of this particular situation is that we need to be able to get the user back to being able to upload and scan documents as normal.

Similar cause to ustaxcourt/ef-cms#8095 - interaction with Edit components on the Edge PDF Viewer toolbar

**Business Impact/Reason for Severity**
Petitions supervisor can no longer upload/scan in documents without this occurring.

**In which environment did you see this bug?**
PROD

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Reported by user.

**To Reproduce**
1. Enter a new Petition.
2. Upload or scan in a file for the petition.
3. Click the three dots in the PDF Viewer toolbar.
4. Click "Add Text"
5. Attempt to add text to the document.
6. Continue with case creation, attempting to scan/upload another document (STIN, etc.)

**Expected Behavior**
Scanning/uploading continues to behave normally, reflecting the correct document in its entirety when scanning/uploaded

**Actual Behavior**

Scanned/uploaded documents contain a blank first page and second page reflective of the document that attempted to be edited. Removing the erroneous PDF, closing out of the browser, and re-logging in and attempting a brand new case still results in this behavior.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
@TomElliottFlexion Tried it with the user reporting the issue, and there was no change in behavior. :/ Is there value in using me and my laptop as a guinea pig?

**Comment by cholly75** [comment]
More info - I'm able to repro the issue on TEST w/r/t the Petition - after adding text via the Reader, removing the PDF, then scanning in a new one I'm presented with just the comments I added in as the document when I click Create PDF. This continues to happen regardless of login/logout/cache follies that I tweak on my side.

**Comment by cholly75** [comment]
Also, the problem does not seem to persist across environments (MIG works fine for me using the same browser session).

**Comment by TomElliottFlexion** [comment]
After meeting with @cholly75, we've decided to try to replace or reset the affected user's PDF renderer, either with an Edge extension, or by reinstalling edge. This will require elevated permissions on a court laptop

**Comment by TomElliottFlexion** [comment]
Some notes for documentation: 

- Completely uninstalling Edge on Windows the traditional way is impossible even with higher permissions; it ships with Windows and so can only be modified. It is possible to work around this, but it’s something that OIS (?) would have to do (command line force uninstall) and it’s not clear that this would even fix the problem- it does not on MacOS.

- As a short term solution, there are a number of PDF browser extensions for Edge that could replace/augment the native Edge PDF rendering; ones like [Adobe](https://microsoftedge.microsoft.com/addons/detail/adobe-acrobat-for-microso/elhekieabhbkpmcefcoobjddigjcaadp) support PDFs in separate tabs, but no embedded (preview) PDFs. Open-source options like [this](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi) _do_ support embedded PDFS. UPDATE: Have yet to find a PDF extension that will work with the embedded  _preview_  PDFs (like the ones in the 'scan' flow of creating a new petition) specifically. One may not exist.

**Comment by TomElliottFlexion** [comment]
@cholly75 Longer term solution possibilities: 
- Disable the toolbar in PDF previews. This will not disable the markup functionality, but it will prevent users from create new markup
- Refactor to render PDFs using [PDFjs](https://mozilla.github.io/pdf.js/), the Mozilla PDF platform (which we already use to manipulate PDFs) @kkoskelin

**Comment by TomElliottFlexion** [comment]
More updates for posterity: 

- Completely reinstalling Edge from the command line in a Windows 10 VM does not resolve the issue. 
- There is another context menu that allows users to add markup text to a PDF by right-clicking and selecting "Add Text". This is independent of the toolbar despite offering the same capability, and so is not disabled when the toolbar is disabled. 
- Building on a previous update, hiding the toolbar does not disable the toolbar's functionality. This means that in some cases a user's toolbar settings may be locked-in after disabling the toolbar. They may not be able to adjust the zoom, rotation, or most commonly the single-page/side-by-side viewing setting. 
- Recommend refactoring to use PDFjs or another PDF platform to render PDFs. The Edge renderer is still undergoing updates and seems likely to cause further issues in the future. Disabling the toolbar may still be a good shorter-term bandaid.
@cholly75 @kkoskelin

**Comment by cholly75** [comment]
Addressing in ustaxcourt/ef-cms#8116
