### ISSUE TITLE
Hide MS-PDF Viewer Toolbar

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8114]
As a DAWSON user, so that I don't accidentally adversely impact my ability to see uploaded or scanned PDF files, I need to hide the default Microsoft PDF toolbar viewer in Edge.

The latest version of the Microsoft PDF toolbar introduces additional text editing and formatting capabilities. Unfortunately interacting with these causes inconsistent and incorrect behavior in DAWSON w/r/t viewing PDF files, for which there is currently no known workaround. 

To prevent this from happening in the future, we would like to hide the toolbar from the current PDF views in DAWSON, and replace the only two needed functionalities it contains - printing and saving the viewed PDFs - with custom buttons or links to do so.

## Acceptance Criteria
* Default MS-Edge PDF Toolbar viewer is hidden from view for DAWSON user in all cases where PDFs are shown in an application tab
* Documents rendered in their own, new tab may still display the MS-Edge PDF toolbar
* User has the ability to print and save shown PDFs from the UI as if they were using the Print and Save buttons on the MS-Edge PDF Toolbar

## Test Cases
* User creates a new case, uploads petition; petition uploaded and rendered correctly, toolbar is not visible. User can save uploaded petition and print uploaded petition
* User creates a new case, scans in petition, creates PDF; PDF created and rendered correctly, toolbar is not visible. User can save and print petition. (Repeat for other documentation in Create Case workflow)
* User calendars trial session, is presented with documentation to be printed for paper service petitioners; PDFs created and rendered correctly, toolbar is not visible. User can save and print all documents.
* User views a Docket record in the Document view and selects a document; PDF is rendered correctly, toolbar is not visible. User can save and print document.
* User creates new Order or Notice and views it in the Drafts view of the Docket record; Order is rendered correctly, toolbar is not visible. User can save and print document.
* User creates new Paper Filing for Docket; uploads or scans in document; document is rendered correctly, toolbar is not visible. User can save and print document.
* User creates new PDF Upload for Docket; uploads document; document is rendered correctly, toolbar is not visible. User can save and print document.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by TomElliottFlexion** [comment]
It will likely be difficult to mimic the current Print and Save functionality and create custom buttons. Recommend implementing a "View Full PDF" (in a new tab) button instead, where one doesn't yet exist. This will allow users to print and save from the new tab.

**Comment by cholly75** [comment]
Closing - will address with ustaxcourt/ef-cms#8116
