### ISSUE TITLE
Implement Alternative Solution for PDF Rendering in DAWSON

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8116]
As a DAWSON user, so that I can interact with PDF files in a safe way, I need an alternative to the Microsoft Edge PDF viewer.

The latest version of the Microsoft Edge PDF viewer introduces additional text editing and formatting capabilities. Unfortunately interacting with these causes inconsistent and incorrect behavior in DAWSON w/r/t viewing PDF files, for which there is currently no known workaround. 

To prevent this from happening in the future, we would like an alternative solution for rendering and interacting with PDF files in the DAWSON application.

This story attempts to address the issue documented in ustaxcourt/ef-cms#8113 

## Acceptance Criteria
* PDF interactions in DAWSON remain functionally similar to the current state (at minimum, print and save capabilities remain)
* The Microsoft Edge PDF Viewer no longer is visible or usable in the DAWSON UI
* Navigational elements present on current UI remain in place (The links that appear contextually in the rendering frame)
* Implementation of solution is coded behind a feature flag, allowing viewer switching between current version and alternate solution

## Notes
* Comprehensive solution will require a large amount of regression testing in Court environments and Court laptops.

## Test Cases
* User creates a new case, uploads petition; petition uploaded and rendered correctly, MS toolbar is not visible. User can save uploaded petition and print uploaded petition
* User creates a new case, scans in petition, creates PDF; PDF created and rendered correctly, MS toolbar is not visible. User can save and print petition. (Repeat for other documentation in Create Case workflow)
* User calendars trial session, is presented with documentation to be printed for paper service petitioners; PDFs created and rendered correctly, MS toolbar is not visible. User can save and print all documents.
* User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new Order or Notice and views it in the Drafts view of the Docket record; Order is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new Paper Filing for Docket; uploads or scans in document; document is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new PDF Upload for Docket; uploads document; document is rendered correctly, MS toolbar is not visible. User can save and print document.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by kkoskelin** [comment]
One possible avenue of research: https://www.pdftron.com/blog/react/how-to-build-a-react-pdf-viewer/
An implementation in Vue using pdf.js directly: https://codesandbox.io/s/llble?file=/src/components/PdfReader.vue

**Comment by TomElliottFlexion** [comment]
Requires `setup-pdfjs-express-viewer-flag.sh <ENV>` to be run to set up the requisite feature flag.

**Comment by cholly75** [comment]
@TomElliottFlexion - Just checked again as per our conversation last week about scaling - looks like the issue is still present where the new renderer is displaying differently scaled/blurred image of the PDF.

Example from 8079-21:

PROD:
 ![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/eeb8c930-6662-402a-b28e-247a93bcdd1f)

MIG:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/5ee204ff-c8c1-4b61-8654-ce9f7e6ed606)

Will continue testing. Thanks!

**Comment by ttlenard** [comment]
I notice that the default zoom level is 114% when viewing on the docket record, and 79% when QCing a doc.  I was playing around with the zoom and found that if you jump to 125% it looks clearer.  Also while poking around, I notice that the "fit to page" option in the zoom level menu takes you to the 114% (document view) or 79% (document QC view) zoom level. Is this in the default view settings somehow?  Could this be why it is appearing blurry?  These are just some thoughts and observations that may be helpful?

**Comment by TomElliottFlexion** [comment]
Thanks Tenille! We'll look into a default zoom for the renderer. Currently, this again seems to be a Windows specific issue

**Comment by ttlenard** [comment]
There appears to be an issue with the PDF's retaining the data that was entered and saved in the form fields.  This is occurring on both MIG and TEST.  Not sure if this has anything to do with this story?

1. log in as a petitioner
2. Upload a STIN and a Petition that has data typed in via the form filler (Chris and I tested by downloading the form from DAWSON and filling it out, saving it, and then uploading it, as well as using existing saved PDF's)
3. On the Preview screen before you submit, click on the Petition and the STIN urls to preview before submitting.
4. Notice that you will see all the data that you entered in the form
5. Upload the documents to create a case
6. Navigate to your newly created case and click on the petition link
7. Notice that the data that was in the form fields is gone when viewing the uploaded petition
8. Log in as a petitions clerk - notice that there is no data in the form fields when viewing as a petitions clerk either.

*Note: Chris and I tested this multiple times, and sporadically we were able to get some of the data that we entered in the form fields to appear after upload.  It was either some random data would appear in the form fields, or no data.

**Comment by ttlenard** [comment]
More updates re: my comment above.  This appears to only be happening on Microsoft Edge. I was able to successfully see the data in PDF form fields if the petition and STIN were created, saved, and then uploaded via Chrome or Firefox Browsers.

**Comment by ttlenard** [comment]
Another update: I was wondering if this was also now occurring on PROD, and I did find a case that had a blank petition, with boxes checked...this was common behavior that I found while testing in Edge.  The case in PROD that I think is exhibiting this same issue is: 32035-21.

**Comment by ttlenard** [comment]
Just got off a call with @TomElliottFlexion . We went over some additional test results.
1- Printing or Print to PDF generates a very blurry image
2 - Save generates a nice and clear PDF

**Comment by TomElliottFlexion** [comment]
Note- Still requires `PDF_EXPRESS_LICENSE_KEY` env variable to be set in all environments

**Comment by cholly75** [comment]
Keeping the framework built but maintaining the feature flag as "F" as the JS solution here does not meet the court's needs.
