### ISSUE TITLE
BUG: Filed and Served Stamp doesn't appear on the page

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8118]
**Describe the Bug**

Looks like some scanned documents are causing the file and served stamp to fall outside of the page. Interestingly, you can see that it was added in the page preview pane (Chrome PDF Viewer). So, it's getting added, but the location is off.

**Business Impact/Reason for Severity**

It's important to be consistent for indicating when a document has been filed and served.

**In which environment did you see this bug?**

Prod / Test

**Who were you logged in as?**

Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Support Ticket

**To Reproduce**

1. Login as a docket clerk
2. File and serve a copy of the PDF available on test in the documents bucket `537e6179-210e-42da-81bc-0ebd7ae23b50`
3. Observe that the Filed And Served with Date doesn't get added to the right place at the bottom of the page. It might be falling off the page.

**Expected Behavior**

Filed & Served should consistently appear at the bottom of documents

**Actual Behavior**

Filed & Served stamp does not appear visible, except for in the preview pane

**Screenshots**

![image (8)](https://user-images.githubusercontent.com/5023502/139739667-217885c2-c92b-457a-847e-07ec3720079d.png)

![entered-and-served](https://user-images.githubusercontent.com/5023502/139739741-1679c5fd-9059-4c52-8d00-ebbfbebb212b.png)

<img width="1789" alt="Screen Shot 2021-11-01 at 10 52 59 AM" src="https://user-images.githubusercontent.com/5023502/139739829-25ddb9a3-a3c6-475b-be48-c22fa12361cf.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by kkoskelin** [comment]
The PDF document in question was revealed to contain read-only form fields.
It is believed that the clerk who scanned the paper document possibly opened the PDF in an editing tool and placed these large "checkbox" fields to cover streaks and imperfections that resulted from some process of printing/scanning/copying.
These edits did indeed have the effect of making the document look much cleaner.
However, they had the unintended effect of interacting with placement of signatures and served date stamps, by obscuring them as the form fields were "above" the layer on which the signatures and stamps were placed.
Strategy is likely to be attempting to either flatten the pdf form or remove the form fields entirely if possible.

**Comment by kkoskelin** [comment]
https://github.com/ustaxcourt/ef-cms/pull/1793

**Comment by ttlenard** [comment]
I tested this on 11/16/21 and I could see the Entered and Served stamp for the SDEC document that is in 11883-21. I'd say this is fixed. Thank you!
