### ISSUE TITLE
BUG: How to Merge PDF help document does not appear to be 508 compliant

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8127]
**Describe the Bug**
As a petitioner, when I open the "Learn more about how to merge files into one PDF" link https://app.test.ef-cms.ustaxcourt.gov/aecece6938ab09496720.pdf, a help document opens and it appears that this document is not 508 compliant.  I used the default narrator app that is installed on my court issued laptop, as well as Edges "read aloud" functionality on the PDF that opens, and some of the content is not getting recognized with these tools.

It appears that the help document has steps 1 and 2 as screen grabs, but these steps are not numbered, there is no alt text available on these two screen grabs, and there is no written instructions to accompany the screen grabs.  Screen readers do not recognize the screen grabs and they skip over these.

The first numbered step in the document is ustaxcourt/ef-cms#6493. Number 1 and number 2 steps are not identified in the document.

There are additional screen grabs in the document that do not have alt text or associated text to help explain what the screen grab is showing.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod, test, Mig

**Who were you logged in as?**
Petitioner, Private Practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing

**To Reproduce**
1. Log in as a petitioner or Private Practitioner
2. Click on start a case
3. Under the Accordion Menu that has the instructions for creating a case, click on Prepare the petition  
4. Click on link for the "Learn more about how to merge files into one PDF"
5. Open a screen reader tool and notice that it doesn't recognize the screen grabs that are in this document.

**Expected Behavior**

When using a screen reader tool, you should be able to understand what is in an entire document.

**Actual Behavior**
A clear and concise description of what actually happened.

The screen reader tools skip some screen grabs

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/83c6cf17-8984-4b97-8584-84e41dc9bc0a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
We will fix this PDF on the court side and have it replaced in S3 so that multiple links across the website/application point to the corrected version.
