### ISSUE TITLE
BUG: The "Learn More about Searching in DAWSON" help guide does not appear to be 508 compliant

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8129]
**Describe the Bug**
The help document that a user selects for searching in DAWSON does not appear to be 508 compliant.  If you download the PDF, it appears to be one big image, rather than text, so this makes it so that a screen reader cannot read it.  https://dawson.ustaxcourt.gov/ff8e9bc494cf3cfbb6f7.pdf

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
PROD, MIG, TEST

**Who were you logged in as?**
Public user, internal court user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing

**To Reproduce**
1. Go to the advanced search screen
2. Click on Order or Opinion Search tabs
3. Click on the "Learn more about searching in DAWSON link"
4. The document will open in a new tab.  You can attempt to have screen readers read the document here, but you can also download and save the document as a PDF.
5. I used the default "Narrator app" that is installed on my court computer, and when you use this, the narrator will select the text as it reads. Notice in my screen grab below, that the entire help document is in one big blue box.  It seems like this help document is one giant image?  I am not seeing any alt text associated with this document either.

**Expected Behavior**
Documents that are available in DAWSON need to be 508 compliant

**Actual Behavior**
A clear and concise description of what actually happened.
I don't think this document is 508 compliant.

**Screenshots**
This image shows the narrator app that has selected one giant image in the help doc, rather than being able to read the text.  Seems like it is one image?  You can also see that I ran the accessibility check on the document and it is full of issues.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1269ea47-4de5-4a47-844c-852be8c8080d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by mariahkannenberg** [comment]
Kristen created the document - could be in Figma. Reach out to Kristen.

**Comment by liadmccabe** [comment]
Here is the figma file: https://www.figma.com/file/GAcqY58Q2xJT8zT8jSMHFe/Search-Redesign?node-id=1282%3A5167

**Comment by cholly75** [comment]
Court is going to regenerate documentation in accessible manner and will create a new story to replace the DAWSON instances of noncompliant documentation.

**Comment by cholly75** [comment]
Closing, will address in ustaxcourt/ef-cms#8160
