### ISSUE TITLE
Ops Request: Onboard New Judges

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8145]
As a new judge to the Tax Court, so that I can use DAWSON, I need to be recognized as a Judge in the appropriate places in DAWSON.

* This is a request to onboard two new Special Trial Judges joining the court potentially as early as Monday. @mmarcotte is working on gathering the judge names for implementation in DAWSON

* This needs to move down the rapid deployment (i.e., Bug path for code so as to not be tied in with potential delays in the batch deployment for batch 13

* @mmarcotte will invite folks to work with him on this and the corresponding issue on the Court board when ready to begin work

## Acceptance Criteria
* New judges have full Judge role functionality in DAWSON
* New judges appear in dropdown lists, selection menus, forms, and filters just like the existing judges in the application

## Notes
- [x]  Add new chambers section
- [x]  Create new users in test environment
- [ ]  Create new users on prod

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by mmarcotte** [comment]
Created the chambers sections in the code. Currently deploying to `test`. Have refactored a helper script that lets you add users into the system.

**Comment by mmarcotte** [comment]
There had already been an item in the Devex backlog for refactoring this out of the code and into the database. That was closed favoring the work being done as part of [this story](https://github.com/flexion/ef-cms/issues/4386). Let's figure out as a team with the PO how to best proceed.

**Comment by mmarcotte** [comment]
Here's what we did (for when we need to do this again before the larger effort to manage users from within DAWSON):

* Adjusted the code to define the chambers for the new judges
* Ran the `bulk-import-judge-users.sh` script with a modified version of the `judge_users.csv` that only included the new judge users in order to create them in the desired (`test`) environment
* Created a new chambers user with one of the newly defined chambers sections.
