### ISSUE TITLE
Court: Implement Alternative to MS-Edge PDF Renderer

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8146]
As a DAWSON user, so that I can interact with PDF files in a safe way, I need an alternative to the Microsoft Edge PDF viewer.

The latest version of the Microsoft Edge PDF viewer introduces additional text editing and formatting capabilities. Unfortunately interacting with these causes inconsistent and incorrect behavior in DAWSON w/r/t viewing PDF files, for which there is currently no known workaround. 

To prevent this from happening in the future, we would like an alternative solution for rendering and interacting with PDF files in the DAWSON application.

This story attempts to address the issue documented in ustaxcourt/ef-cms#8113 and use the framework developed in ustaxcourt/ef-cms#8116

## Acceptance Criteria
* PDF interactions in DAWSON remain functionally similar to the current state (at minimum, print and save capabilities remain)
* The Microsoft Edge PDF Viewer no longer is visible or usable in the DAWSON UI
* Navigational elements present on current UI remain in place (The links that appear contextually in the rendering frame)
* Implementation of solution is coded behind a feature flag, allowing viewer switching between current version and alternate solution

## Notes
* Comprehensive solution will require a large amount of regression testing in Court environments and Court laptops.
* Is there a way to refactor the feature flag/framework to make it even more flexible (i.e., supply browser-specific strings for components should we want to introduce those in the future)?
## Test Cases
* User creates a new case, uploads petition; petition uploaded and rendered correctly, MS toolbar is not visible. User can save uploaded petition and print uploaded petition
* User creates a new case, scans in petition, creates PDF; PDF created and rendered correctly, MS toolbar is not visible. User can save and print petition. (Repeat for other documentation in Create Case workflow)
* User calendars trial session, is presented with documentation to be printed for paper service petitioners; PDFs created and rendered correctly, MS toolbar is not visible. User can save and print all documents.
* User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new Order or Notice and views it in the Drafts view of the Docket record; Order is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new Paper Filing for Docket; uploads or scans in document; document is rendered correctly, MS toolbar is not visible. User can save and print document.
* User creates new PDF Upload for Docket; uploads document; document is rendered correctly, MS toolbar is not visible. User can save and print document.
* User prints document on paper; document is clear and legible with proper formatting

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
## Test Cases

#### 1) User creates a new case, previews the petition and STIN that were uploaded.
 
* Log in as a Petitioner
* Click on the Create Case button
* Click on the "Got it, Let's Start a Case" button
* Upload a STIN and click "Continue to Step 2 of 5"
* Upload a Petition, Answer the question about the IRS notice, and then click "Continue to Step 3 of 5"
* Fill out the information for the Petitioner, and then click "Continue to Step 4 or 5"
* Select a case procedure and trial location, and then click "Continue to Step 5 of 5"
* On the Review your Case screen, click on the URL of the Petition and the URL of the STIN

Expected Results:

- [ ] The PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] The PDF viewer may be able to zoom, pan, find, rotate, fit to width (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] The PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting

#### 2) User Submits case to the US Tax Court, petition uploaded and rendered correctly, MS toolbar is not visible. User can save uploaded petition and print uploaded petition

* Test Case 1
* Click "Submit to US Tax Court" button on Review your Case Screen.
* Click on the Docket number on the confirmation screen
* Click on the URL for the Petition

Expected Results:

- [ ] Petition document opens in new tab
- [ ] Printing the Petition results in a clear and legible document with proper formatting
- [ ] Saving the Petition results in a clear and legible document with proper formatting


#### 3) User creates a new case, scans in petition, creates PDF; PDF created and rendered correctly on Create Case screen, MS toolbar is not visible. User can save and print petition. (Repeat for other documentation in Create Case workflow)
* Log in as a Petitions Clerk
* Click on Document QC Tab
* Click on "Start a Petition"
* While on the Petition tab, be sure that the "Scan" radio button is selected and then select a scanner that you have access to
* Click on "Start Scan"
* Click the "Create PDF" button at the bottom of the preview screen
* Repeat these steps for the STIN, RQT, ODS, and APW tabs

Expected Results:
- [ ] For each document scanned, the PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] For each document scanned, the PDF viewer may be able to zoom, pan, find, rotate, fit to width, view a Table of contents (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] For each document scanned, the PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting


#### 4) User views documents on the "Review and Serve Petition" Screen; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.
* Test Case 3
* Fill in the required data for the Petition (Parties, Case Info, and IRS notice tab)
* Click "Create Case"
* On the "Review and Serve Petition" screen, Click on the document URL's in the Attachments card.
* Note: There will not be an active URL for the STIN

Expected Results
- [ ] For each document, the PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] For each document, the PDF viewer may be able to zoom, pan, find, rotate, fit to width, view a Table of contents (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] For each document, the PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting

### _**????Add something about print paper service for serving petition????**_


#### 5a) User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.
* Test Case 4
* Click "Serve to IRS"
* Click "Yes, Serve"
* Click on Document QC tab
* Click on the Served tab
* The first docket number should be the case that you just served the petition on, click the Petition URL

Expected Results:

- [ ] The page should navigate you to the Document View tab
- [ ] The PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] The PDF viewer may be able to zoom, pan, find, rotate, fit to width, view a Table of contents  (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] The PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting

#### 5b) User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.
* Navigate to a case with multiple documents (large and small documents) on the docket record. (I used 14818-21)
* Click on the Document view tab
* Click through multiple documents on the document view. For each document:

Expected Results:

- [ ] The PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] The PDF viewer may be able to zoom, pan, find, rotate, fit to width, view a Table of contents (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] The PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting

#### 6) User calendars trial session, is presented with documentation to be printed for paper service petitioners; PDFs created and rendered correctly, MS toolbar is not visible. User can save and print all documents.
* Log in as a Petitions Clerk
* Click on Trial Sessions
* Click on "Add Trial Session" button
* Fill in the required fields for a new trial session - be sure that you put something like ~20 max cases, and remember what date and city you created a trial session for!
* Click "Add Session". 
* You should get a green message indicating "Trial Session added"
* Click on the "New" tab and find the trial session you just created
* Click on the City, State URL to open the trial session
* Scroll down to the bottom and check the box for ~20 cases as QC Completed
* Click "Set Calendar"
* Click "Yes, Set Calendar"
* The Print Paper service screen will appear

Expected Results:
- [ ] The PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] The PDF viewer may be able to zoom, pan, find, rotate, fit to width, view a Table of contents (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] The PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting




**DO NOT USE THIS ONE** - 5. User views a Docket record in the Document view and selects a document; PDF is rendered correctly, MS toolbar is not visible. User can save and print document.



#### 7) User creates new Order or Notice and views it in the Drafts view of the Docket record; Order is rendered correctly, MS toolbar is not visible. User can save and print document.

- Log in as a docket clerk
- Navigate to a case
- Click on the Create menu and select Order or Notice
- Select Order from the dropdown menu, and click continue
- Add some text in the order generator and click save.
- Apply the CJ signature and click Save Signature

Expected Results
- [ ] The PDF viewer has the ability (at a minimum) to print or save in this preview screen 
- [ ] The PDF viewer may be able to zoom, pan, find, rotate, fit to width, view a Table of contents (this depends on the implementation - but this was available in the MS Edge viewer as read only type of features)
- [ ] The PDF viewer does not allow the user to add text, highlight, edit, draw, or do any other editing to the PDF
- [ ] Microsoft toolbar is not visible
- [ ] Printing the documents result in a clear and legible document with proper formatting
- [ ] Saving the documents result in a clear and legible document with proper formatting



#### 8) User creates new Paper Filing for Docket; uploads or scans in document; document is rendered correctly, MS toolbar is not visible. User can save and print document.



#### 9) User creates new PDF Upload for Docket; uploads document; document is rendered correctly, MS toolbar is not visible. User can save and print document.


#### 10) User prints document on paper; document is clear and legible with proper formatting.
