### ISSUE TITLE
Court: Indicate Proceeding Type on Trial Session Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8148]
As a Court user, so that I can quickly identify specific types of trial sessions, I need to see what type of Proceeding a given trial session is when viewing the Trial Sessions list.

When calendaring and scheduling judge assignments, it is not clear when looking at the Trial Sessions view which sessions are remote and which ones are in-person on location, as sessions with a specific location assigned can be either. To make this information available at a glance, we would like to indicate which type of proceeding each session is, and provide a filter on the screen to display only specific proceeding types.

## Acceptance Criteria
* Trial Sessions screen indicates the Proceeding Type of the Trial Session for each entry
* Trial Sessions screen has a filter that allows for selecting Trial Sessions of a specific Proceeding Type (In-Person or Remote)
* Standalone Remote Trial Sessions indicate a Proceeding Type of Remote
* When filtered for a particular Proceeding Type, only Trial Sessions of that Proceeding Type display on the Trial Sessions screen
* Both the Proceeding Type and its filter are available on all instances of the Trial Sessions screen (New, Open, Closed, All)

## Notes
Should not be restricted to a particular court role.

## Test Cases
 * In-Person Trial Session is created; Trial Session displays indicating a Proceeding Type of In-Person; when filtered for Remote Proceeding Type on the Trial Sessions screen, In-Person Trial Session no longer displays
* Remote Trial Session is created; Trial Session displays indicating a Proceeding Type of Remote; when filtered for In-Person Proceeding Type on the Trial Sessions screen, Remote Trial Session no longer displays
* Standalone Remote Trial Session is created; Trial Session displays indicating a Proceeding Type of Remote; when filtered for In-Person Proceeding Type on the Trial Sessions screen, Standalone Remote Trial Session no longer displays

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [x] Deployed to the Court's migration environment

**Comment by swongCO** [comment]
![Trial sessions 9248.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7565c540-afb1-407d-8e1d-578fb8552d03)

1. Add a column labeled "Proceeding Type".
2. Add "Session" to the session type column label (currently "Type").
3. Position the new column to the left of session type.
4. The two values in the new column are "In Person" and "Remote".
5. Add a new filter labeled "-Proceeding type-".
6. The values in the new filter dropdown are: "-Proceeding type-"; "In Person"; "Remote".
7. Re-order the filters so that they follow the order in the table: location, proceeding type, session type, judge.

**Comment by ttlenard** [comment]
**Test Cases**

**1. In-Person Trial Session is created; Trial Session displays indicating a Proceeding Type of In-Person; when filtered for Remote Proceeding Type on the Trial Sessions screen, In-Person Trial Session no longer displays**

- Log in as Petitions Clerk
- Click on Trial Sessions from the top menu bar
- Click on Add Trial Session button
- Be sure that location based is selected as the session scope
- Fill out a start date, session type, # of cases.
- Ensure that In Person is selected as location
- Select a Trial Session Location, and fill out location fields
- Fill in information on Session Assignments fields
- Click Add Session.
- Click on New tab, and locate the session that you just created.

Expected Results

- [x] Proceeding type of the trial session you just created should indicate In Person in the Proceeding type column in the table.

- Next, use the filters and filter by Proceeding type, location, Session Type, and Judge.

Expected Results

- [x] When filtering by Proceeding type of Remote - you should not see the session you just created.
- [x] When filtering by Proceeding type of In Person - you should see the session you just created

**2. Remote Trial Session is created; Trial Session displays indicating a Proceeding Type of Remote; when filtered for In-Person Proceeding Type on the Trial Sessions screen, Remote Trial Session no longer displays**

- Log in as Petitions Clerk
- Click on Trial Sessions from the top menu bar
- Click on Add Trial Session button
- Be sure that location based is selected as the session scope
- Fill out a start date, session type, # of cases.
- Ensure that Remote is selected as location
- Select a Trial Session Location, and fill out meeting information fields
- Fill in information on Session Assignments fields
- Click Add Session.
- Click on New tab, and locate the session that you just created.

Expected Results

- [x] Proceeding type of the trial session you just created should indicate Remote in the Proceeding type column in the table.

- Next, use the filters and filter by Proceeding type, location, Session Type, and Judge.

Expected Results

- [x] When filtering by Proceeding type of In Person - you should not see the session you just created.
- [x] When filtering by Proceeding type of Remote - you should see the session you just created

**3. Standalone Remote Trial Session is created; Trial Session displays indicating a Proceeding Type of Remote; when filtered for In-Person Proceeding Type on the Trial Sessions screen, Standalone Remote Trial Session no longer displays**

- Log in as Petitions Clerk
- Click on Trial Sessions from the top menu bar
- Click on Add Trial Session button
- Be sure that Standalone Remote is selected as the session scope
- Fill out a start date, session type.
- Fill out Remote Proceeding information fields
- Fill in information on Session Assignments fields
- Click Add Session.
- Click on Open tab, and locate the Standalone remote session that you just created.

Expected Results

- [x] Proceeding type of the trial session you just created should indicate Remote in the Proceeding type column in the table.

- Next, use the filters and filter by Proceeding type, location, Session Type, and Judge.

Expected Results

- [x] When filtering by Proceeding type of In Person - you should not see the session you just created.
- [x] When filtering by Proceeding type of Remote - you should see the session you just created

**4. Filters on the Trial Session page for Open, New, and Closed tab filter on Proceeding type appropriately.**

- Log in as Docket clerk
- Click on Trial Sessions from the top menu bar
- Click on the Each of the tabs = New, Open, and Closed
- Use the Proceeding type filter and ensure filter works appropriately

Expected Results

- [x] When the Proceeding Type Filter  of "In Person" is selected, no  Remote sessions display in the table
- [x] When the Proceeding Type Filter  of "Remote" is selected, no  In Person sessions display in the table.  Remote should show results for both Remote sessions with a location, and remote sessions that indicate Standalone Remote in the location column.

**Comment by rosiehsmith** [comment]
Completed `Dev Review` on staging and everything looks good!
