### ISSUE TITLE
External Search: Turn on/off Opinion Search for External Users in Production

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8149]
As a DAWSON user, so that I can continue using the system, I need the Court to be able to toggle external Order search off and on without requiring a deployment.

## Acceptance Criteria
* Tech lead can turn order search on or off in the production environment for external users (public users, private practitioners, IRS practitioners) only without a deployment and within 30-60 min
* Users who try to access order search after the search page has loaded AND the search feature has been turned off, are notified in a way that doesn't disrupt their work or log them out

## Notes
Functionally, this should be the same ability implemented in ustaxcourt/ef-cms#8085 with a different context (public users, private practitioners, IRS practitioners)

## Test Cases
* External search is active; public user navigates to advanced search, clicks on Opinions, is able to search and retrieve results.
* External search is active; private practitioner navigates to advanced search, clicks on Opinions, is able to search and retrieve results.
* External search is active; IRS practitioner navigates to advanced search, clicks on Opinions, is able to search and retrieve results.
* External search is active; public user navigates to advanced search, clicks on Opinions, is able to search and retrieve results. 
* Tech lead toggles external search inactive; user is notified/navigated to UI with inactive Opinion search verbiage
* External search is active; private practitioner user navigates to advanced search, clicks on Opinion, is able to search and retrieve results. Tech lead toggles external search inactive; user is notified/navigated to UI with inactive Opinion search verbiage
* External search is active; IRS practitioner navigates to advanced search, clicks on Opinions, is able to search and retrieve results. Tech lead toggles external search inactive; user is notified/navigated to UI with inactive Opinion search verbiage
* External search is inactive; public user navigates to advanced search, is unable to click on Opinions
* External search is inactive; private practitioner navigates to advanced search, is unable to click on Opinions
* External search is inactive; IRS practitioner navigates to advanced search, is unable to click on Opinions

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
Hi @liadmccabe I was just reviewing this story to document the test cases, and I was wondering what you thought about this verbiage for bullets 5, 6, and 7.  I copied it out of the Order Search story and just swapped out the word "Order" and replaced with "Opinion". **"Opinion search has been temporarily disabled. Please try again later."**

**Comment by rachelschneiderman** [comment]
To deploy this story, run the following script:

scripts/setup-external-opinion-search-flag.sh <ENV>

Note: This script sets the value to true by default, just in case any env needs this feature disabled at first..

**Comment by liadmccabe** [comment]
> Hi @liadmccabe I was just reviewing this story to document the test cases, and I was wondering what you thought about this verbiage for bullets 5, 6, and 7. I copied it out of the Order Search story and just swapped out the word "Order" and replaced with "Opinion". **"Opinion search has been temporarily disabled. Please try again later."**

That makes sense to me, it's best to keep it consistent across the board whenever possible, it's clear about the issue and gives the user an action to take. I'm good with that.

**Comment by rachelschneiderman** [comment]
I have run the script to add the flag to all Flexion environments.
