### ISSUE TITLE
BUG: Inactive judges cannot be selected in public (non-logged in) Order search

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8150]
**Describe the Bug**
When searching Orders as a public (non-logged in) user, inactive Judges present on the dropdown menu cannot be selected in the Judge filter.

**Business Impact/Reason for Severity**
Poor user experience; expectation is that inactive judges can be selected to filter search results; Order search cannot be filtered by inactive judges

**In which environment did you see this bug?**
MIG, PROD

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Validating behavior

**To Reproduce**
1. Go to public Order search
2. Attempt to select "Armen" from the Judge filter

**Expected Behavior**
"Armen" is displayed as the filtered judge

**Actual Behavior**
Judge filter reverts to no selection

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by halprin** [comment]
Inactive judges are returned from the backend with less information than the others which results in the dropdown from working.  I initially thought that the UI was wrong, but then I saw the backend was filtering out information that is there in in the db.  So I'm currently looking at `PublicUser.validateRawCollection` in `getJudgesForPublicSearchInteractor.js`.

**Comment by halprin** [comment]
And this is reproducible locally with the "Fieri" judge.

**Comment by halprin** [comment]
Identified a fix and committed it to branch `bug-9278-inactive_judges_for_order_search`.  Tests still need to be modified or added.

In addition to that, there is some homework for why we use `judge.lastName` in the `JudgeSelect.jsx` when `lastName` isn't returned from the API response.  Maybe it is computed somewhere in the frontend?

**Comment by cholly75** [comment]
Tested in TEST environment - all judges are now selectable in the filter menu. 

Currently not getting any results back for legacy judges, and extremely different result sets for current judges (>100 for Buch in MIG, 2 in TEST).  Did comparative search in MIG to check expected results. Discussed w/ @halprin, sending back to In Progress.

**Comment by cholly75** [comment]
@halprin One other detail - I confirmed that the behavior for the logged in user still seems correct for both legacy and current judges, so this appears to only affect the public user.
