### ISSUE TITLE
BUG: Case Status is not getting updated to "General Docket - At Issue (Ready for Trial)" 45 days after Answer document is filed

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8154]
**Describe the Bug**
The Clerk of the Court noticed that some case status's were not getting updated, and were remaining at "General Docket - Not at issue" even after there was an Answer document filed in the case AND 45 days had passed. 

For some background on this: See original story [1187](https://github.com/flexion/ef-cms/issues/1187).

After reviewing the code, it looks as if the cron runs the checkForReadyForTrialCasesLambda on a nightly basis, but only looks at 5000 cases (see Screen grab below).  In DAWSON (as of today, 12-27-21) there are 14,759 cases that have the case status of General Docket - Not at issue. I think that this means that approximately 10,000 cases are getting skipped.

We should make sure that this process triggers for each case as expected.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**
Clerk of the court

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Go to 22565-21, or 23824-21 (just two examples, but there are many)
2. Notice that the Answer Document was filed on 11-10-21 (47 days ago)
3. Notice that the Case Status is still set at "General Docket - Not at Issue"
4. According to story 1187, this case status should be set to "General Docket - at issue (ready for trial)

**Expected Behavior**
45 days after an Answer type document (see 1187 for full list of Answer type documents) is Served, the Case Status should automatically update to General Docket - At Issue - (Ready for Trial).  When this happens, this case then is available to show up on the Eligible for trial list when Calendar section is setting new Calendars.  If the status remains (not at issue), then these cases never show up as ready for trail, and will not get a court date assigned.

**Actual Behavior**
A clear and concise description of what actually happened.
It appears that some cases are getting "skipped" and the case status is not getting updated to General Docket - At Issue (Ready for Trial)

**Screenshots**

Here is the code we were reviewing where we saw the 5000 limit:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/67ba6cb3-9fd3-44fe-8933-e9c53c6fb46b)

Here is a screen grab out to Production that shows that as of today, there are 14,759 cases with the status of general docket - not at issue (This is from the Case Inventory report)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/d883cfae-1977-4012-a2ac-7ebdbbc16bbf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
We think that the size of 5000 is what is causing cases to be skipped.

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by jimlerza** [comment]
I added a helper for retrieving all results via Elasticsearch in [PR 1868](https://github.com/ustaxcourt/ef-cms/pull/1868) that could be useful here.

Here is a [usage example](https://github.com/ustaxcourt/ef-cms/pull/1868/files#diff-231269cfe81ad2f6a2a5aa35e2a47bdd1fc6728208a308be59e6f709f6829a25R45).
