### ISSUE TITLE
Court: Style Change for Notices

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8159]
As a court user, so that notices conform to the new style guide requirements, I need the new style guidelines implemented in DAWSON.

The court conference has approved a new set of style guidelines that take effect on 1/1/2022. These guidelines need to be incorporated into the formatting of all Notices generated and entered in DAWSON.

## Acceptance Criteria
* The header "United States Tax Court" is formatted in 20-point font
* The header "United States Tax Court" is formatted in Old English font
* The subheader "Washington, DC 20217" is formatted in 10-point font
* The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
* All other text on the notice is formatted in Century Schoolbook font
* All other text on the notice is formatted in 12-point font
* The petitioner's name(s) in the Caption are rendered in all capital letters
* The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
* All text paragraphs are justified
* The new style is applied to all types of Notices in DAWSON
* Name/Address portion of notice and clerk signature remain in place for viewing through envelope window

## Test Cases
* Generate a new Notice of any type in DAWSON. Confirm that the Notice is compliant with the new style.
* Generate a new Notice that also creates the print queue for paper service mailing (Notice of remote proceeding, Notice of Trial, etc.), verify Name/Address portion and clerk signature remain in place for viewing through envelope window.
* View a previously generated Notice of any type in DAWSON. Confirm that the style has not changed on prior Notices.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Generate a new Notice of any type in DAWSON. Confirm that the Notice is compliant with the new style.**
- Log into DAWSON as a docket clerk
- Type in a docket number in the upper right (ex 6543-21), and click search
- Click Create
- Select Order or Notice from the menu
- Select Order Type = Notice
- Notice Title = you can type whatever you would like
- Click continue
- A new DAWSON Tab will open
- Add in some test text into the body of the Notice generator
- Click the Preview tab

Expected Results: 
- [ ] The preview should display the Notice in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice

- Click Save
- DAWSON should route you to the drafts page, and a green success message should appear on the top of the page indicating that the Notice you just created was saved.

Expected Results
- [ ] The draft Notice on the drafts page should display the Notice in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice

- Click Add Docket Entry

Expected Results
- [ ] The draft Notice on the Add Docket Entry page should display the Notice in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice

- Click the Served button, and then click on "Save and Serve"
- Click "Yes, Serve"

Expected Results:

- [ ] The Notice on the Print Notice for Paper Service should display the Notice in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice
- [ ] The first page in this preview has the Petitioners Name and address for the envelope window, this remains the same Font and size as it was before.

- Click "Done"
- Click on the Docket Entry URL of the Notice that you just created. This will open up the Document View.

Expected Results:
- [ ] The Notice on the Document View page should display the Notice in the new Style format
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice


**2. Generate a new Notice that also creates the print queue for paper service mailing (Notice of remote proceeding, Notice of Trial, Notice of Receipt of Petition, etc.), verify Name/Address portion and clerk signature remain in place for viewing through envelope window.**
- This test below is for the Notice of Trial
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session"
- Fill in the Session information (It shouldn't matter if it is in person or remote)
- Click "Add Session"
- A green message will appear indicating "Trial Session added".
- Click on the "New" link, and navigate to the trial session you just created.
- Click on the City, State URL
- Check the "QC Complete?" boxes for a few cases in the Eligible case list.
- Click "Set Calendar"
- A modal will appear, click "Yes, Set Calendar"

Expected Results:
- [ ] The Print and mail all paper service documents will have the Notice setting case for trial for all the cases in the trial in the New Style format (The STPO that is also in this print queue should also be compliant if that story was completed before this one.)
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice
      
- [ ] The first page in this preview has the Petitioners Name and address for the envelope window, this remains the same Font and size as it was before.

- Click Done
- Click on the "Open" tab to go find the Trial session you just created
- Click on the City, State URL of the trial session
- Select a docket number from the list of cases (I chose to open it in a new tab)
- Scroll down the docket record to find the Notice of Trial (NTD)
- Click on the Notice URL. This will open the document up in the document view

Expected Results:
- [ ] The Document View will have the NTD in the New Style format 
     - [ ] The header "United States Tax Court" is formatted in 20-point font
     - [ ] The header "United States Tax Court" is formatted in Old English font
     - [ ] The subheader "Washington, DC 20217" is formatted in 10-point font
     - [ ] The subheader "Washington, DC 20217" is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in Century Schoolbook font
     - [ ] All other text on the Notice is formatted in 12-point font
     - [ ] The petitioner's name(s) in the Caption are rendered in all capital letters
     - [ ] The respondent's name ("Commissioner of Internal Revenue") is rendered in all capital letters
     - [ ] All text paragraphs are justified
     - [ ] Clerk's Signature is in the bottom right corner of the Notice
  

**3. View a previously generated Notice of any type in DAWSON. Confirm that the style has not changed on prior Notices.**
- Log in as a Docket Clerk
- Type in a docket number into the search box in the upper left (ex 7890-21) (Any docket number is fine, as long as there is a previously generated Notice on the docket record)
- Click on the Docket entry URL of the Notice, or you can also click on Case Information, and then click on the "Print Confirmation" link to see the Notice of Receipt of Petition.

Expected Results
- [ ] The previously generated Notice is in the older style format.

**Comment by cholly75** [comment]
Closing story - not needed at this time.
