### ISSUE TITLE
Petitions: Auto-Generate Order for Amended Petition and Filing Fee

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8165]
As a petitions clerk, so that I can easily generate needed documentation, I need to have DAWSON generate a draft of an Order for Amended Petition and Filing Fee automatically when I indicate that one is needed for a case.

Currently, when a Petitions Clerk indicates that an Order for Amended Petition and Filing Fee (OAPF) is needed for a case, they check the appropriate box at the time of paper Petition entry or QC of eFiled Petition. After the Petition is served, the Petitions Clerk must then manually create the order via copying and pasting content and uploading a PDF into DAWSON.

As this order is standard text, if the clerk indicates that the order is needed we would like this order along with its attached form for Amended Petition to be automatically generated as a draft entry attached to the case upon Petition service, at which point the clerk can review, edit, delete, and add as a docket entry through normal existing process.

We anticipate additional stories to auto-generate other notices and orders in the same manner; ideally the framework for auto-generating the OAPF can be extended to include other documentation.

## Pre-Conditions
See 8993 for UX specs: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8993

## Acceptance Criteria
* If the Order for Amended Petition and Filing Fee box is checked when the clerk serves the Petition, an Order for Amended Petition and Filing Fee (OAPF) is generated and saved as a Draft document at the time the Petition is served.
* After Case is created and before service of the petition, the UI indicates that OAPF is pending generation
* The generated OAPF is created with the standard Order format (Case caption/docket number at the top followed by title and text of the order), to which is then attached as subsequent pages the actual form for submitting an Amended Petition (both docs are attached below).
* The title of the generated OAPF is "Order"
* The **body** content of the generated OAPF is identical to the attached document:
[https://app.zenhub.com/files/152320868/d703f9a6-89c9-42fb-ab5c-b391e8aea548/download](https://app.zenhub.com/files/152320868/d703f9a6-89c9-42fb-ab5c-b391e8aea548/download)

 - Note that following the text of the order proper is the form for submitting an Amended Petition. This should be appended to the Order in its entirety as presented and as separate pages.
 - The value of the [FILED_DATE] token is derived from the served date of the petition
 - The value for the [ORDER_DATE_PLUS_60] token in the content is derived from the current date at the time of order generation and counting 60 consecutive calendar days hence. If the resulting date falls on a Saturday, Sunday, or federal Holiday then the resulting date should instead be changed to the next weekday that is not a Holiday.
* The generated draft order should not auto-apply the signature of the Chief Judge. The clerk will do this.
* The generated draft order can be interacted with in the same manner as any other Draft order from the Drafts view (edit,
delete, apply a signature, and add as a docket entry).

## Test Cases
* Petitions clerk starts new petition, checks box for "Order for Amended Petition" in the Case Info tab and completes all other required info and creates Case. OAP is not generated. UI reflects pending OAP generation. Petition is served; OAP is generated and appears as a Draft document attached to case.
* Petitions clerk QCs new e-filed petition, checks box for "Order for Amended Petition" in the Case Info tab and completes all other required info and creates Case. OAP is not generated. UI reflects pending OAP generation. Petition is served; OAP is generated and appears as a Draft document attached to case.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Petitions clerk starts new Paper petition, Only checks box for "Order for Amended Petition and Filing Fee" in the Case Info tab and completes all other required info and creates case. Order is not yet generated, but the UI reflects a pending Order generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition, STIN, and RQT under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button
- Add a Trial Location and click the radio button to indicate that the Filing Fee was "Not paid"
- Be sure to uncheck the box for "Order for Filing Fee"
- Under the Orders/Notices Needed section, select the box for Order for Amended Petition and Filing Fee.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with a new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] The "Order for Amended Petition and Filing Fee" should be below the above section header, and will be in regular font.


**2. Petitions Clerk serves the petition. Order for Amended Petition and Filing Fee is generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there is 1 draft.

**3. The draft Order for Amended Petition and Filing Fee is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [x] On the left hand side of the page under the Drafts, you should see a new "Order for Amended Petition and Filing Fee" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be "Order", etc.), and should include the standard body content that is here: https://app.zenhub.com/files/152320868/d703f9a6-89c9-42fb-ab5c-b391e8aea548/download
- [x] The Filed Date in the Order should be the served date of the petition
- [x] The Order Date date should be either be: 1) 60 consecutive calendar days hence (If the calendar date falls on a Saturday, Sunday, or Federal Holiday the then resulting date should be the following weekday that is not a holiday), or 2) there should be a red [ENTER_DATE] to let the clerk know they need to add the date
- [x] An Amended Petition form should be appended to the Order
- [x] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF.

**4. Add the Order for Amended Petition as a docket entry and Serve it.**
- Continuing from the previous test case, click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order for Amended Petition for Paper Service" screen

Expected Results
- [x] Order for Amended Petition and Filing Fee is added as a docket entry and shows as served
- [x] The Order Event Code is "OAPF" on the Docket Record
- [x] The number icon no longer appears on the Drafts tab

**5. Petitions clerk starts new Paper petition, checks boxes for multiple Orders as well as checks the box for "Order for Amended Petition and Filing Fee" in the Case Info tab and completes all other required info and creates Case. Order for Amended Petition and Filing Fee is not yet generated, but the UI reflects a pending Order for Amended Petition and Filing Fee generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition and STIN under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button, Do not check the box for "Order to show cause".
- Leave the Trial location blank. This will ensure that the checkbox is checked for "Order Designating Place of Trial"
- Select the radio button that the fee was NOT paid. This will automatically check the box for Order for Filing Fee. Be sure to uncheck this box.
- Under the Orders/Notices Needed section, select the checkbox for Order for Amended Petition and Filing Fee, along with one other Order, as well as the checkbox for Notice of Attachments in the Nature of Evidence.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with 2 Section Headers.  One that states "Orders/Notices Needed" and new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] Some of the Orders (that have not yet had a story to be auto-created) that you selected should be under the section Header "Orders/Notices Needed" and will be in regular font.
- [x] The "Order for Amended Petition and Filing Fee", and all other Orders/Notices that were selected that have been coded to be auto-created should be under the section header "Orders/Notices Automatically Created in Drafts After Service", and will be in regular font.


**6. Petitions Clerk serves the petition. Order for Amended Petition and Filing Fee, and all other Orders/Notices that were selected that have been coded to be auto-created are generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there are drafts. This number should reflect the total number of draft Orders/Notices created.

**7. The draft Order for Amended Petition is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [x] On the left hand side of the page under the Drafts, you should see a new "Order for Amended Petition and Filing Fee" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be "Order", etc.), and should include the standard body content that is here: https://app.zenhub.com/files/152320868/d703f9a6-89c9-42fb-ab5c-b391e8aea548/download
- [x] The Filed Date in the Order should be the served date of the petition.
- [x] The Order Date date should be either be: 1) 60 consecutive calendar days hence (If the calendar date falls on a Saturday, Sunday, or Federal Holiday the then resulting date should be the following weekday that is not a holiday), or 2) there should be a red [ENTER_DATE] to let the clerk know they need to add the date
- [x] An Amended Petition form should be appended to the Order
- [x] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF

**8. Add the Order for Amended Petition and Filing Fee as a docket entry and Serve it.**
- Continuing from the previous test case, click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order for Amended Petition and Filing Fee for Paper Service" screen

Expected Results
- [x] Order for Amended Petition and Filing Feeis added as a docket entry and shows as served
- [x] The Order Event Code is "OAPF" on the Docket Record
- [x] The number icon should now reflect 1 less document on the Drafts tab

**Comment by cholly75** [comment]
Update on AC: the court would like the FILED_DATE token to represent the actual Filed date of the petition now instead of the served date. Discussed w/ @halprin and @jamesobrooks
