### ISSUE TITLE
Experiment: Onboarding for New Team Members

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8181]
As a new team member, so that my onboarding needs can be met,  I need a way to know everything that's important for me as a new employee.

## Problem/Observation
More structure is needed for onboarding current and future team members in each discipline. 

## Hypothesis
Providing more structure will help answer questions, improve efficiency and provide a more well-rounded and predictable onboarding experience. 

## Experiment Details
Improve the current state of documentation so that a brand new person has an easy way to step-by-step read through the docs and get a better understanding of how the project, team and product works. 

Documentation is spread out and difficult for a beginner to find.

Survey  for current team members - what tech do you need more info about or need want to know. So they can focus on writing documentation for less known topics first.

## Data to Measure
Go back and have new people review the documentation.

## Timebox
When main pieces of documentation are done, have a review.

## Open Questions
* I think the problem statement could be more clear.
* The timebox should be a specific time
* Do we want to separate the "buddy" portion out? I know there were a few people who wanted to try it. 

## Notes

Have engineering specific goals checklist of things a new person could/should be taught how to do
Trello board
Would be nice to have something to reference back to and continue to improve
Teach about different aspects of the system; tie business domains to the backend code
Short videos

Buddy
Buddy system for a dedicated time - for safety - someone I can go to and ask questions with ease
What about a new person each week? That way you see multiple views, and you get 1:1 time with multiple team members

**Comment by ujahio** [comment]
onboarding checklist: https://docs.google.com/document/d/1zhvp8vcWnVSvUbTKZ-0sHrf5lA6OTlpXqvjeLgKJtVk/edit
onboarding reference guide: https://docs.google.com/document/d/1jOd0wAsqTDBKsFeEvUj9ezvdTimTsqTwkYd6Imibl3c/edit#
Github docs: https://flexion.github.io/ef-cms/#/
Project workflow: https://lucid.app/lucidchart/eb52faa0-5076-47f1-8cf4-d0fa2da8a768/view?invitationId=inv_3529825c-dcac-41a8-8413-7c2b5e391643&page=E1c5Hd0icU8n#
Bug/story workflow: https://lucid.app/lucidchart/a6c62296-e1ec-4754-b016-b94c6e0d84df/edit?invitationId=inv_0e7307a1-fe42-4639-bd39-2b5899c61a0c&page=0_0#
onboarding-buddies writeup: https://docs.google.com/document/d/1pj8aFhBqNBcsRNnIHYhRZE72WiUKR11q2HfH0LYNGOg/edit#heading=h.vdpjxhvusgsi
