### ISSUE TITLE
Unservable Consolidated Case Documents (Court-Filed)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8192]
As a docket clerk, in order to prevent having to add multiple docket entries in a group of consolidated cases, I need the system to automatically add an *unservable* docket entry to any other cases in the group that I choose when adding a docket entry for a Draft in the Lead case.

When a document is filed in the Lead Case of a consolidated group, usually it also needs to be filed in the other cases in the group as well. Currently the functionality developed in ustaxcourt/ef-cms#6969 only targets documents intended to be served on parties.

We would like to extend this functionality to documents that are coded as *unservable* as well. Of these documents, a subset also receive cover sheets and so we need to address the creation of these cover sheets as part of this story like so:

We would like cover sheets generated for documents filed in consolidated cases to reflect all the cases in the consolidated group and the document docket positions in those cases. This story addresses court-filed documents, but will be required functionality when we extend consolidated case improvements to party-filed documents.

See screenshots for visuals.

## Pre-Conditions
ustaxcourt/ef-cms#6969

## Acceptance Criteria
* The mechanism developed for ustaxcourt/ef-cms#6969 now includes unserveable court-filed documents with and without cover sheets
  - These documents can be found in https://github.com/flexion/ef-cms/blob/develop/shared/src/tools/courtIssuedEventCodes.json with the value "isUnservable": true"
* The mechanism for propagating the docket entry to other cases is triggered upon saving the docket entry in the Lead case
* When an unserveable document is filed in the Lead Case and any additional cases in the consolidated group and requires a cover sheet to be generated, the cover sheet is generated with the following information on the caption:
  - ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
  - The docket numbers of each other case in the consolidated group are listed sequentially in ascending order on the right side of the caption, followed by the docket entry position of the document in each case as "Document No."
 * If a document was not added to a particular case in the consolidated group, then that case listing in the caption does not  display the "Document No." text after it
* This applies to court-filed documents only

## Notes
Example: ![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/898908ec-eed3-4cea-aa9c-650a4544c747)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
@swongCO @liadmccabe This story still needs UX added.  When the court adds the documents that require cover sheets, these documents are not served to parties, they are just saved to the docket record. Will need to have design added for a new modal for this workflow, since the existing modal states "are you ready to initiate service?" when selecting cases in a CG. Thanks!

**Comment by swongCO** [comment]
Documents that aren't served only have Save Entry / Cancel as CTAs on the Drafts page:
![Add Docket entry - no serve.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/c4eeacb5-050c-425f-859f-fbafc7fad166)

When the user clicks Save Entry, display the modal with the list of cases:
![Add Docket entry - no serve - modal.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e90ce91b-bcfb-4cb6-8a5b-e7fe14dd95dc)
Text changes:
1. Title - Are You Ready to Save This Document to the Docket Record?
2. First line - The following document will be saved to selected cases:
3. Primary btn - Yes, Save

When the user clicks Yes, Save, follow existing flow and take the user to the docket record page with a confirmation message:
- Document saved to selected cases in group.

**Comment by ttlenard** [comment]
## Test Cases 

#### 1.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry (with a document that generates a cover sheet); modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload 
- Upload a PDF, add a description, and click Save 
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet:  **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Save Entry

Expected Results
- [x] **NEW FUNCTIONALITY** Updated modal matches the wording in the mock up above, and has the checkbox checked for "All in the consolidated group" checked.
- [x] **NEW FUNCTIONALITY** There is NOT a list of parties that receive paper service on this modal


#### 1.2) Docket Clerk selects one other case from the consolidated group to save the docket entry into.
- Continuing from test case 1.1
- Uncheck the first checkbox for "All in the consolidated group"
- Select one other case besides the lead case 

Expected Results
- [x] The lead case checkbox will be unselectable and will remain checked.
- [x] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"


#### 1.3) Upon save, the docket entry is saved to the docket record of the selected cases, and a cover sheet is added to the document.
- Continuing from test case 1.2
- Click Yes, Save
- From the docket record of the lead case and the one other case that you selected, open up the document that was just saved.

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] ** NEW FUNCTIONALITY** Green banner that states "Document saved to selected cases in group."
- [x] **NEW FUNCTIONALITY** Each document that was selected in the previous test and that was listed on the modal have the updated coversheet that includes:
     - [x] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
     - [x] The docket numbers of each of the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [x] For the cases that were selected in the modal for Test Case 1.2, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
     - [x] For cases that were not selected in the modal for Test Case 1.2, there will NOT be a "Docket Number or Document No." listed.
- [x] **NEW FUNCTIONALITY** Ensure that the document number that is represented on the cover sheet matches the document number on the docket record of each case.


#### 1.4) Document is reflected appropriately on the docket record for both the lead case and the selected case.
- Continuing from test case 1.3
- Review the document details on the docket record

Expected Results 
- [x] On the lead case, the document is attributed with index #, date, title, pages, and has the edit/seal links (There will not be any data in the column for action, served date, or served parties).
- [x] On the one other case in the CG that was selected, the document is attributed the exact same way on the docket record as in the lead case (index number may vary).


#### 1.5) Document in the non-lead case is the same as the document in the lead case.
- Continuing from test case 1.4
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other case that you filed the document in
- Click on the URL of the document
- Click on the URL to View Full PDF
- This will open the document in a new tab

Expected Results
- [ ] Both documents should be exactly the same
- [ ] Both documents should share the same document ID
- [ ] **NEW FUNCTIONALITY** Both documents should have a cover sheet that includes:
     - [ ] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption 
     - [ ] The docket numbers of each of the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [ ] For the cases that were selected in the modal for Test Case 1.2, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
     - [ ] For cases that were not selected in the modal for Test Case 1.2, there will NOT be a Docket Number or Document No. listed.



#### 2.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry (with a document that generates a cover sheet); modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload 
- Upload a PDF and click Save 
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet:  **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Save Entry

Expected Results
- [ ] **NEW FUNCTIONALITY** Updated modal matches the wording in the mock up above, and has the checkbox checked for "All in the consolidated group" checked.
- [ ] **NEW FUNCTIONALITY** There is NOT a list of parties that receive paper service on this modal


#### 2.2) Docket Clerk selects some of the other cases (not all) from the consolidated group to also save the docket entry into.
- Continuing from test case 2.1
- Uncheck the first checkbox for "All in the consolidated group"
- Select a few other cases (not all) besides the lead case 

Expected Results
- [ ] The lead case checkbox will be unselectable and will remain checked.
- [ ] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"


#### 2.3)  Upon save, the docket entry is saved to the docket record of the selected cases, and a cover sheet is added to the document.
- Continuing from test case 2.2
- Click Yes, Save
- From the docket record of the lead case and the other cases that you selected, open up the document that was just saved.

Expected Results:
- [ ] You will be routed back to the docket record of the lead case
- [ ] ** NEW FUNCTIONALITY** Green banner that states "Document saved to selected cases in group."
- [ ] **NEW FUNCTIONALITY** Each document that was selected in the previous test and that was listed on the modal have the updated coversheet that includes:
     - [ ] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
     - [ ] The docket numbers of each of the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [ ] For the cases that were selected in the modal for Test Case 2.2, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
     - [ ] For cases that were not selected in the modal for Test Case 2.2, there will NOT be a Docket Number or a Document No. listed.
- [ ] **NEW FUNCTIONALITY** Ensure that the document number that is represented on the cover sheet matches the document number on the docket record of each case.


#### 2.4) Document is reflected appropriately on the docket record for the lead case and each case selected.
- Continuing from test case 2.3
- Review the document details on the docket records of each case that the document was saved to

Expected Results
- [ ] On the lead case, the document is attributed with index #, date, title, pages, and has the edit/seal links (There will not be any data in the column for action, served date, or served parties).
- [ ] On the other cases in the CG that were selected, the document is attributed the exact same way on the docket record as in the lead case (index number may vary).


#### 2.5) Document in the non-lead cases are the same as the document in the lead case.
- Continuing from test case 2.4
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other cases that you filed the document in
- Click on the URL of the documents
- Click on the URL to View Full PDF
- This will open the documents in a new tab

Expected Results
- [ ] All of the documents should be exactly the same
- [ ] All of the documents should share the same document ID
- [ ] **NEW FUNCTIONALITY** All documents should have a cover sheet that includes:
     - [ ] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption 
     - [ ] The docket numbers of each of the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [ ] For the cases that were selected in the modal for Test Case 2.2, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
     - [ ] For cases that were not selected in the modal for Test Case 2.2, there will NOT be a  Docket Number or a Document No. listed.



#### 3.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry (with a document that generates a cover sheet); modal appears for clerk to select additional cases to file the document in; 
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload
- Upload a PDF and click Save 
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet: **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Save Entry

Expected Results
- [ ] **NEW FUNCTIONALITY** Updated modal matches the wording in the mock up above, and has the checkbox checked for "All in the consolidated group" checked.
- [ ] **NEW FUNCTIONALITY** There is NOT a list of parties that receive paper service on this modal


#### 3.2) Docket Clerk selects all other cases from the consolidated group to also add the docket entry in those cases; 
- Continuing from test case 3.1
- Leave the checkbox checked for "All in the consolidated group"

Expected Results
- [ ] The lead case checkbox will be unselectable and will remain checked.
- [ ] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"


#### 3.3) Upon save, the docket entry is saved to the docket record of the selected cases, and a cover sheet is added to the document.
- Continuing from test case 3.2
- Click Yes, Save
- From the docket record of the lead case and the other cases that you selected, open up the document that was just saved.

Expected Results:
- [ ] You will be routed back to the docket record of the lead case
- [ ] **NEW FUNCTIONALITY** Green banner that states "Document saved to selected cases in group."
- [ ] **NEW FUNCTIONALITY** Each document that was selected in the previous test and that was listed on the modal have the updated coversheet that includes:
     - [ ] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
     - [ ] The docket numbers of each of the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [ ] For the cases that were selected in the modal for Test Case 3.2, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
- [ ] **NEW FUNCTIONALITY** Ensure that the document number that is represented on the cover sheet matches the document number on the docket record of each case.


#### 3.4) Document is reflected appropriately on the docket record for the lead case each case selected.
- Continuing from test case 3.3
- Review the document details on the docket records of each case that the document was saved to

Expected Results
- [ ] On the lead case, the document is attributed with index #, date, title, pages, and has the edit/seal links (There will not be any data in the column for action, served date, or served parties).
- [ ] On the other cases in the CG that were selected, the document is attributed the exact same way on the docket record as in the lead case (index number may vary).


#### 3.5) Document in the non-lead cases are the same as the document in the lead case.
- Continuing from test case 3.4
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other cases that you filed the document in
- Click on the URL of the documents
- Click on the URL to View Full PDF
- This will open the documents in a new tab

Expected Results
- [ ] All of the documents should be exactly the same
- [ ] All of the documents should share the same ID
- [ ] **NEW FUNCTIONALITY**  All documents should have a cover sheet that includes:
     - [ ] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
     - [ ] The docket numbers of each of the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [ ] For the cases that were selected in the modal for Test Case 3.2, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
     


#### 4) Docket Clerk is in the lead case of a consolidated group and adds a docket entry (with a document that generates a cover sheet), then clicks Cancel. Document is saved to the drafts folder of lead case, is not added to any other case in consolidated group. 
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload 
- Upload a PDF and click Save 
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet: **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Cancel


Expected Results
- [ ] You are navigated back to the drafts tab of the lead case in the CG.



#### 5)  Docket Clerk is in the lead case of a consolidated group and adds a docket entry (with a document that generates a cover sheet); modal appears for clerk to select additional cases to file the document in, but then docket clerk clicks "No, take me back".
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload 
- Upload a PDF and click Save 
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet: **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Save Entry
- On the Pop-up, click "No, take me back"

Expected Results
- [ ] DAWSON navigates back to the Add Docket Entry screen


#### 6) Docket Clerk adds a docket entry (with a document that generates a cover sheet) in a case that is in a consolidated group, but it is not the lead case.  Add docket entry workflow does not include the new modal, and docket clerk does not have the ability to file the document in other cases in the group.
- Log in as a Docket Clerk
- Navigate to a case that is in a consolidated group, and be sure that the case is NOT the lead case. (I used case 17495-17)
- Click Create and select PDF Upload 
- Upload a PDF and click Save
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet: **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Save Entry

Expected Results:
- [ ] Document saves to the docket record
- [ ] The new pop up modal that states "Are you ready to Save this Document to the Docket Record?" does NOT appear. 



#### 7.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload 
- Upload a PDF and click Save 
- Click Add Docket Entry from the drafts page
- Select one of these document types that include a cover sheet: **(NEW FUNCTIONALITY with these docs)**
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)
- Add a description and filed date
- Click Save Entry

Expected Results
- [ ] **NEW FUNCTIONALITY** Updated modal matches the wording in the mock up above, and has the checkbox checked for "All in the consolidated group" checked.
- [ ] **NEW FUNCTIONALITY** There is NOT a list of parties that receive paper service on this modal


#### 7.2) Docket Clerk selects ONLY the lead case from the consolidated group to file the document in
- Continuing from test case 7.1
- Uncheck the first checkbox for "All in the consolidated group"

Expected Results
- [ ] The lead case checkbox will be unselectable and will remain checked.
- [ ] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"


#### 7.3) Upon save, the docket entry is saved to the docket record of ONLY the lead case, and a cover sheet is added to the document.
- Continuing from test case 7.2
- Click Yes, Save
- From the docket record of the lead case, open up the document that was just saved.

Expected Results:
- [ ] You will be routed back to the docket record of the lead case
- [ ] ** NEW FUNCTIONALITY** Green banner that states "Document saved to selected cases in group."
- [ ] **NEW FUNCTIONALITY** The one document on the lead case will have a cover sheet that includes:
     - [ ] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
     - [ ] For the lead case only, the docket entry position of the document has the "Document No." listed after the Docket number.
- [ ] **NEW FUNCTIONALITY** Ensure that the document number that is represented on the cover sheet matches the document number on the docket record of the lead case.


#### 8) Docket Clerk is in the lead case of a consolidated group and adds a docket entry (with a document that DOES NOT generates a cover sheet); modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload 
- Upload a PDF, add a description, and click Save 
- Click Add Docket Entry from the drafts page
- Select a document types that is unservable, but does not include a cover sheet (example: Online Cited Source, Corrected Transcripts, etc.) **(NEW FUNCTIONALITY with these docs)**
- Add a description and filed date
- Click Save Entry

Expected Results
- [x] **NEW FUNCTIONALITY** Updated modal matches the wording in the mock up above, and has the checkbox checked for "All in the consolidated group" checked.
- [x] **NEW FUNCTIONALITY** There is NOT a list of parties that receive paper service on this modal



#### 8.2) Docket Clerk selects all other cases from the consolidated group to save the docket entry into.
- Continuing from test case 8.1
- Leave the checkbox checked for "All in the consolidated group"
- Select Yes, Save
- From the docket record of the lead case and the other cases that in the group, open up the document that was just saved.

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] ** NEW FUNCTIONALITY** Green banner that states "Document saved to selected cases in group."


#### 8.3) Document is reflected appropriately on the docket record for the lead case and the selected cases.
- Continuing from test case 8.2
- Review the document details on the docket record

Expected Results 
- [x] On the lead case, the document is attributed with index #, date, title, pages, and has the edit/seal links (There will not be any data in the column for action, served date, or served parties).
- [x] On the one other case in the CG that was selected, the document is attributed the exact same way on the docket record as in the lead case (index number may vary).


#### 8.4) Documents in the non-lead case are the same as the document in the lead case.
- Continuing from test case 8.3
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other cases that you filed the document in
- Click on the URL of the document
- Click on the URL to View Full PDF
- This will open the document in a new tab

Expected Results
- [x] Both documents should be exactly the same
- [x] Both documents should share the same document ID
- [x] No cover sheet will be on these documents

**Comment by shumway-tm** [comment]
Started prep work on story. Will continue pending path taken in ustaxcourt/ef-cms#6969.

**Comment by codyseibert** [comment]
I talked with @halprin about this story and there are a couple of things we want to clear up with @cholly75 before we continue working on this feature.  We are confused why the modal pops up for the `save entry` button, but it was discussed that only serving it would show the modal.

**Comment by cholly75** [comment]
Comments from Court post-demo: decision was made to NOT reflect on the cover sheet caption any docket numbers in the consolidated group that the document was NOT filed in. Spoke w/ Cody, sending back to In Progress.

CC: @ttlenard - will need to adjust test cases to account for direction change w/r/t docket numbers captured on the, er, caption.

**Comment by ttlenard** [comment]
@cholly75 Test cases above have been updated to reflect the changes suggested.  Docket numbers that were NOT selected in the modal should not be reflected on the cover sheet.
