### ISSUE TITLE
Text Additions to Support Online Cited Sources

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8204]
As a court, so that DAWSON users can locate online sourced citations used in orders and opinions, I need to add verbiage to several publicly accessible DAWSON pages.

To message to users where online sourced citations can be found, we need to add text to several public-facing DAWSON pages explaining that they can be found on the docket record.

See attached screenshots from the Court memo for visual mockups.

## Pre-Conditions
ustaxcourt/ef-cms#8202

## Acceptance Criteria
* "Today's Opinions" page is updated with the following text directly below the date:
  - "Any online sourced citations in these opinions can be viewed directly from the associated docket record"
* Opinion Search page is updated with the following text as the second sentence after "Anyone can search for an opinion in our system for cases filed on or after May 1, 1986":
  - "Any online sourced citations in opinions filed after [DATE TBD] can be viewed directly from the associated docket record"

## Notes
* DATE TBD value will need to be determined based on anticipated go-live date of ustaxcourt/ef-cms#8202
* Cannot go live prior to 6/22/22

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/1b11063d-e567-4014-9419-a23fb71af87a)

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/0791a53d-c5cd-49a1-aaa1-7ad609097ec5)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Test cases reviewed by an engineer on a deployed environment for Engineering Review.
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Today's Opinions page has updated text that refers to the Online Cited Sources.

-  Go here to the TEST URL for Today's Opinions [https://test.ef-cms.ustaxcourt.gov/todays-opinions]

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The page now has updated text below the date that states, "Any online sourced citations in these opinions can be viewed directly from the associated docket record"

#### 2) Opinion Search page has the updated text that refers to the Online Cited Sources.

**Public non-logged in user** 
- Go to the DAWSON Opinion search page here: [https://test.ef-cms.ustaxcourt.gov/]

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The page now has updated text as the second sentence after "Anyone can search for an opinion in our system for cases filed on or after May 1, 1986" that states, "Any online sourced citations in opinions filed after [DATE TBD] can be viewed directly from the associated docket record"
- [ ] **NEW FUNCTIONALITY** - The "DATE TBD" field will have an actual date added, and will depend on the date that this is implemented.

**Private Practitioner and IRS Practitioner** - be sure that you test with both roles
- Log in to DAWSON
- Click on the Advanced Search link in the upper right hand corner of the screen
- Click on the Opinion Tab

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The page now has updated text as the second sentence after "Anyone can search for an opinion in our system for cases filed on or after May 1, 1986" that states, "Any online sourced citations in opinions filed after [DATE TBD] can be viewed directly from the associated docket record"
- [ ] **NEW FUNCTIONALITY** - The "DATE TBD" field will have an actual date added, and will depend on the date that this is implemented.

**Court Staff**
- Log in to DAWSON
- Click on the Advanced link in the upper right hand corner of the screen
- Click on the Opinion Tab

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The page now has updated text as the second sentence after "Anyone can search for an opinion in our system for cases filed on or after May 1, 1986" that states, "Any online sourced citations in opinions filed after [DATE TBD] can be viewed directly from the associated docket record"
- [ ] **NEW FUNCTIONALITY** - The "DATE TBD" field will have an actual date added, and will depend on the date that this is implemented.
