### ISSUE TITLE
BUG: Unable to download all cases on a trial session

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8208]
**Describe the Bug**
Users assigned to a Trial Session are unable to download all cases in the trial session.  The Compressing Case Files will go to 100% (or sometimes it will go over 100% - see screen grab below), but then the user never get's the opportunity to open a zipped folder.

Note - the last download that the DAWSON team has was from 5/20/22, so it appeared to have worked then?
Note- this is working on MIG, but not Test or Prod

**Business Impact/Reason for Severity**
High Severity

This impacts Judges, CA's, Trial clerks that are in a trial session at a location with limited/no wifi.  They need access to case documents.

**In which environment did you see this bug?**
TEST and Prod 
Note: This is working in MIG

**Who were you logged in as?**
Judge, CA, Trial Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Log in as a Judge, CA, or trial clerk
2. Open an upcoming trial session
3. Click on Download all cases
4. the compressing case files progress bar will get to 100% (or more), but nothing happens for the user, and no zip file is available for download.

**Expected Behavior**
When users click on download all cases, they should be able to open a zip folder with all the cases and documents.

**Actual Behavior**
A clear and concise description of what actually happened.
The compressing case files get's stuck, and the user isn't presented with a way to download a zip file.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5dd1d2b4-9e45-45e2-8230-d5e40c1cec0a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by halprin** [comment]
[PR created](https://github.com/ustaxcourt/ef-cms/pull/2304).

**Comment by halprin** [comment]
[Better PR](https://github.com/ustaxcourt/ef-cms/pull/2309) created to `test`.

**Comment by mmarcotte** [comment]
this has been deployed
