### ISSUE TITLE
BUG: IRS and Private Practitioners experience a white screen when attempting to search for a sealed case by docket number

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8209]
**Describe the Bug**
As a logged in practitioner, if I attempt to search for a sealed case by docket number using either the "Search for a case" on the "My Cases" dashboard, or if I search for a sealed case by docket number in any of the tabs in the Advanced Search area, then I receive a white screen (see screen captures below).

**Business Impact/Reason for Severity**
Medium

**In which environment did you see this bug?**
Prod, Test, Mig

**Who were you logged in as?**
IRS Respondent
Private Practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application - this was reported by an IRS Practitioner

**To Reproduce**
1. Log in as a Private Practitioner or an IRS Respondent
2. From the My Cases Dashboard, enter in a docket number of a sealed case (ex: 9771-22)
3. You will get a white screen.
4. To get out of the white screen, you will need to update the url back to the dawson main page and click enter.
5. From your My Cases Dashboard, click on advanced search.
6. If you type in the docket number of a sealed case on any of the tabs, you will receive a white screen.

**Expected Behavior**
There should be the "This case is sealed..." message for the practitioner instead of a white screen

**Actual Behavior**
A clear and concise description of what actually happened.
A white screen appears and the user cannot get out of it smoothly.

**Screenshots**

This is the white screen that appears after searching for a sealed case by docket number, along with the error message from the console:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5bbcf808-a243-4611-99e5-edf36a46faa8)

This is what the public non logged in user sees if they attempt to view a sealed case: 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/71a9ac81-25f9-4395-874f-651f99e8c2ec)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by cholly75** [comment]
@mrinsin - the sealed case UI now displays for private/IRS practitioners, however the My Cases link to take the user back to their dashboard is nonfunctional on the screen. Clicking the "back" button in the browser results in a 400 error. Tested in TEST by logging in as either of the two pracs and searching for 4818-19. Let me know if you want me to show you. Thanks!
