### ISSUE TITLE
Court: Restrict Tracked Items Operations to Docket/Clerk of the Court roles

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8211]
As a court, so that I can prevent tracked items from being improperly edited or removed, I need to restrict the Edit, Delete, and Remove operations to specific roles.

The Tracked Items tab on the Case screen displays both Deadlines and docket entries that are tracked on the Pending Report; these are important to the Court in that they often represent actions that need to be taken by parties or the Court itself, and they ensure that the case itself continues to move through the appropriate steps.

Currently, all roles are able to edit or delete these Tracked Items, and the Court needs to lock down these permissions to a specific set of roles; we would like to make these operations available only to roled Docket users and Clerk of the Court users. 

## Acceptance Criteria
* On the Deadlines tab of the Tracked Items view for a case, the Edit link only displays for Docket or Clerk of the Court roles
* On the Deadlines tab of the Tracked Items view for a case, the Delete link only displays for Docket or Clerk of the Court roles
* On the Pending Report tab of the Tracked Items view for a case, the Remove link only displays for Docket or Clerk of the Court roles
* No functionality changes in these links - they continue to operate as normal for Docket and Clerk of the Court roles

## Notes
Deadlines tab view:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/a8891513-5b65-4c98-9b7c-7ba44e667f54)

Pending Report tab view:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/cbe37ed2-7c29-48ed-ae91-8ab5338abbcf)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk and Clerk of the Court Creates a deadline; The Edit link on the Tracked Items/Deadlines tab on a case is available.

- Log in as a Docket Clerk (will need to repeat this test by logging in as the Clerk of the Court as well)
- Navigate to a case 
- Click on the Tracked items tab
- Be sure that you are on the deadlines sub-tab.
- Click on Create
- Select Deadline
- Fill in the Deadline details and then click save

Expected Results:
- [ ] The edit button is available next to the deadline
- [ ] Clicking the edit button allows you to edit the date, the description of the deadline, and you are able to save the deadline.

*Repeat this test by logging in as the Clerk of the Court.

#### 2) Court staff (besides Docket Clerk and Clerk of the Court) creates a Deadline; The Edit link on the Tracked Items/Deadlines tab on a case is NOT available.

- Log in as a Petitions Clerk (will need to repeat this test by logging in as the other court users (ADC, Chambers, Judge, Trial Clerk, Admissions, Floater)
- Navigate to a case 
- Click on the Tracked items tab
- Be sure that you are on the deadlines sub-tab.
- Click on Create
- Select Deadline
- Fill in the Deadline details and then click save

Expected Results:
- [ ] **NEW FUNCTIONALITY** The edit button is NOT available next to the deadline


*Repeat this test by logging in as all the other court user roles


#### 3) Docket Clerk and Clerk of the court Creates a Deadline; The Delete link on the Tracked Items/Deadlines tab on a case is available for Docket and Clerk of the Court Roles

- Log in as a Docket Clerk (will need to repeat this test by logging in as the Clerk of the Court as well)
- Navigate to a case 
- Click on the Tracked items tab
- Be sure that you are on the deadlines sub-tab.
- Click on Create
- Select Deadline
- Fill in the Deadline details and then click save

Expected Results:
- [ ] The delete button is available next to the deadline
- [ ] Clicking the delete button brings up the "are you sure" modal, where you can select "yes, Delete" and the Deadline will be deleted.

*Repeat this test by logging in as the Clerk of the Court.

#### 4) Court staff (besides Docket Clerk and Clerk of the Court) creates a Deadline; The Delete link on the Tracked Items/Deadlines tab on a case is NOT available for any other Court role except for Docket and Clerk of the Court Roles.

- Log in as a Petitions Clerk (will need to repeat this test by logging in as the other court users (ADC, Chambers, Judge, Trial Clerk, Admissions, Floater)
- Navigate to a case 
- Click on the Tracked items tab
- Be sure that you are on the deadlines sub-tab.
- Click on Create
- Select Deadline
- Fill in the Deadline details and then click save

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The delete button is NOT available next to the deadline

*Repeat this test by logging in as all the other court user roles

#### 5) Docket Clerk or Clerk of the Court adds a Paper filing; Checks the box for "Add to Pending Report; The Remove link on the Tracked Items/Pending report tab on a case is available for Docket and Clerk of the Court Roles
- Log in as a Docket Clerk (will need to repeat this test by logging in as the Clerk of the Court as well)
- Navigate to a case 
- Click on Create
- Select Paper filing
- Upload a document and fill out the information about the filing
- Be sure that you select the box for "Add to Pending Report"
- Click Save and Serve
- Navigate to the Tracked items tab
- Click on the Pending Report Sub-tab

Expected Results:
- [ ] The Remove button is available next to the Pending Item
- [ ] Clicking the Remove button brings up the "are you sure" modal, where you can select "yes, Remove" and the Pending Item will be removed.

*Repeat this test by logging in as the Clerk of the Court.


#### 6) The Remove link on the Tracked Items/Pending report tab on a case is NOT available for any other Court Role except for Docket and Clerk of the Court Roles

This Test has some preconditions:
- You will need to be sure that you are a docket clerk first, and add a paper fililng that has a pending item on a case.

Now the test is ready:
- Log in as a Petitions Clerk (will need to repeat this test by logging in as the other court users (ADC, Chambers, Judge, Trial Clerk, Admissions, Floater)
- Navigate to a case 
- Navigate to the Tracked items tab
- Click on the Pending Report Sub-tab

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Remove button is NOT available next to the Pending Item
