### ISSUE TITLE
Letter of Appeal

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8216]
As a docket clerk handling appeals, so that I can accurately represent appeals documentation on the docket record, I need a new type of docket entry.

When a case goes to appeal, the Court is required to document the letter from the appeals court notifying the USTC that the case docket has created and entered in the appeals court. Currently the letter is being uploaded and a cover sheet generated manually, and these are being docketed as MISC or ROA (Record of Appeal). We would like a new docket entry type to provide these uploaded letters with an appropriate cover sheet and document type.

## Acceptance Criteria
* Letters of Appeal are always entered initially into DAWSON via the PDF Upload functionality
* A new document type is available for selection when adding a draft PDF as a docket entry: "Letter of Appeal"
* Docket clerks are able to add a Description for these documents that will display in the "Filings and Proceedings" column on the docket record
* Docket clerks are able to add a Filed Date for the docket entry
* Documents created with this document type are visible on the docket record with event code: "LOA"
* LOA entries receive cover sheets.
* LOA cover sheets display "Letter of Appeal" followed by the description (if any) entered by the docket clerk.
* LOA entries are never served to any parties when added to the docket record.
* LOA entries cannot be served after being added to the docket record.
* LOA documents are visible and hyperlinked for all court users, parties on the case and counsel for those parties when viewing the docket record.
* LOA documents obey all other visibility rules (i.e., sealing at the case/document level

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Clerk uploads a PDF; New Document type and descriptive information for Letter of Appeal document is available when adding a docket entry.

- Log in as a docket clerk
- Navigate to a case
- Click on the Create Menu
- Select PDF Upload
- Upload a document and put in some description text
- Click Save
- On the drafts page, click Add docket entry.

Expected Results
- [x] **NEW FUNCTIONALITY** - A new selection is available in the dropdown titled "Letter of Appeal"
- [x] Description field is available for clerk to add in descriptive information about the document
- [x] Filed Date field is available for clerk to add in the date filed.

#### 2) Clerk saves the entry to the docket record; LOA document is not served, but available the the public and parties on the case on the docket record.

- Continuing from Test Case 1
- Be sure that you have selected Letter of Appeal as the document type, added a description, and added a Filed Date.
- Click Save Entry

Expected Results
- [x] Green confirmation that states, "Your entry has been added to the docket record."
- [x] The LOA document that you just saved should have a docket index number that is next in the sequence
- [x] The LOA document that you just saved should have the Date that you selected for the date filed 
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is "LOA"
- [x] **NEW FUNCTIONALITY** - The Filings and Proceedings Column text should state "Letter of Appeal", followed by the text that you entered in the description field.
- [x] Page count should reflect the total pages of the document uploaded
- [x] The filed by, Action, Served, and Parties columns should be blank
- [x] The last column should have the options for Edit and Seal.

#### 3) LOA document on the docket record is hyperlinked and is available to view by any court staff.

- Log in as any court user (besides docket clerk, be sure that you test with multiple court roles)
- Navigate to the case you used in test case 1&2.

Expected Results
- [x] **NEW FUNCTIONALITY** The LOA document is hyperlinked on the docket record
- [x] The LOA document opens in the document view panel if you click on the hyperlink
- [x] LOA Document includes a coversheet.
- [x] Usual coversheet content (docket #, Case Caption, etc.) + it should have the title "Letter of Appeal" followed by the description (if any) entered by the docket clerk


#### 4) LOA document on the docket record is hyperlinked and is available to view by parties on the case

This test has some set up steps:
- Log in as a docket clerk
- Navigate to the case you used in test case 1&2
- Click on Case information tab
- Click on Parties tab
- Add a Petitioner that you have a login for (I used Petitioner 1)
- Add in a Private Practitioner that you have a login for (I used PT4444 - private practitioner 6)
- Add in an IRS Practitioner that you have a login for (I used RT6666 - irs practitioner 6)

Now the test is set up:
- Log in as the Petitioner that you added in the steps above
- Click on the docket number of the case that was used in Test case 1

Expected Results
- [x] **NEW FUNCTIONALITY** The LOA document is hyperlinked on the docket record
- [x] The LOA document opens in a new tab if you click on the hyperlink
- [x] LOA Document inlcudes a coversheet.
- [x] Usual coversheet content (docket #, Case Caption, etc.) + it should have the title "Letter of Appeal" followed by the description (if any) entered by the docket clerk

Next:
- Repeat this test with the Private Practitioner and the IRS Practitioner.

#### 5) LOA document is on the docket record; document is not viewable by the public.

- Do not log in, this test is with a general public user
- On the DAWSON landing page, in the case search area, type in the docket number of the case you used in Test case 1
- Click search

Expected Results:
- [x] **NEW FUNCTIONALITY** The LOA document is on the docket record
- [x] The LOA document does not include a hyperlink for public non logged in users


#### 6) LOA document on a sealed case is NOT available to view by the general public

This test case has some set up:
- Log in as a docket clerk
- Navigate to the case you used in test case 1
- Click on the case information tab
- Click on Seal Case
- Confirm that you would like to seal it.

Now the test is ready:
- Do not log in, this test is with a general public user
- On the DAWSON landing page, in the case search area, type in the docket number of the case you used in Test case 1
- Click search

Expected Results:
- [x] You should get a page that indicates that the case is sealed and not available to the public.


#### 7) LOA document is sealed to the public by a docket clerk (case is NOT sealed); document is not available for viewing by a member of the public; document is available for viewing by parties of the case.

This case has some set up:
- Log in as a docket clerk
- Navigate to the case you used in test case 1
- Click on Case information
- Unseal the case at the case level (you will need to do this if using the same case you used in test case 6)
- Confirm that you would like to unseal the case
- Click on the docket record tab
- Click the seal link on the LOA document on the docket record
- Ensure that the radio button indicates Seal to the public
- Click Seal

Now the test is ready:
- Do not log in, this test is with a general public user
- On the DAWSON landing page, in the case search area, type in the docket number of the case you used in Test case 1
- Click search

Expected Results:
- [x] The case should open up, but there will be a red lock icon next to the LOA document on the docket record.
- [x] The LOA document will NOT be hyperlinked, and the public user will not be able to open the document for viewing.

Next:
- Log in as one of the parties of the case (Petitioner, Private Practitioner, IRS Practitioner)
- Click on the docket number of the case

Expected Results:
- [x] **NEW FUNCTIONALITY** The LOA document is hyperlinked on the docket record
- [x] The LOA document opens in a new tab if you click on the hyperlink
- [x] LOA Document inlcudes a coversheet.
- [x] Usual coversheet content (docket #, Case Caption, etc.) + it should have the title "Letter of Appeal" followed by the description (if any) entered by the docket clerk


#### 9) LOA document is sealed to the public and parties of the case by a docket clerk (case is NOT sealed); document is not available for viewing by the public or parties of the case.

This case has some set up:
- Log in as a docket clerk
- Navigate to the case you used in test case 1
- Click the unseal link on the LOA document on the docket record
- Confirm that you would like to unseal
- Click on the Seal link
- Ensure that the radio button indicates Seal to the public and parties on the case
- Click Seal

Now the test is ready:
- Do not log in, this test is with a general public user
- On the DAWSON landing page, in the case search area, type in the docket number of the case you used in Test case 1
- Click search

Expected Results:
- [x] The case should open up, but there will be a red lock icon next to the LOA document on the docket record.
- [x] The LOA document will NOT be hyperlinked, and the public user will not be able to open the document for viewing.

Next:
- Log in as one of the parties of the case (Petitioner, Private Practitioner, IRS Practitioner)
- Click on the docket number of the case

Expected Results:
- [x] The case should open up, but there will be a red lock icon next to the LOA document on the docket record.
- [x] The LOA document will NOT be hyperlinked, and the parties on the case will not be able to open the document for viewing.


#### 10) Regression test with the Test Cases on 9501 (unservable consolidated case documents)

**Comment by cholly75** [comment]
Test looks fine - need to confirm w/ appellate clerk criteria have been met

**Comment by cholly75** [comment]
@mrinsin - 2 requested changes from the business from demo:

1) Change event code from "LOA" to "LS"
2) The generated title on the cover sheet should just be "Letter" followed by the description field text

Thanks!
