### ISSUE TITLE
Blocked Cases Report: Display Consolidation Status

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8219]
As a docket clerk, so that I can tell which blocked cases are part of a consolidated group, I need to signify the consolidated status of a case on the Blocked Cases report.

When setting calendars, the Clerk of the Court and docket review the Blocked Cases report to review and potentially remedy any blocks prior to creating trial sessions, as a Blocked Case will not be shown on the Eligible Cases list for calendaring. When a case is part of a consolidated group, the preference is to take the entire group to trial at the same time; thus, any blocked cases in the group should be addressed to make this possible. To reduce manual effort in verifying all cases in the group for block status and prevent miscalendaring part but not all of a group, we would like to call out the consolidated status of cases appearing on the Blocked Cases report.

## Acceptance Criteria
* When cases are displayed on the Blocked Cases report, if a case is a Lead or Member case of a consolidated group then it is signified as such (preference is to use the same iconography for this as we do with messages)
* No other functionality changes to the Blocked Cases report

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user selects a city for the Blocked Cases report, Lead Case in the group is blocked; Lead case indicator displays next to docket number.
This test case has some set up:
- Log in as a docket clerk
- Navigate to the lead case in a consolidated group (I used 22447-16)
- Click on the Case Information tab
- Click on "Add Manual Block"
- Add a reason, and then click "Block Case"
- Now the test is ready

- Click on the "Reports" menu
- Select Blocked Cases Report
- Select Atlanta, Georgia (or whatever preferred trial location is for the case you used for adding a manual block)

Expected Results:
- [x]  Lead case indicator is present next to the docket number of the lead case in the consolidated group that is blocked.


#### 2) Court user selects city for the Blocked Cases report, Member case in the group is blocked; Member case indicator displays next to docket number.
This test case has some set up:
- Log in as a docket clerk
- Navigate to a member case in a consolidated group (I used 22449-16)
- Click on the Case Information tab
- Click on "Add Manual Block"
- Add a reason, and then click "Block Case"
- Now the test is ready

- Click on the "Reports" menu
- Select Blocked Cases Report
- Select Atlanta, Georgia (or whatever preferred trial location is for the case you used for adding a manual block)

Expected Results:
- [x]  Member case indicator is present next to the docket number of the member case in the consolidated group that is blocked.


#### 3) Court User removes the block on the lead case in the group; Case is no longer present on the Blocked Cases Report.
- Log in as a docket clerk
- Navigate to the Lead case in a consolidated group that you added a block to previously (I used 22447-16)
- Click on the Case Information tab
- Click on "Remove Block"
- Confirm that you want to remove the block
- Click on the "Reports" menu
- Select Blocked Cases Report
- Select Atlanta, Georgia (or whatever preferred trial location is for the case you used for adding a manual block)

Expected results
- [x] The lead case in the consolidated group should no longer appear on the blocked cases report


#### 4) Court User removes the block on the Member case in the group; Case is no longer present on the Blocked Cases Report.
- Log in as a docket clerk
- Navigate to a member case in a consolidated group that you added a block to previously (I used 22449-16)
- Click on the Case Information tab
- Click on "Remove Block"
- Confirm that you want to remove the block
- Click on the "Reports" menu
- Select Blocked Cases Report
- Select Atlanta, Georgia (or whatever preferred trial location is for the case you used for adding a manual block)

Expected results
- [x] The member case in the consolidated group should no longer appear on the blocked cases report

**Comment by rgoshen** [comment]
When this story (9544) is combined with story 3318, it causes the table to shift when filtering by case type.  We need to fix it in 9544 so this does not happen.

**Comment by rgoshen** [comment]
Per Chris Holly, he is not worried about the table shift...it is good to go.
