### ISSUE TITLE
BUG: Clinic letters that are more than one page are getting appended to NOTR in some instances

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8222]
**Describe the Bug**

If a clinic letter has > 1 page (when a clinic letter has both English and Spanish instructions, see Washington DC, Nashville, TN) and if there are multiple petitioners on a case where one petitioner is represented and the other isn't, and the private practitioner is receiving paper service for that case, then the first page of the clinic letter is getting appended to the NOTR on the print for paper service screen.

Cody mentioned that he saw in the code that when a practitioner is representing a petitioner on a case, it says something to the effect of removing the last page on the Notice of Trial - which in many instances DOES remove the clinic letter, but does not remove clinic letters in their entirety for letters that are more than one page in length at the print for paper service step.

Most practitioners receive electronic service, but they CAN file a motion in a case to be exempted from electronic service, and CAN have paper service. If this happens, they should not be receiving clinic letter information. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
TEST

**Who were you logged in as?**
Petitions clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Cody found this one in the code, Tenille verified it!

**To Reproduce**
1. Log in as a petitions clerk
2. Click on trial sessions
3. Click on add trial session
4. Create a new trial session with a city that has a clinic letter that has greater than 1 page (Washington, DC has two pages).
5. Next, find a case in the eligible case list that has multiple petitioners (Petitioner and Spouse case) receiving paper service.
6. Open the case and click on Case information, then click the parties tab
7. Edit the parties by adding a practitioner to only one party and then be sure that the practitioners service preference to paper on the selected case
8. Go back to the eligible case list
9. Be sure that you check the box for this case
10. Set the calendar
11. Notice on the print for paper service screen, you will see that the private practitioner receives the first page of the DC clinic letter. (this shouldn't be there)
12. Next, navigate to the case and open the docket record
13. Click on the Notice of trial document
14. In the document preview, notice the entire clinic letter is present since the other petitioner on the case isn't represented. (this is expected behavior)

**Expected Behavior**
Clinic letters in their entirety need to be removed from the print for paper service notice of trial document if a petitioner is represented by counsel that has paper service

**Actual Behavior**
A clear and concise description of what actually happened.
the first page of the clinic letter is present on the print for paper service screen for the practitioner receiving paper service.  only the second page is removed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by TomElliottFlexion** [comment]
Note: document in question is eventCode = `NTD`. `NOTR` should be Notice of Receipt of Petition
