### ISSUE TITLE
Trial Clerk: Assign non-clerk personnel to Trial Sessions

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8224]
As a trial clerk, so that I can accurately document when a non-regular trial clerk assumes that role for a particular trial session, I need to be able to enter the name on the Trial Session.

Frequently court personnel with prior experience in the role are assigned as trial clerks to a trial session despite not being a regular trial clerk (typically due to personnel shortages or scheduling conflicts). In these situations, we would like to be able to document the name of the person filling in as trial clerk for the session (known informally as a "filler" clerk); currently, only court users with a role of Trial Clerk are selectable in the dropdown menu to be associated with the Trial Session.

## Acceptance Criteria
* When editing or creating a trial session, a user can indicate that a user other than the ones presented on the dropdown list in the Trial Clerk field is fulfilling the role of trial clerk for that session
* When doing so, the "filler" clerk's first and last name are attached to the Trial Session as if it had been selected from the dropdown menu in the Trial Clerk field
* User enters the name of the person manually - we do not want a dropdown of every DAWSON court user possible
* "Filler" clerk's name is displayed everywhere we would expect to see a "usual" trial clerk's name when attached to a Trial Session

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Met with some devs to discuss technical feasibility and decided to wait until it's picked up in Ready for Engineering to dig deeper. Tenille will wait until a solution is proposed to write test cases.

**Comment by TomElliottFlexion** [comment]
From discussion with UX:
- "Filler Clerk" (or other placeholder) will appear in the trial clerk selection dropdown
- Selecting this option will unveil a text box to enter the name of the "filler clerk"
- Text box will match the style of others in the same subsection, and appear either to the right or underneath the aforementioned dropdown
@swongCO @liadmccabe

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user edits an upcoming Trial Session; Selects "Other" in the Trial Clerk dropdown, Adds a "filler" trial clerk name.

- log in as a Court User
- Click on Trial Sessions
- From the Open tab, Select a trial session that is in the future
- Click on the Edit link to edit the trial session
- Click on the Trial Clerk Dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** Option available to select "Other" from the dropdown list of Names
- [x] **NEW FUNCTIONALITY** - When "Other" is selected, a free text field is available to the user to enter a "Filler" clerks first and last name.


#### 2) After adding a "Filler" Trial Clerk; Save the Trial Session; Filler Trial Clerk's Name appears on Assignments Card on the Session Info Page

- Continuing from the previous test
- Save the trial session

Expected Results
 - **NEW FUNCTIONALITY** - The Filler trial clerk's name that you typed in is located in the Assignments card


#### 3) Petitions Clerk adds a new Trial session, Selects "Other" in the Trial Clerk dropdown, Adds a "Filler" trial clerk name.

- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click Add new trial session
- Fill out the trial session info
- Click on the Trial Clerk Dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** Option available to select "Other" from the dropdown list of Names
- [x] **NEW FUNCTIONALITY** - When "Other" is selected, a free text field is available to the user to enter a "Filler" clerks first and last name.


#### 4) After adding a "Filler" Trial Clerk on the New Session; Save the Trial Session; Filler Trial Clerk's Name appears on Assignments Card on the Session Info Page

- Continuing from the previous test
- Save the trial session

Expected Results
 - **NEW FUNCTIONALITY** - The Filler trial clerk's name that you typed in is located in the Assignments card


#### 5) "Filler" Trial Clerk can be edited and replaced with either a different Filler, or a Trial Clerk from the dropdown menu.

Part 1
- Continuing from one of the previous test cases
- Edit a trial session (new or open) that you added a Filler Trial Clerk in
- Select a Trial Clerk Name that is in the dropdown

Expected Results
- [x] The filler trial clerk name is no longer associated or saved with the record
- [x] The filler trial clerk name no longer appears on the assignments card upon save of the updated trial session

Part 2
- Edit a trial session (new or open) again 
- Select Other from the dropdown

Expected Results
- [x] **NEW FUNCTIONALITY** - The filler trial clerk name is now associated with the session
- [x] The Trial clerk that was previously assigned is no longer associated or saved with the record
- [x] **NEW FUNCTIONALITY** - The previous trial clerk name no longer appears on the assignments card upon save of the updated trial session, it is replaced with the filler trial clerk's name.

**Comment by swongCO** [comment]
UX feedback: Please remove the asterisk after "Other"
