### ISSUE TITLE
Stamp Order: Add Hyphens On Stamp Clauses

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8237]
As a judge, so that my stamp orders are stylistically uniform, I need to add hyphens to the beginning and end of the "due date" and free text clauses on the printed stamp.

This is a request from the judges to add the hyphens bookending individual stamp clauses on the stamp that gets applied to a stamp order (see screenshot below) to any "due date" clauses and free text clauses added to the stamp.

## Acceptance Criteria
* When a radio button for either of the "due date" clauses on the Apply Stamp screen is selected, the clause inserted into the stamp is bookended by hyphens
* When free text is entered in the Optional Text field on the Apply Stamp screen, the clause inserted into the stamp is bookended by hyphens
* As per original design, no line should wrap in the stamp display

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/2e3269b6-b37c-4f45-a00f-56d733c92b5c)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Stamp is added to a motion; Radio button is selected in the "Due Date" section and date is added; Stamp preview shows this text bookended with hyphens.

This test has some set up:
- Log in as a docket clerk
- Navigate to a case
- Click on Create
- Select Paper Filing
- Upload a document, and be sure to categorize the document type as a motion 
- Save and Serve the document
- Send a message with the motion you just loaded as an attachment to a Judge/CA/ADC user

Now the test is ready:
- Log in as the user you sent the message to in the previous step.
- Click on the motion document from the message
- Click apply stamp
- Fill out some details, be sure that you select the radio button for the "Due Date" section and add a date.
- Repeat this test by selecting BOTH radio button options to ensure that the expected results work for both radio buttons when selected.

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The text that is added in the stamp preview is bookended with hyphens
- [ ] **NEW FUNCTIONALITY** - The text does not wrap


#### 2) Stamp is added to a motion; Free text is added; Stamp preview shows this free text bookended with hyphens.

- Continuing from the previous test
- Add in some free text to the Stamp and ensure that you use the 60 characters

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The text that is added in the stamp preview is bookended with hyphens
- [ ] **NEW FUNCTIONALITY** - The text does not wrap


#### 3) Stamp is saved; Hyphens separate out the text in the document title in the draft, and in the message attachments.

This is a regression test to ensure that the title still has the hyphens (it did before this story)
- Continuing from the previous test
- Save the stamp
- Review the title of the new document from the message attachment and from the Drafts tab

Expected Results:
- [ ] The title of the document has the text from each section of the apply stamp page separated out by hyphens


#### 4) Stamp is Served and added to the docket record; Hyphens appear in the document title, Text is bookended with hyphens on the stamp itself.

- Continuing from the previous test
- Send a message to the docket clerk and ensure that the draft stamp order is attached.
- Log in as a docket clerk
- Navigate to the case that you created the stamp Order in
- Click on the stamp order (from a message attachment or from the drafts)
- Click add docket entry
- Serve the stamp Order

Expected Results
- [ ] Document title on the docket record has hyphens that separate out each section from the stamp details
- [ ] **NEW FUNCTIONALITY** - The Stamp Order text (due date and free text sections) in the document is bookended by hyphens
- [ ] **NEW FUNCTIONALITY** - The Stamp Order text does not wrap within the Stamp box.
