### ISSUE TITLE
Stamp Disposition: Make Stamp Disposition Available on Withdrawal Motions

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8243]
As a chambers, judge, or ADC user, so that I can stamp grant or deny motions for counsel appearances and withdrawals , I need to be able to apply stamp orders to motions that fall under the category "Appearance and Representation".

In developing ustaxcourt/ef-cms#8336, there were certain motions classified in DAWSON as "Appearance and Representation" documents outside of the pool of other motions; it was decided that we would extend the stamp functionality to these types of motions in a future story.

Welcome to the future! We would like to extend the ability to apply stamps to the following documents/event codes:

Motion to Withdraw as Counsel (M112)
Motion to Withdraw Counsel (M116)

All functionality developed for ustaxcourt/ef-cms#8336 should be applicable to these types of motions in DAWSON. There are no requested changes to the stamp disposition functionality itself, we simply want to include these two motions in the subset of documents that can be "stamped".

## Acceptance Criteria
* When viewing an M112 document, a judge, chambers, or ADC user can see and click the Apply Stamp link as per ustaxcourt/ef-cms#8336
* When viewing an M116 document, a judge, chambers, or ADC user can see and click the Apply Stamp link as per ustaxcourt/ef-cms#8336
* Stamp Disposition functionality is identical for these motions - no changes to current behavior.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) A M112 or M113 Motion is filed by a party; Docket clerk QC's motion; sends message with the motion attached to Judge; Judge/CA/ADC user reviews message; Apply Stamp button is available on the document preview from the message thread.

This test case will take some set up
- Log in to DAWSON as a Party on a case (could be petitioner, Private Practitioner, or IRS Practitioner). 
- File a document in a case
- For the document type, select a "Motion to Withdraw as Counsel" or "Motion to Withdraw Counsel" document, and then click continue.
- Upload the document, fill in the required fields, and Submit your filing
- Next, log in as a docket clerk.
- Navigate to the case you just submitted the motion in.
- Click on the document link to QC the Motion.
- Click "Complete QC", and then click "Complete and Send Message"
- Select Chambers/Buch's Chambers/Judge Buch, add in a test message, and click Send.

Now the test is ready
- Log in as Judge Buch
- Click on the new message from Docket re: the motion you submitted (it should be the first message in Recent Messages on your dashboard).

Expected Results
- [ ] **NEW FUNCTIONALITY** - The apply stamp button is available on the document preview from the Message/Attachments page.

-Repeat this test by having docket send a message with the motion attached to an ADC user, and CA user. Next log in as those users to ensure that these users also have access to the "Apply Stamp" button.
- Also, be sure that you test with both of these document types.



#### 2) Judge/CA/ADC User applies stamp on the M112 or M113 motion from a message attachment; Judge/CA/ADC User is presented with the Apply Stamp Page.

- Continuing from the previous test
- Click on the "Apply Stamp" button

Expected Results
- [ ] **NEW FUNCTIONALITY** - The new Apply Stamp page is available to the user

- Repeat this test with ADC and CA user
- Also, be sure that you test with both of these document types.

#### 3) Regression test that the Stamp functionality works as designed via a message flow as written in story ustaxcourt/ef-cms#8336


#### 4) A M112 or M113 Motion is filed by a party; Docket clerk QC's motion; Judge/CA/ADC user reviews docket record, Clicks on Document View of the Motion; Apply Stamp button is available on the document preview screen.

This test case will take some set up
- Log in to DAWSON as a Party on a case (could be petitioner, Private Practitioner, or IRS Practitioner). 
- File a document on a case
- For the document type, select a "Motion to Withdraw as Counsel" or a "Motion to Withdraw Counsel", and then click continue.
- Upload the document, fill in the required fields, and submit the filing
- Next, log in as a docket clerk.
- Navigate to the case you just submitted the motion in.
- Click on the document link to QC the Motion.
- Click "Complete QC"

Now the test is ready
- Log in as Judge Buch
- Navigate to the QC'd Motion from above from the docket record of the case.
- Click on the document link to get to the Document View

Expected Results
- [ ] **NEW FUNCTIONALITY** - The apply stamp button is available on the Document View page

- Repeat this test with ADC and CA user
- Also, be sure that you test with both of these document types.

#### 5) Judge/CA/ADC User clicks apply stamp on a motion from the document view; Judge/CA/ADC User is presented with the Apply Stamp Page.

- Continuing from the previous test
- Click on the "Apply Stamp" button

Expected Results
- [ ] **NEW FUNCTIONALITY** - The new Apply Stamp page is available to the user

- Repeat this test with ADC and CA user
- Also, be sure that you test with both of these document types.


#### 6) Regression test that the Stamp functionality works as designed via clicking on the Apply stamp link from the document Preview ustaxcourt/ef-cms#8336


#### 7) Regression test that the Stamp Order for M112 or M113 documents can be searched for in the Order Search.
