### ISSUE TITLE
Admission Clerk: Practitioner Documentation UI Edit/Delete/Sort

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8245]
As an admissions clerk, so that I can view relevant documentation related to a practitioner, I need to be able to see and interact with files that have been uploaded to that practitioner's record.

With the implementation of ustaxcourt/ef-cms#8244 we will need a UI for viewing and interacting with files that have been uploaded to a practitioner record in DAWSON. A link to this UI should be available on the Practitioner Detail screen in DAWSON.

To begin with, the UI should only be available to admission clerk users. It should display relevant details about each file (listed in the AC below), be sorted in date order ascending, and include the ability to view each file. It should also allow admission clerks to upload a new file, delete files that have been uploaded, or edit the data associated with a file.

## Pre-Conditions
ustaxcourt/ef-cms#8244

## Acceptance Criteria

* Sort order can be changed to sort ascending or descending by any of the data values displayed
* Individual file entries can be deleted from the UI
* Individual file entries can be edited from the UI
  - Editing a file entry allows the user to edit the existing file information, including replacing the file already on record
  - Editing a file will update the Date Uploaded date on the UI to reflect the most recent date of editing
* Admission clerk can upload a new file from the UI in the same manner as ustaxcourt/ef-cms#8244

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX specs
![Practitioner documentation page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d41b06f7-961c-45f3-8ff2-01108952b575)
1. Each column is sortable
2. Default sort is by date ascending
3. Each row has two icon links at the end - "Edit" & "Delete" (left align)
4. Edit link will open the "Add file" page - change page title to "Edit file" (see mockup below)
5. Delete link will display a confirmation modal then removes the row if confirmed

![Edit file page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/5d3d480f-bb5f-42a5-9ef5-e1bdd99362d6)

**Comment by ttlenard** [comment]
## Test Cases 

Preconditions: Be sure that you have some documents uploaded for a Practitioner.

#### 1) Admissions Clerk accesses the Documentation tab for a Practitioner; Edit/Delete links are available, Table headers have Sort icons.

- Log in as an Admissions Clerk
- Click on the Advanced link in the upper right hand corner of the screen
- Click on the Practitioner Tab
- Search for a Practitioner by either typing in a name or adding a BAR number
- If you searched by Practitioner name, click on the BAR number of the Practitioner you would like to view.
- Click on the Documentation tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Edit and Delete links are available on the right side of the table for each document in the table
- [x] **NEW FUNCTIONALITY** - Column headers have the up/down arrows to indicate that they can be sorted



#### 2) Admissions Clerk clicks the Edit link in an existing row in the Documentation table

- Continuing from the previous test
- Click on the Edit link on the document row that you uploaded in the previous test

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Edit File page opens for the user.


#### 3) Admissions Clerk edits some of the data (changes the file) in an existing row in the Documentation table

- Continuing from the previous test
- Update some of the data (click "Change" and upload a new file)
- Save your edits

Expected Results:
- [x] **NEW FUNCTIONALITY** - The updated file name that you edited will display in the table
- [x] **NEW FUNCTIONALITY** - The uploaded date will update to today's date


#### 4) Admissions Clerk edits some of the data (updates the document category/description) in an existing row in the Documentation table

- Continuing from the previous test
- Update some of the data (change the category and update the description)
- Save your edits

Expected Results:
- [x] **NEW FUNCTIONALITY** - The updates to the category and description will display in the table
- [x] **NEW FUNCTIONALITY** - The uploaded date remains as it was originally.




#### 5) Admissions Clerk cancels out of the Edit File page; Modal asks for confirmation; If "Yes, Cancel" is selected, Clerk is returned to the Documentation tab.

- From the Practitioner Documentation tab, click the Edit link for one of the documents in the table
- Click Cancel

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal appears that asks "Are you sure you want to cancel? If you cancel, your form selections will be lost."
- [x] **NEW FUNCTIONALITY** - When clicking Yes, Cancel, Admissions clerk is navigated back to the Documentation tab



#### 6) Admissions Clerk cancels out of the Edit File page; Modal asks for confirmation; If "No, take me back" is selected, Clerk is returned to the Edit File form.

- From the Practitioner Documentation tab, click Edit link for one of the documents in the table
- Click Cancel

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal appears that asks "Are you sure you want to cancel? If you cancel, your form selections will be lost."
- [x] **NEW FUNCTIONALITY** - When clicking "No, Take me back" is selected, Admissions clerk is navigated back to the Edit file form.



#### 7) Admissions Clerk clicks the Delete link in the row for one of the documents in the Documentation Table; Confirms deletion; Document is deleted.

- Continuing from the previous test
- Click on the Delete link in the row for one of the documents in the table.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Pop up modal appears that states,  "Are you sure you want to delete this document? This action cannot be undone."
- [x] **NEW FUNCTIONALITY** - After clicking "Yes, Delete", user is navigated back to the Documentation tab.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner that states, "This Document has been deleted".


#### 8) Admissions Clerk clicks the Delete link in the row for one of the documents in the Documentation Table; Does not want to delete; Clerk is returned to the Edit screen.

- Continuing from the previous test
- Click on the Delete link in the row for one of the documents in the table.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Pop up modal appears that states,  "Are you sure you want to delete this document? This action cannot be undone.."
- [x] **NEW FUNCTIONALITY** - After clicking "No, Cancel", user is navigated back to the Documentation tab.


#### 9) Admissions Clerk sorts the Columns in the table; Documents sort appropriately.

- Continuing from the previous test
- Click on the column headers to sort ascending or descending.

Expected Results:
- [x] **NEW FUNCTIONALITY** - When a column is sorted, Column name is underlined and the arrow will match whether it is sorted ascending (arrow up), or descending (arrow down).
- [x] **NEW FUNCTIONALITY** - Spot check to ensure that the sorting is working appropriately (sorted by date or name (alphabetical)).

**Comment by swongCO** [comment]
### UX Feedback
See new mockup in UX Specs for design:
- [ ] Change title to "Edit File"
- [ ] In the uploaded file section, match what's on the Add File page
- [ ] Change button text to "Update File"
![Screen Shot 2022-10-27 at 9.54.58 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/27a626e3-3626-48ac-bd08-b3dbd4ac57c1)
——————————————
- [ ] Left align Edit and Delete icon links
- [ ] Reduce the width of the Description column by ~20% and add it to the File Name column so the width increases
![Screen Shot 2022-10-27 at 12.54.35 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3ec3fae2-3d6f-40cf-bad8-d1f8f7d5de2c)

**Comment by ttlenard** [comment]
@TomElliottFlexion Testing Feedback 11/2/2022

I found a couple of things:

Test case 4 - When I click edit and then update the data (not the file), the uploaded date is getting changed to today's date.

Test case 7 - When I delete a document, rather than being brought back to the documentation tab, I am navigated to the Details tab.

**Comment by ttlenard** [comment]
@TomElliottFlexion Testing Feedback 11/3/22

Everything looks great now. Test case 4 and 7 now pass. Thanks for fixing!
