### ISSUE TITLE
Docket User: View of Clerk Assignments

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8263]
As a docket clerk, so that I can manage my team effectively, I need to be able to see a list of a clerk's assigned QC work or all unassigned work.

Docket supervisors need to keep an eye on individual clerk workloads and specific case assignments. Right now, they must rely on the Section Document QC views to view assignments, and there is no ability to see just a specific clerk's assignments.

This story will provide a means for docket supervisors and docket clerks to view a specific docket clerk's assigned work, specifically the Inbox, In Progress, and Processed views currently displayed on the Section Document QC.   

## Acceptance Criteria
* Docket clerks can navigate to a view that displays all work assigned to a specific clerk without seeing any work NOT assigned to the clerk
  - Can see the work in Inbox, In Progress, or Processed
* Docket clerks can navigate to a view that displays all unassigned work without seeing any assigned work
* Docket clerks can change the assignment of a QC item to another docket clerk from this view
* Docket clerks can unassign assigned work from this view
* Views retain same ordering criteria as Section Document QC view currently in production

## Notes
~~* Does the creation of docket supervisor role belong in this or a separate story?~~
 - We'll handle supervisor roles at a later time.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
### UX Specs
![Section QC.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/8cf591e1-1b2f-49af-bf81-ac47c49be2a5)

1. Add "Filter by" [make sure coded as a label not a header] with a dropdown menu using "-Assignment-" as the default
2. The "Assign to" dropdown should always be present in disabled mode when no boxes are checked (box no longer needs to be checked for it to pop up)
3. "Assign to" should remain at the right of the "Filter by" selection
4. Add Counter to the right-hand side above the table (use trial session info active/inactive/all cases as a template for spacing above the table)
5. Counter should have the label bolded and the data in regular font. 

![Section QC 2.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/cb4716bf-8385-4d66-9d35-24305778e11e)

1. When "-Assignment-" is clicked, the list of docket clerks should appear in alphabetical order with "Unassigned" listed at the very top.

![Section QC 3.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/f47ba6cd-b1b9-4477-9115-8e8ac32174c4)
1. When an "-Assignment-" filter is selected (e.g. Unassigned), the table will update to only show selected filter in the results and the count will update to reflect this (e.g. Count:25 for filter of 'Unassigned')
2. "Assigned to" box will remain in the inactive state

![Section QC 4.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/3f648a76-6dc5-469e-9ff7-b25feeb9dc81)

1. Once a docket number is checked, this will activate the "Assign to..." dropdown as well as display the blue pill counter
2. Blue pill will move to the right of the "Assign to..." box and reflect how many docket numbers are selected. When there are no selections, the blue pill disappears.
3. "Assign to..." retains its current function.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk Navigates the Section Document QC Inbox tab, Filter dropdown menu is available.

- Log in as a Docket clerk
- Click on the Document QC tab
- Click on the Section Document QC tab.
- Be sure that you are on the Inbox Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new Filter by dropdown is available on the page.
- [x] **NEW FUNCTIONALITY** - The default menu item that shows in the dropdown is "Assignment"
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is now present to the right of the Assignment dropdown, but is greyed out (won't be activated until a box is checked.)
- [x] **NEW FUNCTIONALITY** - A Counter is now present above the table on the right side


#### 2) Docket Clerk Navigates the Section Document QC In Progress tab, Filter dropdown menu is available.

- Continuing from the previous test
- Click on the In Progress Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new Filter by dropdown is available on the page.
- [x] **NEW FUNCTIONALITY** - The default menu item that shows in the dropdown is "Assignment"
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is now present to the right of the Assignment dropdown, but is greyed out (won't be activated until a box is checked.)
- [x] **NEW FUNCTIONALITY** - A Counter is now present above the table on the right side


#### 3) Docket Clerk Navigates the Section Document QC Processed tab, Filter dropdown menu is available.

- Continuing from the previous test
- Click on the Processed Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new Filter by dropdown is available on the page.
- [x] **NEW FUNCTIONALITY** - The default menu item that shows in the dropdown is "Assignment"
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is NOT present on this page
- [x] **NEW FUNCTIONALITY** - A Counter is now present above the table on the right side



#### 4) Docket Clerk selects a docket clerk user from the Assignment filter dropdown; List is filtered by that clerk and only shows their assignments; Count is updated to reflect Count of selected Clerk.

- Continuing from the previous test
- Navigate to the Section Document QC Inbox Tab
- Click in the Assignment filter dropdown, and select a docket clerk user

Expected Results
- [x] **NEW FUNCTIONALITY** - The List of Docket Clerks in the Assignment dropdown is alphabetized, with the exception of Unassigned, which should be the first item in the list.
- [x] **NEW FUNCTIONALITY** - The list is filtered to only show work for the selected docket clerk
- [x] **NEW FUNCTIONALITY** - The Count is updated to show the count of assignments for the selected docket clerk.
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is now present to the right of the Assignment dropdown, but is greyed out

*Repeat this test from the In Progress Tab.



#### 5) Docket clerk selects Unassigned from the Assignment filter dropdown; List is filtered to show only unassigned work; Count is updated to reflect Count of Unassigned work.

- Continuing from the previous test, on the Inbox Tab
- Click in the Assignment filter dropdown, and select Unassigned

Expected Results
- [x] **NEW FUNCTIONALITY** - The list is filtered to only show unassigned work
- [x] **NEW FUNCTIONALITY** - The Count is updated to show the count of items that are unassigned.
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is now present to the right of the Assignment dropdown, but is greyed out



#### 6) Docket clerk checks some of the boxes next to the Docket number; Assign to box is activated.

- Continuing from the previous test
- Check some of the boxes next to the docket number

Expected Results:

- [x] **NEW FUNCTIONALITY** - The blue pill container displays the total number of checkboxes checked
- [x] **NEW FUNCTIONALITY** - The Assign to box becomes activated 

*Repeat this test from the In Progress Tab.



#### 7) Docket Clerk assigns work items to another Docket Clerk

- Continuing from the previous test, on the inbox tab
- In the Assign To box, select a docket clerk's name to assign the unassigned work.

Expected Results:

- [x] **NEW FUNCTIONALITY** - The work item(s) that you selected disappears from the filtered list for Unassigned work.
- [x] **NEW FUNCTIONALITY** - The Counter is updated to reflect the subtractions from the total of items in the unassigned list (assuming no more work items have been added to the unassigned work while you were assigning the work)

*Repeat this test by re-assigning work from one docket clerk to another.
*Repeat this test from the In Progress Tab



#### 8) Docket clerk un-assigns work that was previously assigned to another Docket Clerk.

- From the Document QC, inbox tab
- Filter the list by a docket clerk in the list to view their items
- Check some boxes next to the docket number
- In the Assign to box, select a different docket clerk's name

Expected Results:
- [x] **NEW FUNCTIONALITY** - The work item(s) that you selected disappears from the filtered list for the docket clerk.
- [x] **NEW FUNCTIONALITY** - The Counter is updated to reflect the subtractions from the total of items in the docket clerk's list (assuming no more work items have been added to the docket clerks work while you were assigning the work)
- [x] **NEW FUNCTIONALITY** - When the filtered list is updated to show the docket clerk that you assigned the work to, the list includes the items that you just reassigned.

*Repeat this test from the in progress tab.


#### 9) Regression test to ensure that the Ordering that is currently in production remains the same.

**Comment by TomElliottFlexion** [comment]
Previous bug involving workItems assigned to the wrong docket clerk appearing when they should be excluded by the filter was due to a data issue in a different story. Moving ticket back to UX

**Comment by TomElliottFlexion** [comment]
Current sorting precedence for table: 

Inbox and In Progress tabs:
|highPriority |trialDate  | receivedAt | docketNumber |
|--- | --- | --- | ---|
|desc. |asc.|asc.|asc.

Processed tab:
|highPriority |trialDate  | completedAt | docketNumber |
|--- | --- | --- | ---|
|desc. |asc.|desc.|asc.

**Comment by ttlenard** [comment]
While testing this story, we found a bug.  This story is blocked until we can resolve bug ustaxcourt/ef-cms#8302.

**Comment by ttlenard** [comment]
Testing Feedback 11/7/2022 - At this point, I can still see duplicate work items on the processed tab (issue that was reported in ustaxcourt/ef-cms#8302), but this is to be expected. The fix for ustaxcourt/ef-cms#8302 eliminates the ability to create duplicates, but doesn't remove them from the processed tab.  In theory, all duplicate will be removed from view in 10 days (this is how long items stay in the processed box), and so in 10 days we shouldn't see any duplicates anymore.  All other testing for this story looks good.

Note that while testing ustaxcourt/ef-cms#8302, I did find two scenarios that COULD still create duplicate work items (reported in a separate bug ustaxcourt/ef-cms#8355).

**Comment by ttlenard** [comment]
11/14/22 - Sui found a bug related to this story.  I have added a separate bug. It's ustaxcourt/ef-cms#8361.

If you apply a filter to the Section Document QC tab and navigate over to the My Document QC tab, the filter persists, and it would appear that you do not have any items in your Document QC.  Once you turn off the Filter on the Section Document QC tab, all of the QC items re-appear for you in the My Document QC.
