### ISSUE TITLE
Session Copy: Consolidated Case/Trial Status Filtering Enhancement

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8265]
As a Session Copy viewer, so that a filtered view of the Session Copy displays cases accurately, I need member cases in consolidated groups to display appropriately even if the Lead Case has been filtered from the display.

With the implementation of ustaxcourt/ef-cms#8214, we introduced grouping and iconography for cases in consolidated groups to the Session Copy page. However, if the Lead Case has a Trial Status assigned that is not selected in the list of filters, none of the member cases in the group are displayed, even though the member cases have a Trial Status assigned that IS selected in the list of filters.

This story will address behavior when the Lead Case trial status has been filtered out of the Session Copy display.

## Acceptance Criteria
* When a consolidated case group is part of a Session Copy, if the Lead Case trial status is not selected as a filter, display all member cases if their trial status IS selected as a filter
* If member cases are displayed but the Lead Case is not, then do not group or indent the member cases in the display
* If member cases are displayed but the Lead Case is not, then sort the member cases according to the default sort order
* If the Lead Case is added to the group by selecting its trial status as a filter, group/sort/indent the Session Copy as per the default behavior implemented in ustaxcourt/ef-cms#8214

## Notes
* Confirm functionality w/r/t printable copy still works as expected

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Trial Status for the lead case in a consolidated group is updated on the Session Copy page; member cases have a different trial status than the lead case; The trial status for lead case is de-selected; Lead case no longer appears in the case list, member cases remain in list.

Preconditions: 
1. A consolidated group of cases that have been calendared for trial
2. Other cases that are not part of the consolidated group are also calendared in the trial session
3. The trial session is assigned to a Judge/Chambers user that you have log in access to.
4. The trial session has an assigned trial clerk user that you have log in access for.

- Log in as a Judge, Chambers, or a trial clerk user that is assigned to the trial session from the preconditions above.
- Click on the City, State link for the trial session
- Scroll down to the Case list
- Find the consolidated group of cases in the list
- Update the trial status for the Lead case in the group
- In the "Show Cases by Trial Status" area, de-select the status that you just assigned to the Lead Case.

Expected Results:
- [x] The Lead case should no longer appear in the list of cases
- [x] The member cases remain in list, and will retain the consolidated case icon
- [x] The member cases are no longer indented in the list
- [x] The member cases are no longer grouped together, and revert to the default sort order (by ascending docket number)

*Repeat this test with the other users that have access to the Session Copy Page


#### 2) Trial status for the Lead Case is selected; Consolidated group sorting, grouping, and indenting is retained in the list.

- Continuing from the previous test case
- Select the check box to view cases with the trial status that you assigned to the lead case in the previous test.

Expected Results:
- [x] The Lead case appears in the list of cases
- [x] The member cases are indented below the lead case
- [x] The member cases are grouped with the lead case

*Repeat this test with the other users that have access to the Session Copy Page


#### 3) Trial status for a member case is updated to a different status than the Lead Case and other member cases on the Session Copy page; The trial status for the member case is de-selected; member case no longer appears in the case list.

- Continuing from the previous test
- Update the trial status for a member case in the group to a different status than what you added for the Lead Case
- In the "Show Cases by Trial Status" area, de-select the status that you just assigned to the member case

Expected Results:
- [x] The Lead Case and the other member cases in the group remain visible in the list of cases
- [x] The Member case that you updated the status for and de-selected, is not visible in the list of cases
- [x] The Lead case in the group has the other member cases still indented below it.

*Repeat this test with the other users that have access to the Session Copy Page


#### 4) Trial status for the member case is selected; Consolidated group sorting, grouping, and indenting is retained in the list

- Continuing from the previous test
- Select the check box to view cases with the trial status that you assigned to the member case in the previous test.

Expected Results:
- [x] The member case appears in the list of cases
- [x] The member case is appropriately sorted/grouped/indented with the Consolidated group

*Repeat this test with the other users that have access to the Session Copy Page


##### 5) Trial status for all cases in the group are updated to different statuses; Selecting and de-selecting Trial status filter upates the list appropraitely.

- Continuing from the previous test
- Update the trial status for all the member cases, making sure that you are adding various trial statuses (or repeating a few is ok too) to the cases in the group, along with updating the trial status for other non-consolidated cases in the list.
- Select/de-select the trial statuses in the "Show Cases by Trial Status" area 

Expected Results:
- [x] List of cases display the consolidated cases appropriately as per the test cases above when selecting/deselecting various trial statuses for the cases in the consolidated group, and the cases that are not part of the consolidated group.

**Comment by rosiehsmith** [comment]
Addressed in [9648](https://github.com/flexion/ef-cms/issues/9648), [PR](https://github.com/ustaxcourt/ef-cms/pull/2703)

**Comment by ttlenard** [comment]
I tested all of the test cases and they all pass.  Going to close this Story since there isn't anything to deploy with this story.
