### ISSUE TITLE
Docket Clerk: Select All when assigning work

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8270]
As a docket clerk, so that I can quickly reassign work, I need the ability to select all displayed boxes on the QC Display.

When assigning work to a clerk, docket often needs to assign multiple items at a time (typically when a clerk is out of the office or is tasked with alternate duties). As the list of outstanding items to assign can often be quite long, it would be helpful once ustaxcourt/ef-cms#8263 is completed to be able to select all displayed work with a single click as opposed to having to individually select each work item.

This story will address the implementation of a 'Select All' functionality on the Section QC Inbox and In Progress displays. 

## Pre-Conditions
ustaxcourt/ef-cms#8263

## Acceptance Criteria
* On the Section Document QC - Inbox display, a user can select all displayed items with a single operation
* On the Section Document QC - In Progress display, a user can select all displayed items with a single operation
* When all items are selected, the assignment menu appears as normal (see screenshot below)
* When all items are selected, the number of selected items appears as normal (see screenshot below)
* When an option is chosen from the assignment menu, all selected work items are assigned as normal
* On both the Inbox and In Progress views, a user can select all displayed items whether or not a filter (see ustaxcourt/ef-cms#8263) is currently in use
* If a filter (see ustaxcourt/ef-cms#8263) is in use, the "Select All" operation only selects those items displayed
* The user can also de-select all displayed work items with a single operation

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/49e61de4-6f3d-49be-b77d-4f34c6d7f0a4)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
### UX Specs
![checkbox 1.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/09c7a5e1-88e6-4ec6-88d4-527c1d345aed)
1. Add checkbox in table header to the left of "Docket No." This box defaults to unchecked.

![Checkbox 2.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/9456b89c-be4d-4ad3-9a5f-ee675cc6ea53)

1. When the new checkbox is clicked, this will automatically select all listed inbox items and activate the "Assign to..." dropdown
2. This will also trigger the blue pill counter to appear to the right of the "Assign to..." dropdown with the appropriate number according to how many items are selected from the list
3. If the header checkbox is clicked again, it will deselect all items in the inbox

![Checkbox 3.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/7ff98485-d693-499d-8373-e4e8799e639b)
1. If a user deselects one of the items, it will also uncheck the checkbox in table header and update the counter in the blue pill

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk Navigates the Section Document QC Inbox tab; New checkbox is available to the left of the Docket No. Column Header.

- Log in as a Docket clerk
- Click on the Document QC tab
- Click on the Section Document QC tab.
- Be sure that you are on the Inbox Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new checkbox is present to the left of the Docket No. Column Header
- [x] **NEW FUNCTIONALITY** - The checkbox is defaulted to be unchecked.



#### 2)  Docket Clerk Navigates the Section Document QC In Progress tab; New checkbox is available to the left of the Docket No. Column Header.

- Continuing from the previous test
- Click on the In Progress Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new checkbox is present to the left of the Docket No. Column Header
- [x] **NEW FUNCTIONALITY** - The checkbox is defaulted to be unchecked.



#### 3) Docket Clerk Navigates the Section Document QC Completed tab; New checkbox is NOT present to the left of the Docket No. Column Header.

- Continuing from the previous test
- Click on the Processed Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The new checkbox is NOT present to the left of the Docket No. Column Header



#### 4) Docket Clerk filters the view for a docket clerk from the filter by Assignment dropdown; Adds a checkmark in the checkbox in the Table Header to Select all; All of the checkboxes for the user are selected at once.

- Continuing from the previous test
- In the Assignment filter, select a docket clerk from the list
- Click on the checkbox in the table header

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the checkboxes are checked all at once for the list of work items for the selected docket clerk.
- [x] **NEW FUNCTIONALITY** - The blue pill icon is updated to indicate the total number of items selected.
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is activated

*Repeat this test on the In progress Tab.



#### 5) Docket Clerk de-selects the checkbox in the table header; All checkbox selections are removed at once.
 
- Continuing from the previous test
- Select the checkbox in the table header to de-select it.

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the checkboxes are de-selected all at once for the list of work items for the selected docket clerk.
- [x] **NEW FUNCTIONALITY** - The blue pill icon disappears once there are no more selections.
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is no longer activated


*Repeat this test on the In Progress Tab.


#### 6) Docket Clerk de-selects a few checkboxes after all of the Checkboxes were selected; Checkbox in the header is de-selected.

- Continuing from the previous test
- Click on the checkbox in the table header to select all the checkboxes in the list
- De-select a few of the checkboxes from the list

Expected Results
- [x] **NEW FUNCTIONALITY** - the checkbox in the table header de-selects.
- [x] The checkbox for each of the individual work items de-selects
- [x] **NEW FUNCTIONALITY** - The blue pill icon is updated to indicate the total number of items selected.
- [x] **NEW FUNCTIONALITY** - The Assign to dropdown is activated


*Repeat this test on the In Progress Tab



#### 7) Docket Clerk re-assigns the selected work items to a different docket clerk; Count is updated to reflect the total number of work items that you de-selected.

- Continuing from the previous test
- In the Assign To box, select a different docket clerk to assign the work items to.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The selected items from the list are re-assigned to a different docket clerk all at once
- [x] **NEW FUNCTIONALITY** - The total count in the right corner is updated to reflect the number of work items that you did not select in the previous test.

*Repeat this test on the In Progress Tab.


8) Docket Clerk updates filter and selects the docket clerk that was just re-assigned work; Filtered list shows all of the appropriate assignments.

- Continuing from the previous test
- In the Assignment filter, select the docket clerk that you assigned work to from the previous test case

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the re-assigned work items from the previous test appear in the list


*Repeat this test on the In Progress Tab.

**Comment by swongCO** [comment]
UX Review feedback:
When the check all box is selected, all lines in the table are selected. When one of the rows is deselected, the check all box is also deselected. When the row is reselected, the check all box remains deselected. The  check all box should be selected whenever all rows are selected.
