### ISSUE TITLE
BUG: Petitions Clerks and Docket Clerks receive validation error if they use the Calculate links when entering Statistics on a Petition

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8277]
**Describe the Bug**
If a petitions clerk uses the Calculate Penalties on IRS Notice link when entering statistics on a Petition, they will receive a validation error that says "enter year, deficiency amount, and total penalties" (see screen grabs below). If the petitions clerk just enters in a Total Penalties amount, then no validation error appears.  The court has guidance for petitions clerks to use the built in calculator in DAWSON to calculate total penalties.

In addition, if a docket clerk uses the Calculate Penalties as determined by Court link, the same behavior occurs. (see screen grabs in comments below)

Also, when entering in the Deficiency amount, we notice that the commas no longer appear, and there is no dollar sign.

**Business Impact/Reason for Severity**
High

**In which environment did you see this bug?**
Prod, Test (This is NOT happening over on DEV)

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Log in as a Petitions Clerk
2. Click on Document QC
3. Click on Start a Petition
4. Enter in the information for a Petition
5. When you get to the IRS notice screen, indicate that you received a notice from the IRS
6. Add in a year, and the deficiency amount (notice here that the dollar sign and commas do not appear. Also, if you edit the amount here by deleting a number, notice that the curser jumps around here.)
7. Click the Calculate Penalties on IRS Notice link.
8. Enter in a couple of Penalties, click calculate
9. Click Review Petition, receive validation error.

Some other notes: If you just put in a total penalty (without using the calculator tool) no validation error.  Also, if you do this same thing on DEV, it works just fine.

**Expected Behavior**
Petitions clerk should be able to Calculate Penalties

**Actual Behavior**
A clear and concise description of what actually happened.
Petitions clerk is not able to calculate penalties

**Screenshots**

Indicate that the IRS notice was provided, you will see this screen. Add in a year, deficiency amount and then Click on the link:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1c25645e-1c7a-4e96-9055-17bbe1b29d6f)

If you add more than one penalty and click calculate on this screen...
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/733e66b0-44ee-4e33-9b6f-1e873661ffdc)

Then you will get this validation error (notice how the Deficiency box is doesn't have the dollar sign, and neither box has commas:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/a0da9329-e9fb-48a8-9c93-fe90b3724c62)

**PRs**
https://github.com/ustaxcourt/ef-cms/pull/2626
https://github.com/ustaxcourt/ef-cms/pull/2623
https://github.com/ustaxcourt/ef-cms/pull/2619

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by mrinsin** [comment]
Info from some initial research: I looked into this and it seems like when the modal is used to calculate the total, a '$' is added to the property `irsTotalPenalties` therefore making it an invalid value for a property thats supposed be a number. Removing the '$' and making that property a number from a string proved my theory and seemed to (hackily) fix the bug for me locally

**Comment by jhansen-flexion** [comment]
Original story is 4657https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/4657#:~:text=%23-,4657,-As%20a%20Petitions

**Comment by codyseibert** [comment]
Some updates, it seems like last week there was an update to react-number-format to upgrade it to version 5, the bug might be caused by this upgrade.  We probably just need some more test coverage around this user sequence

**Comment by ttlenard** [comment]
More updates: I also found this calculator in DAWSON when you add a year/period, and I also received the error:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/4ad57b23-dd5a-447a-b2fa-6dabe2fd73bf)

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/880904cd-80e1-4189-973a-e966a6080ba4)

**Comment by jhansen-flexion** [comment]
Not sure why I cannot assign a bug but @rachelschneiderman volunteered to take this on and will be working on it shortly.

**Comment by jhansen-flexion** [comment]
Not sure why I cannot assign a bug but @rachelschneiderman volunteered to take this on and will be working on it shortly.

**Comment by ttlenard** [comment]
I met with @rosiehsmith and @mrinsin to talk about the missing commas. Yesterday when I was meeting with the petitions clerk, they specifically called out that the commas were missing for large dollar amounts.  Rosie and Mrin have updated the code so that we can get the commas added back in. Thanks Ladies!

Here is a screen grab of what it currently looks like without commas
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/bd5bc8bb-d33e-4366-a4b4-973c86f9c855)
