### ISSUE TITLE
Enforce request limits per IP address.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#828]
We introduce per-IP request limits in #711, but deployed them in count-only mode (meaning they are not blocking IP addresses which exceed the limit). Once we are confident that enforcing these limits will not cause a service outage, we should do so. 

- [ ] Check CloudWatch metrics displayed in WAF to ensure a reasonable and correct number of requests are blocked. 
- [ ] Ensure the application has been updated to gracefully handle blocked requests in https://github.com/ustaxcourt/ef-cms/issues/829.
- [ ] Replace `count {}` directive with `block {}` in the [`per_ip_request_limit ` rule](https://github.com/ustaxcourt/ef-cms/blob/fe6a80ba561cc9f23b748c96b789578106da7fd1/web-api/terraform/api/waf.tf#L14) and [`per_ip_expensive_request_limit ` rule](https://github.com/ustaxcourt/ef-cms/blob/fe6a80ba561cc9f23b748c96b789578106da7fd1/web-api/terraform/api/waf.tf#L36). 
- [ ] Remove `web-api/terraform/bin/import-api-public-stages.sh` (it was a temporary script).

| No requests will be blocked | Requests will be blocked |
|----------------------------|--------------------------|
| ![Screenshot of a blank graph, which is what happens when no requests are counted](https://images.zenhubusercontent.com/5ec54bc142883a8314e50df8/265a46ce-1e6e-426b-96cc-01bd6b6fdd56) | ![Screenshot of a graph with data, which is what happens when requests are counted](https://images.zenhubusercontent.com/5ec54bc142883a8314e50df8/f55fbfae-bced-4084-bb05-f89721acb011)

**Comment by mmarcotte** [comment]
Solved with rate limiting via the application.
