### ISSUE TITLE
Gracefully handle too many requests from a single computer.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#829]
ustaxcourt/ef-cms-flexion#711 introduced AWS Web Application Firewall rules which limit the number of requests allowed for a computer (IP address). When they are enforced in ustaxcourt/ef-cms#6758, API requests may be blocked due to this limit being exceeded, and we need to present the user with something helpful. 

- WAF responds with HTTP 403 when requests are blocked and a JSON response body.

**Comment by mmarcotte** [comment]
Pick this up when Flexion picks up the Search stories.
Possible 403 Forbidden message when we hit this limit; would it forward them to the login page?
Add in the rules from ustaxcourt/ef-cms#6758 for Order & Opinion Search 

@adunkman halp!

**Comment by JessicaMarine** [comment]
@mmarcotte I had previously added https://github.com/flexion/ef-cms/issues/7756 to Flexion's backlog to pick up when we do Order & Opinion search work.  Does that close this ticket or is there something else that needs to be done?  If there is more work to be done, is that Court-sided (18F) or another ticket for Flexion?

**Comment by mmarcotte** [comment]
Closing [for now], but this is referenced in https://github.com/flexion/ef-cms/issues/7756 and it could be revisited if the need arises to more gracefully handle too many requests from a single computer.
