### ISSUE TITLE
SPTO/SPOS: Remove Signature Requirement for Serving

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8296]
As a docket clerk, so that I can manually add standing pretrial orders and standing pretrial orders for small cases to the docket record of a manually calendared case, I need to be able to docket SPTO/SPOS event codes without requiring a signature.

Currently, when a case is added to a calendar outside of the "Set Calendar" process, a docket clerk must add the SPTO/SPOS order to the docket record manually. Right now these are being added as MISC event codes because using the SPTO/SPOS event codes would require an unnecessary and inaccurate signature from the Chief Judge to add to the docket record.

SPTO/SPOS documents when added to the docket record already have a Signed field with the presiding judge's signature line on them - so we do not need to require a signature when docketing these particular types of orders.  

## Acceptance Criteria
* When adding a Standing Pretrial Order to the docket for a case, docket clerk can serve the entry without requiring the CJ signature
* When adding a Standing Pretrial Order for Small Cases to the docket for a case, docket clerk can serve the entry without requiring the CJ signature

## Notes
* Court would prefer to continue adding these manually on a case-by-case basis instead of being able to generate these on-demand for a give session, due to case context and timing issues related to the population of the information on the trial session/case.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk uploads a Standing Pretrial Order to a Regular case; clerk selects SPTO as the document type when adding the docket entry; signature requirement is no longer present for the Order.

- Log in as a Docket Clerk
- Navigate to a case
- Click on Create, and select PDF Upload
- Upload a file, add a description, and click Save
- Click Add Docket Entry
- For Document Type, select Standing Pretrial Order
- Click Save and Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - Document no longer has the warning message that you must include a signature
- [x] The "Are you ready to Initiate Service?" pop up modal appears (Includes information about paper service if Petitioner has paper service)
- [x] After clicking "Yes, Serve" on the pop-up modal, the Print for Paper service appears (if Petitioner has paper service).
- [x] The Standing Pretrial Order is added to the docket record.
- [x] The Event Code on the docket record is SPTO




#### 2) Docket Clerk uploads a Standing Pretrial Order for Small cases; clerk selects SPOS as the document type when adding the docket entry; signature requirement is no longer present for the Order.

- Log in as a Docket Clerk
- Navigate to a case
- Click on Create, and select PDF Upload
- Upload a file, add a description, and click Save
- Click Add Docket Entry
- For Document Type, select Standing Pretrial Order for Small Cases
- Click Save and Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - Document no longer has the warning message that you must include a signature
- [x] The "Are you ready to Initiate Service?" pop up modal appears (Includes information about paper service if Petitioner has paper service)
- [x] After clicking "Yes, Serve" on the pop-up modal, the Print for Paper service appears (if Petitioner has paper service).
- [x] The Standing Pretrial Order is added to the docket record.
- [x] The Event Code on the docket record is SPSO


#### 3) Regression test to ensure that other Orders still require Judges signature.

- Log in as a Docket Clerk
- Navigate to a case
- Click on Create, and select PDF Upload
- Upload a file, add a description, and click Save
- Click Add Docket Entry
- For Document Type, select any other Order besides SPTO or SPOS
- Click Save and Serve

Expected Results:
- [x] Warning message still displays and states that you must include a signature
