### ISSUE TITLE
UX: Enhance process for incorporating product support feedback

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8305]
As a user researcher, so that I can identify user pain points, I need access to user support data.

## Acceptance Criteria
* UX has access to user support data

## Notes
* This user story was created as an outcome from the relaunch. For now, Tenille, Sui and Lia will collaborate to share information. This story is for considering the tagging and automation of production support data or any other way to make the raw data more accessible to UX. See comments for notes from relaunch session. 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Action Items from Relaunch:
1 - Tenille will join the UX meetings with Chris, Lia, and Sui to discuss any Prod support topics that come up, prior to their scheduled 1 on 1 sessions.
2 - Lia, Sui, Tenille, Mike will have a follow up session to look into ZenDesk labels.

**Comment by liadmccabe** [comment]
Status Update as of 1/28/2022 - Tenille, Sui, Mike, and I met for an hour to discuss ZenDesk labels options and ideas. We brainstormed some possible avenues to take and ended with a few action items to include: 1) Tenille looking into whether it's possible to export the excel files to include the body of the tickets and if that's a feasible option 2) For Sui, Tenille and I to bring up the topic of labels in our next USTC: Research & Design meeting to gain clarity on a) if they would be open to using labels since they would have to add them at the Tier 1 level and b) What labels would make most sense to use.  These are just a few ideas that came from that meeting. More to follow.

**Comment by swongCO** [comment]
Another idea from the meeting on 1/28 - utilize ZenDesk's API and create a ZenDesk Lite app that Lia and myself can access, thereby freeing up Tenille from the manual work and allowing UX visibility into a broader range of help tickets.

**Comment by ttlenard** [comment]
@liadmccabe I think I got confused as to which Thursday meeting you were talking about!  We also have a Thursday meeting with Admissions staff only, so I was thinking we would bring it up on that call, not the Thursday UX call. Sorry for that confusion!

Also, a few other action items from the call from this afternoon were:
- I was going to see what kind of training support we have with our current Zendesk Subscription - Could they help us showing us the tools we have with our current subscription?
- I am continuing to get status updates from OIS about if/when we get an updated subscription to ZenDesk that has more functionality.
