### ISSUE TITLE
[SPIKE] Adjust usage of docker to improve CI build times.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#831]
Explore splitting our large docker container into smaller docker images that are run through `docker-compose` and ensure our builds are cached between jobs in a workflow. 

- @adunkman hypothesizes that this will speed up our builds substantially.
- We may be able to remove the usage of a custom CI runner, which would remove all infrastructure and code relating to ECR.
- We can likely reuse this `docker-compose` setup for locally running the application and it’s dependencies. 

AC

- [x] Create baseline metrics
- [x] Come up with any ideas for future stories
- [x] No code changes

**Comment by mmarcotte** [comment]
Flexion has been doing work here, so we should reevaluate based on updated performance.

**Comment by adunkman** [comment]
CircleCI tracks metrics on build and job times — here’s [metrics on job performance over the last 30 days](https://app.circleci.com/insights/github/ustaxcourt/ef-cms/workflows/build-and-deploy/jobs?reporting-window=last-30-days) on the `staging` branch.

![Screenshot of overall build time metrics](https://user-images.githubusercontent.com/14930/114202533-46775f00-9925-11eb-9d31-d0bae6331fd4.png)

To focus on reducing overall build time, we should focus on optimizing: 

- deploy (31:31)
- build-client-unit (15:05)
- build-shared (13:56)
- build-client-integration (11:23)

To focus on reducing overall credit usage, we should focus on optimizing:

- build-client-integration (24,066)
- deploy (8,080)
- e2e-cypress (6,559)
- e2e-pa11y (6,211)

For the purposes of this investigation, I focused on time reduction.

## Findings, recommendations, and expected outcomes on immediately actionable items

### Bug: Source code cache keys never match. 

The current implementation of source code caching approximately doubles the time it takes to checkout code, adding ~0:25 to every job in the first stage of our build, including the following jobs: 

- build-api
- build-client-integration
- build-client-unit
- build-shared
- e2e-cypress
- e2e-cypress-public
- e2e-pa11y
- e2e-pa11y-public

The cache is never used due to a bug in the key names. 

- The cache is stored as `deps-<version>-<branch>-<commit>`
- The cache is attempted to be restored from:
    - `source-<version>-<branch>-<commit>`
    - `source-<version>-<branch>-`
    - `source-<version>-`

Additionally, these jobs do not attempt to use or restore from the source code cache, though they would have a 100% cache hit rate due to their job dependencies: 

- build-client-coverage
- deploy
- migrate
- smoketests
- switch-colors

🌴 **Recommendation:** Rename the cache keys to match, either with `source-` as a prefix or `deps-` as a prefix.

⚠️ **Recommendation:** Ensure the source cache saves time. Since storing the cache takes the same amount of time as checking out code, if restoring the cache also takes the same amount of time as checking out code the caching complexity is worthless. Our limiting factor may be within-datacenter transfer rates.

🌴 **Recommendation:** If the source code cache persists, use reusable configuration to specify source checkout procedures once in configuration, and reference it in all jobs. This ensures every job receives the caching benefits, and bugs are easier to detect and fix. [CircleCI commands](https://circleci.com/docs/2.0/reusing-config/#the-commands-key) or [yaml anchors and references](https://blog.daemonl.com/2016/02/yaml.html) can be used.

📈 **Expected outcome:** A reduction in runtime of ~0:30 for all first stage parallel builds, and if restoring the cache is faster than checking out the code, that time savings would be multiplied by 6 for deployed environments (there are 6 stages to deploy, and each job checks out source code).

### Risk: `istanbul` and `istanbul-combine` are not version locked.

These packages are used to combine code coverage files and assert their coverage meets 95% coverage, and are called using `npx` without the `--no-install` flag — so their latest versions are implicitly installed when they are run. 

🌴 **Recommendation:** Add `istanbul` and `istanbul-combine` to `package.json`, and run `npm ci` in the `build-client-coverage` job.

🌴 **Recommendation:** Any time `npx` is used, add the `--no-install` flag to prevent it implicitly installing packages. This will cause the build to fail any time a dependency is missed. 

📈 **Expected outcome:** Major version changes to either of these packages can break builds and prevent production deployments. This risk will be avoided by version locking them. 

### Cache node.js dependencies.

Our ultimate cache goal would be to prevent downloading or compiling dependencies unless those dependencies have changed. Because we know the operating system and version of all dependencies (`package-lock.json`), we should be able to cache extremely effectively. 

The following jobs perform `npm ci && npm rebuild`, and each execution takes ~1:10 with no caching in place: 

- build-api
- build-client-integration
- build-client-unit
- build-shared
- e2e-cypress
- e2e-cypress-public
- e2e-pa11y
- e2e-pa11y-public
- build-client-coverage (anticipated, see _Risk: `istanbul` and `istanbul-combine` are not version locked._)
- smoketests
- switch-colors

🌴 **Recommendation:** Cache the `~/.npm` folder, including a hash of `package-lock.json` in the key. `npm ci && npm rebuild` will use this folder when it hydrates `node_modules`.

🌲 **Larger recommendation:** Cache the `node_modules` folder, including a hash of `package-lock.json` and a fingerprint of the operating system (machine executor version or Dockerfile version) in the key. Do not run `npm ci` or `npm rebuild` if this cache is hit. If this is a significant time savings, it may warrant adding an additional dependency installation step before parallel tests are run so they have a pre-warmed cache. 

📈 **Expected outcome:** Any reduction in time that can be achieved by caching will be multiplied by 4 for the four affected build stages.

**Comment by adunkman** [comment]
## Longer-term findings, recommendations, and expected outcomes

### Introduce a seed step for test environments and remove seed scripts from deploy processes.

Our longest running job is `deploy`, and it performs the following steps which are designed to add users to test environments: 

- Deploy - Web API - Cognito Create Users (~2:30)
- Deploy - Web API - Cognito Create Court Users (~1:30)

🌴 **Recommendation:** Separate these tasks from everyday deploys and into an initial environment setup task. This work is also tracked at https://github.com/ustaxcourt/ef-cms/issues/540.

📈 **Expected outcome:** Removing these steps would reduce the runtime of the `deploy` step by approximately 4 minutes for test environments, and test environments receive the most frequent deploys.

### Reduce infrastructure components to reduce deploy times. 

The longest-running steps of `deploy` involve `terraform apply`. This is because the application heavily leverages infrastructure components within AWS, and replicates its configuration manually. 

An alternative approach would be to limit the number of places which AWS infrastructure is configured by encapsulating the entire application within a single container, either using a single docker image or a Platform-as-a-Service. `HHS/TANF-app` takes this approach, and [deploys complete in approximately 2 minutes](https://app.circleci.com/pipelines/github/HHS/TANF-app/116/workflows/99aa052b-a315-485b-90f3-a8bb280c7f34/jobs/192).

EF-CMS is a a JavaScript CRUD application and backing data stores. The most simple infrastructure to manage this kind of application would be using a PaaS, which would provide multi-region application replication, traffic routing, and zero-downtime deployments while reducing configuration and deployment time.

🌴 **Recommendation:** If a PaaS is an option the Court wants to explore, explore encapsulating the application in a single image, including the public and private client applications and public and private APIs. Any infrastructure component which requires state (DynamoDB, Elasticsearch, S3) would remain outside of this container. If this approach is taken, the same container can be used to start test environments in CI, which would dramatically reduce the complexity of booting the application for end-to-end, pa11y, and integration tests.

📈 **Expected outcome:** There is no hard data I can provide here — there are too many variables. Simplifying infrastructure in this way would reduce the freedom of development (a PaaS provider provides one or two ways of accomplishing a task) in the name of simplicity. A switch of this kind would certainly be incremental and require planning, leading to a temporary period of time where infrastructure becomes more complex. 

### Untangle and revisit strategy on how dependencies are installed.

Dependencies are included in a few ways: 

1. A custom CircleCI runner, built manually from `Dockerfile-CI` and stored in ECR. Henceforth referred to as "ECR image".
2. A docker image, tagged `efcms`, built in CI by the `deploy` and `migrate` steps, from `Dockerfile`. Henceforth referred to as "efcms image".
3. Installed from NPM, installed by `build-api`, `build-client-integration`, `build-client-unit`, `build-shared`, `e2e-cypress`, `e2e-cypress-public`, `e2e-pa11y`, `e2e-pa11y-public`, `build-client-coverage`, `smoketests`, and `switch-colors`.

There are a few key things we do through CI: 

- Build stuff. Compile assets, bundle up lambdas, etc. 
- Run simpler testing tasks. Unit tests, linters, calculating and reporting code coverage, etc.
- Run complex tests. Runs the application so we can test it, and tests it with cypress tests, pa11y tests, etc.
- Deploy and configure stuff. Terraform, AWS CLI operations, shell scripts which invoke node tasks, etc.

There isn’t a clear strategy for providing dependencies to jobs, which results in most jobs installing most dependencies, even though the job itself needs only a subset of those dependencies. By job, dependencies come from:

- build-api: ECR image, installed from npm.
- build-client-integration: ECR image, installed from npm, docker images for `amazon/dynamodb-local` and `elastic/elasticsearch`.
- build-client-unit: ECR image, installed from npm.
- build-shared: ECR image, installed from npm.
- e2e-cypress: ECR image, installed from npm, cypress reinstalled with `cypress install`, docker images for `amazon/dynamodb-local` and `elastic/elasticsearch`.
- e2e-cypress-public: ECR image, installed from npm, cypress reinstalled with `cypress install`, docker images for `amazon/dynamodb-local` and `elastic/elasticsearch`.
- e2e-pa11y: ECR image, installed from npm, docker images for `amazon/dynamodb-local` and `elastic/elasticsearch`.
- e2e-pa11y-public: ECR image, installed from npm, docker images for `amazon/dynamodb-local` and `elastic/elasticsearch`.
- build-client-coverage: ECR image, installed from npm.
- deploy: efcms image, uses machine executor with no dependencies or node version lock to run `npm run pending-color-switch`.
- migrate: efcms image.
- smoketests: ECR image, installed from npm. Note: Cypress not reinstalled as above.
- switch-colors: ECR image, installed from npm.

🌴 **Recommendation:** Create and implement a strategy for how each kind of task will receive its dependencies, focusing on installing them once in as few ways as possible. Leverage caches for jobs to reuse previously installed and built dependencies, so new branches and commits do not invoke new installations unless the dependencies change.

🌴 **Recommendation:** Remove the ECR image. It creates a hard coupling between runs across branches of a repository and makes updates to those dependencies more complicated with team-wide synchronization required. There is already an established pattern for building and using a docker image (the efcms image) which avoids this problem. 

🌴 **Recommendation:** Use off-the-shelf docker images through docker-compose for common tools, including [`sonar-scanner`](https://hub.docker.com/r/sonarsource/sonar-scanner-cli), [`terraform`](https://hub.docker.com/r/hashicorp/terraform), and [`aws-cli`](https://hub.docker.com/r/amazon/aws-cli). Use [volumes](https://docs.docker.com/storage/volumes/) to attach the code to these images. These off-the-shelf images are officially supported, do not require any dependencies outside of Docker to run, and have first-class support among CI providers including CircleCI and GitHub Actions. There is already an established pattern of using off-the-shelf images for dependent services (`amazon/dynamodb-local` and `elastic/elasticsearch`), but not yet one for these tools.

📈 **Expected outcome:** Implementing a clear strategy for how dependencies are installed will allow them to be installed once and cached in CI, and using off-the-shelf images will allow more straightforward and independent version updates. There are too many variables here to specifically highlight the time reduction, but it would reduce the second column here bringing it closer to the third:

| Task | [Latest `staging`](https://app.circleci.com/pipelines/github/ustaxcourt/ef-cms/2066/workflows/f983e68e-5188-4483-a7e4-94dad1de2b1c) runtime | Time spent executing main job steps |
|------|---------------------------|-----------------------------------|
| build-api | 3:21 | 0:39 (Web API - Test)
| build-client-integration | 9:35 | 7:12 (Web Client - Integration Test max time)
| build-client-unit | 13:36 | 11:04 (Web Client - Unit Test) 
| build-shared | 11:16 | 8:46 (Shared - Test)
| e2e-cypress | 9:07 | 6:45 (Cypress)
| e2e-cypress-public | 4:40 | 2:00 (Cypress)
| e2e-pa11y | 8:58 | 6:36 (Pa11y)
| e2e-pa11y-public | 4:53 | 2:26 (Pa11y)
| build-client-coverage | 0:45 | 0:10 (Combine Coverage + Check Coverage)
| deploy | 17:43 | 16:10 (Deploy - Web API - Terraform through Deploy - Verify Private Elasticsearch)
| migrate | 1:21 | 0:00 (Setup Migration Infrastructure through Wait for SQS Queue to Empty)
| smoketests | 7:08 | 5:15 (Cypress Smoke Tests + Pa11y Smoke Tests)
| switch-colors | 3:11 | 1:18 (Switch Colors)

**Comment by adunkman** [comment]
Last week, Mike, Eric, and myself met to discuss — decided to take the low hanging fruit over to the [EF-CMS OpEx/DevEx](https://trello.com/b/9tgrIFfA/ef-cms-opex-devex) board, and leave the larger items as food for thought for now. 

- [Fix source code caching in CI.](https://trello.com/c/cWgsPhX6/941-fix-source-code-caching-in-ci)
- [Remove source code caching in CI?](https://trello.com/c/NkBmO1Ny/942-remove-source-code-caching-in-ci)
- [Cache the ~/.npm folder in CI](https://trello.com/c/UguGJVbu/943-cache-the-npm-folder-in-ci)
- [Prevent automatic installation of missing npm packages.](https://trello.com/c/K2EHa9wi/944-prevent-automatic-installation-of-missing-npm-packages)

With that, I believe this spike is complete! We can reference this issue in the future to see if our timings have improved after these changes.
