### ISSUE TITLE
BUG: Pretrial Memorandum is getting uploaded to cases with Test data populated in the fields

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8322]
**Describe the Bug**
This has been reported twice now (Case 5584-21 and Case 1863-21). Petitioner adds a Pretrial Memorandum to their case, all looks correct when previewing the document prior to upload, after upload when viewing the document on the docket record, it has bogus test data in it.

If you look in S3, the original file is the correct file with the Petitioners information in it, but if you open the second version in S3, it has all of the bogus test data in it.

**Case 5584-21**
* Original File from S3: [https://app.zenhub.com/files/152320868/d3fb6a4c-d18e-422a-99a7-004b73dd5cbb/download](https://app.zenhub.com/files/152320868/d3fb6a4c-d18e-422a-99a7-004b73dd5cbb/download)
* Version 2 of File from S3: [https://app.zenhub.com/files/152320868/6472340b-227a-4218-b732-8b6d43daa49d/download](https://app.zenhub.com/files/152320868/6472340b-227a-4218-b732-8b6d43daa49d/download)
* Original File from S3 that was resaved (this one loads correctly): [https://app.zenhub.com/files/152320868/12318268-234b-48a0-b900-126f7fdc392c/download](https://app.zenhub.com/files/152320868/12318268-234b-48a0-b900-126f7fdc392c/download)

**Case 1863-21**
* Original File from S3: [https://app.zenhub.com/files/152320868/e38b3e11-b291-475f-b93f-19aeac1cd8e2/download](https://app.zenhub.com/files/152320868/e38b3e11-b291-475f-b93f-19aeac1cd8e2/download)
* Version 2 of File from S3: [https://app.zenhub.com/files/152320868/fa86cd8e-68a4-4f7d-8172-e6f08b3ca382/download](https://app.zenhub.com/files/152320868/fa86cd8e-68a4-4f7d-8172-e6f08b3ca382/download)
* Original File from S3 that was resaved (this one loads correctly): [https://app.zenhub.com/files/152320868/002dad1e-e5c0-4d9b-ae3c-246b4b0a8881/download](https://app.zenhub.com/files/152320868/002dad1e-e5c0-4d9b-ae3c-246b4b0a8881/download)

We are hoping to get some additional information from the Petitioner about where he downloaded the form, what browser he used, what process he took, etc.  We will update this ticket if we find out more information.

We have done quite a bit of testing on this one:

1. Chris and I both downloaded the blank form from the website, filled it out with test data, uploaded it to new cases on both of our test environments
result: We were **unable** to recreate this issue, everything uploaded correctly

2. Mike downloaded the original file that the Petitioner had loaded from S3 logged into the Test environment, and uploaded it to 1863-21S
result: Mike **WAS** able to recreate the problem in TEST.

3. I downloaded the original PDF file from S3, logged into TEST environment as a docket clerk, attempted to do a PDF upload of the original file
result: I **WAS** also able to recreate the issue

4. I simply re-saved the original file from S3 to another PDF, logged into TEST environment as a docket clerk, and then uploaded the newly saved PDF to the case.
result: the newly saved document saved appropriately.

5. I logged in to Mig as a petitioner, filed a document, selected Original PDF, preview looked fine, uploaded the document
result: I **WAS** able to recreate the issue

6. I logged in to Mig as a petitioner, filed a document, selected Original **resaved** PDF, preview looked fine, uploaded the document
result: document uploaded fine

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod, Mig, Test

**Who were you logged in as?**
Petitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the system

**To Reproduce**
1. Use the original file that Petitioner uploaded
2. Log in as Petitioner that has a case
3. File a document on the case
4. Select Pretrial Memorandum as document type
5. Upload the original file from Petitioner
6. Preview the file before submitting (should look fine)
7. Submit the file to the tax court
8. Open the file from the docket record and notice that the file has bogus data in it!

**Expected Behavior**

Files uploaded should not get populated with bogus data

**Actual Behavior**
A clear and concise description of what actually happened.
Pre trial memorandum that was filed got bogus test data added, and the original information is gone.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by codyseibert** [comment]
How to reproduce:

1. download the file from https://app.zenhub.com/files/152320868/d3fb6a4c-d18e-422a-99a7-004b73dd5cbb/download to your desktop with name `testing.pdf`
2. open it in the mac pdf previewer app and save the file (don't make any changes)
3. open the file in chrome, then for "Filed Electronically", check "yes", check it back to "no", then click somewhere else on the page to lose focus on the checkbox
4. save the file and overwrite the file with the same name on your desktop `testing.pdf`
5. open the file in chrome (notice all the fields were reverted back to the defaults)

**Comment by ttlenard** [comment]
We received some additional information from the Petitioner:

**1.  Where did he download the original file from?**  
He retrieved the PTM from the Court’s website.

**2.  What browser was he using?**
Google Chrome.

**3.  How did he fill it out? Adobe reader? In a browser?**
Through the browser.

**4.  What were the processes he used when saving the document? (save first as a word doc? google doc? Then convert to PDF?)**
After entering his data, he downloaded as a PDF and thereafter uploaded the saved PDF file to his case during the efiling process.

**5.  Any additional information that he may have that could help us troubleshoot why this occurred.**
He was able to successfully upload and file his proposed trial exhibits in his case and did not do anything different as far as saving and uploading his PDF documents.

**Comment by TomElliottFlexion** [comment]
Update: The PDF has been replaced with a fresh, test-dataless PDF. Monitoring for future occurrences of this bug.
