### ISSUE TITLE
SPIKE: Chief Judge Transition

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8325]
As a court, so that business operations transition smoothly, I need to understand what changes need to be made in DAWSON at the code level to facilitate the change from Chief Judge Foley to Chief Judge Kerrigan.

On June 1 2022, Judge Kerrigan assumes the office of Chief Judge, an office held in its entirety during DAWSON's lifespan by Judge Foley. In addition to updating things like the Chief Judge's signature, we would like to understand if there are any other areas of the application that will need modification to support the change in officeholder (generated reports, associations between the Chief Judge as an office versus the officeholder) and any potential refactoring that could be done to make the transition between incoming and outgoing easier in the future .

This is a spike to analyze the codebase and determine what stories may be necessary to support the transition between Chief Judge officeholders.

The output should be documentation of what areas of DAWSON will be need to be updated prior to the transition.

Timebox: 8 hours

## Acceptance Criteria
* Features/operations that will need to be modified are identified and documented

## Notes
Follow up to determine if there will be an overlap of outgoing and incoming Chief Judge

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by TomElliottFlexion** [comment]
## 9462 SPIKE

### Changes needed: 
- Add feature flag to enable switchover without deploy
- Change value of `chiefJudgeNameForSigning` (conditionally w/ feature flag) in `sharedAppContext` and fix resulting broken hardcoded tests.
- Refactor tests to use constant for Chief Judge instead (optionally do this step first to avoid broken tests)
- Change Kerrigan's Title to `Chief Judge` and Foley's to `Judge` in `judge_users.csv`

### Notes: 
- Cases/items with Kerrrigan as the `associatedJudge` will remain under Kerrigan's name. Old cases/items under "Chief Judge" will remain under "Chief Judge". New cases/items will continue to be associated with "Chief Judge"
- Any reassignment of cases/item listed under Kerrigan will be done via court procedure rather than programmatically. 
- Everything should be toggled by a feature flag except for updates to Judge Foley and Judge Kerrigan's titles. This will not affect the wider designation of `Chief Judge`, but means that documents signed by Foley or Kerrigan explicitly (not by the 'Chief Judge') will continue to be signed by "Foley, Chief Judge" and "Kerrigan, Judge" until a redeploy. (Documents signed by the Chief Judge can be toggled dynamically)

**Comment by jamesobrooks** [comment]
@TomElliottFlexion would it work (or even make sense) to instead of a feature flag, have the Chief Judge be a configuration item similar to what we recently worked on?

**Comment by TomElliottFlexion** [comment]
Funny that you mention that- we talked about it and since we'd have to query for it before applying any signature, or before serving most documents, the performance hit most likely wouldn't be worth the convenience

**Comment by jamesobrooks** [comment]
Cool. I wouldn't push too hard for it, but if we could grab it once per session I think it might have benefit. Of course Chief Judge won't change too often, but there might be the possibility of abrupt changes for various reasons. @cholly75 could probably tell us more about what might happen in the case of short-notice retirement, incapacitation, etc.

**Comment by cholly75** [comment]
Great thoughts, appreciate the forward thinking! When the CJ is out (vacation, illness, emergency, whatever) an order is issued granting another judge "Acting" CJ powers in their absence (precisely to avoid having to implement new stuff every time). In the case of short-notice retirement or an otherwise longer term thing that would require a more permanent change in officeholder, the Court would have to reconvene to re-elect, and that is... not a quick process. I feel like we'd have ample time to address that if needed.

**Comment by TomElliottFlexion** [comment]
@jamesobrooks We just talked about this too! I also wouldn't be opposed to using this as an opportunity to implement that pattern- if we had solid infrastructure around this it would open up a lot of configuration options down the road.
