### ISSUE TITLE
Edit Docket Entry: Unservable to Servable Document Types

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8326]
As a Docket Clerk, so that I can correct mislabeled docket entries, I need to be able to change a docket entry initially classified as an "unservable" document type to a "servable" document type.

Note: this is in response to discovery w ustaxcourt/ef-cms#8178 - see notes from @rosiehsmith 

Currently, if a docket entry initially entered as a type considered by DAWSON to be "unservable" is edited to a document type that is "servable", the docket entry becomes inoperable due to the fact that no work item was generated when the docket entry was created. This leads to a situation where the edited docket entry cannot be served (it throws a 400 error in DAWSON).

Example: editing a Trial Exhibit entry to a Miscellaneous entry.

Full list of unservable document types can be found here: https://github.com/ustaxcourt/ef-cms/blob/staging/shared/src/tools/courtIssuedEventCodes.json

We would like to have the system recognize what is needed when the docket entry is edited, and handle the conversion gracefully.

## Acceptance Criteria
* Unservable doctype docket entry can be edited to reclassify as servable doctype docket entry
* Edited docket entry can be served
* Edited docket entry is otherwise operable as if it had been initially created with the edited doctype

## Test Cases
* Create a docket entry for an unservable doctype (Trial Exhibit); edit the docket entry to a servable doctype (Miscellaneous). Docket record displays Edit link, and served status is Not Served; Edit link can be clicked and document can be edited further and served/saved as per usual behavior.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by jimlerza** [comment]
Related:
https://github.com/flexion/ef-cms/issues/9372#issuecomment-1050072046

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Create a docket entry for an unservable doctype (ex: Trial Exhibit); edit the docket entry to a servable doctype (ex: Miscellaneous). Docket record displays Edit link, and served status is Not Served; Edit link can be clicked and document can be edited further and served/saved as per usual behavior.
- Log in as a Docket Clerk
- Navigate to a case
- Click Create
- Select PDF upload, and click save
- Click Add Docket Entry
- For document type, select Trial Exhibits, fill out the rest of the required fields
- Click Save Entry
- Click the Edit button for the trial exhibit document you just added on the docket record
- Change the document type to a servable document (ex: Miscellaneous), add a description

Expected Results
- [ ] **NEW FUNCTIONALITY** - User has the ability to save entry or Serve
- [ ] **NEW FUNCTIONALITY** - After Saving or Serving the document, the document entry on the docket record has the edit button available
- [ ] Clerk can edit entry as per usual behavior of servable document types

* Be sure to test with other unservable to servable document types in additional tests following this same workflow.

**Comment by rosiehsmith** [comment]
It looks like this was resolved around the time of [9513](https://github.com/flexion/ef-cms/issues/9513).

There was a lot done with work items in serving documents in the[ associated PR ](https://github.com/ustaxcourt/ef-cms/pull/2390).

**Comment by cholly75** [comment]
Issue is already resolved in production.
