### ISSUE TITLE
Clinic Letter: Multiple NOTR Scenario

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8327]
As a Court, so that we can accurately represent the interests of pro se petitioners with clinic letters attached to the Notice of Receipt of Petition, I need to append a clinic letter to each Notice of Receipt of Petition generated when a petition is served.

When multiple petitioners are attached to a case (for instance petitioner and spouse) but they have two different addresses, two Notices of Receipt of Petition are generated. Currently, we are appending a single clinic letter to the resulting PDF.

We would like to append the appropriate clinic letter to each Notice of Receipt of Petition, provided the petitioner attached to the NOTR meets the criteria for clinic letter inclusion (i.e., is not represented by counsel).

## Acceptance Criteria
* When multiple Notices of Receipt of Petition are generated for a case, append the appropriate clinic letter to each of the NOTRs separately, based on whether or not the party is pro se

## Notes
* This may be required to be implemented prior to going live with the previous set of Clinic letter stories.

## Test Cases
* Petition is entered with petitioner and spouse having different addresses with neither party having counsel. Petition is served; appropriate clinic letter is appended to each NOTR generated
* Petition is entered with petitioner and spouse having different addresses with one party represented by counsel. Petition is served; NOTR for unrepresented party has appropriate clinic letter appended; NOTR for represented party does not have a clinic letter appended
* Regression test behavior w/ multiple petitioners w/ same address

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Petition is entered with petitioner and spouse having different addresses with neither party having counsel. Petition is served; appropriate clinic letter is appended to each NOTR generated**

- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions Clerk
- Click on Document QC
- Click on "Start a Petition" button
- For Party type, select "Petitioner and Spouse"
- Fill out Petitioner information and be sure that you have different addresses for both petitioners (I put that both Petitioners lived in Denver, CO, but with different addresses)
- Fill out the Case info tab, and be sure that you select Denver, Colorado for the Trial location
- For Case Procedure, click "Regular case"
- On the IRS Notice tab, for Type of Case, select "Deficiency" 
- Upload or scan in a Petition, STIN and RQT 
- Click "Create Case"
- Click "Serve to IRS"
- Click "Yes, Serve"

Expected Results:

- [x] The Print Paper Petition Receipt screen should appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, the appropriate Clinic letter will be appended to the end each of the Petitioners Notice of Receipt of Petition.


**2. Petition is entered with petitioner and spouse having different addresses with one party represented by counsel. Petition is served; NOTR for unrepresented party has appropriate clinic letter appended; NOTR for represented party does not have a clinic letter appended**

- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions clerk
- Click on Document QC
- Click on "Start a Petition" button
- For Party type, select "Petitioner and Spouse"
- Fill out Petitioner information and be sure that you have different addresses for both petitioners (I put that both Petitioners lived in Denver, CO, but with different addresses)
- Fill out the Case info tab, and be sure that you select Denver, Colorado for the Trial location
- For Case Procedure, click "Regular case"
- On the IRS Notice tab, for Type of Case, select "Deficiency" 
- Upload or scan in a Petition, STIN and RQT 
- Click "Create Case", and take note of the docket number
- Click "Save for later"
- Next, we need to add in an attorney to ONE of the petitioners
- Log out of DAWSON, and log back in as a docket clerk
- Navigate to the case, and click on case information tab
- Click on Parties
- Type PT4444 to the "Add Counsel" area and click "Search"
- Add Private Practitioner 6 (PT4444) to only ONE of the petitioners
- Click "Add to Case"
- Log out of DAWSON, and log back in as Petitions clerk
- Navigate to Document QC, and then click on "In Progress"
- Click on the Docket Number URL to open the case
- Click on the Petition Link
- Click on the Review and Serve Petition Link
- Click on Review Petition
- Click "Serve to IRS"
- Click "Yes, Serve"

Expected Results:

- [x] The Print Paper Petition Receipt screen should appear with the Notice of Receipt of Petition document for both Petitioners
- [x] If you scroll down, the appropriate Clinic letter will be appended to the end of the Unrepresented Petitioners Notice of Receipt of Petition.

- Click the "Done" link
- Navigate to the Case information tab
- Click on the "Print Confirmation" link on the Case Details Card

Expected Results

- [x] The Notice of Receipt of Petition should have the appropriate clinic letter appended to the end the unrepresented Petitioners Notice
- [x] The represented Petitioner should have a Notice of Receipt of Petition, but it should NOT have a clinic letter appended to the end of the document.


**3. Petition is entered with petitioner and spouse having the SAME address with neither party having counsel. Petition is served; appropriate clinic letter is appended to each NOTR generated** 
- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions Clerk
- Click on Document QC
- Click on "Start a Petition" button
- For Party type, select "Petitioner and Spouse"
- Fill out Petitioner information and be sure that you have the SAME address for both petitioners (I put that both Petitioners lived in Denver, CO)
- Fill out the Case info tab, and be sure that you select Denver, Colorado for the Trial location
- For Case Procedure, click "small case"
- On the IRS Notice tab, for Type of Case, select "Deficiency" 
- Upload or scan in a Petition, STIN and RQT 
- Click "Create Case"
- Click "Serve to IRS"
- Click "Yes, Serve"

Expected Results:

- [x] The Print Paper Petition Receipt screen should appear with only ONE Notice of Receipt of Petition document. 
- [x] If you scroll down, the appropriate Clinic letter will be appended to the end of the one Notice of Receipt of Petition.

**4. Petition is entered with petitioner and spouse having the SAME address with one party represented by counsel. Petition is served; NOTR for both parties do not have a clinic letter appended**
- Ensure that there are two clinic letters in the repository for Denver, CO. Be sure that one letter is for a regular proceeding type, and one letter is for a small proceeding type.
     - See [9429](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9429) Test Case 1 for instructions on how to upload a clinic letter in S3
     - If you are uploading new clinic letters, be sure that they are in this format: _clinic-letter-denver-colorado-small_ and _clinic-letter-denver-colorado-regular_
- Log in as a Petitions clerk
- Click on Document QC
- Click on "Start a Petition" button
- For Party type, select "Petitioner and Spouse"
- Fill out Petitioner information and be sure that you have the same address for both petitioners (I put that both Petitioners lived in Denver, CO)
- Fill out the Case info tab, and be sure that you select Denver, Colorado for the Trial location
- For Case Procedure, click "Regular case"
- On the IRS Notice tab, for Type of Case, select "Deficiency" 
- Upload or scan in a Petition, STIN and RQT 
- Click "Create Case", and take note of the docket number
- Click "Save for later"
- Next, we need to add in an attorney to ONE of the petitioners
- Log out of DAWSON, and log back in as a docket clerk
- Navigate to the case, and click on case information tab
- Click on Parties
- Type PT4444 to the "Add Counsel" area and click "Search"
- Add Private Practitioner 6 (PT4444) to only ONE of the petitioners
- Click "Add to Case"
- Log out of DAWSON, and log back in as Petitions clerk
- Navigate to Document QC, and then click on "In Progress"
- Click on the Docket Number URL to open the case
- Click on the Petition Link
- Click on the Review and Serve Petition Link
- Click on Review Petition
- Click "Serve to IRS"
- Click "Yes, Serve"

Expected Results:

- [x] The Print Paper Petition Receipt screen should appear with the Notice of Receipt of Petition document for one petitioner (the first petitioner), even if it is this petitioner that is represented.
- [x] If you scroll down, there should NOT be a Clinic letter will be appended to the end of the  Notice of Receipt of Petition.

- Click the "Done" link
- Navigate to the Case information tab
- Click on the "Print Confirmation" link on the Case Details Card

Expected Results

- [x] The Notice of Receipt of Petition should NOT have a clinic letter appended to the end  of the Notice
- [x] There should only be one Notice of Receipt of Petition, and it should NOT have a clinic letter appended to the end of the document.

**Comment by halprin** [comment]
Started in on this...  The current branch is `story-9464-multiple_notr_real`.

# Changes Thus Far

- `shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.js`: I no longer convert the `UInt8Array` to a `Buffer` in `generatePaperNoticeForContactSecondary` because if there's a secondary petitioner, the `combineTwoPdfs` will crash.
- `shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.js`: move the clinic letter tests into their own describe blocks.  Added a new unit test that has a second petitioner at a different address.

# Thoughts

- The new unit test I added should probably change its assertion to be based on the number of pages of the PDF that is generated, not the number of calls to `combineTwoPdfs`.
- the other previous clinic letter tests have a secondary petitioner, but never changed the address.  I'm thinking of removing the secondary petitioner from all of those tests to make them more simple tests, and then add new ones that will test the permutations of multiple petitioners.
- After writing more unit tests (that will fail), then start changing the code.
- I'm thinking of regiggering the actual (i.e. non-test) code to be more DRY.  There's some custom logic to generate the notice for the secondary petitioner that is similar to the primary petitioner.

**Comment by ttlenard** [comment]
Some notes on behavior:
1- If there is a Petitioner and Spouse with different addresses, and one petitioner is represented; It is ok if they are still receiving a print confirmation of the Notice of Receipt of Petition at this point.
2 - If there is a Petitioner and Spouse with the SAME address, and one petitioner is represented, only one Notice will be generated for paper printing, even though they are represented.

The most important thing here is that we don't want represented petitioners receiving a clinic letter. After testing this story, the represented petitioner never received a clinic letter, so we are all good!
