### ISSUE TITLE
BUG: When attempting to view docket section outbox, user is logged out

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8328]
**Describe the Bug**
This was reported by Docket. When navigating to the processed tab of the section outbox screen, they immediately get the "Technical Error" message and are kicked back to the login screen.

We have run into something like this before. This bug [8933](https://github.com/flexion/ef-cms/issues/8933) was logged.  Mike then created a script [1669](https://github.com/ustaxcourt/ef-cms/pull/1669) to move records out of the `section-outbox|docket` partition in dynamo. For a more permanent solution he did some refactoring [1739](https://github.com/ustaxcourt/ef-cms/issues/1739), so that the records now have a TTL (time to live), which removes records older than 7 days.  The Problem is that this issue has cropped up again.

Even though the section-outbox messages delete themselves after they've lived for 7 days, it is still possible that the outbox is so large that DAWSON can't display it.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Production

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the system

**To Reproduce**
1. Log in as docket
2. Click on Document QC
3. Click on Processed tab
4. Get logged out of system

**Expected Behavior**
Shouldn't be getting logged out when clicking on processed tab

**Actual Behavior**
A clear and concise description of what actually happened.
When clicking on the processed tab, docket is getting logged out.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by TomElliottFlexion** [comment]
Update: Short term: Outbox will retrieve fewer, smaller items, based on a configurable number of days to query for. 
Long term: Story will be added to backlog to redesign section "Processed" tab
