### ISSUE TITLE
Add Notice of Receipt of Petition to Docket Record

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8330]
As a court user, in order to provide full transparency to the public on the status of a case, I would like the docket record to reflect when a petition has been received/served by the court.

Currently when a petition is served to the IRS, DAWSON generates a Notice of Receipt of Petition informing the petitioner. This Notice (NOTR) is only made available via the Print Confirmation link located on the Case Information tab.

To standardize USTC processes and provide a transparent record of a case, we would like to add the NOTR as an entry on the Docket Record for the case and serve it to the Petitioner(s).

## Acceptance Criteria
* When a Notice of Receipt of Petition is generated, it is added to the Docket Record with the event code NOTR
* The value for the text in the "Filings and Proceedings" column on the Docket Record is "Notice of Receipt of Petition"
* Upon being added to the Docket Record, the Notice of Receipt of Petition is served to all petitioners (or counsel if represented) on the case
  * If the Petitioner has electronic service, they are notified via email in the usual manner
  * If the Petitioner has paper service, the clerk is presented with the Notice of Receipt of Petition for service (this already happens today)
* When viewed from the Docket Record, the Notice of Receipt of Petition reflects the file in its entirety as shown when viewing the Print Confirmation link 
* The Notice of Receipt of Petition is still available via the Print Confirmation link in the usual manner

## Test Cases
* Paper pro se petition is served, clerk is presented with printing paper service, the Notice of Receipt of Petition is added to the Docket Record and is still available on the Print confirmation link.
* Electronic pro se petition is served, the Notice of Receipt of Petition is added to the docket record, Petitioner receives an email that a document has been served on their case, Notice of Receipt of petition is available on the Print confirmation link.
* Represented electronic petition is served, the Notice of Receipt of Petition is added to the docket record, Counsel receives an email that a document has been served on their case, Notice of Receipt of petition is available on the Print confirmation link.
* Paper pro se petition with multiple petitioners (Petitioner and Spouse) with the same address is served, clerk is presented with printing paper service (only one NOTR is generated), the one Notice of Receipt of Petition is added to the Docket Record and is still available on the Print confirmation link.
* Paper pro se petition with multiple petitioners (Petitioner and Spouse) with different addresses is served, clerk is presented with printing paper service (there will be two NOTR documents, one for each petitioner), the two Notice of Receipt of Petitions are added to the Docket Record as one Notice, and it is still available on the Print confirmation link.

* Regression test Clinic Letters  (Small and Regular proceeding type) that get sent out with NOTR with pro se Petitioner, represented petitioner, multiple pro se petitioners with different addresses, multiple pro se petitioners with the same address, mixed representation, ensuring that clinic letters appear with the NOTR on the docket record. 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Paper pro se petition is served, clerk is presented with printing paper service, the Notice of Receipt of Petition is added to the Docket Record and is still available on the Print confirmation link.**
- Log in as a Petitions Clerk
- Click on Document QC Tab
- Click on "Start a petition" button
- Select the party type as "Petitioner" and fill out all of the required fields under the party tab, Case info, IRS Notice, and upload/scan in a Petition, STIN, and RQT document.
- Click on the "Create Case" button
- Click on the "Serve to IRS" button
- Click on the "Yes, Serve" button
- You will be presented with the Print Paper Petition Receipt.  Take note of the content of this document. Click "Done"
- You should get confirmation that the Petition was served to the IRS
- Click on the Served Tab
- The petition that you just served should be on the top of the list
- Click on the Docket number to open the case

Expected Results

- [x] The Notice of Receipt of Petition should be an entry on the Docket record
- [x] The Date should be todays date
- [x]  The Event Code should be NOTR
- [x]  The Filings and Proceedings should be "Notice of Receipt of Petition"
- [x]  The pages should reflect the number of pages of the document
- [x]  The Filed by should be blank
- [x]  The Action should be blank
- [x]  The Served should be today's date
- [x]  The Parties code should be "P"

- Click on the Notice of Receipt of Petition Link.

Expected Results

- [x] The document in the document view should be the exact same document that you took note of on the Print Paper petition receipt above.

- Click on the Case Information tab
- Click on the "Print Confirmation" Link

Expected Results

- [x] The document should be the same as the document that you took note of on the Print Paper petition receipt, and should be the same document that is on the Docket record.


**2. Electronic pro se petition is served, the Notice of Receipt of Petition is added to the docket record, Petitioner receives an email that a document has been served on their case, Notice of Receipt of petition is available on the Print confirmation link.**
- Log in as a Petitioner (be sure that you have access to the email account that you will be using for this user)
- Click "Start a Case"
- Click "Got it, Let's Start a Case"
- Upload a STIN and click "continue"
- Upload a Petition and click "continue"
- Fill out the rest of the required information for a petitioner
- Click "Submit to US Tax Court"
- Take note of the Docket number that you receive.
- Log out of DAWSON

- Log in as a Petitions Clerk
- Click on Document QC Tab
- Click on the "Switch to Section Document QC" link
- Scroll to the bottom of the page, and click on the petition link for the petition you just submitted in the previous steps
- Click on the IRS notice tab, and select No
- Click the "Review Petition" button
- Click "Serve to IRS"
- Click "Yes, Serve"
- You should get confirmation that the Petition was served to the IRS
- Click on the Served Tab
- The petition that you just served should be on the top of the list
- Click on the Docket number to open the case

Expected Results

- [x] The Notice of Receipt of Petition should be an entry on the Docket record
- [x] The Date should be todays date
- [x]  The Event Code should be NOTR
- [x]  The Filings and Proceedings should be "Notice of Receipt of Petition"
- [x]  The pages should reflect the number of pages of the document
- [x]  The Filed by should be blank
- [x]  The Action should be blank
- [x]  The Served should be today's date
- [ ]  The Parties code should be "P"

- Click on the Case Information tab
- Click on the "Print Confirmation" Link

Expected Results

- [x] The document should be the typical Notice of Receipt of Petition document, that includes the case caption, docket number, eAccess information, the Petitioners address, etc.

- Click the "Back" URL to return to the case
- Click on the Notice of Receipt of Petition Link on the docket record

Expected Results

- [x] The document in the document view should be the same as the document that was in the Print Confirmation link.

- Next, check the Petitioners email, and ensure that you received an email indicating Service

Expected Results:

- [x] Email notification received from "noreply"
- [x] Email subject "eService Notification from US Tax Court on Case XXXX-XX"
- [x] Email content should look like the typical service email. Example below:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/ca7525c1-b325-4418-8f56-7db78d08cda4)


**3. Represented electronic petition is served, the Notice of Receipt of Petition is added to the docket record, Counsel receives an email that a document has been served on their case, Notice of Receipt of petition is available on the Print confirmation link.**
- Log in as a Private Practitioner (be sure that you have access to the email account that you will be using for this user. If needed, you will need to add a new practitioner to the DB as an admissions clerk)
- Click "Start a Case"
- Click "Got it, Let's Start a Case"
- Upload a STIN and click "continue"
- Upload a Petition and click "continue"
- Fill out the rest of the required information for a petitioner
- Click "Submit to US Tax Court"
- Take note of the Docket number that you receive.
- Log out of DAWSON

- Log in as a Petitions Clerk
- Click on Document QC Tab
- Click on the "Switch to Section Document QC" link
- Scroll to the bottom of the page, and click on the petition link for the petition you just submitted in the previous steps
- Click on the IRS notice tab, and select No
- Click the "Review Petition" button
- Click "Serve to IRS"
- Click "Yes, Serve"
- You should get confirmation that the Petition was served to the IRS
- Click on the Served Tab
- The petition that you just served should be on the top of the list
- Click on the Docket number to open the case

Expected Results

- [x] The Notice of Receipt of Petition should be an entry on the Docket record
- [x] The Date should be todays date
- [x]  The Event Code should be NOTR
- [x]  The Filings and Proceedings should be "Notice of Receipt of Petition"
- [x]  The pages should reflect the number of pages of the document
- [x]  The Filed by should be blank
- [x]  The Action should be blank
- [x]  The Served should be today's date
- [ ]  The Parties code should be "P"

- Click on the Case Information tab
- Click on the "Print Confirmation" Link

Expected Results

- [x] The document should be the typical Notice of Receipt of Petition document, that includes the case caption, docket number, eAccess information, the Petitioners address, etc.

- Click the "Back" URL to return to the case
- Click on the Notice of Receipt of Petition Link on the docket record

Expected Results

- [x] The document in the document view should be the same as the document that was in the Print Confirmation link.

- Next, check the Practitioners email, and ensure that you received an email indicating Service

Expected Results:

- [x] Email notification received from "noreply"
- [x] Email subject "eService Notification from US Tax Court on Case XXXX-XX"
- [x] Email content should look like the typical service email. Example below:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/ca7525c1-b325-4418-8f56-7db78d08cda4)


**4. Paper pro se petition with multiple petitioners (Petitioner and Spouse) with the same address is served, clerk is presented with printing paper service (only one NOTR is generated), the one Notice of Receipt of Petition is added to the Docket Record and is still available on the Print confirmation link.**
- Log in as a Petitions Clerk
- Click on Document QC Tab
- Click on "Start a petition" button
- Select the party type as "Petitioner and Spouse" and fill out all of the required fields under the party tab, Case info, IRS Notice, and upload/scan in a Petition, STIN, and RQT document.
- Be sure that the Petitioners have the SAME address
- Click on the "Create Case" button
- Click on the "Serve to IRS" button
- Click on the "Yes, Serve" button
- You will be presented with the Print Paper Petition Receipt.  Take note of the content of this document (there should only be one NOTR). Click "Done"
- You should get confirmation that the Petition was served to the IRS
- Click on the Served Tab
- The petition that you just served should be on the top of the list
- Click on the Docket number to open the case

Expected Results

- [x] There should be one Notice of Receipt of Petition as an entry on the Docket record
- [x] The Date should be todays date
- [x]  The Event Code should be NOTR
- [x]  The Filings and Proceedings should be "Notice of Receipt of Petition"
- [x]  The pages should reflect the number of pages of the document
- [x]  The Filed by should be blank
- [x]  The Action should be blank
- [x]  The Served should be today's date
- [x]  The Parties code should be "P"

- Click on the Notice of Receipt of Petition Link.

Expected Results

- [x] The document in the document view should be the exact same document that you took note of on the Print Paper petition receipt above.

- Click on the Case Information tab
- Click on the "Print Confirmation" Link

Expected Results

- [x] The document should be the same as the document that you took note of on the Print Paper petition receipt, and should be the same document that is on the Docket record.

**5. Paper pro se petition with multiple petitioners (Petitioner and Spouse) with different addresses is served, clerk is presented with printing paper service (there will be two NOTR documents, one for each petitioner), the two Notice of Receipt of Petitions are added to the Docket Record as one Notice, and it is still available on the Print confirmation link.**
- Log in as a Petitions Clerk
- Click on Document QC Tab
- Click on "Start a petition" button
- Select the party type as "Petitioner and Spouse" and fill out all of the required fields under the party tab, Case info, IRS Notice, and upload/scan in a Petition, STIN, and RQT document.
- Be sure that the Petitioners have DIFFERENT addresses!
- Click on the "Create Case" button
- Click on the "Serve to IRS" button
- Click on the "Yes, Serve" button
- You will be presented with the Print Paper Petition Receipt.  Take note of the content of this document (there should only be two separate NOTR documents on this print page). Click "Done"
- You should get confirmation that the Petition was served to the IRS
- Click on the Served Tab
- The petition that you just served should be on the top of the list
- Click on the Docket number to open the case

Expected Results

- [x] There should be one Notice of Receipt of Petition as an entry on the Docket record
- [x] The Date should be todays date
- [x]  The Event Code should be NOTR
- [x]  The Filings and Proceedings should be "Notice of Receipt of Petition"
- [x]  The pages should reflect the number of pages of the document
- [x]  The Filed by should be blank
- [x]  The Action should be blank
- [x]  The Served should be today's date
- [x]  The Parties code should be "P"

- Click on the Notice of Receipt of Petition Link.

Expected Results

- [x] The document in the document view should be the exact same document that you took note of on the Print Paper petition receipt above (two NOTR's, one for each petitioner, combined into one document).

- Click on the Case Information tab
- Click on the "Print Confirmation" Link

Expected Results

- [x] The document should be the same as the document that you took note of on the Print Paper petition receipt, and should be the same document that is on the Docket record (two NOTR's, one for each petitioner, combined into one document).

_Do some Regression testing for Clinic Letters (Small and Regular proceeding type) that get sent out with NOTR with pro se Petitioner, represented petitioner, multiple pro se petitioners with different addresses, multiple pro se petitioners with the same address, mixed representation, ensuring that clinic letters appear with the NOTR on the docket record._

**Comment by ttlenard** [comment]
@codyseibert This story looks great on exp4, but I don't think that the changes that were implemented in 9464 were available yet.  Can we please push this code to TEST so that we can do some testing with the multiple NOTR clinic letter scenario? Thank you!
cc: @cholly75 @jimlerza

**Comment by ttlenard** [comment]
@codyseibert This story looks great on exp4, but I don't think that the changes that were implemented in 9464 were available yet.  Can we please push this code to TEST so that we can do some testing with the multiple NOTR clinic letter scenario? Thank you!
cc: @cholly75 @jimlerza
