### ISSUE TITLE
BUG: Formatting issues with DAWSON Generated Orders

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8331]
**Describe the Bug**
Multiple internal Court staff have reported that there are formatting issues with Orders generated in DAWSON after the new style change was implemented in Story [9093](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9093).

Issue number 1 - It seems the paragraph indentations in orders created in DAWSON are all over the place...some are correct (one tab over), many are over too far (two tabs over).  Everything looks correct in the pre-signature (generate), but if I view on the Preview screen and when I add the Judges signature and save it, that's when the indentations go haywire.  

I have not found a work around to get the indentations correct. Court staff have reported that they are now generating Orders outside of DAWSON for the time being.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**
Judge, ADC

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Using the Application

**To Reproduce Issue number 1**
1. Go to a case
2. Click on create
3. Scroll down to Order
4. Begin drafting an order by doing some typical formatting (indent paragraphs by clicking the tab key and notice that it is 5 characters spaced in. I was copy/pasting from existing orders that have multiple paragraphs.
5. Preview the Order (notice in the preview that the spacing is not consistent between paragraphs. It will appear that every other paragraph is indented the same)
6. Close preview
7. Save the Order
8. Sign the Order
8. Notice that the indentations are still off.
9. Also notice that the header US Tax Court seems to be bunched in with the text Washington, DC...(Per Chris - Don't think we will be addressing this one though)

Note: I attempted to see if there was a work around for this by clicking the space bar 5 times, but this results in NO indentation.  I also attempted to copy/paste into notepad, and then copy that into the Order Generator. This resulted in more work to get it formatted, correctly, and then after doing this, there were actually 3 indentation levels to the paragraphs. Court staff have reported that they are generating the Orders outside of DAWSON for the time being and uploading them into DAWSON. This is creating additional work for court staff.

**Expected Behavior**

Paragraph indentations should be representative of what is typed in the Order generator text area. 

**Actual Behavior**
A clear and concise description of what actually happened.

Indentations are not getting formatted as typed in the Order generator area. 

**Screenshots**
Different paragraph indentation spacing on longer orders.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/a10c585f-3f0b-42e4-9326-363bdcb271c4)

Different paragraph indentation spacing + you can see the difference from the one generated outside of DAWSON on the left vs the DAWSON generated one on the right
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/c2d3880c-1141-49d8-9572-6130b38b2240)

This is what happened after I copy/pasted from DAWSON into notepad, then copied that into DAWSON order generator, and then formatted. Notice 3 indentation levels on this example:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cbc204fa-5685-487e-8f61-38819b543219)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by cholly75** [comment]
Update: it looks like the the inconsistent behavior is at least partially a result of the justification implemented with orders to conform to the new Court style guide.

**Comment by rosiehsmith** [comment]
@shumway-tm caught that in [9340](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9340) especially, you can see the impact of justification on the last paragraph. we tried an experiment to update the generated order's `#order-content`'s text-align to left instead, and the spacing at the beginning of the paragraphs looks equal.

**Comment by cholly75** [comment]
**NOTE**: We have approval from the court to remove the right justification on the style if that solves the indentation problem.

**Comment by cholly75** [comment]
Copy/Paste symptom has been offloaded to ustaxcourt/ef-cms#8333
