### ISSUE TITLE
Court: Remove New Trial Session View from Judge/Chamber Roles

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8338]
As a judge or chambers associate, so that I only see trial sessions that have been calendared, I need to only see the Open, Closed, and All views on the Trial Session screen.

The calendaring process can take days or weeks as trial sessions are created, edited, rescheduled, and rearranged based on feedback and judge preference and clerk availability. During this time, trial sessions in the New view are often created, changed, or deleted as the process completes. This leads to unnecessary assumptions and a high degree of "churn" from judges and CAs who misinterpret the significance and purpose of trial sessions displayed on this view.

As these working sessions are not relevant until they become calendared, the court would like to remove the New view from users with Judge or Chambers roles.

## Acceptance Criteria
* Users with a Judge or Chambers role can only access the Open, Closed, or All views on the Trial Session screen.
* Default view for Judge/Chambers roles should be the Open view
* All other roles can still access the New view as normal

## Test Cases
* Log in as judge, navigate to Trial Sessions screen. Only the Open, Closed, and All views are displayed
* Log in as CA, navigate to the Trial Sessions screen. Only the Open, Closed, and All views are displayed
* Log in as Petitions/Docket/General user, navigate to the Trial Sessions screen. New, Open, Closed, All views are displayed.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
## Test Cases

#### 1) As a Judge, when viewing the Trial Sessions screen, only the Open, Closed, and All views are displayed 
- Log in as a Judge
- Click on Trial Sessions
Expected Results
- [x] Open, Closed, and All views are displayed
- [x] New View is not displayed for Judge User
- [x] Default view is the Open tab 

Click on the All Tab
Expected Results:
- [x] Judge user can still see trial sessions that are in the New Status on this page

#### 2) As a Chambers Administrator user, when viewing the Trial Sessions screen, only the Open, Closed, and All views are displayed
- Log in as a Chambers User
- Click on Trial Sessions
Expected Results
- [x] Open, Closed, and All views are displayed
- [x] New View is not displayed for Chambers User
- [x] Default view is the Open tab 

Click on the All Tab
Expected Results:
- [x] Chambers user can still see trial sessions that are in the New Status on this page

#### 3) As Petitions/Docket/General court user, when viewing the Trial Sessions screen, the New, Open, Closed, and All views are displayed.
- Log in as various Court Users (Docket clerk, Petitions clerk, ADC, Admissions, etc.)
- Click on Trial Sessions
Expected Results
- [x] New, Open, Closed, and All views are displayed
