### ISSUE TITLE
Consolidation: Identify Lead Case in UI

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8341]
As as DAWSON user, so that I can accurately make filings in the lead case in a consolidated group, I need to be able to easily identify which case is the lead case.

Sometimes petitioners with multiple separate cases before the Court will have those cases consolidated into a single group for purposes of adjudication. When this happens, those cases are considered a consolidated group.

When a consolidated group (CG) is created, one case in particular is designated as the "lead" case. This is always the case with the lowest docket number in the group and is considered the primary case in which docket entries must be created/filed. Currently to identify the lead case in a CG the user must navigate to the Case Information tab to determine the lead case in the group. To make this more user-friendly and to facilitate further improvements in the area of consolidation, we want the "lead" designation for a lead case to be signified somehow on the case header portion of the screen. 

## Acceptance Criteria
* Lead case in a consolidated group indicates that it is the lead case in the header portion of the case screen.
* When the lead case in a consolidated group changes due to modification to the consolidated group, the lead case indicator appears on the new lead case and is removed from the prior lead case
* Lead case assignment is done automatically upon consolidation of a group of cases
* Lead case designation appears on all CGs currently in the system as well as new CGs going forward

## Notes
* See UX mockups for research/approach

## Tasks
- [x] Add icon to case detail header when case is consolidated and is the lead case - Rosie, Rachel (https://github.com/ustaxcourt/ef-cms/pull/2143)

## Test Cases
* New consolidated group of cases is formed; lead case designation displays in the case header for the lead case
* Existing consolidated group: lead case displays designation in the case header
* Existing consolidated group: consolidated group has a case added that is a lower docket number than the existing lead case; lead case designation displays in the new lead case. Lead case designation is removed from prior lead case
* Existing consolidated group: lead case is removed from the group. Lead case designation is removed from the case; lead case designation is applied to the new lead case in the group

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by swongCO** [comment]
![Docket record - Lead case.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/fe35ef80-a2a5-4090-96bc-45d04df85040)

1. Display {lead case} tag in header next to docket number
2. Use existing header tag style
3. Display {lead case} tag as the first one if there are 2+

**Comment by ttlenard** [comment]
## Test Cases

#### 1) New consolidated group of cases is formed; lead case designation displays in the case header for the lead case
- Log in as a Docket Clerk
- The easiest way to ensure that you are selecting cases that can be consolidated (same requested place of trial, same proceeding type, etc) for testing purposes, is to do the following:
- Click on Trial Sessions
- Click on the New Tab
- Pick an upcoming trial session by clicking on the City, State URL
- Write down a few docket numbers from the eligible case list (ensuring that the cases are the same proceeding type (all small, all regular, all Lein/Levy, etc.)
- Click on the docket number of one of the cases
- Click on the Case information tab
- Click add cases button in the "Consolidated Cases" tile.
- Type in the docket numbers of the cases  you wrote down in the previous steps, and click Search 
- Check the box next to the docket number and click "Consolidate Cases"
- Right click on the each of the docket number links from the Consolidated Cases tile, and open the cases in a new tab

Expected results:
- [x] The lowest docket number will have the lead case designation in the header of the case. Placement should be next to the docket number.
- [x] The other cases that are in the Consolidated group do not have the lead case designation in the header of the case

#### 2) Existing consolidated group: lead case displays designation in the case header
- Log in as a docket clerk
- Navigate to the lowest docket number of an existing consolidated case group (I used 24929-17)
Expected Results
- [x] The lead case designation will be in the header of this case
- [x] When clicking on other cases that are in this consolidated group, none of the other cases have the lead case designation in the header.

#### 3) Existing consolidated group: consolidated group has a case added that is a lower docket number than the existing lead case; lead case designation displays in the new lead case. Lead case designation is removed from prior lead case
- Log in as a docket clerk
- Navigate to the lowest docket number of an existing consolidated case group (I used 24929-17 **- OR GET ANOTHER EXAMPLE FROM DEBORAH**)
- Click on the Case information tab
- On the Consolidated Cases tile, add in a lower docket number to the consolidated group
Expected Results
- [x] The lead case designation will no longer be in the header of the previous lead case
- [x] When clicking on the case that you just added to the consolidated group, the lead case designation is now indicated on this case.
- [x] When clicking on the other cases that are in this consolidated group, none of the other cases have the lead case designation in the header.


#### 4) Existing consolidated group: lead case is removed from the group. Lead case designation is removed from the case; lead case designation is applied to the new lead case in the group
- Log in as a docket clerk
- Navigate to the lowest docket number of an existing consolidated case group (I used 24929-17 **- OR GET ANOTHER EXAMPLE FROM DEBORAH**)
- Click on the Case information tab
- On the Consolidated Cases tile, click on the remove cases link
- Check the box next to the lowest docket number to remove the lowest docket number from the consolidated group (Take note of the docket number of the next lowest case - you will need this docket number later)
- Click "Unconsolidate Cases button
Expected Results
- [x] The lead case designation will no longer be in the header of this case
- [x] The yellow paper icon will no longer be present in the header of this case
- [x] When navigating to the docket number that you noted in the previous steps, this case will now have the lead case designation
- [x] When clicking on the other cases that are in this consolidated group, none of the other cases have the lead case designation in the header.

**Comment by rachelschneiderman** [comment]
While implementing this functionality, we weren't sure if the tag should show only for internal users or for both internal and external users. Waiting for PO to return from OOO to confirm which users should be able to see the tag.

**Comment by rosiehsmith** [comment]
Dev review completed by @mrinsin ✅

**Comment by rosiehsmith** [comment]
UX Feedback to address:
- Expand the width of the case detail header portion that contains the docket number and tags so that they don't wrap to the next line as much
- If tags do end up wrapping, add some vertical space between the lines
- Case title to match the width of the docket number/tags section

This might look like: 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/16403861/167173341-75419cff-226b-4338-8dca-a4cf6d89fcb4.png">
