### ISSUE TITLE
BUG: Consolidated Case List Disappears From Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8342]
**Describe the Bug**
On a consolidated case, when a function is invoked from the Case Information screen such as Editing the case status/caption, sealing or unsealing a case, adding it to a trial, marking it high priority, or adding a manual block, the list of cases displayed in the Consolidated Cases portion of the screen disappears. 

They only display again if the browser page is refreshed or the case is re-navigated to.

**Business Impact/Reason for Severity**
Confusing behavior while working a case in a consolidated group.

**In which environment did you see this bug?**
PROD, TEST

**Who were you logged in as?**
Petitions clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to the Case Information tab for a case in a consolidated group.
2. Note the list of cases in the consolidated group displayed in the Consolidated Cases section of the screen.
3. Click "Mark High Priority" in the Trial section of the screen. Complete the UI for marking a case as high priority.
4. Consolidated cases in the list disappear from view
5. Refresh your screen, and the consolidated cases will re-appear.
6. Note: The same behavior occurs if you edit the case status or caption, seal or unseal a case, add it to a trial, or add a manual block.

**Expected Behavior**
The list of cases in the consolidated group still displays on the screen.

**Actual Behavior**
The list of cases in the consolidate group disappears. 

**Screenshots**
BEFORE:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/87700f3f-ed60-43cf-8d89-cd60979d6143)

AFTER:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/cee7f6c6-b2a2-4157-9633-0fca8efa5073)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
Note: I added one more test scenario in the bug above.  Editing the Case Status/Caption also causes the Consolidated case list to disappear from view.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/44dd6c36-f38c-49b3-bdd9-97e57728c033)

**Comment by ttlenard** [comment]
Retested and now if you edit the case caption or status the consolidated case list remains. Thanks for addressing that!
