### ISSUE TITLE
Modify Filed Date on Auto-Generated Orders

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8343]
As a petitioner, so that orders issued to me pursuant to my petition accurately reflect the docket record, I need the automatically generated Order to Show Cause (OSCP), Order for Amended Petition (OAP), Order Designating Place for Trial (ODT), and Order for Amended Petition and Filing Fee (O) to represent the Filed Date of the petition rather than the Served Date.

Originally when developed, the templates for these auto-generated documents represented the petition served date as the value for the FILED_DATE token; this was by design, as the Court was working through an enormous backlog of petitions that had yet to be filed. Now that we've mostly caught up to the backlog, we want the FILED_DATE token to actually represent the true filed date of the petition as listed on the Docket Record to avoid confusion or potential misrepresentation issues.

## Acceptance Criteria
* Auto-generated OSCP inserts the Filed date of the petition in the FILED_DATE token when generating.
* Auto-generated OAP inserts the Filed date of the petition in the FILED_DATE token when generating.
* Auto-generated ODT inserts the Filed date of the petition in the FILED_DATE token when generating.
* Auto-generated Order for Amended Petition and Filing Fee inserts the Filed date of the petition in the FILED_DATE token when generating. 

## Notes
Original story references:
OSCP: ustaxcourt/ef-cms#8163
OAP: ustaxcourt/ef-cms#8164
ODT: ustaxcourt/ef-cms#8088
O: ustaxcourt/ef-cms#8165

## Test Cases
* File a petition; serve the petition on a different day than the filed date. Auto-generate the OSCP, OAP, ODT, and Order for Amended Petition and Filing Fee; the filed date referenced in the preamble on these orders reflects the filed date of the petition; the due by date on these orders continues to reflect the order creation date + 60.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
## Test Cases

#### 1) File a petition; serve the petition on a different day than the filed date. Auto-generate the OSCP, OAP, ODT, and Order for Amended Petition and Filing Fee; the filed date referenced in the preamble on these orders reflects the filed date of the petition; the due by date on these orders continues to reflect the order creation date + 60.

- Log in as a petitions clerk
- Click on Document QC
- Click on "Start a Petition"
- Upload a Petition
- Fill out the fields on the party tab
- On the Case info tab, fill in the required fields and be sure that the following are selected:
     - Order to show cause
     - Order for Amended Petition
     - Order Designating place of trial
     - Order for Amended Petition and Filing Fee
- On the IRS notice tab, select no, and Deficiency
- Click Create Case
- Click Serve to IRS
- Click done on the Print for paper service screen
- Click on the Served tab
- Click on the docket number of the case you just created
- Click on the Drafts tab and review the dates in the Orders

Expected Results
- [ ] The file date on the draft Order to show cause reflects the filed date of the petition; the due by date continues to reflect the order creation date + 60.
- [ ] The file date on the draft Order for Amended Petition reflects the filed date of the petition; the due by date continues to reflect the order creation date + 60.
- [ ] The file date on the draft Order Designating place of trial reflects the filed date of the petition; the due by date continues to reflect the order creation date + 60.
- [ ] The file date on the draft Order for Amended Petition and Filing Fee reflects the filed date of the petition; the due by date continues to reflect the order creation date + 60.

**Comment by cholly75** [comment]
Obviated w/ ustaxcourt/ef-cms#8165 where this was applied across all AG forms.
