### ISSUE TITLE
Add Filtering to ADC Section Messages

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8344]
As a ADC user, so that I can prioritize and understand the work that needs to be done by our section, I need to be able to filter the Section displayed messages.

The ADC section is facing a large backlog of work that needs to be addressed. Operationally so that a more targeted view of messages that need responding to can be addressed, we want to be able to filter the Section Messages for specific values.

We expect to extend this functionality to other Section messages in the near future.

## Pre-Conditions
ustaxcourt/ef-cms#8346

## Acceptance Criteria
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the Case Status field
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the To field
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the From field
* ADC Section messages Inbox and Sent display can be filtered for a specific value present in the Section field
* ADC Section messages Completed display can be filtered for a specific value present in the Completed By field
* ADC Section messages Completed display can be filtered for a specific value present in the Section field
* Filter selections refresh the list of displayed messages according to the selected filters immediately upon selection
* Multiple filters can be selected concurrently
* Filters can be cleared
* Filters are available on each view (Inbox, Sent, Completed)
* Filters can be applied in conjunction with sorting criteria

## Test Cases
* Section displays all messages; filter selection is made for To field; displays only messages with the corresponding value in the To field
* Section displays all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field
* Section displays all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field
* Section displays all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field
* Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately
* Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages
* Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to the Court's `test` environment for PO Review

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Section displays all messages; filter selection is made for To field; displays only messages with the corresponding value in the To field
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox and Sent tabs
- Click on the "To" filter and make a selection

Expected Results
- [x] The Inbox/Sent tabs are now filtered and only display messages with the corresponding value in the "To" field.
- [ ] The message count of Inbox/Sent has updated to reflect the number of messages that are in the tab associated with the "To" value.


#### 2) Section displays all messages; filter selection is made for From field; displays only messages with the corresponding value in the From field
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox and Sent tabs
- Click on the "From" filter and make a selection

Expected Results
- [ ] The Inbox/Sent tabs are now filtered and only display messages with the corresponding value in the "From" field.
- [ ] The message count of Inbox/Sent tabs has updated to reflect the number of messages that are in the tab associated with the "From" value.

#### 3) Section displays all messages; filter selection is made for Case Status field; displays only messages with the corresponding value in the Case Status field
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox and Sent tabs
- Click on the "Case Status" filter and make a selection

Expected Results
- [ ] The Inbox/Sent tabs are now filtered and only display messages with the corresponding value in the "Case Status" field.
- [ ] The message count of Inbox/Sent has updated to reflect the number of messages that are in the tab associated with the "Case Status" value.

#### 4) Section displays all messages; filter selection is made for Section field; displays only messages with the corresponding value in the Section field
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox, Sent, and Completed tabs 
- Click on the "Section" filter and make a selection

Expected Results
- [ ] The Inbox/Sent/Completed tabs are now filtered and only display messages with the corresponding value in the "Section" field.
- [ ] The message count of Inbox/Sent/Completed has updated to reflect the number of messages that are in the tab associated with the "Section" value.

#### 5) Filter is applied; display updates appropriately; filter value is changed to a different value; display updates again appropriately
- Continuing from Test Case 4
- Be sure that you run this test with the Inbox, Sent, and Completed tabs 
- Change the selection you had in the Section Filter to a new selection (Spot check doing this same test with all the other filters)

Expected Results
- [ ] The Inbox/Sent/Completed tabs are now filtered and only display messages with the new corresponding value in the "Section" field (or other filter applied).
- [ ] The message count of Inbox/Sent/Completed has updated to reflect the number of messages that are in the tab associated with the newly selected "Section" value (or other filter applied)


#### 6) Section displays all messages; filter selection is made for Completed By field; displays only messages with the corresponding value in the Completed By field
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Completed tab 
- Click on the "Completed By" filter and make a selection

Expected Results
- [ ] The Completed tab is now filtered and only displays messages with the corresponding value in the "Completed By" field.
- [ ] The message count of Completed tab has updated to reflect the number of messages that are in the tab associated with the "Completed By" value.

#### 7) Filter is applied; display updates appropriately; filter value is cleared; display updates again to display all messages
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox, Sent, and Completed tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection
- Click on the "Completed by" filter and make a selection
- Clear the filters (set them back to the default)

Expected Results
- [ ] The Inbox/Sent/Completed tabs are no longer filtered and display all messages with no filters on
- [ ] The message count of Inbox/Sent/Completed has updated to reflect the total number of messages that are in the tab


#### 8) Filter is applied; display updates appropriately; additional filter(s) applied; display updates appropriately with each filter selection
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox, Sent, and Completed tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection
- Click on the "Completed by" filter and make a selection

Expected Results
- [ ] The Inbox/Sent/Completed tabs are now filtered and only display messages with the corresponding values based off of the filtered values.
- [ ] The message count of Inbox/Sent/Completed has updated to reflect the number of messages that are in the tab associated with the filtered value.


#### 9) Filter is applied, display updates appropriately; sort the filtered column to arrange results in descending order
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox, Sent, and Completed tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the caret on the Docket Number header to Sort the results in descending order

Expected Results:
- [ ] Columns are filtered appropriately and sorted in descending order

**Repeat the steps above with these columns.**
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection
- Click on the "Completed by" filter and make a selection

**Repeat this test by sorting additional columns (column header varies by tab)**
- Received/Sent/Completed column
- Message Subject/Last Message

#### 10) Filter is applied, display updates appropriately; sort the filtered column to arrange results in ascending order
- Log in as an ADC
- Click on "Switch to Section Messages" URL
- Be sure that you run this test with the Inbox, Sent, and Completed tabs (note: some filters will not be present on ALL tabs)
- Click on the "To" filter and make a selection
- Click on the caret on the Docket Number header to Sort the results in ascending order

Expected Results:
- [ ] Columns are filtered appropriately and sorted in ascending order

**Repeat the steps above with these columns.**
- Click on the "From" filter and make a selection
- Click on the "Case Status" filter and make a selection
- Click on the "Section" filter and make a selection
- Click on the "Completed by" filter and make a selection

**Repeat this test by sorting additional columns (column header varies by tab)**
- Received/Sent/Completed column
- Message Subject/Last Message

**Comment by swongCO** [comment]
![Section Messages - Inbox.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/61be0120-e0d0-41d3-b80a-b58f939a4e1e)
![Section Messages - Sent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/09ab07f7-26b8-48ea-85cc-c1fab0c73cb2)
![Section Messages - Completed.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/45514db8-8660-4c14-8863-956fb306708e)

- Use existing design and interaction for filter components
- Inbox and Sent filters: Case Status, To, From, Section
- Completed filters: Completed By, Section
–––––
![Section Messages - Inbox selected filter.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/107d2ca1-593e-4d29-9d7b-dcceb7562518)

- Selected filter will have a blue border (same color as hover state) and persist until cleared
- The up/down icon changes to "x" when a filter is selected
- Clicking 'x' will reset the filter to the default

**Comment by cholly75** [comment]
Removed AC: "* Message count is updated when filters are applied" - will address message count across application filtered pages together in a separate story

**Comment by codyseibert** [comment]
@cholly75 also made a comment to not display the section on the completed queue since everything in the completed queue will always be the same section
