### ISSUE TITLE
BUG: Docket record filter by dropdown is not displaying for external mobile users

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8349]
**Describe the Bug**
When viewing the docket record on a mobile device, the `filter by` dropdown does not appear.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
Petitioner, Public, Practitioners

**To Reproduce**
Parties
1. Log in to DAWSON as a petitioner (be sure you are a party on a case) on a mobile device
2. Go to any case that the petitioner is a party to

Public
1. Navigate to public DAWSON site a mobile device
2. Go to any case

**Expected Behavior**
The `filter by` drop down should display for external users when viewing on a mobile device.

**Actual Behavior**
The `filter by` drop down does not display for external users when viewing on a mobile device.

**Screenshots**
![image](https://user-images.githubusercontent.com/87717140/198285493-ce71485f-d304-4669-80c3-cce62d0c1ba2.png)

When you start to minimize the screen, the Filter by drop down starts to move around. Is this how it would look on a tablet?
![image](https://user-images.githubusercontent.com/87717140/198285779-b96a2adb-dcbb-472e-83de-188d1577abe8.png)

**Cause of Bug, If Known**

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by swongCO** [comment]
### Mockups of Filter by dropdowns
**Tablet:**
Parties
• include min widths for dropdowns to accomodate long text (see 2nd screenshot, first dropdown)
![Tablet - Party view.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7243de55-778c-4b6d-b3b3-aa71e36c201e)

![Tablet - Party view 2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/300b4da9-11fb-46f8-8164-01ac81680877)

Public
![Tablet - Public view.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/019d57f8-18f1-4868-a830-5ce4a11a4c87)

______________________

**Phone:**
Parties
![Phone - Party view.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e494db85-0665-49ab-87fe-209752487c02)

Public
![Phone - Public view.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/b804033f-aac3-4ec6-937f-f4a520dc9b0d)

**Comment by rachelschneiderman** [comment]
The `Filter by` drop down was introduced into DAWSON via these two stories: ustaxcourt/ef-cms#8226 and ustaxcourt/ef-cms#8259.

**Comment by rachelschneiderman** [comment]
This bug was created from https://github.com/flexion/ef-cms/issues/9683 in order to split out the reported issues into narrower slices.

**Comment by rosiehsmith** [comment]
Blocked for now since we're waiting on updated wireframes to match the original look of the sort dropdown as well as reducing margin above the "Printable Docket Record" button.

**Comment by swongCO** [comment]
Updated mockups for this and 9775 in consideration of original story 3288.

**Comment by rachelschneiderman** [comment]
[PR to test](https://github.com/ustaxcourt/ef-cms/pull/2993)
