### ISSUE TITLE
Long Text Display Mockups for Session Notes on Session Copy Page

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8357]
As a session copy viewer, so that I can decide which method I'd like to use to display long text in the Session Notes field, I need mockups of potential solutions.

This is a tracking story for UX to reflect work done to create mockups of potential solutions for modifying the session notes on the session copy page to display more text than can be currently shown; these mockups will be used to socialize this concept and determine whether there is a need for a solution.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### Options:
![Session Copy page - custom scrollbar.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d5ec13e8-b966-4a2e-9f14-d06711136c80)
![Session Copy page - see more link.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/c9bbba33-7017-4687-9739-0a8246fbdba4)
![Session Copy page 1.1.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/bf1e1d3e-c055-4e55-9fe6-6e443e25ccf9)
![Session Copy page 1.2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/9aba3421-acef-41d6-a0b6-dc0672086875)
![Session Copy page 2.1.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/428ce73f-e67f-4f07-a65b-a6d1bb407c98)
![Session Copy page 2.2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1df591bf-8f28-491c-816f-a4ec07d425ec)
![Session Copy page 2.3.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/b879f256-7392-4867-b727-7fe51cb24c2f)
