### ISSUE TITLE
Clerk of the Court: Enable Stamp Disposition

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8358]
As a Clerk of the Court section user, so that I can use the stamp disposition feature when necessary, I need the stamp order functionality enabled and visible to me.

Sometimes a particularly complex or sensitive issue is referred to the Clerk of the Court (CotC) section for disposition. In these cases, it would be beneficial for those CotC users to have the ability to stamp grant/deny motions using the existing stamp disposition functionality. Any user that is a member of the CotC section should have the same stamp disposition functionality currently available to ADC users, with the signatory judge being the Chief Judge.

## Acceptance Criteria
* When viewing a motion in the Document View, a CotC user can see and click the Apply Stamp link to invoke the stamp disposition workflow
* Stamp disposition workflow behaves the same in all respects for CotC users as other users
* Stamp created by CotC user displays signature of the Chief Judge  

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [x] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

Notes
- _Test cases 1-10 test Stamp Order functionality via the Message workflow._
- _Test cases 13-15 test Stamp Order functionality via the Document Preview workflow._
- _Test cases 16-17 test Stamp Order Search and public terminal user functionality_
- _Test cases 18-19 regression test to ensure previous stamp functionality remain_

#### 1) Motion is filed by a party; Docket clerk QC's motion; sends message with the motion attached to Clerk of the Court; Clerk of the Court user reviews message; Apply Stamp button is available on the document preview from the message thread.

This test case will take some set up
- Log in to DAWSON as a Party on a case (could be petitioner, Private Practitioner, or IRS Practitioner). 
- File a document in a case
- For the document type, select any type of Motion, and then click continue.
- Upload the document, fill in the required fields, and Submit your filing
- Next, log in as a docket clerk.
- Navigate to the case you just submitted the motion in.
- Click on the document link to QC the Motion.
- Click "Complete QC", and then click "Complete and Send Message"
- Select Clerk of the Court/test clerkofcourt1, add in a test message, and click Send.

Now the test is ready
- Log in as test clerkofcourt1
- Click on the new message from Docket re: the motion you submitted (it should be the first message in Recent Messages on your dashboard).

Expected Results
- [x] **NEW FUNCTIONALITY** - The apply stamp button is available on the document preview from the Message/Attachments page.



#### 2) Clerk of the Court User applies stamp on a motion from a message attachment; Clerk of the Court User is presented with the Apply Stamp Page.

- Continuing from the previous test
- Click on the "Apply Stamp" button

Expected Results
- [x] **NEW FUNCTIONALITY** - The new Apply Stamp page is available to the user




#### 3) Clerk of the Court User begins to fill out stamp information on the apply stamp page, Selects the "Back" link; information on the apply stamp page is essentially cancelled, and not saved; User is routed back to their message view.

- Continuing from the previous test
- Begin to select some of the fields/add some additional order text
- Click on the link "Back" link on the top left of the "Apply Stamp" screen

Expected Results
- [x] **NEW FUNCTIONALITY** - The user is directed back to the Message attachments page, where they can see the "Apply Stamp" button on the document preview.




#### 4) Clerk of the Court User fills out stamp information on the apply stamp page, rules for each field follow AC from Original Stamp story (#9479)

- Continuing from the previous test
- Click on the "Apply Stamp" button
- On the "Apply Stamp" Page, Add in some Stamp details. 
- Check the functionality of each of the radio buttons, additional order text field, and the Stamp Preview

Expected Results:
- [x] Save Stamp Order button at the top of the page does not "activate" unless Granted or Denied is selected.
- [x] The radio button for "This case is stricken from the trial session" is optional, and can be selected/unselected'
- [x] You can select/deselect any of the radio buttons underneath the Select any that apply section.
- [x] You can enter a date for today or in the future by either typing in a date, or selecting a date from a date picker
- [x] You can NOT enter a date in the past by either typing in a date, or selecting a date from a date picker (or if you can enter a date in the past, a validation error appears)
- [x] Custom order text box allows for 60 characters only
- [x] All information that is entered/selected in the Stamp input area is dynamically able to be previewed in the "Stamp Preview" box, and includes the Chief Judge Signature.




#### 5) Clerk of the Court User clicks the "Save Stamp Order"; Order is saved to the drafts folder of the case 

- Continuing from the previous test
- Add in the Stamp Order Details 
- Click the button to "Save Stamp Order"


- [x] The signed stamp order is available in the Drafts folder (you should see the number icon indicating a new draft)
- [x] The title/description of the draft Stamp Order should include all data selected/entered from the Stamp Order area



#### 6) Clerk of the Court user clicks the "Delete" button on the Drafts Screen, Modal pops up asking the user to confirm the deletion of the Stamp Order, User selects "No, Take Me Back"

- Continuing from the previous test, View the stamp order from the drafts folder
- Click the Delete Button

Expected Results
- [x] A Modal will pop up asking you to confirm "Are you sure you want to delete this document? Once deleted, it cant be restored."

- Select "No, Take me back"

Expected Results
- [x] The User is navigated back to the drafts page where they can preview the document, have the option to delete, Add Docket Entry, or View PDF.



#### 7) clerk of the Court user clicks the "Delete" button on the Drafts Screen, Modal pops up asking the user to confirm the deletion of the Stamp Order, User selects "Yes, Delete"

- Continuing from the previous test
- Click the Delete Button

Expected Results
- [x] A Modal will pop up asking you to confirm that you "Are you sure you want to delete this document? Once deleted, it can't be restored.."

- Select "Yes, Delete"

Expected Results:
- [x] The Stamp Order is deleted
- [x] User sees the "Apply Stamp" button on the original Motion from the message attachment.



#### 8) Clerk of the Court user Creates a Stamp Order on a Motion, Applies Stamp, Saves Stamp Order; User can attach the draft stamp order to a Message Thread

- Continuing from the previous test
- Click the "Apply Stamp" button on the Original Motion from the Message Attachment
- Add in the Stamp Order details
- Click Apply Stamp
- Click Save Stamp Order
- Navigate back to the message, click reply


Expected Results:
- [x] The Message Modal has the draft Stamp Order attached



#### 9) Clerk of the Court User Sends Message to Docket; Docket Adds Stamp Order to the Docket Record

- Continuing from the previous test
- Send the message with the draft Stamp Order to Docket
- Log in as a Docket Clerk
- Navigate to the message
- Click "Add Docket Entry"

Expected Results
- [x] Description field is populated with the title of the motion followed by the text of the Stamp options selected
- [x] Description field can be edited by the docket clerk


#### 10) Docket Clerk Adds the Stamp Order to the Docket Record

- Continuing from the previous test
- Docket Clerk clicks "Save and Serve"
- Docket clerk clicks "Yes, Serve"

Expected Results
- [x] The docket entry has event code "O"
- [x] The Filings and Proceedings Column displays the type of motion along with the text of the entire Stamp Order
- [x] The docket entry is hyperlinked
- [x] The docket entry is served to all parties in the usual manner, ex: if the parties have paper service, the print paper service page is presented.



#### 11) Motion is filed by a party; Docket clerk QC's motion; Clerk of the Court user reviews docket record, Clicks on Document View of the Motion; Apply Stamp button is available on the document preview screen.

This test case will take some set up
- Log in to DAWSON as a Party on a case (could be petitioner, Private Practitioner, or IRS Practitioner). 
- File a document on a case
- For the document type, select any type of Motion, and then click continue.
- Upload the document, fill in the required fields, and submit the filing
- Next, log in as a docket clerk.
- Navigate to the case you just submitted the motion in.
- Click on the document link to QC the Motion.
- Click "Complete QC"

Now the test is ready
- Log in as test clerkofcourt1
- Navigate to the QC'd Motion from above.
- Click on the document link to get to the Document View

Expected Results
- [x] **NEW FUNCTIONALITY** - The apply stamp button is available on the Document View page



#### 12) Clerk of the court User clicks apply stamp on a motion from the document view; Clerk of the Court User is presented with the Apply Stamp Page.

- Continuing from the previous test
- Click on the "Apply Stamp" button

Expected Results
- [x] **NEW FUNCTIONALITY** - The new Apply Stamp page is available to the user



#### 13) Clerk of the Court User begins to fill out stamp information on the apply stamp page, Selects the "Back" link; information on the apply stamp page is essentially cancelled, and not saved; User is routed back to the Document view page.

- Continuing from the previous test
- Begin to select some of the fields/add some additional order text
- Click on the "Back" link on the top left of the "Apply Stamp" screen

Expected Results
- [x] **NEW FUNCTIONALITY** - The user is directed back to the Document View page, where they can see the "Apply Stamp" button on the document preview.



#### 14) Clerk of the Court User fills out stamp information on the apply stamp page, rules for each field follow AC from Original Stamp story (#9479)

- Continuing from the previous test
- Click on the "Apply Stamp" button
- On the "Apply Stamp" Page, Add in some Stamp details. 
- Check the functionality of each of the radio buttons, additional order text field, and the Stamp Preview

Expected Results:
- [x] Apply Stamp button at the bottom of the page does not "activate" unless Granted or Denied is selected.
- [x] The radio button for "This case is stricken from the trial session" is optional, and can be selected/unselected'
- [x] You can select/deselect any of the radio buttons underneath Select Any that Apply section.
- [x] You can enter a date for today or in the future by either typing in a date, or selecting a date from a date picker
- [x] You can NOT enter a date in the past by either typing in a date, or selecting a date from a date picker (or if you can enter a date in the past, a validation error appears)
- [x] Custom order text box allows for 60 characters only
- [x] All information that is entered/selected in the Stamp input area is dynamically able to be previewed in the "Stamp Preview" box, and includes the Chief Judge Signature.



#### 15) Clerk of the Court User clicks the "Save Stamp Order"; Order is saved to the drafts folder of the case. 

- Continuing from the previous test
- Add in the Stamp Order details
- Click the button to "Save Stamp Order"

Expected Results:
- [x] The signed stamp order is available in the Drafts folder (you should see the number icon indicating a new draft)
- [x] The title/description of the draft stamp order should include all inputs selected from the Stamp Order Details



#### 16) Regression test searching for these Stamp Orders using the Order Search page
- Perform an Order Search as a logged in Court user

Expected Results
- [x] Stamp Order (sealed and unsealed) returned in results when searching by Judge
- [x] Stamp Order (sealed and unsealed) returned when searching by date
- [x] Stamp Order (sealed and unsealed) returned when searching Case title/petitioner name
- [x] Stamp Order (sealed and unsealed) returned when searching by docket number
- [x] Stamp Order (sealed and unsealed) returned when searching by keyword or phrase (example: Denied or Granted)

- Perform an Order Search as a party to a case (IRS, Private Practitioner)

Expected Results
- [x] Stamp Order (sealed to the public and unsealed) returned in results when searching by Judge
- [x] Stamp Order (sealed to the public and unsealed) returned when searching by date
- [x] Stamp Order (sealed to the public and unsealed) returned when searching Case title/petitioner name
- [x] Stamp Order (sealed to the public and unsealed) returned when searching by docket number
- [x] Stamp Order (sealed to the public and unsealed) returned when searching by keyword or phrase (example: Denied or Granted)


- Perform an Order Search as a non-logged in user

Expected Results
- [x] Stamp Order (sealed) is not returned in results when searching by Judge
- [x] Stamp Order (unsealed) returned when searching by date
- [x] Stamp Order (unsealed) returned when searching Case title/petitioner name
- [x] Stamp Order (unsealed) returned when searching by docket number
- [x] Stamp Order (unsealed) returned when searching by keyword or phrase (example: Denied or Granted)

- Perform an Order Search as a user on the Public Terminal 

- [x] Stamp Order (sealed) is not returned in results when searching by Judge
- [x] Stamp Order (unsealed) returned when searching by date
- [x] Stamp Order (unsealed) returned when searching Case title/petitioner name
- [x] Stamp Order (unsealed) returned when searching by docket number
- [x] Stamp Order (unsealed) returned when searching by keyword or phrase (example: Denied or Granted)


#### 17) Regression test - Public Terminal User can open and view Stamp Orders that on the Docket Record
- Log in as the public terminal user
- Navigate to a case that has a stamp order (Sealed and Unsealed)

Expected Results
- [x] Can open and view Stamp Orders that are not sealed
- [x] Sealed stamp order is visible on the docket record, but there isn't a link top open it


#### 18) Regression test - Judge, ADC, and Chambers can still apply stamps per the usual manner from story ustaxcourt/ef-cms#8336.


#### 19 Regression test - Be sure that Clerk of the Court user, Judge, ADC, and Chambers can also stamp withdrawal motions as outlined in story ustaxcourt/ef-cms#8243
