### ISSUE TITLE
Prevent Logout When Viewing Trial Sessions Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8380]
As a DAWSON user, so that I do not get logged out upon attempting to view the Trial Sessions screen, I need the Trial Sessions screen to better manage the data returned in its query.

This is a companion story to ustaxcourt/ef-cms#8379 - the accumulated volume of Trial Session data reached a point where attempting to access a page  that queries for that data (the Trial Sessions screen) causes an immediate logout for the user due to the size of the data returned in the query used by the page.

We need a way to mitigate this so that the data on the Trial Sessions page can be appropriately handled/displayed, either through pagination or filtering or some other method that refines the initial page load so that the user is not logged out when this condition occurs.

## Acceptance Criteria
* Users can access Trial Sessions screen without being logged out when there is a large volume of trial session data
* Users can access the appropriate views on the Trial Sessions screen to see session data

## Notes
* One option would be to limit the data displayed in these views to sessions going back 1 year and all future sessions (since we don't create more than 1 term in advance). If the user needed to go back further, give them an option to do so. 
* Another option (not necessarily mutually exclusive) would be to limit the data returned on this page to:
Start Date
Estimated End Date
Location
ID
Proceeding Type
Session Type
Judge
Status
Is Swing Session

Assuming that's the only functional data this page needs. Analysis by @mmarcotte indicates this would cut the size of the payload by ~93 percent.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by mmarcotte** [comment]
As per the Notes above, If we simply remove the caseOrder we save 87% of the payload size. This information is not used on the Trial Sessions page, and it is simply extraneous information. We should consider "data transfer objects" or simply filtering out the information that the frontend does not need.

```
{
      ...trialSession,
      irsCalendarAdministrator: undefined,
      maxCases: undefined,
      trialClerk: undefined,
      password: undefined,
      meetingId: undefined,
      chambersPhoneNumber: undefined,
      sk: undefined,
      joinPhoneNumber: undefined,
      postalCode: undefined,
      noticeIssuedDate: undefined,
      address1: undefined,
      address2: undefined,
      createdAt: undefined,
      startTime: undefined,
      entityName: undefined,
      sessionScope: undefined,
      courthouseName: undefined,
      gsi1pk: undefined,
      caseOrder: undefined,
}
```

**Comment by mmarcotte** [comment]
Another note is that these two pages also make uses of the `getTrialSessionsAction `

* create new trial session via `/add-a-trial-session`
* edit a trial session via `/edit-trial-session/<trial-session-id>`

**Comment by ttlenard** [comment]
Testing results: 12/21/2022
@codyseibert @cholly75 

Testing results are good. I had no problem accessing trial session data.  Below are the things I tested:

- Create new trial session
- QC eligible cases
- Filter Eligible case list by procedure type
- Set Calendar
- Edit existing trial session
- Chambers/Judge user can click on "View all session info" link and be directed to the session information page 
- Click each tab in a trial session (Open, Inactive, All)
- On the Trial Session tab, can filter successfully
- On the Trial Session tab, can click on each tab successfully (New, Open, Closed, All)
- Click on the docket number from a case on the Session information page - case opens appropriately
- From within a case, on the Case information tab
     - Add case to trial
     - Add calendar note
     - Edit calendar note
     - Click on the city/state link for the trial location - opens session info page appropriately
     - Remove from trial
- From within a case, on the case information tab
     - Set a case for hearing
     - add calendar note
     - edit calendar note
     - Click on the city/state link for the hearing - opens session info page appropriately
     - remove from hearing
- On the Edit trial session page, add a swing session
     - On the Session info page, click on the link and access the swing session
- JSON
     - No longer seeing the Case Order
     - No action item on this right now, but I did have some questions about how the IsClosed flag works.  All cases show IsClosed = false, with the exception of a handful of standalone remote sessions. We may want to reconsider how we use this flag in the future?
     - I see that the more appropriate Trial status field is probably "SessionStatus".

**Comment by ttlenard** [comment]
Testing Feedback from 12/29/2022
@codyseibert 

Testing results round 2 for the refactor are good. I had no problem accessing trial session data.  Below are the things I tested:

- Create new trial session
- QC eligible cases
- Filter Eligible case list by procedure type
- Set Calendar
- Edit existing trial session
- Delete Existing trial session from the new tab
- Dispose of all cases on a trial session so that it goes from open to closed.
- Chambers/Judge user can click on "View all session info" link and be directed to the session information page 
- Click each tab in a trial session (Open, Inactive, All)
- On the Trial Session tab, can filter successfully
- On the Trial Session tab, can click on each tab successfully (New, Open, Closed, All)
- Click on the docket number from a case on the Session information page - case opens appropriately
- From within a case, on the Case information tab
     - Add case to trial
     - Add calendar note
     - Edit calendar note
     - Click on the city/state link for the trial location - opens session info page appropriately
     - Remove from trial
- From within a case, on the case information tab
     - Set a case for hearing
     - add calendar note
     - edit calendar note
     - Click on the city/state link for the hearing - opens session info page appropriately
     - remove from hearing
- On the Edit trial session page, add a swing session
     - On the Session info page, click on the link and access the swing session
- JSON
     - No longer seeing the Case Order
     - No action item on this right now, but I did have some questions about how the IsClosed flag works.  All cases show IsClosed = false, with the exception of a handful of standalone remote sessions. We may want to reconsider how we use this flag in the future?
     - I see that the more appropriate Trial status field is probably "SessionStatus".
