### ISSUE TITLE
BUG: Docket record sort dropdown is not displaying label for external mobile users

### ISSUE THREAD

**Issue by rachelschneiderman** [ustaxcourt/ef-cms#8388]
**Describe the Bug**
When viewing the docket record on a mobile device, the `sort by` dropdown is not displaying properly for parties on a case.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
petitioner1@example.com

**To Reproduce**
1. Log in to DAWSON as a petitioner (be sure you are a party on a case) on a mobile device
2. Go to any case that the petitioner is a party to

**Expected Behavior**
The `sort by` drop down should display label text indicating current sort order.

**Actual Behavior**
The `sort by` drop down displays as two stacked arrows without any label text.

**Screenshots**
![image](https://user-images.githubusercontent.com/20249233/210269513-9e518a2e-c7fb-4ae4-a4f3-3efcfc81c3a0.png)

**Cause of Bug, If Known**
`formattedCaseDetail` was split as part of devex-864 20 months ago, so the property which populates the sort label's reference wasn't up-to-date.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by rachelschneiderman** [comment]
This bug was created from [this bug](https://github.com/flexion/ef-cms/issues/9683) in order to split out the reported issues into narrower slices.

**Comment by rachelschneiderman** [comment]
Sort mobile [original story](https://github.com/flexion/ef-cms/issues/3288)
Sort mobile [PR](https://github.com/flexion/ef-cms/pull/3873) that introduced mobile sort button

Based on the links above, it seems the sort button is missing the description text but is otherwise displaying as designed.

**Comment by rachelschneiderman** [comment]
[PR to test](https://github.com/ustaxcourt/ef-cms/pull/2985)

**Comment by swongCO** [comment]
@rosiehsmith found [this](https://github.com/flexion/ef-cms/pull/3873) from Dec 2019 which has the original design of the sort functionality:

![70819558-5f045300-1d8b-11ea-822f-980c4905382e.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/5ed61116-2e17-4463-baff-899ff2dc34d7)

Based on this, UX would like the original design restored.
