### ISSUE TITLE
BUG: Swing Session Icon Missing On Trial Sessions Views

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8389]
**Describe the Bug**
The chain link icon representing when a trial session is part of a swing session is no longer displaying on any of the Trial Session views. Clicking into the sessions displays the correct swing session status, however there is no indication on any of the list views that these are swing sessions. Unclear at what point this icon went missing. It used to display like this:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/b24eabaa-2c8e-43fc-8481-9d642d86af77)

**Business Impact/Reason for Severity**
User must click into individual trial sessions to determine whether it is part of a swing session

**In which environment did you see this bug?**
PROD, TEST

**Who were you logged in as?**
Docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Reported by user

**To Reproduce**
1. Go to Trial Sessions screen as any Court user
2. Navigate to Open trial sessions - look at 3/13/23 session for Chicago, IL and 3/16/23 session for Peoria, IL

**Expected Behavior**
Chain link icon displayed next to both sessions indicating status as part of a swing session

**Actual Behavior**
No icon is displayed

A clear and concise description of what actually happened.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
Testing Results 1/9/2023 - @shumway-tm @zRogersFlexion 

Swing Session icons now appear on each tab for Trial Sessions.  Thanks for fixing!

**Comment by shumway-tm** [comment]
[PR](https://github.com/ustaxcourt/ef-cms/pull/3009) to staging!
