### ISSUE TITLE
Investigate Options of Orders & Opinions Search

### ISSUE THREAD

**Issue by mark-meyer** [ustaxcourt/ef-cms#839]
Order and Opinion searches are currently offline until we can make the search more performant and offer better results. We don't currently know where the performance bottleneck(s) is and don't have an easy way to test and iterate, which is really the only way to determine the best configuration for Elasticsearch. For example, we can not say with confidence that more smaller instances holding more shards is better than the current configuration of three large nodes. If we could quickly iterate with and Elasticsearch dedicated to testing we may be able to find a solution quickly.

**Possible Path Forward**

- [x]  Create independent Elasticsearch cluster matching current production cluster
- [x]  Add index with same index settings as production including the number of shards(1) and replicas(1)
- [x]  Copy data from the migration ES cluster for the index in question
- [ ]  Add document contents from PDFs to the test index
- [ ]  Take snapshot to allow standing up this index more quickly
- [x]  Experiment with various configurations, index mappings, and queries to identify better options.

**Comment by mmarcotte** [comment]
Mike to sync with @JessicaMarine on the prioritization of Order & Opinion search
