### ISSUE TITLE
Consolidation: Add Icons to Deadlines Report

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8394]
As a Court user, so that I can quickly identify consolidated cases with pending items, I need the Deadlines report to indicate when a case is a lead or member case in a consolidated group.

This story will extend the consolidated iconography seen elsewhere in DAWSON to the items on the Deadlines Report.

## Acceptance Criteria
* Deadlines report items associated with cases that are Lead cases in a consolidated group are indicated with the "L" consolidated icon next to the docket number on the report.
* Deadlines report items associated with cases that are member cases in a consolidated group are indicated with the consolidated icon next to the docket number on the report.

## Notes
- Consolidated groups do not need to be displayed together within the Deadlines Report Table

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
Notes per UX: Add a column between Due Date and Docket Number for icons
![Screenshot 2023-03-29 at 2.02.48 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/347287a8-6655-4bb5-976f-c2b7ca759d4f)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Deadlines Report; Deadlines associated with the Lead case in the consolidated group display the Lead Case icon.

- Log in as any Court User
- Click on Reports
- Click Deadlines

Expected Results:
- [x] **NEW FUNCTIONALITY** - Deadlines associated with the Lead Cases in a Consolidated group display the Lead case icon in between the due date and the docket number.
- [x] Consolidated cases are not grouped, instead retain list order.

#### 2) Court user accesses the Deadlines Report; Deadlines associated with member cases in the consolidated group display the member Case icon.

- Continuing from the previous test

Expected Results:
- [x] **NEW FUNCTIONALITY** - Deadlines associated with the member Cases in a Consolidated group display the member case icon in between the due date and the docket number.
- [x] Consolidated cases are not grouped, instead retain list order.


#### 3) Court user filters the Deadlines report by different dates, and by different Judges; Consolidated case icons display appropriately.

- Log in as any Court user.
- Input start/end dates and click Show deadlines
- Filter by Judge

Expected Results:
- [x] **NEW FUNCTIONALITY** - Deadlines associated with the Lead Cases in a Consolidated group display the Lead case icon in between the due date and the docket number.
- [x] **NEW FUNCTIONALITY** - Deadlines associated with the member Cases in a Consolidated group display the member case icon in between the due date and the docket number.
- [x] Consolidated cases are not grouped, instead retain list order.
- [x] After changing the dates, consolidated case icons still display appropriately
- [x] After filtering by different judges, consolidated case icons still display appropriately



#### 4) Repeat the above tests with different Court users to ensure functionality is the same regardless of Court User Role.

- [x] Test cases 1-3 pass with different Court Roles.
