### ISSUE TITLE
Consolidation: Add Icons to Case Inventory Report

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8395]
As a Court user, so that I can quickly identify consolidated cases, I need the Case Inventory Report to indicate when a case is a lead or member case in a consolidated group.

This story will extend the consolidated iconography seen elsewhere in DAWSON to the items on the Case Inventory Report.

## Acceptance Criteria
* Case Inventory Report cases that are Lead cases in a consolidated group are indicated with the "L" consolidated icon next to the docket number on the report.
* Case Inventory Report cases that are member cases in a consolidated group are indicated with the consolidated icon next to the docket number on the report.
* Case Inventory Report cases that are Lead cases in a consolidated group are indicated with the "L" consolidated icon next to the docket number on the printable version of the report.
* Case Inventory Report cases that are member cases in a consolidated group are indicated with the consolidated icon next to the docket number on the printable version of the report.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- Will all cases for a consolidated group appear in the report?  Maybe
- Do all consolidated cases need to show up next to one another in a group? (This will change how its sorting which is currently by 'date' (docket number) No
- How does knowing the case is consolidated change their workflow? Provides context

**Comment by katiecissell** [comment]
UX Notes:
Follow the existing patterns set by the other reports.

Example shown in the Pending report:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBai9qIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7823807b238c7bdc4198e5a7f5ede6168b5a0f58/image.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user runs a Case Inventory Report; Consolidated Case icons are displayed appropriately.

- Log in as any Court User
- Click on the Reports Menu and select Case Inventory Report
- On the Run Case Inventory Report Pop-up, Select either a Judge or a Case Status (or both) and click Run Report.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead cases in a consolidated group now display the Lead Case Icon next to the docket number.
- [x] **NEW FUNCTIONALITY** - Member cases in a consolidated group now display the Member Case Icon next to the docket number.
- [x] **NEW FUNCTIONALITY** - When hovering your mouse over the icon, the tooltip indicates whether it is a Lead Case or Consolidated Case



#### 2) Court user prints a Case Inventory Report; Consolidated Case Icons are displayed appropriately on the printed report.

- Continuing from the previous test
- Click on the Printable Report Link located on the top right of the screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - Lead cases in a consolidated group now display the Lead Case Icon next to the docket number.
- [x] **NEW FUNCTIONALITY** - Member cases in a consolidated group now display the Member Case Icon next to the docket number.
