### ISSUE TITLE
Debug and diagnose Terraform failures.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#840]
Blocking #728, worked around in #735. Terraform is timing out when calculating plans, and we’re not quite sure why.

**Comment by mmarcotte** [comment]
Nothing is in the Trace logs. :( Then it just exited without calculating the state. Tough one.

**Comment by mmarcotte** [comment]
Possibly related to or helped by https://github.com/ustaxcourt/ef-cms/issues/843
