### ISSUE TITLE
Corporate Disclosure Statement: Petition Entry Changes

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8409]
As a Petitions clerk, so that the DAWSON UI reflects changes to the Ownership Disclosure Statement, I need the Petition entry UI updated to reflect correct verbiage.

With the approval of the upcoming rules package by the Court, the Ownership Disclosure Statement (ODS) is being renamed/replaced as the Corporate Disclosure Statement. We need to update all appropriate areas in DAWSON to reflect this change.

This story will address the Petitions entry/edit UI.

We anticipate these changes will need to be live in mid-March 2023.

## Pre-Conditions
ustaxcourt/ef-cms#8410

## Acceptance Criteria
* Label on ODS tab on Petition entry/edit screen is updated to "CDS"
* Label on "Order for Ownership Disclosure Statement" check box on Petition entry/edit screen is updated to "Order for Corporate Disclosure Statement"
* Attachment link on Review Petition screen is updated to read "Corporate Disclosure Statement" (if needed) - see note
* The Orders/Notices Needed warning message is updated to read "Order for Corporate Disclosure Statement"

## Notes
* On the Review Petition attachments card, if the ODS link is simply lifted from the docketed entry, then this might be addressed with ustaxcourt/ef-cms#8151 (changes to DISC event code, including docketing text/display/title)
* Tab on Petition entry/edit screen:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/815d3f96-eb19-45f1-b77a-b4c291b10eef)
* Text on Petition entry/edit screen:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/e4588d1e-0559-4196-b1d0-719bf08c9d31)
* Attachments card on Review Petition screen:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/fd803fa4-29f8-4776-be2f-f2f473a5d1c6)
* Orders/Notices Needed Message on the Review and Serve Petition Screen:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/aba2d97d-db36-4283-88d7-2cf82bce74e9)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions clerk/Case Services Supervisor starts a new Paper Petition; The Document tab is updated to CDS.

- Log in as a Petitions Clerk or Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Review this page

Expected Results
- [x] **NEW FUNCTIONALITY** - The label on the ODS tab has been updated to "CDS"

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor


#### 2) Petitions Clerk/Case Services Supervisor creates a new case for a Corporation; adds a Corporate Disclosure Statement document to a Petition; Updated document title is displayed on the review screen.

- Continuing from the previous test
- Upload/Scan a Petition doc and a Corporate Disclosure Statement to the Case
- Complete the required fields for the petition, making sure that you select either Corporation or any of the Partnership types as the Party Type
- Do not check the box for "Order for Corporate Disclosure Statement" (this is a later test)
- Click Create Case
- On the "Review the Petition" Screen:

Expected Results:
 - [x] **NEW FUNCTIONALITY** - The Attachment link is updated to read "Corporate Disclosure Statement".

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor
*Be sure to test this with different party types to ensure that the document name is correct for all party types.



#### 3) Petitions Clerk/Case Services Supervisor Serves the Paper Petition for the Corporation to the IRS;  Corporate Disclosure Statement document title is reflected on the docket record appropriately; Document Cover sheet is correctly titled.

- Continuing from the previous test
- Click on the Serve to IRS button
- Click Yes, Serve
- Click Done on the Print for paper service page
- Click on the Served tab
- Click on the docket number link for the Petition you just served
- 

Expected Results:
- [ ] The document title is Corporate Disclosure Statement
- [ ] The event code is DISC
- [ ] The rest of the document data is correct (index number, date filed, number of pages, filer, served date, service)
- [ ] When viewing the CDS document in the Document view, the coversheet displays the correct title of "Corporate Disclosure Statement"

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor


#### 4) Petitions Clerk/Case Services Supervisor adds a Paper Petition for a Corporation; Petition is missing the DCS; Order for Ownership Disclosure Statement checkbox has been updated to "Order for Corporate Disclosure Statement"

- Log in as a Petitions Clerk or Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Upload a Petition document
- Select Corporation as the Party type from the parties tab

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The checkbox that used to state "Ownership Disclosure Statement" is now updated to state, "Corporate Disclosure Statement".

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor
*Repeat this test by selecting the following all of the Partnership selections as the Party type to ensure that the updated Order checkbox is displayed.

#### 5) Petitions Clerk/Case Services Supervisor creates a case for a Corporation; Corporate Disclosure Statement is reflected appropriately in the Orders/Notices Needed Message.

- Continuing from the previous test
- Be sure that the checkbox for the Order for Corporate Disclosure Statement has been selected
- Fill out all of the required fields for the Petition
- Click Create Case

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Orders/Notices Needed section is updated to reflect the Order for Corporate Disclosure Statement

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor
*Repeat this test to ensure that all of the Partnership selections that you selected in the previous test case as the Party type displays the appropriate Order needed.



#### 6) Petitions Clerk/Case Services Supervisor QC's an electronic Petition submitted by a Corporation; The Document tab is updated to CDS; The checkbox is updated to Order for Corporate Disclosure Statement.

- Log in as a Petitions/Case Services Supervisor
- Click on Document QC
- Click on Section Document QC
- Click on the Petition link for a Petition that is in the new status (should pick a petition that is from a Corporation - you can tell b/c it will be a business name)

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The label on the ODS tab has been updated to "CDS"
- [ ] **NEW FUNCTIONALITY** - The checkbox that used to state "Ownership Disclosure Statement" is now updated to state, "Corporate Disclosure Statement".
- [ ] **NEW FUNCTIONALITY** - When switching the Party type from Corporation to any of the Partnership Party types, the Checkbox states "Corporate Disclosure Statement"


*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor



#### 7) Petitions Clerk/Case Services Supervisor creates a case from an electronically submitted Petition for a Corporation; Corporate Disclosure Statement is reflected appropriately in the Orders/Notices Needed Message.

- Continuing from the previous test
- Be sure that the checkbox is checked for the Order for Corporate Disclosure Statement
- Click the Review Petition link

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Orders/Notices Needed section is updated to reflect the Order for Corporate Disclosure Statement

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor
*Be sure that this is reflected appropriately for all party types (Corporation/Partnerships)


#### 8) Petitions Clerk/Case Services Supervisor creates a case from an electronically submitted Petition for a Corporation that has uploaded an ODS; Updated document title is displayed on the review screen.

- Log in as a Petitions Clerk/Case Services Supervisor
- Click on Document QC
- Click on Section Document QC
- Click on the Petition link for a Petition that is in the new status (should pick a petition that is from a Corporation - you can tell b/c it will be a business name)
- Be sure that an ODS has been uploaded for this case, do not check the box for needing an Order for Corporate Disclosure Statement.
- Fill in the required fields for completing the QC of this electronically filed Petition
- Click the Review Petition link

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The Attachment link is updated to read "Corporate Disclosure Statement".

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor
*Be sure that this is reflected appropriately for all party types (Corporation/Partnerships)


#### 9) Petitions Clerk/Case Services Supervisor Serves the electronic Petition for the Corporation to the IRS;  Corporate Disclosure Statement document title is reflected on the docket record appropriately; Document Cover sheet is correctly titled.

- Continuing from the previous test
- Click on the Serve to IRS button
- Click Yes, Serve
- Click Done on the Print for paper service page
- Click on the Served tab
- Click on the Petition link for the Petition you just served
- 

Expected Results:
- [x] The document title is Corporate Disclosure Statement
- [x] The event code is DISC
- [x] The rest of the document data is correct (index number, date filed, number of pages, filer, served date, service)
- [x] When viewing the CDS document in the Document view, the coversheet displays the correct title of "Corporate Disclosure Statement"

*Be sure to do this test with both roles - Petitions clerk and Case Services Supervisor

**Comment by cholly75** [comment]
Story go-live date confirmed 3/20

**Comment by rachelschneiderman** [comment]
Blocking until story can be deployed since we did not implement a feature flag. Test cases are passing.
