### ISSUE TITLE
Corporate Disclosure Statement: OODS Event Code Changes

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8412]
As a Court user, so that DAWSON reflects changes to the Ownership Disclosure Form, I need to update verbiage and behavior associated with the OODS event code.

With the approval of the upcoming rules package by the Court, the Ownership Disclosure Statement (ODS) is being renamed/replaced as the Corporate Disclosure Statement. We need to update all appropriate areas in DAWSON to reflect this change.

This story will address the behavior of the OODS event code (Order for Ownership Disclosure Statement).

We anticipate these changes will need to be live in mid-March 2023.

## Acceptance Criteria
* OODS event code document title is updated to "Order for Corporate Disclosure Statement"
* Document dropdown menus for filing/adding documents reflect new document title of "Order for Corporate Disclosure Statement"
* Behavior for adding OODS documents to docket remains the same - no changes aside from title/display
* Currently docketed/filed OODS entries are unaffected by this change (no need to make retroactive)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court User creates an Order for a Corporate Disclosure Statement; Document type dropdown menu reflects the new title "Corporate Disclosure Statement".

- Log in as a Petitions Clerk
- Navigate to a case
- Click on the Create button
- Click on the Order or Notice option
- Select the general Order as the Order Type
- Leave "Order" as the Order title, and click Continue
- Add in some text in the text area on the Create Order screen, and then click Save
- Add in the judges signature and then click Save Signature
- Click Add Docket Entry for the Order
- On the Add Docket Entry Screen, Click on the Dropdown menu for Document Type

*Repeat this test with CotC, Docket, Case Services Supervisor roles

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Order for Ownership Disclosure Statement is no longer an option in the dropdown menu
- [x] **NEW FUNCTIONALITY** - There is a new option for Order for Corporate Disclosure Statement in the dropdown menu



#### 2) Court User selects Order for Corporate Disclosure Statement in the Document Type Dropdown; Save's and Serve document; Document Title is displayed appropriately on pop-up and on print for paper service screen.

- Continuing from the previous test
- Select Order for Coporate Disclosure Statement
- Add in a future date
- Click Save and Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Document title "Order for Corporate Disclosure Statement" is reflected appropriately on the "Are you ready to Initiate Service?" pop-up modal that appears.
- [x] **NEW FUNCTIONALITY** - After clicking Yes, Serve the Print for Paper Service screen displays the correct document title on the header

*Repeat this test with CotC, Docket, Case Services Supervisor roles


#### 3) Court User selects Order for Corporate Disclosure Statement in the Document Type Dropdown; Save's and Serve document; Document is reflected appropriately on the docket record.

- Continuing from the previous test
- Click Done on the Print for paper service screen
- Review the information for the document on the Docket Record

Expected Results:
- [x] The Event Code is OODS
- [x] **NEW FUNCTIONALITY** - The Document Title is Order for Corporate Disclosure Statement
- [x] All other information on the docket record is as normal (page numbers, date of service, served parties code, edit/seal links if you are a docket clerk)

*Repeat this test with CotC, Docket, Case Services Supervisor roles


#### 4) Court User navigates to a case that has an Order for Ownership Disclosure Statement already docketed; Document title remains the same, new document title is not displayed on existing docket entries.

- Log in as a Court User
- Navigate to a Case that has an Order for Ownership Disclosure Statement already on the docket record

Expected Results:
- [x] New document title is not present, old document title remains.



#### 5) Public User searches for an Order for Ownership Disclosure Statement from the Order Search Page; Search results display appropriate Orders

- Navigate to the DAWSON home page
- As a public user, click on the Order tab
- Type in "Ownership" in the Search by Keyword or Phrase area
- Click Search

Expected Results:
- [x] Orders for Ownership Disclosure Statement documents return in the search results


#### 6) Public User searches for an Order for Corporate Disclosure Statement from the Order Search Page; Search results display newly titled Orders

- Navigate to the DAWSON home page
- As a public user, click on the Order tab
- Type in "Corporate" in the Search by Keyword or Phrase area
- Click Search

Expected Results:
- [x] Orders for Corporate Disclosure Statement documents return in the search results




#### 7) Docket Clerk edits an existing Order for Ownership Disclosure Statement document type to a Corporate Disclosure Statement; System updates the docket record appropriately.

- Log in as a docket clerk
- Navigate to a case that has an Order for Ownership Disclosure Statement on the docket record.
- Click on the Edit link from the docket record
- From the document type dropdown, select Corporate Disclosure Statement
- Click Save

Expected Results:
- [x] Green confirmation banner indicating that the Docket entry changes were saved.
- [x] Event Code remains the same OODS
- [x] **NEW FUNCTIONALITY** - Document title has been updated to Order for Corporate Disclosure Statement


*Repeat this test with CotC, and Case Services Supervisor roles

**Comment by cholly75** [comment]
Story go-live date confirmed 3/20

**Comment by rachelschneiderman** [comment]
Blocking until story can be deployed since we did not implement a feature flag. Test cases are passing.
