### ISSUE TITLE
Display All Docket Entries on Document View Index

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8415]
As a Court user, to lessen confusion on the Document View, I need all docket entries to display on the index portion of the Document View screen.

Currently, docket entries that do not have a corresponding document in DAWSON (minute entries, older docket entries whose files were not migrated into DAWSON) do not show in the index when looking at the Document View of the case. This leads to confusion (and in some cases panic) over missing entries or number sequencing on the record.

We would like all docket entries reflected in the index, and for these entries to be unselectable by the user (as there is no document to display on this view). 

## Acceptance Criteria
* Docket entries with no associated document are displayed when looking at the Document View screen

## Notes
Example of index view for a case w/ minute entry (in this case, docket entry ustaxcourt/ef-cms#6494 is a minute entry indicating that the filing fee has been paid):
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/a796c6f1-0dac-4bc7-bd5d-bedb15f1aaf4)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
![Screenshot 2023-03-09 at 1.48.58 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/689eab56-cb50-46cc-8107-06f3d8d0dfc0)
Per the Case Services meeting, it was determined this mockup was the preferred out of 6 designs.
Mockup details: 
1.   Per the AC, include all index numbers in the document view table.  Those which do not have a document view should appear in gray (use color A9AEB1 which is a pre-existing hex code from the USTC style guide)
2. Users will not be able to click into the grayed out/disabled rows, but can hover
3. Upon hover over the cell, users will see a "No Document View" hover tip message
4. Since users are not able to click into the disabled rows, the Document View will display whatever the previously selected document was, which will also remain highlighted.
5. Disabled rows should not have a cell highlight upon hover.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user navigates to the document view on a case; minute entries now display in grey text and are not selectable.

- Log in as a Court User
- Navigate to a Case
- Ensure that the docket record contains at least one minute entry.
- Click on the Document View tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - Minute entry index numbers are now displayed in the list of documents on the document view page
- [x] **NEW FUNCTIONALITY** - Minute entries display in a lighter grey text
- [x] **NEW FUNCTIONALITY** - User is unable to click on the minute entry
- [x] **NEW FUNCTIONALITY** - When hovering over the minute entry, helper text indicates "No document view"
- [x] **NEW FUNCTIONALITY** - Previous document selection will remain and display that document in the document view.
- [x] **NEW FUNCTIONALITY** - Minute entry rows do not have the cell highlight.


#### 2) Repeat this test with other Court users to ensure the same behavior.

**Comment by TomElliottFlexion** [comment]
Note: after brief discussion w/UX, we're sticking with the existing $theme-color-base color for the disabled document rows

**Comment by ttlenard** [comment]
@TomElliottFlexion All tests pass! Thank you!
