### ISSUE TITLE
Add Motion Filter to Docket Record

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8418]
As a DAWSON user, so that I can quickly navigate to motions, I need to be able to filter the docket record view to only display Motion event codes/entries.

In the course of a case, many times there will be multiple references to specific motions that have been filed. Currently the user must navigate the entirety of the docket record to locate and view a specific motion in question. With long docket records, this becomes unwieldy and confusing.

We would like for a user to be able to see a filtered view of the docket record that includes only those docket entries coded with motion-related event codes. This functionality should manifest as an option in the menu introduced in story ustaxcourt/ef-cms#8226 .

## Acceptance Criteria
* User can see a view of the docket record that includes only docketed entries for the case for which the event code begins with "M"
* User can interact with the docket entries on this view in the same manner as interacting with them on the Docket Record view based on their role (i.e., docket clerks can edit and seal entries from this view)
* User can easily navigate to or implement this view and then return to the full docket record
* View is accessible to all users
* View is ordered in the same default manner as the standard docket record view
* Docket entries on this view obey all other standard rules for visibility
* "Motion" filter option should be sorted alphabetically on the "Filter By" menu

## Notes

These two motions are covered by the above A/C:
- Motion to Withdraw Counsel (filed by petitioner)
- Motion to Withdraw as Counsel 

This document is not in scope for Motions
- Application to Take Deposition

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases


#### 1) Court user can choose to view only docket entries related to Motions on the docket record of a case.

- Log in as any court user (be sure to test with various court user roles)
- Navigate to a case that has Motions 
- In the View Filter, select Motions

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Motion documents and does not show other document types. 
- [x] **NEW FUNCTIONALITY** - The Filter dropdown menu is sorted alphabetically, with Exhibits as the first option, Motions as the second option, and Orders third in the dropdown menu.

*Repeat this test with multiple docket records to ensure that all of the Motion documents are being filtered appropriately



#### 2) Docket Clerk can view/interact with documents on the docket record from the filtered Motion view.

- Log in as a Docket Clerk
- Navigate to a case that has Motions
- In the View Filter, select Motions

Expected Results
- [x] When clicking on the Motion Document title, the Document Preview opens, and you can view the document
- [x] Docket Clerk can seal the motion document from the filtered view on the docket record
- [x] Docket Clerk can edit the Motion document from the filtered view on the docket record 



#### 3) Court user can view/interact with documents on the docket record from the filtered Motion view.

- Log in as a Court User (be sure to test with various Court user roles)
- Navigate to a case that has Motions
- In the View Filter, select Motions

Expected Results
- [x] When clicking on the Motion Document title, the Document Preview opens, and you can view the document



#### 4) Court user can easily change between filtered Motion View, Order view, Exhibit view, and the All Documents View

- Log in as any court user (be sure to test with various court user roles)
- Navigate to a case that has Motions, Orders, and Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In the View Filter, select Motions
- Next, select Exhibits
- Next, select Orders
- Switch back to All Documents

Expected Results
 - [x] **NEW FUNCTIONALITY** - Docket record quickly reloads to show only Motions, Only Orders, only Exhibits, or All Documents depending on what filter the user has selected.



#### 5) Court user Filters for Motions only on the docket record; Sorts by other fields

- Log in as any Court user (be sure to test with various court user roles)
- Navigate to a case that has Motions 
- In the View Filter, select Motions
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Motions sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Motions is selected in the View Filter.



#### 6) Parties on a case an choose to view only docket entries related to Motions on the docket record of a case.

This test has some set up:
- Log in as a docket clerk
- Navigate to a case that has Motions
- In one of those cases, add a test petitioner, a test IRS respondent, and a test private practitioner

- Log in as a Petitioner 
- Navigate to the case that you were just added to
- In the View Filter, select Motions

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Motion documents, and does not show other document types.

*Repeat this test with IRS and Private Practitioner roles



#### 7) Party on a case filters for Motions only on the docket record; Sorts by other fields

- Log in as as a petitioner
- Navigate to the case that has Motions that you got access to in the previous test
- In the View Filter, select Motions
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Motions sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Motions is selected in the View Filter.

*Repeat this test with IRS and Private Practitioner roles



#### 8) Public non-logged in users can choose to view only docket entries related to Motions on the docket record of a case.

- Navigate to the DAWSON homepage search dashboard
- From the Case Search Screen, input a Petitioner name or a docket number for a case that has Motions. 
- Click Search
- In the View Filter on the docket record of the case that you searched for, select Motions

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Motion documents, and does not show other document types.
- [x] **NEW FUNCTIONALITY** - The option for Exhibits is NOT available to Public non-logged in users or the public terminal user, only Motions and Orders should be available in the dropdown menu options.
- [x] **NEW FUNCTIONALITY** - Motions do not have an active link as per usual visibility rules for public users.



#### 9) Public non logged in user filters for Motions only on the docket record; Sorts by other fields

- Continuing from the previous test
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [ ] **NEW FUNCTIONALITY** - The Motions sort appropriately
- [ ] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Motions is selected in the View Filter.



#### 10) Public Terminal user can choose to view only docket entries related to Motions on the docket record of a case.

- Navigate to DAWSON as the Public Terminal User
- From the Case Search Screen, input a Petitioner name or a docket number for a case that has Motions. 
- Click Search
- In the View Filter on the docket record of the case that you searched for, select Motions

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Motion documents, and does not show other document types.
- [x] **NEW FUNCTIONALITY** - The option for Exhibits is NOT available to Public non-logged in users or the public terminal user, only Motions and Orders should be available in the dropdown menu options.
- [x] **NEW FUNCTIONALITY** - Motions have an active link as per usual visibility rules for the public terminal user.



#### 11) Public Terminal user filters for Motions only on the docket record; Sorts by other fields

- Continuing from the previous test
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Motions sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Motions is selected in the View Filter.



#### 12) Docket Clerk seals a Motion from the public; Parties on the case can filter and view the sealed Motion documents from the filtered docket record view

- Log in as a Docket Clerk
- Navigate to a case that has Motions 
- In one of those cases, seal the Motion documents to the public
- Next, log in as a party to the case
- Navigate to the case where you sealed the motion
- Filter by the Motion view

Expected Results
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Motion documents, and does not show other document types.
- [x] Red lock icon appears next to the title of the sealed Motion document
- [x] Sealed Motion document is hyperlinked
- [x] When clicking on the Sealed Motion Document title hyperlink, the Document Preview opens, and you can view the document



#### 13) Docket clerk seals a Motion from the public and parties on the case; Parties on the case can filter and see that there is a sealed Motion document on the docket record view, but are unable to view it.

- Log in as a Docket Clerk
- Navigate to a case that has Motions
- In one of those cases, seal one of the Motion documents to the public and parties on the case
- Next, log in as a party on the case
- Navigate to the case where you sealed the Motion
- Filter by the new Motion view

Expected Results
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Motion documents, and does not show other document types.
- [x] Red lock icon appears next to the title of the sealed Motion document
- [x] Sealed Motion document is NOT hyperlinked
- [x] Party/public user/terminal user is unable to click on the Sealed Motion Document
- [x] The option for Exhibits is NOT available to Public non-logged in users or the Public terminal User, only Motions and Orders should be available in the dropdown menu options.

*Repeat this test with a non-logged in public user and the Public Terminal User by navigating to the case from the Case Search screen.

**Comment by cholly75** [comment]
Test case 9 N/A - public non logged in user cannot sort docket record.
