### ISSUE TITLE
New Trial Session Type - Hybrid S

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8424]
As a calendar clerk, so that I can appropriately schedule and calendar judges and cases, I need a new Type option when creating/editing a Trial Session.

The Court is moving forward with a new type of trial session designed to include both regular and small-type cases with amounts at issue under $50K or less. To facilitate the assignment of cases and judges to these sessions, we would like to be able to call these out as their own particular trial session type, in this case "Hybrid-S".

To begin with, these will function in all respects like a Hybrid trial session, including the criteria used to populate the Eligible Case list for these sessions. 

Future calendaring stories and operational rigor around tracking amounts at issue will introduce additional functionality with Hybrid-S sessions, including their addition to screen and report filters.

## Acceptance Criteria
* When creating a trial session, a user can select "Hybrid-S" as a Type of Trial Session.
* When editing a trial session, a user can select "Hybrid-S" as a Type of Trial Session.
* The Eligible Case list for a "Hybrid-S" session is populated using the same criteria as a "Hybrid" trial session for that location/date/etc. would (i.e., there should be no difference between the Eligible Case list for a Hybrid-S session and a Hybrid session given identical details of scope/location/date/proceeding type) 
* Hybrid-S trial sessions behave in all respects like Hybrid trial sessions.
* Hybrid-S is added to the Session Type filter dropdown for all Trial Session views
* Selecting "Hybrid-S" on the Session Type filter restricts displayed sessions to only those with Hybrid-S as their Session Type
* Filter continues to work in conjunction with all other filters on these views

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
When creating a new trial session, the "Hybrid-S" session type should be below the "Hybrid" option and above the "Special" option.

**Comment by ttlenard** [comment]
## Test Cases


#### 1) Petitions/Calendar clerk adds a new trial session; New option for Hybrid S is available as a Session Type.

- Log in as a Petitions Clerk 
- Click on Trial Sessions
- Click on Add Trial Session

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a new radio button option for Hybrid S in the Session Type section.



#### 2) Petitions/Calendar clerk adds a new Hybrid S session; Session saves appropriately and information is displayed correctly.

- Continuing from the previous test
- Fill in the required fields on the Session information page
- Be sure to select Hybrid S as the Session type
- Click Add Session

Expected Results:
- [x] Green confirmation banner on Trial Session Open tab indicating that Trial Session was added.
- [x] **NEW FUNCTIONALITY** - The trial session you just added (will be on the New Tab) shows Hybrid S in the Session Type Column.
- [x] **NEW FUNCTIONALITY** - After clicking on the City, State link, the Hybrid S displays on the Details Card as the Session type on the Session Information Page.



#### 3) Newly created Hybrid S session functions as per normal Hybrid Trial Session; Displays Eligible case list correctly.

- Continuing from the previous test
- Scroll down to the Eligible case list

Expected Results:
- [x] Filter is present for clerk to be able to filter by case procedure (regular or small)
- [x] Total QC completed counts for Regular, Small, and Total Completed



#### 4) Hybrid S calendar is set; Notices are generated on the docket record as per normal.

- Continuing from the previous test
- Check the box for QC complete on a few Regular and Small cases (Be sure that some of the cases that you QC complete have Petitioners receiving paper service).
- Click the button for Set Calendar
- Click Yes, Set Calendar.

Expected Results:
- [x] Print for paper service screen appears
- [x] Ensure that the paper service includes the following:
	- [x] Address cover sheet for paper petitioners
	- [x] Notice of Trial
	- [x] Appropriate Clinic Letter for S or R cases
	- [x] Standing Pre Trial Order and Pretrial Memorandum
- [x] **NEW FUNCTIONALITY** - After clicking done on the print for paper service, and clicking on the Open tab, The session type reflects Hybrid S on the Session type column.
- [x] **NEW FUNCTIONALITY** - After clicking on the City, State link, Hybrid S displays on the Details Card as the Session type on the Session Information Page.



#### 5) Petitions/Calendar Clerk edits an upcoming trial session from a different session type to a Hybrid S session type; Session information saves appropriately.

- Log in as a Petitions/Calendar Clerk
- Click on Trial Sessions
- Find a Trial session that is in the future (can be from open tab or the new tab)
- Click on the City, State of the trial session
- Click on the Edit link from the Session Information page

Expected Results:
- [x] **NEW FUNCTIONALITY** - Hybrid S is now an option in the Session Type section on the Edit Trial Session Page
- [x] **NEW FUNCTIONALITY** - After updating the Session type to Hybrid S, Clerk can save the session as per normal.
- [x] Green confirmation banner indicating Trial Session updated
- [x] **NEW FUNCTIONALITY** - The Hybrid S displays on the Details Card as the Session type on the Session Information Page.
- [x] For New Sessions only - Eligible case list displays both Regular and Small Cases as per usual Hybrid sessions (including filter, totals by case type, and grand total)


#### 6) Court User Prints the Session information; Hybrid S session information is displayed in the Printed document.

- Log in as any court user
- Click on the Trial Sessions Tab
- Click on the City, State link for an upcoming Hybrid S trial session
- Click on the Print link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The printed copy displays Hybrid S next to the Date at the top of the document.



#### 7) Hybrid S sessions appear on the Trial Session Planning Report.

*Preconditions: Be sure that you have already set a calendar for at least one session for Winter 2023 that is a Hybrid S type of session.  Be sure to take note of which City, State and the assigned Judge for the session.

- Log in as a Court User
- Click on the Trial Sessions Tab
- Click on the Trial Session Planning Report
- Select Fall as the trial term
- Select 2023 as the year.
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - All Hybrid S Trial sessions that were scheduled in Winter 2023 appear appropriately on the Trial Session Planning report. (HS)?



#### 8) Petitions/Calendar Clerk can delete a newly created Hybrid S session.

*Preconditions: Petitions/Calendar clerk has added a New Hybrid S Trial Session, has not yet set the calendar.

- Log in as a Petitions/Calendar Clerk
- Click on the Trial Sessions Tab
- Click on the New Tab
- Click on the City, State link of the Hybrid S session 
- Click the Delete Session link in the upper right hand corner of the screen.
- Click Yes, Delete

Expected Results:
- [x] Session is deleted.
- [x] User is routed back to the New tab.

#### 9) Hybrid S appears in the Session Type Filter

- Log in as any Court User
- Click on the Trial Sessions Tab
- From the Open tab, click on the Session Type Dropdown Filter

Expected Results:
- [x] **NEW FUNCTIONALITY** - Hybrid S appears in the dropdown list below Hybrid and above Special

*Repeat this test with the New tab, Closed tab, and All tab
- [x] **NEW FUNCTIONALITY** - Hybrid S appears in the Session Type Filter dropdown on the New Tab
- [x] **NEW FUNCTIONALITY** - Hybrid S appears in the Session Type Filter dropdown on the Closed Tab
- [x] **NEW FUNCTIONALITY** - Hybrid S appears in the Session Type Filter dropdown on the All Tab


#### 10) After Selecting the Hybrid S filter from the Session Type Dropdown, Results in the table below filter appropriately.

- Continuing from the previous test
- Click on the Open tab
- Select the Hybrid S filter from the Session Type Dropdown list

Expected Results:
- [x] **NEW FUNCTIONALITY** - The table filters appropriately to only display Hybrid S session types

*Repeat this test with the New tab, Closed tab, and All tab
- [x] **NEW FUNCTIONALITY** - The table filters appropriately to only display Hybrid S session types on the New, Closed, and All tabs when the filter is selected.

**Comment by katiecissell** [comment]
When filtering the trial session list, the "Hybrid-S" session type should be below the "Hybrid" option and above the "Special" option. (This is identical to when creating a new trial session)

**Comment by ttlenard** [comment]
@TomElliottFlexion I've added two additional test cases (9 and10 above) to account for adding the Hybrid S option to the Session Type Filter.
