### ISSUE TITLE
Terminal User: Remove Visibility to Struck Docket Entries

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8433]
As the terminal user, so that I do not see information removed from the docket record, I need to not be able to view stricken docket entries.

The terminal user can currently view documents that have been stricken from the record. In accordance with Court policy, these documents should only be viewable by Court personnel. We need to remove the terminal user's ability to open documents stricken from the docket record.

Screen grab of sticken entry with hyperlink:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/9d9ac076-bc19-471a-802b-f456d06047a0)

## Acceptance Criteria
* Documents belonging to stricken docket record entries are not hyperlinked when the docket record is viewed by the terminal user

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Terminal User accesses the docket record of a case that has stricken entries; No hyperlink available for the stricken entries.

- Access DAWSON as the Terminal User
- Type in the docket number of a case that has stricken entries

Expected Results:
- [x] **NEW FUNCTIONALITY** - The stricken entries are no longer active hyperlinks on the docket record.
- [x] **NEW FUNCTIONALITY** - The stricken document cannot be opened or viewed.


#### 2) Regression test Terminal User Permissions

- [x] Hyperlinks are available on the docket record for all documents besides documents that have been stricken, sealed to the public, or not yet served.
- [x] Terminal User can print the docket record
- [x] Terminal User can filter by documents on the docket record (Orders, Motions)
- [x] Terminal User cannot access the docket record for cases that are sealed at the case level.



#### 3) Regression test to ensure that no personal information info is displayed in the JSON.

- [x] Petitioner information is stored as "Public Contact".
- [x] When a Sealed Case is searched for, none of the specific case information is displayed in the JSON. Should be stored as "Public Case".

**Comment by ttlenard** [comment]
@rosiehsmith all tests pass! Thank you!
