### ISSUE TITLE
Updated OAP/OAPF

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8451]
As a petitioner, so that I am filling out the correct form, I need the Order for Amended Petition (OAP) and Order for Amended Petition and Filing Fee (OAPF) to be updated with the correct version of the amended petition form.

Currently we auto-generate both OAPs and OAPFs when the appropriate selections are made by the Petitions clerk at the time of entry. Both of these append a copy of the Petition form to the order text itself, to assist the Petitioner.

As the Petition form was changed with the 3/23 Rules package update, we need to make the corresponding change to the Petition form we include with the OAP and OAPF orders. Attached in the notes is a copy of the correct Petition form.

## Acceptance Criteria
* Auto-generated OAPs append the updated Petition form after the Order page
* Auto-generated OAPFs append the updated Petition form after the Order page
* No other changes to the text or construction of the Order(s)

## Notes
* Updated petition form: [https://app.zenhub.com/files/152320868/1f73eb9e-eb46-40a9-82f7-463008a509be/download](https://app.zenhub.com/files/152320868/1f73eb9e-eb46-40a9-82f7-463008a509be/download) 

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement question: 
- The user story is unclear to us, not sure what the need is as written
As a petitioner, so that I am filling out the correct form, I need the **most up to date** Order for Amended Petition (OAP) and Order for Amended Petition and Filing Fee (OAPF).
-  Still same process and flow, just swapping out old form for new form, correct?

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk processes a petition and checks the box for an auto-generated Order for Amended Petition; The draft Order has the updated Petition attached to the Order

- Log in as a Petitions Clerk
- Click on Document QC
- Click on Start a Petition
- Scan or Upload a Petition, STIN, and RQT
- Complete the information that is required for the Parties tab
- Fill in the information on the Case Info tab, making sure that you check the box for Order for Amended Petition
- Fill in the required information on the IRS Notice tab
- Click Create Case
- On the review and Serve Petition screen, you should see that the Order for Amended Petition is indicated in the Yellow banner.
- Click Serve to IRS
- Click Yes, Serve
- Click Done on the Print for paper service screen
- Click on the Served Tab
- Click on the Docket Number of the Petition you just served
- Click on the Drafts tab

Expected Results
- [ ] **NEW FUNCTIONALITY** - The Draft Order has the updated Amended Petition form appended to the order.
- [ ] No other changes were made to the text of the Order
- [ ] Clerk can process the Updated Order as per normal (Sign, Add docket Entry, Serve)
- [ ] **NEW FUNCTIONALITY** - New Amended Petition form is appended to the Order on the Paper service screen
- [ ] Order for Amended Petition is displayed appropriately on the docket record of the case


**Repeat this test with the Case Services Supervisor role and the CotC role.

#### 2) Petitions Clerk processes a petition and checks the box for an auto-generated Order for Amended Petition and Filing Fee; The draft Order has the updated Petition attached to the Order

- Log in as a Petitions Clerk
- Click on Document QC
- Click on Start a Petition
- Scan or Upload a Petition, STIN, and RQT
- Complete the information that is required for the Parties tab
- Fill in the information on the Case Info tab, making sure that you check the box for Order for Amended Petition and Filing Fee
- Fill in the required information on the IRS Notice tab
- Click Create Case
- On the review and Serve Petition screen, you should see that the Order for Amended Petition is indicated in the Yellow banner.
- Click Serve to IRS
- Click Yes, Serve
- Click Done on the Print for paper service screen
- Click on the Served Tab
- Click on the Docket Number of the Petition you just served
- Click on the Drafts tab

Expected Results
- [ ] **NEW FUNCTIONALITY** - The Draft Order has the updated Amended Petition form appended to the order.
- [ ] No other changes were made to the text of the Order
- [ ] Clerk can process the Updated Order as per normal (Sign, Add docket Entry, Serve)
- [ ] **NEW FUNCTIONALITY** - New Amended Petition form is appended to the Order on the Paper service screen
- [ ] Order for Amended Petition and Filing Fee is displayed appropriately on the docket record of the case


**Repeat this test with the Case Services Supervisor role and the CotC role.
