### ISSUE TITLE
BUG: DAWSON PDF's not opening when the Adobe for Edge Extension is enabled

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8461]
**Describe the Bug**
When the Adobe for Edge extension is enabled on a user's browser, and they attempt to open some documents in DAWSON, they experience a spinning wheel and eventually receive an XML error.  We received a number of reports of this happening the week of June 4th.  Court users all had the extension on.  When they disabled the extension, then the PDF would open in the edge browser just fine.  Upon downloading the PDF documents that were erroring out, we did do some scanning of the documents that worked, and the documents that didn't work.  There were some differences (Need to talk to Mike Marcotte about these results!)

Also, when we discussed PDF issues during the critical bug retro, this issue could be related to the issues described in [critical bug retro](https://docs.google.com/document/d/1S6Y3a3qABcfEz_0tejZEV1CUAofEaIdwXwsl6vHF_38/edit) on 7/17

Most recent report from external user:
Case: 14440-22
Documents: 
13 - opens just fine
14, 15, 16 - XML error.

Found this article:
https://community.adobe.com/t5/acrobat-services-api-discussions/new-error-t5-corrupt-data-in-the-pdf-embedded-api-viewer/td-p/13801026

And this one too: 
https://stackoverflow.com/questions/33451942/what-does-this-xml-file-does-not-appear-to-have-any-style-information-mean

Chris copied this error log from Chrome:
[https://app.zenhub.com/files/152320868/f80432b6-3878-4d71-8c58-8a600883f7eb/download](https://app.zenhub.com/files/152320868/f80432b6-3878-4d71-8c58-8a600883f7eb/download)

**Business Impact/Reason for Severity**
High

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
Court users, Public users

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Make sure that the Adobe for edge extension is turned on
2. Go to case 14440-22, click on documents 14, 15, or 16
3. Click on View Full PDF
4. A new window will open, and you'll experience a spinning wheel for awhile (like 1 min or more), and then eventually an XML error.

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

Here is the error:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/c71ffdce-c05e-486f-ac7f-c26ba6fa3d33)

They all seem to have this error as well:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/c2e5b0c1-a292-4e72-83f5-47e72972ba8d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by Mwindo** [comment]
I tried to reproduce this issue but was able to view documents 14, 15, and 16 on 14440-22 just fine (in test). Maybe this is an issue with the Adobe extension that has since been fixed? Otherwise, perhaps this is a Windows-specific issue. (I tested this with my Mac.)

**Comment by ttlenard** [comment]
I also tried to reproduce this bug, and it is now working.  Maybe Adobe did make some updates since this was reported?  I'll go ahead and close this ticket.
