### ISSUE TITLE
Remove DSC as Document Option for E-Filing/Paper Filing

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8464]
As a docket clerk, so that we do not encourage parties to file unsupported documents, I need the Designation of Counsel to Receive Service document type (DSC) removed as an option from all e-filing and paper filing document menus.

The DSC is a remnant from the days when we maintained all paper docket records, and is no longer supported as a document by the Court as a matter of policy. The Court has requested that we remove this as an option that can be selected by parties when e-filing or by docket when uploading a paper filing.

We do not need or want to retroactively remove or change DSC documents already in the system.

## Acceptance Criteria
* DSC is no longer available to external parties for selection as a document type or the target of another document type when e-filing
* DSC is no longer available to docket clerks as a document type when QCing an e-filed entry
* DSC is no longer available to docket clerks as a document type when docketing a paper filing

## Notes
* @jimlerza - we also need to remove DSC from https://ustaxcourt.gov/documents_eligible_for_efiling.html when this story goes live (and could do it any time prior to that as well)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Questions from pre-refinement:
Are there other scenarios where this DSC can be selected? No. Keep the code to support existing docs.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Practitioner files a document on a case; Designation of Counsel to Receive Service is not an option in the dropdown picklist.

- Log in as a Practitioner that has access to a case
- Click on the docket number link from the my cases list
- Click on the File a Document button.
- Click on the Document type dropdown and start typing "Designation of..."

Expected Results:
- [x] The Designation of Counsel to Receive Service option is no longer in the dropdown picklist.

*Repeat this test with both a private practitioner AND an IRS Practitioner.


#### 2) Petitioner files a document on a case; Designation of Counsel to Receive Service is not an option in the dropdown picklist.

- Log in as a Petitioner that has an open case
- Click on the docket number link from the my cases list
- Click on the File a Document button.
- Click on the Document type dropdown and start typing "Designation of..."

Expected Results:
- [x] The Designation of Counsel to Receive Service option is no longer in the dropdown picklist.




#### 3) Docket Clerk files a paper document on a case; Designation of Counsel to Receive Service is no longer an option in the document type picklist.

- Log in as a Docket Clerk
- Navigate to a Case
- Click on the Create Button
- Click on Paper Filing
- Upload a Document, Click on the Document type dropdown and start typing "Designation of..."

Expected Results:
- [x] The Designation of Counsel to Receive Service option is no longer available in the dropdown picklist.



#### 4) Docket Clerk edits an existing docket entry; Designation of Counsel to Receive Service is no longer an option in the document type picklist.

- Log in as a Docket Clerk
- Navigate to a Case
- Click on the edit button for a docket entry that was submitted by a party
- Click on the Document Type dropdown and start typing "Designation of..."

Expected Results:
- [x] The Designation of Counsel to Receive Service option is no longer available in the dropdown picklist the Docket record updates appropriately.



#### 5) Existing Designation of Counsel to Receive Service documents that were filed to the docket record previously remain on the docket record.

- Log in as a docket clerk
- Navigate to an existing case that has a Designation of Counsel to Receive Service document that is already filed on the docket record.

Expected Results:
- [x] The DSC document remains on the docket record and is displayed appropriately
- [ ] Docket Clerk can edit the document meta-data and the document saves appropriately (don't change the document type, but other meta data)
- [x] Docket Clerk can seal/unseal the DSC document as per usual.

**Comment by ttlenard** [comment]
Testing Feedback @jasonfu9966 

Test Case 5 is currently failing.  When navigating to a case in the system that has a legacy DSC document filed on the case (1532-23), I get a 400 error.  Looking at the network tab in the console, it seems like it is failing at entry 10, which is the existing DSC doc. 


![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2d8c6ffd-a532-455d-9d8f-92ea7baa5f05)

**Comment by ttlenard** [comment]
@jasonfu9966 

Looks like I can now access the case with the legacy DSC documents, but if I attempt to edit the DSC entry (Test Case 5, second checkbox), I notice that the document type is blank, and if I just try to edit the metadata for the entry I get an error that I need to add a document type.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/22b278d8-0bc4-4ac6-b541-31b1ba2ab539)

**Comment by jasonfu9966** [comment]
something we accounted for but is not yet a test case:
if a petitioner submits a document as DSC, then docket clerks should be able to QC that document as DSC.
