### ISSUE TITLE
BUG: Petitioner Service info and email address are not updating appropriately on cases

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8466]
**Describe the Bug**

Petitioners email address isn't displayed on the Petitioner information card in a case, and their Service preference is still set to Paper after the admissions clerk adds in an email, and the petitioner verifies their email.  At the point in the workflow where the admissions clerk adds in the email address for the petitioner, the petitioner information card shows the email address as pending.  Something seems to not be updating appropriately at the point where the Petitioner verifies their email address.  Petitioner ends up with eAccess to the case and can file documents, but the information in DAWSON is incorrect. It doesn't list their email and their Service preference still displays paper.

We have seen this happen a handful of times in production, but we have never been able to pinpoint why it happens. In test and staging, we are now seeing this happen ALL of the time.  

*Note that this DOES NOT happen if the Petitioner has already set up a petitioner account before an admissions clerk attempts to associate the petitioner to the case.  If petitioner creates an account beforehand, they get associated correctly.

**Business Impact/Reason for Severity**
Critical

**In which environment did you see this bug?**
Test, Staging, Prod

**Who were you logged in as?**
Admissions clerk and Petitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Big thanks to Mrin and Rosie for finding this one while they were developing another story.

**To Reproduce**
1. Log in as an admissions clerk
2. Navigate to a case where the Petitioner has paper service (not represented either)
3. Click on the case information tab and then parties tab
4. Click the edit button for the petitioner
5. Scroll down to the bottom and add in an email that you have access to
6. Save
7. Notice that the email address that you just entered for the Petitioner is displayed on the Petitioner card, and it should say that it is pending.
7. Next, log out of DAWSON.
8. Navigate to your email and find the email that asks the petitioner to verify their account
9. Log back in to DAWSON using the credentials that were in the email
10. You should now have access to your case and be able to file documents
11. Click on the Case information tab, and then the parties tab
12. Notice that your email address isn't stored on your petitioner card, and your service preference is still set to paper.

**Expected Behavior**
Once a petitioner verifies their email address, it needs to switch their service preference to electronic and also store their email address on the case.

**Actual Behavior**
A clear and concise description of what actually happened.
The email address isn't getting stored with the petitioner and the service preference is still displaying paper.

**Screenshots**
Here is a screen grab showing the email address is pending after the admissions clerk adds in the email.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/dd5a534f-ea1d-4bc2-9153-5211409fccd2)

Here is a screen grab showing the Petitioner that just verified their email address and accessed their case.  It shows no email provided and paper service, yet I am logged in and able to file documents and view my case.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2950d356-2782-489e-aa69-f8dca1cb26dd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by mmarcotte** [comment]
Looks like this is the underlying problem:

```
    "errorMessage": "User: arn:aws:sts::***:assumed-role/iam_update_petitioner_cases_lambda_role_stg/update_petitioner_cases_lambda_stg_blue is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:***:table/efcms-deploy-stg because no identity-based policy allows the dynamodb:GetItem action",

```

**Comment by mmarcotte** [comment]
## Plan of action:

- [x] Deploy this to production
- [x] Test this in lower environment 
- [ ] Add smoketest for entire process
  - [x] Petitions Clerk creates a Paper Case
  - [x] Admissions Clerk adds an Email to the petitioner for that Case
  - [x] ??? How do we control / ascertain the Temporary Password for the newly created user
  - [x] Petitioner with that Email logs in and sets a Permanent Password
  - [x] Asserts that NOCE filed and Petitioner has Electronic Access and Email Address specified (no longer pending)
- [x] Find affected users in production
- [x] Remedy the problem for the users affected in production
- [x] Report the users affected in production to Chris/Tenille
