### ISSUE TITLE
Docket Record: Allow Public/Parties To Sort By Age

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8480]
As a member of the public, so that I can quickly navigate a docket record, I need the Sort By menu added to the docket record view for non-logged in users.

We would like to extend the sorting currently available to logged in DAWSON users to the public at large.

## Acceptance Criteria
* Non-logged in user can access the Sort By menu on the docket record view for a case
* Sort By option selection reorders the docket record view in the same manner it currently does for a logged in user
* No other changes to functionality
* Mobile view can remain same, just extend to public

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/de7fc19c-5d0c-4db7-ac80-7f03d0137cbc)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Non logged in user navigates to a docket record; The sort by box is now visible to the non-logged in user.

- As a public non-logged in user, navigate to DAWSON
- From the case search page, enter in a docket number and click search
- Review the docket record page

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a box that is defaulted to "Sort by Oldest".
- [x] **NEW FUNCTIONALITY** - When the user clicks on the box, the options to Sort by Oldest, Sort by Newest, Sort by no. (ascending), and Sort by no. (descending) are available.


#### 2) Non-logged in user changes the default sort to Sort by Newest; docket record sort order is sorted newest to oldest.

- Continuing from the previous test
- Click on the Sort by Oldest box
- Select Sort by Newest

Expected Results:
- [x] **NEW FUNCTIONALITY** - Docket record entries are sorted appropriately, newest to oldest


#### 3) Non-logged in user changes the sort to Sort by no. (ascending); docket record sort order is sorted in ascending order by index number.

- Continuing from the previous test
- Click on the Sort by box
- Select Sort by no. (ascending)

Expected Results:
- [x] **NEW FUNCTIONALITY** - Docket record entries are sorted appropriately, in ascending order by index number



#### 4) Non-logged in user changes the sort to Sort by no. (descending); docket record sort order is sorted in descending order by index number.

- Continuing from the previous test
- Click on the Sort by box
- Select Sort by no. (descending)

Expected Results:
- [x] **NEW FUNCTIONALITY** - Docket record entries are sorted appropriately, in descending order by index number


#### 5) Non-logged in user accesses a docket record on a mobile device, Sort by oldest to newest is now visible.

- As a public non-logged in user, navigate to DAWSON on a mobile device
- From the case search page, enter in a docket number and click search
- Review the docket record page

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is an area that is defaulted to "Oldest to Newest".
- [x] **NEW FUNCTIONALITY** - When the user clicks on Oldest to Newest, it changes to Newest to Oldest.
- [x] **NEW FUNCTIONALITY** - No other sort by options are available on mobile.

**Comment by swongCO** [comment]
UX feedback
- Capitalize d in Filed date
- Change the order of rows to No., Filed Date, Filings and Proceedings, Served
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1VpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--065a7384e041f2596733e8dcd816b5a7aae1daf1/Screenshot%202023-08-21%20at%201.25.25%20PM.png)

**Comment by ttlenard** [comment]
Testing looks great! I love the refactoring work that was done on this story.  So much better! Thank you!

**Comment by ttlenard** [comment]
There may actually be an issue that I just found.  Looks like there is some funkiness in how the Served Parties are being displayed on the docket record for Court users.  This doesn't seem to affect external users.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc28yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--66d959d88fae1117bcd1f27f7161574fce827875/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3MyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bbc68212f48f0dd3291f266ce774fa0dfd138fac/image.png)

This is what it should look like:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3cyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3dbef402ee9037a01f465119d2ba475dd4d7d242/image.png)

**Comment by ttlenard** [comment]
The issues above are now fixed.  Thank you!
