### ISSUE TITLE
BUG: Advanced Search link for practitioners on mobile offer "Practitioner" as search option

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8508]
**Describe the Bug**
On mobile devices, when an IRS or private practitioner is logged in, clicking the Advanced Search link from the My Cases screen asks them to choose Case, Order, Opinion, or Practitioner for their search option.

Choosing "Practitioner" takes them to a non-functional page, however we need to remove this option from the UI so that it cannot be selected.

**Business Impact/Reason for Severity**
Confuses users; practitioner search is not available for non-Court users

**In which environment did you see this bug?**
TEST

**Who were you logged in as?**
Private Practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Checking mobile behavior
 
**To Reproduce**
1. Log in as a Private Practitioner
2. Click the "Advanced Search" link at the bottom of the My Cases display

**Expected Behavior**
User is presented with the option to search for Case, Order, or Opinion

**Actual Behavior**
User is presented with the option to search for Case, Order, Opinion, or Practitioner. Selecting "Practitioner" returns a non-functional page.

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjEvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--83c242ed4b66f59a5186f677905d0a1aec6fd0ee/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjkvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--806e7d5a04398eb143de2d3384486e0ad0a05c9d/image.png)

**Cause of Bug, If Known**
Since the creation of the mobile component, practitioner tab has not been hidden behind any logic, seems like this was broken since the feature was developed, or AC has changed for that feature.

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
All tests on Mobile (iPhone and Android) Pass. Thank you!
