### ISSUE TITLE
E-Filing: Modify Confirmation Banner When Multi-docketing

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8511]
As a petitioner or practitioner, so that I have correct expectations when multi-docketing an e-filing, I need the language in the confirmation banner to be updated.

When external parties e-file a document across a consolidated group, the green confirmation banner we display is like so:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWltIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--feb95e8c9e56f296a35eeecb7fb17281fb999f9a/image.png)

However, if the e-filing is for a "Simultaneous" document, this is not correct; simultaneous documents are held for service until both sides of the case have filed their respective versions.

To be more accurate and consistent in our messaging, we would like to update the confirmation banner text displayed when multi-docketing an e-filed document to be in line with what is displayed when filing in a single case:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXVtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--345e43d01e613265a45c0d4c64c9b9afb2340352/image.png)

## Acceptance Criteria
* Language in confirmation banner displayed after successfully e-filing across all cases in a consolidated group is changed to: "Document filed and is accessible from the Docket Records."

## Notes
- Would it be acceptable if the service message for internal folks (court employees) to change as well?

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Questions from pre-refinement:
- should the AC specifically point out that it's for simultaneous docs? NO, it'll be for all doc types
- confirm that change applies even when some of the consolidated cases are served NO, ptrs/practitioners can only file in all or one in a group

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner files a document across a consolidated group of cases; Confirmation banner text indicates that the document was filed and is accessible from the Docket record.

- Log in as a Petitioner that is associated with a consolidated group of cases
- Click on the docket number link of one of the consolidated cases from the My Cases Page
- Click on File a Document button
- Click on Ok, I'm ready to file button
- Select a document type and click Continue (any document type is ok)
- Upload a document and fill out the required fields, making sure that you select file in all cases in the group
- Click on Review Filing button
- Check the redaction acknowledgement checkbox
- Click Submit your filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - The green confirmation banner now displays "Document filed and is accessible from the Docket Record"
- [x] Green confirmation banner includes print receipt link. (No change in functionality)


*Repeat this test with the following:
- [x] Simultaneous documents
- [x] Response/amended/amendment/redacted Type documents
- [x] Log in as a Private Practitioner and repeat the test case above
- [x] Log in as an IRS Practitioner and repeat the test case above
