### ISSUE TITLE
Docket: Show Intervenor As Filing Party

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8512]
As an intervening party, so that the docket record correctly reflects filings I have made, I need the docket record to display "Intv." and my name in the Filed By column.

Currently, intervenors associated with a case are able to file documents to that case. In these situations, the docket record labels the intervenor as a petitioner. Docket clerks must manually edit the filing party to show that the person was an intervenor rather than the petitioner.

We would like to more accurately reflect the filing party on the docket record; rather than have Docket manually edit the Filed By value, we would like the system to reflect the appropriate role of the intervenor on the docket record.

## Acceptance Criteria
* When docketing a paper filing, if the docket clerk selects the Intervenor as the filing party, then the docket record should default to display "Intv." alongside the person's name in the Filed By column. 
* When a document is e-filed, if the user selects the Intervenor as the filing party, then the docket record should default to display "Intv." alongside the person's name in the Filed By column.
* When an Intervenor is one of multiple parties selected as the filers of a document, the Filed By value appropriately represents the intervenors in conjunction with the other filing parties (see screenshot 4)
* The "Filed By" value is represented appropriately where used elsewhere in DAWSON (e.g., print receipts, pending report, etc) to reflect "Intv." and the intervenor name  
* Docket entries can still be edited to display alternate text

## Notes
![image](https://github.com/ustaxcourt/ef-cms/assets/87043681/1980c786-6339-47e3-a1f4-71cad126bf3b)

![image](https://github.com/ustaxcourt/ef-cms/assets/87043681/7cb4db84-b86a-45d8-9957-823476e2cf9c)

![image](https://github.com/ustaxcourt/ef-cms/assets/87043681/ff73565e-16ee-452c-aac3-e01bae97f091)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFh4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4fb62a140485714db19488b51fcce84bd1458d10/image.png)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Questions from pre-refinement
- if a party's role changed to intervenor, does previous filings Filed By change too? NO
- why is this important? For accuracy in docket record

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk adds a paper filing to a case with an intervenor as a filing party; Selects Intervenor as the party filing the document; Document on the docket record indicates "Intv." followed by their name in the Filed by column.

- Log in as a Docket Clerk
- Navigate to a case that has an Intervenor as a party
- Click Create and then select Paper Filing
- Fill in the required fields and upload/scan a document on the Add Paper filing screen
- Be sure that you check the box for the Intervenor in the "Who is Filing this document?" Section.
- Click Save and Serve
- Click Yes, Serve

Expected Results:
- [x] Green confirmation banner 
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Intv. [Intervenor Name] on the docket record
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intv. [Intervenor Name]



~~#### 2) Docket Clerk adds a paper filing to a case with 2 intervenors as parties; Selects both Intervenors as the parties filing the document; Document on the docket record indicates "Intvs." [Intervenor 1 Name] & [Intervenor 2 Name] in the Filed by column.~~

~~- Log in as a Docket Clerk~~
~~- Navigate to a case that has 2 Intervenors as a parties to a case~~
~~- Click Create and then select Paper Filing~~
~~- Fill in the required fields and upload/scan a document on the Add Paper filing screen~~
~~- Be sure that you check the box for both of the Intervenors in the "Who is Filing this document?" Section.~~
~~- Click Save and Serve~~
~~- Click Yes, Serve~~

~~Expected Results:~~
~~- [ ] Green confirmation banner~~ 
~~- [ ] **NEW FUNCTIONALITY** - The Filed by column indicates Intvs. [Intervenor 1 Name] & [Intervenor 2 Name] on the docket record~~
~~- [ ] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intvs. [Intervenor 1 Name] & [Intervenor 2 Name]~~



#### 3) Docket Clerk adds a paper filing to a case with an intervenor as the filing party; Selects Intervenor and other petitioner(s) as the parties filing the document; Document on the docket record indicates "Intv." and "Petrs." appropriately in the Filed by column.

- Log in as a Docket Clerk
- Navigate to a case that has an Intervenor as a party
- Click Create and then select Paper Filing
- Fill in the required fields and upload/scan a document on the Add Paper filing screen
- Be sure that you check the box for the Intervenor and Petitioner(s) in the "Who is Filing this document?" Section.
- Click Save and Serve
- Click Yes, Serve

Expected Results:
- [x] Green confirmation banner 
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Petrs. [Petitioner(s) name(s)] & Intv. [Intervenor Name] on the docket record
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Petrs. [Petitioner(s) name(s)] & Intv. [Intervenor Name]


*Repeat this test by also checking the box for Respondent when making a paper filing. 
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Resp. & Petrs. [Petitioner(s) name(s)] & Intv. [Intervenor Name] on the docket record
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Resp. & Petrs. [Petitioner(s) name(s)] & Intv. [Intervenor Name]



#### 4) Intervenor eFiles a document on a case; Selects Intervenor as the party filing the document; Document on the docket record indicates "Intv." followed by their name in the Filed by column.

Preconditions:
- Be sure that you also have an email that you have access to associated with one of the Petitioners on the case that you are going to use for this test.

Now the test is ready:
- Log in as an intervenor to a case
- Click on the docket number for a case on the My cases page
- Click File a Document
- Click Ok, I'm ready to File
- Select a document type and click Continue
- Upload a PDF
- Do not add any supporting documents at this time
- Be sure to select the Intervenor as the party filing the document
- Click Review Filing
- Ensure that the Parties Filing the Document(s) section indicates the filing party is the Intervenor
- Check the box indicating that you have redacted per Rule 27
- Click submit your filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Intv. [Intervenor Name] on the docket record
- [x] All other document metadata on the docket record remains unchanged and functions as normal
- [x] **NEW FUNCTIONALITY** - After clicking on the Print receipt, The Filed by text on the Receipt of Filing document indicates "Filed by Intv. [Intervenor Name]"
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intv. [Intervenor Name]


#### 5) Service emails from filings indicate file by Intervenor appropriately.

- Continuing from the test above
- Navigate to your email that you have associated with a petitioner from the previous test case
- Open the eService Notification for the filing that you made in the previous test

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Filed by value in the service email indicates "Intv. [Intervenor Name]"



#### 6) Private Practitioner that represents an Intervenor eFiles a document on a case; Selects Intervenor as the party filing the document; Filed by information reflects Intv. appropriately.

- Continuing from the previous test
- Click on the File a Document button
- Upload a document and fill out the required fields
- Click Submit filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates "Intv. [Intervenor Name]" on the docket record
- [x] All other document metadata on the docket record remains unchanged and functions as normal
- [x] **NEW FUNCTIONALITY** - After clicking the print receipt, the document title in the Documents filed section displays "Intv. [Intervenor Name]"
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intv. [Intervenor Name]


#### 7) Intervenor adds supporting documents to their filing - Filed by is "Intv. [Intervenor Name]" for each supporting document

- Log in as an intervenor to a case
- Click on the docket number for a case on the My cases page
- Click File a Document
- Click Ok, I'm ready to File
- Select a document type and click Continue
- Upload a PDF
- Be sure to add multiple supporting documents
- Be sure to select the Intervenor as the party filing the document
- Click Review Filing
- Ensure that the Parties Filing the Document(s) section indicates the filing party is the Intervenor
- Check the box indicating that you have redacted per Rule 27
- Click submit your filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Intv. [Intervenor Name] on the docket record for EACH document filed
- [x] All other document metadata on the docket record remains unchanged and functions as normal for each filing
- [x] **NEW FUNCTIONALITY** - After clicking on the print receipt, the Filed by displayed on the print receipt document indicates "Filed by Intv. [Intervenor Name]"
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intv. [Intervenor Name]
- [x] **NEW FUNCTIONALITY** - The Filed by value in the service emails indicates "Intv. [Intervenor Name]"

*Be sure to also do similar tests where Intervenor files a Motion for Leave to file and a Motion for leave to file out of time. Be sure that the lodged document indicates that it was Filed by "Intv. [Intervenor Name]"
- [x] This test Passes

*Repeat this test with a Private Practitioner filing on behalf of an intervenor
- [ ] This test Passes



#### 8) Party on a case files a document and selects multiple parties filing the document, including the Intervenor; Filed by value includes appropriate acronyms for all parties that filed.

- Log in as a party on a case that also has an intervenor on the case
- Click on the docket number for a case on the My cases page
- Click File a Document
- Click Ok, I'm ready to File
- Select a document type and click Continue
- Upload a PDF
- Do not add any supporting documents at this time
- Be sure to select the Intervenor AND all of the other parties as the parties filing the document
- Click Review Filing
- Ensure that the Parties Filing the Document(s) section indicates the filing party is the Intervenor + all other parties
- Check the box indicating that you have redacted per Rule 27
- Click submit your filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] on the docket record
- [x] All other document metadata on the docket record remains unchanged and functions as normal
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name]
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name]
- [x] **NEW FUNCTIONALITY** - The Filed by value in the service emails indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name]

*Repeat this test by logging in as different parties on the case (Petitioner, Respondent, Intervenor) and ensure that the Filed by is reflected appropriately.
- [x] This test Passes

*Repeat this test by adding a paper filing as a docket clerk
- [x] This test Passes



#### 9) Party on a case files a document and selects multiple parties filing the document but not all, including the Intervenor; Filed by value includes appropriate acronyms for all parties that filed.

- Log in as an intervenor to a case
- Click on the docket number for a case on the My cases page
- Click File a Document
- Click Ok, I'm ready to File
- Select a document type and click Continue
- Upload a PDF
- Do not add any supporting documents at this time
- Be sure to select the Intervenor AND at least one other party as the parties filing the document. Leave either a respondent or petitioner unselected.
- Click Review Filing
- Ensure that the Parties Filing the Document(s) section indicates the filing party is the Intervenor + the party you selected
- Check the box indicating that you have redacted per Rule 27
- Click submit your filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Petr(s). [Petitioner Name(s)] & Intv. [Intervenor Name] on the docket record or Resp. & Intv. [Intervenor Name] depending on which parties you selected.
- [x] All other document metadata on the docket record remains unchanged and functions as normal
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates the parties you selected appropriately
- [x] **NEW FUNCTIONALITY** - The Filed by value in the service emails indicates the parties you selected appropriately

*Repeat this test by selecting different parties, and always leaving someone off.
- [x] This test Passes

*Repeat this test by logging in as different parties on the case (Petitioner, Respondent, Intervenor) and ensure that the Filed by is reflected appropriately.
- [x] This test Passes



#### 10) Intervenor associated with a case in a consolidated group files a document across the group; Selects Intervenor as the party filing the document; Document on each cases docket record indicates "Intv." followed by their name in the Filed by column.

- Log in as an intervenor that is associated with a case in a consolidated group
- Click on the docket number for the case on the My cases page
- Click File a Document
- Click Ok, I'm ready to File
- Select a document type and click Continue
- Upload a PDF
- Do not add any supporting documents at this time
- Be sure to select the Intervenor as the party filing the document
- Select the All in the Consolidated group radio button
- Click Review Filing
- Ensure that the Parties Filing the Document(s) section indicates the filing party is the Intervenor
- Check the box indicating that you have redacted per Rule 27
- Click submit your filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Intv. [Intervenor Name] on the docket record of each case in the group
- [x] All other document metadata on the docket record of each case in the group remains unchanged and functions as normal
- [x] **NEW FUNCTIONALITY** - After clicking on the Print receipt, The Filed by text on the Receipt of Filing document indicates "Filed by Intv. [Intervenor Name]"
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intv. [Intervenor Name] on each case in the group
- [x] **NEW FUNCTIONALITY** - The Filed by value in the service emails indicates "Intv. [Intervenor Name]"

*Repeat this test by also filing supporting documents across a group
- [x] This test passes

*Repeat this test by selecting multiple parties that are filing across the group
- [x] **NEW FUNCTIONALITY** - The Filed by value indicates the parties you selected appropriately



#### 11) Private Practitioner that represents an Intervenor that is associated with a case in a consolidated group files a document across the group; Selects Intervenor as the party filing the document; Document on each cases docket record indicates "Intv." followed by their name in the Filed by column.

- Log in as a Private Practitioner that represents an intervenor that is associated with a case in a consolidated group
- Click on the docket number for the case on the My cases page
- Click File a Document
- Click Ok, I'm ready to File
- Select a document type and click Continue
- Upload a PDF
- Do not add any supporting documents at this time
- Be sure to select the Intervenor as the party filing the document
- Select the All in the Consolidated group radio button
- Click Review Filing
- Ensure that the Parties Filing the Document(s) section indicates the filing party is the Intervenor
- Check the box indicating that you have redacted per Rule 27
- Click submit your filing

Expected Results:
- [x] Green confirmation banner with a print receipt link
- [x] **NEW FUNCTIONALITY** - The Filed by column indicates Intv. [Intervenor Name] on the docket record of each case in the group
- [x] All other document metadata on the docket record of each case in the group remains unchanged and functions as normal
- [x] **NEW FUNCTIONALITY** - After clicking on the Print receipt, The Filed by text on the Receipt of Filing document indicates "Filed by Intv. [Intervenor Name]"
- [x] **NEW FUNCTIONALITY** - The Filed by column on the printable docket record indicates Intv. [Intervenor Name] on each case in the group
- [x] **NEW FUNCTIONALITY** - The Filed by value in the service emails indicates "Intv. [Intervenor Name]"

*Repeat this test by also filing supporting documents across a group
- [x] This test passes

*Repeat this test by selecting multiple parties that are filing across the group
- [x] **NEW FUNCTIONALITY** - The Filed by value indicates the parties you selected appropriately



#### 12) Docket Clerk accesses the Document QC Page to review filings from the above test cases; Filed by value on the Document QC views reflect Intervenor appropriately.

- Log in as a docket clerk
- Click on Document QC
- Click on Section Document QC
- Scroll down the list until you find the filings that you made in the previous test cases

Expected Results:
- [x] **NEW FUNCTIONALITY** - For filings where it was only the intervenor filing the document, the Filed by column indicates Intv. [Intervenor Name] on the Document QC inbox
- [x] **NEW FUNCTIONALITY** - For filings where there were multiple parties selected as the filing party, the filed by column indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] (or other appropriate combinations)
~~- [ ] **NEW FUNCTIONALITY** - For filings where there were multiple intervenors filing the document, the Filed by column indicates Intvs. [Intervenor 1 Name & Intervenor 2 Name]~~
- [x] **NEW FUNCTIONALITY** - For filings that were made across a consolidated group, the Filed by column for each document filed simultaneously is labeled appropriately. (Intervenor only, multiple parties, etc.)



#### 13) Docket Clerk selects a document to QC, Filed by value is reflected appropriately

- Continuing from the previous test case
- Click on the Document name for one of the documents that you filed in the previous test cases

Expected Results:
- [x] **NEW FUNCTIONALITY** - For filings where it was only the intervenor filing the document, The Filed by on the top left of the Document QC page indicates Intv. [Intervenor Name]
- [x] **NEW FUNCTIONALITY** - For filings where it was only the intervenor filing the document, The Filed by text box on the left side of the document QC page indicates Intv. [Intervenor Name]. This field can be edited.
- [x] **NEW FUNCTIONALITY** - For filings where there were multiple parties selected as the filing party, The Filed by on the top left of the Document QC page Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] (or other appropriate combinations)
- [x] **NEW FUNCTIONALITY** - For filings where there were multiple parties selected as the filing party, The Filed by text box on the left side of the document QC page indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] (or other appropriate combinations). This field can be edited.
~~- [ ] **NEW FUNCTIONALITY** - For filings where there were multiple intervenors filing the document, the Filed by on the top left of the Document QC page indicates Intvs. [Intervenor 1 Name & Intervenor 2 Name]~~
~~- [ ] **NEW FUNCTIONALITY** - For filings where there were multiple intervenors filing the document, the Filed by text box on the left side of the document QC page indicates Intvs. [Intervenor 1 Name & Intervenor 2 Name]. This field can be edited.~~
- [x] **NEW FUNCTIONALITY** - For filings that were made across a consolidated group, the Filed by on the top left of the Document QC page indicates Intv. [Intervenor Name] for each case's Document QC page. 
- [x] **NEW FUNCTIONALITY** - For filings that were made across a consolidated group, the Filed by text box on the left side of the document QC page indicates Intv. [Intervenor Name] for each case's Document QC page. This field can be edited.



#### 14) Docket Clerk completes the QC, Filed by value on the Document QC Views reflect Intervenor appropriately.

- Continuing from the previous test
- Click Complete or Complete and Send Message
- Click on the Processed tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - For filings where it was only the intervenor filing the document, the Filed by column indicates Intv. [Intervenor Name] on the Document QC inbox
- [x] **NEW FUNCTIONALITY** - For filings where there were multiple parties selected as the filing party, the filed by column indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] (or other appropriate combinations)
~~- [ ] **NEW FUNCTIONALITY** - For filings where there were multiple intervenors filing the document, the Filed by column indicates Intvs. [Intervenor 1 Name & Intervenor 2 Name]~~
- [x] **NEW FUNCTIONALITY** - For filings that were made across a consolidated group, the Filed by column for each document filed simultaneously is labeled appropriately. (Intervenor only, multiple parties, etc.)



#### 15) Court user accesses the document view for a document that was filed by an intervenor, Filed by at the top of the page is reflected appropriately.

- Log in as any Court user
- Access one of the cases from above where an intervenor/Practitioner filed a document and included an intervenor as a filing party
- Click on a document where an intervenor is listed in the Filed by column.

Expected Results:
- [x] **NEW FUNCTIONALITY** - For filings where it was only the intervenor filing the document, the Filed by at the top of the Document View indicates Intv. [Intervenor Name] on the Document QC inbox
- [x] **NEW FUNCTIONALITY** - For filings where there were multiple parties selected as the filing party, the filed by at the top of the Document View indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] (or other appropriate combinations)
~~- [ ] **NEW FUNCTIONALITY** - For filings where there were multiple intervenors filing the document, the Filed by at the top of the Document View indicates Intvs. [Intervenor 1 Name & Intervenor 2 Name]~~
- [x] **NEW FUNCTIONALITY** - For filings that were made across a consolidated group, the Filed by at the top of the Document View for each document filed simultaneously is labeled appropriately. (Intervenor only, multiple parties, etc.)



#### 16) Court User accesses the Pending Report tab from the Tracked Items Tab; Filed by for intervenors is reflected appropriately

- Log in as any Court User
- Access one of the cases from above where an intervenor/Practitioner filed a document (Motion/Proposed Stip) and included an intervenor as a filing party
- Click on the Tracked Items tab
- Click on the Pending Report Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - For filings where it was only the intervenor filing the document with the pending item, the Filed by column indicates Intv. [Intervenor Name] on the Document QC inbox
- [x] **NEW FUNCTIONALITY** - For filings where there were multiple parties selected as the filing party, the filed by column indicates Resp. & Petrs. [Petitioner Name(s)] & Intv. [Intervenor Name] (or other appropriate combinations)
~~- [ ] **NEW FUNCTIONALITY** - For filings where there were multiple intervenors filing the document, the Filed by column indicates Intvs. [Intervenor 1 Name & Intervenor 2 Name]~~
- [x] **NEW FUNCTIONALITY** - For filings that were made across a consolidated group, the Filed by column for each document filed simultaneously is labeled appropriately. (Intervenor only, multiple parties, etc.)



#### 17) Public user accesses DAWSON on a mobile device; Filed by information reflects Intervenor appropriately 

- This test is just to ensure that the Intervenor information from the test cases above look appropriate on a mobile device.

Expected Results:
- [x] Tests Cases above for public users look fine on mobile.

**Comment by ttlenard** [comment]
@nechama-krigsman All test cases pass.  Passing this one over to @cholly75 so that he can have some folks at the Court do a bit of review as well.
