### ISSUE TITLE
Case Search: Search Filter Updates

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8513]
As someone searching for a specific case, so that I have more control over my search parameters and can more easily find international cases, I need the Country filter on Case Search to be optional.

Currently when searching for a case, we default the Country filter to "United States". This ends up having the effect of obscuring cases from search results for those cases where a petitioner's filing address is designated as outside of the U.S. We have received multiple support tickets and internal inquiries about "missing" cases from the Case Search, requiring education about how the Country filter works and operates in this context. As this filter is required (there is no option to de-select the Country filter entirely), this serves more to hide those "international" cases rather than filter out unwanted cases from the search results.

We would like to make this filter optional to let the user decide whether to make use of it or not, making those international cases searchable with the rest of the collection by default given the other search criteria entered. This change affects all DAWSON users.

## Acceptance Criteria
* Case Search no longer requires a "Country" value as a filter to execute
* "Country" filter on Case Search UI is defaulted to unselected (e.g., "-Select-" value used in State filter)
* "State" filter on Case Search UI is not shown until/unless "United States" is selected on the Country filter
* Searching with no Country value selected returns results from both domestic and international cases
* Country, State, Date filter UIs updated to indicate that they are optional filters
* Changes affect all users

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] Swagger docs have been updated if API endpoints have been added or updated.
 - [ ] UI should be touch optimized and responsive for external users.
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [ ] Types have been added to all added and updated functions.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5

**Comment by swongCO** [comment]
**UX Notes**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1RhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb95d18d1a27da80363b6623a347c873f8ed5fbe/Search%20-%20all%20locations.png)

- Change country dropdown selector to radion btns
- 3 selections: All (default), United States, International 
___
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2ZhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d95b2a8366e195f82d80395ebeb8e7d6fb475ab8/Search%20-%20us%20locations.png)

- When United States is selected, display States dropdown selector
- Rename to "State/Territory"
___
Mobile views:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckRhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30fccb37af6041703b1a4fc5072b35dc4a1b5f56/Search%20-%20all%20locations_mobile.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckxhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c0a9f2b89b535ec9f9c149b2928b0938cabda07b/Search%20-%20us%20locations_mobile.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Public Non-logged in user accesses the DAWSON Case Search page, Country options are now displayed as radio buttons.

- Navigate to the DAWSON Case search page
- Review the Search by Name section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Country section has 3 radio buttons, with All selected by default
- [x] **NEW FUNCTIONALITY** - User may check any 1 radio button, does not allow for multi-select
- [x] **NEW FUNCTIONALITY** - When United States is selected, the State/Territory Dropdown is displayed with "-Select-" as the default
- [x] **NEW FUNCTIONALITY** - When International is selected, there is no State/Territory dropdown menu displayed for the user.



#### 2) Practitioner accesses the DAWSON Case Search Page, Country options are now displayed as radio buttons.

- Log in as a Private Practitioner
- Click on the Advanced link in the upper right corner of the screen
- Review the Search by Name section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Country section has 3 radio buttons, with All selected by default
- [x] **NEW FUNCTIONALITY** - User may check any 1 radio button, does not allow for multi-select
- [x] **NEW FUNCTIONALITY** - When United States is selected, the State/Territory Dropdown is displayed with "-Select-" as the default
- [x] **NEW FUNCTIONALITY** - When International is selected, there is no State/Territory dropdown menu displayed for the user.

*Repeat this test as an IRS Practitioner
- [x] This test Passes.



#### 3) Public terminal user accesses the DAWSON Case Search Page; Country options are now displayed as radio buttons.

- Be sure that you have your IP address listed in the allowed Terminal user in dynamo
- Go to the DAWSON homepage
- Review the Search by Name section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Country section has 3 radio buttons, with All selected by default
- [x] **NEW FUNCTIONALITY** - User may check any 1 radio button, does not allow for multi-select
- [x] **NEW FUNCTIONALITY** - When United States is selected, the State/Territory Dropdown is displayed with "-Select-" as the default
- [x] **NEW FUNCTIONALITY** - When International is selected, there is no State/Territory dropdown menu displayed for the user.



#### 4) Court User accesses the DAWSON Case Search Page, Country options are now displayed as radio buttons

- Log in as a Court User
- Click on the Advanced link in the upper right corner of the screen
- Review the Search by Name section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Country section has 3 radio buttons, with All selected by default
- [x] **NEW FUNCTIONALITY** - User may check any 1 radio button, does not allow for multi-select
- [x] **NEW FUNCTIONALITY** - When United States is selected, the State/Territory Dropdown is displayed with "-Select-" as the default
- [x] **NEW FUNCTIONALITY** - When International is selected, there is no State/Territory dropdown menu displayed for the user.


#### 5) Public Non-Logged in User accesses the DAWSON Case Search page; Leaves the default Country to All, Searches for a Petitioner last name that has results for both US and International (Smith), Results for US and International are displayed.

- Navigate to the DAWSON Case Search page
- Type in Smith in the Petitioner Name field
- Leave the Country radio button as the default (All)
- Input 04/21/2023 as the start date
- Input 04/22/2023 as the end date
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - Results list should display both US and International Filers with the last name Smith


#### 6) Public Non-Logged in User accesses the DAWSON Case Search page; Selects International radio button; Searches for a Petitioner last name that has results for both US and International (Smith), Results for International only are displayed.
 
- Continuing from the previous test
- Select the Country radio button for International
- Leave the rest of the filters the same as above
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - The result for the international petitioner is the only case in the results list. There are no results for US.



#### 7) Public Non-Logged in User accesses the DAWSON Case Search page; Selects United States radio button; Searches for a Petitioner last name that has results for both US and International (Smith), Results for US only are displayed.
 
- Continuing from the previous test
- Select the Country radio button for United States (leave the State/Territory option blank)
- Leave the rest of the filters the same as above
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - The result for the US petitioner is the only case in the results list. There are no results for International.
- [x] When filtering by state, if a different state than the one that the petitioner lives in is selected, the results go to 0.
- [x] When filtering by state, if the state that the US petitioner lives in is selected, the results list displays the US Petitioner.



#### 8) Repeat the tests 5-7 with the following users:

- [x] Private Practitioner
- [x] IRS Practitioner
- [x] Terminal User
- [x] Court User

 
#### 9) Docket Clerk seals a Case with a Petitioner that has a US address; Public Non-logged in users that search for the case do not see results.

- Log in as a docket clerk
- Navigate to a case that has a Petitioner with a US address
- Click on Case information
- Click on Seal Case
- Take note of the Petitioner Name for the case, and when it was filed
- Log out
- Next, as a Public non-logged in user, access the DAWSON Case Search Page
- Type in the name of the Petitioner from above 
- Be sure you have All or US selected for the Country 
- Click search

Expected Results:
- [x] Sealed Case is not presented in the results list

*Repeat this test with the following public users:
- [x] Private Practitioner
- [x] IRS Practitioner
- [x] Terminal User


#### 10) Docket Clerk seals a Case with a Petitioner that has an International Address; Public Non-logged in users that search for the case do not see results.

- Log in as a docket clerk
- Navigate to a case that has a Petitioner with an International address
- Click on Case information
- Click on Seal Case
- Take note of the Petitioner Name for the case, and when it was filed
- Log out
- Next, as a Public non-logged in user, access the DAWSON Case Search Page
- Type in the name of the Petitioner from above 
- Be sure you have All or US selected for the Country 
- Click search

Expected Results:
- [x] Sealed Case is not presented in the results list


*Repeat this test with the following public users:
- [x] Private Practitioner
- [x] IRS Practitioner
- [x] Terminal User


#### 11) Court user searches for a Sealed Case that has a Petitioner with a US address; Results are populated in the Results list

- Log in as a Court User
- Click on the Advanced link in the upper right corner
- Type in the Petitioner name that you used in Test case 9
- Be sure you have All or US selected for the Country 
- Click search

Expected Results:
- [x] Sealed Case is available in the results list ~~and has a sealed case icon next to the docket number~~

*Repeat this test with the International Petitioner from test case 10
- [x] Sealed Case is available in the results list ~~and has a sealed case icon next to the docket number~~



#### 12) Test to be sure that the new Country and State/Territory fields function and look ok on Mobile devices.

- [x] Tests 1-11 look and function appropriately on a mobile device

**Comment by ttlenard** [comment]
@Absolutestunna @codyseibert 

Testing looks good. Thanks!
