### ISSUE TITLE
FLAKY TEST: `court-issued-documents.cy.ts`

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8515]
## Path to Test File

```
cypress/cypress-smoketests/integration/court-issued-documents.cy.ts
```

## Readout of the failure

```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  case-creation.cy.ts                      01:02       11       11        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  change-address.cy.ts                     00:08        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  court-issued-documents.cy.ts             04:38       16       13        3        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  create-trial-session.cy.ts               02:06       27       27        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  search.cy.ts                             00:58       11       11        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user-post-authentication.cy.ts            82ms        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 6 failed (17%)                      08:54       70       67        3        -        -  
```

Where the test fails:

```
 Running:  court-issued-documents.cy.ts                                                    (3 of 6)


  Petitioner
    ✓ should be able to login (4335ms)
    should be able to create a case
      ✓ should complete wizard step 1 (370ms)
      ✓ should go to wizard step 2 (181ms)
      ✓ should complete the form and submit the petition (9528ms)

  Petitions clerk
    ✓ should be able to login (5403ms)
    ✓ should be able to create a case with paper service (18185ms)
    1) should be able to serve the petition on the electronically-filed case
```

## Workflows of Failrure(s)

* [Github Action](https://github.com/ustaxcourt/ef-cms/actions/runs/6304210259/job/17115082645?pr=4003)

## What were you working on?

Making a PR

## Notes

So, it looks like the test fails because it tries to show the STIN in the document viewer. This should never happen. If it had shown the Petition, it would have likely passed. 

![Screenshot 2023-09-25 at 4 51 03 PM](https://github.com/ustaxcourt/ef-cms/assets/5023502/b0a96644-7c1f-4eec-bf61-337cbea1ba6a)

Perhaps something strange is in the Action that sets up the UI???

## Definition of Done (Updated 4-14-21)

**Engineering**

- [ ] Documentation has been added to this card with any helpful information relating to the test failures.
- [ ] Test has been fixed or removed.
- [ ] Test has been reattempted 5 times without fail.

**Comment by mmarcotte** [comment]
This occurred [over here](https://github.com/ustaxcourt/ef-cms/actions/runs/6394513569/attempts/1?pr=3987) in [this PR](https://github.com/ustaxcourt/ef-cms/pull/3987).

**Comment by mmarcotte** [comment]
This occurred [over here](https://github.com/ustaxcourt/ef-cms/actions/runs/6435132455/job/17475761641?pr=4030) in [this PR](https://github.com/ustaxcourt/ef-cms/pull/4030), but a different test!

**Comment by TomElliottFlexion** [comment]
Fix PR with a little explanation: https://github.com/ustaxcourt/ef-cms/pull/4079

**Comment by mmarcotte** [comment]
https://github.com/ustaxcourt/ef-cms/actions/runs/6577141653/job/17868121442 

bummer this seemed to have happened again over here...
