### ISSUE TITLE
New Case Status: Submitted - Rule 122

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8516]
As a judge, so that I can prioritize cases for work and reassignment, I need a new case status in DAWSON titled "Submitted - Rule 122".

Currently a case is given a Submitted status in DAWSON when it is ready for a judge to issue a decision and/or opinion. However, there is a subset of cases that fall under Rule 122, which deems that a case may be submitted for decision without requiring a trial. These cases are often good candidates for reassignment to another judge, as they don't require contextual information from a trial to inform the decision/opinion. Being able to distinguish cases that have been submitted under Rule 122 from cases that have been submitted post-trial would be very helpful in allowing the Court to manage its caseload.

We would like a new case status value of "Submitted - Rule 122" to be created. This status would be available to assign to a case like any other, and display as such anywhere we currently display Case Status information. Additionally, cases with the status of "Submitted - Rule 122" would be captured on the Activity report and the judge/CA dashboard under "Submitted/CAV Cases". We do not need to modify any current case data to reflect the new status - the Court will change these as needed for cases as appropriate.

## Acceptance Criteria
* New value "Submitted - Rule 122" is added to the list of available Case Status options anywhere Case Status can be assigned/selected/viewed (case data, reports, etc.)
* When a case is assigned the status of "Submitted - Rule 122" it is captured on the Activity report in the same manner as a case with the status of "Submitted"
* When a case is assigned the status of "Submitted - Rule 122" it is captured on the Submitted/CAV Cases portion of the appropriate judge/CA dashboard

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Clerk manually updates the Case Status for a case; "Submitted - Rule 122" is available to select

- Log in as a Docket clerk 
- Navigate to a case
- Click on the Case Information tab
- Click on the link to "Edit Case Status/Caption"
- Click on the Case Status dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - The new Case status for "Submitted - Rule 122" is available to select. 
- [x] **NEW FUNCTIONALITY** - The Submitted - Rule 122 status is displayed below Submitted in the dropdown

*Repeat this test with CotC and CSS roles



#### 2) Case Status Label for "Submitted - Rule 122" is displayed on the Case Header and in the JSON

- Continuing from the previous test
- Select "Submitted - Rule 122" from the dropdown and assign a judge user
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case Status header now displays "Submitted - Rule 122"
- [x] **NEW FUNCTIONALITY** - When viewing the Case JSON, the Case status displays "Submitted - Rule 122"



#### 3) Case status on the Case Information/History Tab displays Cases in Submitted - Rule 122 status appropriately

- Continuing from the previous test
- Click on the Case information tab
- Click on the History tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case in the Submitted - Rule 122 status is present in the Case Status column in the Case Status table on the History tab



#### 4) Judge User runs an Activity Report, cases assigned to the judge with a status of "Submitted - Rule 122" display in the report results

- Log in as the Judge user that you just assigned the Submitted - Rule 122 case to in the above test case
- Click on the Reports menu
- Select Activity Report
- Input valid dates, leave the default judge user
- Click Run Report
- Review the results in the Submitted/CAV Cases section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case in the Submitted - Rule 122 status is present in the results list

*Repeat this test with a Chambers User



#### 5) Judge User accesses their Dashboard, cases assigned to the Judge with a status of "Submitted - Rule 122" display in the Submitted/CAV Cases section of their dashboard

- Continuing from the previous test
- Click on the Dashboard tab
- Scroll down and review the Submitted/CAV Cases section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case(s) in the Submitted - Rule 122 status is present in the Submitted/CAV Cases Section
- [x] **NEW FUNCTIONALITY** - User is able to click the edit link and add/edit data in the Edit Details pop-up modal for the Submitted - Rule 122 Case.

*Repeat this test with a Chambers User



#### 6) Court User runs a Case Inventory report, selects Case Status dropdown filter; new "Submitted - Rule 122" status is available in the dropdown picklist.

- Court User clicks on the Reports Header
- Select Case Inventory Report
- The Run Case Inventory Report modal will display
- Click on the dropdown for Select Case Status

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Submitted - Rule 122" case status is present in the picklist.
- [x] **NEW FUNCTIONALITY** - After selecting Submitted - Rule 122, all cases in this status display in the report results.
- [x] **NEW FUNCTIONALITY** - Printable report displays case status appropriately



#### 7) Court User runs a custom case report, selects Case Status dropdown filter; new "Submitted - Rule 122" status is available in the dropdown picklist.

- Court User clicks on the Reports Header
- Select Custom Case Report
- Select valid Case Created start/end dates
- Click on the dropdown for Select Case Status

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Submitted - Rule 122" case status is present in the picklist.
- [x] **NEW FUNCTIONALITY** - After selecting Submitted - Rule 122 and running the report, all cases in this status display in the report results.



#### 8) Court User runs a Blocked Cases report, Blocked cases with a status of "Submitted - Rule 122" display in the report results

- Court User clicks on the Reports Header
- Click Blocked cases
- Select Trial Location that has a case in Submitted - Rule 122 status
- Review the results

Expected Results:
- [x] **NEW FUNCTIONALITY** - Cases with a status of "Submitted - Rule 122" are present in the results list.



#### 9) Court User runs a Pending report, Cases with a pending item with a case status of "Submitted - Rule 122" display in the report results

- Court User clicks on the Reports Header
- Select Pending Report
- Select a Judge that has a case(s) that is in Submitted - Rule 122 status
- Review the results

Expected Results:
- [x] **NEW FUNCTIONALITY** - Cases with a status of "Submitted - Rule 122" are present in the results list.
- [x] **NEW FUNCTIONALITY** - Printable report displays case status appropriately



#### 10) Judge's Recent Messages on their dashboard display cases in Submitted - Rule 122 status appropriately

- Log in as a Judge User
- Review the Recent Messages on your dashboard

Expected Results:
- [x] **NEW FUNCTIONALITY** - Cases with a status of "Submitted - Rule 122" are displayed appropriately in the recent messages table.

*Repeat this with a CA


#### 11) Court users messages display cases in Submitted - Rule 122 Status appropriately

- Log in as any Court User 
- Review the messages tab

Expected Results:
- **NEW FUNCTIONALITY** - Cases with a status of "Submitted - Rule 122" are displayed appropriately in the following locations:
     - [x] My Messages Inbox view 
     - [x] My Messages Sent view
     - [x] Section Messages Inbox view
     - [x] Section Messages Sent view
- [x] This test passes with all court user roles
     - [x] Docket Clerk
     - [x] Petitions Clerk
     - [x] Case Services Supervisor
     - [x] Clerk of the Court
     - [x] Chambers
     - [x] Trial Clerk
     - [x] Admissions Clerk
     - [x] Judge
     - [x] Floater
     - [x] ADC
     - [x] Reporters Office


#### 12) Court users Document QC displays cases in Submitted - Rule 122 Status appropriately

- Log in as a docket clerk
- Review the Document QC tab

Expected Results:
- **NEW FUNCTIONALITY** - Cases with a status of "Submitted - Rule 122" are displayed appropriately in the following locations:
     - [x] My Document QC Inbox view 
     - [x] My Document QC Processed view
     - [x] Section Document QC Inbox view
     - [x] Section Document QC Processed view
- [x] This test passes with all court user roles (not all user roles will have in progress/completed/served tabs)
     - [x] Docket Clerk
     - [x] Petitions Clerk
     - [x] Case Services Supervisor
     - [x] Clerk of the Court
     - [x] Chambers
     - [x] Trial Clerk
     - [x] Admissions Clerk
     - [x] Judge
     - [x] Floater
     - [x] ADC
     - [x] Reporters Office
