### ISSUE TITLE
Pending Report: Display Date/Location of Calendared Items

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8526]
As a CA or judge, so that I can quickly prioritize my pending items for cases that have been calendared, I need pending items associated with a case in Calendared status to display the date and location of the trial session on the Pending Report.

Earlier this year we implemented changes to make messages and QC items associated with Calendared cases more informative to the user by displaying the date and location of the trial session for the case alongside its Calendared status. We would like to extend this behavior to the Pending Report display.

## Acceptance Criteria
* Items on the Pending Report with a Case Status of "Calendared" now display the date and location of the trial session for which the case is calendared

## Notes
* Can we also make the small change to include the suffix letter designation to the screen version of the report (it's already on the printed version, so we're just removing an inconsistency between the two)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement
- Feels a bit prescriptive, suggestion for user story: As a CA or Judge, so that calendared cases are prepared for trial, I need to know when they have pending items outstanding.
- ux add a mock

**Comment by katiecissell** [comment]
UX Notes:
Follow the pattern set by Document QC and Messages
Screenshot of doc QC
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67adb144d20ed5c8258a7a4fac3ad967fb06a9b7/image.png)


Mock up of pending report with date and location added
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48f3bc122b8f2566d158c439f1d8c5e80ec16adf/image.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Pending report; Cases that are in Calendared Status display the date and place of trial.

- Log in as any court user
- Click on the reports menu and select Pending Report
- Select a Judge user 

Expected Results:
- [x] **NEW FUNCTIONALITY** - Cases in Calendared status now display the Date and Place of trial in a consistent manner as we do in other locations in the system (See UX Notes)

*Repeat this test with other Court Users
*Repeat this test by viewing other Judges Pending items in the Dropdown to ensure consistency

**Added Test Case 2 on 11/14/2023 as discussed in standup**

#### 2) Court User accesses the Pending Report; Cases now display the appropriate Suffix with the Docket number.

- Continuing from the previous test
- Review the docket number link for each case in the results list

Expected Results;
- [x] **NEW FUNCTIONALITY** - Docket number links in the results list now display the appropriate suffix.
- [x] **NEW FUNCTIONALITY** - Docket number suffix on the UI version of the pending report matches the printed report (printed report already had the suffix displayed, it was only on the UI where it was missing).

*Repeat this test with other Court Users
*Repeat this test by viewing other Judges Pending items in the Dropdown to ensure consistency

**Comment by swongCO** [comment]
**UX review**
Remove "undefined" when a session is standalone remote to follow what is displayed in Messages and QC:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFh2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--966337be7f64d0c0287a5748ac320cd74b04acf0/Screenshot%202023-11-20%20at%209.19.39%E2%80%AFAM.png)
