### ISSUE TITLE
BUG: Incorrect Error message appears if a Petitions Clerk clicks create case before all required fields have been completed.

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8533]
**Describe the Bug**
The UX crew found a bug while testing other stories.  As a petitions clerk, if you are entering a paper petition and click the Create Case before all of the required fields on the IRS notice tab have been completed, you get validation errors (this is normal).  But there appears to be an incorrect Validation error message that appears for the IRS notice information after you click the Calculate Penalties on IRS notice link.  Tom had mentioned that it isn't a front-end validation error, but rather a back-end error message that shouldn't be displayed for the user (Tom - please confirm this!).

The only time you receive this error, is if you click create case prematurely and there are other validation errors for the IRS notice tab (Enter case type).

If you simply click create case a second time, the "back-end" validation error disappears and you can create the case with no issue.
If you go through the flow and don't have any validation errors, then then the error message does not appear.

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Test and Staging, so it's most likely happening in production too.

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**
1. Log in as a Petitions Clerk
2. Click on Document QC
3. Click on Start a Petition
4. Upload a Petition and fill in the required fields on the Parties tab and on the Case info tab.
6. Do NOT fill out any of the data on the IRS notice tab
7. Click Create Case
8. You will receive a validation error that you need to input a case type
9. Fill out the required fields on the IRS notice tab, and be sure to select "Yes" that an IRS notice was provided and Deficiency as the case type.
10. As you start to enter in the year and total Deficiency amount, notice that the error message above switches to state, "Statistics ustaxcourt/ef-cms#6491 - Enter year, deficiency amount, and total penalties"
11. Next, click on the Calculate Penalties on IRS notice link and input one or more penalties.
12. Click Calculate and Save
13. Now notice that the error message changes and states: 
 - Enter deficiency on IRS Notice.
 - Use IRS Penalty Calculator to calculate total penalties.
 - "yearOrPeriod" is required
14. Petitions clerk can just click Create Case again and the Petition can submit just fine, but this error message should not be displayed.

**Expected Behavior**
The error message that is in step 10 above should be the only error message displayed

**Actual Behavior**
A clear and concise description of what actually happened.
An unusual error message is displayed if the user clicks on the calculate penalties on IRS notice link.

**Screenshots**
![image](https://user-images.githubusercontent.com/87717140/222742427-27000f78-f288-484c-a9da-3e61a3d38cab.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by swongCO** [comment]
**UX Review feedback**
Found more messaging issues:
1. IRS Notice tab - enter Deficiency or Total penalties first
2. Click Create Case/Review Petition
3. Note the two errors at top to upload petition and RQT, both of which were already uploaded

Screenshots:

![Screenshot 2023-03-06 at 11.18.22 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d2dd09e8-b987-4a22-bd5b-86ccab8403f7)

![Screenshot 2023-03-06 at 11.18.34 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d4623a97-0af2-4969-9846-b71e6411e949)

Recording of reproduction steps:

https://images.zenhubusercontent.com/152320868/1785b6b3-2991-4081-a98e-3cd47e393212/video1868337309.mp4

**Comment by rosiehsmith** [comment]
Steps to reproduce bug in the above video:
1. Go to a edit a petition on a created case, case type deficiency with an IRS Notice provided
2. Add a penalty (without filling out year or deficiency)
3. Click "Review Petition" - normal alert error just on Statistics displays
4. Add a deficiency to the same statistic (without filling out year)
5. Alert shows "Upload or scan a Petition" This should not be there. Also shows RQT error if the case has a requested trial location.

**Comment by ttlenard** [comment]
Testing Feedback @rosiehsmith Looks good!  I am no longer seeing the incorrect error message with the steps described in the bug.
