### ISSUE TITLE
Chambers: Remove Ability to Edit Trial Session

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8534]
As a calendar clerk, so that chambers admins do not cause confusion by editing details of a trial session, I need CA users to not have editing permissions for trial sessions.

Recently we have seen two instances where otherwise well-meaning CAs have taken it upon themselves to edit details of calendared trial sessions. This caused several points of confusion regarding resourcing of trial clerks and contact information for the judges' chambers information.

As per Court policy, only a few roles should be able to edit trial sessions. This story will address removing the ability for CA users.

## Acceptance Criteria
* On the trial session details screen, the Edit link is not present if the logged-in user has the role of Chambers.

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/6a743ceb-e192-46fb-a8ee-36193d6ef8d5)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (?standard testing?). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Chambers User navigates to a trial session; edit link is no longer available

- Log in as a chambers user
- Click on Trial Sessions 
- Click on the City/State link for a trial session that is in the future (from the Open and New tab)

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The edit link is no longer present for the Chambers user

*Be sure to test this with multiple trial sessions from the Open and New tab


#### 2) Other Court users navigate to a trial session; edit link is still present.

- Log in as all other Court users (Petitions Clerk, CotC, Docket, CSS, Judge, etc.)
- Click on Trial Sessions 
- Click on the City/State link for a trial session that is in the future

Expected Results:
- [ ] The edit link is still present and can be clicked
- [ ] Upon clicking on the link, the user can edit the trial session details.
