### ISSUE TITLE
BUG: The E-Service Consent Checkbox gets clicked when the user clicks to the right of the checkbox and label

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8536]
**Describe the Bug**
I was testing other functionality when I accidently clicked near the E-Service Consent checkbox and noticed that the checkbox got checked.   It looks like the checkbox and label take up the entirety of the blue-ish area and if you click to the right of it, for example, the checkbox gets checked.

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**
1. Log in as a Petitions Clerk
2. Click on Document QC
3. Click on Start a Petition
4. Start filling in the Petitioner information and scroll down to where the E-Service consent checkbox is
5. Move your cursor to the right of the E-Service Consent box and notice that it remains "active"
6. With your cursor to the right of the field, left click
7. Notice that the checkbox gets checked, even though you weren't on the checkbox or the label. 

**Expected Behavior**
The checkbox should only be checked if your cursor is over the checkbox or the label.

**Actual Behavior**
Clicking all the way to the right of the checkbox checks the checkbox.

**Screenshots**
Clicking your mouse way over here will check the box.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/b053dc99-bf32-477e-ac54-50cd7fa21e5d)

**Cause of Bug, If Known**
To conform to accessibility standards, clicking on a checkbox's label will have the same behavior as if the user selected the checkbox itself. The size of the label for a checkbox defaults to the size of its container (FormGroup in this case). The containing FormGroup had a width set to be equal to its container, which in this case is the whole form. Therefore, even though there wasn't visible text in the right hand half of the label, anywhere within the form in the same row as the label text was clickable.

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the ?Unable to reproduce? tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by rachelschneiderman** [comment]
https://github.com/ustaxcourt/ef-cms/pull/3298

**Comment by rachelschneiderman** [comment]
https://github.com/ustaxcourt/ef-cms/pull/3302
