### ISSUE TITLE
TCRP: Page Number Metadata

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8540]
As a viewer of the USTC report pamphlets, so that the pamphlet hosting page can accurately represent the page on which an opinion appears in the pamphlet, I need to be able to enter the page number of the opinion when filing the TCRP docket entry.

The planned process is to docket the Tax Court Report Pamphlets on the docket record for each case in which an opinion contained in the pamphlet was issued. To facilitate display on the pamphlet hosting page of the page number on which the opinion is located in the pamphlet, we want to indicate at the time of filing the pamphlet the page number on which the associated opinion appears on the pamphlet.

## Acceptance Criteria
* When adding a TCRP docket entry, the clerk can enter the Opinion starting page number in a field.
* The page number field is a required field for docketing the TCRP
* Acceptable values in the field are 1-4 numeric digits
* Value entered in the field is *not* displayed on the docket record for the TCRP
* Value entered in the field can be edited when the docket entry is edited

## Notes
- TODO: Add new field representing page number to `OpinionPamplets.jsx` (new view added as a part of [9865](https://github.com/flexion/ef-cms/issues/9865)). May need to add the field to `efcms-docket-entry-mappings.js` since `OpinionPamplets.jsx` is populated from Elasticsearch results: 
<img width="464" alt="image" src="https://user-images.githubusercontent.com/20514925/228606051-672b8337-0aa0-4c69-aa3c-08f75c03a0be.png">

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
New field added below description and above filed date, title is "Opinion starting page". Field only allows numerals to be entered. (like the deficiency field on IRS notice tab in petition flow). It is a required field, validation if it is not filled out should follow standard styling and say "Enter opinion starting page"
When the docket entry is being edited, the opinion starting page field should appear below description.
 ![Pamplet starting page.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/a6278233-bd31-4d64-8838-764b87a9ba10)![Pamplet starting page validation.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/b016daf9-1a91-4905-bc82-f7638f641a10)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk adds a TCRP document; option to enter an Opinion starting page number is available.

- Log in as a docket clerk
- Navigate to a case
- Click on the create button
- Select PDF Upload
- Upload a PDF and add a description
- Click Save
- Click Add Docket Entry from the document view page
- On the Add docket entry screen, for document type, select Tax Court Report pamphlet

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new field present titled "Opinion starting page".


#### 2) Docket Clerk adds in a valid page number in the Opinion starting page field; data is saved appropriately.

- Continuing from the previous test
- Input a description for the TCRP document
- Add in a valid page number (1-4 numeric digits)
- Input a filed date
- Click Save Entry

Expected Results:
- [ ] TCRP document saves appropriately on the docket record.
- [ ] Page number data is NOT displayed on the docket record.


#### 3) Docket Clerk edits a TCRP entry on the Docket Record; Clerk can edit the page number value.

- Continuing from the previous test
- Click on the edit link to the right of the TCRP docket entry on the docket record
- Ensure that the page number that you entered previously is still present in the Opinion starting page field.
- Change the page number to different value
- Click Save 

Expected Results:
- [ ] TCRP document saves appropriately on the docket record.
- [ ] Page number data is NOT displayed on the docket record.


#### 4) Docket clerk attempts to save the TCRP entry without inputting an Opinion starting page value; Receives validation error.

- Log in as a docket clerk
- Navigate to a case
- Click on the create button
- Select PDF Upload
- Upload a PDF and add a description
- Click Save
- Click Add Docket Entry from the document view page
- On the Add docket entry screen, for document type, select Tax Court Report pamphlet
- Input a description for the TCRP document
- Do not add any data in the Opinion starting page field (leave it blank!)
- Input a filed date
- Click Save Entry

Expected Results:
- [ ] Clerk receives a validation error message


#### 5) Docket clerk attempts to add an invalid page number, attempts to add text/symbol data to the Opinion starting page field; clerk receives a validation error message.

- Continuing from the previous test
- Attempt to add in an invalid page number (attempt to input more than 4 digits)
- Input a filed date
- Click Save Entry

Expected Results:
- [ ] Clerk receives a validation error message

*Repeat this test by attempting to input letters, decimal points, symbols, negative numbers etc.

**Comment by katiecissell** [comment]
@TomElliottFlexion  During UX review, found I could enter in the opinion starting page field the following characters: "e" "." and"-"  It won't let you save with it, but would be preferable to not allow those characters to be entered like all the other symbols/letters.

**Comment by cholly75** [comment]
Closing - will revisit at a later time
