### ISSUE TITLE
BUG: Docket Clerks get a spinning wheel of doom when attempting to edit an iteration type document that was QC'd prior to 3/26/23

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8549]
**Describe the Bug**
We have had a few reports from docket indicating that they are getting the spinning wheel of doom when attempting to edit an iteration type of document (strike, add an action, etc).  With testing, I see that the only time this is happening is if it is an iteration type of document that was QC'd prior to the 3/26/23 release.  

This is also happening with iteration type of documents that are secondary/tertiary type of documents.  Example: Motion for Leave to File First Amendment to Petition

I believe it may be that the old way of capturing the iteration value is not playing nice with the new way we maintain this data when a clerk attempts to edit the record.  (See screen shot of the error message received in the console. Uncaught RangeError))

It appears that a clerk can still seal these iteration documents just fine.
It appears that Docket clerks can complete QC on an iteration type of document that was submitted before the release, but they must input an iteration value. (This is fine!)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. log in as a docket clerk
2. Navigate to case that has an iteration type of document that was submitted and QC'd prior to the 3/26/23 release. (22264-22, 14887-22)
3. Click the Edit button
4. Get the spinning wheel of doom.

**Expected Behavior**
Clerks should be able to edit the iteration type of document.

**Actual Behavior**
A clear and concise description of what actually happened.
Clerks are unable to edit an iteration type document that was QC'd prior to 3/26/23 release

**Screenshots**

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/f49279a8-5a83-4136-a881-394bceca13b2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by cholly75** [comment]
Tested, closed and deployed to PROD 3/29
