### ISSUE TITLE
BUG: Session info page is not displaying open cases or the case count correctly after printing paper service

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8553]
**Describe the Bug**
When a clerk makes a change to a trial session that triggers a change (Notice of change of trial judge, Notice of change from in person to remote, 30-Day Notice of trial, etc.), the print for paper service screen appears. After they indicate that they are done with printing, DAWSON navigates them back to the session information page.  When they are navigated here, the Session info page indicates that there are no open cases on the session.  In order for the Clerk to see the open cases on the session, they have to Click on trial sessions menu and then come back into the session.  See screen grabs below for more details.

Thanks to Cody for spotting this initially with change of trial judge on a session!

**Business Impact/Reason for Severity**
med

**In which environment did you see this bug?**
Test (I did not see this happening in Staging)

**Who were you logged in as?**
Petitions clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**
1. Log in as a petitions clerk
2. Click on Trial Sessions
3. Click on the City, State link for an upcoming trial session
4. Click the edit button (or if this one has a 30 day notice ready to be served, serve it)
5. Update from in person to remote (or vice versa), or change the trial judge
6. Click done
7. On the print for paper service screen, click done (or printing complete)
8. You will be navigated back to the session info page for this session
9. Notice at the bottom of the screen that it is showing 0 cases and no open cases on the trial session.

**Expected Behavior**
When a clerk is navigated back to the trial session after the print for paper service screen, they should see all the open cases on the session info page

**Actual Behavior**
A clear and concise description of what actually happened.
When a clerk is navigated back to the trial session after the print for paper service screen, they are seeing it say that there are no open cases on the session.

**Screenshots**
This screen grab is what it looks like after I generated a 30 day notice of trial and clicked printing complete.  When I was navigated back to the session info page, it showed 0 cases.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9aff751f87558827fac0ba7626d8654643e663aa/image.png)

This screen grab is what it looks like after I refreshed and came back to the trial session. Notice that this session has 52 open cases.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--360420795c62c0d5999b0b8f09f1dc0f04b8abd6/image.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by pixiwyn** [comment]
Wasn't able to make much progress with this bug. Going to put it back in Ready for Engineering for the moment.

**Comment by jtdevos** [comment]
fyi: I followed the reproduction steps in TEST but did not see the broken behavior (the counts appeared as expected). 
 Do we know if this bug occurs consistently?  If not I'm wondering if it was unintentionally fixed in a newer release. 
 
Additional info:
- log in as petitionsclerk1@example.com on https://app.test.ef-cms.ustaxcourt.gov/
- changed Houston, TX 3/18/24 session from in-person to remote, then vice-versa
- count was unchanged on session info page (16 at the time)

**Comment by ttlenard** [comment]
@jtdevos After making a change to the trial session or sending out the 30 day notice, all of the cases on the trial session are appearing after being navigated back to the trial session screen.  Glad this is working now!  If there wasn't any code changes, can you please update this bug to closed?  If there were changes, we'll leave it in Court Engineering and deploy. Thanks!
