### ISSUE TITLE
BUG: Numbered/Bulleted list formatting on Order Generator not displaying appropriately on Preview or after Save

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8555]
**Describe the Bug**
In the Order Generator page, if you have a numbered or bulleted list with multiple levels, it looks fine on the Generator screen, but if you preview the document or save it, the formatting changes.  

**For Numbered/lettered lists:** 
Order generator screen has number/letter combinations.  On Preview or Save, it no longer has the number/letter combinations for multi-level list, it switches to all numbers.  See screen grabs.

Example in editor:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUF0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--104eb34bac3c2cf1cc6440ebf376bc6f3c326275/image.png)

Example in preview/generated doc:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUV0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e56b253fdb22ec38d3596c08e7e97c1296f64a/image.png)

**For Bulleted Lists:**

Order generator screen has bulleted list - all bullets are solid black. On the preview, it switches to solid/open bullets (this is actually probably desirable, but why doesn't the generator display this appropriately?)

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**
Any Court User

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the Application

**To Reproduce**
1. Go to a case
2. Click on the Create menu, and then select Order or Notice
3. Select Order  
4. On the Generate tab, create a numbered and bulleted list, making sure that you have multiple levels 
5. Notice that the numbered list shows numbers/letters appropriately
6. Notice that the bulleted list only has solid bullets
7. Click on the Preview tab
8. Now notice that the numbered/lettered list changes to all numbers
9. Now notice that the bulleted list changes to solid/non-solid/square bullets

Not sure why the formatting changes between the editor and the preview/saved doc?

**Expected Behavior**
1. What is entered in the generator should be the same as in the preview or the saved document when numbered lists are used. 
2. Bulleted lists in the generator should show different types of bullets when multiple levels are used (like it currently does in the preview/saved document.

**Actual Behavior**
A clear and concise description of what actually happened.
What is shown in the generator is not what is displayed on the preview for both numbered/bulleted lists

**Screenshots**

Here is a screen grab of the Order Generator - notice the numbers/letters/bullets:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDB0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdfab9bf6840b408bf2de48605af71022bdd4e8a/image.png)

Here is a screen grab of the Order Preview - notice that there are no more letters, and the bullets have changed.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDR0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97871b5ec0bc38ab6fdddd221e361b82235ba72b/image.png)

Here is a screen grab of the Order after it was saved - notice that there are no more letters, and the bullets have changed.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDh0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--626c8c5e14537f1d0516398383651aba0cb48237/image.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

5.

**Comment by ttlenard** [comment]
@TomElliottFlexion Some testing feedback:

I notice that the first two levels of a numbered list are working fine, but after the 2nd level, it seems to be stuck at lower-case letters. (See screen grabs below).

I also noticed that bulleted lists are now acting differently and are only displaying solid bullets on both the generator and the preview.

Notice in the screen grabs below, the generator has different number/letter combinations vs the preview.  The preview it switches over to a's and b's.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0o0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bdd4b998bef71bae0fed354a4b5b3884561fe1a/image.png)



[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTE0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40a79a4e82723c8cc0372a477fc5e1ba65f1cdd2/image.png)

**Comment by ttlenard** [comment]
@TomElliottFlexion  Looks great now. Thank you!

**Comment by TomElliottFlexion** [comment]
PR with a little documentation: https://github.com/ustaxcourt/ef-cms/pull/4142
