### ISSUE TITLE
Judge/CA Dashboard: New Value for Status of Matter LOV

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8557]
As a judge/CA, so that I can more accurately classify the cases in Submitted/CAV status for the Chief Judge, I need another value added to the list of values in the Status of Matter dropdown menu on my Dashboard.

In reviewing the Submitted/CAV cases portion of the Activity report, the Court has requested that an additional value be made available to classify as a case's Status of Matter: "Awaiting Release". This is primarily used to indicate that a case's bench opinion (OST) is awaiting the release of the transcript before the opinion can be made public.

"Awaiting Release" should be in the Status of Matter LOV between "Submitted to Reporter" and "Stayed".

## Acceptance Criteria
* "Awaiting Release" is available to select as a value when choosing a value for a case's Status of Matter on the judge/CA dashboard
* "Awaiting Release" is reflected on the Activity report for cases with that value assigned to it

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge user adds a Status of Matter to a case that is on their Submitted/CAV Cases section on their Dashboard; "Awaiting Release" is an option in the dropdown.

- Log into DAWSON as a Judge user that has cases that are a in Submitted or CAV status
- Scroll down to the Submitted/CAV cases section
- Click on the Edit link for one of the cases
- Click on the dropdown menu for the Status of Matter field

Expected Results:
- [x] **NEW FUNCTIONALITY** - There value "Awaiting Response" is now available in the dropdown list between "Submitted to Reporter" and "Stayed".


#### 2) Judge User selects "Awaiting Response" as the Status of Matter for one of their cases; Value saves and is displayed appropriately on the Dashboard.

- Continuing from the previous test
- Select the "Awaiting Response" value from the picklist
- Add a Final Brief Due date and a Primary issue (if you want, not required)
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Awaiting Response" value is saved and displays on the Judges Dashboard


#### 3) Judge User accesses the Activity report; Cases in Submitted/CAV cases that have the value of "Awaiting Response" are displayed appropriately on the Activity Report.

- Continuing from the previous test
- Click on the Reports menu and then select Activity
- Input some dates, leave the default judge user, and then run the report
- Scroll down to the Submitted/CAV Cases Section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Awaiting Response" value displays on the Activity report for the judge

*Repeat this test by selecting other Judge values and ensure that the "Awaiting Response" value is displayed appropriately in the results.


#### 4) Repeat tests 1-3 with a Chambers Administrator

- [x] **NEW FUNCTIONALITY** - Tests 1-3 pass with a CA user

**Comment by ttlenard** [comment]
@rachelschneiderman @nechama-krigsman

Testing looks good. Thanks!
