### ISSUE TITLE
Enhancements to Trial Session Planning Report

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8558]
As a _______, so that ________, I need ________.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by mwestereng1** [comment]
### **UX Notes:**
Please see the [Figma File](https://www.figma.com/design/7bMaSunIwunaE1bO57vTYz/Trial-Session-Planning?node-id=168-3513&t=UV87TMOOxYZfYKNS-1) for updates and comments in magenta. Some mock ups are also displayed below.

- Updates to the PDF Trial Session Planning Report
- On Screen Trial Session Planning Report Part 1
- On Screen Trial Session Planning Report Part 2

Important Note: There are still a few items for the on screen report that UX needs to verify with the court.

Trial Session Planning Report PDF page 1 example:
<img width="618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN09yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79e35b2deed6cb1087a1950cbbff751fe5180434/FINAL%20TS%20Planning%20Report%20PDF%20Page%201.png" alt="FINAL TS Planning Report PDF Page 1.png" />

Trial Session Planning Report PDF page 2 example:
<img width="618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--487480dc861d390e197522f9d248d60130906f5e/Final%20TS%20Planning%20Report%20PDF%20Page%202.png" alt="Final TS Planning Report PDF Page 2.png" />

Permutation Trial Session Planning Report PDF - No cities to display:
<img width="1224" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de708a1e3d00c86e6cf169675c41779e7cbfee60/Permutation%20-%20TS%20Planning%20Report%20No%20Cities.png" alt="Permutation - TS Planning Report No Cities.png" />

Part 1 -On screen Trial Session Planning Report (verify card/accordion with the court):
<img width="552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHVyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33b0dc0534dde77c78d856690414ccfcb742defe/v4.1%20On%20Screen%20Trial%20Session%20Planning%20Report.png" alt="v4.1 On Screen Trial Session Planning Report.png" />

Part 1 - On screen Trial Session Planning Report with tooltip (verify date last visited with the court):
<img width="552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d7e11929265a3aa0ed78d9f99c6329893366686/v4.1%20On%20Screen%20Trial%20Session%20Planning%20Report%20with%20Tooltip.png" alt="v4.1 On Screen Trial Session Planning Report with Tooltip.png" />

Part 2 - On screen Trial Session Planning Report linking to eligible cases by city (verify with court):
<img width="552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--416208c443b3e5f31d0663ce923052da8cdcdf10/v5.1%20On%20Screen%20Trial%20Session%20Planning%20Report%20with%20Tooltip.png" alt="v5.1 On Screen Trial Session Planning Report with Tooltip.png" />

-Part 2 - Eligible cases for trial by city (verify inclusions with court):
<img width="631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b6c1515288c82c6486270d4b6016bb53cad9b3f/Trial%20Session%20Planning%20Report%20Eligible%20Cases.png" alt="Trial Session Planning Report Eligible Cases.png" />
