### ISSUE TITLE
Trial Session Planning Report - Reorder By City

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8560]
As a calendar term planner, so that I can quickly scan the Trial Session Planning report to calculate the potential number and type of sessions needed per term, I need the report organized by city rather than state.

Feedback from all participants in the most recent term planning session indicates that the Trial Session Planning report would be faster and easier to use if the locations were organized alphabetically by City rather than State, as that is how the Court primarily thinks of locations for trial. This would allow the planners to more quickly scan and parse data from the report.

## Acceptance Criteria
* Locations on the Trial Session Planning report are organized alphabetically by Location name (i.e., City) rather than alphabetically by State

## Notes
* Do we even need the state column? We're already displaying the state as part of the location name.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX Notes:
- Remove the State column. Ideally use its space for the Location column so we can reduce the number of locations that must wrap. (But if the table won't allow it then thats fine)
- Alphabetical order by city name
- Note: Could whoever picks this up show UX which locations still wrap after the change? We are debating on shortening Washington, District of Columbia to Washington, D.C. and if its the only one wrapping still we may just do that.

Mock:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2gzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16825938030713333b407a3dc83bc98501db9265/image.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user generates a Trial Session Planning Report; Location data is alphabetized by City.

- Log in as any Court user
- Click on the reports menu and select Trial Session Planning Report
- Select Winter
- Select 2023
- Click Run Report

Expected Results:
- [x] The Report that is generated is alphabetized by City
- [x] The Report is formatted correctly

*Repeat this test by running the report for the following term/years. Verify that each document generated is alphabetized by City and is formatted correctly.

- [x] Winter 2024
- [x] Winter 2025
- [x] Spring 2023
- [x] Spring 2024
- [x] Spring 2025
- [x] Fall 2023
- [x] Fall 2024
- [x] Fall 2025
