### ISSUE TITLE
New Event Code: Amended Notice of Trial (ANTD)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8561]
As a docket clerk, so that I can reduce the number of notices that I need to issue when information changes on a trial session, I need to be able to docket and serve an Amended Notice of Trial.

When details for a trial session change after the initial calendaring, it is sometimes necessary to issue a notice to all parties associated with cases calendared for the session. Some of these are automated and some of them are docketed manually. The Court is moving towards an Amended Notice of Trial, which will be a one-size-fits-all document issued on demand when necessary. This should cut down on the number of types of notices currently issued as well as provide more flexibility in making multiple changes to a trial session when necessary.

To this end, we would like a new event code to be supported in DAWSON: the Amended Notice of Trial (ANTD). This behaves like other Court-issued notices - in particular the Notice of Trial (NTD) - in all respects. Future stories will address the generation and format of these notices.

## Acceptance Criteria
* Docket clerks/CSS/CotC can select Amended Notice of Trial (ANTD) as an option when adding a docket entry
  - ANTD does not require signature
* Selecting "Amended Notice of Trial" prompts the following inputs on the Add Docket Entry UI (same as presented when docketing a Notice of Trial):
  - Trial Date (date picker)
  - Trial Location (dropdown menu of trial locations)
  - Both fields must have valid values before saving/serving the docket entry
  - Docket Entry Preview text updates title of document using these values as with NTD
* ANTD is always served on both petitioner and respondent parties
  - Upon serving ANTD, if any parties receive paper service the clerk is presented with the paper service PDF as usual
* Docketing the ANTD displays the Docket Entry Preview text in the "Filings & Proceedings" column on the Docket record

## Notes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0tFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e02ec69243ec6883827da3e854c17054327cb9f/image.png)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- what do we do with old notices (change of judge and proceeding type)? get rid of them (in a later story)
- what is a significant enough change to warrant this notice going out? we don't care; any changes

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk starts to add a document to the docket record; New Amended Notice of Trial document is available in the Document type dropdown.

- Log in as a docket clerk
- Navigate to a case
- Case should have a document in drafts that was uploaded by another clerk, or you can upload a PDF as the docket clerk
- Click on the Add docket entry link from the document view
- Click on the Document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a new document type labeled Amended Notice of Trial.
- [x] **NEW FUNCTIONALITY** - When not filtering, the Amended Notice of Trial is below the 30-Day Notice of Trial document in the list order.
- [x] **NEW FUNCTIONALITY** - Clerk can type in ANTD in the dropdown and the Amended Notice of Trial will display

*Repeat this test with the CotC and CSS roles.



#### 2) Docket Clerk selects Amended Notice of Trial document from the Document Type dropdown; Trial Date and Trial Location fields are required.

- Continuing from the previous test
- Select the Amended Notice of Trial from the document type dropdown
- Do not input any data in the Trial date or Trial Location fields
- Click the Save and Serve button

Expected Results:
- [x] Validation error message for Trial Date and Trial Location field
- [x] No signature validation error message appears for Amended Day Notice of Trial (this document shouldn't require a signature)

*Repeat this test with the CotC and CSS roles.


#### 3) Docket Clerk inputs required fields for the Amended Notice of Trial document; Saves and Serves Document.

- Continuing from the previous test
- Input values for the Trial date and Trial Location (ensure that the docket entry preview text displays the title of the document correctly!)
- Click Save and Serve
- Click Yes, Serve (ensure that the document title is correct on this pop-up confirmation modal)

Expected Results
- [x] Print for paper service if Petitioner has paper service.
- [x] Green confirmation banner indicating that the document was served.
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is ANTD
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings column displays "Amended Notice of Trial on [DATE] at [CITY, STATE]".
- [x] **NEW FUNCTIONALITY** - The [DATE] is the value that you input in the previous test
- [x] **NEW FUNCTIONALITY** - The [CITY, STATE] is the value that you entered in the previous test.
- [x] **NEW FUNCTIONALITY** - ANTD is served successfully on all Parties.
- [x] All other fields on the docket record are as per normal.

*Repeat this test with the CotC and CSS roles.


#### 4) Docket clerk adds an Amended Notice of trial to the docket record; Saves entry, does not Serve; Document is saved appropriately to the docket record.

- Log in as a Docket Clerk
- Navigate to a case
- Upload a PDF and add the docket entry
- Select Amended Notice of Trial
- Input a trial date and trial location 
- Click Save Entry

Expected Results:
- [x] Green confirmation banner indicating that the document was saved
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is ANTD
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings column displays "Amended Notice of Trial on [DATE] at [CITY, STATE]".
- [x] **NEW FUNCTIONALITY** - The [DATE] is the value that you input for trial date 
- [x] **NEW FUNCTIONALITY** - The [CITY, STATE] is the value that you entered in the previous test.
- [x] Entry indicates "Not Served", and is highlighted in yellow.
- [x] No index number, no filed date, no value in the service column.

*Repeat this test with the CotC and CSS roles.


#### 5) Docket Clerk serves the previously saved ANTD, Docket record reflects information correctly.

- Continuing from the previous test
- Click on the document link for the Amended Notice of Trial on the docket record
- From the document view, click the Serve link
- Click Yes, Serve (ensure that the document title is correct on this pop-up confirmation modal)

Expected Results
- [x] Print for paper service if Petitioner has paper service.
- [x] Green confirmation banner indicating that the document was served.
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is ANTD
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings column displays "Amended Notice of Trial on [DATE] at [CITY, STATE]".
- [x] **NEW FUNCTIONALITY** - The [DATE] is the value that you input in the previous test
- [x] **NEW FUNCTIONALITY** - The [CITY, STATE] is the value that you entered in the previous test.
- [x] **NEW FUNCTIONALITY** - ANTD is served successfully on all Parties.
- [x] All other fields on the docket record are as per normal.

*Repeat this test with the CotC and CSS roles.


#### 6) Docket Clerk edits the document metadata for an Amended Notice of Trial; Document saves appropriately on the docket record

- Continuing from the previous test
- Click on the edit link on one of the Amended Notice of Trial documents that you just served.
- Update the Document Type
- Click Save

Expected Results:
- [x] Green confirmation banner indicating Docket entry changes saved. 
- [x] Document title and Event code are updated on the docket record

*Repeat this test by editing other metadata

- [x] Filed date
- [x] Date of trial
- [x] Trial Location
- [x] Adding an action
- [x] Striking the document
- [x] Adding the document to the pending report
     - [x] Pending report item is reflected on the tracked items tab in the case
     - [x] Case appears on the Pending Report

*Repeat this test with the CotC and CSS roles.


#### 7) Docket Clerk seals the Amended Notice of Trial; Document seals appropriately.

- Continuing from the previous test
- Click on the Seal link on the docket record
- Indicate the seal level that you would like
- Click Seal

Expected Results:
- [x] Document has the red lock icon
- [x] Document is no longer accessible for the parties that you indicated

*Be sure that you test this with both seal levels
*Repeat this test with the CotC and the CSS roles.



#### 8) Terminal user accesses case with a Amended Notice of Trial that has been docketed; User can view the document.

- Access DAWSON as the Terminal user
- Navigate to a case that has an Amended Notice of Trial

Expected Results:
- [x] Terminal user can click on the link and view the document.



#### 9) Docket clerk multi-dockets the Amended Notice of Trial; Document is filed and served appropriately.

- Log in as a docket clerk
- Navigate to the lead case in a consolidated group
- Upload a PDF and add the docket entry
- Select Amended Notice of Trial
- Input a date and trial location
- Click Save and Serve

Expected Results
- [x] Consolidated case modal appears
- [x] Docket clerk can select all or some cases in the group
- [x] After service, print for paper service appears (if P has paper service)
- [x] The Amended Notice of Trial is served appropriately across all cases that you selected in the Consolidated Group.


*Repeat this test with the CotC and the CSS roles.

**Comment by ttlenard** [comment]
Testing looks good. Thanks @codyseibert  @Absolutestunna
