### ISSUE TITLE
BUG: The status report portion of the Stamp Order does not display in the Stamp Preview

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8565]
**Describe the Bug**
A Court user reported to us when you select either of the Status Report Due radio buttons on the Stamp Order screen, they do not display in the Stamp Preview.  The good news is that the status report text DOES show up after you save the stamp order.

**Business Impact/Reason for Severity**
Med

**In which environment did you see this bug?**
Test, Prod

**Who were you logged in as?**
Judge, chambers user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
This was reported to us by a Court user on Prod

**To Reproduce**
1. Log in as a Judge that has a message with a motion attached to it
2. Open the message
3. Click on the apply stamp link in the document preview
4. Fill out the required fields, and be sure to select the radio buttons in the status report due section.
5. Notice that neither of the sentences appears in the preview on the stamp order
6. Save the stamp order
7. Notice that the draft document DOES actually have the data, and this appears to be an issue only with the stamp preview.

**Expected Behavior**
Anything entered on the left side of the stamp builder should display in the preview on the right

**Actual Behavior**
A clear and concise description of what actually happened.
The text in the status report section of the stamp builder is not displaying on the document preview

**Screenshots**

Status report text not displaying in the Preview:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95d524c87403b3e383c264fa1aae0635544240af/image.png)

Status report text DOES display after save
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3100e31f54c29610c59ae2722c468bd1e5e5ad9a/image.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by TomElliottFlexion** [comment]
Solution on branch flexion/`10188-BUG-stamp-preview-date`

**Comment by ttlenard** [comment]
I also see this when I click on the Delete link on a deadline in a case.  Tom and Nechama have confirmed that this is also related to this bug.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW1aQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--713eaa166a32b47f73aeba6abb64136084f7e9e1/image.png)

**Comment by TomElliottFlexion** [comment]
https://flexion.slack.com/archives/CHMLA049H/p1698939874229629

**Comment by ttlenard** [comment]
@rachelschneiderman Testing Feedback

When you add in the Status report fields, they are now showing up in the preview. Also, deleting a status report item displays the date correctly now. Thank you!

There is still an issue though. Here are the steps to recreate it:
- Click on the Apply stamp link when previewing a motion
- Select Granted or denied
- Select one of the status report radio buttons and pick a date
- Click on the Clear optional fields link

Issue: 
- The date that was input in the date picker remains. The only way to delete the date, is to physically check the status report radio buttons again to get the date field to activate so that you can delete the date. Then you have to clear optional fields again to remove the radio button selection.

Note: I tested this on the IRS Test environment since the date picker stuff is NOT yet on IRS TEST.  When you click on the Clear optional fields in IRS Test, the Date that was selected gets reverted back to no selection.

Here is a screen grab from in TEST (I just clicked clear optional fields. Notice how the date that was previously selected stays in the date picker, but it's greyed out, and the date that was previously selected remains in the preview):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVd1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dda9d78b2558d48d71bb64fb36ed3a7809cf5fc/image.png)

Screen grab from IRS Test Environment (I just clicked clear optional fields. Notice how the date picker resets and it is not displayed in the preview anymore):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXF1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84a962030a780637c52fb76ffc1a0d58cb675c26/image.png)





I

**Comment by ttlenard** [comment]
@rachelschneiderman

Looks like the date clears, but the helper text in the date field is no longer present like it is in IRS test (See screen grab above).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de66c7ca4af312a507da3f69657cc9cf80a8a9c9/image.png)

**Comment by ttlenard** [comment]
@rachelschneiderman testing looks good! Thank you.
