### ISSUE TITLE
Entry of Appearance: Remove Court Seal from Header

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8567]
As a practitioner, so that my entry of appearance document does not imply that it was Court-issued, I need the Court Seal removed from the upper left hand corner of the generated Entry of Appearance forms.

The Court seal is applied to the generated Entry of Appearance forms; this should theoretically only be present on Court-issued documents and cover sheets. We would like it removed.

We expect that this should apply to future DAWSON-generated petitioner/practitioner documents as well.

## Acceptance Criteria
* Auto-generated entry of appearance documents do not have the Court Seal present in the header of the document.

## Notes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVNLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09b401f499d6c07325725c4907291f15ad39e59f/image.png)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner efiles an Auto-Generated Entry of Appearance document; The document preview displayed does not have the USTC Seal; The linked document does not have the USTC Seal.

- Log in as a Private Practitioner
- Search for a case
- Click on the Request Access to Case button
- Select Entry of Appearance from the document dropdown list
- Select the Petitioner that you are representing
- Be sure that the radio button for Auto-generate Entry of Appearance PDF is selected.
- Click Review Filing button
- On the Review your Filing page:

Expected Results:
- [x] The document preview on the right side of the screen does not have the USTC seal in the upper left corner
- [x] After clicking the document link, the document that opens does not have the USTC Seal in the upper left corner.
- [x] After submitting the EA document, the document on the docket record does not have the USTC Seal in the upper left corner. 


#### 2) IRS Practitioner efiles an Auto-Generated Entry of Appearance document; The document preview displayed does not have the USTC Seal; The linked document does not have the USTC Seal.

- Log in as an IRS Practitioner
- Search for a case
- Click on the Request Access to Case button
- Select Entry of Appearance from the document dropdown list
- Be sure that the radio button for Auto-generate Entry of Appearance PDF is selected.
- Click Review Filing button
- On the Review your Filing page:

Expected Results:
- [x] The document preview on the right side of the screen does not have the USTC seal in the upper left corner
- [x] After clicking the document link, the document that opens does not have the USTC Seal in the upper left corner.
- [x] After submitting the EA document, the document on the docket record does not have the USTC Seal in the upper left corner.

**Comment by ttlenard** [comment]
@rachelschneiderman

Testing looks good. Thank you!
