### ISSUE TITLE
Text Changes - Petition Submission Flow

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8571]
As a petitioner, so that I have a clear understanding what is required of me when filing a petition, I need the text accompanying the online petition submission flow to be updated.

After reviewing the current language in the online petition submission flow, the Court has requested some edits to the existing text in order to better set expectations for the petitioner. 

## Acceptance Criteria
The following changes are made to the text on the appropriate pages in the online petition submission flow.

**<ins>p.1 Create A Case</ins>**

 - _Change the paragraph under "Check the Deadline For Filing" to read:_
You may have received a notice in the mail from the Internal Revenue Service (IRS). The IRS notice may show the last date to file or the number of days you have to file a Petition.  In most cases, the Court must receive your electronically filed Petition no later than 11:59 pm Eastern Time on the last date to file. Petitions received after this date may be untimely and your case may be dismissed for lack of jurisdiction.

 - _Change the paragraph under "Confirm your identity" to read:_
You’ll be asked to upload your Statement of Taxpayer Identification Number (STIN)* form in Step 1 of creating a case. This document is sent to the IRS to help them identify you, but it’s never visible as part of the case record.

 - _Change the paragraph under "Prepare the Petition" to read:_
The Petition is the document that explains why you’re challenging the IRS’s determination. You can use the Court’s standard Petition form or you can upload your own Petition that complies with the requirements of the Tax Court Rules of Practice and Procedure.

 - _Change the 2nd list item under "Prepare the Petition" to read:_
2. Create a single PDF of your Petition and IRS notice (if you received one)

 - _Change the paragraph under "If you're filing jointly with a spouse, for someone else, or for a business...", "Joint Petition With A Spouse" to read:_
To file a joint Petition with your spouse, you must have their consent. Both you and your spouse should [sign the Petition](https://ustaxcourt.gov/dawson_faqs_case_management.html#CASE7). If you do not have your spouse’s consent, select “Myself” as the person who is filing.

 - _Change the paragraph under "If you're filing jointly with a spouse, for someone else, or for a business...", "Someone Else" to read:_
To file a case on behalf of another taxpayer, you must be authorized to practice before this Court as provided by the [Tax Court Rules of Practice and Procedure](https://ustaxcourt.gov/rules.html) (Rule 60). Enrolled agents, certified public accountants, and attorneys who are not admitted to practice before the Court are not eligible to represent taxpayers. 

 - _Change the last line on this page to read:_
Next you’ll continue to follow the steps to upload your documents and fill in the information that will create your case.

**<ins>p.2 Statement of Taxpayer Identification</ins>**

 - _Change the last line of the paragraph in the gray information box to read:_
It’s sent to the IRS to help identify you but is never visible as part of the case record.

**<ins>p.3 Your Petition</ins>**

 - _Change the sentence in the gray information box to read:_
Don’t forget to remove or block out (redact) your personal information on all your documents, including any IRS notice(s).

**<ins>p.4 Who Are You Filing This Petition For?</ins>**

 - _Change the text in the "You Must Have Your Spouse's Consent To File On Their Behalf" modal that appears when selecting "Myself and My Spouse" and "No" to read:_

To file on behalf of your spouse, you must have consent. Both you and your spouse should sign the Petition.

If you do not have your spouse’s consent, select “Myself” as the person who is filing.

 - _Change the sub-option label "Partnership (as a partnership representative under the BBA regime)" that appears when selecting "A business" to read:_

Partnership (as a partnership representative under BBA)

 - _Change the text in the gray information box under "Corporate Disclosure Statement" to read:_

[Tax Court Rule 60](https://ustaxcourt.gov/rules.html) requires a corporation, partnership, or limited liability company, filing a Petition with the Court to also file a Corporate Disclosure Statement (CDS).

**<ins>p. 5 What Case Procedure Should You Choose For Trial?</ins>**

 - _Change the first paragraph on the page to read:_

If your case qualifies, you may choose to have it handled as a small tax case. The Court handles small tax cases differently.

 - _Change the sentence under "U.S. Tax Court Locations" to read:_

This is the place your case will be heard if it goes to trial.

**<ins>p.6 Review Your Case Details</ins>**

 - _Change the last sentence in the gray information box at the top of the page to read:_

You will not be able to make changes to your case once you submit it without filing a motion.

 - _Change the first list item under "A Few Reminders Before You Submit" to read:_

1. Double check your IRS Notice to ensure your Petition is timely.  In most cases, the Court must receive your Petition no later than 11:59 pm Eastern Time on the last date to file.

 - _Change the fourth list item under "A Few Reminders Before You Submit" to read:_

4. Confirm that all information being submitted appears as you want it to appear. After clicking Submit to U.S. Tax Court, you will only be able to edit your case by filing a motion.

**<ins>p. 7 (Confirmation upon submission)</ins>**

 - _Change the second sentence in the second paragraph to read:_

You’ll also be able to check the status of your case, submit new documents, and view activity in the case on the docket record. 

 - _Change the second bullet point under "Next Steps" to read:_

•	As new information about the case becomes available you will be notified at the email address you provided.

## Notes
* Changes should include hyperlinks where indicated

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- why are the changes happening now? language was written when it was implemented so time for a refresh; update deadline to file text due to recent Supreme Court ruling

**Comment by ttlenard** [comment]
## Test Cases

These test cases reference the specific changes listed in the A/C.

#### 1) The text changes match what is indicated in the A/C.

Expected Results:
- [ ] Page 1 changes match
- [ ] Page 2 changes match
- [ ] Page 3 changes match
- [ ] Page 4 changes match
- [ ] Page 5 changes match
- [ ] Page 6 changes match
- [ ] Page 7 changes match

**Comment by jasonfu9966** [comment]
questions while working:
1. should hyperlinks open in a new tab, the same tab, or vary by case? 
1. should the text "In most cases, the Court must receive your electronically filed Petition no later than 11:59 pm Eastern Time on the last date to file." still be bold? 
2. Same question for "In most cases, the Court must receive your Petition no later than 11:59 pm Eastern Time on the last date to file."

**Comment by cholly75** [comment]
@jasonfu9966 :

1) New tab
2) Yes
2) Yes

Thanks,
Chris

**Comment by ttlenard** [comment]
@jasonfu9966 Tiny grammatical issue.

Please remove this comma:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c67454107fdcc480c3f4f899cb2f9c564bed42ef/image.png)

**Comment by ttlenard** [comment]
I reviewed this with Jason on his local and the comma was removed. Thank you for fixing!
