### ISSUE TITLE
BUG: Remote Trial Session data is not displaying on the Printable Trial Session info page

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8577]
**Describe the Bug**
There are two issues with this bug:
- When a Trial session is scheduled as a remote session, the location information on the printable version of the Session information page indicates "No location entered".
- When a trial session is scheduled as in-person, but then changes to remote, the in-person location information that is on the printed version of the session information page remains and is not updated with the remote information. (I also noticed that if you edit the session from remote back to in person, the original in person data is already there - this is probably why that data populates on the printed version??? Seems it's not getting removed from the DB???)

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**

**Scenario 1**
1. Log in as a petitions clerk
2. Click on trial session
3. Click on the Add Trial Session button
4. Fill in all the required information for a remote session
5. Click Add Session
6. Click on the City, State link of the session you just created
7. Check the box to select a few eligible cases
8. Click Set Calendar
9. Click Yes, Set Calendar
10. Click done on the paper service screen
11. Notice on the Session information page, it provides the Remote Proceeding information
12. Click on the Print Session info page
13. For the Location, it states "No location entered" rather than display the remote proceeding information.

**Scenario 2**
1. Log in as a Petitions Clerk
2. Click on Trial Sessions
3. Be sure you are on the Open tab.
4. Find an In person session that is in the future.
5. Click on the City, State link.
6. Notice the In Person location information on the session info page.
7. Click on the Edit link on the session info page.
8. Change the session from in person to remote, making sure to input the required remote information.
9. Click Save
10. Click done on the print for paper service screen.
11. Notice that on the Session information screen, there is now remote proceeding information.
12. Click on the Print Session Information link
13. The location information on the printed version still shows the in-person location information.

**Expected Behavior**
The printed version should match what is on the Session information screen

**Actual Behavior**
A clear and concise description of what actually happened.
No information is displayed for the location on the printed version, or, if a session changed from in person to remote, the in person information still displays on the printed version.

**Screenshots**

Here is a session that was initially scheduled as remote. Notice how it states "No location entered"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d91bffc585bc3b8717f06eafeaf32ae19473172a/image.png)

Here is a session that was changed from in person to remote.  Notice the Session information page displays the Remote proceeding info:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b39a82f6894854e3f9e1fcd4af2b89ec15f903d1/image.png)

Here is the printed version. Notice that it is still displaying the in-person data.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUVPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8e91149b6dee9250a2708182b008ee8b3d4a216/image.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

6.

**Comment by jhansen-flexion** [comment]
Bloced Waiting for UX Design changes and review with Chris

**Comment by swongCO** [comment]
**UX Notes**
Add meeting info from Session Info page to printable pdf
- display input as they are in Session Info page (if none, then "Not provided" is displayed)
- fit all 4 info fields into the Trial Information card, matching the height of the Assignments card
- this is applicable to both remote and standalone remote sessions

<img width="724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2F3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d3590b4ab56080ad3e20219774bf4dcf2c3e48e/Frame%201.png" alt="Frame 1.png" />

**Comment by ujahio** [comment]
Addressing UX feedback to change default text to 'Not provided'.

**Comment by ttlenard** [comment]
@Absolutestunna Thanks for fixing. Looks good.
