### ISSUE TITLE
BUG: Cases migrated with amendment documents are missing `previousDocument` property and generate error on Public API

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#8586]
**Describe the Bug**

We are seeing the following JavaScript error in the error logs when users attempt to download a public docket entry. 

```
TypeError: Cannot read properties of undefined (reading 'documentType')
    at PublicCase.isPrivateDocument (/var/task/api-public.js:495611:185)
    at /var/task/api-public.js:510770:47
    at Generator.next (<anonymous>)
    at fulfilled (/var/task/api-public.js:510734:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

They should be getting an Unauthorized document because we cannot determine the previousDocument. The previousDocument property is missing on these amendment docket entries due to their migration.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**

Prod

**Who were you logged in as?**

N/A

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

Reviewing error logs

**To Reproduce**

1. Navigate to the public API: `public-api/24158-09/92d611b6-0075-4c48-acf6-0d5fb91bfc79/public-document-download-url`
2. See error and error in logs

**Expected Behavior**

Since the amendment docket entry does not have a previousDocument, we should assume that it is a Private Document (not an amendment to a Brief). Plus, these were filed before the policy date, and so the public does not get access.

Unauthorized Access to Private Document

**Actual Behavior**

Users would have gotten a 400 error. A JavaScript error was logged.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
Testing for this bugfix included the following regression tests:
- 10113
- 9866
- 10037
- 10045
- 10076
- Verified Lodged document visibility
- Verified Sealed document visibility
- Verified Stricken document visibility
- Verified Transcript document visibility
- Verified the above with searching the public api
- Verified stamp orders, proposed stip flow, Document QC inbox, Opinions, Orders, Online Cited Source documents
- Verified with Terminal user, Public non-logged in user, Public logged in user not associated with cases, IRS Practitioner, Private Practitioner.

**Comment by ttlenard** [comment]
Looks like there is an issue with the "Not Served" label displaying on the docket record for the RQT minute entry for eFiled petitions.  @mmarcotte has already identified the issue and is fixing it.

<img width="1485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFdyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cadcdaaad3b231e88308e7a96498a48e7bc3f35a/image.png" alt="image.png" />
