### ISSUE TITLE
BUG: Users associated with many cases are experiencing a 504 error when logging in

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8601]
**Describe the Bug**

We received a helpdesk ticket recently where an IRS user experienced a 504 error upon login.  After reviewing the logs, we are seeing that this is happening somewhat often for a handful of users.  The user that this reported this is associated with around 7557 cases in Prod.

all the 504's are with this endpoint:  `/cases`

Note that it would appear that sometimes it is taking these users more than 29 seconds for their My cases page to load, resulting in the 504 error, and sometimes they get it to load around 28 seconds, so they do sometimes have success when logging in.  

**Business Impact/Reason for Severity**
Med

**In which environment did you see this bug?**
Prod

**Who were you logged in as?**
This is one of the users gordon.p.sanz@irscounsel.treas.gov

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
This was reported via the Helpdesk

**To Reproduce**
1. Attempt to log in as a user that has many many cases
2. Receive 504 error

**Expected Behavior**

Users should not receive a 504 error upon login

**Actual Behavior**
A clear and concise description of what actually happened.

Users with many many cases are experiencing a 504 error

**Screenshots**

Here is a screen grab from Prod Kibana:
<img width="1483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--969bd94cd2e832f86cc22f0bcf49b46b007e00ad/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by mmarcotte** [comment]
90 days is the outer deadline of cases we need to worry about for closed cases.

**Comment by mmarcotte** [comment]
We saw benefit in reintroducing the UserCase records with the following structure so that you could easily query upon them and paginate through them:

```
pk: user|<userid>
sk: case|<status>|<date>|<docketNumber>
docketNumber: 123-23
closedDate: 2023-03-30
status: Closed
leadDocketNumber: 124-23
```

We were also considering a couple of different approaches for endpoint strategies when thinking about Pagination

1. Make an endpoint that you can paginate through for either open or closed: 

    ```
    /cases/{open:closed}/{page|startVal}
    {
      cases: [
        {},
        {},
        {},
        {},
        {},
      ],
      total: 5000
    }
    ```

2. Make two endpoints, one for a quick summary and another for pagination:

    ```
    /cases 
    {
      open: {
        cases: [
          {},
          {},
          {},
          {},
          {},
        ],
        total: 5000,
      },
      closed: {
        cases: [   
          {},
          {},
          {},
          {},
          {},
        ],
        total: 3000
      }
    }
    
    /cases/{open:closed}/{page|startVal}
    {
      cases: [
        {},
        {},
        {},
        {},
        {},
      ],
    }
    ```

3. Make two endpoints, one to paginate and another to get the count

    ```
    /cases/{open:closed}/{page|startVal}
    {
      cases: [
        {},
        {},
        {},
        {},
        {},
      ],
    }
    
    /cases/{open:closed}/count 
    {
      total: 5000
    }
    ```
