### ISSUE TITLE
BUG: Serving a Petition to the IRS is causing 504 errors, auto-generated draft Orders have coversheets

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8613]
**Describe the Bug**

We have identified two issues on Test, not sure if they are related or not.  

The two issues below occur when a Petitions clerk either creates a paper petition and serves it to the IRS, or QC's an electronically filed petition and serves it to the IRS.

Issue 1 - The `/cases/[docket number]/serve-to-irs` request url is sometimes resulting in a 504 error.  This seems to happen when there are multiple auto-generated orders that get generated when serving to the IRS.  We also saw this issue on the Staging environment on 2/2/24. (See screen grabs of logs).  When this happens, we've seen different behavior. Sometimes you will see that the Petition is successfully served to the IRS, and if you attempt to serve multiple times, you'll see duplicative docket numbers in the Served box of Document QC.  Sometimes you will see duplicative draft orders (and multiple coversheets - see Issue 2 below). Sometimes there will not be duplicative docket numbers in the QC, but duplicative Orders in draft.

Issue 2 - Regardless of if there is a 504 error, any time there is an auto-generated Order that gets identified in the Petition QC process, the resulting draft Orders have coversheets.  Sometimes the draft order text is present (so there will be a coversheet + the draft order), and sometimes there is ONLY a coversheet, and no draft Order.  In the scenario where there is only a coversheet and the draft autogenerated order is one that has an amended petition (OAP and OAPF), there will be a coversheet and the amended petition that is appended, but no actual draft order.

**Business Impact/Reason for Severity**
High

**In which environment did you see this bug?**
Test (and we saw the 504's in Staging on Friday 2/2, but not the Order coversheet issue)

**Who were you logged in as?**
Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**

Issue 1 - 504's
1. Log into Test as a Petitions clerk
2. Click on Document QC tab. 
3. QC an eFiled Petition, or create a new paper petition to QC
4. Be sure that you indicate multiple Orders that will need to be auto-generated.  Seems it is always around 3 or 4 that cause the 504 to happen.
5. Serve to IRS
6. You will get the spinner indicating that it is working on serving the case, but then it will bring you back to the Review and Serve Petition Screen, making it appear that it didn't work.
7. If you click serve to IRS again, the same behavior will occur
8. If you open a new tab and go to Document QC/Served box, you will see that there are duplicate docket numbers for the case, and it got served twice.
9. Open the docket record
10. Notice that you might have multiple draft orders (we'll go into this issue below)

Issue 2 - Coversheets on Auto-generated Orders
1. Regardless of if you experienced a 504 while serving a petition or not (you could just serve a regular petition, and not receive the 504), navigate to a Petition that you just served.  Be sure that you have some auto-generated orders that you created.
2. Click on the draft Order
3. Notice that there is ONLY a coversheet, and the draft order is actually not present.  If you happen to actually have a draft order that DID get the actual draft order language, this could happen too. (See case 1827-24 on TEST). Most of the time, only a coversheet will be generated for the draft order.

**Expected Behavior**
Issue 1 - Petitions clerks should not receive 504 errors when serving a petition with multiple auto-generated notices

Issue 2 - Auto-generated Orders should not be receiving coversheets until they are served.

**Actual Behavior**
A clear and concise description of what actually happened.
Issue 1 - Petitions clerks are receiving a 504 when they are indicating that there are multiple Auto-generated Orders needed

Issue 2 - All auto-generated orders are getting coversheets before they are served, and many times the actual text of the draft order isn't being generated.

**Screenshots**

504 issues on Test
<img width="1568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26f66ccf6d803dde95a5795076bb476ba7167c14/image.png" alt="image.png" />

504 issues on Staging - this is a screengrab from the 504's we saw on Staging on Friday 2/2. I did some testing on 2/5 and didn't experience any 504's on 2/5, so I'm not sure what is going on.
<img width="1563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2469abfe820789140bd5622f8f2cd7c726469d8f/image.png" alt="image.png" />

Here is an example of the duplicate cases that show up in Document QC if you experience the 504 and retry serving to IRS.
<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d47e254cad10185e269cec069fe2a0f8d5f317ad/image.png" alt="image.png" />

Here is a screengrab of the duplicate Orders generated WITH the Order/Notice content.
<img width="1441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65a635e97eff152a95b299ddc2188c400fbc85d1/image.png" alt="image.png" />

Here is a screengrab of duplicate orders generated with ONLY the coversheet generated, and no Order/Notice content:
<img width="1400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46b239617d24d78a0bc0ea66e1f00e7c6e65af30/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by katiecissell** [comment]
Modal:
<img width="1921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXBEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9b9923add57dd92e5b704ec876bc55bcab571f4/image.png" alt="image.png" />
