### ISSUE TITLE
Practitioner Search - Public

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8614]
As a member of the public, so that I can ensure that my attorney is in good standing with the USTC, I need the Practitioner Search to be available to me.

The USTC would like to provide a way for the public in general and petitioners in specific to validate a current or potential attorney's standing with the Tax Court to confirm that they are licensed to practice before USTC. To that end, we would like to expose a version of the internal Practitioner search to all external users and the public as an additional tool available alongside the other Advanced Search options (Case, Order, Opinion).

This story will cover exposing the Practitioner search to the general public. Follow up story will address exposing to Petitioner/Practitioners logged into DAWSON.

## Pre-Conditions
ustaxcourt/ef-cms#8621
ustaxcourt/ef-cms#8623

## Acceptance Criteria
* All non-logged in Court users can access Practitioner Search
* Practitioner Search for non-Court users functions identically to the internal version of Practitioner Search, with one exception: Bar Number is NOT hyperlinked, and Practitioner Records are NEVER available to non-Court users. 
* Available search criteria for Practitioner Search:
  - Practitioner Name
  - Bar Number
 * Search results display the following fields:
   - Bar No.
   - Name
   - Original Bar State
   - Admission Status
   - Practitioner Type
   - Practice Type
   - Admission Date
* Text added to page/UI: "The information provided in the search results below is maintained by the Admissions Clerk of the U.S. Tax Court. Practitioners may update their contact information by logging into DAWSON and updating their practitioner accounts. Practitioners may change thier practitioner type, practice type, or admission status by contacting the Admissions Clerk at admissions@ustaxcourt.gov."
 
## Notes
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5IQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fe81c883197a5419505996cdca4ed0d380ebfca/image.png" alt="image.png" />
* Need to add rate limiting?

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement question:
- Possibility we send info over network request, if we do, we might need to filter that to make more secure?
- Add logging so we can tell if people are using it?

**Comment by katiecissell** [comment]
UX Notes:
[Figma file](https://www.figma.com/file/sDn5MVTHF1yZWkQwLmEOyL/USTC-%7C-Practitioner-Search?type=design&node-id=27%3A39&mode=design&t=qo5VqAeo5fIkvNk1-1)

Search
- Add disclaimer text with bullets.
<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1SQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54abe450ca0d60eedccdd9500b1bb5972ef97ab0/image.png" alt="image.png" />


Search mobile
- When in mobile view, show radio options to search by name or bar number. 

<img width="250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a9edc6cab3cac5013302475793881ae09190349/image.png" alt="image.png" />

Search results:
- Remove hyperlink for bar number.
- Add results count
- If there are no results display the empty state message of ""No matches found"
<img width="1217" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkV5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec1775f3fa09522071a4c21411ab30babf4330a1/image.png" alt="image.png" />



Mobile search results:
- Display search results in cards with the name as the header. (Make sure large names will wrap in the header)
<img width="176" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkl5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--041fd0435c9381fc14158d139675413ae63cad38/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Public DAWSON user navigates to the DAWSON homepage; New tab for Practitioner now displays.

- As an public user, navigate to the DAWSON homepage

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a new tab to the right of Opinion, titled "Practitioner"



#### 2) Public DAWSON user clicks on the Practitioner tab; new Practitioner search page displays.

- Continuing from the previous test
- Click on the Practitioner tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - Practitioner search page displays
- [x] **NEW FUNCTIONALITY** - Text information is displayed underneath the Practitioner tab (see mockup)
- [x] **NEW FUNCTIONALITY** - External user can search by Name or by Bar number (same as internal users)



#### 3) Public DAWSON user searches for a practitioner that has a common last name; Search results include pagination.

- Continuing from the previous test
- Type in a last name of a practitioner that would yield many results (ex. Smith or Jones)
- Click Seach

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Search results have a paginator at the top of the page
- [x] **NEW FUNCTIONALITY** - There is a total count in the upper right of the search results
- [x] **NEW FUNCTIONALITY** - Search results are sorted by Practitioner first name A-Z
- [x] **NEW FUNCTIONALITY** - There are no hyperlinks in the Search results, so no additional data can be viewed for the practitioners
- [x] **NEW FUNCTIONALITY** - Columns in the Results table include: Bar No., Name, Original Bar State, Admission Status, Admission Date, Practitioner Type, and Practice Type.



#### 4) Public DAWSON user searches for a Practitioner, while having their console open; JSON data does not display any additional Practitioner data beyond what is available in the UI.

- Continuing from the previous test
- Open the console app
- Type in another name in the Name field
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - Search results are appropriate (as test cases above indicate)
- [x] **NEW FUNCTIONALITY** - If the name you searched for isn't super common, there will not be any pagination
- [x] **NEW FUNCTIONALITY** - In the JSON, no additional data beyond what is in the UI is available.



#### 5) Public DAWSON user searches for a Practitioner by typing in a Bar number; user receives one singular result if the Bar number is valid.

- As an public user, navigate to the DAWSON homepage
- Click on Practitioner tab
- Type in a valid Bar number for a practitioner
- Click Search

Expected Results
- [x] **NEW FUNCTIONALITY** - A singular record is displayed for the Practitioner
- [x] **NEW FUNCTIONALITY** - No paginator
- [x] **NEW FUNCTIONALITY** - All column data is appropriate for the single user
- [x] **NEW FUNCTIONALITY** - Total Count displays 1



#### 6) Public DAWSON user searches for a Practitioner by typing in an invalid Bar number; User receives messaging that states, "No Matches found"

- As an public user, navigate to the DAWSON homepage
- Click on Practitioner tab
- Type in an invalid Bar number
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - User receives a message in the search results area that states, "No Matches Found. Check your search terms and try again."

*Repeat this test, but instead, type in a Practitioner Name that will not yield any results - you should receive the same messaging.



#### 7) Public DAWSON user searches for a Practitioner, clicks Clear Results link; Data in the results table and in the search field clears.

- As an public user, navigate to the DAWSON homepage
- Click on Practitioner tab
- Search for a Practitioner by typing in a name
- Click Search
- After the search results load, click on the Clear Search link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The search results clear
- [x] **NEW FUNCTIONALITY** - The search term clears

*Repeat this test by first searching for a practitioner using the Bar number search, and then clicking on the Clear Search.



#### 8) Regression Tests

- [x] Data in the search results is the same for public user and internal user
- [x] Practitioner Search is not available via advanced search tab for logged in Practitioners/Petitioners
- [ ] Practitioner Search is not available via the Terminal User
     - After testing, the Practitioner search IS available to the Terminal user. I talked with Chris and he is fine with leaving this functionality available for the terminal user.
- [x] Ensure that the practitioner record is not available publicly (they cannot type in the url to get the practitioner record. ex: https://app.test.ef-cms.ustaxcourt.gov/practitioner-detail/JL0086)



#### 9) Mobile

- [x] All tests above pass on a mobile device 
- [x] Design on mobile is clear and matches mockups (results are displayed in tiles, Bar vs Name search is selectable via radio button)

**Comment by cholly75** [comment]
Reminder: need to update Judge record status to Inactive prior to go-live.

**Comment by katiecissell** [comment]
UX Feedback 
- [x] -Line currently says "The information provided in the search results below is maintained by the Admissions Clerk of the U.S. Tax Court." Should say " The information in the search results below is maintained by the Admissions Clerk of the U.S.T.C" 
- [x] - Typo in second bullet for "thier"
- [x] First and second bullet should wrap instead of continuing across page. The divider between the two search boxes is the marker for where it should wrap.
- [ ]- For internal users: David Bailey Smith is not showing their bar state in the search result list, but if you click on them they do have a bar state. And in public search they are showing the bar state in the search results. **WE ARE WAITING FOR A RESPONSE TO DETERMINE WHAT TO DISPLAY, CURRENTLY FOR INTERNAL USERS WE DISPLAY CONTACT STATE AND 10258 IS STATING BAR STATE (JOHN CRUZ)**
- <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--240fecf40d29ffcade9e7c5ea6fc1eb2f6d46596/image.png" alt="image.png" />
<img width="346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b2bfc4f92680ae992e5f29478f4136ee95a6126/image.png" alt="image.png" />
Public view:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10328f2e565f1b0c03bdbd233a9477740d01c52e/image.png" alt="image.png" />


Mobile feedback
- [x] Clear Search should be centered and have more padding above it so its not so close to the search button.

**Comment by cruzjone-flexion** [comment]
- [x]  Fix Paginator UI bug: when in mobile the Previous and Next button are not being displayed

**Comment by ttlenard** [comment]
Replying to @katiecissell comment above:

Leave the State data that displays in the results as it currently is:

Internal Practitioner search = Contact state
External Practitioner search = Original BAR state.

**Comment by ttlenard** [comment]
- [x] @cruzejone - some testing feedback. We need to change the text in the first sentence back to "U.S. Tax Court" as per the A/C. Thank you!
