### ISSUE TITLE
BUG: 504 error occurs when a user attempts to upload a large document to a case.

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8616]
**Describe the Bug**

We are seeing some 504 errors for the API Gateway Access Log in OpenSearch, and we think it is happening when users are attempting to upload large documents to a case.  I found this issue while testing something else, and I notice that depending on if you are an internal vs external user, there is different behavior.  Sometimes the document ends up on the docket record without a coversheet, sometimes the user receives an error, and the document isn't uploaded at all.  I believe it depends on when the timeout occurs in the overall sequence of upload events.  Either at the 'validate' stage or the 'coversheet' stage seem to be most common.

Some thoughts:
Not entirely sure how some of the documents on the docket record of the Facebook case got on there without coversheet.   Was it b/c of these 504 errors?  Did the implementation of the "Your Request Was Not Completed" error message pop-up change some behavior to the external users?  Did DAWSON used to let documents through and now the user receives this error message?  Not sure at this point. (See screen grab below).  I also think that this bug is related to bug ustaxcourt/ef-cms#8615

**Business Impact/Reason for Severity**
med

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
Docket clerk, Petitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**

Internal users:
**Scenario 1**
- Log in as a docket clerk
- Open your console
- Navigate to a case
- Click Add paper filing
- Upload a very large document. I was actually using a 132,000 page document that was very close to the 520 MB limit.
- Fill out the metadata for the filing and click Serve
- You will get the spinning wheel for awhile
- The spinning wheel will stop, and you will be navigated back to the Add Paper filing page with an error stating that "The system is taking too long to respond".
- The network tab will show that it errored out on the coversheet step, and the console tab shows the 504, and a cerebral error thrown by sequence "serveDocumentCompleteSequence".
- If you navigate to the docket record from this page, you will see that the document is actually on the docket record, but there isn't a coversheet on the document
- If you check the logs, Service was sent appropriately.

**Scenario 2**
- Log in as a docket clerk
- Open your console
- Navigate to a case
- Click Create and then select PDF Upload
- Upload a very large document
- Be sure to select one of the Unservable document types that receive a cover sheet upon saving to the docket record. (Letter of Appeal, Hearing Exhibits, Trial Exhibits, U.S.C.A, Bounced Service Email, or Returned Mail).
- Click Save entry
- You will get the spinning wheel for awhile
- The spinning wheel will stop, and you will be navigated back to the Upload PDF page with an error stating that "The system is taking too long to respond".
- The network tab will show that it errored out on the `court-issued-order` step, and the console tab shows the 504, and a cerebral error thrown by sequence "uploadCourtIssuedDocumentSequence"
- If I navigate to the docket record, the document was not saved.

**Scenario 3**
- Will need to verify that large docs will upload on Paper Petition flow

**Scenario 4**
- Log in as a docket clerk
- Open your console
- Navigate to Section Document QC
- QC one of the Large documents that you eFiled as an External User
- Change the document type (or make any edit that will generate a new coversheet)
- Complete and/or Complete and send message
- Document QC completes successfully/and message sends successfully

External Users
**Scenario 1**
- Log into DAWSON as a Petitioner or Practitioner
- Open your console
- Navigate to one of your cases
- Click File a document
- Select a document type and select a big document from your computer (the document I was testing with was approaching the 520 MB limit - did not receive the error))
- Fill out the information for the document
- Submit document
- You will get the spinning wheel
- After awhile, you will get the "Your Request could not be completed" pop-up.
- Check the console tabs and network tabs
- Depending on how far the document got, you may have an error for the validate or the coversheet step.
- Navigate to the docket record
- Did the document end up on the record? Probably not?  
- We think this behavior may vary based on how far the upload goes.  

**Scenario 2**
- Will need to verify that large documents can be uploaded without error when eFiling a Petition.

**Expected Behavior**

**Actual Behavior**
A clear and concise description of what actually happened.
**Screenshots**

**Internal User**
Internal user - Error on Network tab after attempting to upload a big doc. Errored out on 'coversheet'
<img width="1517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d6876961d587e16ad8e3c318883453588931dc5/image.png" alt="image.png" />

Internal User - Error on Console tab after attempting to upload a big doc.
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d838045cdce541e8b145789272c4ce3ad527c673/image.png" alt="image.png" />

Internal User - Big doc ended up on docket record, but there is no coversheet on this document.
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXREQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc3baf2ce6b26b923dfc729dae75cb224c4bc402/image.png" alt="image.png" />

Logs
Docket clerk adds paper filing of big doc, logs do not show error when filtering by docket clerk. We see that the doc got to the 'upload-policy'. If filtering by 504, we would see this on the API Gateway.
<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a585ecd3d625701e70dcca7825a735f40fe73618/image.png" alt="image.png" />

Internal user - Upload PDF - unservable documents - network tab
<img width="1593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzY2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90fb10ab2775864c66bb745d96f80bcc5f5dba54/image.png" alt="image.png" />

Internal user - Upload PDF - unservable documents - console
<img width="1859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEM2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6b226c45734ee0bae1af3c5ab72c41089403ff4/image.png" alt="image.png" />

**External User**
External user attempts to upload a document to a case - Receives a "Your Request Was Not Completed" error on the 'validate' step.
<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--075026b1d05e47a119feda1dac4ac340c6d8b8b9/image.png" alt="image.png" />

Logs - We see that the document upload didn't get past 'upload-policy'
<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e047b285906464aab3eeed6459319621061fb98f/image.png" alt="image.png" />

Logs - We see the 504 at the validate step
<img width="1492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5EQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8aceb0dfe86139e6044b5a08243309c9a49ea76d/image.png" alt="image.png" />

Logs - Here is a screen grab from Production - showing 504 errors on the validate or coversheet step when large documents are attempting to be uploaded (we validated that the 504's from 2/6 were exhibit documents being uploaded by the IRS to a case. At this point in time, not sure if they had success or not since each attempt creates a new document ID)
<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da7a1d465eefb9e020e6d87df1c80e287dd6728a/image.png" alt="image.png" />

Logs - Sept 27 in Production from the FB case where we also see 504 errors when those big Exhibit docs were uploaded.
<img width="1232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f93f9283096e8002cb4be066ec2f5ad10929b08/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
@cruzjone-flexion @nechama-krigsman I was testing other things and I attempted to upload that big document as a Petitioner that was just creating a case.  Some interesting behavior.

1. Log in as a Petitioner
2. Create a case
3. Be sure to upload the big document in the Petition filing flow (either for the petition, IRS notice, or STIN)
4. Upload progress bar went over 100% (see screen grabs)
5. Receive a 504 error, and it takes the user back to the review and submit case screen.  
6. Interestingly though, the Petition was submitted to the Court.
7. See Case 1954-24 on Test.  
8. I also notice that the Attachment to Petition file (this was the big file I attempted to upload) has 0 pages.  
9. Very similar behavior as what was reported above, just in a different workflow.

<img width="1192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71ae0d981d65ee19285d50be93d090cdbaa05f22/image.png" alt="image.png" />

<img width="1202" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3llQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba3c0a6a310f20d440d2d6fa785a6c102aa0aad1/image.png" alt="image.png" />

<img width="1024" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4508ce684f7e2e8e2e09da3de9055b7db0f3379e/image.png" alt="image.png" />

<img width="1733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a50c776e6b861f11f702e716d07edbe9c1b8d12f/image.png" alt="image.png" />

<img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeENlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccab4d77bd4edbca781eb7d0838066e7c42da85e/image.png" alt="image.png" />

**Comment by cruzjone-flexion** [comment]
Make sure we verify that versioning is still available in the S3 bucket. Should still have the ability to look at the original PDF the user uploaded.

**Comment by ttlenard** [comment]
@nechama-krigsman @cruzjone-flexion While testing today I found that the external flow is still behaving the same way, I'm getting a 504 error still.  Also, after talking about this, we identified another scenario where a Court user could upload a PDF as one of the unservable documents  (these get a coversheet.)  I've added this scenario to the information above.  

Sounds like we have 5 scenarios that we would want to test with:
1. Internal user - Add paper filing
2. Internal user - Upload PDF and select one of the 6 Unservable documents.
3. Internal user - Add paper petition
4. External User - Add eFiled document
5. External User - eFile a petition.

Edit 3/25/24
- Another workflow to test is if there is an eFiled document, and when Docket QC's the document, they update something in the document metadata that could cause an updated coversheet to be added to the filing (ex: changing the document type).

**Comment by ttlenard** [comment]
After chatting some with @cruzjone-flexion, he mentioned that the fix for this bug utilized websockets.  The IRS blocks websockets, so the solution to fix this issue will need to be reconsidered.

**Comment by ttlenard** [comment]
Some observations of the log entries.  I notice that we now are seeing many log entries that have "fetch" in them.  Not sure if this is ok?  We would see an increase in log entries for any user adding in a document. @jimlerza @jtdevos @mmarcotte 

This is what it looks like for a Large document:
<img width="601" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVltQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ce5545c6a602b2c35fcffca4517d44e6610d38f/image.png" alt="image.png" />


This is what it looks like for a "normal" sized filing (2-3 pages)
<img width="1124" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51daf97a535ebdd81b24de7203038dfd90e5aa27/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
@nechama-krigsman @cruzjone-flexion Some testing feedback.

I was testing what would happen if an external user filed a big doc (this worked fine), but then when Docket QC's the document, they have to update the document type and add data to the additional information 1 text box and checked the add to the coversheet when QCing.  After clicking complete and send message, I got the neverending spinning wheel. I was watching the logs and the Network tab. Seems things were going ok, until I got an Auth/refresh.  After that, things seemed to stop? 

Also, saw this type error in the console - not sure if this is related?
<img width="1759" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01yQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ec97ba2424d5f382c1479e106c39ff4d23cf862/image.png" alt="image.png" />


This is when things kinda stopped:
<img width="1572" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c9b82cf8c2d4b16ebf831e40613459109399a45/image.png" alt="image.png" />

The logs:
<img width="1316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1VyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fc8a3060248686cb41f17389b1aeeadee6d56d1/image.png" alt="image.png" />

I refreshed the screen, and then received this message:
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--551afa7624da649f2e32c303952ba98e5452ba6a/image.png" alt="image.png" />


I see this in my Processed tab in Document QC. This is the updated document title that I added.:
<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b8cb2a394e4c3da92138ba2b374b61858fcad0e/image.png" alt="image.png" />


After opening the document and reviewing it on the docket record, I see that the updated coversheet was generated, with the updated title. Yay! Looks like the process worked, but the user was stuck watching the spinning wheel.  After over 30 minutes I gave up on it, only to see that it worked. :(

**Comment by ttlenard** [comment]
@cruzjone-flexion  @nechama-krigsman More testing feedback.

I was testing the Court user upload PDF workflow.  After spinning wheel for quite some time, I received a 400 error.  Here is the console:
<img width="1618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d65d40c2b4cc94021e7a57cf9e73c475e2ef81b8/image.png" alt="image.png" />


I don't see any errors in the Network tab.
<img width="1733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--993045b8ee4945f039eedd000bbede74ee16239a/image.png" alt="image.png" />


Here are the logs:
<img width="1507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6696f795ae9fb9cc1e73be62ab691836a3942c2e/image.png" alt="image.png" />

**Comment by nechama-krigsman** [comment]
@ttlenard regarding the 400 error the user gets while uploading large PDFs using the upload PDF workflow, now that we fixed the 504 errors and can process the file we are running into a separate issue. When scraping the PDF, we are getting an out of memory exception. As we discussed, we need to create a separate task to optimize scraping the pdfs.

**Comment by ttlenard** [comment]
Testing looks good. I was able to get through all the scenarios with the exception of the internal user PDF upload.  We'll write up a separate ticket for that.
