### ISSUE TITLE
BUG: 400 Error When Non-Logged In User Attempts to Print Docket Record

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8618]
**Describe the Bug**
When a non-logged in user navigates to a case and clicks the "Printable Docket Record" link, a 400 error is displayed. This is happening in both TEST and STAGING. This also happens for the Terminal user.

**Business Impact/Reason for Severity**
High

**In which environment did you see this bug?**
Test/STG

**Who were you logged in as?**
Nobody.

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Demoing other functionality

**To Reproduce**
1. Go to Case Search w/o logging in as a user
2. Search for and navigate to a Case docket record
3. Click the "Printable Docket Record" link on the screen

**Expected Behavior**
PDF of docket record generates, user is presented w/ a modal telling them the document is ready for viewing

**Actual Behavior**
400 error displayed

**Screenshots**
Output from browser console when this happens:

<img width="1798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1BQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5af154038bf47d266d180ea5227cd337bb4e8168/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by codyseibert** [comment]
I tried reverting exp5 to commit 31056b5602276f9dfd8409f7f245f4716b32c703 and it's working fine with that commit.  My next steps are going up the commits and try to figure out what might have caused this to break.

**Comment by codyseibert** [comment]
```
# status: waiting for both good and bad commits
# good: [3f45fb58af93d2d2df7dbcb35b99db4ba9997409] devex: remove deprecated stream-event-id
git bisect good 3f45fb58af93d2d2df7dbcb35b99db4ba9997409
# status: waiting for bad commit, 1 good commit known
# bad: [2d77bc733d16ca8aeff079ae1411cd4d3dbdb8a6] Merge pull request ustaxcourt/ef-cms-flexion#4603 from flexion/dep-updates-2024-01-22
git bisect bad 2d77bc733d16ca8aeff079ae1411cd4d3dbdb8a6
# bad: [fb6bf491bb4641f55b2bb56d990e89415fd0cbd0] dependencies: update aws terraform provider
git bisect bad fb6bf491bb4641f55b2bb56d990e89415fd0cbd0
# bad: [26fb961f89396ac9b29c84fec387ccde5adf5666] Merge branch 'dependency-updates-week-of-jan-15-2024' of https://github.com/flexion/ef-cms into dep-updates-2024-01-22
git bisect bad 26fb961f89396ac9b29c84fec387ccde5adf5666
# bad: [a9c3fa72ce169498626055bdee473729a9653036] dependencies: update sass
git bisect bad a9c3fa72ce169498626055bdee473729a9653036
```

one left
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[b543a76dce3959a20058bcb5592433d923af4c0a] dependencies: minor and patch versions in main package.json

all of these failed with feature flag issues

**Comment by codyseibert** [comment]
bad - 9036fb8a5176c70fc7492cb290fb148eb57ca469
good - 3f45fb58af93d2d2df7dbcb35b99db4ba9997409

**Comment by TomElliottFlexion** [comment]
PR: https://github.com/ustaxcourt/ef-cms/pull/4673
