### ISSUE TITLE
Add a script to handle the resending of temporary passwords

### ISSUE THREAD

**Issue by Anthony-Calderaro** [ustaxcourt/ef-cms#862]
We should be able to make a script that is able to something similar to the following workflow:
- [ ] Pull all the relevant tickets from Zendesk based on a specific `tag`
- [ ] For each ticket, grab the email address of the sender or from the "email of user" field and check their credentials in Cognito.
- [ ] Reply and close out the ticket based on the status in Cognito:
  - [  ] RESET_TEMPORARY_PASSWORD should return the `resent` snippit from textEditor and execute `resendCredentials.py`
  - [ ] CONFIRMED should return the `confirmed` snippit
  - [ ] If no email is in cognito, skip that user and return the ticket number, indicating that the ticket needs to be reviewed individually.

**Comment by mmarcotte** [comment]
done
