### ISSUE TITLE
Petitioner - Edit contact info - change Country dropdown to radio btns

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8625]
As a petitioner, so that I can see my options clearly, I need to be able to view options up front.

If a petitioner wants to edit their contact info in a case, the country selection is a dropdown that has only two options. We’d like to change this to radio btns to make the options visible without having to click the dropdown. This aligns with the country selection in case search as well as in the new petitions efiling flow.

Pre-Conditions:
none

Acceptance Criteria:
Change the country dropdown to two radio btns (United States, International)
Determine if user documentation needs to be updated (Tenille): Y / N

<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--297bcd19f45cd91160e97e13a638f1c494b6f7a4/image.png" alt="image.png" />

**Comment by jasonfu9966** [comment]
"Country" appears in seven places:
- Contact Edit: when a petitioner changes their contact info on a case
  - Look for the box that says "This form will automatically create and submit a change of contact information notification for this case. Please ensure your information is accurate before submitting."
- Primary Contact: when a petitioner is creating a case and enters an address
- Secondary Contact: when a petitioner is filing on behalf of self and/or someone else, like a deceased spouse
- When an internal user edits a petitioner's information
- When a practitioner adds their contact info
- When a practitioner edits their contact info (on a case?)
- Adding a petitioner to a case

**Comment by ttlenard** [comment]
Testing Feedback @jasonfu9966 

I noticed some funky behavior while testing.
1. Log in as a Petitions Clerk
2. Click on Document QC
3. Click Add New Petition
4. Upload a Petition document
5. For party type, select Petitioner and deceased spouse
6. Fill in the information for the petitioner
7. For the deceased spouse, select the international radio button
8. Notice that the screen jumps down, and you have to scroll back up to enter in the data for the deceased spouse.

**Comment by ttlenard** [comment]
@jasonfu9966 

Need to add another scenario to your above list:  

- When a Petitions Clerk Adds in a Paper Petition

**Comment by ttlenard** [comment]
@katiecissell @swongCO I'm going to pass this design debt as is, but can you please add in a new design debt card to fix the screen jumping issue I found while testing?  See comment above.

cc: @jasonfu9966
