### ISSUE TITLE
Petitioner - Edit contact info - spell out State dropdown list

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8626]
As a petitioner, so that I can make the right selection, I need to be able to view the full name of states.

If a petitioner wants to edit their contact info in a case, the state selection is a dropdown that lists only abbreviations, including for territories, military bases, etc. We’d like to list the full name of all the options. This aligns with the state selection in case search as well as in the new petitions efiling flow.

Pre-Conditions:
none

Acceptance Criteria:
Spell out all the items in the state dropdown (see case search for reference)
Determine if user documentation needs to be updated (Tenille): Y / N

<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73a51e25e7101f07b50a55be27db244b1c353a06/image.png" alt="image.png" />

**Comment by katiecissell** [comment]
Areas where State dropdown was changed:
 - Petitioner: case info - edit contact info
 - Petitioner: create petition Petitioner info et al
 - Petitioner: Create petition Petitioner and spouse info
 - Docket Clerk: Add Petitioner to case
 - Practitioner: Edit contact info
 - Practitioner: create petition Petitioner info et al
 -Admissions clerk: Add practitioner to Dawson

**Comment by ttlenard** [comment]
Testing Feedback @pixiwyn @katiecissell

Looks like a practitioner is now unable to change their contact information on Test. The only available option for a private practitioner is to update their email address, but they should be able to update their contact information as well.

To see the difference, compare between Test and Staging:

1. Log in to Test as a private practitioner
2. Click on the person icon and then select My Account.
3. The only available option for you to edit is the email account, there is no contact info available:
<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGJEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05d8626e1002cf1007d303b1e2ed9caef5d964b5/image.png" alt="image.png" />

1. Log into staging as a Private practitioner
2. Click on the person icon and then select My Account
3. Notice that you have the ability to update the contact info for the practitioner. This is how it should be:
<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5EQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20be5c0d4d63f35d9ac50605dba243b54d6cbbfd/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
*Update related to the comment above. Seems this may be a caching issue.  If you first log in as a Petitioner, go to the my Account page, you will see the normal petitioner screen where you can only edit your email. Log out, then log in as a Private practitioner. Go to the my account page, you will see the same thing that a petitioner sees, where you cannot edit your contact info.  This will also happen in the reverse.  If you then log in as a Petitioner, you will see your contact info, and you shouldn't see it.

**Comment by pixiwyn** [comment]
We were able to show that the issue mentioned was pre-existing, can we write up a bug ticket for that? @cholly75

**Comment by ttlenard** [comment]
@pixiwyn I will write up a bug ticket for the stuff mentioned above. Thanks!

Update: Bug ustaxcourt/ef-cms#8711
