### ISSUE TITLE
Remove extra checkmark from file upload component

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8631]
As a petitioner, so that I am not confused, I need to not see extra checkmarks that do not provide meaningful information.

Pre-Conditions:

none

Acceptance Criteria:

When a document is filed, there is not an extra green checkmark icon next to the header of the file upload component.

When a supporting document is added, there is not an extra green checkmark icon next to the header of the file upload component.

Determine if user documentation needs to be updated (Tenille): Y / N

Pain Avoided/Frustration Saved:

Breadth/Pervasiveness of Problem:

We think these two might be the last of the file upload components that have an extra checkmark. But if an engineer checks the code and see them elsewhere…then ideally we’d remove them all at once.

Complexity of Problem (Low, Medium, High) and Why it's Complex:

low?

<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b9721f0164a874ba365e6aafeef71f8f5235306/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d8e6556b2141f6ec73a583dc966e22618b76a3f/image.png" alt="image.png" />

**Comment by swongCO** [comment]
**UX feedback**
Found another flow while testing 10350: as IRS practitioner, File First Document

**Comment by akuny** [comment]
I double-checked in test and the extra checkmarks are not displaying when filing a document as an IRS practitioner, as desired.
