### ISSUE TITLE
Remove cancel upload and hidden button on upload progress modal

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8633]
As a Petitioner, so that I am not confused about my upload, I should not be able to see or interact with any links in the progress modal.

Pre-Conditions:
none

Acceptance Criteria:
- When the petitioner is filing a petition or documents and the upload progress modal is shown at the end, remove the cancel upload link and don't allow interaction with any hidden buttons.
- Determine if user documentation needs to be updated (Tenille): Y / N

Pain Avoided/Frustration Saved:
Confusion about what that hidden button does and preventing them from cancelling the upload

Breadth/Pervasiveness of Problem:
We think its just for petitioners?

Complexity of Problem (Low, Medium, High) and Why it's Complex:
medium?

<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93157a84382c7b0e5ed825b7a39eb7fefe35ab54/image.png" alt="image.png" />

<img width="1652" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd51197d77469d59348a4f361f594cda74367287/image.png" alt="image.png" />

<img width="1799" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ca7fb0aa9cc5914060e98fb8d40a4fee06ae226/image.png" alt="image.png" />

**Comment by En-8** [comment]
After chatting with UX, we opted for removing the close link (upper right corner) and Cancel Upload button (middle, under progress bar) from the base file upload progress component, which is going to impact anywhere this component is shown, not only petitioners. Here are the potentially impacted locations:

- Review page of ‘Represent a Party’ flow (as IrsPractitioner or privatePractitioner)
- Review step of File Document (associated practitioner or petitioner)
- Paper Filing as Court user
- File petition workflow, final step (as private practitioner)
- NEW file petition workflow, final step (as petitioner)
