### ISSUE TITLE
Remove PDF icon on review page for filings

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8636]
As an external filer, so that I can not be confused or lulled into a false sense of security, I need to not see a PDF icon when it’s not a PDF.

Pre-Conditions:
none

Acceptance Criteria:
When filing a document, on the review page do not show a PDF icon next to the link of the document.
This is specifically for the “File a document” flow for external filers.
Determine if user documentation needs to be updated (Tenille): Y / N
Pain Avoided/Frustration Saved:
It can be confusing if they uploaded a non-pdf and it shows a pdf icon.

Breadth/Pervasiveness of Problem:
This ticket is removing the file a document flow pdf icons, the new petitions flow will remove the icons for the petitions flow so external users shouldn’t see this icon at all.

Complexity of Problem (Low, Medium, High) and Why it's Complex:
low

<img width="1116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2ZCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a51672c66f17c2dffed87b0189f47b49e750c142/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
Testing Feedback @akuny 

Looks like the pdf icon is still displaying on mobile devices:
<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi8xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d00f165eadcaa3e1672b4f6af01bdb9c0963cc11/image.png" alt="image.png" />

**Comment by katiecissell** [comment]
As a part of this ticket, we are fixing the pdf link to appear as a link when in portrait mode in mobile. Its a link in any other view currently so this will match the behavior on other screens.

**Comment by ttlenard** [comment]
@akuny Some more testing feedback. Not sure if you are already aware of this or not, but I am seeing the PDF icon when a practitioner files an Entry of appearance and uploads their EA.

<img width="1161" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70d47832125ccb3f1ce8775a3aaf85e1246a8471/image.png" alt="image.png" />

**Comment by akuny** [comment]
@ttlenard Thank you for catching that--I'll make sure they're removed when this issue goes to review next time.
