### ISSUE TITLE
Opex: Refactor API deployment process

### ISSUE THREAD

**Issue by TomElliottFlexion** [ustaxcourt/ef-cms#8638]
## Acceptance Criteria
- I’m looking into a way to simplify our terraform complexity for deploying lambda functions to combine them all into a single file built with a simple webpack (or esbuild) command in the future, but use lazy loading to prevent slower cold starts.
- API uses true blue/green deployment
- Webpack is replaced with esbuild (everywhere)

**Comment by zachrog** [comment]
This story also completes ustaxcourt/ef-cms#8650.
