### ISSUE TITLE
Upgrade sparticuz/chromium and puppeteer

### ISSUE THREAD

**Issue by TomElliottFlexion** [ustaxcourt/ef-cms#8649]
## Acceptance Criteria
- sparticuz/chromium: 114.0.0 -> 112.0.0
- puppeteer: 20.7.3 -> 19.8.5
- puppeteer-core: 20.7.3 -> 19.8.5

**Comment by ttlenard** [comment]
@rachelschneiderman Some testing feedback.

On the Test Environment, I'm seeing a blank PDF page that is getting generated with the Pretrial Memorandum when calendaring.  Right now I am assuming that it has to do with the Node update and font sizes, can you confirm? Note that I am NOT seeing this behavior on the IRS environment.

I've attached both print for paper service documents.
 
[Test_Env_Calendar_PrintPaperService.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUV2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32c7381a239a1f5af61f69a5b0dcf1c16841f4de/Test_Env_Calendar_PrintPaperService.pdf)

[IRS_Env_Calendar_PrintPaperService.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUl2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9d4230c0b17a49ded1a15db0319ecdfdb27d5e7/IRS_Env_Calendar_PrintPaperService.pdf)

**Comment by ttlenard** [comment]
Retested and the extra blank page is no longer appearing for the Pretrial Memo. Thanks @jasonfu9966
