### ISSUE TITLE
Remove the PDF Layer terraform logic needed for the new pdf generation lambda

### ISSUE THREAD

**Issue by TomElliottFlexion** [ustaxcourt/ef-cms#8650]
As an engineer, so that I can keep our terraform code clean, I need to remove the code associated with the use-layer-state feature flag after prod has been deployed at least two times.

## Pre-Conditions
  - none
## Acceptance Criteria
- all instances of current-use-layers and deploying-use-layershave been removed, including the terraform ternary statement which decides when to use a layer on the lambdas or not.

## Pain Avoided/Frustration Saved
- less code to maintain

## Breadth/Pervasiveness of Problem
  - unknown

## Complexity of Problem (Low, Medium, High) and Why it's Complex
  - low

**Comment by jhansen-flexion** [comment]
This story was completed with 10296.
