### ISSUE TITLE
BUG: User stuck in loop when logged in during deployment color switch/cleanup

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8657]
**Describe the Bug**
If a user is logged in when the color switch/cleanup step happens during a deployment, they are presented with a spinning wheel and endless looping in DAWSON if they are on the browser tab or attempt to take action (we've seen both happen). DAWSON appears like it is trying to re-establish authentication and failing, yet it will keep attempting to do so.

Refreshing the page or closing the tab and re-logging in appears to clear the problem.

**Business Impact/Reason for Severity**
Med - problem is confusing for users who may stay logged in during a deployment.

**In which environment did you see this bug?**
TEST

**Who were you logged in as?**
Docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Nothing

**To Reproduce**
1. Log in as any user to a given environment
2. Make a deployment to that environment 

**Expected Behavior**
User is either logged out or (prior behavior) sent back to home page in DAWSON at some point in the deployment

**Actual Behavior**
User appears to be stuck in a loop attempting to re-authenticate or process the last user action taken prior to deployment color switch step?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by En-8** [comment]
We're fairly certain after trying to reproduce this in an experimental environment that this ended up addressed within the context of https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10368.

We recommend closing this one @cholly75  @ttlenard, unless you feel differently.

**Comment by ttlenard** [comment]
This appears to be fixed by ustaxcourt/ef-cms#8701.
