### ISSUE TITLE
SPIKE: Investigate session timeout/refresh behavior w/ new login schema

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8658]
This is a spike to investigate the current behavior w/r/t session management and the auth token refresh. 

1) Desired behavior is that after ~1hour of idle time (potentially across multiple tabs) the user is asked via modal whether they're still present, the answer to which determines whether their token is refreshed or they are logged out.

2) Prior behavior w/r/t logging in forced users (we _think_) to always have to manually log back in entering credentials when closing all their active browser tabs (N.B.: Tenille has mentioned that she in the past has been able to recover closed tabs and continue working, so perhaps this is just a case where the natural timeout after 1 hour still occurred behind the scenes.)

We have had reports that either or both of (1) and (2) may not be true in some cases anymore, as some users have reported that they're automatically logged back in using their prior credentials after having closed the app for a long period of time. 

We want to figure out A) how the session timeout operates currently, and B) what impact the new login mechanism has on user behavior across sessions/tabs/login instances.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by pixiwyn** [comment]
From what I can tell, if you login, open three tabs, after the timeout (55 mins) will show the modal "Are you still here?" with yes button. Then if you leave it will log you out after (5 minutes). The other two tabs get stuck loading (see screenshot), and one will say you've been logged out (see screenshot).

Then if you close your browser, before that 55 minutes is up, and your cookie save (most will unless doing something specific with a plugin), then when you reopen Dawson, will relog you in, and start the timer over again.

Each browser/device follows this independent of each other. 

<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHY1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80af8523442a3319d84ab1a7c5aa47a40da8264f/2024-03-20_15-18-24.png" alt="2024-03-20_15-18-24.png" />

<img width="1195" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHo1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2a9882f40bd6a2ffaa000860dfbd09c26cf72ad/2024-03-20_15-22-50.png" alt="2024-03-20_15-22-50.png" />

**Comment by pixiwyn** [comment]
The cookie itself is good for 24 hours until it gets invalidated by the idle timeout from above, 24 hours has elapsed, or something else cleaned up your cookies.

**Comment by ttlenard** [comment]
Test results for the idle login was as I expected.
1. Yesterday evening around 9PM MT - Log in to Prod as general user
2. Navigate to any page in DAWSON
3. Click the X in the top right to close the browser (do not log out of DAWSON)
4. This morning around 5:50AM MT - Navigate to the DAWSON homepage
5. Click Log in
6. I see the URL goes to this: https://app.dawson.ustaxcourt.gov/login, but then switches to this https://app.dawson.ustaxcourt.gov/document-qc/section/inbox without me doing anything.
7. No log in page, user is automagically navigated to their DAWSON page (for general user it was the document QC page).
8. The steps above can be repeated over and over this AM.

**Comment by cholly75** [comment]
@pixiwyn - after discussion w/ devOps, the behavior we'd like to enforce is a post-activity 1 hour session timeout even when the browser has been closed and the user isn't seeing a modal. This should make our timeout policy more uniform regardless of whether someone has an open session or not. Let's chat today about it.
