### ISSUE TITLE
Prevent due dates in the past

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8663]
As a court user, so that I can prevent errors from happening, I need the calendar picker to not allow me to pick due dates in the past.

AC:
- User cannot select a past date in the date picker.
- Determine if user documentation needs to be updated (Tenille): Y / N

When you create a trial session, there is a start date selector that doesn't let you pick before today that you can probably imitate.

List of locations of calendar pickers for due dates:
Stamp Grant
Add deadline
edit deadline
<s>Edit submitted/CAV
Edit pending motions</s> (dates can be in the past due to closed cases)
Docket entry for Orders that have a date picker

Screenshots:
Stamp grant
<img width="697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c127b635a1f093e64d4a123935c24540c50a0a69/image.png" alt="image.png" />

Add deadline:
<img width="829" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c460d665e854bce25e97c2642037d739110bbfa/image.png" alt="image.png" />

edit deadline:
<img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDRlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75c0b206470cf732dc6dfaa963f263c55f5bb129/image.png" alt="image.png" /> 

Docket entry for Orders with date picker:
<img width="597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0o2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--827543ef9c144e9a1b37ae61c26016ceb864198e/Screenshot%202024-04-19%20at%202.13.58%E2%80%AFPM.png" alt="Screenshot 2024-04-19 at 2.13.58 PM.png" />

**Comment by swongCO** [comment]
**UX review**

Stamp grant passed.

Something weird going on with deadlines. Some that I tested passed while others did not. Screenshots where past dates are showing:
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0g4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7cae7111a3cd0942d413f3674767dbae019999d/Screenshot%202024-05-21%20at%2011.52.16%E2%80%AFAM.png" alt="Screenshot 2024-05-21 at 11.52.16 AM.png" />
<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1A4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f61d0c9049123e0b6edfb8d5ed30a0e3e709eb98/Screenshot%202024-05-21%20at%2011.52.39%E2%80%AFAM.png" alt="Screenshot 2024-05-21 at 11.52.39 AM.png" />
___
Orders - not sure if these are related but certain orders (examples below but also any filing fee orders) now have the entire calendar unselectable:
<img width="599" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Q4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--998592737ecbe57cf8b3b002477c519d7e224eb5/Screenshot%202024-05-21%20at%2012.13.26%E2%80%AFPM.png" alt="Screenshot 2024-05-21 at 12.13.26 PM.png" />
<img width="599" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1g4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbb3d39d61b41393e5940e278af0b2db47dc3891/Screenshot%202024-05-21%20at%2012.13.54%E2%80%AFPM.png" alt="Screenshot 2024-05-21 at 12.13.54 PM.png" />

**Comment by ttlenard** [comment]
I was able to manually input a past date in the due date field for a deadline in case 8956-24:
<img width="686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3M3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5055a605cb677812fb03cfbdc92cf2413f2a5102/image.png" alt="image.png" />

I saved the new deadline, and it saved without any validation errors:
<img width="1800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzA3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5343cf8a35b3e9f94a50f138b6e44331c23dccc5/image.png" alt="image.png" />

I could also do this same workflow when editing a deadline, and it saved without a validation error.

When manually inputting a date in the past for stamp, orders, or trial sessions, I get the validation error still.

I also notice that we have some inconsistent validation error messages in regards to past dates. Some say "Enter a valid date", while some say, "Due date cannot be prior to today. Enter a valid date."  Question for @swong and @katiecissel - did you want these validation errors to be consistent with not being able to select dates in the past?

**Comment by katiecissell** [comment]
It would be best if we could have all errors trigger by a too early due date say "Due date cannot be prior to today. Enter a valid date." @akuny do you foresee any problems with adjusting that validation message?

**Comment by akuny** [comment]
Following up on discussion with @ttlenard and @cholly75, the team has decided to move forward with restricting users' access to past dates in the date picker, but not to move forward with introducing server-side validation logic to ensure that new deadlines are not created in the past. This is due to the knock-on effect that that change would have on migrations.

**Comment by ttlenard** [comment]
Testing Feedback:

The validation error message indicates that the user can pick yesterday, but the date picker doesn't let you pick yesterday, and also yesterday is a date in the past. Not sure why this validation error message is different than what was indicated in the comments above?
<img width="966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36035d4137dff245c98e7ca04621e20288cf01d0/image.png" alt="image.png" />

<img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f43c70ea7eceb249b9d2121411697ec299f121c7/image.png" alt="image.png" />
