### ISSUE TITLE
AWS v2 -> v3 conversion: S3

### ISSUE THREAD

**Issue by jimlerza** [ustaxcourt/ef-cms#8669]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 S3 SDK have been converted to the AWS v3 S3 SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context, so all downstream uses will need to be checked and adjusted if necessary.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by jhansen-flexion** [comment]
Blocked: Waiting for Lerza to return, need concensus on a decision.

**Comment by zachrog** [comment]
Affected areas with PDF viewing
- [x] Printing reports
- [x] Creating a Case - Petitioner/Practitioner
- [x] Previewing documents uploaded/scanned when Petitions clerk creates a paper filed case
- [x] Reprint paper service pdf
- [x] Zipping documents (Docket record/trial session working copy)
- [x] Stamp preview
- [x] Entry of appearance
- [x] Opening/preview document
- [x] Custom Case report csv.
- [x] Cold case report csv.
- [x] Trial session Planning Report.
- [x] Todays Orders/Todays Opinions
- [x] Print Receipts
- [x] Printable docket record
- [x] Print for paper service docs 
- [x] Print version of session info
- [x] View full PDF from Drafts
- [x] View full PDF from Docket Record
- [x] Apply signature to Order
- [x] Edit Order and Edit Order Preview
- [x] Add/Edit/View Full PDF - Correspondence
- [x] Previewing docs in Messages
- [x] Previewing docs in QC
- [x] Previewing docs in PDF upload
- [x] Viewing the NOTR from the Print confirmation link on the case info tab
- [x] Practitioner Records
- [x] Order Generation
- [x] Order generation with Multi-docketing
- [x] Test zipping up documents on a super-size case (not Facebook)
     - [x] Test with 11019-19 (this one I know stalls out on Prod - this was reported to us, but Prod has over 100 more documents than on test as of 6/28)
     - [x] Test with 7671-17 (this one is a real case on Appeal where the Court downloaded documents in this case)
- [x] Test zipping up large trial sessions (did LA - Pugh 9/9/24)
