### ISSUE TITLE
AWS v2 -> v3 conversion: SES

### ISSUE THREAD

**Issue by jimlerza** [ustaxcourt/ef-cms#8671]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 SES SDK have been converted to the AWS v3 SES SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context, so all downstream uses will need to be checked and adjusted if necessary.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by jtdevos** [comment]
I've been trying to determine the extent to which SES is used in the code.   Here's what I've found so far. 

Direct access to SES: 
- `web-api/src/persistence/messages/sendEmailToUser.ts`
- `web-api/src/applicationContext.ts::getEmailClient`
- `web-api/src/dispatchers/ses/sendBulkTemplatedEmail.ts::sendWithRetry`
- `web-api/src/persistence/ses/getSesStatus.ts::getSesStatus`

Files/methods that reference SES indirectly:
- `web-api/src/applicationContext.ts::getMessageGateway::sendEmailToUser()`
- `web-api/src/lambdas/sendEmails/send-emails.ts` (pulls item off queue then sends via applicationContext.getMessagingClient())


Files / methods that utilize SQS for queueing emails:
- `web-api/src/applicationContext.ts::getMessagingClient`
- `web-api/src/dispatchers/ses/sendBulkTemplatedEmail.ts::sendBulkTemplatedEmail`
- `web-api/src/persistence/messages/sendEmailEventToQueue.ts`
- `shared/src/business/useCaseHelper/email/sendEmailVerificationLink.ts`
- `web-api/src/lambdas/sendEmails/send-emails.ts`: lambda that monitors queue then sends email
 
Some other outstanding questions that I have: 

- why does applicationContext expose email sending multiple places, e.g.
    - `ctx.getEmailClient()`
    - `ctx.getMessageGateway().sendEmailToUser()`
    - `dispatchers/ses/sendBulkTemplatedEmail.ts::sendWithRetry` (also why is this in the sendBulkTemplatedEmail file as it does not appear to send email in bulk or using a template?)
- there are two(three, really) implementations of sendBulkTemplatedEmail() 
    - applicationContext::getEmailClient() (ref to SES which has sendBulkTemplatedEmail() method)
    - dispatchers/ses/sendBulkTemplatedEmail(): utilizes SQS to enqueue bulk email(i assume)

**Comment by jhansen-flexion** [comment]
@jtdevos @jimlerza This story is reportedly breaking emails on test. It may need to be rolled back from this week's release. Let's discuss.
