### ISSUE TITLE
Practitioner: Online Petition Generation

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8672]
As a practitioner, so that the instructions for generating a petition are clear, I need verbiage changes to the online petition generation flow.

With the development of the online petition generation wizard, we want to make sure that in the event a practitioner is filing on behalf of the petitioner that the language in the flow makes sense when asking for information/giving instructions to the practitioner. UX has reviewed the existing language and identified where we would want to change verbiage based on the fact that the user is a practitioner rather than a petitioner.

Additionally, the resulting generated PDF for the petition should contain the practitioner's information associated with their DAWSON user account (see mockup attached).

## Pre-Conditions
##5512

## Acceptance Criteria
* Practitioners filing a case can use the petition generation workflow
* Language in online petition generation flow is adjusted for practitioner use as per mockups provided by UX
* Workflow behaves as petitioner online petition generation
* Generated petition PDF contains practitioner information derived from their DAWSON login information

## Notes
* Allow time for discovery 

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX Notes:

See [Figma File](https://www.figma.com/design/6uihfDrN6nGBPonTdIZ8lq/USTC-%7C-5512-Petitioner%3A-petition-efiling-flow?node-id=576-414) for updates (comments and text indicated with magenta rectangles):
- end to end flow
- petitioner info
- generated pdf

**Comment by ttlenard** [comment]
- [ ] Need to be sure that when a practitioner clicks on the close link in the upper right corner of the "are you sure you want to cancel?" pop-up modal, the workflow doesn't start them all the way over.  We fixed this as part of ustaxcourt/ef-cms#7175, but this issue is still present with the practitioner flow.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Caseless Practitioner logs in to DAWSON; New Welcome page displays.

- Log in to DAWSON as a private practitioner that does not have any cases associated with their account

Expected Results:
- [x] **NEW FUNCTIONALITY** - Welcome page displays for the private practitioner user (see mockup).


#### 2) Caseless Practitioner clicks on the Create a Case button; How to create a case screen displays for the Practitioner.

- Continuing from the previous test
- Click on the Create a Case button

Expected Results:
- [x] **NEW FUNCTIONALITY** - A New How to Create a Case page is displayed for the Practitioner that is slightly different than the petitioner how to create a case page
- [ ] **NEW FUNCTIONALITY** - Text is updated to be appropriate for Practitioners (see Mockup)
- [x] **NEW FUNCTIONALITY** - There is only 1 accordion menu for the Practitioner.
- [x] Other functionality is the same as the petitioner workflow

*Be sure to do this test with a practitioner that has at least 1 case, they should also see the new Create a case page after clicking on create a case.


#### 3) Private Practitioner clicks the "I'm ready to Start button", Practitioner is routed to the Petitioner information section.

- Continuing from the previous test
- click on the I'm ready to start button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Practitioner is routed to the Petitioner information page
- [x] **NEW FUNCTIONALITY** - Wording on the screen matches the mocks for practitioners
- [x] Other functionality is the same as the petitioner workflow



#### 4) Private Practitioner fills out data for Petitioner; clicks Next; Practitioner is routed to the Petition page.

- Continuing from the previous test
- Select Petitioner from the options and fill out the required data (should match what is in the petitioner workflow)
- Click Next

Expected Results: 
- [x] No change on the Petition page
- [x] Functionality is the same as the petitioner workflow



#### 5) Private Practitioner clicks next; Practitioner is routed to IRS Notice page

- Continuing from the previous test
- After you have filled out the information for the Petition (should match what is in the petitioner workflow)
- Click Next

Expected Results
- [x] **NEW FUNCTIONALITY** - Text is updated on the IRS Notice Page to be appropriate for Practitioners (see Mockup)
- [x] Other functionality is the same as the petitioner workflow



#### 6) Private Practitioner clicks Next; Practitioner is routed to the Case Procedure and Trial Location page

- Continuing from the previous test
- Click Next

Expected Results:
- [x] No change on the Case Procedure page
- [x] Functionality is the same as the petitioner workflow



#### 7) Private Practitioner clicks next, Practitioner is routed to the STIN page

- Continuing from the previous test
- Click Next

Expected Results:
- [x] **NEW FUNCTIONALITY** - Text is updated on the STIN page to be appropriate for Practitioners (see Mockup)
- [x] Other functionality is the same as the petitioner workflow



#### 8) Private Practitioner clicks next, Practitioner is routed to the Review and Submit Case screen

- Continuing from the previous test
- Click Next

Expected Results:
- [x] **NEW FUNCTIONALITY** - There an update on this page to indicate that if there are multiple practitioners representing the petitioner, that they must file appearance documents after the petition has been processed by the court.
- [x] **NEW FUNCTIONALITY** - There a new section that displays the practitioner contact information.
- [x] Other functionality is the same as the petitioner workflow


#### 9) Private Practitioner clicks next, Practitioners Petition document(s) is filed, and they are routed to the Pay Filing Fee page.

- Continuing from the previous test
- Click the Submit Documents and Create Case button

Expected Results:
- [x] No change on the Pay Filing Fee page
- [x] Functionality is the same as the petitioner workflow



#### 10) Practitioner clicks on the docket number link; Previews the generated petition document.

- Continuing from the previous test
- Click on the docket number link in the header
- Next click on the Petition link on the docket number
- Review the generated petition document

Expected Results:
- [x] **NEW FUNCTIONALITY** - The generated petition document that was filed by the practitioner has a new section that includes the Practitioner contact information.
- [x] Other features/data in the PDF are the same as the petitioner created Petition document.



#### 11) Private Practitioner files other Petitions and generates the document, text changes for each petitioner type have been updated for practitioner flow.

- As a private practitioner, create more petitions, but this time select:

**Petitioner and Spouse (not deceased)**

Expected Results
- [x] **NEW FUNCTIONALITY** - Text is updated to be appropriate for Practitioners (see Mockup)
- [x] **NEW FUNCTIONALITY** - There is no section for Spouse's email address or registration for eService
- [x] Other functionality is the same as the petitioner workflow


**Petitioner and Spouse (deceased)**
Expected Results
- [x] **NEW FUNCTIONALITY** - Text is updated to be appropriate for Practitioners (see Mockup)
- [x] **NEW FUNCTIONALITY** - There is no section for Spouse's email address or registration for eService
- [x] Other functionality is the same as the petitioner workflow


**Other/Minor or legally incompetent person**
- Conservator
- Guardian
- Custodian
- Next Friend for a minor
- Next friend for a legally incompetent person

Expected Results
- [x] **NEW FUNCTIONALITY** - Text is updated to be appropriate for Practitioners (see Mockups)



#### 12) Go through Story 5512 Test Cases to ensure all other functionality works (mobile, navigation, Petitions Clerk QC, etc.)

- [ ] Tests pass!


#### 13) Regression test the Petitioner workflow to ensure that functionality hasn't changed

- [ ] This test passes


#### 14) Regression test IRS Practitioner workflow to ensure that functionality hasn't changed

- [x] This test passes

**Comment by ttlenard** [comment]
@nechama-krigsman Here are some minor tweaks that we found while testing the Petitioner OPG workflow that would be nice to incorporate into the Practitioner flow as well.

#### 1) Review and Submit Page

- [x]  IRS Notice section - Display the name of the notice that the user selected, not the case type to minimize confusion.  We currently display the case type on the review page, but then on the PDF we display the notice name
Here is what it says on the Review page:
<img width="1439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlpKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dc75227fb356eba225329ca50b07b718a299027/image.png" alt="image.png" />

Here is what is displayed on the PDF (the selection from the dropdown:
<img width="930" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfe216322782d489736c8f29afdcebafcebfb77a/image.png" alt="image.png" />


#### 2) Auto Generated PDF:  Partnership cases
- [ ] Partnership case - all 3 types - the Tax Matters Partner name/partner name/partnership representative name displays on the PDF, but it is missing the c/o in front of the name. All other case types display the "c/o" just fine.  The only thing affected is the PDF, it looks fine in the DAWSON UI.
<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9a38a64dc323e742904178e4682145f6e576def/image.png" alt="image.png" />


#### 3) Auto-Generated PDF: Petitioner Phone Number
- [x] Add a label titled "Phone" for every case type.  This way if a petitioner adds in "N/A" it won't be confusing.
<img width="498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d266649093843ba9332f4d14e100e3bb53fe5111/image.png" alt="image.png" />


#### 4) Text Update
- [x] Change "of" to "from" on this alert:
<img width="914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33765162639fd48e5aec9edd379017809f312c2e/image.png" alt="image.png" />

**Comment by katiecissell** [comment]
Initial feedback:
Welcome page

- [x]  Remove second line "The Court encourages all petitioners to file documents electronically."

Review page:

- [x] - Theres an odd gap in spacing between state/zip code and phone number

- <img width="656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e4ab8cba4e3e6d0f1cc984c48d6a02231fd9a79/image.png" alt="image.png" />

**Comment by swongCO** [comment]
Feedback - how to create a case page
- [x] Capitalize "p" in petition in the first paragraph

<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmRnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97d15c459b183c34e817395298b18171b2b81386/Screenshot%202024-08-15%20at%203.09.48%E2%80%AFPM.png" alt="Screenshot 2024-08-15 at 3.09.48 PM.png" />

**Comment by swongCO** [comment]
Feedback

- [x] Step 1 - address field validation is not clearing out when toggling from US to International and vice versa
- [x] My Cases page - wrap long names so they aren't cut off (like on step 7 with the docket number)

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2RrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c080d0d37a6510028c34526cb23cd96d69876756/IMG_2290.PNG" alt="IMG_2290.PNG" />

___
Spacing

- [x] Review page - make spacing consistent above and below blue banner

<img width="913" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3RrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--079ce2eae6e1d0e3725e0cb70bec142582f35737/Screenshot%202024-08-16%20at%209.16.38%E2%80%AFAM.png" alt="Screenshot 2024-08-16 at 9.16.38 AM.png" />

___
- [x] Mobile - match spacing under Counsel's Contact Information to Petitioner Information

<img width="393" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3hrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b189cc42f41b278810391c90cdde41c878ba3994/Screenshot%202024-08-16%20at%209.24.06%E2%80%AFAM.png" alt="Screenshot 2024-08-16 at 9.24.06 AM.png" />

___
- [x] My Cases page / search card - add spacing under first sentence

<img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0prQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f5f96a74231b92f642ccae8ef9a6cb6149b4f87/Screenshot%202024-08-16%20at%2011.16.57%E2%80%AFAM.png" alt="Screenshot 2024-08-16 at 11.16.57 AM.png" />

___
- [x] Mobile - move link up to align with baseline of card title

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05rQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45c74040d36c59fd02fdf33395a19b5bf56b276e/IMG_2287%202.PNG" alt="IMG_2287 2.PNG" />

**Comment by ttlenard** [comment]
Testing Feedback:

- [x] Let's update this text for number 3 to say "the petitioners" instead of "your".
<img width="861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJ2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e441fb72b43f47240a9608c08bcbe138f270384c/image.png" alt="image.png" />

**Comment by swongCO** [comment]
- [x] Capitalize p in petition
- [x] Capitalize e and a in entry of appearance

<img width="966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZ3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--439fe5c69fbe9a2ed0e898899b2b57699474c7e8/Screenshot%202024-08-20%20at%209.13.39%E2%80%AFAM.png" alt="Screenshot 2024-08-20 at 9.13.39 AM.png" />

**Comment by swongCO** [comment]
Mobile step 2

- [ ] On iphone, the corner drag icon doesn't display; it displays on android but is very tiny - To be addressed in a design debt card.
- [x] On both iphone and android, the text boxes do not span the width of the screen; it's happening in landscape view as well

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGR3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8ef038e062fd0350f0b39774cc912d4afc1734a/IMG_2303.PNG" alt="IMG_2303.PNG" />

<img width="1732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGh3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3c38849d0653682c939696958a919a4dac679f7/IMG_2304.PNG" alt="IMG_2304.PNG" />

Android drag icon:
<img width="342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHB3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dd26f5c2a4ea7ae4cebaba146526518a9f164a0/Screenshot_20240820-110226.png" alt="Screenshot_20240820-110226.png" />

**Comment by swongCO** [comment]
- [ ] Add the same amount of padding on the right side that is on the left so the text boxes/link don't go up to the edge

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXAvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5c1bc571cb4eb703170a808eff53379803b4775/IMG_2308.PNG" alt="IMG_2308.PNG" />

**Comment by ttlenard** [comment]
- [x] @nechama-krigsman Per the judge's feedback, we can remove the "A minor or legally incompetent person" selection, and all of the associated party types (Conservator, Guardian, Custodian, Next friend for a minor, and Next friend for a legally incompetent person) from the practitioner flow.

<img width="1015" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0NhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db6ffc8a70a4df0a099350654492912904f622d4/image.png" alt="image.png" />

**Comment by swongCO** [comment]
**Test feedback**

- [x] Create a case page - Delete "you have" in the first sentence of the Deadline to File paragraph

<img width="1860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c6d6b70ec2bd9b09881835b44dd7e867e4d91eb/Screenshot%202024-08-28%20at%2011.19.42%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.19.42 AM.png" />

___
- [x] Create a case page - Change accordion text

<img width="534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b491f546c0178ea95f33c046d2d129c8a5f9be1/Screenshot%202024-08-28%20at%2011.21.11%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.21.11 AM.png" />

___

- [x] Petitioner and spouse info - amend name label to "petitioner spouse"

<img width="834" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3lhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea15c96cced5775b2cb5bd8d97f7eae1b02f76e5/Screenshot%202024-08-28%20at%2011.25.34%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 11.25.34 AM.png" />

___

- [x] Review page - update the alert banner text under Counsel info

<img width="1526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--507f9f7f1d228de571b9e3b79356eea02af7f707/Screenshot%202024-08-28%20at%2012.47.01%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 12.47.01 PM.png" />

___
- [x] Review page Petitioner info - amend party type to "Petitioner & petitioner spouse" (confirm that this is for display only on the flow and doesn't change the actual party type in the backend)
-
- [x] Add a field for the phone number above the email and display "Phone number not provided" if the field is blank

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0diQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cccbcc002f702f929d3dac58948737da963b245e/Screenshot%202024-08-28%20at%2012.58.10%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 12.58.10 PM.png" />

___

- [x] Pay filing fee page - change both "Your" to "The" and update sentence text

<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1diQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ffc6a57744825c5f11ecd13877a44fe38d0c710/Screenshot%202024-08-28%20at%2012.50.15%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 12.50.15 PM.png" />

___

- [x] Generated pdf - add phone and email labels to the counsel contact info

<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0947f60a3d23c7b2911e1a9dbd5b93df3e9166e3/Screenshot%202024-08-28%20at%2012.52.52%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 12.52.52 PM.png" />

**Comment by swongCO** [comment]
- [x] My Cases page for both petitioner and private practitioner - the Other options accordion in the Filing fee options card does not have a focus state when tabbing via keyboard

<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFN6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a389e7a4b8120316d98295f0dff9567434af8a74/Screenshot%202024-09-03%20at%202.24.18%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 2.24.18 PM.png" />

**Comment by katiecissell** [comment]
Two small tweaks:

- [x] 1. Missed a 'were'. This message should be "The case has been created and documents were sent to the U.S. Tax Court."


 Currently: <img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdys1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--069c1072878791df42868cc6f1bebc0f244ff702/image.png" alt="image.png" />

- [x] 2. On the intro page, update the last line to " After the Petition is processed by the Court, you’ll be able to view the status of the case, submit new documents and perform other actions."
- [x] 3. In the last bullet, change "your case" to "the case".

Currently: <img width="1568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEM1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23833bc8ec6a4eeada6bb97c3e2d5480f6887254/image.png" alt="image.png" />

- [x] 4. On intro page Change "Access your case documents over the internet" to "Access case documents over the internet"

**Comment by swongCO** [comment]
- [x] Increase the line height of all of the text in the stepper: it's currently 15.3px while the font size is 16px - increase line height to 18px or 125%

<img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVM1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfd97ec6dc067e0ff0a42631d873d47a27e6454e/Screenshot%202024-09-06%20at%2012.24.50%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 12.24.50 PM.png" />

___
Mobile

- [x] Portrait view: needs padding on the right side (match the padding on the left side of the screen)
- [x] Landscape view: right align Remove link to the right edge of the text box

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTY1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78022cb3d4bf30d446b376d98eb382c7048557cb/IMG_2333.PNG" alt="IMG_2333.PNG" />

<img width="1732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMSs1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a59a51f2fe57e5596aca0c951ef2bc623f8e548/IMG_2334.PNG" alt="IMG_2334.PNG" />

**Comment by mwestereng1** [comment]
One additional item:

- [x] Change "your Petition" to "the Petition" on the How to Create a Case" page.
<img width="1083" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXE1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb6ed26b6db615349c94fef794185dccc809ee82/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
Testing Feedback:
- [x] If you go beyond "z", the UI starts to display special characters, but the PDF represents them correctly. See screen grabs:
<img width="1034" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM20rQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37049357794a60239e883e9ea1b9e1235bc2e8cb/image.png" alt="image.png" />

<img width="307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3UrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d8796ba442d47e4a24629930d2ede945caa371f/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
Testing Feedback:

- [x] Can we please add in validation to the primary contact email field?  It's not catching it on this step, but it does catch it when I try to submit.

Example of an email that is not in the correct format on the review page:
<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGkrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc76a108484d2af9641a355c481e135caf3c6c67/image.png" alt="image.png" />

Validation error received upon submit:
<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHErQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ffba28e2524a7bc04637674852833b2a1e27b36/image.png" alt="image.png" />

Example of the secondary contact email validation. Can we get this same validation added to primary contact if the user attempts to click Next on the Petitioner contact info page?
<img width="985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGErQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e10246083c13cfe3567c6dafcd6ff39d04386a5/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
Testing Feedback:

- [x] If you are still making updates to the workflow, please adjust this text.
<img width="768" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDYvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edc579d9c43aee1c96d8e752a84e358b8e6ce8b0/image.png" alt="image.png" />

**Comment by swongCO** [comment]
**iOS feedback**

DISREGARD - links issues are related to 10427; the stepper issue will be handled in a DD at a later time

- [ ] Disable the ability to go back in the stepper to steps already completed in both portrait and landscape mode if the steps don't have labels
- [ ] Links are being cut off in portrait mode:
- [ ] Create a case page

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08770bcb1fa98a278be5a3765fdc695df8afe985/IMG_2338.PNG" alt="IMG_2338.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7e1ea34f6e3abafcaadf3aadf01ab7c490db793/IMG_2339.PNG" alt="IMG_2339.PNG" />

___
- [ ] Petitioner info - business

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--227486c0a8abfc0ef92c57d403c4b77ce1866610/IMG_2340.PNG" alt="IMG_2340.PNG" />

___
- [ ] Step 4 Case procedure page

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9FQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0c41b19e89a0ad464b683ce3819efda0c2df2b2/IMG_2337.PNG" alt="IMG_2337.PNG" />

___
- [ ] Step 5 STIN

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--616ae7a4acbddf3ffb5f068f795e7485a7ef1877/IMG_2341.PNG" alt="IMG_2341.PNG" />

___
- [ ] Step 7 Filing fee page

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--071b573f2edfb9b6e0139d258f03f6ce89e28337/IMG_2341.PNG" alt="IMG_2341.PNG" />

**Comment by nechama-krigsman** [comment]
@swongCO I think the links getting cut off may be related to the changes made as part of 10427

**Comment by ttlenard** [comment]
The Judges reviewed the text one last time and had 1 additional suggestion that they would like to see on both the Practitioner workflow and the Petition workflow.

1. Can we change "case" to "Petition" here?
<img width="829" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f624c237ae84037750e78f8146b76d6b33872135/image.png" alt="image.png" />
