### ISSUE TITLE
BUG: PDF upload error when an Internal user uploads a large PDF

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8679]
**Describe the Bug**
This bug was originally reported in ustaxcourt/ef-cms#8616.  After working on that bug, it was suggested that we split this issue out. See comment in that story from Nechama for further details.

I was testing the Court user upload PDF workflow.  After spinning wheel for quite some time (20+ minutes) I received a 400 error.  Here is the console:
<img width="1618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d65d40c2b4cc94021e7a57cf9e73c475e2ef81b8/image.png" alt="image.png" />

I don't see any errors in the Network tab.
<img width="1733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--993045b8ee4945f039eedd000bbede74ee16239a/image.png" alt="image.png" />

Here are the logs:
<img width="1507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6696f795ae9fb9cc1e73be62ab691836a3942c2e/image.png" alt="image.png" />

**Business Impact/Reason for Severity**
med

**In which environment did you see this bug?**
Prod/Test

**Who were you logged in as?**
internal users

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Doing work

**To Reproduce**
- Log in as a docket clerk
- Open your console
- Navigate to a case
- Click Create and then select PDF Upload
- Upload a very large document (You will need to give it like 20 min or more...it will eventually bonk)
- This is where you will get the errors above

**Expected Behavior**
Internal court user should be able to upload a large document without error

**Actual Behavior**
A clear and concise description of what actually happened.
Internal user receives error when attempting to upload a large document

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by cholly75** [comment]
@rachelschneiderman - check our Slack channel, file was too big to upload here but it _appeared_ to upload correctly to Slack. Thanks!

**Comment by rachelschneiderman** [comment]
@cholly75 @swongCO @katiecissell 

Katie and Sui, could you both help us explore some options for solving this bug that would not be too intrusive for the users? This bug is occurring because when a user chooses to "Upload PDF" the PDF that is uploaded is immediately parsed and scraped and the text contents stored so they can be searchable - in case the resulting docket entry is either an Order or Opinion. There are a multitude of other court issued event codes that are not searchable that it would be feasible to upload as a Court Issued Filing, for example, an Exhibit.  The PDF Tenille uploaded that caused this bug is over 132K pages of text and that amount of text exceeded the limit allowed by the Javascript engine.

An example of some options we have talked about so far:
- Store document contents differently so that document size doesn't matter.
- Do not parse and scrape immediately upon upload, parse and scrape after the user has chosen a searchable document type.
- When user is uploading a PDF, also ask them to choose an event code for the upload so that we can decide whether or not to parse and scrape the document.

There are probably a lot of other options as well! I am not sure what a court user would find most intuitive. Chris mentioned that docket section users will be the most likely to know the event code of the document, other users may not know how to categorize uploads as accurately. Thank you!

**Comment by swongCO** [comment]
Spoke with Chris and Tenille. We're all in agreement that the second option that Rachel provided is the best solution. The two upload flows are as follows:
1. A user uploads a pdf using the PDF upload feature; the pdf is only stored; docket will QC and select the appropriate document type; if it is a searchable doc type (currently orders and opinions), it will be parsed and scraped after the document is served
2. A user uploads a pdf using the PDF upload feature; the pdf is only stored; docket will QC and select the appropriate document type; if it is not a searchable doc type, it will not be parsed and scraped after the document is served

Optional:
For an edge case where an uploaded pdf exceeds the string text limit of 9 quadrillion, we can show a modal with a message that informs the user of the problem and to do something about it (or tell the original uploader to).

Chris still has some technical questions that he will address with devs.
