### ISSUE TITLE
BUG: Log in button is greyed out if user saves their credentials in their browser, making it appear inactive

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8681]
**Describe the Bug**
When a user saves their credentials in their browser, their email and password are pre-filled in to the email and password fields on the DAWSON log in page.  If a user does this, the log in button is greyed out, and if you hover your mouse over the Log in button, there is a red circle with a slash through it. This makes it appear that the log in button is not working, even though it does work and the user can simply click it and they will log in.

We need to update this so that the button displays as active in this scenario, so as not to confuse users.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Prod/Test

**Who were you logged in as?**
I was not logged in. This happens on the log in screen

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the system

**To Reproduce**
1. Log in to DAWSON
2. Be sure to save your credentials on your browser (I was using Edge)
3. Log out
4. Navigate back to DAWSON and click Log in
5. Your credentials should be auto-populated in the email/password fields
6. Notice the Log in button is greyed out and if you hover your mouse over it, there is a red circle.

**Expected Behavior**
Log in button appears active

**Actual Behavior**
A clear and concise description of what actually happened.

Log in button appears inactive, even though it can be clicked

**Screenshots**
<img width="1034" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05e56fb64683099f5210473cc4ab16848e3239d4/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by swongCO** [comment]
**UX Note**
Look into logic to detect if text is present in both fields. The other option is to add focus on either field to see if it'll enable the log in btn.

Time box some exploring if we can easily make the log in button recognize when text is entered in the fields or not. If it looks like an unreasonable amount of time, we will just have to add validation for the empty email and password fields.
