### ISSUE TITLE
Allow IRS Practitioners to select Entry of Appearance as the First Document Filed in a Case

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8683]
As an IRS Practitioner, so that I can see the petitioner's petition in DAWSON prior to filing an Answer, I need to be able to select Entry of Appearance in the "What Document Are You Filing?" menu when clicking "File First IRS Document" button.

Typically, the IRS document first filed in a case is the Answer; however in order to view the petition (and other associated filings) in DAWSON prior to composing an Answer, it would be helpful for the IRS to be able to simply assign an attorney to the case by filing an Entry of Appearance as the first document filed by the IRS on the case.

We would like to add the EA (Entry of Appearance) along with its ability to be generated automatically to the "What Document Are You Filing?" menu of options available when filing the first IRS document in a case.

## Acceptance Criteria
* IRS Practitioners can select "Entry of Appearance" from the "What Document Are You Filing?" menu when clicking "File First IRS Document" on a case
* When selecting "Entry of Appearance" the user is given the opportunity to either upload the EA or automatically generate the EA document as per usual process/filing
* Filing the Entry of Appearance as the first IRS document filed on the case attaches the filer to the case as Respondent counsel as per usual process.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- does EA replace all the options in the dropdown? NO
- does this change rules of auto generation from previous story? NO

**Comment by ttlenard** [comment]
## Test Cases

#### 1) IRS Practitioner accesses a case that has not yet had any IRS Filings, Entry of Appearance is now available in the dropdown picklist for "What document are you filing?".

- Log in as an IRS Practitioner
- Navigate to a case that does not yet have any documents filed by the IRS
- Click on the File First Document button
- Click on the Document type Dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a picklist item for Entry of Appearance and it is in the list in Alphabetical order (Above Exhibits).
- [x] **NEW FUNCTIONALITY** - User can type "Entry of Appearance" or any part of the document title and the dropdown picklist filters appropriately
- [x] **NEW FUNCTIONALITY** - User can type in the event code "EA" and the dropdown picklist filters appropriately



#### 2) IRS Practitioner selects Entry of Appearance from the File First IRS Document picklist; Options for auto-generating or uploading the EA are available if the Petitioner on the case has eService.

- Continuing from the previous test
- Be sure that the Petitioners on the case have electronic service.
- Select Entry of Appearance

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Options for Auto-generating or uploading the document are available as per usual.



#### 3) IRS Practitioner selects the option to Auto-generate the EA; Document is generated and the Practitioner is automatically associated with the case as per usual.

- Continuing from the previous test
- Select the radio button to Auto-generate the EA
- Click the Review Filing button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The auto-generated EA is displayed with the IRS Practitioners information as per usual (and the IRS Practitioner can also view the document in a new tab if they click on the document link).
- [x] **NEW FUNCTIONALITY** - After Submitting the filing, the Entry of Appearance is filed/served on the docket record, and there is a green confirmation with print receipt as per usual
- [x] **NEW FUNCTIONALITY** - The IRS Practitioner is added as Respondent counsel on the case


#### 4) IRS Practitioner selects the option to Upload an EA; Document can be uploaded, and once submitted, the practitioner is automatically associated with the case as per usual.

- As the IRS Practitioner, navigate to a case that does not yet have any documents filed by the IRS
- Be sure that the Petitioner on the case has electronic service
- Select Entry of Appearance
- Select the radio button to Upload the EA
- Upload the document and then click Review Filing button
- Check the box that the document has been redacted
- Click Submit your Filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Entry of Appearance is filed/served on the docket record, and there is a green confirmation with print receipt as per usual
- [x] **NEW FUNCTIONALITY** - The IRS Practitioner is added as Respondent counsel on the case



#### 5) IRS Practitioner selects Entry of Appearance from the File First IRS Document picklist; Options for uploading the EA is the only option available if the Petitioner on the case has paper service.

- As the IRS Practitioner, navigate to a case that does not yet have any documents filed by the IRS
- Be sure that the Petitioner on the case has paper service
- Click on the File First IRS Document picklist
- Select Entry of Appearance from the Document type dropdown.

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is no option to Auto-generate the EA
- [x] **NEW FUNCTIONALITY** - The only option available is to Upload a document




#### 6) IRS Practitioner uploads an EA document, and once submitted, the practitioner is automatically associated with the case as per usual.

- Continuing from the previous test
- Upload a document
- Click the Review Filing button

Expected Results
- [x] **NEW FUNCTIONALITY** - The user gets to the review your filing page as per usual
- [x] **NEW FUNCTIONALITY** - After indicating that the document was redacted and submitting the filing, the document is filed/served on the docket record as per usual.
- [x] **NEW FUNCTIONALITY** - There is a green confirmation banner with print receipt as per usual and the IRS Practitioner is added as Respondent counsel on the case.



#### 7) IRS Practitioner that is associated with a case clicks on the File a document button; Entry of Appearance is not available in the What document are you filing menu options.

- Log in as an IRS Practitioner
- Navigate to one of the cases on the My Cases Screen
- Click on the File a document button
- Click on the Document type dropdown

Expected Results:
- [x] Entry of Appearance is not available in the dropdown picklist and typing in the event code (EA) does not display any result for Entry of appearance either.



#### 8) Regression tests:

- [x] IRS Practitioner accesses a case where there are already IRS Practitioners associated, Request Access to Case button is available, and the Practitioner can file an EA as per usual.
- [x] Private Practitioner accesses a case that they are not associated with, Request Access to Case button is available, and the Practitioner can file an EA as per usual.
- [x] Private Practitioner that is associated with a case can file a document per usual, EA is not in the File a document picklist
- [x] Ensure that the EA does not "start the clock" for the case status to change from "Not at issue" to "At issue - ready for trial". This "clock" should continue to rely on "Answer" types of documents, not the EA.
- [x] Entry of Appearance is still available in the Document Type dropdown in the Add Paper Filing workflow (Log in as a docket clerk for this test)
- [x] Entry of Appearance is NOT available in the "What document are you filing?" dropdown for a petitioner that is associated with a case
- [x] Entry of Appearance is NOT available in the "What document are you filing?" dropdown for a Private Practitioner that is associated with a case
- [x] Normal visibility rules apply (not available for the public viewer, Is available for the Terminal user, only available for viewing if the user is a party on the case, document can be sealed/stricken, etc. as per usual)



#### 9) Be sure that this story is deployed to the IRS test environment, and that the IRS users can test this before we deploy to Prod.

- [ ] IRS has confirmed that this is working for them on the IRS Test Environment

**Comment by cholly75** [comment]
Notes from discussion:

1) Need to make sure docket entry description/coversheet title for EA filed as first IRS doc says "Entry of Appearance for Respondent"

2) Want the same auto-generate UI/view for filing EA as if filing in "Request Access to Case" view/flow

**Comment by En-8** [comment]
Per discussion with @cholly75 here: https://flexion.slack.com/archives/CHMLA049H/p1715975785709849

we also made the change as part of this to remove the "parties filing" section for the "File First IRS doc" screen. Filing party will automatically be "Respondent" in this case.

**Comment by ttlenard** [comment]
Some initial Testing feedback: @En-8 @codyseibert 

I noticed that there was a lag after you select Auto-generate Entry of Appearance and then click Review Filing.  If the user experiences this lag, and they end up clicking on the review filing button multiple times, it ends up auto-generating multiple documents when the page goes to the review filing screen. In the screen grab below, I clicked the review filing button 5 times.
<img width="1716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVQ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ddd4b0f80abd656355ab2500e622ae98501b06b/image.png" alt="image.png" />

After I did this, I tried to click the back button, but it doesn't appear to work (you have to click it 5 times to get through all 5 of the documents that were generated for it to go back to the previous screen.)

We might want to add in a spinner after the user clicks on review filing button so that they know it is processing and they don't click on the button multiple times?  I did a comparison with the existing auto-generation of the Entry of Appearance workflow, and there is a spinner implemented in that workflow.  Maybe we can mimic that?  Here is a screen grab of the spinner in the existing workflow. This displays right after I click Review filing (it doesn't let me click it more than once.)
<img width="1806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWo4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2a7df3f0e05077c556bd20cf256174902e6f8e9/image.png" alt="image.png" />

Let me know if you have any questions.

**Comment by ttlenard** [comment]
@En-8 @codyseibert some more testing feedback

Private practitioner file a document workflow has a bug.  When attempting to file a document, I can select a document from the list, but when I click on the review filing button, I get a validation error to select a filing party. The filing party section is no longer available to the Private practitioner to select from, and I am unable to file the document.  IRS Practitioners are still able to see the Filing parties on their workflow to file a document. This problem only seems to be occurring when a Private practitioner that is already associated with a case is filing a document.

See screen grabs:
Private Practitioner clicks the file a document button:
<img width="1525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b029e5221b543cc48816b55dc984d78fd121607e/image.png" alt="image.png" />

After they upload a document and click Review Filing, they get a validation error to select a filing party, but this section is no longer present. The Practitioner is stuck and cannot move forward or file a document.
<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc2f320f5019fdf8cd65677f3e7289e9df13572c/image.png" alt="image.png" />
