### ISSUE TITLE
BUG: Docket Clerks are getting a spinning wheel when Completing QC

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8691]
**Describe the Bug**

Docket Clerks are getting a spinning wheel when Completing QC.  When a docket clerk goes to their QC inbox, selects a document to QC and either clicks "Complete" or "Complete and Send Message", they get stuck on the spinning wheel.  If they refresh their screen, they will get the "Document already handled" message.  If you go and review the document QC and message box, the document and the message were successful, but this was not apparent to the user, since they were stuck on the screen with the spinning wheel.

This doesn't happen ALL the time.  Sometimes a clerk can complete QC and send message fine, without error. 

The team thought that this bug may be related to ustaxcourt/ef-cms#8616 and also maybe the reason had to do with filing in cases with a biggish docket record?
Is this also related t bugs ustaxcourt/ef-cms#8692 and ustaxcourt/ef-cms#8693?

**Business Impact/Reason for Severity**

High

**In which environment did you see this bug?**
Production (before we rolled back), Test

**Who were you logged in as?**
Docket Clerk 6

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

This behavior was first reported to us by Court Docket users

**To Reproduce**
1. Log in as a docket clerk
2. Click on Document QC
3. Click on Section Document QC
4. Click on the document title of a document
5. Click Complete and send message
6. Fill out the message pop-up
7. Click Send
8. Receive spinning wheel for multiple minutes
9. Refresh your browser
10. You will receive the "Document already handled" modal
11. Go check your QC processed tab - your document as processed as per normal
12. Go check your sent messages tab - your message was sent as per normal.

*Be sure that you test this in several cases of various size (cases with large docket records, med, and small docket records.).
*Be sure that you test with Large documents, med and small documents).
*Be sure that you test with the complete and the complete and send message buttons.
*Be sure that you test with updating the document type/adding additional text when completing QC to ensure that the additional coversheet is added/QC completed.
*Be sure that you test filing and then QCing in consolidated cases

**Expected Behavior**
Users should not receive the spinning wheel - things should complete 

**Actual Behavior**
A clear and concise description of what actually happened.
Document QC and messages are completing, but the user is not notified, and they are stuck with a spinning wheel.

**Screenshots**

<img width="1833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--339486781698dad6be9c18b649cdaf0838fba35e/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by pixiwyn** [comment]
Additional DoD was required for this ticket (we added in an additional test) then Mike requested that consider updating chunk sizes for what we store in the DB, updated to 4k, and PR: https://github.com/ustaxcourt/ef-cms/pull/4874

**Comment by ttlenard** [comment]
@pixiwyn Looks like I'm getting the spinning wheel again when completing QC on the FB case.  When I complete QC  and send message, it seems to work fine. Not sure if this issue is only with clicking Complete only?  Here are the screen grabs of my console:

<img width="1625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4678a986b42fd848dba87246fde87867220a75c/image.png" alt="image.png" />




<img width="1529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0xBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5b44bcc12f9e9358d14dd381d363719c8514c9e/image.png" alt="image.png" />
