### ISSUE TITLE
Inactivate Judge Colvin in DAWSON

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8694]
As a Court, so that our active judge list is up to date, I need Judge Colvin inactivated as a Judge user in DAWSON.

Judge Colvin passed away a few weeks ago and his outstanding work has been reassigned. We need to mark him as an "inactive" judge in DAWSON and remove the ability for users to send messages to him or his Chambers, assign him to trial sessions, or otherwise designate him as associated to a case. We also need to inactivate his DAWSON user account.

## Acceptance Criteria
* Users can no longer select Judge Colvin/Colvin's chambers as options when sending messages
* Judge Colvin cannot be assigned a trial session
* Judge Colvin cannot be assigned a case
* Judge Colvin does not appear as a selection in any dropdown where the LOV is exclusively "active" judges
* Judge Colvin continues to appear as a selection in any dropdown list that includes "inactive" judges (e.g., order/opinion search)
* Judge Colvin's DAWSON account is deactivated

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [x] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user sends a message, Judge Colvin/Chambers is no longer an option.

- Log in as a Court user
- Navigate to a case
- Click Create
- Choose Message
- In the message Pop-up, for section, select Chambers
- Click on the Chambers dropdown

Expected Results:
- [x] Judge Colvin's Chambers is no longer an option in the picklist




#### 2) Petitions clerk schedules a new trial session, Judge Colvin is no longer available in the Judge dropdown

- Log in as a Petitions Clerk
- Click on Trail Sessions
- Click on Add new session
- Scroll down to the Assigned Judge Dropdown

Expected Results
- [x] Judge Colvin is no longer in the dropdown picklist



#### 3) Petitions clerk edits an existing trial session, Judge Colvin is no longer available in the Judge Dropdown.

- Log in as a Petitions Clerk
- Click on Trial Sessions
- On the open tab, scroll down to a trial session that is in the future
- Click on the City, State link for the session
- Click Edit
- Scroll down to the judge dropdown

Expected Results
- [x] Judge Colvin is no longer in the dropdown picklist


#### 4) Docket Clerk changes the case status for a case and selects Assigned, Judge Colvin is no longer available in the assigned Judge Dropdown.

- Log in as a docket clerk
- Navigate to a case
- Click on the Case information tab
- Click on the link to change the case caption/status
- Click on Assigned
- Click on the Judge dropdown

Expected Results:
- [x] Judge Colvin is no longer in the dropdown picklist



#### 5) Any user searches for Orders/Opinions issued by Judge Colvin, results list displays appropriately

- Navigate to DAWSON as any user (public, party, Court user)
- Search Orders and Opinions
- Click on the Judge Dropdown filter

Expected Results:
- [x] Judge Colvin IS available in the dropdown picklists.



#### 6) Judge Colvin is no longer on any picklist for active judges

- [x] Regression test to ensure that Judge Colvin is not on any picklist in the system for active Judges



#### 7) Judge Colvin no longer has a Cognito account.

- Log into AWS and navigate to Cognito
- Search for Judge Colvin's email account

Expected Results:
- [x] Judge Colvin no longer has a Cognito account. It has been disabled.




#### 8) Check to ensure that there are no messages remaining in any of Judge Colvins chambers.

- [x] Need to ensure that there are no active messages that still in DAWSON for Judge Colvins Chambers



#### 9) Docket clerk adds a decision type document to the docket record, Judge Colvin is no longer listed in the Judge Dropdown when adding Decision types of documents.

- Log in as a docket clerk
- Navigate to a case
- Click on Create
- Select PDF upload
- Upload a document and add in a description, click save
- Add a signature to the document
- Click Add Docket Entry
- Select any of the Decision type documents
- Click on the Judge Dropdown

Expected Results:
- [x] Judge Colvin is no longer in the dropdown picklist

**Comment by katiecissell** [comment]
Pre-refinement Questions:
- Has this happened before? How often does this happen?
- Does Judge Colvin have any data associated with him and do we need to migrate it?

**Comment by TomElliottFlexion** [comment]
Similar: https://github.com/flexion/ef-cms/issues/9480

**Comment by swongCO** [comment]
**UX feedback**
Colvin is still appearing in some dropdowns. The failed test cases are 2,3,4,9.

**Comment by En-8** [comment]
That's my bad, @swongCO, there was a manual deploy step I missed when I pushed this to test EOD friday. I ran it and re-checked those test cases and it's looking good on my end, should be good to recheck.
