### ISSUE TITLE
Display New Line Formatting in Notes Fields

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8704]
As a Court user, so that notes are clearly understood, I need line breaks to display in the Case Notes or Judge Notes fields on a Case.

One of the requests we've consistently heard is that the Notes fields in DAWSON can become confusing to read/parse because of the lack of formatting available; the text cannot be formatted and there are no paragraph breaks, which renders each field a continuous text string, despite the add/edit UI clearly displaying and recognizing the breaks.

We would like to display the line/graf breaks in the Notes field views on the Case without having to open the add/edit UI to see them.

## Acceptance Criteria
* When adding/entering Calendar Notes, Case Notes or Judge Notes for a Case, line/paragraph breaks are preserved when saving and displaying the notes in the Case UI.

## Notes
* We would also like to extend this ability to the Notes fields in other areas of DAWSON, such as the Trial Session and Session Copy notes fields. We can do this in separate stories, but if it's efficient to do it concurrently with this story then please advise.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user adds in a case note on a case; Line/paragraph breaks that were displayed in the pop-up modal are displayed on the Case notes section in the case after it is saved.

- Log in as a Court user
- Navigate to a case
- Click on the Notes tab
- Click on Add Case Note 
- Add in some text, making sure that you have various line breaks/paragraphs.
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The line/paragraph breaks that you had in the pop-up modal display the same way on the Case Notes Card.

(Ensure that if you edit the note to add additional notes, after save, the formatting is still displaying line/paragraph breaks)

*Repeat this test with various court users



#### 2) Judge user adds in a Judge's note on a case; Line/paragraph breaks that were displayed in the pop-up modal are displayed on the Judge's notes section in the case after it is saved.

- Log in as a Judge User
- Navigate to a case
- Click on the Notes tab
- Click on Add Note in the Judge's Notes card
- Add in some text, making sure that you have various line breaks/paragraphs.
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The line/paragraph breaks that you had in the pop-up modal display the same way on the Judge's Notes Card.

(Ensure that if you edit the note to add additional notes, after save, the formatting is still displaying line/paragraph breaks)


*Repeat this test with a Chambers user

**BONUS**
- Add a Judge's note with line/paragraph breaks to a case that the Judge/Chambers users is assigned to, that is also calendared for trial
- Click on the city/state link for the trial session
- Scroll down the page and find the Judge's note in the list of cases

Bonus functionality (Dev Discretion)
- [x] The Judge's note on the Session copy page also displays the line breaks as it did on the Judge's notes section in the case.
- [x] The Judge's note on the printable session copy page also displays the line brakes as it did on the Judge's notes section in the case.


#### 3) Court user adds a Calendar note on a case, Line/paragraph breaks that were displayed in the pop-up modal are displayed on the Trial Card section in the case after it is saved.

- Log in as a Court user
- Navigate to a case that is calendared for trial
- Click on the Case information tab
- Click on the Edit link next to the trial information 
- Select Add/Edit Calendar Note
- Add in some text, making sure that you have various line breaks/paragraphs.
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The line/paragraph breaks that you had in the pop-up modal display the same way underneath the City/State link on the Trial card.

(Ensure that if you edit the note to add additional notes, after save, the formatting is still displaying line/paragraph breaks)

**BONUS**
- Click on the City/State link of the trial session
- Scroll down the cases until you find the docket number of the case that you just added the Calendar note in.

Bonus functionality (Dev discretion):
- [x] The Calendar note on the Trial session page also displays the line breaks as it did on the Trial information section in the case.
- [x] The Calendar note on the printable trial session copy page also displays the line breaks as it did on the trial information section in the case



#### 4) Existing Case notes that were saved on a case are now formatted.

- Log in as a Court user
- Navigate to a Case that had an existing note that had multiple line breaks prior to the deployment of this story (ex: 19821-16)
- Click on the Notes tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The line/paragraph breaks that were previously entered are now displayed on the Case notes card.



#### 5) Existing Judges notes on a case are now formatted

- Log in as a Judge or Chambers user (I used Judge Ashford)
- Navigate to a case that had an existing note that had a line break (ex: 13281-23)
- Click on the Notes tab

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The line/paragraph breaks that were previously entered are now displayed on the Judge's notes card.

**BONUS**
- Click on the City/State link of the trial session
- Scroll down the cases until you find the docket number of the case that had the existing Judge's note in it

Bonus functionality (Dev discretion):
- [ ] The Judge's note on the Trial session page also displays the line breaks as it did on the Judge's Notes section in the case.
- [ ] The Judge's note on the printable session copy page also displays the line brakes as it did on the Judge's notes section in the case.


#### 6) More BONUS Stuff (Dev Discretion)

- Trial Session notes have line/paragraph breaks (this text field is available when a user adds/edits a trial session).
- Session Notes have line/paragraph breaks (This text field is available when a Judge/Chambers is on the Session Copy page and they click add note at for the Session Notes card at the top of the page).
- Session Notes have line/paragraph breaks on the printable session copy page.

**Comment by pixiwyn** [comment]
Noticed for Judge Notes, the edit and delete links weren't at the top like with case notes, went ahead and just fixed this, see updated screenshot:<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1J6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07c695c07d19617c29f68e6813b5a67ba9343c00/2024-06-18_11-11-04.png" alt="2024-06-18_11-11-04.png" />

**Comment by pixiwyn** [comment]
Believe I got all the bonus items as well. Please let me know if I missed anything, thanks!

**Comment by swongCO** [comment]
UX feedback
The font for notes is different on the printable pdfs:
<img width="866" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU45QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b66b5ee4ba2ff371d239382728125e10cbc1166/Screenshot%202024-06-20%20at%2010.28.40%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 10.28.40 AM.png" />
