### ISSUE TITLE
BUG: When Court users are logged in and viewing DAWSON on a mobile device, case docket records display a blank white screen.

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8707]
**Describe the Bug**
We recently started getting reports from Court users that when they attempt to view a case docket record on their Court issued iPhones, they are getting a blank white screen on their device.  After using a mobile device simulator, we were able to find the error (see screen capture below.)  Some example docket numbers that we found this issue in is 17866-22, and 12000-22.

It appears that this bug may have something to do with the implementation of ustaxcourt/ef-cms#8462 (download docket entries)?  Is the docket record just too "wide" making it so that the page won't load on a mobile device?  

We have found some temporary solutions for Court users. If they turn their phone to "landscape" mode and refresh, it typically will load.  Also, if they adjust the font size and refresh, or if they view the page in "desktop mode" on their device, these solution will all allow the page to render successfully.  If they don't actively update their settings or change the view, then the docket record will never load for the user.

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Prod/Test

**Who were you logged in as?**
Any Court user (besides general user)

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
This bug was reported to us by Court users

**To Reproduce**
1. Log into DAWSON as a Court user (not a general role) on a mobile device (can be either iOS or android)
2. Type in a case docket number
3. Receive white screen
4. If on an iphone, click on the little A's in your address bar to lessen the font size down to 75%. 
5. Click refresh
6. Page will load
7. Now you can zoom back in to 100% if needed.
8. Repeat the process at 100%. - Get a white screen
9. Turn the phone to landscape mode
10. refresh the screen
11. Page will load
12. If on an android device, you will need to go into the browser settings and turn on "view in desktop mode"

**Expected Behavior**

Docket records should still load for logged in Court users when logged in on a mobile device (it might not be pretty, but it should still load)

**Actual Behavior**
A clear and concise description of what actually happened.
Docket records aren't loading for Logged in Court users when they are viewing on a mobile device

**Screenshots**

Here is the error message that we were able to get from the simulator:
<img width="1199" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c7ea4a1b094a184f614c5a80f56f242ebc606ff/image.png" alt="image.png" />

Here is the error for that type error:
<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e45603345c1c7973231fa54e2439900396b42192/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by TomElliottFlexion** [comment]
In `web-client/src/views/DocketRecord/DocketRecord.tsx` we are using a React useEffect to get element `'all-selectable-docket-entries-checkbox'`. This element is only present in the `NonPhone` section of the tsx. Ideally, we would be tying the checkbox state to Cerebral rather than React
