### ISSUE TITLE
Message Inbox - Additional Sorting

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8709]
As a DAWSON user, so that I can customize my inbox display to my preferences, I need to be able to sort on any column I choose.

Feedback from the Court indicates a desire to expand our sorting capabilities in the message inbox across a variety of roles.  We would like to implement "full spectrum" sorting in a number of places in the system, but to begin with we will start with the Inbox view for the user and section messages, adding sort functionality to columns that do not currently possess it.

## Acceptance Criteria
* Inbox view for user and section messages now has the ability to sort by the following criteria/columns:
  - Case Title (alphabetically)
  - Case Status (alphabetically)
  - To (alphabetically) - note this only exists on Section Messages screen
  - From (alphabetically)
  - Section (alphabetically)
* Sorting works in conjunction with filter selections just like the current sorting options

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- what specific needs does this solve? are they going to sort by every column?

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user views their My Messages inbox; Sort functionality is available on all columns.

- Log in as a docket clerk
- Navigate to your My Messages inbox
- Review the page

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Each column now has the sort arrows on the column header (new with this story is Case Title, Case Status, From, Section)



#### 2) Court user views the Section Messages inbox; Sort functionality is available on all columns.

- Continuing from the previous test
- Navigate to the Section Messages inbox
- Review the page

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Each column now has the sort arrows on the column header (new with this sotry is the Case Title, Case Status, To, From, Section)



#### 3) Court user views other Message boxes; "Full Spectrum" sorting is not available on the other boxes (sent, completed) in the My messages or in Section Messages.

- Continuing from the previous test
- Navigate to the My Messages Sent box and Completed Box, and then view the Section Messages Sent and Completed boxes. 

Expected Results:
- [ ] The first 3 columns in the Sent and Completed boxes have sorting, the rest of the columns remain unsortable for now.



#### 4) Court user sorts their My Messages Inbox by the Case Title Column; Sorting is A-Z, and then Z-A after clicking the sort link a second time.

- Continuing from the previous test
- Navigate back to your My Messages Inbox
- Click on the Case Title Column Header

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The messages in the inbox are sorted appropriately by case title, A-Z
- [ ] **NEW FUNCTIONALITY** - After clicking on the Case title Column a second time, the messages in the inbox are sorted appropriately by case title, Z-A



#### 5) Court user sorts their My Messages Inbox by Case Status Column; Sorting is A-Z, and then Z-A after clicking the sort link a second time.

- Continuing from the previous test
- Navigate back to your My Messages Inbox
- Click on the Case Status Column Header

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The messages in the inbox are sorted appropriately by case status, A-Z
- [ ] **NEW FUNCTIONALITY** - After clicking on the Case status Column a second time, the messages in the inbox are sorted appropriately by case status, Z-A


#### 6) Court user sorts their My Messages Inbox by the From Column; Sorting is A-Z, and then Z-A after clicking the sort link a second time.

- Continuing from the previous test
- Navigate back to your My Messages Inbox
- Click on the From Column Header

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The messages in the inbox are sorted appropriately by From, A-Z
- [ ] **NEW FUNCTIONALITY** - After clicking on the From Column a second time, the messages in the inbox are sorted appropriately by From, Z-A



#### 7) Court user sorts their My Messages Inbox by the Section Column; Sorting is A-Z, and then Z-A after clicking the sort link a second time.

- Continuing from the previous test
- Navigate back to your My Messages Inbox
- Click on the Section Column Header

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The messages in the inbox are sorted appropriately by Section, A-Z
- [ ] **NEW FUNCTIONALITY** - After clicking on the Section Column a second time, the messages in the inbox are sorted appropriately by Section, Z-A



#### 8) Court user Filters their My Messages Inbox; Sorting on all columns works correctly. 

- Continuing from the previous test
- Filter some of the Columns
- Next click on each of the column headers to also add sorting

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The messages in the inbox are sorted appropriately, even when filters are applied.



#### 9) Repeat tests 4 - 8 but with the Section inbox 

- [ ] **NEW FUNCTIONALITY** - The messages in the Section inbox are sorted appropriately after repeating test cases 4-8.
- [ ] **NEW FUNCTIONALITY** - Court user can sorts their My Messages Inbox by the To Column, Sorting is A-Z, and then Z-A after clicking on the sort link a second time.



#### 10) Regression Test - Court users can view/sort their message screen on a mobile device

- [ ] Court users can view their messages and sort them while logged in on a mobile device (it doesn't have to be pretty, it just needs to work.)



#### 11) Repeat all tests with all court users (with the exception of the general user, they do not have messaging capability)

- [ ] Admissions Clerk
- [ ] Trial Clerk
- [ ] Petitions Clerk
- [ ] Chambers
- [ ] Judge
- [ ] ADC
- [ ] Clerk of the Court
- [ ] Case Services Supervisor
- [ ] Floater
- [ ] Reporters Office
- [ ] Docket Clerk

**Comment by ttlenard** [comment]
Testing Feedback:

- [x] If there are no comments in a completed message, and the user sorts off of this column in the completed box, they receive a spinning wheel and nothing sorts. In looking at the console, there is an error.  I tested this with another user that had comments in all of the completed messages, and it sorted just fine. It seems that it only has issues if there are no comments (and the comments are not required, so there will be many times that a completed message won't have any data in this field.

<img width="1784" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d7894675c663348c7bba6904c2c4ba7f4aa35a5/image.png" alt="image.png" />
