### ISSUE TITLE
Bug: Placeholder - IRS ETCS Listener appears to be broken

### ISSUE THREAD

**Issue by jhansen-flexion** [ustaxcourt/ef-cms#8713]
IRS is reporting that their ETCS listener is not able to record data. 
There are no Kibana errors in the log. 

It appears that the new login mechanism doesn't like tokens via superuser pool

**Comment by jhansen-flexion** [comment]
IRS is reporting that their ETCS listener is not able to record data. 
There are no Kibana errors in the log. 

It appears that the new login mechanism doesn't like tokens via superuser pool

**Comment by jimlerza** [comment]
We wrote a doc for testing the API v2 endpoints as an IRS superuser:

`docs/additional-resources/irs-super-user.md`
