### ISSUE TITLE
BUG: IRS Superuser cannot download STIN docket entry

### ISSUE THREAD

**Issue by jtdevos** [ustaxcourt/ef-cms#8716]
**Describe the Bug**
If an IRS superuser account attempts to generate a download URL using the `document-download-url` endpoint,  they receive an error message stating "Unauthorized to view document at this time".  Note that this impacts the DAWSON REST v2 API, not the visual DAWSON app.  

**Business Impact/Reason for Severity**
The IRS practitioners receive/review cannot these STIN documents because the IRS superuser cannot obtain them via the API v2 endpoint.

**In which environment did you see this bug?**
IRS, PROD

**Who were you logged in as?**
IRS Superuser 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
testing endpoints on the v2 API

**To Reproduce**
1. Establish a session on the IRS environment using the instructions documented in [Testing API v2 with Your IRS Test User](https://ustaxcourt.github.io/ef-cms/#/additional-resources/irs-super-user?id=testing-api-v2-with-your-irs-test-user)
2. generate a reconciliation report for a day that is likely to have records, e.g. https://api.irs.ef-cms.ustaxcourt.gov/v2/reconciliation-report/2024-01-03
3. identify a STIN entry in the reconciliation report - 
4. use the docket number and docket-entry ID try to generate a download URL using the `document-download-url` endpoint.

**Expected Behavior**
JSON response containing download URL and `200 OK` status code.

**Actual Behavior**
`403 Unauthorized` status code and error message: 
```
{
  "message": "Unauthorized to view document at this time."
}

```

**Comment by jhansen-flexion** [comment]
10263 may be related.
