### ISSUE TITLE
Practitioners: Relabel "Request Access To Case" Button/Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8720]
As a practitioner, so that I understand what to expect when requesting association with a case, I need the "Request Access To Case" button to be relabeled, along with the title of the resulting screen.

In DAWSON, a practitioner viewing a case record to which they are not associated as counsel is presented with a button labeled "Request Access To Case", followed by a screen similarly titled with a curated menu of documents which they can then e-file to enter an appearance as counsel.

We have seen some practitioners confused about the process for this button, thinking that the "Request Access to Case" workflow is the way to gain visibility into the case docket record, even if they do not intend to represent a party associated with the case.

To make this more clear, we would like to relabel the "Request Access to Case" button as "Represent a Party". The screen that appears after clicking this button is then retitled from "Request Access To This Case" to "Represent a Party to this Case". No other changes are needed to this screen/workflow at this time. 

## Acceptance Criteria
* Request Access to Case button for _all_ practitioners is relabeled as "Represent a Party"
* Request Access to this Case screen is retitled "Represent a Party to this Case"
* No other changes to filing process

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Questions from Pre-refinement:
- Need to confirm, this is just for practitioners and will not affect the respondent side? because their button is named the same today.. (It will affect IRS and private practitioners)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner navigates to a case that they are not a party on; Button at the top right of the page now displays "Represent a Party".

- Log in as a Private Practitioner
- Type in a docket number of a case that you are not a party to in the case search card
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - The button in the top right of the screen now says "Represent a Party"



#### 2) Private Practitioner clicks the Represent a Party button; DAWSON displays screen with text that says, "Represent a Party to this Case".

- Continuing from the previous test
- Click on the Represent a Party button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Page title is now "Represent a Party to This Case"
- [x]  No other changes to this page



#### 3) IRS Practitioner navigates to a case that they are not a party on, but there is already another IRS Practitioner on the case; Button at the top right of the page now displays "Represent a Party".

- Log in as an IRS Practitioner
- Type in a docket number of a case that you are not a party to, but already has an IRS Practitioner associated with the case
- Click Search

Expected Results:
- [x] **NEW FUNCTIONALITY** - The button in the top right of the screen now says "Represent a Party"



#### 4) IRS Practitioner clicks the Represent a Party button; DAWSON displays screen with text that says, "Represent a Party to this Case".

- Continuing from the previous test
- Click on the Represent a Party button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Page title is now "Represent a Party to This Case"
- [x]  No other changes to this page

*Repeat test cases 3 and 4 with a Practitioner that has DOJ as an employer.


#### 5) Repeat Tests 1-4 on a mobile device

- [ ] Tests 1-4 Pass
