### ISSUE TITLE
Revise Document Menu for File First IRS Document Workflow

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8721]
As an IRS practitioner, so that I am only presented with document types that I should be filing as the first IRS document filed on a case, I need the menu of available document types to be revised.

The File First IRS Document screen's document menu contains document types that IRS would or should never file as the first document on a case. To prevent error or confusion, we would like to edit this menu to include only the document types/event codes in the spreadsheet attached to this story.

## Acceptance Criteria
* File First IRS Document screen only allows the IRS Practitioner to file the document types listed in the attached spreadsheet
* No other changes to functionality

## Notes

[What documents may be eFiled 1.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bde4acecd8e9e858e64b2a2d48b4985b631b128/What%20documents%20may%20be%20eFiled%201.xlsx)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) IRS Practitioner files the first document on a case; Document type dropdown menu now has a limited set of documents to choose from.

- Log in as an IRS Practitioner
- Type in the docket number of a case that does not yet have an IRS Practitioner assigned to the case.
- Click Search
- Click on the File First IRS Document button.
- Click on the Document Type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - The documents that display in the dropdown match what is in the attached Spreadsheet.  

*Be sure to test by filing a number of documents that are in the list to ensure that filing is completed correctly.


#### 2) Regression tests

- [x] Request Access to case (Represent a Party - new button!) dropdown menu items remain the same as they were - no modifications made (IRS, DOJ, and Private Practitioners)
- [x] File a document dropdown menu items has ALL of the documents - no modifications made (IRS, DOJ, Private Practitioners, Petitioners)
- [x] When a docket clerk adds/edits a paper filing, ALL documents display
- [x] When a docket clerk QC's an IRS filing, the document type dropdown menu when they QC the filing displays ALL of the documents, not the trimmed down list.
- [x] When a docket clerk edits a document on the docket record, the document type dropdown menu displays ALL of the documents, not the trimmed down list.
- [x] When a docket clerk adds a PDF upload, the document type dropdown remains the same, no changes made.
- [x] Menu displays correctly on mobile devices.

**Comment by mwestereng1** [comment]
### **UX Test Feedback**

- "Application to Take Deposition" add "of" 
- "Motion to Add Small Tax case Designation" capitalize "case"
- "Motion to Consolidate" add "Docket Numbers"
- "Motion to Correct Clerical Order" change to "Motion to Correct Clerical Error"
- "No Objection" add "to"
- "Notice of No Objection" add "to"
- "Notice of Objection" add "to"
- "Objection" add "to"
- "Opposition" add "to"
- "Request for Place of Trial" add "at"

For smaller screens, is it possible to adjust the wrapping for the "Document type" instructions? 
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjluQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--135c3ecde6aa83518d8e8bd65be1a3994e063d37/Screenshot%202024-06-14%20at%2012.25.38%E2%80%AFPM.png" alt="Screenshot 2024-06-14 at 12.25.38 PM.png" />

**Comment by En-8** [comment]
For the changes to copy for options to choose, @ttlenard and @mwestereng1 chatted and Tenille is going to check up on those changes and, if we choose to move forward with them, they will be a follow-up story to this one.

We also decided to make the wrapping of the text in the document type component a follow-up design debt card.

Thanks for the feedback Missy!

**Comment by cholly75** [comment]
Thanks @mwestereng1 - we will incorporate some of these bullets into our planned follow up story overhauling the document lists available to everyone.
