### ISSUE TITLE
Stack radio btns for screens under a specified size

### ISSUE THREAD

**Issue by swongCO** [ustaxcourt/ef-cms#8724]
As a Dawson user, so that my mobile experience is optimized, I want radio buttons to be listed in an expected order.

Currently, the second radio btns for country and case procedure selections are wrapping for screen sizes under 375px. The country selector appears in multiple pages while case procedure is part of the petition efiling flow. 

Acceptance Criteria:
- Ensure that radio btns for country and case procedure selections stack for smaller screen sizes
- Find other instances of radio btns with the same behavior and implement the fix
- Determine if user documentation needs to be updated (Tenille): Y / N

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVl3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb1caf263bf560fcf3ee99614d2928e521f58cbf/Screenshot%202024-06-03%20at%2011.09.10%E2%80%AFAM.png" alt="Screenshot 2024-06-03 at 11.09.10 AM.png" />

<img width="364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWN3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37afecf4209134ec1568db5285df9d87a1702197/Screenshot%202024-06-03%20at%2011.09.48%E2%80%AFAM.png" alt="Screenshot 2024-06-03 at 11.09.48 AM.png" />

**Comment by katiecissell** [comment]
Done as a part of 5512!
