### ISSUE TITLE
Upgrade Dynamsoft Web TWAIN server EC2 image to 18.x

### ISSUE THREAD

**Issue by jimlerza** [ustaxcourt/ef-cms#8725]
As a DAWSON maintainer, so that I can ensure users can continue to utilize in-browser scanning, I need to upgrade our Dynamsoft server version to 18.x.
Goal is to have this deployed by 6/22/24
## Pre-Conditions

Six licenses have been procured.

## Acceptance Criteria

- 6 EC2 instances are updated to run the 18.x version of the Dynamsoft Web TWAIN server:
  - [ ] `dynamsoft-stg` (us-east-1)
  - [ ] `dynamsoft-stg` (us-west-1)
  - [ ] `dynamosoft-test` (us-east-1)
  - [ ] `dynamsoft-test` (us-west-1)
  - [ ] `dynamsoft-prod` (us-east-1) 
  - [ ] `dynamsoft-prod` (us-west-1)

## Notes

- Dynamsoft server software can be downloaded from the [Dynamsoft Customer Download Center](https://www.dynamsoft.com/customer/download) (or see @jimlerza).
- Licenses are saved in each environment's entry in Secrets Manager.
- Need to regression scanning/printing from DAWSON via Court machine

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user doesn't have to do anything to upgrade their version, this happens seamlessly.

- [ ] Court user has updated version, and they didn't have to do anything. 


The following are all regression tests to ensure that the new version works the same as the current version that the Court uses.

#### 2) Petitions clerk scans in paper Petition and associated documents; scan saves per normal.

- Log in as a Petitions clerk, be sure that your scanner is on and connected to your computer.  Also, be sure that you have the new Dynamsoft version.
- Click on Document QC
- Click on Start a Petition button
- Be sure that a scanner is selected
- Click the Start Scan button
- After the scan is done, click Create PDF.

Expected Results:
- [x] Scanning/creating the PDF works as per normal
- [x] You can rescan and can create multiple batches
- [x] You can scan as per normal for each of the document types in the petition flow.

*Repeat this test with the Case Services Supervisor role and the CotC role



#### 3) Docket Clerk scans in Paper filings to a case; scan saves as per normal.

- Log in as a Docket Clerk
- Navigate to a case
- Click on the Create button
- Select Paper filing
- Select the Scan radio button
- Click on the Start Scan button
- After the scan is done, click Create PDF

Expected Results:
- [x] Scanning/creating the PDF works as per normal
- [x] You can rescan and can create multiple batches
- [x] You can scan as per normal for each of the document types in the Paper filing flow.

*Repeat this test with the Case Services Supervisor role and the CotC role


#### 4) Court user scans in correspondence files to a case; scan saves as per normal.

- Log in as a Docket Clerk
- Navigate to a case
- Click on the Correspondence tab
- Click on Add Correspondence link
- Select the scan radio button 
- Click on the Start Scan button
- After the scan is done, click Create PDF

Expected Results:
- [x] Scanning/creating the PDF works as per normal
- [x] You can rescan and can create multiple batches
- [x] You can scan as per normal for each of the document types in the add correspondence flow.

*Repeat this test with all Court users
