### ISSUE TITLE
Improve textarea elements

### ISSUE THREAD

**Issue by swongCO** [ustaxcourt/ef-cms#8726]
As a Dawson user, so that I can use the text area box efficiently, I need the UI to be logical.

All text area boxes in Dawson, including inside modals, allow users to expand/contract horizontally and vertically by dragging on the bottom right icon. We should constrain the dragging to vertical only, as it is possible to drag a text box off a page or collapse it so the text isn't readable.

Acceptance Criteria:

- Remove the ability to horizontally expand or contract a text area box for all screen sizes
- Set a minimum height for the text area box so it can't be shorter than one line of text
- <s>iOS: ensure that the corner drag icon displays and is functional</s>
- <s>android: ensure that the corner drag icon displays correctly and is functional</s>
- Apply this to the component throughout Dawson
- Determine if user documentation needs to be updated (Tenille): Y / N

Some examples found:

![Image](https://github.com/user-attachments/assets/4fdbfdc5-06a6-4b67-8b93-c88e819873c8)

![Image](https://github.com/user-attachments/assets/746939af-a4fa-43ba-8424-2caebe4d02ca)

![Image](https://github.com/user-attachments/assets/443f46e0-9383-4d18-b16e-459a1c94ab71)

![Image](https://github.com/user-attachments/assets/efff4ebc-ecac-4f91-86f3-4eb0c9d682d9)

![Image](https://github.com/user-attachments/assets/0c1d3cd3-8305-4fd2-9c32-d612c6b01180)

___
Drag icon - iOS:

![Image](https://github.com/user-attachments/assets/4748e726-57f5-4614-8af0-73255dc5935e)

Drag icon - android

![Image](https://github.com/user-attachments/assets/335c28b6-d111-4307-bc6e-5e63835b9dd0)

**Comment by Mwindo** [comment]
The first two Acceptance Criteria seem easy enough:

- Remove the ability to horizontally expand or contract a text area box
- Set a minimum height for the text area box so it can't be shorter than one line of text

The next two seem trickier and maybe worth questioning:

- iOS: ensure that the corner drag icon displays and is functional
- android: ensure that the corner drag icon displays correctly and is functional

What is the issue with these second two criteria?

- The drag icon is browser-specific, not something that we add in DAWSON. Some browsers--like iOS Safari--simply do not support resizing textareas and therefore do not display the drag icon. To fix this, we would need to create our own drag icon and use custom JavaScript to resize.
- However, this begs the question: Is this really what we want to do? Mobile browsers often disable this behavior by default for a reason: it can be clunky (maybe even an accessibility concern) to drag-to-resize on mobile devices.

Regarding the second two criteria, then, I think I need more context on what problem we are trying to solve. Other options we have for mobile that I can think of:
- Expect that mobile browsers will often not support drag-to-resize. Set minimum textarea sizes that are mobile-friendly.
- Create a new `ResizableTextarea` component that grows or shrinks vertically depending on the input of the user, and use that (either everywhere, or as needed, i.e., when reasonable default sizes are not enough).

**Comment by Mwindo** [comment]
Here is where the textareas appear:

![Image](https://github.com/user-attachments/assets/0f425db3-bc7d-4fbf-ab6b-db0898e71382)
