### ISSUE TITLE
BUG: Printable Case Inventory Report times out

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8732]
**Describe the Bug**

It appears that if there are a lot of cases in a certain status, the Printable Case Inventory Report is timing out with a 504.  At this point, it seems to only be occurring with the Case Status of "General Docket - At Issue (Ready for Trial)". There are currently 9,443 cases in this status on the Test environment (9,134 in Prod).  This report wasn't timing out on any of the other case statuses in this report. Note: The General docket not at issue has 5,257 cases and it generated the printable report just fine.

**Business Impact/Reason for Severity**
Med

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
Any Court User

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Thanks to Missy!  She found this bug while testing other functionality

**To Reproduce**
1. Log in as a Court user
2. Click on Reports menu
3. Select Case Inventory
4. Select General Docket - At Issue (Ready for Trial)
5. Run the report
6. Click on the Printable Report link
7. For the user, nothing happens, the spinner just disappears and they are brought back to the case inventory report. 
 If you have the console open, you will notice that there is a 504 error.  Interestingly, there are no 504 errors reported in the logs or in Sentry. Why not?

**Expected Behavior**
This printable report should not be timing out

**Actual Behavior**
A clear and concise description of what actually happened.
The printable report timed out, but doesn't give the user any indication of any error. The only way to see the error is to view it in the console. There are no logs indicating the error, and nothing reported out in Sentry either.

**Screenshots**
<img width="1870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzlHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dc1ac1983c7be2dacebb87cf9bcc4e8b134e8f3/image.png" alt="image.png" />

<img width="1883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26bf26be23dec7e07167fc0df6eb289328e4f081/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
@cruzjone-flexion I'm getting a 400 error in Test when I try to run the report.
<img width="1882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGF0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2c3e2520b3482a9ecaeff3e67cc2ba80efa01bb/image.png" alt="image.png" />

Here is the error in Kibana Logs:
<img width="834" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2V0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38c48f76ebfdc2b1fc778f858fe9b74f10b85d9b/image.png" alt="image.png" />

**Comment by cruzjone-flexion** [comment]
Error causing the 400 error
<img width="835" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLyt0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30eff042f9c6bc8b043cd33025388dc56b479b77/image.png" alt="image.png" />
