### ISSUE TITLE
BUG: Select Scanner link doesn't select a scanner on first selection

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8734]
**Describe the Bug**
When a user is first selecting a scanner in DAWSON and they click "Select Scanner", the default scanner that displays in the picklist isn't getting selected. The user has to select a different scanner in the list first, and then click change, and re-select the desired default scanner in order for it to be able to be selected.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Test, Prod, Staging

**Who were you logged in as?**
Petitions clerk, Court user, Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Log in as a Petitions clerk
2. Click on Document QC
3. Click on Start a Petition 
4. Click on Select Scanner
5. Select the scanner that you have connected to your computer and indicate how you would like to scan documents
6. Click Select
7. When you do this, nothing happens, and the "Select Scanner" link still displays, no scanner was selected.
8. The only way for the scanner to be selected and to "stick" is to choose a different scanner from what is displayed in the dropdown.
9. After you select a different scanner, and click select again, will it then update the scanner.
10. To get the scanner that you originally wanted to have selected, you have then then click on the Change link, and select the scanner.  At this point the scanner you selected will then display and you can then do your scanning.

*Note that this happens with a court user scanning in correspondence files, and for Docket Clerks scanning in Paper filings.

**Expected Behavior**
If the scanner that you want is displayed in the dropdown and you click select, the scanner should be selected.

**Actual Behavior**
A clear and concise description of what actually happened.
The default scanner that shows in the picklist is not getting selected, even though the user sees it and selects it.

**Screenshots**

When you first come in to scan a petition, there is no scanner selected.
<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjlIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8ab6a1dbb25d5ff6cd32f0ac4898ba72c0ddd02/image.png" alt="image.png" />

After clicking select Scanner link, you get this modal:
<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0pIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--700ec1ad5f78434bbdd0f2f0f052ff47c976de4b/image.png" alt="image.png" />

If the scanner that you want is what is being displayed by default, and you click Select,  it brings you back to this screen, and nothing is selected, and there is no scan option.
<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48ea95b3050b51c8ed48b5cde482e01938aaadf3/image.png" alt="image.png" />

To get the scanner you want, you have to click on Select Scanner again, click on the dropdown menu, select a different scanner from the dropdown, and click select.
<img width="1126" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27a1eb0777c718189752a7665be21c6edb903e66/image.png" alt="image.png" />

Once you select a different scanner than the original selection in the default view, you can then go back in and click the change link, select the scanner you want, and then it will b"stick"
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2xIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4fe9f9a874fb4c2eb51e5094a95289be8dd0ba4/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by akuny** [comment]
After discussing this bug with @ttlenard, we will initialize the scanner and scanner mode dropdown fields with placeholder values that must be changed in order for the user to submit the form. These placeholder values will no longer be an option after the user has made a selection.

**Comment by ttlenard** [comment]
@akuny: I found an issue today with this bugfix.  We're going to need to address this before we push to Production. Sorry for not catching this sooner!

1 - Click on Select Scanner
<img width="1847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87d2c94ec6eb25c321c7ddec978f4a3c5a2d9798/image.png" alt="image.png" />

2 - The Court scanner is the first one in the list. select that:
<img width="1904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0VPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a21b321b336cdb5effcd7317a9cf81faeafb163/image.png" alt="image.png" />

3 - Click on the Start Scan button, notice that the scannerSourceIndex says 1. This is the incorrect index, it should be 0.
<img width="1901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1lPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--454f81531003e905bea2b5e94955332e5022e655/image.png" alt="image.png" />

4 - because the index is incorrect, it results in an error message:
<img width="1908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2NPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c172b66f968fd6b317f81cd24fcea8f3bac927a/image.png" alt="image.png" />

5 - the way to fix this is to select an different scanner first, and then select the one that you want. This will correct the Index number to 0, and scanning will be able to happen. I believe the "fix" for this bug only addressed the UI, and didn't fix the back end data associated with the scanner Index.

**Comment by akuny** [comment]
Thank you for the detailed description of the issue. Some technical details for the record:

The select element for setting a scanner was previously updating the scanner index based on the selected option element's [selectedIndex property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedIndex). However, the addition of a new placeholder option element, which appears only when a scanner has not been set, caused the index values passed from the form to state to be off by one.

Instead of using the selectedIndex property, the solution involves passing the value of the preexisting "index" data attribute during the update.
