### ISSUE TITLE
Make Un-Served Petition Docs Visible To Logged In User

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8735]
As a petitioner or practitioner, so that I can view the petition I just submitted to the USTC, I need to be able to view my e-filed petition submission prior to service to the IRS.

Currently when e-filing a case with the USTC, petitioners cannot see the petition or any ATP they just filed, as the petition has not yet been served.

This restriction makes little sense, as it is the petitioner's own submission to the USTC and they should not be prevented from viewing it.

We would like to make the e-filed Petition, CDS, and ATP visible to the petitioner immediately after successfully creating the case, so that when they navigate to My Cases and view their submission they can actually _see_ their submission. 

## Acceptance Criteria
* Petition is visible on the docket record to a logged in party/counsel to a case even when the status is Not Served
* ATP (if present) is visible on the docket record to a logged in party/counsel to a case even when the status is Not Served
* CDS (if present) is visible on the docket record to a logged in party/counsel to a case even when the status is Not Served

## Notes
* STIN documents are not on the docket record and should remain that way

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner e-files a Petition and then navigates to the docket record; the Petition document has a hyperlink and can be viewed.

- Log in as a petitioner
- E-file a petition
- After submitting, navigate to the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The unserved Petition document has a hyperlink
- [x] **NEW FUNCTIONALITY** - Upon clicking on the hyperlink, the petitioner can view the document that they submitted (opens in a new tab as per usual)
- [x] All other data on the docket record displays as per normal



#### 2) Petitioner e-files a Petition for a business and includes a CDS and ATP documents; upon reviewing the docket record, all documents submitted have a hyperlink and can be viewed.

- Log in as a petitioner
- E-file a petition as a business, and be sure that you also upload an IRS notice and a CDS
- After submitting, navigate to the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The unserved Petition documents all have hyperlinks
- [x] **NEW FUNCTIONALITY** - Upon clicking on the hyperlinks, the petitioner can view all the documents that they submitted (opens in a new tab as per usual)
- [x] All other data on the docket record displays as per normal



#### 3) Practitioner e-files a Petition and then navigates to the docket record; the Petition document has a hyperlink and can be viewed.

- Log in as a Private Practitioner
- E-file a petition
- After submitting, navigate to the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The unserved Petition document has a hyperlink
- [x] **NEW FUNCTIONALITY** - Upon clicking on the hyperlink, the practitioner can view the document that they submitted (opens in a new tab as per usual)
- [x] All other data on the docket record displays as per normal



#### 4) Practitioner e-files a Petition for a business and includes a CDS and ATP documents; upon reviewing the docket record, all documents submitted have a hyperlink and can be viewed.

- Log in as a Private Practitioner
- E-file a petition as a business, and be sure that you also upload an IRS notice and a CDS
- After submitting, navigate to the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The unserved Petition documents all have hyperlinks
- [x] **NEW FUNCTIONALITY** - Upon clicking on the hyperlinks, the practitioner can view all the documents that they submitted (opens in a new tab as per usual)
- [x] All other data on the docket record displays as per normal



#### 5) Regression tests

- [x] Practitioners not associated with the case do not see the hyperlink for the unserved petition docs
- [x] Terminal user does not see the hyperlink for the unserved petition docs
- [x] Public users do not see the hyperlink for the unserved petition docs
- [x] Logged in petitioners not associated with the case do not see the hyperlink for the unserved petition docs
- [x] Court users can see the hyperlink for all of the unserved petition docs as per normal
- [x] After serving the petition, document visibility behaves as per normal to users
- [x] Turn off the FF for ustaxcourt/ef-cms#7175 and retest all of these. Should behave the same
- [x] Petitions not yet served prior to this story will become visible to the user that submitted the case after deploying 



#### 6) Tests 1-5 pass on a mobile device

- [x] Passes on mobile
