### ISSUE TITLE
BUG: Alert messages are displaying on the log in screen if the user is logged out due to inactivity

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8737]
**Describe the Bug**
If a user received an alert (ex: Document filed and is accessible from the docket record, error message, etc.) and remained on that page without logging out, their system eventually logs them out.  When they click on the log in button to log back in, we see the alert display on the Log in to DAWSON page (see example of this occurring in the screen grab below.)

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Any user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**
1. Log in as any user
2. Do something to get an alert message at the top of your screen
3. Now, do nothing until the system automatically logs you out
4. You will then get the "we logged you out" screen. Click on the button to log back in
5. See the alert that you had received again on the log in screen

**Expected Behavior**
These alerts shouldn't be persisting on the log in screen

**Actual Behavior**
A clear and concise description of what actually happened.
The previous alert that you received displays on the log in screen and it is just a bit confusing/misleading.

**Screenshots**
<img width="979" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53c952f1ece2f28b89df12dae1afc5120ad4a01f/image.png" alt="image.png" />

**Desktop (please complbugete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by cholly75** [comment]
Being fixed with ustaxcourt/ef-cms#8682.

**Comment by Mwindo** [comment]
Since this has been addressed in ustaxcourt/ef-cms#8682 (which should be staged tomorrow or Monday), I think we can close this ticket :)

**Comment by ttlenard** [comment]
Agree with Chris above. Closing this ticket.
