### ISSUE TITLE
Trial Sessions Page: Add Session Copy Notes

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8739]
As a Court, so that I can easily see relevant details about a Special trial session, I need session copy notes to display on the Trial Sessions page.

## Pre-Conditions
ustaxcourt/ef-cms#8740

## Acceptance Criteria
* Session Notes attached to the judge/CA's Session Copy for a Special trial session are displayed alongside the appropriate Trial Session on the Trial Sessions page.
* Possible optional AC: remove the Edit link on the Session Info page for all judges

## Notes
![Image](https://github.com/user-attachments/assets/cef91f52-72ff-477a-bd9e-5ef1049238e9)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [x] Is framed in business/user need, the value has been addressed.
- [x] Includes acceptance criteria
- [x] Has been refined
- [x] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by mwestereng1** [comment]
### UX Notes
[Figma Page File](https://www.figma.com/design/hXGX0kcb8Gxqwnp9tu3OlS/10411-%26-10408-Trial-session-page-updates?node-id=0-1) - Mock is located in section called "FINAL - Special Session Notes"

- Add row for "Special Session Notes:" below special session rows
- Only applies when "Session Type" is a "Special" - Notes do not display for any other "Session Type".
- If there are no notes for a special trial session, the notes row should still be displayed.

**With "Special Session Notes"**
![Image](https://github.com/user-attachments/assets/0bc80568-b637-438a-944b-1569ed87beff)

**No "Special Session Notes"**
![Image](https://github.com/user-attachments/assets/689edcc0-35e2-413d-8712-e249aa9560b0)

**Comment by ttlenard** [comment]
## Test Cases:

#### 1) Court user accesses the Trial Sessions/Calendared Page; Special sessions that contain session notes have the notes displayed on the trial sessions page.

*This test has a pre-requisite - be sure that some special trial sessions that are calendared have session notes added. Be sure that other session types also have Session notes added (regular, small, hybrid, hybrid-S, motion/hearing)

- Log in as a Court user
- Click on the Trial Sessions tab
- Review the sessions that are Special Sessions on the page.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Special sessions that have session notes now display a new line under the session information that contain whatever was typed in the Session Notes field.  This section has a title "Special Session Notes"
- [x] **NEW FUNCTIONALITY** - Special sessions that did not have session notes do not display any data (there will not be a Special Session Notes section for these sessions)

*Be sure to test this with all Court users to ensure that the Special Session Notes are visible to all Court users.



#### 2) Court user accesses the Trial Sessions/Calendared Page; Other Session types that contain session notes do not display any notes on the Trial Sessions Page.

- Continuing from the previous Test
- Review the other session types besides Special

Expected Results:
- [x] All other session types do not display any of the session notes that were added.

*Be sure to test this with all Court users to ensure that the Special Session Notes are visible to all Court users.


#### 3) Judge edits their Special session that didn't previously have Session Notes and adds in some Session Notes from the Session copy page; Special Session notes display on the Trial Sessions Page.

- Continuing from the previous test
- Click on the City, State for one of the Judges special trial sessions that didn't have any notes
- Click on the Add note link on the Session Notes card
- Add in some notes in the Session Notes Field
- Click Save
- Review the Trial Sessions Page, find the Special session that you just added notes to.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The special Session notes that you just added are now displayed in the Special Session Notes section.

*Repeat this with a Chambers administrator

#### 4) Judge edits their Special Session that has Session notes; deletes the existing notes; Special Session notes no longer display on the Trial Sessions/Calendared page.

- Continuing from the previous test
- Click on the City, State for the special trial session that you just added Session notes to
- Click on the Edit Note or Delete Note link
- Delete the notes in the Session Notes Field
- Click Save
- Review the Trial Sessions Page, find the Special session that you just deleted the notes on.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The special Session notes that you just deleted are no longer displayed underneath the Special Session

*Repeat this with a Chambers Administrator


#### 5) Trial Clerk assigned to a Special Session adds in Session Notes from the Session copy page; Trial Clerk's notes do not display on the Trial Session Page.

- Log in as a Trial Clerk assigned to a Special Session
- Click on Trial Sessions Header
- Click on the City/State link of a Special Session that you are assigned to
- Click on the View Session Copy link
- Add in a Session Note
- Click Save
- Review the Trial Sessions Page, find the special session that you just added Session notes to

Expected Results:
- [x] The Session notes that you just added to the Special Session do not display as Special Session Notes on the Trial Sessions Page.


**OPTIONAL A/C**
#### 6) Judge user navigates to the Session info page of a session that is in the future; Edit link is no longer present.

- log in as a Judge User
- Navigate to a Trial Session
- If it is one of your sessions, click on view session info link

Expected Results:
- [x] **NEW FUNCTIONALITY** - there is no longer an edit link present.

**Comment by JayFlexy** [comment]
Quetions
---
* Question for 10408: Should Special Session notes visibility in the table align with who can see and edit then when viewing Special session details

* Question for 10408: If the current user is not assigned to the session, should also not see the notes on the TrialSession Rows page?

**Comment by katiecissell** [comment]
Exploration into Voice Over noticed that adding a row that is not related to the columns results in some weird voice Over behavior of it reading column names not 'related' to that row. Since this table is for internal users who we know do not currently utilize voice over we can move ahead with this but if we should ever need a public facing table with a row independant of the columns, we'll most likely have to rethink the component itself.

**Comment by cholly75** [comment]
Additional potential AC added; to facilitate change management we would like to remove the Edit link on the Session Info page for all Judges. @JayFlexy to evaluate on Monday 11/18 to determine if we can add to this story or need to address separately.

CC: @ttlenard
