### ISSUE TITLE
Trial Sessions Page: Calendared View

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8740]
As a Court user, so that I can easily see the trial sessions I want to see, I want a single, filterable view of calendared trial sessions that can be filtered by status.

To streamline the Trial Sessions view and make it more useful for both end of year reporting and Court personnel, we will be making some changes requested by the Court. These changes will enable this view to deliver more information about trial sessions and allow more flexibility in customizing the information displayed on this screen.

The first of these changes is a modification to the All/Open/Closed views, as outlined below.

## Acceptance Criteria
* Open and Closed tabs are removed from the Trial Sessions screen
* "All" tab is renamed to "Calendared"
* Status filter is added to the Trial Sessions "Calendared" view
* Status filter allows the following selections:
  - Open (displays only open Trial Sessions when selected)
  - Closed (displays only closed Trial Sessions when selected)
  - All (displays both Open and Closed Trial Sessions)
* Status filter is defaulted to "Open" selection
* Calendared tab is the default view for all Court users when clicking on the Trial Sessions link on the top nav in DAWSON
* Existing filters remain in place and functional on Calendared view
* Status column added to view, containing "Open or "Closed" value for each session displayed

## Notes
* "New" trial sessions are never displayed on the Calendared view.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**
[Figma](https://www.figma.com/design/0O247PVxacOgMXWTq8nXm8/USTC-%7C-10409-Trial-Sessions-page---Calendared-view?node-id=0-1) file

- add session status as the last column (see the current All tab for reference)
- add new filter as radio btns (default to Open)
- keep existing user permissions
- switching between New and Calendared will reset all filters

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk navigates to the Trial Sessions Page; Two tabs are displayed: New and Calendared.

- Log in as a Petitions Clerk
- Click on the Trial Sessions tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now only two tabs: New and Calendared
- [x] **NEW FUNCTIONALITY** - Calendared view is the default tab that is active
- [x] **NEW FUNCTIONALITY** - Session Status is below the tabs, with 3 radio buttons, All, Open, and Closed
- [x] **NEW FUNCTIONALITY** - Open Radio button is selected by default and the display is only open calendared sessions (no closed)
- [x] **NEW FUNCTIONALITY** - Clicking on the All radio button displays all calendared sessions (open and closed)
- [x] **NEW FUNCTIONALITY** - Clicking on the Closed radio button displays all closed calendared sessions (no open)
- [x] **NEW FUNCTIONALITY** - There is now a Session status column displayed to the far right of the table
- [x] **NEW FUNCTIONALITY** - No sessions in New status are displayed in the table


#### 2) Petitions Clerk filters the Calendared table; filters work as per normal

- Continuing from the previous test
- Select a radio button for session status
- Select a few filters

Expected Results
- [x] Filters work as per normal


#### 3) Petitions Clerk clicks on the New Tab; Session status radio buttons do not display; table remains the same.

- Continuing from the previous test
- Click on the New tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The session status radio buttons do not display
- [x] Column data remains the same 
- [x] Filters work as per normal


Repeat tests 1-3 as other Court roles

- [x] Clerk of the Court
- [x] Case Services Supervisor
- [x] General
- [x] Admissions Clerk
- [x] Docket Clerk
- [x] ADC
- [x] Trial Clerk



#### 4) Chambers Administrator navigates to the Trial Sessions Page; Only one tab is displayed: Calendared.

- Log in as Chambers Administrator
- Click on the Trial Sessions Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - Calendared is the only tab displayed (New is not displayed for this user role)
- [x] **NEW FUNCTIONALITY** - Session Status is below the tabs, with 3 radio buttons, All, Open, and Closed
- [x] **NEW FUNCTIONALITY** - Open Radio button is selected by default and the display is only open calendared sessions (no closed)
- [x] **NEW FUNCTIONALITY** - Clicking on the All radio button displays all calendared sessions (open and closed)
- [x] **NEW FUNCTIONALITY** - Clicking on the Closed radio button displays all closed calendared sessions (no open)
- [x] **NEW FUNCTIONALITY** - There is now a Session status column displayed to the far right of the table
- [x] **NEW FUNCTIONALITY** - No sessions in New status are displayed in the table

Repeat this test with these users

- [x] Judge
- [x] Floater
- [x] Reporters Office

#### 5) Regression test to ensure that the page functions as per normal

- [x] This test passes



#### 6) Ensure that the trial sessions page will display on Mobile devices

- Log in as a Court user (be sure to test with Judges/CA's and the other court roles) on a mobile device
- Click on the trial sessions tab

Expected Results:
- [x] The trial sessions page opens and functions (Does not have to look nice, it just has to function).

**Comment by zachrog** [comment]
Is "New" a session status in terms of business process, or are only "open" and "closed" session statuses?

answer: Yes "New" is a session status

**Comment by zachrog** [comment]
How should the "New" tab be sorted and how should the "Calendared" tab be sorted? oldest to newest or newest to oldest?

Answer: Both "New" and "Calendared" should be sorted from oldest to newest based on start date

**Comment by zachrog** [comment]
Swing session criteria from Chris H.

Swing session candidacy
- The term must be the same(Fall, Winter, Spring...)
- The term year must be the same
- cannot have a swing session with your own session
- Cannot be a Closed trial session

Ordering
- 1. by trial location
- 2. Start date (earliest start date to latest start date)

**Comment by zachrog** [comment]
After talking with Chris H. here are the routing instructions after a person creates a new trial session.

- ALWAYS navigate them to the New tab

He is open to revisiting the routing in another story/ design debt

**Comment by zachrog** [comment]
Tenille, 

Things that need regression:
- swing session options
- NOTT reminder indicator

**Comment by swongCO** [comment]
**UX feedback**

- [x] The dropdown list of judges should retain the same behavior as the previous iteration - New and Open sessions show only active judges; Closed and All show active and inactive judges
- [x] The filters do not reset when logging in and out as the same user or as a different user
- [x] Update empty state message to "There are no trial sessions for the selected filters."
- [ ] <s>Right align the Add trial session btn to the right edge of the table</s> (advise if this should be DD; we're trying to fix them as we find them) **DEV + UX decided it would be best to handle this as DD to include btns across Dawson**

<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzNRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe5d0d2c783e84c4520a327a04c90ba563ceb1ba/Screenshot%202024-09-12%20at%208.48.24%E2%80%AFAM.png" alt="Screenshot 2024-09-12 at 8.48.24 AM.png" />

**Comment by zachrog** [comment]
Validation investigation.

Problem statement: How can we detect when making a validation changes to entities, we do not create invalid data in the database?

**Comment by swongCO** [comment]
**UX feedback**

- [x] After creating/editing/deleting a new trial session, the user should be navigated to the New tab - it's navigating them to Calendared (change from existing behavior)
- [x] "Unassigned" is not displaying under the Judge column for New sessions that are unassigned
