### ISSUE TITLE
IRSPractitioner: Restrict Access to DOJ Employees

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8744]
As a DOJ employee, so that I do not enter appearances in cases that I shouldn't have access to, I need to only be able to represent parties in cases that are in the status On Appeal.

Recently, the Court has seen DOJ attorneys requesting access to cases where the lawyer is not representing a party on appeal. This is prohibited by Court policy, so we want to restrict this via code to prevent this from occurring again.

## Acceptance Criteria
* IRS practitioner users with an Employer value of "DOJ" do not see the "Represent a Party" button when viewing a case unless the Status of the case is "On Appeal".

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) DOJ Attorney enters an appearance on a case where the case status is "On Appeal", Attorney is added to the case as per normal.

- Preconditions: Be sure that you have a log in for a DOJ attorney
- Log in as the DOJ attorney
- Navigate to a case whose status is "On Appeal"

Expected Results:
- [x] The Represent a party button is displayed at the top right of the screen as per normal
- [x] After clicking on the Represent a Party button, the DOJ practitioner is able to enter an appearance as per normal
     - [x] Attorney can generate the EA if all parties receive electronic service
     - [x] Attorney can upload the EA 
     - [x] Docket record reflects the EA document as per normal, service is sent as per normal.



#### 2) DOJ Attorney navigates to a case that is not on Appeal; The Represent a Party button is not available and is not displayed.

- Preconditions: Be sure that you have a log in for a DOJ attorney
- Log in as the DOJ attorney
- Navigate to a case whose status is anything but "On Appeal"

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Represent a party button is NOT displayed at the top right of the screen.
- [x] **NEW FUNCTIONALITY** - DOJ Attorney is not able to file any type of document on the case.

*Be sure that you test with Every Case Status.

- [x] New
- [ ] General Docket - Not at Issue
- [x] General Docket - At Issue - Ready for Trial
- [x] Calendared
- [x] Submitted
- [x] Submitted - Rule 122
- [x] Rule 155
- [x] Jurisdiction Retained
- [x] Closed
- [x] Closed - Dismissed
- [x] Assigned - Case
- [x] Assigned - Motion
- [x] CAV



#### 3) DOJ Attorney navigates to a case that was once On Appeal, but is no longer on Appeal (closed); DOJ attorney no longer sees the "Represent a Party button)

- Preconditions: Be sure that you have a log in for a DOJ attorney
- Log in as the DOJ attorney
- Navigate to a case whose status is "On Appeal"
- You will see the Represent a Party button
- Next, log out and back in as a docket clerk
- Change the case status to anything other than On Appeal
- Log back in as the DOJ Attorney
- Navigate to the case from above that was previously on appeal

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Represent a party button is NOT displayed at the top right of the screen.
- [x] **NEW FUNCTIONALITY** - DOJ Attorney is not able to file any type of document on the case.


#### 4) Regression test to ensure the following:

- [x] IRS attorney's can still enter an appearance on cases that are in any case status
- [x] Private Practitioners can still enter an appearance on cases that are in any case status
- [x] Private, IRS, and Petitioners, Intervenors, Participants can still file documents on any case, regardless of case status
- [x] Sealed cases remain sealed, and if the user is not already a party, they cannot see the docket record or file documents.


#### 5) Repeat tests 1-4 on a mobile device

- [x] This test passes

**Comment by mwestereng1** [comment]
UX Feedback:

- DOJ employee is allowed to "File First IRS Document" 
- The "File First IRS Document" button is available if the petition has been served to the IRS, but the first IRS document hasn't been filed, regardless of case status. Examples: 15380-20, 10000-20, 10876-24
- Logged in as IRSPractitioner2 (changed to DOJ employee)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2p4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70eb124bbc3a877e0b08b300458cced1321f87c6/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
Everything passes, with the exception of a DOJ attorney being able to file the first document when a case status is General Docket - Not at Issue.  This issue is being addressed in another story (#10426).

**Comment by cruzjone-flexion** [comment]
A new [task card](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10426) was created regarding UX Feedback "File First IRS Document"
