### ISSUE TITLE
AWS v2 -> v3 conversion: API Gateway Management API

### ISSUE THREAD

**Issue by jtdevos** [ustaxcourt/ef-cms#8746]
## Pre-Conditions

 - none

## Acceptance Criteria

 - All usages of the AWS v2 ApiGatewayManagementApi SDK have been converted to the AWS v3 ApiGatewayManagementApi SDK.

## Pain Avoided/Frustration Saved

 - AWS v2 SDK has been deprecated

## Breadth/Pervasiveness of Problem

 - Used in app context.

## Complexity of Problem (Low, Medium, High) and Why it's Complex

- medium

## Notes

**Comment by ttlenard** [comment]
Tests:
- [x] Private Practitioner update contact information (address + phone)
- [x] Private Practitioner file multiple documents across a consolidated group
- [ ] Petitioner update contact information (address + phone)
- [ ] Petitioner update email address
- [x] Calendaring
- [x] Change of Trial Judge
- [x] Remote to In Person
- [x] In person to remote
- [x] 30-day notice of trial
- [x] Serving a Petition to IRS
- [x] Submit a Petition
- [x] External user Upload large (super-size) document to a case
- [ ] Internal user - add paper filing - large (super-size) document
- [x] Download all documents from a large case
- [x] Download all case documents from a trial session
