### ISSUE TITLE
BUG: DAWSON is not recognizing the correct user/role that is logged in if the user is logging in/out as different users

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8748]
**Describe the Bug**
We've noticed while testing that if you are logged in as one user, and then you log out and immediately log back in as another user, DAWSON doesn't know which user you are logged in as. We've seen this happen on a handful of occasions now. We believe that this also caused an issue in Production, but have failed to be able to recreate it while testing. DAWSON needs to check the user/role that you are logged in as, so that we don't continue to have these issues.  This affects testing between roles/log ins, but also affects production users (most likely paralegals that log in as various attorney's).

**Issue 1 - Advanced Search link**
- log in as a Practitioner
- Notice that there is an advanced link on the Search for a case card
- Log out
- Log in as a Petitioner
- Notice that there is STILL an advanced search link on the Search for a case card
- If you try to click on it, you will get an error. (the advanced search link should NOT be there for the petitioner - they do not have this search capability)
- Refresh the page
- Now the advanced search link no longer appears (good!)
- Next log out as the petitioner and log back in as a Practitioner
- Notice that you don't have an advanced search link. If you refresh the page, the link will appear.

**Issue 2 - Cold Case report**
- We noticed this while testing the cold case report story that actually resulted in a bug (#10416)
- Log in as a court user (not general)
- Click on reports, and then select cold case report (see cases in the list)
- Next log out
- Log in as a general user
- Click on reports, and then select cold case report (see cases in the list)
- Next, refresh the screen
- Now you will NOT see any cases in the list and in your console, you will see a 403
- At first, DAWSON thought that you were the other court user that you were initially logged in as, and displayed the data

**Issue 3 - Prod issue reported to DAWSON support (have not been able to recreate it yet)**
- Paralegal was going to file an entry of appearance for their attorney. 
- They had been logged in as attorney 1 to check the case.
- They logged out of DAWSON as attorney 1
- They logged in as attorney 2 and they filed the EA. They reported that the preview was correct and displayed attorney 2's info correctly.
- After filing the EA, they reviewed the document on the case
- The data on who was entering the EA on the doc ended up being attorney 1 (who was already an attorney on the case), but the filed by was Attorney 2.  Since they were logged in as attorney 2, the doc should have had attorney 2's info on the signature line.

**Issue 4 - Edit Practitioner Record**
- Log in as Admissions Clerk
- Navigate to a Practitioner record via search
- Click Edit
- Log out, log back in as Judge
- Navigate to a Practitioner record via search
- Edit link is available and active, should be restricted to Admissions Clerk role 

**Business Impact/Reason for Severity**
Medium

**In which environment did you see this bug?**
Production/Test

**Who were you logged in as?**
all users

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality/DAWSON support ticket

**To Reproduce**
see above

**Expected Behavior**
DAWSON should understand which role the user is logged in as 

**Actual Behavior**
A clear and concise description of what actually happened.
DAWSON doesn't know which role/user a user is logged in as if they are logging in/out of DAWSON

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by JayFlexy** [comment]
# Problems we see with the app that are unrelated to changes

- generateStampedCoversheetInteractor does not have any authorization
- Remove validateRawCollection
- remove cy.login() (enfornce login through user-specific helpers)

**Comment by ttlenard** [comment]
Permissions I've tested:
- [x] Terminal User
- [x] Public non-logged in user (doc visibility, search, todays orders/opinions)
- [x] Court users/adding/editing trial sessions
- [x] Petitioner filing a petition/filing documents/search for cases they are not associated with
- [x] Private Practitioner filing EA, document visibility, simultaneous doc filing, update address info, update petitioner address info
- [x] Private Practitioner, petitioner, IRS Practitioner update email
- [x] Petitioner, IRS Practitioner update address/phone #
- [x] Docket Clerk edit documents (seal, rename, strike)
- [x] Docket Clerk QC status report
- [x] Docket Clerk Consolidate cases
- [x] Docket Clerk - Change case status/caption
- [x] Docket Clerk - manual block
- [x] Docket Clerk - Manually add a case to a calendar
- [x] Docket Clerk - add/edit/delete deadlines
- [x] Docket Clerk - Print Practitioner case list
- [x] Docket Clerk - Add Counsel to an existing case
- [x] Docket Clerk - Add party to a case
- [x] Docket Clerk - Add/Edit statistics on a case
- [x] Manually mark as high priority
- [x] Judge complete Order report
- [x] Judge Stamp
- [x] Judge - Add data to Submitted/CAV and Pending Items
- [x] Judge - Download all cases in a trial
- [x] Judge - Create Order - add docket numbers to consolidated order
- [x] Judge - Edit draft order
- [x] Judge - Upload PDF
- [x] Judge - Judges Notes
- [x] Judge - Session Copy - view/add notes, filter, print
- [x] ADC - Create/Sign/Edit Order
- [x] ADC - Send/receive Messages
- [x] ADC - Stamp
- [x] ADC - Status Report Order
- [x] Docket Add Docket Entry
- [x] Petitions Clerk - Set Calendar
- [x] Print session info
- [x] Print Paper Service (initial Calendaring)
- [x] Petitions Clerk - Issue 30 day notice
- [x] Petitions Clerk - Create new paper petition
- [x] Petitions Clerk - QC eFiled Petition
- [x] Petitions Clerk - Add Order to case 
- [x] Court users - Download all docket entries
- [x] Admissions clerk adds in an email for eAccess to a Petitioner
- [x] Admissions Clerk - adds in a new practitioner
- [x] Admissions Clerk - adds/edits practitioner documentation
- [x] Reports - docket clerk
- [ ]
