### ISSUE TITLE
10417 Remove getCurrentUser minimum necessary changes

### ISSUE THREAD

**Issue by En-8** [ustaxcourt/ef-cms#8756]
This issue represents the minimum necessary work required to set up the pattern for removing applicationContext.getCurrentUser. The intent with splitting out this work is to ease the transition by making the change backwards compatible so that we don't create undue burden for (or just outright break) in-flight work while the broader set of changes is in test but not staging. There is also an example of what it will look like to move away from get current user on the back end.

**This is merely a preparatory refactor, it will not solve the bug identified in 10417**

While no functional changes are expected, here are the potentially-impacted areas, should something have gone wrong:
* Custom Case Report
* Maintenance mode
* All "public" endpoints
  * searches (case, order, opinion, practitioner)
  * viewing documents
  * Todays Orders & Todays Opinions

**Comment by ttlenard** [comment]
Let's be sure that we test the following:
- [x] Terminal user
- [x] Sealed case/doc visibility
- [x] policy date documents (decisions, briefs)
- [x] Opinions
- [x] Orders
- [x] Maintenance mode
- [x] Custom Case Report
