### ISSUE TITLE
Remove padding from button link focus state

### ISSUE THREAD

**Issue by swongCO** [ustaxcourt/ef-cms#8758]
As a Dawson user, so that I have a consistent experience, I need button links to have a standardized focus state.

<s>Nechama did try out a fix which removed the padding, but this will require some manual testing to make sure that everything that had padding removed, didn't actually need it. See this document for some regression testing done when the padding was removed: https://docs.google.com/document/d/1WtNGI1Y0bsudLiQmtCm_2hl2gl81lLAxlhMODwYFaRc/edit?usp=sharing</s>

Acceptance Criteria:

- Remove the padding around button links in the focus state for inline links in paragraphs/sentences
- Apply this to the petition flow for petitioners and private practitioners
- Determine if user documentation needs to be updated (Tenille): Y / N

Examples from petition flow:

<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--940f5613096ec97514b385aa86734d8501725907/Screenshot%202024-07-09%20at%202.12.14%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 2.12.14 PM.png" />

<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9HQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81948cabf2bec50d1533393cf058f67ec0d768bf/Screenshot%202024-07-09%20at%202.12.21%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 2.12.21 PM.png" />

<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf76198ec63365d564f7481652f7197c924ae30c/Screenshot%202024-07-09%20at%202.12.39%E2%80%AFPM.png" alt="Screenshot 2024-07-09 at 2.12.39 PM.png" />

Create a case:
<img width="1832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXc5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ca43195cbb81aaffb311550e9826cb929ead034/image.png" alt="image.png" />

<img width="1818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTA5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2cc3b27576d493912adeac35257763eef532bcf/image.png" alt="image.png" />

<img width="926" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdyswQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--417f2c52d3706046757132a18702335e664b19eb/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGUwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78d78f216407500a7e3ca898bbdbcadcaf427f39/image.png" alt="image.png" />

<img width="1136" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGkwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c238ed5befd07dce4828b847ce0e4231d42dd3d2/image.png" alt="image.png" />

<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXEwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01a9b8345d75a6c2b877865cd0cf4eca4db9d4c3/image.png" alt="image.png" />

<img width="440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWUwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68de2ec1a0b5c584d8ff82dda447897b37368ee5/Screenshot%202024-09-05%20at%2011.46.13%E2%80%AFAM.png" alt="Screenshot 2024-09-05 at 11.46.13 AM.png" />

___
The add irs Notice has a bit too much padding on the bottom. The add reason or fact buttons show the correct amount.
<img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWkwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--387eff3592d7226dafb67d23c98e5ac5bafa53fe/image.png" alt="image.png" />

___

<img width="902" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkswQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e3a691fc10044d361ceaebd03e9af66d8eb8a1d/image.png" alt="image.png" />

**Comment by swongCO** [comment]
**Test feedback**
Found something peculiar while testing and not sure if it's related to the work being done. Screenshots below of the menu in the pdf preview of different flows. Note that all the icon links except for one in each menu isn't centered vertically, including the vertical line that separates each link. They should all be centered vertically - last screenshot is how the menu should appear (not sure when it changed).

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2VwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0edb009d764a481d54cc18ec78908c61a6e99dee/Screenshot%202024-09-03%20at%203.16.04%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 3.16.04 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c484d0a5d24c8b1f9418fe1287ebc04df25beb81/Screenshot%202024-09-03%20at%203.27.14%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 3.27.14 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21wQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c774c02dcb599462192bfbee8c1f517de51f9498/Screenshot%202024-09-03%20at%203.48.26%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 3.48.26 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d0ad7b7b4e629c8eba7b7c76b304b2b057d57b8/Screenshot%202024-09-03%20at%203.49.02%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 3.49.02 PM.png" />

<img width="1510" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLytwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eba993995144f2692ea3cec0e95a180a24cfb06d/Screenshot%202024-09-03%20at%204.01.01%E2%80%AFPM.png" alt="Screenshot 2024-09-03 at 4.01.01 PM.png" />

**Comment by swongCO** [comment]
Due to unintended consequences, we are limiting this to only the petition flow for now. Some button links will be changed to anchor links (like the Learn more link on the order search page) per Nate's recommendation.

**Comment by katiecissell** [comment]
Moved the padding issues for the file upload component change button to [10479](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10479)
