### ISSUE TITLE
Align Iteration Field & Error Message

### ISSUE THREAD

**Issue by mwestereng1** [ustaxcourt/ef-cms#8766]
As a user of Dawson, I need field formatting to remain in alignment, so I have a consistent experience.

When the "What Iteration Is this filing?" field is empty and validated, the error message and input field move out of alignment. The "What Iteration Is this filing?" field appears when the following document types are selected (there may be more instances):

- Amended [Document Name]
- Amendment [anything]
- Request for Admissions
- Stipulation of Facts
- Supplement
- Supplement To [anything]
- Supplemental
- Supplemental [anything]

Existing error message example:
<img width="936" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1dbccf957b27668f04b4b905c4381adcf957e62/image.png" alt="image.png" />

The "Document type" dropdown that contains these list items can be accessed several ways:
1. Log in as an IRS Practitioner, Private Practitioner, or Petitioner and "File a Document"
    <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a49cc7d34f4c7ab36c170106888371373a82dfb/image.png" alt="image.png" />

2. Log in as a Cases Services Supervisor, Clerk of Court, or Docket Clerk and  "Create" > "Paper Filing"
    <img width="552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab470d9b21ec270a8234d69f5d948b52a7201c48/image.png" alt="image.png" />

### Pre Conditions: 
None

### Acceptance Criteria

- [ ] When and iteration is not selected, and the user saves their selection, the "What Iteration Is this filing?" field and error message remain aligned with the other fields, and error messages. 
- [ ] The text case is changed for "Iteration" and "Is", so the field title reads "What iteration is this filing?"
- [ ] These changes are made everywhere the "What Iteration Is this filing?" field appears in Dawson.
- [ ] Determine if user documentation needs to be updated (Tenille): Y / N

**Comment by katiecissell** [comment]
This affects file a document for private practitioner and petitioner as well as internal court users file a paper filing amendment.

**Comment by mwestereng1** [comment]
Error messaging and alignment look great! We noticed some discrepancies between the wording in the document type dropdown in Dawson and json, which are unrelated to this story.
