### ISSUE TITLE
Inaccurate banner is displayed for logged in petitioner

### ISSUE THREAD

**Issue by swongCO** [ustaxcourt/ef-cms#8770]
As a logged in petitioner, so that I am not confused, I should not see a banner that doesn't apply to me.

Logged in petitioners are seeing a banner in cases that they are not a party to that is inaccurate.
Steps to reproduce:
1. Log in as a petitioner.
2. Go to a case that hasn't been served and you are not a party to.
3. There is a banner informing the user that they can file a document after the petition is served.

Acceptance Criteria:

- Remove the alert banner for logged in petitioners unless they are party to a case
- Determine if user documentation needs to be updated (Tenille): Y / N

<img width="1561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49d00a0b2face5cd9c4adb5128b8a3b384abb886/Screenshot%202024-07-29%20at%202.01.30%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 2.01.30 PM.png" />

<img width="1182" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4fa4e87a08ba6b79af2304976fb9683102dc8ac/Screenshot%202024-07-29%20at%202.01.52%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 2.01.52 PM.png" />

**Comment by Mwindo** [comment]
It looks like we were just missing a "userIsAssociatedWithCase" check.

**Comment by swongCO** [comment]
UX Review
Passed testing with petitioner, private practitioner and IRS practitioner.
