### ISSUE TITLE
Docket Clerk: Remove Ability to Create Regular/Small/Hybrid/H-S Trial Sessions

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8776]
As a docket clerk, so that I don't accidentally create trial sessions that then need to be deleted, I need to be restricted to only being able to create Special trial sessions and Motion/Hearings.

When a docket clerk creates a trial session, they should be creating a Special session or a motion hearing in direct reference to an order that has been issued. All other types of trial sessions should be created by either petitions clerks or Case Services Supervisor roles. 

To prevent docket clerks from creating unnecessary or incorrect trial sessions which end up having to be removed from the system, we need to restrict the options available to them when creating trial sessions, and ensure that they can ONLY create Special sessions or motion hearings.

## Acceptance Criteria
* When creating a trial session, docket clerk users can only select either "Special" or "Motion/Hearing" as the Session Type
* When editing a trial session, docket clerk users can only select either "Special" or "Motion/Hearing" as the Session Type
* Docket clerks may **not** edit a trial session of types Regular, Small, Hybrid, or Hybrid-S in **any way**

## Notes
<img width="253" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGd4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e33763d7d6725999cda00bd20856262483f8a3a/image.png" alt="image.png" />

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- Should they still be able to edit those session types or no? They can still edit small/reg/etc but for session type they can change to their two options though. Chris is considering if we should force them to change session type to special or motion/hearing if they edit.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk user creates a new trial session; The only options available to them are "Special" and "Motion/Hearing".

- Log in to DAWSON as a Docket Clerk
- Click on the Trial Sessions header
- Click on the Add Trial Session Button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The only two available session types listed are Special and Motion/Hearing.



#### 2) Docket Clerk creates a Special Trial Session, Session is created successfully.

- Continuing from the previous test
- Fill out the required fields for a special session
- Click Save

Expected Results:
- [x] Special Session is created as per normal



#### 3) Docket clerk creates a Motion/Hearing; Session is created successfully.

- Continuing from the previous test
- Click on the Add Trial Session button
- Fill out the required fields for a Motion/Hearing
- Click Save

Expected Results:
- [x] Motion/Hearing is created as per normal



#### 4) Docket Clerk edits the Special Session that they just created; Only Special and Motion/Hearing session types are available; can edit session successfully.

- Continuing from the previous test
- Click on the City/State link of the special session that you just created
- Click on the edit link for the session

Expected Results:
- [x] **NEW FUNCTIONALITY** - The only Session Type options on the edit screen are Special and Motion/Hearing
- [x] Clerk can make any additional edits to the session that they created and save the session as per normal.

*Repeat this test by editing the Motion/Hearing that you created in the previous test
- [x] This test passes



#### 5) Docket clerk attempts to edit a Special Session that is in the past; no edit link is available

- This is a regression test to ensure existing functionality is still intact.
- Continuing from the previous test
- Click on the Trial Sessions Header
- Click on the City/State link for a Special session that has a past date.

Expected Results
- [x] There is no edit link available on the Session information page

*Repeat this test with a Motion Hearing that is in the past
- [x] This test passes



#### 6) Docket clerk opens a regular session; no edit link is available.

- Continuing from the previous test
- Click on the Trial Sessions Header
- Scroll down the list of sessions until you find a Regular session
- Click on the City/State link for the session

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is no longer any Edit link on the session information page
- [x] **NEW FUNCTIONALITY** - Docket clerk cannot get to the edit screen by manipulating the URL to get to the edit page - Clerk receives a 404.

*Repeat this test with other Session types
- [x] Small
- [x] Hybrid
- [x] Hybrid-S



#### 7) Regression test that other Court users still have existing permissions

- [x] The scenarios below pass
- [x] Users can only edit sessions that are in the future, not in the past


**Who can add new trial sessions?**
- Petitions Clerk
- Clerk of Court
- Case Services Supervisor
- ADC
- Admission clerk 
- General
- Trial Clerk
- Docket Clerk (only Special and Motion Hearing)

Who Can't
- Floater
- Judge
- Chambers
- Reporters Office

*These users get a 404 if they attempt to input the URL to add a trial session (https://app.test.ef-cms.ustaxcourt.gov/add-a-trial-session)


**Who Can Edit Trial Sessions that are in the future?**
- Judge
- Docket Clerk (only Special and Motion/Hearing)
- Petitions Clerk
- Clerk of the Court
- Case Services Supervisor
- Reporters Office
- ADC
- Floater
- General
- Trial Clerk
- Admissions Clerk


Who Can't?
- Chambers (but there is currently a bug - if a CA knows the edit link url (https://app.test.ef-cms.ustaxcourt.gov/edit-trial-session/058d4e26-550e-4792-a230-fdb44b9a4af8), then they can edit away
