### ISSUE TITLE
Operational Need: Judge Changes In DAWSON

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8778]
As the clerk of the Court, so that work is assigned properly, I need Judge Way and STJ Landy registered in DAWSON as judge roles.

Judge Kashi Way will be taking the oath of office on 8/7/2024. We need him to be present in DAWSON as a "regular" judge, with the ability to have chambers personnel assigned to him when they onboard.

STJ Landy will be taking the oath of office on 8/8/2024. We need to transition him from the role of Special Trial Judge to "regular" Judge, keeping his current user data intact (i.e., case assignments, chambers personnel, trial sessions, etc).

Both of these changes need to be live by Monday, 8/12/2024.

## Acceptance Criteria
* Judge Way can log into DAWSON with the permissions, signature, and functionality of a judge role
* Judge Landy can log into DAWSON with the permissions, signature, and functionality of a judge role
  - Judge Landy retains possession of existing cases, documents, assignments, messages

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by cholly75** [comment]
Confirmed email addresses for the judge users in this story:

Judge.Way@ustaxcourt.gov
Judge.Landy@ustaxcourt.gov

(I don't think WE care about the capitalization, but that's how they're getting entered into Outlook here at the Court.)

**Comment by Mwindo** [comment]
> Confirmed email addresses for the judge users in this story

Thank you @cholly75 ! Do we have a phone number associated with Way's chambers yet?

**Comment by Mwindo** [comment]
In the process of working on scripts to update Landy and add Way, we noted a few follow-up items/questions:

- Can we remove `@ustaxcourt.dawson.gov` user duplicates from lower envs?
- We are only creating `pk user-email` to `sk user` mapping records for petitioners, and we are not using `getUserByEmail` (which uses this mapping) in code. Is this intentional? Is this the result of a recent refactor?
- We have `createJudgeUserProxy.ts` that refers to a `POST` "/judges" endpoint, but we don't seem to have this in our routes. Why is this here?
- experimental4 seems to be broken:

<img width="1877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0k5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1255285859dd1a375eb7f9c8d1e72e4974d1c10/Screenshot%202024-08-07%20at%203.17.35%E2%80%AFPM.png" alt="Screenshot 2024-08-07 at 3.17.35 PM.png" />
