### ISSUE TITLE
Court users have visual indicator that Service Emails have been sent

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#879]
## Acceptance Criteria

- As a Court user, in order to know that the Court has performed its legal operation, it would be helpful to have a simple visual indicator for every successful (and unsuccessful) service email of any document.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

- SES reports a UUID for every successful sending. We could store this information and associate it with the docket entry record. We could link that UUID with each email address attempted to confirm which emails succeeded.

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by JessicaMarine** [comment]
@mmarcotte I'd like to better understand this story. If the order of operations is properly followed, the service information on the docket record would not be updated unless the email is successfully sent (https://github.com/flexion/ef-cms/issues/8039).  Isn't that the visual indicator?

**Comment by mmarcotte** [comment]
For me the visual indicator would be a 🟢  for each person where an email was successfully sent. So, if we attempted to serve 5 people, we would expect to see five green circles. If any errors were encountered sending, perhaps we could get a 🔴 . 

This could be improved upon in the future, 

- where if we had a way to track whether or not they opened the email or accessed the document this could perhaps be a 🔵 .
- we could retry service emails that failed
- we could track email bounces here

**Comment by mmarcotte** [comment]
@mmarcotte , @cholly75 , @ttlenard to chat about this and figure out next steps in the coming weeks

**Comment by mmarcotte** [comment]
doesn't look like this is going to happen :)
