### ISSUE TITLE
BUG: Users are being created without a userId

### ISSUE THREAD

**Issue by zachrog** [ustaxcourt/ef-cms#8796]
**Describe the Bug**
Some users in production do not have a custom:userId attribute in cognito. This means that they have no userId when they log in and the system will crash. Below is a report of affected cognito users.

[prod-users-no-custom-userId.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3c0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--270b2736eb26791021af1f954d2ba34d1d9b0b1e/prod-users-no-custom-userId.txt)

This issue may be related to bug ustaxcourt/ef-cms#8686

**Business Impact/Reason for Severity**
Users are unable to log into the Dawson system

**In which environment did you see this bug?**
production

**Who were you logged in as?**

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
Unknown how this bug is occurring. It can be confirmed that DAWSON is creating these malformed users.

**Expected Behavior**
All users get created and retain their custom:userId

**Actual Behavior**
Sometimes users are created without a userId or their userId is being removed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
Some Investigation notes:

I am seeing similar errors in the logs for a handful of these users.  For the users that I looked into, I see that they are getting an error that their user already exists, even though they only first created their account.  

<img width="1640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVE4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5a15924dc3f692115db89cda9d896c08ea3fca2/image.png" alt="image.png" />

<img width="1307" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVU4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dff2277ae8c9069f367a75a5ff70d3fcd2dfd1fa/image.png" alt="image.png" />

For the users with duplicate accounts, I believe that this is related to bug ustaxcourt/ef-cms#8686.  I was able to recreate this by adjusting this setting for my mouse, and I was able to duplicate this issue:

Here is a real user:
<img width="1439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWM4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12331e7cff0348f0c93f598b4143af635ab1788b/image.png" alt="image.png" />

Here are the logs from test. Notice I was able recreate it:
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWc4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccc08aaf658ebbc6c110ff19cdc3d1cb54abe232/image.png" alt="image.png" />

To recreate, adjust your mouse settings to this:
<img width="528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWs4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4c2427df813a59e6425a0dc08a1c8f848802c3a/image.png" alt="image.png" />

And you can see the results in Cognito. Two accounts created:
<img width="1557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXM4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4df72b2d88acb6773a556a66a5a3480af69e17e0/image.png" alt="image.png" />

Do we just need to disable the continue button after the first click? Seems this might be part of the problem?
<img width="1122" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkE4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db3ffc44bf4965cdd6e8901dca912d44b087c0d5/image.png" alt="image.png" />

**Comment by Mwindo** [comment]
I'm updating ustaxcourt/ef-cms#8686 with some findings that are relevant to this bug.

**Comment by Mwindo** [comment]
Part of this is explained by ustaxcourt/ef-cms#8686 (see comment thread there). The other part is explained by users who encountered errors on the old Cognito-hosted signup page. We will run a script to fix these users' accounts so that they can actually use DAWSON.

**Comment by Mwindo** [comment]
@jimlerza Feel free to reassign this as needed now that you have a handle on it!
