### ISSUE TITLE
Session Info Page: Public View

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8798]
As a member of the public, so that I can see what cases are currently scheduled to be heard at a trial session, I need a public view of the Session Info page.

In ustaxcourt/ef-cms#8797, we are implementing a public view of scheduled trial sessions. In doing so, the trial sessions will be hyperlinked as usual to the specific Session Info page for that trial session. Because we do not need or want to include irrelevant data to the user, we will need a customized public-facing view of the Session Info page for display to the public.

Note that this story and 10460 should be released together; a feature flag may be necessary to facilitate separate deployments for each.

## Pre-Conditions
ustaxcourt/ef-cms#8797

## Acceptance Criteria
* Page is accessible to public facing (i.e., non-logged in user)
* Page title displays city/state, start date of session
* Page displays information contained in "Courthouse Information" if the trial session proceeding type is **In Person**
  - If proceeding type is Remote then no Remote Proceeding information is displayed 
* All other info/cards removed from public facing page (Details, Assignments, Notes)
* Page retains current format of internal view of Trial Sessions page with the following exceptions:
  - Tabs/Views removed: Inactive Cases/All Cases
  - Columns removed: Calendar Notes
  - Icons added: red "seal lock" for cases on the session that are sealed
    - Note: would like to add this to internal view as well if possible
  - Page retains Docket No., Case Title, Petr/Respondent Counsel columns
* Docket No. links direct user to public view of Case Page
  - Clicking on a sealed case hyperlink directs users to the sealed case error/info UI
* List of open cases on page matches list of open cases on internal view at all times
* Text addition to page: "Information on this page is current as of [current mm/dd/yy 12:00 AM Eastern]" (use current time in est)
* Re-enable incoming links from page created in ustaxcourt/ef-cms#8797

## Notes
* If the trial is a swing session, do we need to indicate which session it's linked to on this page? - Chris to answer

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX Notes:

[Figma File](https://www.figma.com/design/VD71xuva6ACC1OSF7kXVRx/USTC-%7C-10460%2C10461-%7C-Public-Trial-Sessions?node-id=170-784&t=qAvvNmbGilPG3pkv-1)
![Image](https://github.com/user-attachments/assets/ebdadebb-fd5c-4e25-b1e3-87597bcc9a5a)


![Image](https://github.com/user-attachments/assets/75102de2-5801-4f94-9baf-359cdc1eec09)

![Image](https://github.com/user-attachments/assets/b8eab724-13af-41cf-a3ca-464ca0e69806)
![Image](https://github.com/user-attachments/assets/0681fcff-647f-48e0-91a3-26988ace7d4a)

___
Adding sealed icons to internal view:

![Image](https://github.com/user-attachments/assets/d70f877d-b7a7-452f-884c-6ede0494c187)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Public user clicks on the City, State link for an In Person session from the new Scheduled Trial Sessions Page; The new Public version of the Session information page opens.

- As a public non-logged in user, navigate to the new Scheduled Trial Sessions Page (Story ustaxcourt/ef-cms#8797)
- Click on the City, State link for an in Person session on that page 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The public version of the In Person Session Information page displays (see mockup)
- [x] **NEW FUNCTIONALITY** - Page header in blue states City, State, with the start date underneath (does not display estimated end date if there was one)
- [x] **NEW FUNCTIONALITY** - There is a breadcrumb at the top of the page that when clicked, navigates the user back to the Scheduled Trial Sessions Page
- [x] **NEW FUNCTIONALITY** - Underneath the page title "Session Information", sentence states the current date/timestamp (ET) (see mockup)
- [x] **NEW FUNCTIONALITY** - There is a details card that includes the Courthouse location
- [x] **NEW FUNCTIONALITY** - If it is a swing session, it is indicated to the right of the Courthouse address with a link to the Session
- [x] **NEW FUNCTIONALITY** - Clicking on the link to the swing session opens the session information page on the same tab
- [x] **NEW FUNCTIONALITY** - There is a table of open cases listed below the details card (See mockup for column headers/format), along with a total count.
- [x] **NEW FUNCTIONALITY** - Sealed cases display the red lock icon, with a hover tip indicating it is a sealed case
- [x] **NEW FUNCTIONALITY** - Consolidated cases display the Consolidated icons for lead/member case, with a hover tip indicating the appropriate type of case
- [ ] **NEW FUNCTIONALITY** - Sealed and consolidated icons meet accessibility guidelines

*double check that the total number of open cases displayed on the Public Session Information page matches what is displayed for the session when viewed by an internal user.


#### 2) Public user clicks on the City, State link for a remote session from the new Scheduled trial sessions Page; the new Public version of the Session information page opens.

- As a public non-logged in user, navigate to the new Scheduled Trial Sessions Page (Story ustaxcourt/ef-cms#8797)
- Click on the City, State link for a remote session on that page 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The public version of the Remote Session Information page displays (see mockup)
- [x] **NEW FUNCTIONALITY** - Page header in blue states City, State, with the start date underneath (does not display estimated end date if there was one)
- [x] **NEW FUNCTIONALITY** - There is a breadcrumb at the top of the page that when clicked, navigates the user back to the Scheduled Trial Sessions Page
- [x] **NEW FUNCTIONALITY** - Underneath the page title "Session Information", sentence states the current date/timestamp (ET) (see mockup)
- [x] **NEW FUNCTIONALITY** - There is a details card ONLY if the remote session is part of a swing session. If no swing session, there is NO Details card
- [x] **NEW FUNCTIONALITY** - If it is a swing session, it is indicated in the Details card (see mockup)
- [x] **NEW FUNCTIONALITY** - Clicking on the link to the swing session opens the session information page on the same tab
- [x] **NEW FUNCTIONALITY** - There is a table of open cases listed below the details card if swing session. If no swing session, no details card (See mockup for column headers/format)
- [x] **NEW FUNCTIONALITY** - Sealed cases display the red lock icon, with a hover tip indicating it is a sealed case
- [x] **NEW FUNCTIONALITY** - Consolidated cases display the Consolidated icons for lead/member case, with a hover tip indicating the appropriate type of case
- [ ] **NEW FUNCTIONALITY** - Sealed and consolidated icons meet accessibility guidelines

*double check that the total number of open cases displayed on the Public Session Information page matches what is displayed for the session when viewed by an internal user.



#### 3) Public user clicks on the docket number link (non-sealed case) from the Session Information page; Case opens and displays case as per usual for the public user.

- Continuing from the test above
- Click on the docket number for a (non-sealed) case on the Session information page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case docket record opens and displays the case as per usual for the public user (just the docket record tab, only Orders, practitioner filed briefs, amicus briefs, decision documents filed on 8/1/23 and later are linked.)
- [x] **NEW FUNCTIONALITY** - Sealed documents on the docket record display as per usual, same with stricken



#### 4) Public user clicks on the docket number link (sealed case) from the Session Information Page; Case opens and displays case as per usual for the public user.

- Continuing from the test above
- Click on the docket number for a (sealed) case on the Session information page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case page opens, but displays the red banner along with the information about how the case is sealed as per usual.


#### 5) User opens up their console and reviews the case JSON; Sealed case info is limited to ONLY what is displayed on the screen, no other case information is displayed for the sealed case. (Dev discretion - probably best to do the same for non-sealed cases too?)

- Continuing from the test above
- Review the Session information page
- Be sure that your console is open to the network tab
- Click on the JSON view and review the case list for the session

Expected Results:
- [x] No additional case information is displayed for sealed cases, other than what is displayed on the screen.
- [x] Dev discretion - Non-sealed cases display the same data as sealed cases? only what is displayed on the screen?


#### 6) Repeat the tests above on a mobile device

- [x] Tests pass on iOS
- [x] Tests pass on Android
- [ ] Clicking on the swing session icon, Sealed icon, and consolidated icons display the helper text appropriately on mobile.
- [x] Mobile design matches mockups
- [x] When there is no petitioner counsel, header for "Petitioner Counsel" is not displayed on mobile



#### 7) Docket Clerk user removes a case from an open trial session; Case no longer displays on the public Session information view.

- As a public non-logged in user, navigate to a scheduled trial session and take note of the open cases
- Next, log in as a Docket Clerk, Navigate to the same scheduled trial session and remove a case from the trial
- Log out
- As the public user, navigate back (or refresh) the page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The open cases that are listed no longer displays the case that the docket clerk removed.
- [x] **NEW FUNCTIONALITY** - The current date/timestamp is updated.




#### 8) Seal icons are now displayed on the internal Session Information Page (all tabs) (also the Session Copy and printed pages?) - Dev Discretion!

- This is dev discretion on if this is added internally.

- [x] Icons are added (UPDATE: At the time of testing, the sealed icon was added to the session info page and the eligible case list, but NOT the session copy or printed pages of the session info/copy)

**Comment by katiecissell** [comment]
Mocks updated 11/1/24 to reflect that sealed cases for public view will show only the docket number, sealed icon, consolidation icon and the word sealed.

**Comment by Mwindo** [comment]
We are spending some time refactoring what subset of case information different sorts of users have for sealed and unsealed cases (e.g., public user, internal court users, non-internal user). The current logic (most of it in `getCaseInteractor`) is difficult-to-follow and has some redundancies. We want to streamline the logic and also make sure it is enforced in our entity constructors (e.g., `PublicCase`) so that anytime we create a particular entity we can know what data is available (rather than particular interactors being responsible for that).

**Comment by Mwindo** [comment]
After discussion with @ttlenard and @cholly75, I've decided to first finish the story without the above-mentioned refactor. While I think the refactor is an important one, it will require thorough testing, which could delay the release of the feature itself (especially if complications arise). Depending on the situation after that, my goal is to open a fast-follow ticket addressing the refactor. At worst, I will open a devex card with details.

**Comment by Mwindo** [comment]
Quick note: We have decided to add the sealed icon to the New Trial > Eligible Cases view as well.

**Comment by swongCO** [comment]
### UX feedback

- [x] Details card: increase courthouse address line height to 24px (matches the internal view styling)
- [x] Details card: wrap text so it doesn't wrap partially
![Image](https://github.com/user-attachments/assets/3d1e0147-2dbe-48ba-a926-1bfb24ddd8bc)

- [x] Swing session icon hover tip should match what's on the public trial sessions page: "Swing session: will be held in two cities"
- [x] Sealed icon hover tip: capitalize "s" (can punt to DD at dev discretion)
- [x] Do not display term tag next to location in the blue header banner
- [x] Table counter: change the font weight of the number to Regular
- [x] Table counter: At a certain breakpoint, it jumps to the left edge of the table - it should be aligned to the right edge of the table
- [x] Table: make the table scrollable when it can't display fully in small screen sizes
![Image](https://github.com/user-attachments/assets/f2fdbd95-6d14-4c5c-b9d8-a23052efff97)

- [x] The icons column header currently is read by VoiceOver as "lead case indicator" - change to "Icons for consolidated and/or sealed cases"
- [x] There are three H1s and one H3 (no H2) - John and Nechama will remove one H1 (welcome text) so the location in the blue banner text can remain H1; Session Information can be H2; Details can be H3

**Comment by swongCO** [comment]
### UX feedback
For smaller screen widths:
- [x] Reduce spacing between icon and docket number
- [x] Vertically center icon inside of row (if not possible, align it with the baseline of the docket number)
- [x] When both sealed and consolidated icons are displayed, do not stack - display side by side

![Image](https://github.com/user-attachments/assets/94170018-2295-46bc-b295-04adfcfc0298)
![Image](https://github.com/user-attachments/assets/004880e8-8098-438a-90fd-e4fcf2dbca3d)

Mobile portrait view:
- [x] Left align docket numbers with case title et al
- [x] Reduce spacing between icon and docket number
- [x] Don't replicate label for counsel if there is more than one - list names under the same label like on desktop view
<img src = "https://github.com/user-attachments/assets/9123d48d-cd3d-413e-9153-e2b5f4ab5248" width = "300">

**Comment by swongCO** [comment]
### UX feedback

- [x] Member case docket no. should be indented (like current eligible cases for internal users)
- [x] All cases in a consolidated group should be displayed adjacent to each other

![Image](https://github.com/user-attachments/assets/bf69a927-5325-4cfa-bc24-97f3bf482a2c)

**Comment by ttlenard** [comment]
Testing Feedback @Mwindo 

- [x] Test case 1/Expected Result 2 - This indicates that there shouldn't be an estimated end date in the header.  I'm seeing the estimated end date displayed.  Looks like we removed estimated End date from view in #10460, so we shouldn't be displaying it on the session info page. Thanks!

![Image](https://github.com/user-attachments/assets/809cbdd1-85aa-4f77-a831-6f8d99df1332)

**Comment by ttlenard** [comment]
Testing Feedback: @Mwindo 

I'm seeing an issue where the Session info page opens, but then it immediately goes back to the Trial sessions page. I've outlined the steps and also included a recording of it happening.

1. Go to the Trial sessions page
2. I filtered the list by remote (this step isn't necessarily needed)
3. Click on a session URL
4. The Session info page should open
5. Click go back to trial sessions
6. Click on a session URL
7. What I am experiencing is that the page flashes to open the Session info page, but then it immediately goes back to the Trial Session page. The URL showed the session ID that I clicked on. If I click refresh, only THEN would the session info page display.

Note: You might need to click on a few sessions for it to happen. It's not being consistent on a specific session, it seems random.

Here is the video:https://github.com/user-attachments/assets/8d29e64a-f65b-4349-9e72-f0b44e01a8c7

**Comment by Mwindo** [comment]
Well that's no good. Looking into it now.

UPDATE 1: The same behavior can be triggered with the back button. It looks like a race condition (we set the page information for Trial Session Details, but then re-set the page information for Trial Sessions depending on timing) ... but I am still trying to discern how that comes about.

UPDATE 2: For some reason, it seems we are triggering the trial sessions page twice, and then one of those triggers is then "overwriting" the page info for session details. This behavior does not occur in my local environment. 

https://github.com/user-attachments/assets/a0dcb9e1-1f90-44f0-b6e3-6433dfa4aff0

UPDATE 3: This was due to a botched merge conflict in test. It should be resolved now.

**Comment by ttlenard** [comment]
Testing feedback:

Just putting this comment here so that we do not forget about it later:

Everything looks good, with the exception of the swing session icon, consolidated icon, and sealed icons not being able to be clicked/hovered on mobile. This fix should be addressed with Design Debt ticket https://github.com/flexion/ef-cms/issues/10548
