### ISSUE TITLE
BUG: Parties are able to select documents that are in the Draft folder, stricken, and not served for some document type scenarios

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8801]
**Describe the Bug**
Petitioners, Private Practitioners, and IRS Practitioners are able to see and select documents that are in the draft folder on a case when they are filing certain types of documents that require selecting a secondary or tertiary document.  For example, a Petitioner filing an amended document is asked "What document are you amending?" and they are presented with a dropdown picklist of documents that are on the docket record.  The problem is that documents that are in the drafts folder are also displaying on this list and they shouldn't be.

We also found that stricken documents and documents that have not yet been served appear in the picklist too.

The good news is that these draft/stricken/unserved documents are not visible to the public, it's just the title of the document. Displaying additional document titles that are not on the docket record can also be confusing to the user since it appears that they may be listed in the date they were created?

I believe this is happening for the following document type scenarios:
- Scenario A (example: Redacted)
- Scenario C (example: Declaration in support of)
- Scenario D (example: Certificate of Service for)
- Scenario F (example: Amended)
- Scenario H (example: Motion for leave to file/File out of time + one of the document types above)

**Business Impact/Reason for Severity**
Medium - draft documents titles should not be visible to the public.

**In which environment did you see this bug?**
Staging and Test

**Who were you logged in as?**
Petitioner, Practitioner, IRS Practitioner

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**
1. Log in as a docket clerk
2. Navigate to a case
3. Click on the Create menu, and select PDF upload
4. Upload a document and title it something unique (not a document title that already exists on the docket record)
5. Save the PDF upload
6. It should now be in the drafts folder
7. Be sure that for the case you are in, you also have access as a petitioner, private practitioner, or IRS Practitioner. If you don't, be sure to add one as a party to the case
8. Next, log in as that party (petitioner, private practitioner, IRS Practitioner)
9. Navigate to the case
10. Click File a document
11. On the what document are you filing page, select Amended (or the other scenario type documents listed in the description of this ticket)
12. On the What document are you amending dropdown, notice that the draft document title is available for you to select. This should not be displayed here.

**Expected Behavior**
Documents in draft should not be available to be selected in the document dropdowns for parties filing secondary or tertiary documents.  Should also not display stricken documents, or documents that have not yet been served.

**Actual Behavior**
A clear and concise description of what actually happened.
Documents in draft are currently able to be selected when parties are filing documents that have a secondary or tertiary document selection.

**Screenshots**

Secondary document picklist showing draft documents:
<img width="1078" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVphQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6983d3d3b40390c12f579468e663ff222d778d95/image.png" alt="image.png" />

Tertiary document picklist showing draft documents
<img width="923" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3c135c175d4172a51c337e54ccad5bf25754cda/image.png" alt="image.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by Mwindo** [comment]
The fix itself should be easy enough: `selectDocumentTypeHelper.ts` has a function `getPreviouslyFiledDocuments`. It is used only in this case (populating the dropdown menu in the scenarios Tenille has listed), so we can add some filtering logic to the function and rename it for clarity. That said, the best way to implement this filtering logic is not 100% clear to me: we have various ways of "formatting" docket entries (e.g., sometimes, it seems, we have an `isDraft` property; sometimes we don't). I think it is worth spending a little extra time to go through and 1) ensure the properties we expect to filter by are always actually available in this function and 2) investigate and maybe reduce the discrepancies between the different formats for docket entries.
