### ISSUE TITLE
Update Email Validation Error Message

### ISSUE THREAD

**Issue by mwestereng1** [ustaxcourt/ef-cms#8802]
As a Dawson user, I need error messages to tell me specific actions to take, so that I can correct my submissions.

Some email fields in DAWSON give a generic error message when validating an email address for correct formatting. We would like to update all email address fields in the system to one consistent error message when the email address provided is not in the correct format.

[Link to the Figma File](https://www.figma.com/design/O9AjyS26VCz2Cml4cpF3uT/Design-%2F-Tech-Debt?node-id=436-20)

This is the correct error message that we would like to use when user inputs any text or characters that are not in the correct email address format for required or optional email fields. This is a correct example from "Review & Serve Petition":

![Image](https://github.com/user-attachments/assets/dce60a16-b4b4-42e6-a065-591b4ee6ea97)

![Image](https://github.com/user-attachments/assets/23e3f225-a65b-4019-b4ca-bad6754b0c39)

If the field is required, but they don't enter any text or characters, the error should retain the same "Enter a valid email address" message. 
![Image](https://github.com/user-attachments/assets/fa3204de-b453-497e-b43d-b62d4f132f02)

If there are multiple fields for validating the email address (ie. "Change Login & Service Email Address"), the error messages should update individually based on if/what text or characters are entered into each the field.
![Image](https://github.com/user-attachments/assets/1750626b-9623-4382-a354-208532a393d8)

___

**IMPORTANT NOTE: If any of these email validation updates prevent a dropdown selection chosen by the court from passing validation, we do not want to implement the format validation.** 

For example, most of the time adding or editing an IRS calendar administrator for a trial session is done through a drop down menu and the email address auto-populates (see image below). If that auto-populated email address can't pass validation, we do not want to add validation to this field. This field currently does not have validation. This example shows an anonymized email address in the pre-production environments, instead of their actual email address. We also don't want to prevent these anonymized emails from passing validation in the pre-production environments.
![Image](https://github.com/user-attachments/assets/0d9a719d-a194-43db-9785-297f187d3efc)

___

Below is a summary of where email address fields are located that need to be updated.

___

**"Create Account" (text only update)**

Accessed:
1. Create Account
2. Log In > Create your account now

For this scenario only, we are not changing the styling of the error message. We are only updating the text. 

Current error message and styling
![Image](https://github.com/user-attachments/assets/51fe7d40-2708-44e1-93f4-279d90e14bdc)

If the email address is in the incorrect format, update the error message text only to: "Enter email address in format: yourname@example.com"
![Image](https://github.com/user-attachments/assets/6e523dc9-c630-48e7-8feb-632443735863)

If no email address is entered, there are no changes to the current error message. The error message should state "Enter a valid email address"
![Image](https://github.com/user-attachments/assets/6cbf9e83-bf0e-42f9-95b6-e8bf4380539e)

___ 

**"Change Email"**

Login as a Petitioner > Utilities > My Account > Change Email 

![Image](https://github.com/user-attachments/assets/83384c8f-c4fa-4766-9d79-934b370ea851)

Login as Private Practitioner, IRS Practitioner, or DOJ Attorney > Utilities > My Account > Change Email
![Image](https://github.com/user-attachments/assets/f90c61c9-9475-4028-8eb7-10eebaa78ecc)

Current email error messages
![Image](https://github.com/user-attachments/assets/af345fb5-c225-4987-9261-e666e7060116)

___

**Admissions Clerk - "Add New Practitioner"**
Login as an Admissions Clerk > Advanced > Practitioner > Add New Practitioner > Login & Service Email > Change Login & Service Email

Pathway to "Add New Practitioner"
![Image](https://github.com/user-attachments/assets/59d480e0-43b3-4271-b603-60b533749190)

Current error messages
![Image](https://github.com/user-attachments/assets/5ac736f4-b59f-4ca7-8d42-b1caa20a1390)

![Image](https://github.com/user-attachments/assets/ce3fabf9-0a0f-4dc3-88f7-704a7d81a7e5)

___

**Admissions Clerk - Edit Practitioner**
Login as an Admissions Clerk > Advanced > Practitioner > Search for existing practitioner > select practitioner > Edit > Login & Service Email > Change Login & Service Email

Current pathway to "Edit Practitioner"
![Image](https://github.com/user-attachments/assets/324a0a29-4bf4-4003-9ef2-d630b6c889ca)

Current error messages
![Image](https://github.com/user-attachments/assets/a14feff7-87d7-40d2-9b2d-43b62fcedd3f)

![Image](https://github.com/user-attachments/assets/53529bb4-2845-4685-9ced-2c9eeb7d74d4)

___

**Not pursuing with this design debt
Add or Edit Trial Session IRS Calendar Administrator Email** 
URL: https://app.test.ef-cms.ustaxcourt.gov/edit-trial-session/e85e85c2-84fb-4bdd-bef6-01a07e4a8361

<s>Log in as a Admissions Clerk, Assistant Deputy Counsel, Case Services Supervisor, Clerk of the Court, Docket Clerk, Petitions Clerk, or Trial Clerk
1. Trial Sessions > Select trial session from the list > "Edit" Session Information > Session Assignments > Email (Optional)
2. Trial Sessions > "Add Trial Session" > Session Assignments > Email (Optional)

Access pathway is slightly different for a Judge:

1. Dashboard >  Select trial session from Upcoming Trial Sessions > "View All Session Info" "Edit" Session Information > Session Assignments > Email (Optional)</s>

___

**Court User Creates a Petition**

Log in as a Case Services Supervisor, Clerk of the Court, or Petitions Clerk

Document QC > "Start a Petition" > Parties > "E-service consent" = checked 

Currently, there is no email validation if they check the "E-service consent" box. 
![Image](https://github.com/user-attachments/assets/f721e5d2-fd73-40c5-9316-1c3f4d723bb0)

___

### Pre-Conditions:
None

### Acceptance Criteria:
- [ ] Only for "Create Petitioner Account" the error message style will remain the same. 
     - [ ] If user doesn't enter any text or characters, keep current "Enter a valid email address" error message. 
     - [ ] If user enters text or characters in the field that are not in the correct email address format, update error message to "Enter email address in format: yourname@example.com".
- [ ] If email field is required, but user doesn't enter any text or characters, keep current "Enter a valid email address" error message. 
- [ ] If email field is optional or required and user enters text or characters in the field that are not in the correct email address format, update error message to "Enter email address in format: yourname@example.com".
- [ ] For court user, creating a petition, add validation and error message if "E-service consent" box is checked
     - [x] If user does not enter any text or characters, error message, "Enter a valid email address" should be displayed.
     - [ ] If user enters text or characters that are not in the correct email address format, "Enter email address in format: yourname@example.com" should be displayed.
**- [ ] If any of these email validation updates prevent a dropdown selection (ie. IRS calendar administrator for a trial session) from passing validation, we do not want to implement validation or format validation for those fields.**
- [ ] Determine if user documentation needs to be updated (Tenille): Y / N

Pain Avoided/Frustration Saved:
Error message tells users exactly what they need to do to fix the error that is preventing their submission.

Breadth/Pervasiveness of Problem:
This primarily affects users who are creating a new petitioner account, or users who are changing their email address for login or service.

Complexity of Problem (Low, Medium, High) and Why it's Complex:
Low

**Comment by mwestereng1** [comment]
### UX Notes:

- [ ] Implement real-time  inline validation for the email fields.
- [ ] Validation seems to persist from one user session to the next. To re-create this behavior, login as a petitioner, go to My Account > Change Email. Enter an email address that will give you an error message. Log out, and log back in as a petitioner go to My Account > Change Email. The user receives a live error message.
- [ ] Disregard the email validation for adding/changing an IRS Calendar Administrator for the concerns raised at the beginning of this story.
- [x] When a court user creates a petition (https://app.test.ef-cms.ustaxcourt.gov/file-a-petition/step-1), if the "E-service consent" box is checked, and 
     - [ ] No email address is entered, the user should receive the "Enter valid email address" error message
     - [ ] The email is in an invalid format

Error message when they enter an email address in an invalid format, and the box is NOT checked (this is correct)
![Image](https://github.com/user-attachments/assets/7dde86c1-155e-457b-9b06-491d638d25f9)


Error message when they enter an email address in an invalid format, and the box IS checked (this is correct)
![Image](https://github.com/user-attachments/assets/65941d0e-3888-47c5-8ce0-3dcfebdd8ade)


No error message when the "E-service consent" box is checked and no email address is entered (they should receive an error message in this case)
![Image](https://github.com/user-attachments/assets/822baddf-0595-4e6a-974e-2bd07e96421b)

**Comment by mwestereng1** [comment]
[Google Doc](https://docs.google.com/document/d/1kNfPyBknuTuus30cikMKi0m037kE9H-8NOVsz0ibd4I/edit?usp=sharing) with some findings

**Comment by mwestereng1** [comment]
Added comments to the [Google Doc](https://docs.google.com/document/d/1kNfPyBknuTuus30cikMKi0m037kE9H-8NOVsz0ibd4I/edit?tab=t.76v2ieaqbw62) in the tab UX Review 10-17-24

**Comment by mwestereng1** [comment]
Since there is overlap between [10074](https://github.com/orgs/flexion/projects/11/views/1?pane=issue&itemId=76509709&issue=flexion%7Cef-cms%7C10074) and 10466, it is best to proceed with testing them at the same time. If that is not possible, it would be best to test 10074 first. 

Most recent UX comments to the [Google Doc ](https://docs.google.com/document/d/1kNfPyBknuTuus30cikMKi0m037kE9H-8NOVsz0ibd4I/edit?usp=sharing) under the UX Review 10-25-24 tab. A couple of options for future development:
- When editing a practitioner, the duplicate email validation that does not clear is a bug. Needs a separate story.
- For the two inline error messages, but only one banner error message. We could have two separate messages as a separate story. For example, "Enter a valid email address" and "Re-enter a valid email address".
- The inline validation that does not update for the petition email address if the e-service consent box is checked is being fixed.

**Comment by ttlenard** [comment]
Testing Feedback @akuny @mwestereng1 

- [ ] Please remove any validation added to the Petition email address field/E-service consent in the Paper Petition workflow.  These fields were implemented originally with no validation by design. Here's the logic: When a Petitions clerk inputs a paper filed petition, the clerk transcribes all data that is on the paper petition into the electronic form in DAWSON. The paper form that they receive very well may have an invalid email address, a missing email address, or even just the E-Service consent checkbox checked, without ANY email added to the paper form.  We need to be able to allow Petitions clerks the ability to input whatever was input on the paper form without running into validation.

This example would be ok - no validation errors should occur with this:
![Image](https://github.com/user-attachments/assets/a4080e26-6f86-4189-b81e-20ed41330426)

This is ok too.
![Image](https://github.com/user-attachments/assets/cf5bfe2e-9d62-43c5-9bb9-9e444d09b0ae)

This should also be ok.
![Image](https://github.com/user-attachments/assets/b8233d33-0226-4fe3-8397-636064b53743)

**Comment by TomElliottFlexion** [comment]
Re: the comment above; we're keeping existing validation on the `paperPetitionEmail` field. This means that the E-service consent checkbox is not validated, and the petition email address can be empty OR a valid email address
