### ISSUE TITLE
Update trial swing session question to sentence case

### ISSUE THREAD

**Issue by mwestereng1** [ustaxcourt/ef-cms#8804]
As a Dawson user, so that I have a consistent experience in Dawson, I need field labels to be consistent.

Log in as any user who has the ability to edit a new or open trial session: Admissions Clerk, Assistant Deputy Counsel, Case Services Supervisor, Clerk of the Court, Docket Clerk, Petitions Clerk, Trial Clerk

Trial Session > Select a New or Open trial session in the future > "Edit" Session Information > "This is part of a Swing session" = checked  

Change "Which Trial Session is This Associated With?" to sentence case "Which trial session is this associated with?"

<img width="671" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGgvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ae7bab1d1a671b2a77b716c7b60149f90ee47d0/image.png" alt="image.png" />

___

### Pre-Conditions:
None

### Acceptance Criteria:
- [ ] "Which Trial Sessions is This Associated With?" has been changed to sentence case
- [ ] Determine if user documentation needs to be updated (Tenille): Y / N

Pain Avoided/Frustration Saved:
Field label consistency throughout Dawson.

Breadth/Pervasiveness of Problem:
Minor, only impacts users who are editing and linking/swinging trial sessions.

Complexity of Problem (Low, Medium, High) and Why it's Complex:
Low

**Comment by jimlerza** [comment]
Note: this was implemented by @akuny and the code came along with ustaxcourt/ef-cms#8806 in [PR ustaxcourt/ef-cms-flexion#5355](https://github.com/ustaxcourt/ef-cms/pull/5355).
