### ISSUE TITLE
Fix flaky cypress test

### ISSUE THREAD

**Issue by Mwindo** [ustaxcourt/ef-cms#8811]
`cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts` fails relatively often. Arbitrary examples:

- https://github.com/ustaxcourt/ef-cms/actions/runs/10601286770/job/29380746494?pr=5292
- https://github.com/ustaxcourt/ef-cms/actions/runs/10292721434/job/28487666411?pr=5223
- https://github.com/ustaxcourt/ef-cms/actions/runs/10371284717/job/28711228936
- https://github.com/ustaxcourt/ef-cms/actions/runs/10355568380/job/28663508993?pr=5176

Let's figure out how how to prevent the failure since it can add ~15 extra minutes to a push/deploy/etc.

**Comment by pixiwyn** [comment]
Should we fix flaky tests as apart of our stories, irregardless of inconvenience that it may cause?
We should fix flaky tests as apart of our stories going forward.
