### ISSUE TITLE
M112/M116 Should Automatically Register As Pending Items When Filed

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8815]
As a Court, so that cases are appropriately blocked when counsel is requested to be withdrawn, I need paper and e-filed Motion to WIthdraw As Counsel and Motion to Withdraw Counsel (petitioner filed) to automatically be tracked as Pending Items on a case when filed.

When a motion is filed, it is automatically added as a Pending Item on the Tracked Items associated with the case, and a Blocked label is put on the case. This is so that the Court knows that a motion is awaiting disposition before the case advances further in the process.

M112 and M116 (Motion to Withdraw As Counsel and Motion to Withdraw Counsel (petitioner filed) for some reason do not do this; they should. 

## Acceptance Criteria
* When a Motion to Withdraw as Counsel is paper or e-filed, it registers as a Pending Item on the Tracked Items associated with the case
* When a Motion to Withdraw Counsel (petitioner filed) is paper or e-filed, it registers as a Pending Item on the Tracked Items associated with the case
* Both M112 and M116 behave as motions in every other regard (including removing the "Track Document?/Add to pending report" option on the Docket QC UI)

## Notes
* Looking in https://github.com/ustaxcourt/ef-cms/blob/staging/shared/src/tools/externalFilingEvents.json and https://github.com/ustaxcourt/ef-cms/blob/staging/shared/src/tools/internalFilingEvents.json it appears that both M112 and M116 are classified under "Appearance and Representation" rather than "Motions", possibly why this is occurring? These are the only two motions exhibiting this reported behavior.
* Note that this may be cause to revisit ustaxcourt/ef-cms#8243 and refactor work done in that story to extend stamp grant privileges to these two motions as well.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- this may actually be a bug (Tom please explain)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner eFiles a Motion to Withdraw as Counsel; The case that the motion was filed on has this motion on the Pending Items tab, and the case is blocked.
- Log in as a Private Practitioner that is associated with at least one case
- Click on the docket number of the case
- Click on the File a document button
- Select Motion to Withdraw as Counsel document type
- Upload the document
- Click Next
- Check the box to acknowledge redaction
- Submit the document
- Next, log in as a Docket Clerk
- Click on Document QC/Section Document QC
- Find the Motion document that was just filed
- Click on the document title
- QC the document and send a message to the assigned judge or ADC
- Navigate back to the case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case header now displays that the case is blocked from trial
- [x] **NEW FUNCTIONALITY** - The Motion to Withdraw as Counsel is now displayed on the pending items tab and there is an indicator on the tracked items tab as per normal



#### 2) IRS Practitioner eFiles a Motion to Withdraw as Counsel; The case that the motion was filed on has this motion on the Pending Items tab, and the case is blocked.  

- Log in as an Practitioner that is associated with at least one case
- Click on the docket number of the case
- Click on the File a document button
- Select Motion to Withdraw as Counsel document type
- Upload the document
- Click Next
- Check the box to acknowledge redaction
- Submit the document
- Next, log in as a Docket Clerk
- Click on Document QC/Section Document QC
- Find the Motion document that was just filed
- Click on the document title
- QC the document and send a message to the assigned judge or ADC
- Navigate back to the case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case header now displays that the case is blocked from trial
- [x] **NEW FUNCTIONALITY** - The Motion to Withdraw as Counsel is now displayed on the pending items tab and there is an indicator on the tracked items tab as per normal



#### 3) DOJ Practitioner eFiles a Motion to Withdraw as Counsel On a case that is on appeal; The case that the motion was filed on has this motion on the Pending Items tab, and the case is blocked.

- Log in as a DOJ Practitioner that is associated with at least one case that is on Appeal
- Click on the docket number of the case
- Click on the File a document button
- Select Motion to Withdraw as Counsel document type
- Upload the document
- Click Next
- Check the box to acknowledge redaction
- Submit the document
- Next, log in as a Docket Clerk
- Click on Document QC/Section Document QC
- Find the Motion document that was just filed
- Click on the document title
- QC the document and send a message to the assigned judge or ADC
- Navigate back to the case

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Case header now displays that the case is blocked from trial
- [ ] **NEW FUNCTIONALITY** - The Motion to Withdraw as Counsel is now displayed on the pending items tab and there is an indicator on the tracked items tab as per normal



#### 4) Petitioner eFiles a Motion to Withdraw Counsel; The case that the motion was filed on has this motion on the Pending Items tab, and the case is blocked.  

- Log in as a Petitioner that is associated with at least one case
- Click on the docket number of the case
- Click on the File a document button
- Select Motion to Withdraw Counsel (filed by petitioner) document type
- Upload the document
- Click Next
- Check the box to acknowledge redaction
- Submit the document
- Next, log in as a Docket Clerk
- Click on Document QC/Section Document QC
- Find the Motion document that was just filed
- Click on the document title
- QC the document and send a message to the assigned judge or ADC
- Navigate back to the case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case header now displays that the case is blocked from trial
- [x] **NEW FUNCTIONALITY** - The Motion to Withdraw Counsel (filed by petitioner) is now displayed on the pending items tab and there is an indicator on the tracked items tab as per normal



#### 5) Petitioner paper files a Motion to Withdraw Counsel; The case that the motion was filed on has this motion on the Pending Items tab, and the case is blocked.  

- Log in as a docket clerk
- Navigate to a case that has a party that has paper service
- Click on the Create button
- Click on the Paper filing option from the dropdown
- Upload or scan a document
- Fill in the required fields
- Select Motion to Withdraw as Counsel (filed by Petitioner) from the document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is no longer a section for "Track document/Add to pending report" on the Add Docket Entry screen when Motion to Withdraw Counsel (filed by Petitioner) is selected. (check this for Motion to withdraw Counsel as well)
After serving the document:
- [x] **NEW FUNCTIONALITY** - The Case header now displays that the case is blocked from trial
- [x] **NEW FUNCTIONALITY** - The Motion to Withdraw Counsel (filed by petitioner) is now displayed on the pending items tab and there is an indicator on the tracked items tab as per normal



#### 6) Regression tests 
- [x] Docket clerk can QC pending motions (M112/M116) as per normal
- [x] Judge Users can Stamp the pending motions (M112/M116 + others) as per normal
- [x] Docket Clerk can add the stamped motion (M112/M116 + others) as per normal
- [x] Pending Motions (M112/M116 + others) display appropriately on the Pending Report.
- [x] Docket clerk can remove the pending item as per normal.
- [x] The blocked label is no longer present after pending item is removed (blocked label will only be removed if there are no pending/no deadlines/no manual block)
- [x] When filing a motion to withdraw Counsel in a consolidated group, and user files across group, Motion is captured on pending report in all cases in the group
