### ISSUE TITLE
Add empty state message when docket record filtered.

### ISSUE THREAD

**Issue by katiecissell** [ustaxcourt/ef-cms#8818]
As a dawson user, when I filter the docket record and there are no documents of that type, display an empty state message so i understand there are no documents and don't mistake it for not loading the page.

Preconditions:
none

AC:
- When there are no documents to be displayed in the docket record due to filtering, display an empty state message. "There are no documents of that type."
- Needs to work on desktop and mobile

![Image](https://github.com/user-attachments/assets/10121214-cacf-45d6-9cc6-f42fd9f55a4c)

![Image](https://github.com/user-attachments/assets/9d79753d-ec0a-409a-b624-788ab3f37710)

**Comment by ttlenard** [comment]
Testing Feedback:
- [x] When a Public DAWSON user (public user or public terminal user) filters for a document that is not on the docket record, the empty state message does not display.
          - as a public user, go to the case search page
          - type in a docket number to search for (I used 236-24)
          - Click search
          - Filter the docket record for motions
          - No empty state message displays
          - Repeat the steps above, but log in as any type of user
          - See the empty state message

![Image](https://github.com/user-attachments/assets/847b084e-30bc-4a93-aab4-d3b5b8368045)
