### ISSUE TITLE
Move User (Judge/TrialClerk) Case Notes to Postgres

### ISSUE THREAD

**Issue by pixiwyn** [ustaxcourt/ef-cms#8826]
branch off: origin/10391-dynamo-migrations-kysely-aurora-rds-tokens (till merged in)

DynamoDB Entities to Replace:

- user-case-note

convert the functions in web-api/src/persistence/dynamo/userCaseNotes to postgres kysely functions.

DynamoDB Functions to Move (unit tests can be removed):
<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2237446dd206d1e06ad339280f96d8200a0cbcf/2024-09-25_10-49-19.png" alt="2024-09-25_10-49-19.png" />

**Comment by ttlenard** [comment]
Things I tested:
- [x] Judge User can add/edit/delete a Judge Note on the Session Copy page
- [x] Judge User can add/edit/delete a Judge Note on the Case
- [x] Chambers User can add/edit/delete a Judge Note on the Session Copy page
- [x] Chambers User can add/edit/delete a Judge Note on the Case
- [x] Users outside of the Specific Judge's Chambers cannot view Judge's Notes
- [x] Sticky note icon displays appropriately when there is a Judge's note (submitted bug ustaxcourt/ef-cms#8855 as a result of testing this - issue is unrelated to this story)
- [x] Judge Notes that existed prior to this story display on Session Copy pages and on Cases
- [x] Judge/Chambers can still add formatting (spaces, indentations) to their notes and the formatting is retained when viewing in DAWSON
- [x] No character limit for Judge notes is still retained. Kaitlyn verified Postgres has a limit of somewhere around 3M
- [x] Verified with Kaitlyn that Trial Clerk notes have migrated appropriately in Postgres

Update 11/15/24
All of the above were tested again, with the addition of the following:
- [x] Trial Clerk can add/edit/delete a trial clerk note on the Session Copy page 
- [x] Connected to Postgres to verify data was migrated appropriately, Data appears to be present and query-able!
