### ISSUE TITLE
Full Spectrum Docket Sorting

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8854]
As a DAWSON user, so that I can navigate quickly to the docket entries I'm interested in, I need to be able to sort by any column on the docket record.

The time has come to implement our column sorting mechanism seen elsewhere in DAWSON (the up/down arrows w. underlining) on the docket record view for all users. This will allow everyone to customize their viewing according to their own needs/preferences.

## Acceptance Criteria
* Current "Sort By" dropdown menu is removed
* Docket record defaults to current sort order (i.e., filed date ascending)
* All columns can now be sorted ascending or descending by value:
  - No.: numerical
  - Filed Date: date
  - Event: alphabetical
  - Filings and Proceedings: alphabetical
  - Pages: numerical
  - Filed By: alphabetical
  - Action: alphabetical
  - Served: date
  - Parties: alphabetical
* When secondary sort is required, sort by Filed Date, ascending
* Filters work in conjunction with sorting
* Download selections work in conjunction with sorting 
* Sorting has no impact on visibility permissions for a given user
* Printable docket record reflects current sort order on the screen when link is selected and if user chooses to download it when downloading docket entries

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

  
*

**Comment by katiecissell** [comment]
Add sorting arrows to all columns. The one selected to sort the table will have the single arrow with the underline. This will follow existing sorting patterns in Dawson (Like in messages).  Mobile view will not be impacted by this change, it will remain sorting by its dropdown. Make sure to test that Ipads are able to use this sorting feature. (We think the ipads use the desktop view and not the mobile. If there are ipads that use the mobile view, we will need to discuss what to do with it)

![Image](https://github.com/user-attachments/assets/7402d39e-4378-4ed8-b53d-cfa72400fec2)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Case Services Supervisor views a case docket record; Sort arrows are now present on all columns.

- Log in to DAWSON
- Navigate to a case and view the docket record

Expected Results:
- [x] The default sort remains the same, filed date - oldest to newest.
- [x] **NEW FUNCTIONALITY** - The Filed date column is underlined with an up arrow, indicating that this is the active column that is sorted on.
- [x] **NEW FUNCTIONALITY** - Each column on the docket record has the up/down arrow next to the column name for sorting.



#### 2) Case Services Supervisor sorts on the "No." column; Docket record is sorted by number ascending.

- Continuing from the previous test
- Click on the "No." column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows on the Filed Date column
- [x] **NEW FUNCTIONALITY** - On the No. column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - No.'s are now in ascending order.
- [x] **NEW FUNCTIONALITY** - Clicking on the "No." column header again re-sorts the column and it is now descending with the arrow pointing down.



#### 3) Case Services Supervisor sorts on the Filed Date column; Docket record is now sorted by Filed Date ascending.

- Continuing from the previous test
- Click on the "Filed Date" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the No. column
- [x] **NEW FUNCTIONALITY** - On the Filed Date column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Filed Date is now in ascending order.
- [x] **NEW FUNCTIONALITY** - Clicking on the "Filed Date" column header again re-sorts the column and it is now descending with the arrow pointing down.



#### 4) Case Services Supervisor sorts on the Event Column; Docket record is now sorted by alphabetical (a-z) order and if necessary, there is a secondary sort by filed date (ascending).

- Continuing from the previous test
- Click on the "Event" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Filed Date column
- [x] **NEW FUNCTIONALITY** - On the Event column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Event is now in alphabetical order (a-z), and if necessary, the secondary sort is by filed date (ascending)
- [x] **NEW FUNCTIONALITY** - Clicking on the "Event" column header again re-sorts the column and it is now in z-a order, with the filed date in descending order, with the arrow pointing down.



#### 5) Case Services Supervisor sorts on the Filings and Proceedings Column; Docket record is now sorted alphabetical (a-z) order and if necessary, there is a secondary sort by filed date (ascending).

- Continuing from the previous test
- Click on the "Filings and Proceedings" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Event column
- [x] **NEW FUNCTIONALITY** - On the Filings and Proceedings column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings is now in alphabetical order (a-z), and if necessary, the secondary sort is by filed date (ascending).
- [x] **NEW FUNCTIONALITY** - Clicking on the "Filings and Proceedings" column header again re-sorts the column and it is now in z-a order, with the filed date in descending order, with the arrow pointing down. 



#### 6) Case Services Supervisor sorts on the Pages Column; Docket record is now sorted in numerical ascending (1-100+) order and if necessary, there is a secondary sort by filed date (ascending).

- Continuing from the previous test
- Click on the "Pages" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Filings and Proceedings column
- [x] **NEW FUNCTIONALITY** - On the Pages column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Pages is now in numerical ascending order (1-100+) and if necessary, the secondary sort is by filed date (ascending).
- [x] **NEW FUNCTIONALITY** - Clicking on the "Pages" column header again re-sorts the column and it is now in numerical descending (100-1) order, with the filed date in descending order, with the arrow pointing down. 



#### 7) Case Services Supervisor sorts on the Filed By Column; Docket record is now sorted alphabetical (a-z) order and if necessary, there is a secondary sort by filed date (ascending).

- Continuing from the previous test
- Click on the "Filed By" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Pages column
- [x] **NEW FUNCTIONALITY** - On the Filed By column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Filed by is now in alphabetical order (a-z) and if necessary, the secondary sort is by filed date (ascending).
- [x] **NEW FUNCTIONALITY** - Clicking on the "Filed By" column header again re-sorts the column and it is now in z-a order, with the filed date in descending order, with the arrow pointing down. 



#### 8) Case Services Supervisor sorts on the Action Column; Docket record is now sorted alphabetical (a-z) order and if necessary, there is a secondary sort by filed date (ascending).

- Continuing from the previous test
- Click on the "Action" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Filed By column
- [x] **NEW FUNCTIONALITY** - On the Action column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Action is now in alphabetical order (a-z) and if necessary, the secondary sort is by filed date (ascending).
- [x] **NEW FUNCTIONALITY** - Clicking on the "Action" column header again re-sorts the column, and it is now in z-a order, with the filed date in descending order, with the arrow pointing down. 



#### 9) Case Services Supervisor sorts on the Served Column; Docket record is now sorted date (ascending/oldest to newest) order.

- Continuing from the previous test
- Click on the "Served" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Action column
- [x] **NEW FUNCTIONALITY** - On the Served column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Served is now in date ascending order (oldest to newest).
- [x] **NEW FUNCTIONALITY** - Clicking on the "Served" column header again re-sorts the column and it is now in date descending (newest to oldest) order with the arrow pointing down.



#### 10) Case Services Supervisor sorts on the Parties Column; Docket record is now sorted alphabetical (a-z) order and if necessary, there is a secondary sort by filed date (ascending).

- Continuing from the previous test
- Click on the "Parties" column

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two arrows back on the Served column
- [x] **NEW FUNCTIONALITY** - On the Parties column, the arrow points up and the column is now underlined to indicate that this is the column that the table is sorting on.
- [x] **NEW FUNCTIONALITY** - Parties is now in alphabetical order (a-z) and if necessary, the secondary sort is by filed date (ascending).
- [x] **NEW FUNCTIONALITY** - Clicking on the "Parties" column header again re-sorts the column and it is now in z-a order with the arrow pointing down.



#### 11) Case Services Supervisor sorts the columns and then clicks on the Printable Docket Record Link; Printed version displays the docket record in current sort order.

- Continuing from the previous test
- Sort the docket record
- Click on the Printable Docket Record Link
- Click Open on the modal
- New tab opens with the printable docket record link

Expected results:
- [x] **NEW FUNCTIONALITY** - Printable docket record matches whatever sort order was selected.



#### 12) Case Services Supervisor filters the docket record by a specific document type, applies a sort; sorting and filtering display the data on the docket record appropriately.

- Continuing from the previous test
- Be sure that you are on a docket record that has multiple orders, multiple exhibits, and multiple motions
- Select a filter
- Sort each of the columns as indicated in previous test cases

Expected Results:
- [x] **NEW FUNCTIONALITY** - Docket record sorts appropriately when a document filter is applied

*Repeat this test by filtering by different document types and ensuring that sorting works appropriately with different filters.



#### 13) Case Services Supervisor sorts the columns and then selects some documents for download and includes the printable docket record in the download; selected documents are downloaded appropriately, and the printable docket record matches the sort order on the screen.

- Continuing from the previous test
- Sort the docket record
- Select all of the documents for download
- Click the download link
- Select the checkbox to indicate that you would like to include the printable the docket record
- Click the download button
- Indicate where on your computer that you would like the download to save
- When it is finished downloading, open the folder
- Review the documents

Expected Results:
- [x] Documents selected are downloaded appropriately
- [x] **NEW FUNCTIONALITY** - The printable docket record matches whatever sort order was selected.



#### 14) Case Services Supervisor sorts the columns and then edits a docket entry, data saves appropriately.

- Continuing from the previous test
- Be sure that the docket record is sorted in a different way than the default (filed date ascending).
- Click on the Edit link for one of the entries, and take note of where in the list of docket entries this entry is
- Make an edit to the docket entry
- Click save

Expected Results:
- [x] The docket record is still sorted as it was prior to the edit, and the edits are saved appropriately

*Repeat this test by Sorting and then sealing a document
- [x] The docket record is still sorted as it was prior to the seal, and the seal level is saved appropriately



#### 15) Repeat Test cases 1-13 above with all user types to ensure sorting works appropriately for all DAWSON users.

Internal Court users
- [x] ADC
- [x] Admissions Clerk
- [x] Chambers
- [x] Clerk of the Court
- [x] Floater
- [x] Docket Clerk
- [x] General
- [x] Judge
- [x] Petitions Clerk
- [x] Reporters Office
- [x] Trial Clerk

External
- [x] IRS Practitioner
- [x] Petitioner
- [x] Private Practitioner
- [x] DOJ Practitioner

Public
- [x] Non-logged in user
- [x] Terminal user



#### 16) Regression test accessing the case docket record on a mobile device; no changes to existing mobile view.

- [x] This test passes.

**Comment by swongCO** [comment]
### UX feedback

- [x] No sort is indicated when the page first loads (see Messages for reference)
- [x] Printable pdf: some columns are not displaying data

![Image](https://github.com/user-attachments/assets/3eb5cbd7-e1a8-4e13-bc40-a4b41af381e0)
___
When the browser window is reduced to ~575px:
- [x] the sort dropdown is still displaying
- [x] data is not displaying in some columns - see staging screenshot for correct behavior

Test behavior:
![Image](https://github.com/user-attachments/assets/49b91399-1f03-4b38-8fa6-225c245f7536)
![Image](https://github.com/user-attachments/assets/9dd2d327-104d-45db-b9f3-1dea4937ea80)

Correct staging behavior:
![Image](https://github.com/user-attachments/assets/b1175a00-53a7-4bda-83f7-e6600b085010)

**Comment by ttlenard** [comment]
@nechama-krigsman @cruzjone-flexion 

Testing Feedback
- [x] Test Case 15 - Ability to sort the docket record isn't available for the following users:
     - [x] Public non-logged in user
     - [x] Terminal user

This is what I am currently seeing for non-logged in users: 

![Image](https://github.com/user-attachments/assets/1895fe1f-a308-4782-b1d7-5d5a39d857fa)

**Comment by ttlenard** [comment]
Testing Feedback

@nechama-krigsman @cruzjone-flexion 

Test case 16 does not pass.  On mobile, the "Sort by" box is present as per normal, but on Test when I choose a different selection other than the default "Oldest", the selection doesn't update. The docket record IS sorting appropriately, but the option that the user selected does not update, and "Oldest" stays checked and displayed in the dropdown. I tested this against Production, and it works appropriately on Production. See screen grabs below from both android and iOS device on Test.

Android device - notice that "Oldest" is selected, but the docket record is actually sorted by newest. The same thing happens with any of the selected sort by options.
![Image](https://github.com/user-attachments/assets/063dea8c-4999-46a2-8efc-39cb8be0e2b3)



iOS device - notice that "Oldest" is selected, but the docket record is actually sorted by newest. The same thing happens with any of the selected sort by options.
![Image](https://github.com/user-attachments/assets/d6ecaf44-6449-41a1-a4a9-c56064563507)
