### ISSUE TITLE
Casing of words is not consistent

### ISSUE THREAD

**Issue by swongCO** [ustaxcourt/ef-cms#8862]
As a Dawson user, so that I am not distracted by little things, I need the casing of words to follow existing patterns.

There are a few areas where the casing of words don't follow the existing patterns.

### Acceptance Criteria:
* Fix the casing of words as indicated below
* Determine if user documentation needs to be updated (Tenille): Y / N

1. Trial Sessions page - hover tip for swing sessions icon: capitalize the first s
![Image](https://github.com/user-attachments/assets/29ea5c8f-6b5e-4170-88f1-77304542abc7)

2. Petitioner efiling flow step 1 - name field: lower case n in Name
<img src="https://github.com/user-attachments/assets/b5532f70-cec5-4da7-9138-0faaa891eabe" width="500">

3. Address form fields - Zip code label: capitalize all letters in Zip (apply to all instances of zip code labels)
![Image](https://github.com/user-attachments/assets/040f0154-5178-4c07-8ec7-a7e2aad28e61)

4. Docket Record icon hover tips: capitalize first letter of the first word
![Image](https://github.com/user-attachments/assets/24b86361-0516-455f-8a35-6e267a424e33)
![Image](https://github.com/user-attachments/assets/1cccfa36-edfa-40f5-b5d2-c9b06bbdfc20)
![Image](https://github.com/user-attachments/assets/4cc536ec-ac18-4e08-bd51-15f0ab7fd5ab)

5. Message Inbox: capitalize first letter of the first word
![Image](https://github.com/user-attachments/assets/1fc82c6b-11ec-4740-a66e-eb6b161a117c)

6. Document QC Inbox: capitalize first letter of the first word
![Image](https://github.com/user-attachments/assets/f18efee8-3508-42f3-9592-175eca71148e)

**Comment by btejha** [comment]
@swongCO would you like updated as well, when you hover over the message icon ?

 ![Image](https://github.com/user-attachments/assets/e4a733e4-3b8c-4587-8d0b-6ccc79100be9)

**Comment by swongCO** [comment]
### UX feedback

- [ ] Swing session is still displaying with incorrect casing
![Image](https://github.com/user-attachments/assets/a455fee4-3c73-4550-8e4c-17f3c4b3ad63)
