### ISSUE TITLE
Session Copy - Session Notes card: change styling to match other note cards

### ISSUE THREAD

**Issue by swongCO** [ustaxcourt/ef-cms#8873]
As a judge or CA, so that I have a consistent experience in DAWSON, I need the Session Notes card to look like other note cards.

### Description
The styling of the Session Notes card is different than all other note cards.

### Acceptance Criteria
* Match the styling of existing note cards for empty and non-empty states
* Move the links to match the existing note cards
* Determine if user documentation needs to be updated (Tenille): Y / N

Session Notes card:
![Image](https://github.com/user-attachments/assets/ff0dcbb5-2d3a-49a2-9374-d8fcbe911392)
![Image](https://github.com/user-attachments/assets/83099941-45e4-4369-9ef5-6e54a19c7175)

Existing note cards:
![Image](https://github.com/user-attachments/assets/373abd10-3bdb-430d-83a4-628163ff1430)

**Comment by mwestereng1** [comment]
**UX Feedback:**

Stack the two cards when resisizing the window. Wrapping of the links above the "Session Notes" header is existing behavior.

![Image](https://github.com/user-attachments/assets/a870557f-4ef0-450b-bc93-caa7d3717354)

Example of cards stacked from Docket Notes tab:
![Image](https://github.com/user-attachments/assets/2cc5eed2-81a8-4025-ad83-05e3da2605ff)

**Comment by swongCO** [comment]
Found an odd instance where extra space is added to the bottom of the assignments card and session notes card. Upon digging further, it looks like it's happening in swing sessions only. The extra space is present in both the Session Info and Session Copy pages.

- [ ] Remove added spacing at the bottom of the assignments and notes card
- [ ] Ensure the change is applied to both Session Info and Session Copy pages

![Image](https://github.com/user-attachments/assets/c8fa736b-135c-4ba9-93bf-50a3ac549d27)

![Image](https://github.com/user-attachments/assets/c79d99d9-bb8f-415d-aa78-708ab0243218)

**Comment by btejha** [comment]
Thank you for pointing this out! I’ll work on removing the extra spacing at the bottom of the assignments and notes cards. I’ll make sure the fix is applied consistently to both the Session Info and Session Copy pages. Appreciate the detailed notes!
