### ISSUE TITLE
Electronic Service Reliability Improvement

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#901]
## Pre-Conditions

Environment with cases and parties attached to the case

## Acceptance Criteria

* As the sysadmin of the Court, in order to better fulfill the Court's legal obligation of serving documents, I need API requests that initiate service to offload heavy lifting to other Lambdas dedicated to building PDFs or serving email.
* As the Court itself, in order to only serve documents when they are ready, I need the order of operations to be well-defined and followed: documents are prepared first, and then Email service is attempted, and finally the docket entry's state reflects the result of attempt.
* As a Court user serving documents, in order to know when my attempt to serve a document is in progress, has completed or has failed, I need the system to keep me informed.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

This will likely need to be broken up into stories for the various types of documents that we serve; however, they should all make use of some shared logic or infrastructure for building documents and sending email.

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by JessicaMarine** [comment]
Jessica added to Flexion's backlog: https://github.com/flexion/ef-cms/issues/8039
