### ISSUE TITLE
Ensure no duplicate service

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#902]
## Acceptance Criteria

* As a Court User, so that I don't add confusion by serving parties two (or more) times for documents or petitions, my first attempt to serve a document should prevent subsequent attempts.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

Somehow, a petitions Clerk was able to serve the IRS a new petition. Perhaps it was a double click, perhaps they had the case open in two tabs. 

They initiated two identical API requests within the course of 2.5 seconds to `/cases/14831-20/serve-to-irs`

* Mar 2, 2021 @ 08:56:41.241
* Mar 2, 2021 @ 08:56:43.719

These identical requests went about their business and did what they were supposed to do.

The first thing these handlers need to do is to prevent an identical request coming in. it would lock the case/document while it performs its task. And then hopefully leave it in a state where it cannot be served again. 

Both requests were running concurrently a they ended:

* Mar 2, 2021 @ 08:56:45.819
* Mar 2, 2021 @ 08:56:50.334

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by JessicaMarine** [comment]
Jessica added to Flexion's backlog: https://github.com/flexion/ef-cms/issues/8040
