### ISSUE TITLE
Inventory and ride-along with deployments.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#922]
As one of the first steps to #911, doing research on the current state of deployments would be a great place to start! 

Potential tasks:

- Create group of developers who commonly run deploys for both Flexion and the Court.
- For each developer:
    - Run a complete deploy, including any local setup needed for manual account and environment-specific deployment steps, a migration, and color switching.
    - Have another developer document every action, if action succeeds or fails on first try, and how long each step takes.
- Synthesize notes together to understand the most complicated, longest-running, and trickiest deployment steps to indicate where and how automation would be best applied.

**Comment by mmarcotte** [comment]
- document the process of a deployment as you go, like a train/ducks in a line
- use color coded manual/automatic
- identify pain points

**Comment by mmarcotte** [comment]
possibly involve Corey & Kristen to help improve the user experience for the deployment process, too.
