### ISSUE TITLE
BUG: Missing PDFs

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#933]
**Describe the Bug**
Docket No. 4647-02L (there are images for index #1-15, but no images for #16-25).

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod

**Who were you logged in as?**
Fig Ruggieri

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 4647-02
2. Note that there are no PDFs attached to entries #16-25

**Expected Behavior**
* PDFs should be attached to all entries, when appropriate

**Actual Behavior**
* Entries #16-25 are missing

**Screenshots**
![image](https://user-images.githubusercontent.com/40871081/111790139-45a85b80-8898-11eb-8864-5c59ecacea45.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by mark-meyer** [comment]
I looked in the migration database and these documents are not there either. I sent a note to Mike McVicker -- maybe he has some knowledge or context that will help.

**Comment by mmarcotte** [comment]
Are there other cases where this might be a problem?
- could search ES for docket records that have mixed results for `isFileAttached` and `!isFileAttached`
- might be in a different pool of PDFs in Blackstone

Did we find if these documents existed in Blackstone?

**Comment by JessicaMarine** [comment]
Loretta believes that everything after January 1, 2005 should be scanned in.  She is confirming date.

**Comment by JessicaMarine** [comment]
@mark-meyer Loretta confirmed that all docket entries after 1/1/2005 should have a PDF attached. Since all of the entries on 4647-02 that are missing PDFs pre-date 1/1/2005, I think this is correct.  We can probably close this issue.

**Comment by mmarcotte** [comment]
would not expect the PDFs to be there because they pre-date 1/1/2005; this issue can be closed. work is covered in another ticket.
