### ISSUE TITLE
Figure out the scope of the Missing PDF problem

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#958]
Jessica to give a date to Mark to help find the cutoff for when the Court went electronic.
Mark to try to look up cases where docket records are incomplete (mixture of `isFileAttached` and `!isFileAttached`)

**Comment by JessicaMarine** [comment]
Related to #933.  Loretta thinks everything on and after 1/1/2005 should have PDF.  She is confirming date.

**Comment by JessicaMarine** [comment]
@mark-meyer Loretta confirmed that all docket entries after 1/1/2005 should have a PDF attached.

**Comment by mmarcotte** [comment]
We are looking for the dispositive documents. Cannot find them. 

Looking in the Migration SQL Server Tables. In PDF Dockets All. Just no row in the table for the ones we're trying to find. 

1/1/2005 is the served date

**Comment by mark-meyer** [comment]
After scanning the PDFs for the roughly 20k cases with missing documents, most did not exist in the PDF table provided by Mike McVicker. Documents were found for around 70 cases. Of these  roughly 30 were conformed decisions, the rest had signatures.

**Comment by mmarcotte** [comment]
No longer a DAWSON problem; records issue
